### ISSUE TITLE
数据新增

### ISSUE THREAD

**Issue by kl720** [zhangdaiscott/jeecg-boot#10]
数据新增时，使用了DictSelectTag设置几个字典字段，无法获取字典选择的值，保存失败

**Comment by zhangdaiscott** [comment]
描述有点简单，把代码贴出来

**Comment by kl720** [comment]
> 描述有点简单，把代码贴出来
我截了个图，看说得清楚不
![1](https://user-images.githubusercontent.com/3956096/53802982-3fc7d200-3f7e-11e9-9c3c-3fac8b144097.png)
![2](https://user-images.githubusercontent.com/3956096/53802988-435b5900-3f7e-11e9-9429-f3c8f2cb82b4.png)

**Comment by zhangdaiscott** [comment]
收录，我们尽快解决

**Comment by zhangdaiscott** [comment]
已改，下个版本发布
