### ISSUE TITLE
用戶登录后又自己的退出问题  急急

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#100]
本人用的是sql sever2008数据库
1、本人检查方法，代码连mysql登录测试正常
2 sql sever2008数据库 就出现 登录后退出问题   本人吧mysql的数据多重新创建一遍到sqlserver
3 debug 走LoginControlle程序  login方法 正常，
4 sqlserver 数据连接是按 Jeecg-Boot 技术文档 V1. Oracle/SQL server数据库切换 配置 谢谢 ，

1登录退出前台界面
![V1X0I TX8XATR3DJDT87CXP](https://user-images.githubusercontent.com/5210084/57420553-a5fcf980-723a-11e9-9edd-385b6e72d56d.png)

2登录退出控制台界面
![image](https://user-images.githubusercontent.com/5210084/57420605-dc3a7900-723a-11e9-8d07-f57603577823.png)
3 redis 启动正常
![image](https://user-images.githubusercontent.com/5210084/57420622-e78da480-723a-11e9-8a49-6e634cf6f43d.png)

**Comment by zhangdaiscott** [comment]
兼容性可能有问题，下个版本，我们会发布兼容多数据库的脚步

**Comment by shaowen** [comment]
感谢你们的框架的帮助，感谢你们的回答
