### ISSUE TITLE
Online表单开发表描述无法同步到数据库

### ISSUE THREAD

**Issue by junjie124** [zhangdaiscott/jeecg-boot#1002]
##### 版本号：
jeecg-boot 2.1.4
mysql 5 .7
##### 问题描述：
Online表单开发时，“表描述”无法同步到数据库表的注释

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
表名备注同步意义不大
