### ISSUE TITLE
首次打开一对多表单，JEditableTable的addDefaultRowNum属性不生效

### ISSUE THREAD

**Issue by 553036892** [zhangdaiscott/jeecg-boot#1003]
##### 截图&代码：

     dataSource: {
        immediate: true,
        handler: function (newValue) {
          if(newValue.length == 0){//不执行下面代码就没问题
            return
          }
          // 兼容IE
          this.getElementPromise('tbody').then(() => {

            this.initialize()

            省略。。。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，我们确认下

**Comment by bill74s** [comment]
是否和那个删除的问题一样啊

**Comment by 553036892** [comment]
打断点看是空行已经添加了，然后又没了，就把这过程叫做删除了。

**Comment by sjlei** [comment]
确实是因为预添加的行又被删了

由于`this.getElementPromise` 方法是异步的，所以有可能导致预添加的行在该方法之前运行

![image](https://user-images.githubusercontent.com/34293221/76585348-1c345180-6519-11ea-95f2-3dab185a07a4.png)

而在 `then` 方法里又会清空 `rows` ，也就是删除所有行

![image](https://user-images.githubusercontent.com/34293221/76585326-12125300-6519-11ea-8a84-0a96084eed4e.png)

我加了个判断就好了

![image](https://user-images.githubusercontent.com/34293221/76585578-ada3c380-6519-11ea-8f07-2fd9bb5579f7.png)

该功能下个版本发布后修复，在此之前可以按照上图的代码修改

**Comment by sjlei** [comment]
![image](https://user-images.githubusercontent.com/34293221/76585785-3f133580-651a-11ea-926d-913a482217e4.png)

**Comment by 553036892** [comment]
还有个问题，首次打开，JEditableTable下拉框选项，没有加载出来，要在随便输入框填一下，下来选项才加载出来

**Comment by sjlei** [comment]
> 还有个问题，首次打开，JEditableTable下拉框选项，没有加载出来，要在随便输入框填一下，下来选项才加载出来

上图的代码里确实有这个问题，我那样改之后导致存值的变量不是响应式的了，所以无法及时更新视图，改成下面这样就好了

![image](https://user-images.githubusercontent.com/34293221/76676970-b375d380-6603-11ea-9175-60aa425f0f30.png)

**Comment by sjlei** [comment]
@553036892 你要是说 checkbox 或者 select 选不上确实有这个问题，采用我刚发的代码就能解决。但是下拉选项没有加载出来这个问题倒是没有复现
