### ISSUE TITLE
关于新增用户部门绑定的BUG

### ISSUE THREAD

**Issue by Chenghaogithub** [zhangdaiscott/jeecg-boot#1005]
##### 版本号：
2.1.4

##### 问题描述：
1.新增用户并绑定部门后，sys_user表中org_code字段值是空的，只会在新增后再编辑后才会有值，**如图（1）**。通过debug发现新增的时候，页面传过来的参数“selecteddeparts”是空的，**如图（2）.**
2.通过编辑用户信息之后，sys_user表中org_code的值是机构名称，并不是我们想要的对应的机构编码，**如图（3）**
##### 截图&代码：

**1.**
![1](https://user-images.githubusercontent.com/34958055/76643131-766ff980-658f-11ea-97cd-0a36dee50853.png)
**2.**
![2](https://user-images.githubusercontent.com/34958055/76643283-b636e100-658f-11ea-9a58-b56c3e78b369.png)
**3.**
![3](https://user-images.githubusercontent.com/34958055/76643301-bdf68580-658f-11ea-97eb-4ad18675d315.png)
**部门截图**
![QQ截图20200314010455](https://user-images.githubusercontent.com/34958055/76643366-dc5c8100-658f-11ea-94e6-64204b3569bf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用户部门关系用的不是
sys_user表中org_code字段

这个是保存登录选择的那个部门
