### ISSUE TITLE
poi导出 如果字段里面是字典  导出翻译成对应文字 这个功能是否提供了  例如sex字典数据

### ISSUE THREAD

**Issue by DexSinis** [zhangdaiscott/jeecg-boot#1006]
##### 版本号：
 2.1.4

##### 问题描述：
poi导出 如果字段里面是字典  导出翻译成对应文字 这个功能是否提供了  例如sex字典数据或者状态字典

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14175683/76677278-64ca3880-6607-11ea-97c2-b31f6b4c2199.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/76724359-b4367300-6785-11ea-9304-f848f092d7a5.png)
   @Excel(name = "状态", width = 15,dicCode="user_status")
