### ISSUE TITLE
新建自定义表单菜单无法访问

### ISSUE THREAD

**Issue by yutao929** [zhangdaiscott/jeecg-boot#1007]
##### 问题描述：
通过在线开发-online表单开发的新表单，然后在系统管理-菜单管理把新开发的表单加到在线开发下面作为子菜单，然后在角色管理里为当前角色配置该新菜单的权限，然后刷新页面，在在线开发下面点击该新菜单，提示“很抱歉，资源未找到”，页面一直停留在刷新状态无法展示内容。

##### 截图&代码：
这里怎么放入截图？
“很抱歉，资源未找到”

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1293035

**Comment by Fxiao1** [comment]
> http://doc.jeecg.com/1293035

抱歉，您提供的地址404了
