### ISSUE TITLE
打成jar包，访问不到代码生成器模板

### ISSUE THREAD

**Issue by jiuhua142** [zhangdaiscott/jeecg-boot#1010]
##### 版本号：
2.1.4

##### 问题描述：
不打jar包，可以成功生成代码
打成jar包，访问不到代码生成器模板
   /java/jeecg-boot-module-system-2.1.4.jar!/BOOT-INF/classes!/jeecg/code-template-online does not exist. 
jar包，可以找到模板

##### 截图&代码：

![jar](https://user-images.githubusercontent.com/43517440/76735277-89591880-679f-11ea-8762-e0e4386cd066.png)
![jar (2)](https://user-images.githubusercontent.com/43517440/76735432-df2dc080-679f-11ea-8f28-fcc87b571031.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已出对应方案，下个版本发布
