### ISSUE TITLE
/online/cgform/api/exportXls/{code}接口问题

### ISSUE THREAD

**Issue by qazjiangchuan** [zhangdaiscott/jeecg-boot#1012]
##### 版本号：
hibernate-re:5.2.13

##### 问题描述：
/online/cgform/api/exportXls/{code}
这个接口，好像是传时间范围的时候，无论begin还是end 都会解析成 >= 导致数据不准确。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18412718/76738514-c1635a00-67a5-11ea-9fbb-593f494dd69f.png)
![image](https://user-images.githubusercontent.com/18412718/76738556-d7711a80-67a5-11ea-8990-95129d172a74.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by qazjiangchuan** [comment]
问题应该是在这里

else {
                    Object var11 = var2.get(var7 + "_begin");
                    if (var11 != null) {
                        var3.append(" AND " + var7 + ">=");
                        if (org.jeecg.modules.online.cgform.c.f.a(var8)) {
                            var3.append(var11.toString());
                        } else {
                            var3.append("'" + var11.toString() + "'");
                        }
                    }

                    Object var12 = var2.get(var7 + "_end");
                    if (var12 != null) {
                        var3.append(" AND " + var7 + ">=");
                        if (org.jeecg.modules.online.cgform.c.f.a(var8)) {
                            var3.append(var12.toString());
                        } else {
                            var3.append("'" + var12.toString() + "'");
                        }
                    }
                }

**Comment by zhangdaiscott** [comment]
已经发现，下个版本发布
