### ISSUE TITLE
切换不同角色登录时，会跳转到上一个角色的路径页，新角色没权限会进入404

### ISSUE THREAD

**Issue by weixingqi** [zhangdaiscott/jeecg-boot#1019]
##### 版本号：最新版本
查看了最新版本的permission.js，会有一样的问题。

##### 问题描述：

切换不同角色登录时，会跳转到上一个角色的路径页，新角色没权限会进入404。
根据排查定位到问题在permission.js里
##### 截图&代码：

![image](https://user-images.githubusercontent.com/33211372/77132899-1354fa00-6a9c-11ea-81f2-ebb6dfbfea55.png)
如图，redirect会获取到上一个角色遗留的路径，

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 2428552874** [comment]
请问这个问题如何解决的？我也遇到了相同的问题
