### ISSUE TITLE
前端页面接入外部链接

### ISSUE THREAD

**Issue by tony2y** [zhangdaiscott/jeecg-boot#102]
请问一下，项目中前端类似于Swagger接口页面，druid数据监控页面。这种外部链接在VUE中怎么实现。

**Comment by ileadall42** [comment]
@tony2y 请看路由菜单定义，组件有iframe。

**Comment by tony2y** [comment]
在 router.config.js 文件中没有看到，或者是在其它地方进行设置的吗

**Comment by ileadall42** [comment]
你全局搜索 pagelayout iframe 两个关键词 任意一个，然后看看常见案例的百度页面是怎么实现的。

**Comment by tony2y** [comment]
好的 谢谢
