### ISSUE TITLE
配置 Href 跳转，并没有显示为超链接

### ISSUE THREAD

**Issue by ddwolf715** [zhangdaiscott/jeecg-boot#1020]
##### 截图&代码：
图1：
Href配置为/online/cgformList/4396792436db444d8ee0d1ec9068160e?src_system_id=${id}
也使用https://www.baidu.com 测试了，也是不行
![image](https://user-images.githubusercontent.com/17849555/77138925-da725080-6aae-11ea-8b3c-099b9153f8cb.png)
图2：
功能测试时，并没有显示为超链接
![image](https://user-images.githubusercontent.com/17849555/77139031-52d91180-6aaf-11ea-8604-870d67eb6560.png)
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有bug，下个版本修复
