### ISSUE TITLE
@jeecg/antd-online-re 组件不能按需加载

### ISSUE THREAD

**Issue by yuancongcong** [zhangdaiscott/jeecg-boot#1022]
##### 版本号：
2.1.3

##### 问题描述：
组件加载太慢，有2M多，不能单个组件加载

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以参考改造
https://github.com/sendya/ant-design-pro-vue/blob/1.2.0/docs/load-on-demand.md
