### ISSUE TITLE
handledetail无法使用，即详情页面依然可以编辑

### ISSUE THREAD

**Issue by Aimn** [zhangdaiscott/jeecg-boot#1027]
##### 版本号：

最新版本号
##### 问题描述：
online自动生成代码，配置好以后，配置详情按钮，点击详情进入handledetail方法，但是modal依然可以点击输入，与方法设计的不可点击有冲突。
在online表单开发里面使用功能测试生成的auto表单的详情页不可点击。

##### 截图&代码：
<a @click="handleDetail(record)">详情</a>
通过online表单自动生成的代码，自己配置好的业务页面
![image](https://user-images.githubusercontent.com/8426734/77503796-7deda780-6e99-11ea-9b8b-5e35f0df3e77.png)
![image](https://user-images.githubusercontent.com/8426734/77503807-86de7900-6e99-11ea-8f4c-044d283dd2dc.png)

通过online表单生成的auto表单页面
![image](https://user-images.githubusercontent.com/8426734/77503892-c6a56080-6e99-11ea-8de5-62274a041425.png)
![image](https://user-images.githubusercontent.com/8426734/77503906-d02ec880-6e99-11ea-8151-a39914eac7bf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Aimn** [comment]
JeecgListMixin里面的handledetail方法是    
handleDetail:function(record){
      this.$refs.modalForm.edit(record);
      this.$refs.modalForm.title="详情";
      this.$refs.modalForm.disableSubmit = true;
    },

而OnlCgFormAutoList里面的方法是
      handleDetail(record){
        this.$refs.modal.detail(this.formTemplate,record.id);
   }

**Comment by tygithub1** [comment]
代码生成器没有处理handleDetail，要想自己处理，
1.弹窗页面vue data里面声明 disableSubmit：false
2.在每个表单元素上加  :readOnly="disableSubmit"  但是这里需要注意的是，并不是每个组件都是可以通过设置readOnly实现不可编辑，详见具体组件的使用手册

**Comment by zhangdaiscott** [comment]
简单实现开发表单禁用方案
使用 <j-form-container :disabled="true"> 通过参数disabled

参考示例：
![image](https://user-images.githubusercontent.com/3162115/78453506-bb85d800-76c4-11ea-9411-682a39de8f88.png)
