### ISSUE TITLE
在线 的online报表报错

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1029]
##### 版本号：

2.1.4
##### 问题描述：

在线 的online报表，点击解析以后报错。之前2.1.3还是好的。这个sql我在Navicat里面执行是没有问题的
##### 截图&代码：

![image](https://user-images.githubusercontent.com/58909486/77512552-39b8d200-6eae-11ea-84c3-1aa340e7c74e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块有bug，近期会发布新版
