### ISSUE TITLE
上传多张图片，只回显了一张.

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#103]
![image](https://user-images.githubusercontent.com/27263086/57507677-028f1000-7332-11e9-9a5b-b57e12bf9b66.png)
![image](https://user-images.githubusercontent.com/27263086/57507713-218da200-7332-11e9-8095-0bf30ede0dbd.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
这个demo代码有bug,图片上传组件 antd-vue 官方是有的，也有预览的例子，不同场景下的示例很多，请看官方文档：[地址](https://vue.ant.design/components/upload-cn/)

**Comment by zhangdaiscott** [comment]
已经改，下个版本发布
