### ISSUE TITLE
在线报表和在线online的问题

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1030]
##### 版本号：
2.1.4

##### 问题描述：

还是关于在线报表和在线online的问题。
我发现在online中使用pop组件，然后配置了
字典Table
字典Code
字典Text
我发现如果
字典Code
字典Text这里面字段如果太多了。那么online功能测试，点开表单，页面布局回错乱。但是如果字段少一点就正常。如下图所示
##### 截图&代码：
![image](https://user-images.githubusercontent.com/58909486/77543755-152b1d00-6ee3-11ea-84c5-05aab7733d16.png)
![image](https://user-images.githubusercontent.com/58909486/77543757-152b1d00-6ee3-11ea-8b8a-8240cfedf045.png)
换成四个字段以后，显示正常如下：
![image](https://user-images.githubusercontent.com/58909486/77543814-2a07b080-6ee3-11ea-95ec-2e1d2bdfd07d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，我们确认下

**Comment by COMAC919** [comment]
> 好的，我们确认下

是否存在问题？或者有没有修复的计划

**Comment by tygithub1** [comment]
确认存在此问题，已修复！
