### ISSUE TITLE
jeecg-boot修改名称后无法使用online表单开发,一直报404

### ISSUE THREAD

**Issue by 385219784** [zhangdaiscott/jeecg-boot#1032]
##### 截图&代码：以下是请求路径,已经变成了更改名称后的路径,但是
http://localhost:3000/xhm-boot/online/cgform/head/list?_t=1585210841

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44

**Comment by JackRenDeveloper** [comment]
按照相应的办法修改后无效

**Comment by zhangdaiscott** [comment]
index.html后台的接口地址改了吗
