### ISSUE TITLE
代码生成器无法用自定id作为主键策略

### ISSUE THREAD

**Issue by Hachiko-JQ** [zhangdaiscott/jeecg-boot#1033]
##### 版本号：
2.1

##### 问题描述：
数据库主键是用自增id，但是代码生成器生成的entity主键注解为@TableId(type = IdType.UUID)，导致insert的时候报id无法设置成uuid，后来手动修改IdType为AUTO就没问题了，一般表结构主键都习惯用语自增id，而且性能远远高于uuid。

##### 截图&代码：
[图片]

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经规划，后面会实现

**Comment by zhangdaiscott** [comment]
目前暂时可以生成代码后，手工调整

**Comment by darellwu** [comment]
/**id*/
	@TableId(type = IdType.AUTO)
    @ApiModelProperty(value = "id")
    private java.lang.Integer id;

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0

两个修改成自增 id 的配置，改了都没起作用，
还是报：
### Cause: java.sql.SQLException: Incorrect integer value: 'ff808181718b53f801718b53f8d30000' for column 'id' at row 1
还是 uuid

**Comment by qq471754603** [comment]
这个问题很实际

**Comment by yejianmail** [comment]
希望能支持主键类型选择

**Comment by zhangdaiscott** [comment]
归集到问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1312
