### ISSUE TITLE
多表数据导出 报错

### ISSUE THREAD

**Issue by lhhlzz** [zhangdaiscott/jeecg-boot#1034]
##### 版本号：
jeecg-boot  2.0

##### 问题描述：
导出的时候 自己实体类定义的  字段需要导出
系统会默认去表里面查这个字段 但是我表里面没这个字段  所以一直报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/62694187/77630262-b074ce80-6f85-11ea-8643-5d7951c8284e.png)

![image](https://user-images.githubusercontent.com/62694187/77629960-4ceaa100-6f85-11ea-9016-56a54a647738.png)

![image](https://user-images.githubusercontent.com/62694187/77630053-6db2f680-6f85-11ea-9b33-56fb9bdbb92d.png)

![image](https://user-images.githubusercontent.com/62694187/77630152-8de2b580-6f85-11ea-9d7a-c76cf2b13d24.png)

（提交的图片报错）
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
mybatis的错吧加
 @TableField(exist = false) 
https://blog.csdn.net/zhuzejiang/article/details/101430500

**Comment by lhhlzz** [comment]
这样的话&nbsp; 我自定义的辅助字段&nbsp; 数据没这个字段&nbsp; 但是&nbsp; 也想导出 是不是 就没办法导出了


比如：我表里面 只要userId 但是我通过关联用户表查出来userName&nbsp; 返回到这个实体里面&nbsp; &nbsp;加上@TableField(exist = false) 那我这个userName 就没办法导出了&nbsp;


还有： 这个框架的导出功能是不是&nbsp; 只能导出单表？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 上午9:30
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"李正"<1065764568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 多表数据导出 报错 (#1034)





 
mybatis的错吧加
 @TableField(exist = false)
 https://blog.csdn.net/zhuzejiang/article/details/101430500
