### ISSUE TITLE
vue页面组件继承菜单数据权限问题

### ISSUE THREAD

**Issue by lch245298** [zhangdaiscott/jeecg-boot#1035]
##### 问题描述：
vue页面a中访问后台controller list
vue页面b用a做组件，分配菜单定义数据权限 state=0
vue页面c用a做组件，分配菜单定义数据权限 state=1
给同一角色分配菜单b和c，页面b和c数据权限不能相互独立，数据都是空的
若分配a和b，a和b显示的是state=0的数据
若分配a和c，a和c显示的是state=1的数据
后台list方法上加了  @PermissionData
问：有没有比较适合不同菜单 同一页面 不同数据权限的方式

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62693683/77708465-24a18780-7003-11ea-951b-919a8520735d.png)

**Comment by zhangdaiscott** [comment]
你可以通过参数做成两个菜单配置
