### ISSUE TITLE
前端项目如何新建项目名称

### ISSUE THREAD

**Issue by qinguabao** [zhangdaiscott/jeecg-boot#1040]
前端项目如何新建项目名称？

##### 问题描述：
前端项目如何新建项目名称？在nginx html目录，新建一个文件夹test ，然后将前端打包的 dist 下的文件放入到 nginx /html/test/ ，直接访问 127.0.0.1:80/test ，浏览器控制台会报错，取的资源文件都是test目录上一级的。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273922
