### ISSUE TITLE
浏览器的最低版本

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1041]
##### 版本号：

2.1.4
##### 问题描述：

麻烦咨询一下，该版本对浏览器的最低版本有什么要求吗？比如谷歌，IE还有fox之类的？
##### 截图&代码：

如上

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
ie11+ 谷歌 火狐 版本应该不限制
