### ISSUE TITLE
J-pop组件

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1043]
##### 版本号：
2.1.4

##### 问题描述：
我在自己的vue中引用J-pop组件，但是测试的时候只能选择单条记录。但是使用online配置的pop组件却可以选择多条。同时我把对应表单下载代码后配置出来的也是只能选择单条。请问是怎么回事？能否设置可以选择多条？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58909486/77983785-6fdcd280-7342-11ea-8ece-fdf52d953c4b.png)
![image](https://user-images.githubusercontent.com/58909486/77983816-82efa280-7342-11ea-94e3-a423573f4ead.png)
![image](https://user-images.githubusercontent.com/58909486/77983922-c77b3e00-7342-11ea-8d9f-5c6fe8781de9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个需要改造JPopup.vue 支持多选

**Comment by COMAC919** [comment]
> 这个需要改造JPopup.vue 支持多选

这个组件都没有开源，怎么改造啊。但是我看online上面是可以多选啊。希望更新一下把，支持设置单选多选，毕竟这个组件用得比较多。

**Comment by zhangdaiscott** [comment]
已改，下个版本发布

**Comment by darellwu** [comment]
不单不能多选，还不能回选，请问下个版本什么时候发布呢？

**Comment by JocoChen** [comment]
JPopup.vue 组件2.2.0版本 无法进行模糊查询，能否将查询功能改造为模糊查询，或者开源一下JPopup.vue
