### ISSUE TITLE
点击j-popup,里面有数据，如果选择同名的数据，文本框为空

### ISSUE THREAD

**Issue by HeAvenLinH** [zhangdaiscott/jeecg-boot#1044]
##### 版本号：
2.1.4

##### 问题描述：
j-popup里面已经选择了数据，如果再点击j-popup，选择同名的数据，回调之后文本框变成空

##### 截图&代码：
1.
![image](https://user-images.githubusercontent.com/12153749/77985229-72412b80-7346-11ea-9346-390bdb64cfb8.png)
2.
![image](https://user-images.githubusercontent.com/12153749/77985248-86852880-7346-11ea-806b-845e2155c532.png)
3.点击确认之后
![image](https://user-images.githubusercontent.com/12153749/77985268-943aae00-7346-11ea-9d4f-6d76e37a52ec.png)
4.代码
![image](https://user-images.githubusercontent.com/12153749/77985303-ad435f00-7346-11ea-95c9-ee7b1d87969a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个是个bug，已经修复了，下个版本发布
