### ISSUE TITLE
online报表配置，表单错误

### ISSUE THREAD

**Issue by HeAvenLinH** [zhangdaiscott/jeecg-boot#1046]
##### 版本号：
2.1.4

##### 问题描述：
生产环境下，报表SQL解析及动态报表配置明细都有问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12153749/78017708-42624a00-737f-11ea-9abd-3f3d99e656ec.png)

![Uploading image.png…]()

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
第二张图看不见

**Comment by HeAvenLinH** [comment]
已经完成了，ng配置问题
