### ISSUE TITLE
附表使用popup弹出框，滚动条消失

### ISSUE THREAD

**Issue by ddwolf715** [zhangdaiscott/jeecg-boot#1049]
##### 版本号：
2.1.4

##### 问题描述：
附表使用了popup弹出框，生成代码后，滚动条没有了，变成如下图，字段都被挤成一堆了。
不使用popup弹出框，则没有问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17849555/78089982-767b5080-73fb-11ea-9282-08989f87a22d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ddwolf715** [comment]
是有其他人也遇到这个问题了？是如何解决的？

**Comment by c56kevin** [comment]
表格上加tableScroll

**Comment by ddwolf715** [comment]
> 表格上加tableScroll
我看生成的代码里是用 j-editable-table，应该用的是 JEditableTable控件，但这个控件并没有tableScroll的设置项啊。
请问是如果添加tableScroll？

**Comment by ddwolf715** [comment]
我看生成的代码里是用 j-editable-table，应该用的是 JEditableTable控件，但这个控件并没有tableScroll的设置项啊。
请问是如果添加tableScroll？

> 表格上加tableScroll


我看生成的代码里是用 j-editable-table，应该用的是 JEditableTable控件，但这个控件并没有tableScroll的设置项啊。
请问是如果添加tableScroll？

**Comment by ddwolf715** [comment]
> 表格上加tableScroll


我看生成的代码里是用 j-editable-table，应该用的是 JEditableTable控件，但这个控件并没有tableScroll的设置项啊。
请问是如果添加tableScroll？

**Comment by zhangdaiscott** [comment]
我们确认下

**Comment by tygithub1** [comment]
![HG}M%FZ3KM87BKN1BS(T0S2](https://user-images.githubusercontent.com/27989856/78741908-2a955200-798d-11ea-8dc4-1e3770f854f0.png)

未出现所述bug！

**Comment by ddwolf715** [comment]
> ![aa](https://user-images.githubusercontent.com/27989856/78742024-78aa5580-798d-11ea-9461-53008473f4a2.png)
> 
> 未出现所述bug！

您的截图也是生成代码后的效果吗？
不生成代码在线看是没有问题。但生成代码后滚动条就消失了，其中有某列使用了popup弹出框，如果不使用popup弹出框，滚动条就还在。
另外这两天又发现使用开关组件的列，也是生成代码后，开关也不能使用了。

是不是在线可以使用全部功能，而生成代码使用时，是有一些功能限制的？比如有的功能只能在在线方式中使用，生成代码后就不能使用了。

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/78748192-f5453000-799d-11ea-801d-d8446c225907.png)
是生成后的代码
