### ISSUE TITLE
online表单js增强修改从表控件值问题

### ISSUE THREAD

**Issue by luo173668** [zhangdaiscott/jeecg-boot#1051]
##### 版本号：
1.0.0

##### 问题描述：
修改从表某一控件值，使之关联的控件值也相应变化，但是无法找到内置的Event对象，报错。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58063768/78164233-082aa280-747c-11ea-8e3c-fc38ac3171ff.png)
![image](https://user-images.githubusercontent.com/58063768/78164244-0d87ed00-747c-11ea-86f2-d9ad3cd32b08.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by luo173668** [comment]
![image](https://user-images.githubusercontent.com/58063768/78164538-766f6500-747c-11ea-9506-502a6f193eec.png)

![image](https://user-images.githubusercontent.com/58063768/78164513-6d7e9380-747c-11ea-9bc4-09eeefa9408a.png)

**Comment by luo173668** [comment]
可以回答我一下吗？这个是bug还是我操作问题，搞了好几天都没搞定

**Comment by zhangdaiscott** [comment]
图太小  不清晰

**Comment by zhangdaiscott** [comment]
另外你的版本太低，低版本不一定支持

**Comment by zhangdaiscott** [comment]
已经修复，五一后版本发布
