### ISSUE TITLE
后台Swagger Authorize后，访问接口还是报token失效

### ISSUE THREAD

**Issue by He-Xiao-Bo** [zhangdaiscott/jeecg-boot#1052]
##### 问题描述：
后台Swagger Authorize后，访问接口还是报token失效

##### 截图&代码：

![image](https://user-images.githubusercontent.com/25975216/78203221-fc190200-74c8-11ea-8c7f-e56695fcdd78.png)

![image](https://user-images.githubusercontent.com/25975216/78203252-16eb7680-74c9-11ea-9f30-7eae133d7fed.png)

![image](https://user-images.githubusercontent.com/25975216/78203295-35517200-74c9-11ea-8b2d-740ecb9b34dd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
/doc.html   用这个试试
![image](https://user-images.githubusercontent.com/3162115/78207706-0640fd80-74d5-11ea-81c5-a38fdcd403dd.png)

**Comment by He-Xiao-Bo** [comment]
这个是可以的，我是知道的，但是我就是想swagger页面，让Authorizes生效

**Comment by He-Xiao-Bo** [comment]
感觉header头没有带进去，这是swagger框架缺陷吗

**Comment by wangliguokaka** [comment]
同问这个问题 swagger-ui.html 确实带不上token信息

**Comment by zhangdaiscott** [comment]
swagger-ui.html 太丑，为什么不用/doc.html

**Comment by wangliguokaka** [comment]
有bug的地方 总想解决掉 看了一下代码配置 红框的地方被注释掉的 之前应该是考虑过这个问题
![image](https://user-images.githubusercontent.com/17798088/79822707-6a642c80-83c4-11ea-9c9c-54b7028fd8e1.png)
