### ISSUE TITLE
单表数据导出多表头 auto 的Excel注解 groupName属性

### ISSUE THREAD

**Issue by HeAvenLinH** [zhangdaiscott/jeecg-boot#1053]
##### 版本号：
2.1.4

##### 问题描述：
没有groupName属性

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12153749/78203406-747fc300-74c9-11ea-856e-a030ab5c9787.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
<dependency>
			<groupId>org.jeecgframework</groupId>
			<artifactId>autopoi-web</artifactId>
			<version>1.1.0</version>
			<exclusions>
				<exclusion>
					<groupId>commons-codec</groupId>
					<artifactId>commons-codec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


这个版本已经有了
