### ISSUE TITLE
关于table列宽可拖动问题

### ISSUE THREAD

**Issue by zzbsh** [zhangdaiscott/jeecg-boot#1054]
##### 版本号：
2.1.4

##### 问题描述：
由于table中会存在很多字段内容过长的问题，能否在全局集成table的列宽拖动功能

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
新版会提供两套方案
一套样式 默认左右拖动不允许换行
一套样式 允许换行需要设置列宽度
