### ISSUE TITLE
数据中的children属性中的列表里面的相关属性，没有字典数据 xxx_dictText

### ISSUE THREAD

**Issue by chishaohui333** [zhangdaiscott/jeecg-boot#1055]
##### 问题描述：
数据中的children属性中的列表里面的相关属性，没有字典数据 xxx_dictText，只有父级的才有

##### 截图&代码：

代码：
Company实体类：
@Dict(dicCode = "company_type")
private String companyType;
private List<Company> children;

后台返回的数据：
 "records": [
            {
                "companyType": "1",
                "companyName": "A公司",
                "createBy": "admin",
                "companyType_dictText": "主公司"
                "children": [
                    {
                        "companyType": "1",
                        "companyName": "A1公司",
                        "createBy": "admin"
                    },
                    ......
                 ]
             },
             ......
            ]
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
返回列表用IPage包一下
![image](https://user-images.githubusercontent.com/3162115/78622328-6f4eb980-78b7-11ea-99fc-47f7eae2eac9.png)

![image](https://user-images.githubusercontent.com/3162115/78622307-6362f780-78b7-11ea-86ec-37b19241046b.png)
