### ISSUE TITLE
form表单自定义校验

### ISSUE THREAD

**Issue by 15994028931** [zhangdaiscott/jeecg-boot#1056]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/29727795/78322778-47ebaa00-75a2-11ea-8f02-01164ef3fc08.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/78622681-5b578780-78b8-11ea-9331-aebe7fca077e.png)
https://www.antdv.com/components/form-cn/#API
