### ISSUE TITLE
首页修改主题颜色后左侧导航首页字体还是默认蓝色字体

### ISSUE THREAD

**Issue by Irvinna** [zhangdaiscott/jeecg-boot#1057]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Irvinna** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/18528640/78338081-b477a080-75c4-11ea-85b3-5fc122a4e607.png">

**Comment by sjlei** [comment]
问题已修复，将在下个版本更新。

**Comment by xmlspyspring** [comment]
> 问题已修复，将在下个版本更新。

请问是什么原因导致的,旧版本如何解决这个问题? 我现在就要解决这个问题啊

**Comment by zhangdaiscott** [comment]
public/color.less
增加样式代码
`// 侧边导航栏首页颜色跟随主题变化
.ant-menu.ant-menu-root > .ant-menu-item:first-child.ant-menu-item-selected {
  & > a,
  & > a:hover {
    color: @primary-color;
  }
}`
