### ISSUE TITLE
列表查询输入第一个数字无效

### ISSUE THREAD

**Issue by exiacer** [zhangdaiscott/jeecg-boot#1062]
##### 版本号：
目前演示版本也有

##### 问题描述：
比如用户列表 账号模糊查询框
火狐浏览器 win10自带输入法 
切换为中文 输入 数字123 查询框内显示23
切换为英文输入法 无问题 

##### 截图&代码：
![微信截图_20200407100923](https://user-images.githubusercontent.com/35093992/78622755-95288e00-78b8-11ea-9771-0172b9ec10a5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不存在你说的问题
![Uploading image.png…]()
