### ISSUE TITLE
菜单配置默认跳转地址无效

### ISSUE THREAD

**Issue by HeAvenLinH** [zhangdaiscott/jeecg-boot#1064]
##### 版本号：
2.1.4

##### 问题描述：
菜单配置默认跳转地址无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12153749/78658641-feca8b80-78fc-11ea-9234-de4f188af5f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by HeAvenLinH** [comment]
设置成功默认跳转地址，一级菜单也不起作用

**Comment by zhangdaiscott** [comment]
你如果配置了两级菜单，点击一级菜单不会跳转；
但如果你代码里面用push一级菜单，会跳转到默认地址
