### ISSUE TITLE
数据权限使用in的问题

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#1066]
##### 版本号：
2.1.4

##### 问题描述：
使用数据权限的时候，例如如果规则是 createBy IN admin,#{sys_user_code} 则不会生效，查看发现是JwtUtil代码的处理替换占位符时有问题

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以自己改造JwtUtil

**Comment by zhangdaiscott** [comment]
你也可以用自定义sql片段
![image](https://user-images.githubusercontent.com/3162115/79344726-c6612800-7f62-11ea-9d51-5722c9a7c6c5.png)
