### ISSUE TITLE
遗留系统数据库表的设计不规范，数据库字段不能通过对象属性驼峰转换的问题

### ISSUE THREAD

**Issue by 37305562** [zhangdaiscott/jeecg-boot#1068]
##### 版本号：
v2.1.4

##### 问题描述：
遗留系统数据库表的设计不规范，数据库字段不能通过对象属性驼峰转换，在分页查询时出错的解决方法。

##### 截图&代码：

QueryGenerator  
     installMplus
               TableInfo tableInfo=TableInfoHelper.getTableInfo(searchObj.getClass());
		List<TableFieldInfo> list=tableInfo.getFieldList();
		Map<String,String> nameToColumn =new HashMap<String,String>();
		
		for(TableFieldInfo info:list) {
			nameToColumn.put(info.getProperty(), info.getColumn());
		}
           nameToColumn 建立对象的属性与表的字段对应关系，原来代码中需要驼峰转换的，改成通过映射关系来处理。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没看明白

**Comment by 37305562** [comment]
比如在addEasyQuery中 name = oConvertUtils.camelToUnderline(name); 是通过这行转成数据库表的字段的，可以换成name = nameToColumn.get(name);

**Comment by zhangdaiscott** [comment]
还是没明白，请配合截图 描述清楚

**Comment by zhangdaiscott** [comment]
这个并不是命名不规范，而是因为实体是驼峰写法，查询逻辑用的是原始表字段名字（带下划线杠），所以需要转换
