### ISSUE TITLE
感觉目前项目提供的能力比较弱，我希望有的功能

### ISSUE THREAD

**Issue by 939347507** [zhangdaiscott/jeecg-boot#107]
1、统一单点登录平台、提供oauth接口，必须可以集群部署、session分布式存储、提供管理界面可以管理客户端，支持不同的业务子系统登录主题定制
2、cms内容管理系统，支持多站点、集群部署、支持全站静态化、能够前后端分离最好、支持自定义栏目、自定义模型模板、支持插件式开发
3、支持统一管理多个子系统的菜单权限
4、监控系统：数据库监控、机器监控、应用监控、流量监控、调用链监控、redis监控、druid监控
5、独立的消息系统，客户端支持同步、异步发送消息到消息系统，邮件、短信、微信等等、提供管理界面，查看发送记录、发送状态、调用量监控、队列堆积，需要保证mq的可靠消息必达，发送失败重试3次，3次仍然失败通知调用端发送失败，支持流量控制（限制客户端发送速度）
6、统一的日志平台、多个系统统一发送日志给日志平台，日志平台可以搜索日志、查看、过滤日志，业务子系统支持动态修改日志级别
7、提供统一的存储系统接口，支持fastdfs、ftp、local file、阿里云oss 、七牛云等云存储平台

**Comment by 939347507** [comment]
8、文档转码系统、在线浏览word、ppt、excel、txt、pdf
9、视频切片转码系统，对上传的视频文件，可以自定义触发规则、转码系统支持集群部署

**Comment by galaxist** [comment]
可以的，这一套下来放到众包平台没个5万以上，下不来。

**Comment by 939347507** [comment]
10、分布式任务调度系统，支持在线任务管理、启动、暂停、删除、可以在线查看调度日志、在线编写任务代码，这个xxl-job已经有了

**Comment by 939347507** [comment]
11、代码生成

**Comment by zhangdaiscott** [comment]
感谢，你的建议很好，我们会逐步实现

**Comment by 939347507** [comment]
12、独立的账户子系统、统一管控各个子系统的用户数据，免得用户数据分散在各个子系统难以维护

**Comment by 939347507** [comment]
13、独立的支付网关，所有的支付请求统一走网关，避免支付功能散落在各个子系统，可靠性低，难以维护

**Comment by 939347507** [comment]
14、通用模块抽离、比如工具类、base dao 、base service、base model、base controler、base vo、response响应格式统一、freemarker、mq、web、redis、mybatis这些都是基本的框架，很多子系统如果都写一遍一样的代码也是难以维护，把这些封装一层做成spring boot starter, 业务系统需要直接引入就行了，前后端交互接口数据签名，通过noncestr、timestam、appId、sign等、后端校验防止重放攻击、防止数据篡改

**Comment by 939347507** [comment]
15、子系统多了，安全是个问题，统一的服务鉴权网关

**Comment by 939347507** [comment]
16、独立的id发放系统，保证全局id唯一

**Comment by root123456** [comment]
不如直接上springcloud全家桶

**Comment by zr8657** [comment]
出门左转猪八戒，请

**Comment by tygithub1** [comment]
专业名词知道很多有个jb用，我啥都给你做了，你不就下岗了吗？

**Comment by y13810805250** [comment]
这是搞大平台呀

**Comment by minghu** [comment]
第一个功能我也正想着呢，有没有开发计划哟，1、统一单点登录平台、提供oauth接口，必须可以集群部署、session分布式存储、提供管理界面可以管理客户端，支持不同的业务子系统登录主题定制。

**Comment by 939347507** [comment]
以上功能虽然很多，但是确实这些功能是每个稍微有点规模的项目都需要的，现在哪还是简单的单体应用开发的年代，做系统并不是说做个后台管理系统就完事了，pc端面向不同人群，以我们公司目前项目为例，我们做中小学教育的，一个项目需要考虑很多端、比如运营管理端、教育局端、学校管理端、学校老师端、学生家长端、学生端、第三方客户端、微信端、桌面应用程序端，东西多了，势必就复杂了。

**Comment by anitaihua** [comment]
@939347507 就你懂得多

**Comment by cr7mufc520** [comment]
@939347507 伸手党真可恶，凭啥免费给你做

**Comment by 939347507** [comment]
> @939347507 就你懂得多

我也从没期望开源项目会把这些做了，公司的项目这些我都做了，只是阐述一些功能点或者方向吧

**Comment by niphor** [comment]
都做过了 还不来贡献代码？...单是提需求我也能365天,每天提不重样的

**Comment by galaxist** [comment]
> > @939347507 就你懂得多
> 
> 我也从没期望开源项目会把这些做了，公司的项目这些我都做了，只是阐述一些功能点或者方向吧

都做了就分享出来，大家一起完善不是更好吗？

**Comment by jiujiukai** [comment]
如果有做完的确实可以贡献出来公共代码，本来这个项目就是开源的，大家有什么想法可以实现的提上来，一起学习学习

**Comment by Diveler** [comment]
这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗

**Comment by galaxist** [comment]
> 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗

是滴呀 要不我给你提个建议，开发个彩票算号必中软件？

**Comment by Diveler** [comment]
> > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> 
> 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？

好啊，等着吧，随便你提，采不采纳随我啊

**Comment by galaxist** [comment]
> > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > 
> > 
> > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> 
> 好啊，等着吧，随便你提，采不采纳随我啊

对呀，我提的需求才能赚多少钱？你知不知道他提得这些需求加起来比一个彩票大奖500万都不差了。那是正常人提的需求吗？他昨个不找微软提个需求开放win10全部源代码？

**Comment by tygithub1** [comment]
> > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > 
> > 
> > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> 
> 好啊，等着吧，随便你提，采不采纳随我啊

你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?

**Comment by galaxist** [comment]
> > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > 
> > > 
> > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > 
> > 
> > 好啊，等着吧，随便你提，采不采纳随我啊
> 
> 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?

明白人呀，说不定这个就是被怼的换个小号来bb。

**Comment by Diveler** [comment]
> > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > 
> > > > 
> > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > 
> > > 
> > > 好啊，等着吧，随便你提，采不采纳随我啊
> > 
> > 
> > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> 
> 明白人呀，说不定这个就是被怼的换个小号来bb。
都是大佬，你们叼，你们叼，
不过这就给我安排成别人小号了，那顺便帮我联系下我大号让他带我飞一波

**Comment by 939347507** [comment]
> > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > 
> > > > 
> > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > 
> > > 
> > > 好啊，等着吧，随便你提，采不采纳随我啊
> > 
> > 
> > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> 
> 明白人呀，说不定这个就是被怼的换个小号来bb。



> > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > 
> > > 
> > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > 
> > 
> > 好啊，等着吧，随便你提，采不采纳随我啊
> 
> 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?

不想多说了，避免引战，真正做过有点规模的项目，就知道我说的这些是很常见的需求，我上面也举例了我们公司目前的项目要做哪些东西，功能虽然都实现了，但是并不一定好，而且这种东西都是商业机密，代码与自己的业务紧密关联的，依赖很多基础设施的，公司的东西不是说你一个人决定的，我想呆过大公司的就知道内部有严格的网络管理、代码管理、上网监控的，邮件都是内网的，聊天不能用qq、微信，不能百度博客代码的，什么u盘都是不能携带的。

**Comment by 939347507** [comment]
> > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > 
> > > > > 
> > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > 
> > > > 
> > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > 
> > > 
> > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > 
> > 
> > 明白人呀，说不定这个就是被怼的换个小号来bb。
> 
> > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > 
> > > > 
> > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > 
> > > 
> > > 好啊，等着吧，随便你提，采不采纳随我啊
> > 
> > 
> > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> 
> 不想多说了，避免引战，真正做过有点规模的项目，就知道我说的这些是很常见的需求，我上面也举例了我们公司目前的项目要做哪些东西，功能虽然都实现了，但是并不一定好，而且这种东西都是商业机密，代码与自己的业务紧密关联的，依赖很多基础设施的，公司的东西不是说你一个人决定的，我想呆过大公司的就知道内部有严格的网络管理、代码管理、上网监控的，邮件都是内网的，聊天不能用qq、微信，不能百度博客代码的，什么u盘都是不能携带的。

我前面也说过阐述方向或功能点，具体做不做那还不是个人的事情，又没逼着谁做。

**Comment by niphor** [comment]
> > > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > > 
> > > > > > 
> > > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > > 
> > > > > 
> > > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > > 
> > > > 
> > > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > > 
> > > 
> > > 明白人呀，说不定这个就是被怼的换个小号来bb。
> > 
> > 
> > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > 
> > > > > 
> > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > 
> > > > 
> > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > 
> > > 
> > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > 
> > 
> > 不想多说了，避免引战，真正做过有点规模的项目，就知道我说的这些是很常见的需求，我上面也举例了我们公司目前的项目要做哪些东西，功能虽然都实现了，但是并不一定好，而且这种东西都是商业机密，代码与自己的业务紧密关联的，依赖很多基础设施的，公司的东西不是说你一个人决定的，我想呆过大公司的就知道内部有严格的网络管理、代码管理、上网监控的，邮件都是内网的，聊天不能用qq、微信，不能百度博客代码的，什么u盘都是不能携带的。
> 
> 我前面也说过阐述方向或功能点，具体做不做那还不是个人的事情，又没逼着谁做。

你提的16个里，你只要按着jeecgboot的样式起码提交一个repo，就没人会喷你
你还能现在上github发言，说明你公司网络监管也不怎么严格，何必举一些类似银行公安内部的开发上网规范。
而且没人逼着你抄你公司的代码。

**Comment by galaxist** [comment]
> > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > 
> > > > > 
> > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > 
> > > > 
> > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > 
> > > 
> > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > 
> > 
> > 明白人呀，说不定这个就是被怼的换个小号来bb。
> 
> > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > 
> > > > 
> > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > 
> > > 
> > > 好啊，等着吧，随便你提，采不采纳随我啊
> > 
> > 
> > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> 
> 不想多说了，避免引战，真正做过有点规模的项目，就知道我说的这些是很常见的需求，我上面也举例了我们公司目前的项目要做哪些东西，功能虽然都实现了，但是并不一定好，而且这种东西都是商业机密，代码与自己的业务紧密关联的，依赖很多基础设施的，公司的东西不是说你一个人决定的，我想呆过大公司的就知道内部有严格的网络管理、代码管理、上网监控的，邮件都是内网的，聊天不能用qq、微信，不能百度博客代码的，什么u盘都是不能携带的。

你不想引战，还在这胡说八道逗乐子呢？你写的代码是你公司的机密，所以你就可以在网上信口开河提需求要别人家给你开发了？

**Comment by zr8657** [comment]
> > > > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > > > 
> > > > > > > 
> > > > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > > > 
> > > > > > 
> > > > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > > > 
> > > > > 
> > > > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > > > 
> > > > 
> > > > 明白人呀，说不定这个就是被怼的换个小号来bb。
> > > 
> > > 
> > > > > > > 这些人跟jeecg-boot有仇吧，提建议的都被怼，是不想jeecg发展吗
> > > > > > 
> > > > > > 
> > > > > > 是滴呀 要不我给你提个建议，开发个彩票算号必中软件？
> > > > > 
> > > > > 
> > > > > 好啊，等着吧，随便你提，采不采纳随我啊
> > > > 
> > > > 
> > > > 你可拉到吧，提意见的时候巴拉巴拉一大堆，说的高大上，自己很牛逼，全做过，让你分享一下就歇菜了，那还有必要扯吗?
> > > 
> > > 
> > > 不想多说了，避免引战，真正做过有点规模的项目，就知道我说的这些是很常见的需求，我上面也举例了我们公司目前的项目要做哪些东西，功能虽然都实现了，但是并不一定好，而且这种东西都是商业机密，代码与自己的业务紧密关联的，依赖很多基础设施的，公司的东西不是说你一个人决定的，我想呆过大公司的就知道内部有严格的网络管理、代码管理、上网监控的，邮件都是内网的，聊天不能用qq、微信，不能百度博客代码的，什么u盘都是不能携带的。
> > 
> > 
> > 我前面也说过阐述方向或功能点，具体做不做那还不是个人的事情，又没逼着谁做。
> 
> 你提的16个里，你只要按着jeecgboot的样式起码提交一个repo，就没人会喷你
> 你还能现在上github发言，说明你公司网络监管也不怎么严格，何必举一些类似银行公安内部的开发上网规范。
> 而且没人逼着你抄你公司的代码。

这人就是在打滚而已，转进不成开始打滚了。

**Comment by Diveler** [comment]
停了停了，都是大佬，你们说的都对，都有道理

**Comment by 939347507** [comment]
一堆喷子。。关闭了

**Comment by galaxist** [comment]
> 一堆喷子。。关闭了

我们直喷键盘侠

**Comment by niphor** [comment]
我只是建议楼主先开源**一个**自己写的建议而已

**Comment by zhangdaiscott** [comment]
建议很好，欢迎提建议，更欢迎提供对应的解决方案，喷喷就当乐呵了...

**Comment by zhangdaiscott** [comment]
单点已经集成，提供了方案： http://jeecg-boot.mydoc.io/?t=346456

非常欢迎大家多提建议

**Comment by zhubinsheng** [comment]
从19年看着平台实现了上述的大部分功能，真不错；
可否提供一个主从复制的功能或者是建议我自己实现。看了网上好几种 不知道哪种最方便最安全

**Comment by UsernameUntaken** [comment]
http://jeecg-boot.mydoc.io/?t=346456 这个咋关闭了

**Comment by zhangdaiscott** [comment]
新文档地址：
http://doc.jeecg.com
http://vue3.jeecg.com
