### ISSUE TITLE
当有百万级数据时，分页查询很慢。

### ISSUE THREAD

**Issue by wingnyl** [zhangdaiscott/jeecg-boot#1072]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
百万数据不算大，你说的慢，能具体描述出来？

**Comment by wingnyl** [comment]
select * from sys_msg where del_flag = 0 limit(pageNo,pageSize) 当这个pageNo很大时  分页就会很卡。

**Comment by zhangdaiscott** [comment]
mybatis plus 可以自定义分页
