### ISSUE TITLE
请问如何调用 TabLayout.vue 里面的 provide() 方法来关闭当前 tag 菜单标签页 ？

### ISSUE THREAD

**Issue by xiaoxuliu123** [zhangdaiscott/jeecg-boot#1073]
##### 版本号：
2.1.2

##### 问题描述：
vue 页面如何调用 TabLayout.vue 里面的 provide() 方法来关闭当前 tag 菜单标签页 ？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30621321/78869711-9522bc80-7a77-11ea-9e7b-4a4df924f315.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
// 注意：以下代码必须存在
        // inject:['closeCurrent'],
        this.closeCurrent()
