### ISSUE TITLE
online 表单中，在 附表中存在上传图片组件，点击上传图片并提交，显示提交失败

### ISSUE THREAD

**Issue by gitLiuZenghui** [zhangdaiscott/jeecg-boot#1074]
##### 问题描述：
online 表单中，在 附表中存在上传图片组件，点击上传图片并提交，提交报错，原因为上传图片的参数不是图片路径 。
操作步骤：
1.online创建一个主表
2.online创建一个附表，与主表关系1对1，新增一个字段，设置组件为图片
3.点击功能测试，新增一条数据，上传一张图片，点击提交
4.提交报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/22736694/78870836-5c83e280-7a79-11ea-9904-83709db1233a.png)

![image](https://user-images.githubusercontent.com/22736694/78870911-76bdc080-7a79-11ea-9fb2-5d9f80755bc0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.1.4可能有问题，你可以测试下演示系统是否有问题

**Comment by gitLiuZenghui** [comment]
上面的步骤就是在演示系统上操作的

**Comment by zhangdaiscott** [comment]
已经处理，五一后版本发布
