### ISSUE TITLE
最新文档对接CAS代码网盘链接失效

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#1075]
##### 问题描述：文档中Jeecg Boot 后端对接CAS步骤中的1.从网盘下载代码添加到后端项目工程中
的网盘链接失效，希望更新一下。最近需要整合sso。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49051702/78959423-76770100-7b1d-11ea-816f-429285b03bcc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经不需要了，最新版本已经自带了 cas相关代码

**Comment by wjxjasin** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年4月10日(星期五) 中午11:23
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "jasin"<wjxjasin@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 最新文档对接CAS代码网盘链接失效 (#1075)





 
已经不需要了，最新版本已经自带了 cas相关代码
