### ISSUE TITLE
数据字典中配置字典项状态配置无效

### ISSUE THREAD

**Issue by Loren1999** [zhangdaiscott/jeecg-boot#1076]
##### 版本号：
2.1.4

##### 问题描述：
系统管理中数据字典模块配置字典项状态不生效,需在mapper文件中增加查询条件 and s.status = '1'

##### 截图&代码：
	<select id="queryDictItemsByCode" parameterType="String"   
                                               resultType="org.jeecg.common.system.vo.DictModel">
		   select s.item_value as "value",s.item_text as "text" from sys_dict_item s
		   where dict_id = (select id from sys_dict where dict_code = #{code})
		   and s.status = '1'
		   order by s.sort_order asc
	</select>

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
特意这么写，保证老的业务数据状态可用。只让新的业务不用这个字典状态
