### ISSUE TITLE
online报表中模糊查找问题

### ISSUE THREAD

**Issue by yezhq2018** [zhangdaiscott/jeecg-boot#1079]
##### 版本号：
Jeecg-Boot 快速开发平台 2.1.4

##### 问题描述：
online报表中是不是不能模糊查找？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
前后带 *

**Comment by yezhq2018** [comment]
谢谢！
