### ISSUE TITLE
token在redis中进行超时校验的疑问

### ISSUE THREAD

**Issue by wangliguokaka** [zhangdaiscott/jeecg-boot#1082]
##### 版本号：
2.1.4

##### 问题描述：
token在redis中进行超时校验的疑问，这样如果redis正常运转，是不是和设置成超时无限长没有什么区别，设置超时时间是为了保证在token被盗取后仍然可以在很大程度上保持资源的保护效用，按照现在的代码感觉一旦被获取token，就可以做跨域攻击。

有不当的地方，请大神指正

##### 截图&代码：

![捕获](https://user-images.githubusercontent.com/17798088/79058092-c1b71e00-7c9b-11ea-96cd-eff805d95381.PNG)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
代码里面也有对应逻辑控制
