### ISSUE TITLE
后端获取token

### ISSUE THREAD

**Issue by wlh4959** [zhangdaiscott/jeecg-boot#1083]
##### 版本号：
2.1.4

##### 问题描述：
在后端项目做的ftl页面，如何获取token？

##### 截图&代码：
![如何在后端的ftl页面中获取token](https://user-images.githubusercontent.com/27939657/79083758-b8dd4f80-7d62-11ea-81d6-99f602c7a771.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
6
