### ISSUE TITLE
online生成代码的页面刷新404

### ISSUE THREAD

**Issue by wlh4959** [zhangdaiscott/jeecg-boot#1084]
##### 版本号：
2.1.4

##### 问题描述：
用online表单开发功能生成的代码，覆盖到对应目录后，重启服务，并按文档配置菜单，对账号授权，然后点击菜单可以正常打开功能页面，但是刷新就会出现404，不知哪里操作遗漏？

##### 截图&代码：
![菜单配置](https://user-images.githubusercontent.com/27939657/79083938-bd563800-7d63-11ea-903c-529742ec9e53.png)
![现场设备列表页面](https://user-images.githubusercontent.com/27939657/79084123-ab28c980-7d64-11ea-9146-532b8654e80b.png)
![刷新404](https://user-images.githubusercontent.com/27939657/79083944-c8a96380-7d63-11ea-9b29-888ad52cc813.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1305119
