### ISSUE TITLE
打卡多个页面菜单(Tab多页签方式)后,刷新一下就只剩下一个了

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1085]
##### 问题描述：
1.用tab多页签方式,打开多个菜单页面以后,刷新页面,就会只留下首页和当前激活的tab页面了,其他已经打开的就没了.
2.tab页签切换的时候会重新初始化一次这个页面,这也许是不太想看到的,比如在页面A,打开了一个新增表单,填写的时候发现有一个参数需要参考别的页面去填写,这个时候打开或者切换到页面B,再切换回页面A的时候,弹出的那个表单就刷没了.
3.建议在页面顶部的打开收起左侧菜单树的那个按钮旁边增加一个刷新按钮,可以只刷新当前激活的tab页签的页面.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by cisa4Cs** [comment]
同问，这个问题有答案了吗？
