### ISSUE TITLE
导入数据库表时失败。。

### ISSUE THREAD

**Issue by afeidexiaolulu** [zhangdaiscott/jeecg-boot#1087]
##### 版本号：
2.1.4
##### 问题描述：
导入数据库表时失败

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46062447/79093939-69117f00-7d88-11ea-85a1-38488962d6ff.png)
![image](https://user-images.githubusercontent.com/46062447/79093960-7af32200-7d88-11ea-8141-4ec82afaaabd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1275846
