### ISSUE TITLE
导入数据库表失败，，已更改，jeecg_database.properties的配置文件

### ISSUE THREAD

**Issue by afeidexiaolulu** [zhangdaiscott/jeecg-boot#1088]
##### 版本号：
2.1.4

##### 问题描述：
导入数据库表失败，，已更改，jeecg_database.properties的配置文件

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46062447/79094293-a32f5080-7d89-11ea-9f67-ee480c176531.png)
![image](https://user-images.githubusercontent.com/46062447/79094296-a62a4100-7d89-11ea-956e-ca2edba4fac2.png)
![image](https://user-images.githubusercontent.com/46062447/79094317-b2160300-7d89-11ea-9f12-eb216e89a457.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
本地开发环境还是服务器？

**Comment by afeidexiaolulu** [comment]
本地开发环境，，自己添加了activiti的一个module

**Comment by shuaidiao** [comment]
这个问题怎么解决

**Comment by afeidexiaolulu** [comment]
更改 /resource下面的jeecg文件夹下面的数据库配置
