### ISSUE TITLE
子菜单配置外部打开不生效

### ISSUE THREAD

**Issue by wlh4959** [zhangdaiscott/jeecg-boot#1089]
##### 版本号：
2.1.4

##### 问题描述：
我在菜单管理配置打开方式为外部，但是依然在本页面内部打开，不能新建一个浏览器页面打开

##### 截图&代码：
![外部打开](https://user-images.githubusercontent.com/27939657/79096686-6f0b5e00-7d90-11ea-856e-f2ea3ca520d4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
外部方式 只能打开以http开头的，你这内部路由，为什么要单独开网页
