### ISSUE TITLE
JCategorySelect  保存到数据库的是id不是code

### ISSUE THREAD

**Issue by MrQiaoLei** [zhangdaiscott/jeecg-boot#1090]
##### 版本号：

master
##### 问题描述：
JCategorySelect 保存到数据的是id，能否改为code。code比id的作用要大

##### 截图&代码：

![image](https://user-images.githubusercontent.com/17661940/79098540-cdd2d680-7d94-11ea-9e8d-5f9d6d2e4b7d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yezhq2018** [comment]
j-tree-select也是如此，建议改成保存的字段可以自定义方便些。
