### ISSUE TITLE
树形下拉组件，树字典组件保存id字段问题

### ISSUE THREAD

**Issue by yezhq2018** [zhangdaiscott/jeecg-boot#1091]
##### 版本号：
2.1.4

##### 问题描述：
j-tree-select，这个保存的字段可以改为指定的字段，但是，改为id以外的字段时，树形只显示第一级的内容，第二级及以下就不能展开。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/43459014/79100152-5141f700-7d98-11ea-817f-0e49a521b615.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
这个id对应的就是树形结构的key，树在点击时候，会用这个key当成pid去查询展示下级。所以改成别的字段就查不出来了。如果想改动，需根据表结构来酌情修改

**Comment by lsqGitHub716** [comment]
这个id对应的就是树形结构的key，树在点击时候，会用这个key当成pid去查询展示下级。所以改成别的字段就查不出来了。如果想改动，需根据表结构来酌情修改
