### ISSUE TITLE
新clone下来的前端部分，执行pre 之后，再build出错

### ISSUE THREAD

**Issue by cloudyHappy** [zhangdaiscott/jeecg-boot#1093]
##### 问题描述：

 直接clone下来的项目，什么都没改。并且成功执行了npm run pre .
然后再npm run build ,就出现了错误。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42270207/79101080-66b82080-7d9a-11ea-84b6-700ce2a10fd9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
百度下，不清楚
