### ISSUE TITLE
在线开发-报表配置-点击功能测试，提示Parameter 'sys_user_code' not found

### ISSUE THREAD

**Issue by DrKarev** [zhangdaiscott/jeecg-boot#1094]
版本号：2.1.4
问题描述：
报表配置“select username,realname,sex,birthday,create_time from sys_user where username = '#{sys_user_code}'”,然后点击【功能测试】提示“查询失败：SQL执行失败：nested exception is org.apache.ibatis.binding.BindingException: Parameter 'sys_user_code' not found. Available parameters are [arg0, sqlStr, param1, param2]”

截图&代码：
image
![image](https://user-images.githubusercontent.com/12276846/79287480-849a9800-7ef6-11ea-81de-e43a097effb1.png)

![image](https://user-images.githubusercontent.com/12276846/79287495-8cf2d300-7ef6-11ea-8ccc-da1b38feebb3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
#{}
http://doc.jeecg.com/1273976

**Comment by DrKarev** [comment]
> #{}
> http://doc.jeecg.com/1273976

参数我是按照这个格式设置的#{}，带任何参数设置都报这个问题

**Comment by DrKarev** [comment]
> #{}
> http://doc.jeecg.com/1273976

您看看我这个语句select username,realname,sex,birthday,create_time from sys_user where username = '#{sys_user_code}' ，应该是没有设置错的，但依然报参数不存在，而这个参数再菜单设置里面是好使的，所以怀疑是bug请教您
