### ISSUE TITLE
JEditTable下使用slot模式下，JSearchSelectTag无法选中。

### ISSUE THREAD

**Issue by kaybinwong** [zhangdaiscott/jeecg-boot#1095]
##### 版本号：
2.1.4

##### 问题描述：
JEditTable下使用slot模式下，JSearchSelectTag无法选中。前端不是很熟，是不是绑定的事？

##### 截图&代码：
```
<j-editable-table
              :ref="refKeys[0]"
              :loading="poBillDetailTable.loading"
              :columns="poBillDetailTable.columns"
              :dataSource="poBillDetailTable.dataSource"
              :maxHeight="300"
              :rowNumber="true"
              :rowSelection="true"
              :actionButton="true"
              @valueChange="handleValueChange">
              <template v-slot:goodsId="props">
                <j-search-select-tag placeholder="请选择商品" dict="erp_goods,name,id" @change="handleChange(props)" :async="true"/>
              </template>
          </j-editable-table>
```
![image](https://user-images.githubusercontent.com/5570216/79365311-1220cb00-7f7d-11ea-83ba-6ad3183ddde0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
你并没有绑定值所以选不上，建议使用双向数据绑定（v-model）
使用slot的控件的值是不受JEditableTable管理的，需要你自己手动管理，可参考下面的截图

![image](https://user-images.githubusercontent.com/34293221/81391589-efcf3700-914f-11ea-9c56-3ae5d7943a43.png)

![image](https://user-images.githubusercontent.com/34293221/81391556-df1ec100-914f-11ea-8558-35062eaac974.png)


![image](https://user-images.githubusercontent.com/34293221/81391344-85b69200-914f-11ea-9673-e066007e0c16.png)

**Comment by kaybinwong** [comment]
感谢你的回答， 这样的确能实现，但是有没有办法让je管理slot的空间的值呢？这样使用起来才能无缝使用

**Comment by sjlei** [comment]
> 感谢你的回答， 这样的确能实现，但是有没有办法让je管理slot的空间的值呢？这样使用起来才能无缝使用

目前是没有这个功能的，但是有这个计划，以后会添加的

**Comment by guaicaiboshi** [comment]
请问这样的话，这个值怎么对应的上是哪个控件的呢？
