### ISSUE TITLE
列表页面跳转新的路由需要展示成面包屑菜单样式，求助

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#1096]
##### 版本号：
2.1.3

##### 问题描述：
如何实现子菜单为隐藏路由菜单，父菜单也是路由菜单，目前设置子菜单后，父菜单默认只具有展开作用，无路由功能。
比如：list和详情都为路由页面，想把详情设置在list下级，无法做到，只能设置成同级菜单。（面包屑下使用效果略差）
请问作者大大有什么方案吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Nicky213Zhang** [comment]
![微信图片_20200416175146](https://user-images.githubusercontent.com/25654842/79442316-fcf27d80-800a-11ea-9874-017d723a7ebd.png)
好像在文档里找到说明了，请问有大神可以指导下怎么改造吗

**Comment by Nicky213Zhang** [comment]
![image](https://user-images.githubusercontent.com/25654842/79458902-16082800-8025-11ea-8150-794dd19d826f.png)
通过改造menu/index里渲染menu的方法，可以实现面包屑路由效果，但是this.$router.push({ path: 'xxx',query:{ id:1 } })跳转不动

**Comment by zhangdaiscott** [comment]
这个问题最新版已经解决

**Comment by Nicky213Zhang** [comment]
> 这个问题最新版已经解决

您指的是2.1.4版本还是未发布的版本？我拉取了2.1.4并没有解决我说的问题
