### ISSUE TITLE
ant design vue升级到1.5.0以上导致用户选择器不可用

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1098]
##### 版本号：

2.1.4
##### 问题描述：

因为折叠面板组件的插槽功能需要1.5.0+才有，我把项目vue升级到1.5.3后，用户选择器就无法使用了，点击了没反应
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
我们项目vue升级到1.5.2没问题

**Comment by COMAC919** [comment]
> 我们项目vue升级到1.5.2没问题

我下载的源码后，运行项目，用户选择器可以使用。修改版本到1.5.2，用户选择器不起作用。使用的是hub上面的源码。请问是什么地方出问题了吗？页面也没有报错

**Comment by COMAC919** [comment]
> 我们项目vue升级到1.5.2没问题

经过几次测试，我发现直接升级到1.5.2，用户选择器使用不了。后来检查是组件里面的search.Js中onSearch方法中的loading显示未定义导致的，我进一步查看了1.4.11中的该方法，并没有校验这个loading方法。注释或者传入该值后，用户选择器才能使用。我不知道你们是怎么直接升级到1.5.2就能直接使用的？
![image](https://user-images.githubusercontent.com/58909486/79681258-695bbf80-824b-11ea-913d-aaf426f01fcb.png)

**Comment by COMAC919** [comment]
解决方法：
<template>
  <div>
    <a-input-search
      v-model="userNames"
      placeholder="请先选择用户"
      disabled
      @search="onSearchDepUser">
      <a-button slot="enterButton" :disabled="disabled">选择用户</a-button>
    </a-input-search>
    <j-select-user-by-dep-modal ref="selectModal" :modal-width="modalWidth" :multi="multi" @ok="selectOK" :user-ids="value" @initComp="initComp"/>
  </div>
</template>
中的disabled删除
