### ISSUE TITLE
应该是权限管理bug

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#110]
![image](https://user-images.githubusercontent.com/27263086/57821212-44043d00-77c2-11e9-96f8-e786b36d2cf7.png)
查看菜单时以及授权时，并没有对这两个授权，但是我单独访问这个页面成功了，说明授权没有成功，临时角色是没有这两个页面的访问权限的。

**Comment by ileadall42** [comment]
![image](https://user-images.githubusercontent.com/27263086/57821244-68601980-77c2-11e9-988b-31e5e22e1fa3.png)

**Comment by zhangdaiscott** [comment]
了解

**Comment by jarvissdiff** [comment]
应该没有使用shiro的权限验证吧

**Comment by NoSuchBean** [comment]
这个问题也是我所关心的,有两个方案可以解决(但是我们领导想要第三种方案,所以我只好提了个issue):
方案1: 使用@RequiresPermissions();
方案2:写个拦截器,重写preHandle,在里面获取到当前请求的菜单路径,然后调用SysPermissionMapper.getPermissionsByUsername(username)查出该账户所有的权限,如果权限list.contains(当前请求的路径)则放行,反之不放行;
那么我的问题来了,我们领导不想使用@RequiresPermission(),说是配置太麻烦了,领导也不想使用我实现的方案2,说是自己造轮子怕有坑,不巧的是,领导又翻到了ResourceCheckFilter,这个类,所以他觉得框架已经造好了方案2的轮子,可是我研究了半天,也没有找到框架里面的轮子,请问jeecg团队的各位大大,框架是否已经提供了这个轮子? @zhangdaiscott

**Comment by UPMuling** [comment]
同求

**Comment by zhangdaiscott** [comment]
已经实现权限控制，下个版本发布
