### ISSUE TITLE
关于多数据源的问题

### ISSUE THREAD

**Issue by lch245298** [zhangdaiscott/jeecg-boot#1100]
##### 版本号：
2.1.3

##### 问题描述：
用多数据源，@DS注解在自动生成的代码ServiceImpl中的方法上无法正常使用，访问的好像还是默认的。
单独写的Service可以。
是因为继承了ServiceImpl的原因么
自动生成的代码框架不支持多数据源么

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62693683/79542603-857e2600-80be-11ea-9235-70bdc7b1bc1b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhang0001** [comment]
#994 可能是重复代理导致

**Comment by zhangdaiscott** [comment]
我这边测试好使
