### ISSUE TITLE
定时服务执行一段时间以后，报错o.s.scheduling.quartz.LocalDataSourceJobStore:973 - Handling 1 trigger(s) that missed their scheduled fire-time

### ISSUE THREAD

**Issue by linekite** [zhangdaiscott/jeecg-boot#1108]
##### 版本号：
2.1.0

##### 问题描述：
定时服务执行一段时间以后，报错o.s.scheduling.quartz.LocalDataSourceJobStore:973 - Handling 1 trigger(s) that missed their scheduled fire-time

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/u011750989/article/details/83502066
