### ISSUE TITLE
编译后popup组件无法使用的BUG

### ISSUE THREAD

**Issue by chengyu2333** [zhangdaiscott/jeecg-boot#1109]
##### 问题描述：
编译后popup组件显示空白，且在线开发中的modal组件都无法使用。且没有报错信息。
据排查是main.js中的以下代码引起的：

##### 截图&代码：
```
if (process.env.NODE_ENV !== 'production') {
  require('@jeecg/antd-online-214')
  require('@jeecg/antd-online-214/dist/OnlineForm.css')
}
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把条件删掉

if (process.env.NODE_ENV !== 'production') {
