### ISSUE TITLE
vue  订单展示问题咨询

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#111]
有一个订单，如果要修改数据，不能在原订单中修改，， 只能增加要修改的数据 关联订单号， 
用vue  如何显示，让用户很容易看清楚 数据和原订单对比

红色圈表示原单修改过的数据

下面剪头表示原单 修改的字段 新值和就值  谢谢
![image](https://user-images.githubusercontent.com/5210084/57823943-f42a7380-77cb-11e9-8cc5-0171fabda890.png)

**Comment by zhangdaiscott** [comment]
jeecgboot 有个数据快照功能
http://jeecg-boot.mydoc.io/?t=344885
