### ISSUE TITLE
在线开发-报表配置“配置sql语句where的参数是系统常量”报错找不到该常量

### ISSUE THREAD

**Issue by DrKarev** [zhangdaiscott/jeecg-boot#1110]
##### 问题描述：
你们官方在线的系统没有问题，但是git上面最新的代码【在线开发-报表配置】“配置sql语句where的参数是系统常量”这个功能都是有问题的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12276846/79693926-021c2a80-82a0-11ea-9134-4f39de01ee0f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
等新版
