### ISSUE TITLE
jeecg 2.1.4添加新模块,mapper异常？

### ISSUE THREAD

**Issue by yiyuan0109** [zhangdaiscott/jeecg-boot#1111]
##### 版本号：
jeecg boot version： 2.1.4

##### 问题描述：
在jeecg-boot 下添加了一个子module ，同时也在org.jeecg.config.MybatisPlusConfig配置了扫描模块的类路径，有的mapper竟然没有起作用,在调用方法时出错了(org.apache.ibatis.binding.BindingException: Invalid bound statement (not found):cn.cccteam.modules.order.mapper.MallOrderGoodsMapper.getOneItem).
但是cn.cccteam.modules.order.mapper.MallOrderInfoMapper 的没有问题，lis 方法也可以查询得到数据.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12425007/79718685-311db500-830f-11ea-86de-3fefcb16f952.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
改目录了，要自己额外加扫描路径

**Comment by yiyuan0109** [comment]
已经配置了, 就是有些mapper有效，有些mapper无效
![image](https://user-images.githubusercontent.com/12425007/79823131-8b794d00-83c5-11ea-9f19-8c0e61fd7bdc.png)
