### ISSUE TITLE
前端项目运行之后账号密码登录验证码图片无法显示

### ISSUE THREAD

**Issue by jiubanmoli** [zhangdaiscott/jeecg-boot#1112]
##### 问题描述：
前端项目运行之后账号密码登录验证码图片无法显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27392418/79722712-21a26a00-8317-11ea-85c9-c47c4f55500f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by MrQiaoLei** [comment]
确保项目redis配置正确，本地已开启redis服务

**Comment by MrQiaoLei** [comment]
后台项目有没有正常启动
