### ISSUE TITLE
菜单配置外部打开方式无效

### ISSUE THREAD

**Issue by womeng2009** [zhangdaiscott/jeecg-boot#1115]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/64006143/79734782-d80f4a80-8329-11ea-9392-bcb84d0dbe73.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
只支持http开头链接

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273950

**Comment by womeng2009** [comment]
收到，非常感谢🙏

**Comment by womeng2009** [comment]
> http://doc.jeecg.com/1273950

收到，非常感谢，效率很高。

**Comment by womeng2009** [comment]
> http://doc.jeecg.com/1273950

您好，仔细看了一下文档，系统提供的是可配置外网的链接进入本系统访问，那可以将本系统某个页面提供给别的系统访问吗，不是嵌入到系统内，而是单独一个窗口进行打开，没有权限认证的方式。
