### ISSUE TITLE
部门管理, 定义的数据规则不生效.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1116]
##### 版本号：
Jeecg  Boot Version: 2.1.4
Spring Boot Version: 2.1.3.RELEASE (v2.1.3.RELEASE)

##### 问题描述：
部门管理, 定义的数据规则不生效.
1. sysDepartController.java,queryTreeList方法, 已经增加注解了
@PermissionData(pageComponent = "system/DepartList")
2.系统管理>菜单管理>部门管理, 添加了数据规则
3.给用户分配的角色权限, 发现不起作用,用户还是可以查看所有部门的数据.

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/20039800/79736165-f7a77280-832b-11ea-99ab-cfd840daa4f0.png)

![图片](https://user-images.githubusercontent.com/20039800/79736089-dd6d9480-832b-11ea-8822-26990f815286.png)

![图片](https://user-images.githubusercontent.com/20039800/79736316-32110f80-832c-11ea-97cf-c1882c11beb4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块没用jeecg的查询过滤器  QueryGenerator.initQueryWrapper
需要手工集成
http://doc.jeecg.com/1607185
