### ISSUE TITLE
vue1.5.2，新增用户中部门选择器不可用

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1120]
##### 版本号：
2.1.4

##### 问题描述：
ant design vue升级到1.5.2，新增用户表单中部门选择器不可用。但是自己online生成的自己的表单里面的部门选择器使用没问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58909486/80064188-0ed3a380-856a-11ea-8707-680de6eb0bff.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级不兼容，需要disabled 改为 readOnly

**Comment by COMAC919** [comment]
> 升级不兼容，需要disabled 改为 readOnly

麻烦问一下，最高目前是支持哪个版本vue？
