### ISSUE TITLE
为什么默认字段没有del_flag?

### ISSUE THREAD

**Issue by onlyhiphop** [zhangdaiscott/jeecg-boot#1122]
##### 版本号：
v2.1.4

##### 问题描述：
作者没有将del_flag设计成默认字段有什么用意吗？

##### 截图&代码：
作者没有将del_flag设计成默认字段有什么用意吗？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
并不是所有的系统 都需要逻辑删除。你这边需要可以默认加上

**Comment by onlyhiphop** [comment]
好的！谢谢您的答复！

**Comment by onlyhiphop** [comment]
> 并不是所有的系统 都需要逻辑删除。你这边需要可以默认加上



> 并不是所有的系统 都需要逻辑删除。你这边需要可以默认加上

好的！谢谢您的答复！

**Comment by lanwaixian** [comment]
如果使用Online表单开发，手动加上del_flag字段就可以自动软删除了吗？还需要其他配置吗？
