### ISSUE TITLE
excel  导出分隔符问题

### ISSUE THREAD

**Issue by zhuqiyun** [zhangdaiscott/jeecg-boot#1126]
##### 版本号：
2.1.2

##### 问题描述：
@Excel(name = "货位", dictTable="wm_cargo_space",dicCode="id",dicText="code", width = 30)

数据中查询出来的字段带下划线，跟字典翻译的分隔符冲突了  ，导致翻译失败

##### 截图&代码：
 GNCK_01-11-11-1-2_1234666257306947585, GNCK_01-11-11-1-3_1234666303712727042, GNCK_01-11-11-1-4_1234666342019305473, GNCK_01-11-11-1-5_1234666403788820481,

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在此问题

**Comment by helloquan** [comment]
我是这么解决的
修改autopoi项目中的org.jeecgframework.poi.excel.export.base.ExportBase类
查找   .equals(temp[1]
把上面一行的  temp = str.split("_");
改成  temp = str.split("_",2);
就可以了，各位可以试试看

**Comment by zhangdaiscott** [comment]
已经修复，请用这个版本
```
<dependency>
	<groupId>org.jeecgframework</groupId>
	<artifactId>autopoi-web</artifactId>
	<version>2.0.1</version>
</dependency>
```

**Comment by lpf-lpf** [comment]
> 已经修复，请用这个版本
> 
> ```
> <dependency>
> 	<groupId>org.jeecgframework</groupId>
> 	<artifactId>autopoi-web</artifactId>
> 	<version>2.0.1</version>
> </dependency>
> ```

没找到这个版本啊？最新的版本是1.4.7啊
