### ISSUE TITLE
有集成第三方扫码登录的推荐方式么

### ISSUE THREAD

**Issue by petma** [zhangdaiscott/jeecg-boot#1128]
##### 截图&代码：
login.vue
` <div class="user-login-other">
        <span>其他登陆方式</span>
     <a ><a-icon class="item-icon1" type="dingding"></a-icon></a>
 </div>
`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时没有，需要自己开发

**Comment by petma** [comment]
https://ding-doc.dingtalk.com/doc#/serverapi2/kymkv6
