### ISSUE TITLE
请问 如何用 AutoPoi  导出 导入 2个 sheet（同一个excel ） ？

### ISSUE THREAD

**Issue by LiuNet2** [zhangdaiscott/jeecg-boot#113]
jeecg-boot 中使用  AutoPoi导入导出的excel是一个sheet ，请问 如何用 AutoPoi  导出 导入 2个 sheet（同一个excel 中） ？

https://github.com/zhangdaiscott/autopoi

**Comment by zhangdaiscott** [comment]
设置导入参数
![image](https://user-images.githubusercontent.com/3162115/58159365-e9318080-7cae-11e9-8e80-749af89cde12.png)

**Comment by gelinagg** [comment]
图片看不到。
