### ISSUE TITLE
服务器日志超过设置的MaxFileSize时

### ISSUE THREAD

**Issue by kingchengzdm** [zhangdaiscott/jeecg-boot#1130]
##### 版本号：
2.1.4

##### 问题描述：
当服务器日志文件超过设置的MaxFileSize时，好像这个文件就没有了。是不是可以做一个当日的日志文件切分

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19925479/80336204-33d95680-8889-11ea-8209-13c12146deb8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已经修复，下个版本发布
