### ISSUE TITLE
ie11打开测试地址http://boot.jeecg.com/会无限转圈圈

### ISSUE THREAD

**Issue by 541543262** [zhangdaiscott/jeecg-boot#1131]
##### 版本号：
http://boot.jeecg.com/  测试环境当前版本

##### 问题描述：
ie内核浏览器均会有这种情况
打开测试地址http://boot.jeecg.com/会无限转圈圈
##### 截图&代码：

![image](https://user-images.githubusercontent.com/36912807/80354642-95112200-88a9-11ea-88ab-edb806bb1776.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已改，未发布最新的
