### ISSUE TITLE
上传图片后再列表不显示缩略图，数据库保存的也不是图片地址

### ISSUE THREAD

**Issue by ldan123321** [zhangdaiscott/jeecg-boot#1134]
##### 问题描述：
上传图片后再列表不显示缩略图，数据库保存的也不是图片地址

##### 截图&代码：

![微信图片_20200428163127](https://user-images.githubusercontent.com/52995508/80465497-c7845300-896d-11ea-8f18-6105743aa5c3.png)
![微信图片_20200428163206](https://user-images.githubusercontent.com/52995508/80465544-d3701500-896d-11ea-83d3-f6c093a354cf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你用的是那个功能  online还是生成的代码？

**Comment by ldan123321** [comment]
> 你用的是那个功能online还是生成的代码？

用的是本地环境的online表单开发后的功能测试，没生成代码

**Comment by zhangdaiscott** [comment]
新版2.2不再存在此问题，请验证
