### ISSUE TITLE
Excel按模板导出有Bug

### ISSUE THREAD

**Issue by heroghost** [zhangdaiscott/jeecg-boot#1136]
##### 版本号：
2.1.4
##### 问题描述：
引用jar包
autopoi 1.0.5
其中
PoiEIUtil.java里的isTrue方法，这个方法里一堆问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2017291/80491421-46d94d00-8995-11ea-84ae-bcaa6b80e9a1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by pypykim** [comment]
tag:1.1.1 未解决

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
