### ISSUE TITLE
jEditabletable组件中jpopup清空当前值，未能同时清空携带返回回填的其他值

### ISSUE THREAD

**Issue by kongshanchat** [zhangdaiscott/jeecg-boot#1137]
##### 截图&代码：
[image](https://user-images.githubusercontent.com/24310433/80557264-ef74c480-8a08-11ea-99e8-34e612a52f1f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，将在下个版本更新
