### ISSUE TITLE
代码生成器模板  生成 一对多ERP风格模板  配置问题

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#114]
本人SqlServer 库
生成 一对多ERP风格模板  下图   
![image](https://user-images.githubusercontent.com/5210084/57901809-1d650580-7899-11e9-82e1-d43f418374b1.png)

下图配置对吗 谢谢 
![image](https://user-images.githubusercontent.com/5210084/57901794-0faf8000-7899-11e9-96b6-74c067b86f25.png)
![image](https://user-images.githubusercontent.com/5210084/57901887-6fa62680-7899-11e9-94ef-af99dffb1028.png)

报错图 
![image](https://user-images.githubusercontent.com/5210084/57901903-8ba9c800-7899-11e9-94ad-0f17c4e12428.png)

默认配置 正常 图下图
![image](https://user-images.githubusercontent.com/5210084/57901968-beec5700-7899-11e9-90ae-d23574cced8d.png)

**Comment by tygithub1** [comment]
po.setForeignKeys(new String[]{"order_id"});
po.setOriginalForeignKeys(new String[]{"order_id"});

please add the second line of code in your main method

**Comment by shaowen** [comment]
> ```
> po.setForeignKeys(new String[]{"order_id"});
> po.setOriginalForeignKeys(new String[]{"order_id"});
> ```
> 
> 请在main方法中添加第二行代码

具体在哪里增加谢谢，

**Comment by shaowen** [comment]
具体在哪里增加 谢谢

**Comment by tygithub1** [comment]
your error is because the parameter 'originalForeignKeys' is null ,you need set it after setForeignKeys method.

**Comment by shaowen** [comment]
![image](https://user-images.githubusercontent.com/5210084/58011556-16522780-7b25-11e9-97b6-5024fd145f40.png)
改這裡的模板嗎

**Comment by tygithub1** [comment]
哥，你非要的我说中文？那个错误不是说模板的某一行抛出空指针了吗？originalForeignKeys为空了，你在main方法里调用代码生成器的时候对每个子表设置一下啊，就在setForeignKeys后面设置就行了，值一样。

**Comment by shaowen** [comment]
謝謝 已經解決
