### ISSUE TITLE
（使用sqlserver数据库)用户管理查询出错

### ISSUE THREAD

**Issue by qingjing0606** [zhangdaiscott/jeecg-boot#1140]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/10215599/80565040-1390cf80-8a22-11ea-9d43-39230084c658.png)

SysUser.java 文件需做处理
  /**
     * 身份（0 普通成员 1 上级）
     */
    @Excel(name="（1普通成员 2上级）",width = 15)
    // fix keyword 'identity' in sqlserver begin
    @TableField("[identity]")
    // fix keyword 'identity' in sqlserver end
    private Integer identity;

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yunpyy** [comment]
版本号：2.1.4

SysUserMapper.xml文件中多处del_flag后是双引号，导致sqlServer执行sql报错。

`<update id="revertLogicDeleted">
		UPDATE
			sys_user
		SET
			del_flag = "0",
			update_by = #{entity.updateBy},
			update_time = #{entity.updateTime}
		WHERE
			del_flag = "1"
			AND id IN (${userIds})
	</update>`

**Comment by zhangdaiscott** [comment]
已经改了，下个版本发布
