### ISSUE TITLE
jEditableTable中jpopup弹窗回填下拉字典值的时候，下拉字典未能成功赋值

### ISSUE THREAD

**Issue by kongshanchat** [zhangdaiscott/jeecg-boot#1141]
##### 截图&代码：
第一步 默认管控类型 单件
![image](https://user-images.githubusercontent.com/24310433/80569514-abdf8200-8a2b-11ea-8b8a-a59de060fe8a.png)

第二步修改popup弹出选中值  管控类型 对应为 数量管控
![image](https://user-images.githubusercontent.com/24310433/80569468-9407fe00-8a2b-11ea-855d-38131085221c.png)

第三步 管控类型 依然为单件 未能变更
![image](https://user-images.githubusercontent.com/24310433/80569407-733fa880-8a2b-11ea-99cd-ee479b4614de.png)

具体popup代码与select设置

![image](https://user-images.githubusercontent.com/24310433/80569719-17295400-8a2c-11ea-8fdc-f119aa26c7e7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，将在下个版本更新
