### ISSUE TITLE
j-popup弹窗组件可否在前端传递参数过滤报表中的数据

### ISSUE THREAD

**Issue by kongshanchat** [zhangdaiscott/jeecg-boot#1142]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/24310433/80571268-e696e980-8a2e-11ea-8605-8b8729dcf992.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以

**Comment by cfm999** [comment]
请问，如何传递的？
再三搜索未获有关信息，研究JEditable.vue及JPopup也未找到方法，还请指教，谢谢！

**Comment by kongshanchat** [comment]
@zhangdaiscott 冒昧请教是如何传递参数呢，

此外 2.0新版本在技术文档中j-popup组件引用jeecgBiz目录下j-popup，但在实际源码中未发现j-popup.vue组件,文档和源代码部分不一致

![image](https://user-images.githubusercontent.com/24310433/81144404-8fe95c80-8fa6-11ea-99cd-a7978ddb1071.png)

**Comment by javaAjun** [comment]
就这?
