### ISSUE TITLE
为什么不能加技术交流群？

### ISSUE THREAD

**Issue by yeehan711** [zhangdaiscott/jeecg-boot#1148]
为什么不能加技术交流群？

**Comment by zhangdaiscott** [comment]
Jeecg-Boot交流群： ②769925425、①284271917（满）

**Comment by yeehan711** [comment]
验证问题答案是什么？输入JeecgBoot ,提示：群主拒绝添加任何人。


 原始邮件 
发件人: JEECG开源社区<notifications@github.com>
收件人: zhangdaiscott/jeecg-boot<jeecg-boot@noreply.github.com>
抄送: yeehan<leecheng711@126.com>; Author<author@noreply.github.com>
发送时间: 2020年5月3日(周日) 12:46
主题: Re: [zhangdaiscott/jeecg-boot] 为什么不能加技术交流群？ (#1148)


Jeecg-Boot交流群： ②769925425、①284271917（满）
