### ISSUE TITLE
建议添加图片上传预览组件以及markdown.

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#115]
如果可以的话可以是做成可装卸的方式，不过我觉得集成在一起应该也没啥问题

建议 图片是可以预览的那种图片，多图预览显示，如#103 那样的结果。
tinymce 很好，可能很多人还需要百度的ueditor以及一个markdown 编译器。
![image](https://user-images.githubusercontent.com/27263086/57936006-972adc80-78f5-11e9-871b-200d46c06230.png)

**Comment by zhangdaiscott** [comment]
3Q 暂时只做图片预览功能
