### ISSUE TITLE
# 启动 yarn run serve

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#1151]
##### 版本号：
2.1.4 update to 2.2.0

##### 问题描述：
<s> [webpack.Progress] 98% after emitting
<s> [webpack.Progress] 98% after emitting CopyPlugin
 ERROR  Failed to compile with 1 errors2:41:38

This dependency was not found:

* @/components/jeecg/JGraphicCode in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/user/Login-bad.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @/components/jeecg/JGraphicCode
<s> [webpack.Progress] 100% 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61414528/80922726-80ed8900-8db1-11ea-8478-d18e17ba7922.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
新版删除了JGraphicCode，你可以手工加回来
