### ISSUE TITLE
升级代码生成器依赖，支持返回生成结果&支持服务器端生成代码config

### ISSUE THREAD

**Issue by baixinan** [zhangdaiscott/jeecg-boot#1152]
##### 问题描述：
升级文档中：“升级代码生成器依赖，支持返回生成结果&支持服务器端生成代码config”，这句话的意思是这个版本在断网条件下，代码生成器模块无法生成代码吗？
这句话能否解释一下，谢谢！

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
解决的这个俩问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1010
https://github.com/zhangdaiscott/jeecg-boot/issues/865

**Comment by zhangdaiscott** [comment]
使用文档
http://doc.jeecg.com/1684391
