### ISSUE TITLE
前端发布后在访问nginx的情况下，新添加的vue文件访问不到。

### ISSUE THREAD

**Issue by CodingJason** [zhangdaiscott/jeecg-boot#1153]
##### 版本号：
2.1.4

##### 问题描述：
新增helloworld页面，使用jar包发布方式，前端发布到nginx之后，新的页面访问不到。

##### 截图&代码：

添加的新的vue页面
![image](https://user-images.githubusercontent.com/3403239/80990485-f8322400-8e68-11ea-8682-0b9e5f196774.png)
本地配置
![image](https://user-images.githubusercontent.com/3403239/80991077-0f254600-8e6a-11ea-9336-d78ad8e7c68f.png)

yarn run serve 可以访问
![image](https://user-images.githubusercontent.com/3403239/80990778-83131e80-8e69-11ea-8797-13e047a3ee8f.png)

但是,yarn run build 并且上传到服务器，并且布到nginx 之后。配置菜单也无法访问.
服务器配置。
![image](https://user-images.githubusercontent.com/3403239/80990954-dbe2b700-8e69-11ea-8f95-166e53411e36.png)
但是点击没有反应，无法跳转
![image](https://user-images.githubusercontent.com/3403239/80991162-32e88c00-8e6a-11ea-9ccd-d0561fe0f6d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
发布问题

**Comment by CodingJason** [comment]
> 发布问题

是yarn打包的问题么？
