### ISSUE TITLE
这个版本还是没有解决-online 基础篇-SQL增强部分变量可用的问题

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#1154]
##### 版本号：
2.2.0

##### 问题描述：
http://doc.jeecg.com/1276930
online 基础篇-SQL增强

#{sys_date} | 系统日期"yyyy-MM-dd" 不能使用

#{sys_time} | 系统时间"yyyy-MM-dd HH:mm" 不能使用

比如：insert purchase (create_time,create_by) values ('#{sys_time}','#{sys_user_code}');
其中#{sys_time}出问题了。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/61414528/80987607-dcc51a00-8e64-11ea-8936-3438325ff38a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
问题已修复，下个版本发布
