### ISSUE TITLE
online 下拉搜索框/校验字段/字典table写法（变量）

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#1155]
##### 版本号：
2.2.0

##### 问题描述：
 XX表 where  sales ='#{sys_user_code}'无效
需要@Param注解来声明参数？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61414528/80998248-2f0e3700-8e75-11ea-9f98-4b36ab46c18d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
