### ISSUE TITLE
登录失效，一段时间内（半小时左右）不操作，就会报“很抱歉，登录已过期，请重新登录”。

### ISSUE THREAD

**Issue by linekite** [zhangdaiscott/jeecg-boot#1156]
##### 版本号：
2.1.4

##### 问题描述：
登录失效，一段时间内（半小时左右）不操作，就会报“很抱歉，登录已过期，请重新登录”。
但是看代码，token设置的超时时间是7天。
##### 截图&代码：

![image](https://user-images.githubusercontent.com/14540108/81088368-6e985a00-8f2d-11ea-9cfb-cd4085164c61.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
org.jeecg.common.system.util.JwtUtil
默认半小时
`public static final long EXPIRE_TIME = 30 * 60 * 1000;`
