### ISSUE TITLE
动态报表变量问题

### ISSUE THREAD

**Issue by mysuplover** [zhangdaiscott/jeecg-boot#1157]
##### 问题描述：boot版本不支持动态报表中sql变量替换的问题，
之前可以如下操作:
SELECT t.*,isscode as tcode FROM VW_MERCHANTINFO t where {code} and {isscode} and {whman} and {whdepartcode} and {fzdepartcode} and {devlman}
请问什么时候能支持？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用法错误，参考官方文档
http://doc.jeecg.com/1273862
