### ISSUE TITLE
分类字典信息修改时值没有带过来。

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1159]
##### 问题描述：
在分类字典管理中，修改一条信息后，然后再点击另一条信息修改，这时候的弹框内容是空的，没有带过来。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把列表页面关掉，重新进入试试，vue页面有缓存

**Comment by jave-joe** [comment]
> 把列表页面关掉，重新进入试试，vue页面有缓存

列表页面关掉后，第一次点击修改的时候正常，只要修改完后，再点击修改的话，弹出的表单内容就是空的，console有警告：

Warning: You cannot set a form field before rendering a field associated with the value. You can use `getFieldDecorator(id, options)` instead `v-decorator="[id, options]"` to register it before render.

**Comment by zhangdaiscott** [comment]
空的？录个gif看看

**Comment by jave-joe** [comment]
> 空的？录个gif看看

已经解决，但是不知道是什么原因导致，
我在赋值的时候让等待了一下，然后再赋值，就好了。
this.$nextTick(() => {
          setTimeout(() => {
            this.form.setFieldsValue(pick(this.model,'pid','name','code','description'))
          }, 150)
        })
