### ISSUE TITLE
省级三级联动生成代码后无效

### ISSUE THREAD

**Issue by He-Xiao-Bo** [zhangdaiscott/jeecg-boot#1161]
##### 问题描述：

最新系统online 在线测试支持三级联动，但是生成代码，代码放在前后端，三级联动无效果，online有这个功能，是不是这个要jeecgboot免费版不支持

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
三级联动生成的代码太繁琐，不如自己实现的简洁，所以没生成
