### ISSUE TITLE
jeecg-boot开源框架集成问题

### ISSUE THREAD

**Issue by coral963** [zhangdaiscott/jeecg-boot#1162]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/64893193/81249629-ad273500-9051-11ea-92d6-9da3d745c400.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请多看文档
http://doc.jeecg.com/1273851

微服务得自己改造
