### ISSUE TITLE
部门选择组件自定义返回值，数据无法回填

### ISSUE THREAD

**Issue by mo-bie** [zhangdaiscott/jeecg-boot#1163]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/31677968/81266689-c7740980-9077-11ea-978a-46d902571e27.png)
![image](https://user-images.githubusercontent.com/31677968/81266874-2043a200-9078-11ea-91bf-6fdd87c7bc06.png)
![image](https://user-images.githubusercontent.com/31677968/81266912-33ef0880-9078-11ea-90f9-211c409c9f46.png)

指定返回orgCode，保存到数据库的也是orgCode，但是在重新修改数据时，回填的值也是code，所以树组件没有勾选，部门名称也没有回填。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mo-bie** [comment]
![image](https://user-images.githubusercontent.com/31677968/81267400-fccd2700-9078-11ea-8976-1aec4bae65b3.png)
在JSelectDepart中修改了代码，首次打开部门选择窗时无法回填，但是关闭重新打开后就可以回填了。。。

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
