### ISSUE TITLE
一个用户有多个部门，但是只能分配一个部门角色，新角色进来，旧角色会被删除

### ISSUE THREAD

**Issue by 1677612666** [zhangdaiscott/jeecg-boot#1164]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/25949648/81267439-12425100-9079-11ea-9843-c14f1b6789d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本
