### ISSUE TITLE
上传组件J-upload设置单个文件上传

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#1165]
##### 版本号：
2.1.4

##### 问题描述：
J-upload组件设置number=1，无效，还是能够选择多个文件

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58909486/81272633-4d944e00-9080-11ea-890a-ddeebb3d48e3.png)

![image](https://user-images.githubusercontent.com/58909486/81272669-5c7b0080-9080-11ea-8c2c-d893fcb0b415.png)

![image](https://user-images.githubusercontent.com/58909486/81273040-e5923780-9080-11ea-8427-31604960f253.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
新版本已解决
