### ISSUE TITLE
联动组件在生成代码后没有效果？

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1166]
##### 问题描述：
在表单配置中，把某项配置成联动组件，按照官方在线配置的那种格式去配置对应的联动条件，
在生成代码后，针对联动组件这块好像没有生成对应的效果，modal里直接是个input框，是这块在代码生成中没有实现还是我这边配置的有问题呢？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1161
