### ISSUE TITLE
自增的主键id表设计生成的表单不能提交

### ISSUE THREAD

**Issue by qq471754603** [zhangdaiscott/jeecg-boot#1167]
##### 版本号：
 2.2.0

##### 问题描述：
自增的主键id表设计生成的表单不能提交

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23146592/81319272-02029400-90c2-11ea-92c8-36563e970321.png)
![image](https://user-images.githubusercontent.com/23146592/81319281-06c74800-90c2-11ea-9710-4ec5eb7330d9.png)

**Comment by qq471754603** [comment]
![Uploading image.png…]()

**Comment by qq471754603** [comment]
业务需要 不能把表改成String 类型,36长度

**Comment by ifzm** [comment]
兄弟你怎么解决的？

**Comment by qq471754603** [comment]
我是改那个主键的方式auto的那个



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jim"<notifications@github.com&gt;; 
发送时间: 2020年7月16日(星期四) 下午5:38
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "Luckly hu"<471754603@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 自增的主键id表设计生成的表单不能提交 (#1167)





 
兄弟你怎么解决的？
