### ISSUE TITLE
validatorRules和initialValue有冲突,只能有一个生效.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1168]
##### 版本号：
2.2.0

##### 问题描述：
如果validatorRules在前,则检查生效,如果initialValue在前,则initialValue生效.
不能同时起作用.

```
v-decorator="['memorySize',validatorRules.memorySize, {'initialValue':2}]"
```

```
validatorRules: {
memorySize: {
            rules: [
              { required: true, message: '请存储大小!'},
            ]
          },
}
```
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
代码错误
正确写法：
v-decorator="['carName', validatorRules.carName]"
carName: {
            initialValue:'2',
            rules: [
              { required: true, message: '请输入车辆名称!'},
            ]
          },
