### ISSUE TITLE
2.2版本online开发生成的代码列表展示报错

### ISSUE THREAD

**Issue by heidongzai** [zhangdaiscott/jeecg-boot#1169]
##### 版本号：
2.2

##### 问题描述：

2.2版本online开发生成的代码列表展示报错
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19759686/81364790-1920a080-9119-11ea-9352-3edc93e40561.png)
![image](https://user-images.githubusercontent.com/19759686/81364802-2178db80-9119-11ea-92b7-d3b69f5eafe9.png)
![image](https://user-images.githubusercontent.com/19759686/81364810-25a4f900-9119-11ea-9101-f48e505a6cca.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你为什么会调用这个方法，确认下
![image](https://user-images.githubusercontent.com/3162115/81365296-4de12780-911a-11ea-814c-4336dc2ca351.png)

**Comment by heidongzai** [comment]
找到原因了，MybatisPlusConfig里面没有配新生成的mapper
