### ISSUE TITLE
tabs组件,使用卡片样式失效.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1170]
##### 版本号：
2.2.0

##### 问题描述：
<a-tabs v-model="activeKey" @change="handleChangeTabs" type="card">
无法显示ant的卡片样式.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请按照要求发截图

**Comment by realcjames** [comment]
同遇到这个问题了。。应该是被多页签模式里面的样式给覆盖了

**Comment by zhangdaiscott** [comment]
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，的确是样式冲突的问题，将在下个版本更新。

手动修复参考：
![image](https://user-images.githubusercontent.com/34293221/82194045-cae57b80-9928-11ea-814d-adf6411a39e2.png)

**Comment by GordonHuangYong** [comment]
![图片](https://user-images.githubusercontent.com/20039800/83089305-99a74100-a0c8-11ea-97e3-46218386f93e.png)
![图片](https://user-images.githubusercontent.com/20039800/83089319-a2981280-a0c8-11ea-9bb1-939e58858a62.png)
![图片](https://user-images.githubusercontent.com/20039800/83089370-be031d80-a0c8-11ea-931d-295c89c68310.png)

貌似不起作用.
