### ISSUE TITLE
多数据源下，Online在线表单开发--更多--功能测试

### ISSUE THREAD

**Issue by Lude-King** [zhangdaiscott/jeecg-boot#1171]
##### 版本号：
V2.2.0

##### 问题描述：
**Online在线表单开发--更多--功能测试。**
因为配置了多个数据源，且当前自动生成的表并不在jeecg_boot库中，如果我想使用该功能，是必须要把这个表移动到jeecg_boot数据库里吗？目前通过查看官方文档并未找到答案，想知道当前有没有支持多数据源的方案呢？期待大神回复

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13196829/81377304-c9050680-9137-11ea-84b9-939dcafe65d5.png)
![image](https://user-images.githubusercontent.com/13196829/81377393-f651b480-9137-11ea-95bb-0d74f646188d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
Online在线表单开发  不支持多数据源

**Comment by blissnmx** [comment]
借楼主帖子
请问数据大屏的数据源有计划支持prometheus吗？
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
可以在积木报表项目，提需求issue
