### ISSUE TITLE
树控件自动生成代码功能测试里面可以，生成了却 是普通文本框

### ISSUE THREAD

**Issue by daixianlong** [zhangdaiscott/jeecg-boot#1172]
##### 版本号：
2.2.0

##### 问题描述：
树控件自动生成代码功能测试里面可以，生成了却 是普通文本框

##### 截图&代码：
功能测试
![image](https://user-images.githubusercontent.com/64056003/81394689-ebf1e380-9154-11ea-97bf-e030adfcac01.png)
实际生成
![image](https://user-images.githubusercontent.com/64056003/81394827-2eb3bb80-9155-11ea-8a2e-a41dc4d3f117.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自定义树控件不支持，需要手工实现
