### ISSUE TITLE
发现org.jeecgframework.poi.excel这个包在私服中没有了，导致启动失败！

### ISSUE THREAD

**Issue by wangminli** [zhangdaiscott/jeecg-boot#1174]
##### 版本号：
 2.2.0

##### 问题描述：
发现org.jeecgframework.poi.excel这个包在私服中没有了，导致启动失败！

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/5483360/81420032-dcd55a80-9181-11ea-8e87-4e86bcf99de3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你依赖没下下载好

**Comment by mll120110** [comment]
我也遇到相同问题，本地maven仓库配置的是阿里云仓库节点。
