### ISSUE TITLE
JEditableTable.vue卡顿原因之一buildProps

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1177]
##### 版本号：
2.2.0

##### 问题描述：
JEditableTable.vue中, 修改表格任意的数据, 都会导致每个单元格都调用一次buildProps.
行*列越多, 调用越多,多次调用,性能下降.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经计划重构行编辑组件

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1178

**Comment by GordonHuangYong** [comment]
能否在当前版本, 解决这个问题,等不及重构 了.

**Comment by zhangdaiscott** [comment]
近期会出简单的方案，保持平滑升级

**Comment by zhangdaiscott** [comment]
覆盖这俩文件就可以了
src/utils/util.js
src/components/jeecg/JEditableTable.vue

[Desktop.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4648963/Desktop.zip)

**Comment by GordonHuangYong** [comment]
问题解决了一半, 编辑或点击行时,没问题了.
滚动时,还是会卡顿;

**Comment by zhangdaiscott** [comment]
在酝酿更深度的重构，请等待

**Comment by liuwenfei-afk** [comment]
这个问题修复了吗
