### ISSUE TITLE
在线开发，下拉搜索bug

### ISSUE THREAD

**Issue by rosskalif** [zhangdaiscott/jeecg-boot#1181]
##### 问题描述：
在线开发，配置一张表的多个关联表下拉搜索时，新增编辑有的下拉不正常显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44200156/81520762-c42e9580-9377-11ea-8c38-dc480cfa66d8.png)
![image](https://user-images.githubusercontent.com/44200156/81520846-ff30c900-9377-11ea-8d60-44863de6b9bc.png)
![image](https://user-images.githubusercontent.com/44200156/81520871-18d21080-9378-11ea-93a8-bb6e652658bd.png)

数据库sqlserver
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的意思，存在多个下拉搜索控件的情况下，有问题？

**Comment by rosskalif** [comment]
是的，userid在新增或编辑时没有变成下拉框，但是设置成查询时都可以下拉

**Comment by lvdandan16** [comment]
我这里试了一下，未复现这个问题，可确认一下页面属性中控件类型是否设为了下拉框
