### ISSUE TITLE
@Cacheable(value = CacheConstant.SYS_DICT_TABLE_CACHE)缓存并没有起作用

### ISSUE THREAD

**Issue by guanyufen123** [zhangdaiscott/jeecg-boot#1182]
##### 版本号：
2.1.5
感觉新版本也存在这个问题
##### 问题描述：
在org.jeecg.modules.system.service.impl.queryTableDictByKeys 的方法上用了redis缓存，但是这个缓存并没有起到作用。每次查询总会新建key。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41617530/81530466-850e3d80-9393-11ea-8f4f-176a6fb9cc78.png)

访问案例中自定义组件的下拉树多选
![image](https://user-images.githubusercontent.com/41617530/81530667-e504e400-9393-11ea-821d-485be6f98b47.png)
。两次选择相同的，清空后再选1次。

redis结果：
第一次点击：
![image](https://user-images.githubusercontent.com/41617530/81530938-678da380-9394-11ea-8636-0617c85422a0.png)

第二次：

![image](https://user-images.githubusercontent.com/41617530/81531005-8429db80-9394-11ea-934f-9e9402a7a952.png)

**Comment by zhangdaiscott** [comment]
应该是这个问题
https://github.com/zhangdaiscott/jeecg-boot/issues/994

**Comment by guanyufen123** [comment]
> 应该是这个问题
> [＃994](https://github.com/zhangdaiscott/jeecg-boot/issues/994)

但是我按照那个问题的解决办法修改了下。
![image](https://user-images.githubusercontent.com/41617530/81532403-e4ba1800-9396-11ea-9bbb-3690acf03258.png)

也是重新创建key。

**Comment by zhangdaiscott** [comment]
重新创建是对的，这个就是按照参数生成不同的key

**Comment by guanyufen123** [comment]
> 重新创建是对的，这个就是按照参数生成不同的key

那样的话，这个缓存就没有意义了，这访问一次生成一次。缓存不就没有存在的必要了 吗

**Comment by guanyufen123** [comment]
> 重新创建是对的，这个就是按照参数生成不同的key

这个参数有个是数组，数组每次的地址都是不同的，所以即使两次访问数组内部数据一样，也不会从缓存中获取。

**Comment by zhangdaiscott** [comment]
可以先手工把参数类型改成字符串。
具体下个版本发布修改

taoyan367@
![image](https://user-images.githubusercontent.com/3162115/83098784-1bee3000-a0de-11ea-96b4-36ff8b70d538.png)

**Comment by guanyufen123** [comment]
> 可以先手工把参数类型改成字符串。
> 具体下个版本发布修改
> 
> ![image](https://user-images.githubusercontent.com/3162115/83098784-1bee3000-a0de-11ea-96b4-36ff8b70d538.png)

好的，谢谢大佬
