### ISSUE TITLE
JAreaLinkage 省市区选择组件数据回填间隔失效

### ISSUE THREAD

**Issue by mo-bie** [zhangdaiscott/jeecg-boot#1183]
##### 问题描述：
JAreaLinkage 省市区选择组件数据回填间隔失效
使用代码生成，在编辑数据的 FormModal 中省市区选择组件间隔出现无法回填，也就是每间隔一次打开 FormModal 时，JAreaLinkage 中的 value 没有赋值（第一次回填成功，第二次失败第三次成功，后边循环）
追踪代码时可以看到 JAreaLinkage 中 value 的监听值为 undefined

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，将在下个版本更新

**Comment by zhangdaiscott** [comment]
着急的话，可以下载覆盖
[Uploading JAreaLinkage.zip…]()
