### ISSUE TITLE
hbuildx打包后导出功能下载失败

### ISSUE THREAD

**Issue by ngc010** [zhangdaiscott/jeecg-boot#1185]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述太简单

**Comment by ngc010** [comment]
问题描述：使用hbuilderx打包为app后安装到手机上，登录系统后点击导出按钮 导出excel，会提示是否下载，点击下载后 会收到提示 下载失败。 
![1](https://user-images.githubusercontent.com/13461011/82111934-1528fa00-977b-11ea-8c8f-095a00307b6b.jpg)
![2](https://user-images.githubusercontent.com/13461011/82111922-05111a80-977b-11ea-9de8-abb1f8dbbbd5.jpg)
