### ISSUE TITLE
后台找不到jar 去了jeecg的私服也没有下载到

### ISSUE THREAD

**Issue by CSuperC** [zhangdaiscott/jeecg-boot#1187]
##### 版本号：

2.2 jeecgboot 5.6日发布的master分支
##### 问题描述：

找不到三个jar hibernate-re 2.1.5 ，codegenratejar 1.2.0  autopoi-web 1.1.1
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273965

**Comment by CSuperC** [comment]
使用了这个私服地址，依然找不到jar maven clean install -U

**Comment by CSuperC** [comment]
@zhangdaiscott 我试了私服，私服地址里面，找不到三个jar 
 hibernate-re 2.1.5 ，codegenratejar 1.2.0 autopoi-web 1.1.1 这三个jar

**Comment by zhangdaiscott** [comment]
说明你配置有问题，其他人都可以

**Comment by CSuperC** [comment]
@zhangdaiscott
这是我本地的maven 仓库配置  之前版本的maven需要的包，我都下载下来了，这次的新版本，依赖的包，找不到啊 hibernate-re 2.1.5 ，codegenratejar 1.2.0 autopoi-web 1.1.1 这三个jar，之前的hibernate-re 2.1.4，等autopoi-web 1.0.5都下载下来了
That repository definition will have a unique id, so we can create a mirror reference for that
   | repository, to be used as an alternate download site. The mirror site will be the preferred
   | server for that repository.
   |-->
  <mirrors>
        <mirror>
            <id>nexus-aliyun</id>
            <mirrorOf>*,!jeecg,!jeecg-snapshots</mirrorOf>
            <name>Nexus aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror>
  </mirrors>


  <!-- profiles
   | This is a list of profiles which can be activated in a variety of ways, and which can modify
   | the build process. Profiles provided in the settings.xml are intended to provide local machine-
   | specific paths and repository locations which allow the build to work in the local environment.
   |
   | For example, if you have an integration testing plugin - like cactus - that needs to know where

**Comment by CSuperC** [comment]
@zhangdaiscott 可以了，问题找到了，我们公司的网络进行限制了，所以获取不到这个私服地址的jar
