### ISSUE TITLE
分类字典在online功能测试可以，但是用代码生成器后没有效果

### ISSUE THREAD

**Issue by He-Xiao-Bo** [zhangdaiscott/jeecg-boot#1189]
##### 版本号：

2.0.0
##### 问题描述：
分类字典在online功能测试可以，但是用代码生成器后没有效果，列表都展示id，新增那里也没有出现下拉选项，

##### 截图&代码：
<img width="757" alt="Capture" src="https://user-images.githubusercontent.com/25975216/81643003-40e47100-9457-11ea-885a-a2a37aecb1ff.PNG">

![image](https://user-images.githubusercontent.com/25975216/81643218-b6504180-9457-11ea-81f4-3ea93a6ca5eb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by He-Xiao-Bo** [comment]
联动组件在配置数据字典后，代码里面好像并没有显示

**Comment by zhangdaiscott** [comment]
联动组件不支持生成

**Comment by He-Xiao-Bo** [comment]
是要商业版版才支持生成吗

**Comment by He-Xiao-Bo** [comment]
联动组件不支持生成，那分类字典其不是没有用到实际开发代码，是要企业版jeecg才可以吗??
