### ISSUE TITLE
默认配置修改无效

### ISSUE THREAD

**Issue by cnbizhh** [zhangdaiscott/jeecg-boot#119]
defaultSetting.js 配置修改无效
![image](https://user-images.githubusercontent.com/7309951/58008664-75ad3900-7b1f-11e9-9c4f-9a1113c778a4.png)

**Comment by zhangdaiscott** [comment]
清缓存，F5刷新首页

**Comment by cnbizhh** [comment]
谷歌浏览器 强制清过缓存，无痕模式 都尝试过 没有效果

**Comment by zhangdaiscott** [comment]
多少版本

**Comment by cnbizhh** [comment]
浏览器版本 72.0.3626.109（正式版本） （64 位）
程序版本 master

**Comment by zhangdaiscott** [comment]
jeecgboot

**Comment by cnbizhh** [comment]
当前最新版本： 2.0.0（发布日期：20190520）

**Comment by tygithub1** [comment]
没办法，就是有bug，你可以照下面步骤试一下（以主题色为例）：
1.设置defaultSetting.js 中的参数 primaryColor: '#F5222D',
2.清除浏览器缓存访问,这个时候主题色没变，还是蓝色
3.再次修改defaultSetting.js 中的主题色primaryColor: '#1890FF', 访问 他会变成红色

**Comment by tygithub1** [comment]
这项目他在mian.js中有一堆类似如下的代码
store.commit('TOGGLE_COLOR', Vue.ls.get(DEFAULT_COLOR, config.primaryColor))
意思是将从 Vue.ls中取值 如果没有则设置config即defaultSetting.js 中的primaryColor
第一次无缓存访问他是走的defaultSetting.js中的配置
但是坑爹的是src\components\setting\SettingDrawer.vue这个主题设置文件中有如下一段代码
```
      // 当主题色不是默认色时，才进行主题编译
      if (this.primaryColor !== config.primaryColor) {
        updateTheme(this.primaryColor)
      }
      if (this.colorWeak !== config.colorWeak) {
        updateColorWeak(this.colorWeak)
      }
      if (this.multipage !== config.multipage) {
        this.$store.dispatch('ToggleMultipage', this.multipage)
      }
```
这里的this.primaryColor 取的是vue.ls中的数据，也就是说在浏览器无缓存状态下访问的时候，defaultSetting.js 中的值就是vue.ls中的值，那么他将不走update方法，那么第一次设置vue-ls了，第二次修改defaultSetting.js为另外一个值，就会走update主题了。

**Comment by cnbizhh** [comment]
![image](https://user-images.githubusercontent.com/7309951/58870114-20ae1d00-86f2-11e9-9903-d994bd8c2b36.png)
![image](https://user-images.githubusercontent.com/7309951/58870154-36bbdd80-86f2-11e9-8a0e-524b8558a164.png)
再把 文件的样式调整一致就可以

**Comment by zhangdaiscott** [comment]
https://ant.design/docs/react/customize-theme-cn


![image](https://user-images.githubusercontent.com/3162115/58957269-dbade780-87d2-11e9-9bcb-af8b25eba2a4.png)
