### ISSUE TITLE
Online表单开发报错：很抱歉，资源未找到，接口访问404

### ISSUE THREAD

**Issue by leetone123** [zhangdaiscott/jeecg-boot#1190]
##### 版本号：
2.2.0

##### 问题描述：
Online表单开发报错：很抱歉，资源未找到，接口访问404

##### 截图&代码：
`http://localhost:8080/online/cgform/head/list?_t=1589270704&column=createTime&order=desc&field=id,,,tableType,tableName,tableTxt,tableVersion,isDbSynch,createTime,action&pageNo=1&pageSize=10&copyType=0`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
