### ISSUE TITLE
报表设计-大屏设计器问题

### ISSUE THREAD

**Issue by zilong-zhou** [zhangdaiscott/jeecg-boot#1194]
##### 问题描述：

1.在你们项目中做出来的可视化图形怎么把他变为自己的页面
2.动态数据，拿自己的接口数据为什么不能显示在你们的页面上

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个不建议这么去用，因为boot.jeecg.com 是演示环境，数据会定期清理

**Comment by GavinGooge** [comment]
请问，开源版本里，有大屏设计器吗？

**Comment by zhangdaiscott** [comment]
没有，可以使用 http://www.jimureport.com
在线免费用
