### ISSUE TITLE
部署jeecg-boot的问题

### ISSUE THREAD

**Issue by husg2008** [zhangdaiscott/jeecg-boot#1195]
##### 问题描述：内网中Dell服务器的tomcat发布了服务a,端口号为8082,分别配置以下几处：
1)菜单配置访问地址设为：http://内网IP:8082/a;
2)然后在nginx.conf配置(图1);
3)在public的index.html中配置接口(图2)：
但是最终访问菜单a的服务，内网可以访问，外网访问不到，请问还需要哪里配置或者修改呢？
##### 截图&代码：
图1
![image](https://user-images.githubusercontent.com/28718944/81795122-57b1c300-953e-11ea-8353-e073816e38dc.png)
图2
![image](https://user-images.githubusercontent.com/28718944/81795201-731cce00-953e-11ea-88af-b8edda73cd5f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台接口，也得开通外网的权限。
