### ISSUE TITLE
默认跳转路由

### ISSUE THREAD

**Issue by camieZ** [zhangdaiscott/jeecg-boot#1197]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/24276028/81917991-81cfb780-9608-11ea-8563-d38a6fed9892.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by camieZ** [comment]
设置为null和空字符串都无效

**Comment by zhangdaiscott** [comment]
mybaits设置空值不处理，目前只能手工改数据库
