### ISSUE TITLE
建议把启动项目下放到自定义模块

### ISSUE THREAD

**Issue by kaybinwong** [zhangdaiscott/jeecg-boot#1198]
##### 版本号：
2.2.0

##### 问题描述：
需要引用system类，但system模块又需要引用自定义模块，导致循环依赖

##### 截图&代码：

建议把启动项目下放到自定义模块。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的用法不对
http://doc.jeecg.com/1273938
