### ISSUE TITLE
找回密码时短信验证码存Redis没有设置过期时间，造成之后都无法发送验证码

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#1199]
##### 版本号：
2.1.3   2.2.0

##### 问题描述：
SysUserController中phoneVerification，短信验证码存Redis未设置过期时间，造成以后登陆等需要验证码时都会提示验证码未过期，无法获取新的验证码。我是用的2.1.3，看了下代码2.2.0这个问题应该也存在

##### 截图&代码：
![bug](https://user-images.githubusercontent.com/44466941/82001244-4f1bd280-968d-11ea-84e5-b6a4e8670cb0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
问题已修复，将在下个版本更新
