### ISSUE TITLE
online表单开发问题

### ISSUE THREAD

**Issue by rosskalif** [zhangdaiscott/jeecg-boot#1200]
##### 问题描述：
**在线开发问题：**
1.当一张表有多个外键时，导致所有主表都不能正常浏览子表数据；
比如C表数据来源与A表和B表的关系组合，即C表为A·B表的关系表，存在2个外键（即A表和B表的主键--根据在线表单设计配置）
再保存附表时，只能更新其中一个主表的附表值（即只能再A表或B表的配置附表框其中一个出现附表的表名）
2.当在线开发时，一张表在未设置为主表时，字段配置为某个数据字典时（枚举下拉值）可以正常下拉数据，但是当把这张表配置为主表即存在子表时，有配置数据字典的字段不生效了，不能下拉了

##### 截图&代码：
1.一张表多个外键：
跟踪出来会发现语句组合时，条件组合了多个外键表的值，而不是当前选中的主表记录的那条值，
比如：SELECT proccode,userid FROM proctouser where 1=1   AND proccode= 'GSX010'  AND userid=2 ORDER BY create_time desc；可以发现 本来应该只传递主表proccode的值GSX010就够了，结果有组合了另一个外键表userinfo表的ID的值给该关系表userid赋值2,导致不能查询出数据
2，主表模式下，数据字典不能正常下拉
![image](https://user-images.githubusercontent.com/44200156/82002296-04e82080-9690-11ea-8da7-5371d03a1dcb.png)
指定查询能正常下拉
![image](https://user-images.githubusercontent.com/44200156/82002386-395bdc80-9690-11ea-9564-2cff5e40be65.png)
但是在新增或编辑时，页面报错，不能下拉
![image](https://user-images.githubusercontent.com/44200156/82002571-acfde980-9690-11ea-888f-150cad89a796.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
问题1：目前一个子表只支持一个外键即对应一个主表，这个问题修改比较麻烦，计划后续会修改
问题2：已修复，将在下个版本更新
