### ISSUE TITLE
登录页面在IE下，用户名密码不显示

### ISSUE THREAD

**Issue by wuchangrong** [zhangdaiscott/jeecg-boot#1203]
##### 版本号：
2.2.0

##### 问题描述：

登录页面在IE下，用户名密码不显示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30275850/82062487-c5a3e900-96fc-11ea-9be0-9c4e4b527d6a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这边支持IE11+

**Comment by wuchangrong** [comment]
报错信息如下：

[Vue warn]: Error in created hook: "TypeError: 对象不支持“values”属性或方法"

found in

---> <AFormItem>
       <AForm>
         <Login> at src/views/user/Login.vue
           <RouteView> at src/components/layouts/RouteView.vue
             <UserLayout> at src/components/layouts/UserLayout.vue
               <ALocaleProvider>
                 <LocaleReceiver>
                   <AConfigProvider>
                     <App> at src/App.vue
                       <Root>

**Comment by fangyueben** [comment]
解决了吗？

**Comment by wuchangrong** [comment]
解决了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午4:43
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"老巫"<13385445@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 登录页面在IE下，用户名密码不显示 (#1203)





 
解决了吗？

**Comment by yijian0645** [comment]
意思是IE11以上才支持?IE11不支持是吗？？我让我同事的IE11访问也一样的问题
