### ISSUE TITLE
前端页面有告警：Warning: [antdv: LocaleProvider] `LocaleProvider` is deprecated. Please use `locale` with `ConfigProvider` instead

### ISSUE THREAD

**Issue by wuchangrong** [zhangdaiscott/jeecg-boot#1204]
##### 版本号：
2.2.0

##### 问题描述：
Warning: [antdv: LocaleProvider] `LocaleProvider` is deprecated. Please use `locale` with `ConfigProvider` instead

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by kaybinwong** [comment]
ant版本升级问题，不影响使用。可以更改App.vue
local-provider > config-provider

**Comment by zhangdaiscott** [comment]
good
