### ISSUE TITLE
JEdittable加载数据问题

### ISSUE THREAD

**Issue by kaybinwong** [zhangdaiscott/jeecg-boot#1205]
##### 版本号：
2.2.0

##### 问题描述：
JEdittable加载Formtypes.select数据时，未能选中，而是显示value

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5570216/82065975-5c72a480-9701-11ea-9bcd-0027b8738371.png)

````
            {
              title: '商品',
              key: 'goodsId',
              type: FormTypes.select,
              dictCode: "erp_goods,name,id",
              allowSearch: true,
              width:"200px",
              placeholder: '请输入${title}',
              defaultValue: '',
              validateRules: [{ required: true, message: '${title}不能为空' }],
            },
````

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
并没有复现出你的这个问题，请给出具体的复现方式。
请确认数据库的配置正确，`erp_goods`中是否包含`name`和`id`两个字段

![image](https://user-images.githubusercontent.com/34293221/82185610-0fb6e580-991c-11ea-91fa-86a023e707b7.png)

![image](https://user-images.githubusercontent.com/34293221/82185473-d5e5df00-991b-11ea-9ca2-c1744b6e2648.png)

**Comment by kaybinwong** [comment]
是有这两个字段的，明天我贴完整代码。另外看截图显示张三，name又是uuid，是不是name要是商品ID才行，而不是商品名称？

**Comment by sjlei** [comment]
> 是有这两个字段的，明天我贴完整代码。另外看截图显示张三，name又是uuid，是不是name要是商品ID才行，而不是商品名称？

我是按照你图里的写法写的`dictCode`，以为你知道这种表字典的写法。
简单说明一下这个写法，`demo,name,id`，`demo`是表名，`name`是显示text，`id`是存储到数据里老爹value，所以我截图中的显示的张三，保存的是id

**Comment by kaybinwong** [comment]
> > 是有这两个字段的，明天我贴完整代码。另外看截图显示张三，name又是uuid，是不是name要是商品ID才行，而不是商品名称？
> 
> 我是按照你图里的写法写的`dictCode`，以为你知道这种表字典的写法。
> 简单说明一下这个写法，`demo,name,id`，`demo`是表名，`name`是显示text，`id`是存储到数据库里的value，所以我截图中的显示的张三，保存的是id

我上面没表述好，
我的意思是你截图的name是显示UUID，而不是张三。
实际上现在使用就是你所说的，name是商品名称，id是商品id。
![image](https://user-images.githubusercontent.com/5570216/82276197-2bbb9500-99b7-11ea-9be8-42aa5e7ffc16.png)

见附件
[PoBillList.txt](https://github.com/zhangdaiscott/jeecg-boot/files/4647782/PoBillList.txt)
[PoBillModal.txt](https://github.com/zhangdaiscott/jeecg-boot/files/4647784/PoBillModal.txt)
[erp_goods.sql.txt](https://github.com/zhangdaiscott/jeecg-boot/files/4647790/erp_goods.sql.txt)

**Comment by sjlei** [comment]
> 另外看截图显示张三，name又是uuid，是不是name要是商品ID才行，而不是商品名称？

这是正常的，控件显示的是张三是因为配置的显示字段就是`name`，获取数据的时候获取的是UUID是因为配置的保存字段就是id。

![image](https://user-images.githubusercontent.com/34293221/82278737-7a6c2d80-99bd-11ea-9ce8-e28dc008be6b.png)

----

我用你给的数据库和字段配置测试了一下，能正常使用。
你截图里的问题像是下拉框没有正确显示`显示字段`文本，我这里并没有复现，你确认一下你使用的JEECG的版本确定是最新版`2.2.0`吗？

![image](https://user-images.githubusercontent.com/34293221/82278288-71c72780-99bc-11ea-8318-e68a96f42a83.png)
![image](https://user-images.githubusercontent.com/34293221/82279041-2b72c800-99be-11ea-94dc-dd0d3c5b3cb1.png)
![image](https://user-images.githubusercontent.com/34293221/82279084-47766980-99be-11ea-9fb5-21efa75a97c5.png)

**Comment by kaybinwong** [comment]
确定是2.2.0，下拉是有值，但是首次打开编辑页面不显示 显示字段，需要点击行中的任一个输入框后才能正常显示。
![image](https://user-images.githubusercontent.com/5570216/82323593-df9a4000-9a0a-11ea-9b61-3bdf3e91ec33.png)
![image](https://user-images.githubusercontent.com/5570216/82323617-e759e480-9a0a-11ea-981d-571066304f42.png)

**Comment by kaybinwong** [comment]
发现页面加载后，下拉框选型数据并未及时填充，需要操作后才能有数据

**Comment by sjlei** [comment]
> 发现页面加载后，下拉框选型数据并未及时填充，需要操作后才能有数据，会不会是数据加载顺序的问题？

跟顺序没有关系，你这种情况很有可能是数据库里没有这一条数据，多以匹配不上，你选择的时候选择的是数据库里有的数据，所以能匹配上，请检查一下数据库里是否有`id`为图中的数据。

![image](https://user-images.githubusercontent.com/34293221/82328392-643c8c80-9a12-11ea-9cf3-449df9c448bb.png)

**Comment by sjlei** [comment]
@kaybinwong 问题已复现，感谢反馈，下个版本更新。

跟数据加载顺序无关，Vue会自动监听数据变化，然后更新页面的，但是由于旧的写法让Vue监听不到，所以导致页面没有自动更新，点一下才更新，换成新的写法就行了。

更新之前可以先修改以下文件：
`src/components/jeecg/JEditableTable.vue`
第2519行改成：
`this.$set(column, 'options', newOptions)`

![image](https://user-images.githubusercontent.com/34293221/82397392-f3818880-9a82-11ea-8dea-89a4e07c2647.png)

**Comment by kaybinwong** [comment]
数据库是有数据的，不整了我重新生成代码看看，这类table有没有计划引入一些开源组件？
 anyway，谢谢你 sjlei。

**Comment by kaybinwong** [comment]
可以了，厉害，谢谢你 @sjlei

**Comment by zhuduotao** [comment]
这个页面column.type===Formtypes.radio的时候，options没有初始化。

**Comment by chengyu2333** [comment]
> @kaybinwong 问题已复现，感谢反馈，下个版本更新。
遇到个类似的问题。
我用Formtypes.popup选择一条记录，回显到key为"mediaType"的Formtypes.select时，显示空白，调试回显的值为undefined
测试：
handleValueChange(event) {
        console.log(event.row);
}
输出：
id: "15939581033179506605"
mediaId: "1264972260698812418"
mediaName: "任务目标2帮助小智回到家"
mediaType: undefined

如果将key为"mediaType"的Formtypes.select改为普通文本显示则没问题
