### ISSUE TITLE
在线演示web第三方无法登录

### ISSUE THREAD

**Issue by lifefloating** [zhangdaiscott/jeecg-boot#1206]
##### 版本号：

在线演示版本

##### 问题描述：

第三方登录直接无法登录

##### 截图&代码：

git  微信  钉钉 第三方无法登录

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
演示环境未配置

**Comment by duansheli** [comment]
@zhangdaiscott 
在线演示 ： http://boot.jeecg.com  
不能登录示例站点， 那提供这个站点有意义吗

能否提供docker演示版
通过几行命令 用docker启动一个演示环境
