### ISSUE TITLE
Online表单开发的表单控件长度设置也无效

### ISSUE THREAD

**Issue by linling0103** [zhangdaiscott/jeecg-boot#1207]
##### 版本号：
2.2.0 2020-05-06

##### 问题描述：
在Online表单开发上[表单控件长度]缺省显示120 改了60设置也无效。
还有列表列的宽度哪里可以设置吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前是自适应的，不支持设置

**Comment by linling0103** [comment]
自动生成程序来跑的自适应比Online的要整齐多，谢谢!
