### ISSUE TITLE
省市区组件生成代码问题

### ISSUE THREAD

**Issue by yezhq2018** [zhangdaiscott/jeecg-boot#1208]
##### 版本号：
JEECG-BOOT 2.2.0

##### 问题描述：
online生成的省市区组件代码，列表中编辑时，第一次点编辑能绑定到表单，第二点击就不行，第三又可以，第四次不行.........

##### 截图&代码：

![Uploading image.png…]()

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
图片无效

**Comment by mo-bie** [comment]
一样问题，用antd树选择组件重写了。。。

**Comment by lvdandan16** [comment]
问题已修复，将在下个版本更新
