### ISSUE TITLE
在线表单开发相关问题

### ISSUE THREAD

**Issue by fangLinYu** [zhangdaiscott/jeecg-boot#1209]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
老版有的注解没生成，参考可以自己改代码生成器的模板，加上swagger注解

**Comment by fangLinYu** [comment]
这个问题通过升级到2.2.0解决了，还有个bug，online表单生成代码时，*mapper.xml文件第一行会有空格，导致项目启动失败，删除空格就好了 



fanglin_yu@163.com
 
发件人： JEECG开源社区
发送时间： 2020-05-16 19:52
收件人： zhangdaiscott/jeecg-boot
抄送： fangLinYu; Author
主题： Re: [zhangdaiscott/jeecg-boot] 在线表单开发相关问题 (#1209)
老版有的注解没生成，参考可以自己改代码生成器的模板，加上swagger注解
