### ISSUE TITLE
数据权限bug

### ISSUE THREAD

**Issue by gelinagg** [zhangdaiscott/jeecg-boot#121]
数据权限，如果一张表中设置多个数据权限规则，系统默认只查询第一条数据。。。bug
而且用户配置了数据权限，代码在数据库中如果没有查询到数据权限。。。系统不会提示，只会显示所有的数据。建议优化下。

**Comment by gelinagg** [comment]
我看了PermissionDataAspect是根据菜单管理来配置的，是不是应该根据用户所在的角色，角色的数据权限，然后再从菜单查询比较正确呢。。。

**Comment by zhangdaiscott** [comment]
请截图发出你的配置，描述太抽象
