### ISSUE TITLE
2.2.0版本中用户管理功能数据保存不正确问题

### ISSUE THREAD

**Issue by Loren1999** [zhangdaiscott/jeecg-boot#1210]
##### 问题描述：
用户管理，新增用户时，数据库org_code字段数据没保存到数据库里，编辑时，
org_code字段的值保存的是上一次修改的值，不是最新的。

##### 截图&代码：
新增时：
![1](https://user-images.githubusercontent.com/20633409/82142892-5fd96d80-9872-11ea-87ad-f65d10e166a5.png)
![2](https://user-images.githubusercontent.com/20633409/82142898-68ca3f00-9872-11ea-8f7b-cc7ed89aae56.png)
![3](https://user-images.githubusercontent.com/20633409/82142901-69fb6c00-9872-11ea-94e9-e9f4bdca2b07.png)
修改时：
![4](https://user-images.githubusercontent.com/20633409/82142951-cc546c80-9872-11ea-8b73-922f2a10ed3c.png)
![5](https://user-images.githubusercontent.com/20633409/82142952-cd859980-9872-11ea-872e-f0a6d3ee162a.png)
![6](https://user-images.githubusercontent.com/20633409/82142953-ceb6c680-9872-11ea-921e-c988878ad0db.png)
![7](https://user-images.githubusercontent.com/20633409/82142955-d1192080-9872-11ea-84b7-aaa34fdaf15c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你理解错误，这个字段是系统标准字段，通过拦截器写入，记录添加人的所属部门
编辑不再做更改

**Comment by Loren1999** [comment]
感谢您的回复，这个字段并非由MybatisInterceptor拦截器写入的系统标准字段，这个是系统用户表sys_user的org_code字段，且确实存在问题，希望您再查看下~~
