### ISSUE TITLE
hibernate-re 不存在

### ISSUE THREAD

**Issue by freedomme** [zhangdaiscott/jeecg-boot#1211]
##### 版本号：
2.2版本

##### 问题描述：
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-re</artifactId>
			<version>2.1.5</version>

这个jar 包不存在吧？

			<groupId>org.jeecgframework</groupId>
			<artifactId>autopoi-web</artifactId>
			<version>1.1.1</version>
在maven 的中央仓库，放上去最新版本是 1.1.0  阿里的最新只有 1.0.3

##### 截图&代码：
查过中央仓库，没有发现这个jar。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273965
