### ISSUE TITLE
登录验证码图片无法显示

### ISSUE THREAD

**Issue by zhaomengqiao** [zhangdaiscott/jeecg-boot#1215]
##### 版本号：
2.2

##### 问题描述：
登录验证码图片无法显示。
redis有正确配置，可以连接上。错误日志里也没有错误。并且查看验证码接口是成功返回的，只是result是空。

 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23172646/82172345-762c0b80-98fc-11ea-8e56-de590289a0fd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述过于简单
