### ISSUE TITLE
online自定义树结构,下载后失效, 代码下载到本地后selectTree变为input框

### ISSUE THREAD

**Issue by NMY-Y** [zhangdaiscott/jeecg-boot#1216]
##### 版本号：
2.2.0

##### 问题描述：

我在online开发时，做了两个表单，一个主表，一个附表，在附表中的一个字段的 使用的控件为  树控件，功能测试时，这个 字段 控件正常，生成代码也时一个文本框。

在online生成时 空间正常,下载代码时  变为input 框

##### 截图&代码：
online 生成正常显示自定义树, 并正常格式化tree_id数据:
![image](https://user-images.githubusercontent.com/58156640/82194581-9e7e2f00-9929-11ea-8d9d-f4bf9cc67a2b.png)
![image](https://user-images.githubusercontent.com/58156640/82195740-4cd6a400-992b-11ea-8955-f9fb251f7bd3.png)

代码下载后配置 自定义树结构变为input  , 列表回显tree_id ,不格式化:
![image](https://user-images.githubusercontent.com/58156640/82194698-cbcadd00-9929-11ea-94ff-5cc8a5693e4d.png)
![image](https://user-images.githubusercontent.com/58156640/82195844-768fcb00-992b-11ea-9df1-e60a4c2cf385.png)

生成的代码:
![image](https://user-images.githubusercontent.com/58156640/82194810-f7e65e00-9929-11ea-8589-26b8e468c2f4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持自定义树控件的生成，生成的代码太繁琐，不如自己实现
