### ISSUE TITLE
日历控件无法使用

### ISSUE THREAD

**Issue by xhlstrive** [zhangdaiscott/jeecg-boot#1218]
##### 版本号：
2.2.0

##### 问题描述：
当设置为主从表时，日历控件报错：TypeError: Cannot read property 'appendChild' of null

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6897730/82305055-bf10bc80-99ef-11ea-814c-6db4b47ccce0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
问题已修复，将在下个版本更新

**Comment by kevin-lr** [comment]
主题模板不用‘ERP(一对多)’是可用的

**Comment by xhlstrive** [comment]
是的，单表是可以用的，ERP就报错了，期待新版本
