### ISSUE TITLE
调整浏览器窗口,左侧菜单栏消失

### ISSUE THREAD

**Issue by azunia** [zhangdaiscott/jeecg-boot#1219]
##### 版本号：
2.2

##### 问题描述：
将最大化浏览器调整成小窗口至菜单栏悬浮,再次最大化浏览器,菜单栏消失

##### 截图&代码：
![llqbc](https://user-images.githubusercontent.com/26101389/82390466-5bc76e80-9a71-11ea-8d6d-f4a6a234455b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by cqLJH** [comment]
楼主知道是怎么回事嘛，我也遇到这种情况了

**Comment by azunia** [comment]
> 楼主知道是怎么回事嘛，我也遇到这种情况了

说来惭愧
2.2版本依赖包  ant-design是1.5.2
发现有新版本便替换成了1.6
但没有注意到1.6和前面其他的更新日志,比如这样的:
> 重构 Modal、Drawer 底层 Portal 组件，解决 Modal、Drawer 内容更新延迟问题 #2244
导致上面的问题,还有 a-modal 和 j-modal 不能调整样式(padding top)的问题
便降版本到 1.5.6
又发现了 页眉通知栏 加载时 会出现错位的问题....
懒得折腾,索性还是1.5.2吧...有完美更新的方法,告知一下...

**Comment by cqLJH** [comment]
好的谢谢

**Comment by LeeSheeQee** [comment]
是<a-drawer />导致的，楼主这个问题用v-show代替v-if可以解决,不过其它页面有<a-drawer>的显示-隐藏后去其他页面也会报错...

**Comment by muYouGou** [comment]
将 \src\components\page\GlobalLayout.vue 第5行 v-if 改成v-show 即可 23行添加 v-show="device === 'desktop'" 即可就该这个bug
