### ISSUE TITLE
online表单开发-生成代码后前台页面中没有更多--“详情”link

### ISSUE THREAD

**Issue by zhaiqiang1987** [zhangdaiscott/jeecg-boot#1221]
##### 版本号：
2.2

##### 问题描述：
online表单开发-生成代码后前台页面中没有更多--“详情”link，只有删除link，AUTO在线表单中是有的。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重复问题，关闭
https://gitee.com/jeecg/jeecg-boot/issues/I1C089
