### ISSUE TITLE
online表单生成单表树时保存失败

### ISSUE THREAD

**Issue by hunji** [zhangdaiscott/jeecg-boot#1224]
##### 版本号：
2.2

##### 问题描述：
online表单生成单表树时保存失败，保存时不能触发保存事件

##### 截图&代码：
![QQ截图20200520163836](https://user-images.githubusercontent.com/6678566/82425082-a3bdb400-9ab8-11ea-88dd-fbd89502cce0.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，下个版本更新
