### ISSUE TITLE
升级到该版本后，登录页面的验证码无法正常加载

### ISSUE THREAD

**Issue by splayer2** [zhangdaiscott/jeecg-boot#1228]
##### 版本号：
2.2.0  2020-05-06

##### 问题描述：
1、升级到该版本后，登录页面的验证码无法正常加载。原先版本中public\index.html文件中设置为 window._CONFIG['domianURL'] = 'http://localhost:8080/jeecgboot'; 时，映射到互联网的IP可以正常登录访问。升级到2.2.0版本后，使用上述配置时，登录页面的验证码无法正常加载。需将 http://localhost:8080/jeecgboot 中的 localhost设置为 互联网访问的IP，才可正常加载，如设置：window._CONFIG['domianURL'] = 'http://218.95.12.21:63002/jeecgboot'; (我这边web端口是8080，映射到互联网是 63002端口)。但若次设置，则本地环境又无法正常价值 验证码。反之，本机局域网内验证码加载正常，互联网加载失败。

##### 截图&代码：
    为什么上传的图片老是失败？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在这个问题

**Comment by zhangdaiscott** [comment]
方案：
修改
src/utils/request.js
取消用apiBaseUrl作为baseURL
~~~
const service = axios.create({
  baseURL: '/jeecg-boot',
  //baseURL: apiBaseUrl, // api base_url
  timeout: 9000 // 请求超时时间
})
~~~
这样就可以用vue.config.js 的代理功能了

**Comment by happy1836** [comment]
部署后无法加载验证码，localhost可以    根据上面的改baseURL 不行

**Comment by wangqian0628** [comment]
![image](https://user-images.githubusercontent.com/16589026/114488425-edb90680-9c43-11eb-9aab-6666843b6d26.png)
在浏览器中直接访问验证码地址都可以正常出来，但是在登录页面Status一直是Canceled，验证码无法加载。
![image](https://user-images.githubusercontent.com/16589026/114488496-0e815c00-9c44-11eb-8aaf-de8329ad8c6d.png)

**Comment by ProwDong** [comment]
我把src/utils/request.js修改后还是一样在外网环境下无法加载验证码，当在外网环境中请求的验证码的接口地址复制到浏览器中是访问正常有返回值的，但是在控制台中就报错：Failed to load resource: net::ERR_EMPTY_RESPONSE，请问还需要在哪里配置吗

**Comment by ProwDong** [comment]
> ##### 版本号：
> 2.2.0 2020-05-06
> 
> ##### 问题描述：
> 1、升级到该版本后，登录页面的验证码无法正常加载。原先版本中public\index.html文件中设置为 window._CONFIG['domianURL'] = 'http://localhost:8080/jeecgboot'; 时，映射到互联网的IP可以正常登录访问。升级到2.2.0版本后，使用上述配置时，登录页面的验证码无法正常加载。需将 http://localhost:8080/jeecgboot 中的 localhost设置为 互联网访问的IP，才可正常加载，如设置：window._CONFIG['domianURL'] = 'http://218.95.12.21:63002/jeecgboot'; (我这边web端口是8080，映射到互联网是 63002端口)。但若次设置，则本地环境又无法正常价值 验证码。反之，本机局域网内验证码加载正常，互联网加载失败。
> 
> ##### 截图&代码：
> ```
> 为什么上传的图片老是失败？
> ```
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

请问你解决了吗

**Comment by ProwDong** [comment]
> 部署后无法加载验证码，localhost可以 根据上面的改baseURL 不行

部署到内网服务器后需要使用ngix代理后台地址，不然也不行

**Comment by samposn** [comment]
如果使用的是 openjdk 也会出现获取验证码出错

**Comment by samposn** [comment]
> 部署后无法加载验证码，localhost可以 根据上面的改baseURL 不行

如果使用的是 openjdk 也会出现获取验证码出错

**Comment by yingwu-zhang** [comment]
> 部署后无法加载验证码，localhost可以 根据上面的改baseURL 不行

我第一次使用Localhost可以正常显示，后面就不行了。
