### ISSUE TITLE
JUpload fileList[a].response不存在.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1229]
##### 版本号：
2.2.0

##### 问题描述：
上传多个文件时,returnUrl为false时,会报此错误.

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/20039800/82515224-5427c880-9b4a-11ea-89c5-8c8093bc9237.png)
![图片](https://user-images.githubusercontent.com/20039800/82515262-6b66b600-9b4a-11ea-8b49-9dbfad642486.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已修复，下个版本将会更新
