### ISSUE TITLE
高级查询在Oracle异常

### ISSUE THREAD

**Issue by zhen1129** [zhangdaiscott/jeecg-boot#1231]
##### 版本号：
所有

##### 问题描述：
高级查询在Oracle异常

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26321654/82539794-9a981a00-9b80-11ea-9c96-9987aff7fd68.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把报错的SQL帖一下

**Comment by zhen1129** [comment]
![image](https://user-images.githubusercontent.com/26321654/82645957-50796c00-9c46-11ea-83cd-97db5ed372fa.png)
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM fprs_fp_report WHERE 1 = 1 AND (fault_desc IN ("北京路")) 

就是查询的时候将单引号 转成双引号了

**Comment by sjlei** [comment]
经测试，最新版`2.2.0`的没有这个问题。

如果你的有问题，请说一下你使用的哪个功能，我这里表单设计器、Online表单和自定义高级查询都没问题。
