### ISSUE TITLE
Online表单开发 生成代码 列表.vue中 没有详情按钮和自定义按钮

### ISSUE THREAD

**Issue by yangfuhua2009** [zhangdaiscott/jeecg-boot#1232]
##### `截图&代码： 
`  <span slot="action" slot-scope="text, record">
          <a @click="handleEdit(record)">编辑</a>

          <a-divider type="vertical" />
          <a-dropdown>
            <a class="ant-dropdown-link">更多 <a-icon type="down" /></a>
            <a-menu slot="overlay">
              <a-menu-item>
                <a-popconfirm title="确定删除吗?" @confirm="() => handleDelete(record.id)">
                  <a>删除</a>
                </a-popconfirm>
              </a-menu-item>
            </a-menu>
          </a-dropdown>
        </span>` 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个暂时不支持，自定义按钮得自己手工编码了

**Comment by yangfuhua2009** [comment]
详情按钮也是需要自己加的吗？
