### ISSUE TITLE
关于cloud微服务问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#1233]
##### 版本号：
2.2.0

##### 问题描述：
请问作者大大预定什么时候会发布微服务版本呢，从boot版学到不少东西，真心感谢。
想着跟着继续学习cloud版本，不知道作者大大是采用的哪套标准，是官方springcloud系列还是spring cloud alibaba系列呢，非常期待，望回复！

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
spring cloud alibaba系列
马上会出

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-cloud
