### ISSUE TITLE
Mysql的sql导入问题

### ISSUE THREAD

**Issue by Android-BRUCE** [zhangdaiscott/jeecg-boot#1234]
##### 问题描述：
在workbench中导入sql文件报错，datetime错误，将datetime(0) 改为datetime 后方可正常导入

##### 截图&代码：
datetime(0)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Android-BRUCE** [comment]
另外，sql表中qrtz_打头的表 都必须大写表名字，否则后台一只报错。

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写
