### ISSUE TITLE
建议更换成flowable的BPMN引擎

### ISSUE THREAD

**Issue by YiuTerran** [zhangdaiscott/jeecg-boot#1238]
##### 版本号：
当前

##### 问题描述：
感谢作者创建这个项目，帮了很多忙，提个小小的建议。目前工作流引擎的画风太古老了，感觉和Antd设计界面格格不入。可以考虑替换成新版flowable自带的UI，flowable和Activiti基本是兼容的。

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
3Q
