### ISSUE TITLE
修改了org.jeecg的包名后，online整体功能都用不了

### ISSUE THREAD

**Issue by qiuhaipeng1** [zhangdaiscott/jeecg-boot#1239]
##### 版本号：
2.2.0

##### 问题描述：
修改了org.jeecg的包名后，online整体功能都用不了

##### 截图&代码：
所有和online有关的方法都提示404

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
保留org.jeecg，新增自定义扫描包即可
