### ISSUE TITLE
角色授权、菜单新增没有授权

### ISSUE THREAD

**Issue by gelinagg** [zhangdaiscott/jeecg-boot#124]
登录用自己建立的用户，角色授权系统提示没有权限。。。但是角色已经授权给了用户了。代码发现貌似写死了admin。。。场景：我们不可能将admin开放给客户，客户肯定也有个admin，可以配置角色授权的。。。希望可以尽快解决。。。

**Comment by gelinagg** [comment]
![Uploading QQ图片20190521105117.png…]()

**Comment by zhangdaiscott** [comment]
全文搜java代码里面的注解：
@RequiresRoles({"admin"})
把这个删掉
