### ISSUE TITLE
登录代码验证用户是否注销有bug，if条件永远为false

### ISSUE THREAD

**Issue by Sean-214** [zhangdaiscott/jeecg-boot#1240]
##### 版本号：
当前master分支

##### 问题描述：
登录代码验证用户是否注销有bug，if条件永远为false。

##### 截图&代码：
https://github.com/zhangdaiscott/jeecg-boot/blob/01ce2e8dab21d77942d3d378a45036a896b8d80b/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/service/impl/SysUserServiceImpl.java#L363

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已收录

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
