### ISSUE TITLE
调整浏览器窗口，左侧菜单栏消失

### ISSUE THREAD

**Issue by cqLJH** [zhangdaiscott/jeecg-boot#1241]
##### 版本号：
2.2

##### 问题描述：
将最大化浏览器调整成小窗口至菜单栏悬浮，再次最大化浏览器，菜单栏消失

##### 截图&代码：

![image](https://user-images.githubusercontent.com/52238648/82774360-35da0980-9e77-11ea-8bde-919df6f9d1ee.png)

**Comment by muYouGou** [comment]
将 \src\components\page\GlobalLayout.vue

**Comment by muYouGou** [comment]
将 \src\components\page\GlobalLayout.vue 第5行 v-if 改成v-show 即可 23行添加 v-show="device === 'desktop'" 即可就该这个bug

**Comment by LongYue9608** [comment]
> 将 \src\components\page\GlobalLayout.vue 第5行 v-if 改成v-show 即可 23行添加 v-show="device === 'desktop'" 即可就该这个bug

有用
