### ISSUE TITLE
想集成微信与APP页面

### ISSUE THREAD

**Issue by aqi915** [zhangdaiscott/jeecg-boot#1242]
##### 问题描述：
     想集成微信与APP页面，其它权限菜单系统为同一套，不知道有好的方案吗？看源码应该是单页面系统。
    目前在思考：
            1. 是否支持微信按钮点击，带来用户信息，通过权限判断后，直接后端调取路由到已经配置的页面。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
登录采用token机制，其他APP或者微信直接按照当前登录机制对接即可

**Comment by aqi915** [comment]
还有点没想通，权限验证过了，微信单独的按钮怎么重定向到路由页面呢？有文档可以参考吗？
