### ISSUE TITLE
如何在在目前的后台上搭配轻量级cms前端

### ISSUE THREAD

**Issue by xinheblue** [zhangdaiscott/jeecg-boot#1244]
我司用Jeecg boot做后台，除了常规的各种权限之外，还需要有一个内容管理平台，也就是目前的只在访问 http://域名/admin的时候才出现，而访问http://域名的时候，出现的是cms子系统配置的内容。而http://域名/user是前台用户需要登录才能看到的相关页面，这个应该是个通用需求

问题是目前jeecg 用的包很多，对/admin来说，电脑访问并不是个大问题

但是对前端和需要用户登录访问的，需要能手机随时访问，怎么降低依赖大小

通过vue多入口，发现还是会打包进去，导致cms前台压缩了也得10来m，3-5秒才能加载一个页面，这个很难接受

**Comment by zhangdaiscott** [comment]
cms为什么不换个前端
通过ngix映射不同的前端目录

**Comment by xinheblue** [comment]
> cms为什么不换个前端
> 通过ngix映射不同的前端目录

多谢群主，这确实是一个很好的解决办法
另外是否有多入口的打包方式以及是否妥当，通过修改vue.config.js的多入口一块打包,每个模块抽取自己的依赖打包对应的index，方便复用共用代码和简化上线部署流程
