### ISSUE TITLE
跪求官方做技术支持啊

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1245]
##### 版本号：
JEECG-BOOT 2.2

1、希望在online支持子表中的数值或金额类的合计功能，不用写代码的。

![QQ图片20200525205327](https://user-images.githubusercontent.com/59654718/82814520-ea9d1680-9ec9-11ea-8293-a7fafda42420.png)

2、希望官方写一个下推的功能案例：如【采购合同】生成【采购入库单】。

提问，太过幼稚，请勿喷我...

确实在业务过程中碰到这个麻烦事，一直搞不出来

**Comment by zhangdaiscott** [comment]
这个功能，行编辑已经实现合计设置，
但是online还不支持配置

行编辑功能参考，菜单：常用示例->JEditableTable示例
![image](https://user-images.githubusercontent.com/3162115/83092880-e1ca6180-a0d0-11ea-9e25-90b26661a5d1.png)

**Comment by tianchenglong323** [comment]
这个功能是很需要  管理系统中这种根据某种单据生成另外一种单据的情况特别多

**Comment by tb2888** [comment]
能不能加上合计这个功能呢？

**Comment by zhangdaiscott** [comment]
online暂时没计划加合计
