### ISSUE TITLE
在线文档中不能支持对List<Enum>的入参

### ISSUE THREAD

**Issue by KochamCie** [zhangdaiscott/jeecg-boot#1246]
**版本号**：V1.1

**问题描述**：定义Controller中入参为List/Array 类型并且指定泛型为枚举类型，在线文档(swagger)中下拉框可选枚举值，无法多选而且选中的一个无法传递到接口。在原生swagger-ui中可以通过ALT选中多个枚举作为参数传递。

**截图&代码**：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
能否截图看一下

**Comment by KochamCie** [comment]
![image](https://user-images.githubusercontent.com/21299325/83351505-2aa34400-a377-11ea-97f6-f439e126b132.png)

Hi

左边的红框标识了字段是array类型，但是右边的selectbox只支持单选。

**Comment by J-cafe** [comment]
框架用的就是原生的swagger，swagger-ui是支持多选的，doc是不行的，多选用的是Ctrl而不是ALT。如果需要测试多选参数可以访问http://server:<port>/swagger-ui.html页面测试。
