### ISSUE TITLE
第三方登录失败

### ISSUE THREAD

**Issue by aqi915** [zhangdaiscott/jeecg-boot#1247]
##### 版本号：
2.2

##### 问题描述：
最近测试了github与企业微信的第三方登录，都没成功，错误都类似。

**application.yml文件配置**
    WECHAT_ENTERPRISE:
      client-id: wwbc**********7864
      client-secret: Wiz9Fh********4jiretU-C6g5Q3n********gNV_3M
      redirect-uri: http://anju****.e2.l******ia.net:2***0/thirdLogin/wechat_enterprise/callback
      agent-id: 1000002

**企业微信授权回调域：**

   anju****.e2.l******ia.net:2***0

**错误信息：**
{"success":false,"message":"操作失败，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: cn.hutool.core.lang.Assert.notBlank(Ljava/lang/CharSequence;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/CharSequence;","code":500,"result":null,"timestamp":1590458158176}

##### 截图&代码：

**企业微信截图信息：**
![11](https://user-images.githubusercontent.com/14802274/82852739-51f0b000-9f36-11ea-89e4-bd673589d81c.png)
![12](https://user-images.githubusercontent.com/14802274/82852769-67fe7080-9f36-11ea-90a7-30c8cd8a4e5e.png)
![13](https://user-images.githubusercontent.com/14802274/82855890-2a521580-9f3f-11ea-8cb6-35429ff17c5f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已收录

**Comment by tygithub1** [comment]
哪一行报的错误?

**Comment by tygithub1** [comment]
把pom里面的hutool依赖删掉试试

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecg-boot/issues/I1G4X9
