### ISSUE TITLE
Mock API的接口地址是不是换了

### ISSUE THREAD

**Issue by pkaq** [zhangdaiscott/jeecg-boot#1248]
##### 版本号：
最新版本

##### 问题描述：
 target: 'https://mock.ihx.me/mock/5baf3052f7da7e07e04a5116/antd-pro', // mock API接口系统
这个访问不到 是不是地址换了

**Comment by zhangdaiscott** [comment]
作废的，没有用mack api

**Comment by pkaq** [comment]
> 作废的，没有用mack api

所以只用这套前端的话 需要自己一个个F12扒数据咯?
