### ISSUE TITLE
菜单配置问题

### ISSUE THREAD

**Issue by qqLife** [zhangdaiscott/jeecg-boot#1249]
##### 问题描述：点击左侧菜单管理，在右侧树结构列表——菜单管理——新增：组织机构管理，并确定提交。
刷新页面，左侧菜单管理中未出现新建的组织机构管理菜单
个人思路： 前端定义了组件 system/organizeMangage.vue   后台不知道改哪里？
/jeecg-boot/sys/permission/getUserPermissionByToken此方法调用的是左侧边栏的菜单，
/jeecg-boot/sys/permission/list  此方法调用在表单中新建的菜单（组织机构），新建后并没有更新到上面方法操作的mysql表中。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37296782/82875009-64381180-9f69-11ea-9c47-47062b11d1df.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
新增的菜单需先在角色中授权

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273950

**Comment by qqLife** [comment]
谢谢您哈，昨天问了下群友，立马点明了我。感谢您在百忙之中抽空回答我的问题
