### ISSUE TITLE
配置新增菜单，跳转404

### ISSUE THREAD

**Issue by PLAhui** [zhangdaiscott/jeecg-boot#125]
![image](https://user-images.githubusercontent.com/35413994/58065773-64b10600-7bb9-11e9-97e3-acba39e08b13.png)
![image](https://user-images.githubusercontent.com/35413994/58065805-7eeae400-7bb9-11e9-8387-e98b41107a6c.png)
![image](https://user-images.githubusercontent.com/35413994/58065826-90cc8700-7bb9-11e9-8018-34af3c55721e.png)

**Comment by zhangdaiscott** [comment]
菜单配置页面截图

**Comment by PLAhui** [comment]
已解决！
需要选择路由菜单(文档1.1中不需要)
![YN@LD%{O87}{ET$}`}LAE3P](https://user-images.githubusercontent.com/35413994/58066667-e7879000-7bbc-11e9-89c8-654779cc1437.png)

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=345664

**Comment by 2428552874** [comment]
> http://jeecg-boot.mydoc.io/?t=345664

你好，这个文档打不开了，可以更新一下链接吗

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/
