### ISSUE TITLE
希望恢复markdown编辑器

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#1250]
##### 版本号：
2.2.0

##### 问题描述：
2.2.0版本一开始的时候我看还是内置支持markdown编辑器，但后来的commit里面又删除了，详见 [降低前端搭建难度，暂时删除tui-editor markdown编辑器](https://github.com/zhangdaiscott/jeecg-boot/commit/cdfa6f8ac666f5be0afcb3a62149b4217f48ea93)，markdown编辑器还是非常有用的，建议恢复支持。

**Comment by zhangdaiscott** [comment]
ok 在考虑换 一个组件

**Comment by liudonghua123** [comment]
嗯，我之前在vue-ant-design里面想使用markdown editor，对比了一些最后使用的是 mavon-editor (https://github.com/hinesboy/mavonEditor)，后来看到你用的是 tui.editor (https://github.com/nhn/tui.editor)，感觉功能更强大，但也重量级一些，其实可以多个富文本编辑器、markdown编辑器同时存在，由用户来根据自己喜好，需求决定用哪一个。
代码生成其中就默认其中一个就行。
