### ISSUE TITLE
Online报表配置

### ISSUE THREAD

**Issue by xieqi48790421** [zhangdaiscott/jeecg-boot#1251]
##### 问题描述：
Online报表配置的查询SQL能用存储过程吗

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/43559414/82963870-84fa7880-9ff6-11ea-8cb5-3411d59d77cb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
