### ISSUE TITLE
静态资源获取问题

### ISSUE THREAD

**Issue by CSuperC** [zhangdaiscott/jeecg-boot#1257]
##### 问题描述：
刷新online 表单页面，不知道哪里有请求，请求到了静态图片

##### 截图&代码：

有奇怪的请求，请求到这里，不知道为啥，不知道哪里发起的，前端
/jeecg-boot/sys/common/static/temp/11_1582468686154.jpg  他的全部路径为这个，
问题
1 这个是哪里发的请求？
2 这个temp 是哪里控制的？
3 这些图，应该放到哪里？
4 这块影响功能么？
**
* 预览图片&下载文件
* 请求地址：http://localhost:8080/common/static/{user/20190119/e1fe9925bc315c60addea1b98eb1cb1349547719_1547866868179.jpg}
*
* @param request
* @param response
*/
@GetMapping(value = "/static/**")
public void view(HttpServletRequest request, HttpServletResponse response) {
   // ISO-8859-1 ==> UTF-8 进行编码转换
   String imgPath = extractPathFromPattern(request);
   if(oConvertUtils.isEmpty(imgPath) || imgPath=="null"){
      return;
   }
   // 其余处理略
   InputStream inputStream = null;
   OutputStream outputStream = null;
   try {
      imgPath = imgPath.replace("..", "");
      if (imgPath.endsWith(",")) {
         imgPath = imgPath.substring(0, imgPath.length() - 1);
      }
      String filePath = uploadpath + File.separator + imgPath;
      File file = new File(filePath);
      if(!file.exists()){
         response.setStatus(404);
         _throw new RuntimeException("文件不存在..");_ 
      }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
online 表单页面是功能测试吗？
temp是文件或图片上传的默认业务路径，如果上传时不设置业务路径则默认为temp

**Comment by CSuperC** [comment]
@lvdandan16  请求online 表单列表页，不知道哪里，会请求
/jeecg-boot/sys/common/static/temp/11_1582468686154.jpg，这个静态资源，抓包F12也看不到对应哪里请求来的，不知道这个temp 下，怎么配置，怎么控制的整个请求

**Comment by tygithub1** [comment]
you can try refresh any page not only online,then you will find this exception always occur,i guess the reason is your avatar,yeah,you can find one user's avatar in the upper right corner,maybe you do not have

**Comment by CSuperC** [comment]
@tygithub1   yes ，any page is has exception ，but i dont konw why ，avatar ？i use admin

**Comment by CSuperC** [comment]
@tygithub1 yes i get it ,it 's what you say ,thanks,i will  gon on it ,table sys_user
