### ISSUE TITLE
a-tabs下的a-tab-pane中有富文本组件j-editor，切换tab页签后j-editor内容会消失

### ISSUE THREAD

**Issue by capricornstone** [zhangdaiscott/jeecg-boot#1258]
##### 截图&代码：
刚打开j-editor中有内容
![image](https://user-images.githubusercontent.com/3507110/83098669-d893c180-a0dd-11ea-9edd-115bd4bce673.png)
切换tab页签
![image](https://user-images.githubusercontent.com/3507110/83098713-f3fecc80-a0dd-11ea-9a00-58705951457f.png)
切换后tab后j-editor内容会消失
![image](https://user-images.githubusercontent.com/3507110/83098779-18f33f80-a0de-11ea-9e43-35480e04a567.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已收录

**Comment by sjlei** [comment]
问题已修复，将在下个版本更新

**Comment by jianglei02** [comment]
> 问题已修复，将在下个版本更新

麻烦问下版本什么时候发布，或者怎么解决呢

**Comment by sjlei** [comment]
可直接替换 `src/components/jeecg/JEditor.vue` 这个文件来解决。

[JEditor.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4727832/JEditor.zip)

切换`tab`时的确会导致这个富文本内容消失且不可编辑，具体原因未知，应该是这个组件本身的问题，不光是vue版本，jQuery版本也有这个问题。
解决方法就是当切换时重新加载一下这个组件，但是由于是重新加载，所以虽然内容在，但是你滚动的距离还有选中的内容等属性会被重置。

**Comment by jianglei02** [comment]
> @jianglei02
> 
> 可直接替换 `src/components/jeecg/JEditor.vue` 这个文件来解决。
> 
> [JEditor.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4727832/JEditor.zip)
> 
> 切换`tab`时的确会导致这个富文本内容消失且不可编辑，具体原因未知，应该是这个组件本身的问题，不光是vue版本，jQuery版本也有这个问题。
> 解决方法就是当切换时重新加载一下这个组件，但是由于是重新加载，所以虽然内容在，但是你滚动的距离还有选中的内容等属性会被重置。

好的，谢谢

**Comment by zhangdaiscott** [comment]
下个版本发布

**Comment by qf8505** [comment]
最新版本问题依然存在。增加了父级ATabs和ATabPane判断。但是<keep-alive v-if="multipage">
          <router-view v-if="reloadFlag"/>
        </keep-alive>
        <template v-else>
          <router-view v-if="reloadFlag"/>
        </template>
      </transition>并没有放到tab下。
