### ISSUE TITLE
前端页面右上的退出登录按钮Bug

### ISSUE THREAD

**Issue by Sean-214** [zhangdaiscott/jeecg-boot#1259]
##### 版本号：
当前master分支

##### 问题描述：
退出登录直接跳转到 '/' 路径是错误的，如果部署到一个子目录会有影响。
应该使用路由跳转 `that.$router.push({ path: '/user/login' })` 。

##### 截图&代码：
https://github.com/zhangdaiscott/jeecg-boot/blob/01ce2e8dab21d77942d3d378a45036a896b8d80b/ant-design-vue-jeecg/src/components/tools/UserMenu.vue#L171

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已收录

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
