### ISSUE TITLE
性能监控模块是否考虑开源

### ISSUE THREAD

**Issue by yihuiluo235** [zhangdaiscott/jeecg-boot#126]
如题，是否考虑开源，如不开源的话，能否提供实现思路。
![image](https://user-images.githubusercontent.com/2733701/58068557-5d432a00-7bc4-11e9-8172-1913734ee7b6.png)

**Comment by zhangdaiscott** [comment]
这个已经开源，下载最新版本

**Comment by yihuiluo235** [comment]
> 这个已经开源，下载最新版本

您好，是性能监控，不是系统监控

**Comment by ileadall42** [comment]
@yihuiluo235  授权 admin账户就可以看到了。实在不行你可以直接看代码。

**Comment by yihuiluo235** [comment]
> @yihuiluo235 授权 admin账户就可以看到了。实在不行你可以直接看代码。

十分感谢答疑
