### ISSUE TITLE
Online图表配置问题

### ISSUE THREAD

**Issue by qqLife** [zhangdaiscott/jeecg-boot#1260]
##### 版本号：2.2
不知道如何配置图表，前端组建中没有
![image](https://user-images.githubusercontent.com/37296782/83131289-2de9c600-a112-11ea-904f-11e39a16f257.png)
页面中不存在次图表菜单，是我项目版本问题吗，我也是按照百度云分享下载解压的
##### 问题描述：通过文档配置图表没有相关图表graphreport组件
 请问：是vue项目中暂时还没有开源配置这个图表组件呢，还是需要商业授权。但是在授权免费版本中第二个版本是有这个图表配置菜单项的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37296782/83132427-f714af80-a113-11ea-9744-5aec3a6611f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此功能暂时不开源
