### ISSUE TITLE
online报表复杂SQL报错

### ISSUE THREAD

**Issue by chengyu2333** [zhangdaiscott/jeecg-boot#1261]
##### 版本号：
2.1.4

##### 问题描述：
当SQL中子查询包含where时，SQL解析会报错。
原因可能是计算返回行数的sql生成错误，当遇到where时直接就认为sql结束了。
建议可以自定义行数计算的sql，也可以提高sql的效率

##### 截图&代码：
SQL：
select id,mp_name,
       (select count(0) from teaching_order
           join sys_user on sys_user.id = teaching_order.user_id and teaching_order.order_status=1
           join wechat_user wu on wu.user_id = sys_user.id
           join teaching_agent agent on agent.id = wu.agent_id ba agent.wechat_mp = wechat_mp.app_id
        ) purchasedNumber
from wechat_mp

报错信息：
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'id ) TOTAL', expect RPAREN, actual EOF pos 314, line 5, column 72, token EOF : SELECT COUNT(1) FROM ( select id,mp_name,
       (select count(0) from teaching_order
           join sys_user on sys_user.id = teaching_order.user_id and teaching_order.order_status=1
           join wechat_user wu on wu.user_id = sys_user.id
           join teaching_agent agent on agent.id = wu.agent_id ) TOTAL

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级2.2
