### ISSUE TITLE
最新版本select dict组件有问题,

### ISSUE THREAD

**Issue by zxiaozhou** [zhangdaiscott/jeecg-boot#1262]
##### 版本号：
2.1.4

##### 问题描述：
最新版本下拉字典如果使用你们封装的JDictSelectTag组件会出现请选择或者说placeholder无法显示，官方部署的版本也一样，比如消息模板的模板类型。下面是官网部署项目截图(本地也是有问题的)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/62740686/83202666-a71d0380-a17a-11ea-9787-35bd30bbdadd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的意思，匹配值有问题？

**Comment by zxiaozhou** [comment]
@zhangdaiscott 是提示信息没显示，比如:"我设置的placeholder为请选择模板类型"，但打开那个提示信息没有，，是空白的。比如下面图片的
![image](https://user-images.githubusercontent.com/62740686/83245216-04dd3a00-a1d3-11ea-86df-348945e7d164.png)

虽然不影响正式逻辑。。但是总觉得不能设置提示信息placeholder怪怪的，也不利于体验

**Comment by lvdandan16** [comment]
已收录

**Comment by zxiaozhou** [comment]
@lvdandan16 我发现不显示placeholder是计算属性getValueSting导致的，，只要去掉:value="getValueSting"就正常。但是也没注意看代码对后续东西有影响没。。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
