### ISSUE TITLE
domianURL 命名问题，是否应该是 domainURL？

### ISSUE THREAD

**Issue by mwxxhdb** [zhangdaiscott/jeecg-boot#1263]
##### 问题描述：
domianURL 命名问题，是否应该是 domainURL？

##### 截图&代码：
文件：jeecg-boot/ant-design-vue-jeecg/public/index.html
window._CONFIG['domianURL'] = 'http://127.0.0.1:8080/jeecg-boot';

**Comment by zhangdaiscott** [comment]
是的，改动比较多，所以暂时这样了
