### ISSUE TITLE
功能测试页面与实际生成的不一致

### ISSUE THREAD

**Issue by rockstone0** [zhangdaiscott/jeecg-boot#1264]
##### 版本号：
2.2.0

##### 问题描述：
1 功能测试的页面是erp上下父子表的形式,生成的却只有父表一个了
2 功能测试的搜索条件有,生成的搜索条件却没有了
##### 截图&代码：
可以用已经做好的测试页面:
主表(ERP) | test_order_main | 测试订单主表
功能测试与生成的对比下,一看便知.

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成的时候，需要再次选择模板才行

**Comment by rockstone0** [comment]
试了下,改成了erp模板,出现了上下结构了的表了.谢谢.

同时也发现另外一个问题,使用erp视图,当树表作为子表时,不再是树型表格了,变成了平面表格.

<img width="1145" alt="图片" src="https://user-images.githubusercontent.com/15150272/83230882-20d5e100-a1bd-11ea-82b2-7af43ee429ff.png">

生成后的页面(子表三个有层级关系,在子表变成附表前,树视图正常,改成附表后,树效果没了):
<img width="1136" alt="图片" src="https://user-images.githubusercontent.com/15150272/83231096-84f8a500-a1bd-11ea-9b1d-df042fcf8707.png">

**Comment by zhangdaiscott** [comment]
不支持树

**Comment by rockstone0** [comment]
好吧,谢谢
