### ISSUE TITLE
系统通告选人bug

### ISSUE THREAD

**Issue by longyunfei123** [zhangdaiscott/jeecg-boot#1265]
##### 截图&代码：
![b76dd426f6256563e0b10d92c07d937](https://user-images.githubusercontent.com/66101358/83219055-ed398d80-a1a1-11ea-9b0f-ef4e324b5901.png)

![7d9c2572fd34248eaa69038b4823bb2](https://user-images.githubusercontent.com/66101358/83219071-f9bde600-a1a1-11ea-8b1c-fdda531aa120.png)
![0ce250a4524e463fc4b638e1e480f9c](https://user-images.githubusercontent.com/66101358/83219076-fd516d00-a1a1-11ea-83dc-b8e28e965200.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
已收录

**Comment by zhangdaiscott** [comment]
处理完成，下个版本发布
