### ISSUE TITLE
Tinymce富文本bug

### ISSUE THREAD

**Issue by sperains** [zhangdaiscott/jeecg-boot#1268]
##### 问题描述：
Tinymce富文本编辑器，工具栏图标出不来，显示not found。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18645425/83322435-40870b00-a28a-11ea-984b-c4072cbdce06.png)

![image](https://user-images.githubusercontent.com/18645425/83322422-3533df80-a28a-11ea-9846-5419caf8e95c.png)

**Comment by zhangdaiscott** [comment]
依赖有问题吧，默认不会这样

**Comment by sperains** [comment]
这个问题。。
我之前是用的cnpm安装的依赖，我换成yarn重新安装了一遍依赖后正常了。

**Comment by met7or** [comment]
yarn install重新安装了也还是not found，大佬有什么解决的办法吗

**Comment by hejun311** [comment]
同问 之前好好的 啥也没做  也出现了这个问题

**Comment by hejun311** [comment]
import 'tinymce/icons/default';
同志们  引入这个就可以拉

**Comment by zhangdaiscott** [comment]
已经处理下个版本发布
