### ISSUE TITLE
nginx配置内网地址，外网无法访问

### ISSUE THREAD

**Issue by qqLife** [zhangdaiscott/jeecg-boot#1269]
##### 问题描述：vue打包后放入nginx中，配置172地址，在服务器本地可以访问页面并调用后台接口。但是用映射的外网地址是无法访问页面
  vue的require.js 也修改了baseURL： ‘/jeecg-boot’,
以及index.html中的domainUrl ，imgDoMainUrl地址均为内网后台地址
##### 截图&代码：
nginx配置

使用外网地址无法访问页面：
![image](https://user-images.githubusercontent.com/37296782/83329286-2fa2bd80-a2bb-11ea-9f9f-13d37fdfde4d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273922
