### ISSUE TITLE
如何清除登录页面的默认账户密码

### ISSUE THREAD

**Issue by qqLife** [zhangdaiscott/jeecg-boot#1270]
##### 问题描述：登录页吗的默认账户：admin，密码：123456.
前端input标签v-decorator="['username',{initialValue:'', rules: validatorRules.username.rules}]" initValue初始值均清空，再次刷新页面依然存在默认账户密码

##### 截图&代码：
v-decorator="['username',{initialValue:'', rules: validatorRules.username.rules}]" 清空了初始值
![image](https://user-images.githubusercontent.com/37296782/83339879-87194b80-a304-11ea-9056-5e4b1cbe41e2.png)
虽然这问题有些弱智，但实在是没找到修改的地方，望前辈能帮忙回答下，万分感谢

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
src/views/user/Login.vue

![image](https://user-images.githubusercontent.com/3162115/83343374-2271e700-a32c-11ea-8f4a-7ecc476371b5.png)

**Comment by qqLife** [comment]
我是清除的这里，刷新了之后还是有默认账户密码



---原始邮件---
发件人: "JEECG开源社区"<notifications@github.com&gt;
发送时间: 2020年5月31日(周日) 上午10:47
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送: "qqLife"<281362832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhangdaiscott/jeecg-boot] 如何清除登录页面的默认账户密码 (#1270)




 
src/views/user/Login.vue

**Comment by qqLife** [comment]
退出登录后不想显示登录原账户和密码该咋设置呢



---原始邮件---
发件人: "JEECG开源社区"<notifications@github.com&gt;
发送时间: 2020年5月31日(周日) 上午10:47
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送: "qqLife"<281362832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhangdaiscott/jeecg-boot] 如何清除登录页面的默认账户密码 (#1270)




 
src/views/user/Login.vue
