### ISSUE TITLE
角色授权有数据权限时没有显示提示标签

### ISSUE THREAD

**Issue by feitian124** [zhangdaiscott/jeecg-boot#1271]
##### 版本号：
2.2.0

##### 问题描述：
bilibili视频讲解时有提示标签，本地跑时没有:
角色管理 -> 授权 ，有数据权限时，没有显示提示标签。

##### 截图&代码：

![2020-05-31_10-00_1](https://user-images.githubusercontent.com/1425383/83342842-901b1480-a326-11ea-9565-b2792a37b628.png)
![2020-05-31_10-01](https://user-images.githubusercontent.com/1425383/83342869-c2c50d00-a326-11ea-83f2-d3bdea951033.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
我们本地代码未发现没有标签的情况

**Comment by feitian124** [comment]
@lvdandan16 那奇怪了，你也是 2.2.0 吗

**Comment by lvdandan16** [comment]
是的，我们这也是2.2.0版本

**Comment by feitian124** [comment]
经查， 代码没有问题， 是数据问题。
我数据库中 `sys_permission` 中的 `rule_flag`字段值全部为 0,  故页面没有显示。
查询发现脚本`2jeecgboot_mysql5.7.sql`中`单表模型示例`这条的`rule_flag`确实是0,
应该是 @zhangdaiscott 导出的数据有脏数据。
```
INSERT INTO `sys_permission` VALUES ('4148ec82b6acd69f470bea75fe41c357', '2a470fc0c3954d9dbb61de6d80846549', '单表模型示例', '/jeecg/jeecgDemoList', 'jeecg/JeecgDemoList', 'DemoList', NULL, 1, NULL, NULL, 1.00, 0, NULL, 1, 1, NULL, 0, NULL, NULL, '2018-12-28 15:57:30', 'admin', '2019-02-15 16:24:37', 0, 0, NULL, NULL);
```
删除已有数据股则后自己创建， 可以看到指示图标了。
