### ISSUE TITLE
表单风格问题

### ISSUE THREAD

**Issue by sunbo68** [zhangdaiscott/jeecg-boot#1277]
##### 版本号：
2.2.0

##### 问题描述：
在线表格的表单风格设置的是两列,生成的代码后的还是一列

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本支持

**Comment by sunbo68** [comment]
大概什么时候上新版本
