### ISSUE TITLE
【在线报表】-功能测试-里面导出数据只能是10条，是否可以配置，或者这个是bug?

### ISSUE THREAD

**Issue by DrKarev** [zhangdaiscott/jeecg-boot#1278]
##### 版本号：
2.2.0

##### 问题描述：
【在线报表】里面导出数据只能是10条，可以配置吗，选了20或30条的分页也还是导出10条。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重复问题关闭
https://github.com/zhangdaiscott/jeecg-boot/issues/1230
