### ISSUE TITLE
Online开发导入数据库表-Docker-oracle 环境下出不来

### ISSUE THREAD

**Issue by hefangfang** [zhangdaiscott/jeecg-boot#1279]
##### 版本号：
Jeecg Boot 2.2

##### 问题描述：
Online 表单开发，通过“导入数据库表”的方式创建，一直提示查询不出来，环境是-Docker-oracle
，但是换成非docker的就可以
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
代码生成器的数据库配置改了吗

**Comment by hefangfang** [comment]
改了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午10:06
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"贺芳芳"<936856214@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] Online开发导入数据库表-Docker-oracle 环境下出不来 (#1279)





 
代码生成器的数据库配置改了吗

**Comment by zhangdaiscott** [comment]
目前提供的信息不足，无法分析
