### ISSUE TITLE
系统设置-主题色Bug

### ISSUE THREAD

**Issue by Sean-214** [zhangdaiscott/jeecg-boot#1281]
##### 版本号：
当前master分支

##### 问题描述：
右上角用户头像-系统设置-主题色报错，部署到一个子目录会有影响。
link 标签 href 属性直接使用了 ‘/color.less’ 路径，打包到一个子目录时（即设置了publicPath）路径错误，应改为 `lessStyleNode.setAttribute('href', __webpack_public_path__ + 'color.less')`

##### 截图&代码：
https://github.com/zhangdaiscott/jeecg-boot/blob/8a8e92cda38b9f042fdcfb1c2a56c88c59eb80a5/ant-design-vue-jeecg/src/components/tools/setting.js#L67

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已分配

**Comment by sjlei** [comment]
感谢反馈，已采用你的写法，下个版本发布
