### ISSUE TITLE
3个页面生成时的问题(表注释,开关控件,表单列数)

### ISSUE THREAD

**Issue by rockstone0** [zhangdaiscott/jeecg-boot#1282]
##### 版本号：
2.2.0

##### 问题描述：
问题1 从数据库导入表时,表是有注释的,导入后,注释是表名,需要重新设置下才行
问题2 在线表单开关控件,生成后放入项目不显示,功能测试页面正常
问题3 在线页面设置字段按两列显示,生成后添加与修改页面却是一列
##### 截图&代码：
问题2的截图:
<img width="1342" alt="图片" src="https://user-images.githubusercontent.com/15150272/83473082-56c7dd80-a4bb-11ea-9a54-fcf3d8e212b2.png">
<img width="1132" alt="图片" src="https://user-images.githubusercontent.com/15150272/83473138-6fd08e80-a4bb-11ea-8fb5-cb05bbadba72.png">
功能测试页面正常:
<img width="696" alt="图片" src="https://user-images.githubusercontent.com/15150272/83473350-ecfc0380-a4bb-11ea-816e-4c5fb47d196a.png">
项目上页面是数字输入框,列表反显也只是数字:
<img width="716" alt="图片" src="https://user-images.githubusercontent.com/15150272/83473438-26347380-a4bc-11ea-8848-47160e82cecf.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1312
