### ISSUE TITLE
模版生成的代码不规范和报错

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1283]
##### 版本号：
v2.2.0

##### 问题描述：
模版生成的代码不规范

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12267648/83486407-b1713180-a4db-11ea-8ef7-33d3dea25889.png)
如果表单填写的包名是sip.server 生成出来的mapping是这个
如果表单填写的包名是sip/server 生成出来的代码就会有cuo错误
![image](https://user-images.githubusercontent.com/12267648/83486514-e7aeb100-a4db-11ea-9f84-4a20ee5c31b4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinwu-yang** [comment]
![image](https://user-images.githubusercontent.com/12267648/83486589-1167d800-a4dc-11ea-8303-68e4fbd3c686.png)
![image](https://user-images.githubusercontent.com/12267648/83486599-188ee600-a4dc-11ea-834e-5e10feb99e29.png)
这两个位置应该分出处理，如果是package应该是点，如果是mapping应该是斜杠

**Comment by zhangdaiscott** [comment]
小包不支持带点，深层次目录可以在
![Uploading image.png…]()

设置
