### ISSUE TITLE
部署到生产环境后，顶部工具栏和底部页脚都没有了

### ISSUE THREAD

**Issue by ddwolf715** [zhangdaiscott/jeecg-boot#1284]
##### 版本号：
v2.2.0

##### 问题描述：
按文档 [JAR部署方案](http://doc.jeecg.com/1273922) 中的方法部署后，顶部工具栏和底部页脚都没有了，如图1所示，图中有文字标识。
1.菜单收缩按钮没有了
2.顶部工具栏没有了
3.底部页脚没有了

另外的的nginx配置如图2所示

##### 截图&代码：
图1
![image](https://user-images.githubusercontent.com/17849555/83494019-3a8e6580-a4e8-11ea-8858-ffe78139b143.png)

图2
![image](https://user-images.githubusercontent.com/17849555/83494151-6a3d6d80-a4e8-11ea-86a0-e31b4dfd9b8c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ddwolf715** [comment]
有其他人遇到过同样的问题吗？

**Comment by zhangdaiscott** [comment]
未重现

**Comment by ddwolf715** [comment]
> 未重现

我的这个问题，可能是哪里出现的问题？

**Comment by fengliu-A** [comment]
我也出现了这个问题，我是顶部菜单部署到生产环境上无法显示，本地正常

**Comment by fengliu-A** [comment]
> > 未重现
> 
> 我的这个问题，可能是哪里出现的问题？

有解决方案吗？
