### ISSUE TITLE
前端HeaderNotice.vue，websocketclose方法不存在

### ISSUE THREAD

**Issue by Sean-214** [zhangdaiscott/jeecg-boot#1285]
##### 版本号：
当前master分支

##### 问题描述：
this.websocketclose(); 没有这个方法

##### 截图&代码：
https://github.com/zhangdaiscott/jeecg-boot/blob/8a8e92cda38b9f042fdcfb1c2a56c88c59eb80a5/ant-design-vue-jeecg/src/components/tools/HeaderNotice.vue#L127

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这段代码删除即可
![image](https://user-images.githubusercontent.com/3162115/83508997-518b8280-a4fd-11ea-82cc-a287e89fcc62.png)

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
