### ISSUE TITLE
v2.2.0版本，按钮type为danger时，看不到文字

### ISSUE THREAD

**Issue by yogwang** [zhangdaiscott/jeecg-boot#1286]
##### 版本号：
v2.2.0

##### 问题描述：
当按钮 `type` 为 `danger` 时，文字也是白色的，就会如下图一样的情况。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51895542/83500644-a3c6a680-a4f1-11ea-8a12-9dbf4c642c17.png)
然后审查模式下边看到是有一个样式覆盖了组件库的样式
![image](https://user-images.githubusercontent.com/51895542/83501124-441ccb00-a4f2-11ea-8c87-39a7d64947e3.png)

把 `require('@jeecg/antd-online-beta220/dist/OnlineForm.css')` 注释掉就没问题了。

**Comment by zhangdaiscott** [comment]
"ant-design-vue": "1.5.4",  固定这个版本试试

**Comment by yogwang** [comment]
@zhangdaiscott"1.5.4"也是不行。
![image](https://user-images.githubusercontent.com/51895542/83586193-68be8480-a57e-11ea-9546-6f4e354737c6.png)
![image](https://user-images.githubusercontent.com/51895542/83586207-6fe59280-a57e-11ea-8913-12326c30c59a.png)

之前 [2.1.0 版本也是这个问题](https://yogwang.site/2020/jeecg-boot-devDiary10/)

**Comment by zhangdaiscott** [comment]
固定后，重新install了？

**Comment by yogwang** [comment]
@zhangdaiscott 重新Install了
