### ISSUE TITLE
【极简部署方案】后台报"身份认证失败"

### ISSUE THREAD

**Issue by gzz2017gzz** [zhangdaiscott/jeecg-boot#1287]
##### 版本号：
Jeecg  Boot Version: 2.2.0
##### 问题描述：
按官方文档 使用【极简部署方案】
当把servlet.context-path 值改为空或去掉时后台不停报
2020-06-02 18:38:44,915[INFO][ShiroRealm.java:95]:————————身份认证失败——————————IP地址:  127.0.0.1

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32632097/83511856-e2645d00-a501-11ea-82db-2321869df147.png)

![image](https://user-images.githubusercontent.com/32632097/83511999-1a6ba000-a502-11ea-9bb0-f09a31d881f2.png)

肯请大佬帮忙查证解决

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是本地还是服务器？
可以通过浏览器，F12看看有什么请求被拒绝了

**Comment by xza-rep** [comment]
同上，获取验证码的时候会报这个错误

**Comment by xza-rep** [comment]
本地没有任何问题，通过容器化调用我后段的也没有问题

**Comment by xza-rep** [comment]
部署上去就有问题😔
