### ISSUE TITLE
参数路由会打开标签页

### ISSUE THREAD

**Issue by yangfuhua2009** [zhangdaiscott/jeecg-boot#1289]
##### 问题描述：
 this.$router.push({ path: '/knowledge/CmsArticlechapterList', query: { articleid: id } })
路由跳转不同的菜单,当参数不同时,会打开多个标签页?期望只打开同一个标签页

##### 截图&代码：
 this.$router.push({ path: '/knowledge/CmsArticlechapterList', query: { articleid: id } })
![1](https://user-images.githubusercontent.com/15136732/83584161-dd8ec000-a578-11ea-8e19-7d6a5e37db8d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yangfuhua2009** [comment]
也试了下动态路由的配置,也是url的path不同导致打开多个标签页,这个能不能打开到同一个标签页

**Comment by jerometang** [comment]
打开新的标签是正确的，否则你永远只能看到最后一个标签的内容；
如果用一个标签那么带来的新问题是，在新建页面的情况下你输入的内容会被新建的标签给覆盖掉。

**Comment by zhangdaiscott** [comment]
我们这么设计是对的，不同的参数就应该打开不同的tab，因为业务变了。
你这边如果需要再同一个tab里面加载不同的业务，可以自己改造下路由加载的逻辑。

**Comment by mingyangsama** [comment]
您好，请问解决这个问题了吗，同样遇到这个问题了

**Comment by lobster17** [comment]
真是缺心眼的设计

**Comment by anuxs** [comment]
> 真是缺心眼的设计

我这是第一次看到用这么恶毒和不友好的字眼形容原始作者的设计，理由人家已经阐明，你觉得不符合你的预期，你可以自己提交pr，或者出门右转。用得着这么恶毒吗？你不配用开源项目，不合己意就恶语相向。

**Comment by lobster17** [comment]
> > 真是缺心眼的设计
> 
> 我这是第一次看到用这么恶毒和不友好的字眼形容原始作者的设计，理由人家已经阐明，你觉得不符合你的预期，你可以自己提交pr，或者出门右转。用得着这么恶毒吗？你不配用开源项目，不合己意就恶语相向。

你以为是我要用的么，公司之前买的商业版的，有问题他们也不解决，说就是这么设计的，设计上各种反人类的设计，这破框架也就忽悠一下培训学校出来的新人用还行，连基本的数据模型分层规范都没有，直接entity拿到vo层返回，呵呵了

**Comment by galaxist** [comment]
> > > 真是缺心眼的设计
> > 
> > 
> > 我这是第一次看到用这么恶毒和不友好的字眼形容原始作者的设计，理由人家已经阐明，你觉得不符合你的预期，你可以自己提交pr，或者出门右转。用得着这么恶毒吗？你不配用开源项目，不合己意就恶语相向。
> 
> 你以为是我要用的么，公司之前买的商业版的，有问题他们也不解决，说就是这么设计的，设计上各种反人类的设计，这破框架也就忽悠一下培训学校出来的新人用还行，连基本的数据模型分层规范都没有，直接entity拿到vo层返回，呵呵了

哈哈，自己公司架构选型时，用屁股决定的吗？
>连基本的数据模型分层规范都没有，直接entity拿到vo层返回，呵呵了
笑死人，自己不会改一下代码生成器模板么？花钱了您就是爹了？
![image](https://user-images.githubusercontent.com/3365218/94219915-74153180-ff1a-11ea-9685-8c7ddbc394e3.png)

**Comment by jinhongjie007** [comment]
在哪里改造？

**Comment by King10031** [comment]
> 在哪里改造？
解决了吗 老哥

**Comment by yangfuhua2009** [comment]
我刚看到消息，你那边解决没




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月12日(星期四) 中午11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 参数路由会打开标签页 (#1289)





  
在哪里改造？
 解决了吗 老哥
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by King10031** [comment]
> 我刚看到消息，你那边解决没
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月12日(星期四) 中午11:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jeecgboot/jeecg-boot] 参数路由会打开标签页 (#1289) 在哪里改造？ 解决了吗 老哥 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

并没有
