### ISSUE TITLE
数据字典

### ISSUE THREAD

**Issue by gelinagg** [zhangdaiscott/jeecg-boot#129]
新增的时候怎么获取数据字典的值呢？

1. - 1.      <a-col :md="6" :sm="8">
2. - 2.             <a-form-item label="性别">
3. - 3.               <a-select v-model="queryParam.sex" placeholder="请选择性别查询">
4. - 4.                 <a-select-option value="">请选择性别查询</a-select-option>
5. - 5.                 <a-select-option value="1">男性</a-select-option>
6. - 6.                 <a-select-option value="2">女性</a-select-option>
7. - 7.               </a-select>
8. - 8.             </a-form-item>
9. - 9.           </a-col>

查询的时候是ok的

**Comment by zhangdaiscott** [comment]
<j-dict-select-tag  v-decorator="['sex', {}]" :triggerChange="true" placeholder="请输入用户性别"
                  dictCode="sex"/>
http://jeecg-boot.mydoc.io/
