### ISSUE TITLE
关于jeecg-boot 权限问题

### ISSUE THREAD

**Issue by x522491416** [zhangdaiscott/jeecg-boot#1290]
##### 问题描述：
采用jeecg-boot 当作管理后台，如果在同一套代码里接入业务平台的代码，业务平台的用户拿到了token是不是就可以访问后台的接口。测试了也有数据返回。管理后台需要校验权限符合现在的jeecg-boot设计逻辑，而业务的用户我只需要校验他token是不是正确的就可以了，是起两个后台好，还是整合在一起，起两个后台的缺点就是有的代码需要重复写两遍，希望可以得到指点

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述不是特别清楚，如果需要多个业务模块开发，独立权限模块，可以看看cloud版
https://gitee.com/jeecg/jeecg-cloud
