### ISSUE TITLE
firefox浏览器,JEditableTable,拖动排序会导致进入搜索,safari和qq浏览器正常.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1291]
##### 版本号：
2.2.0

##### 问题描述：
firefox浏览器,拖动排序会导致进入搜索,
safari和qq浏览器正常.

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/20039800/83590377-32860280-a588-11ea-84b9-7bb1d093ee2d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by sjlei** [comment]
问题已解决，下个版本发布
