### ISSUE TITLE
报表配置中数据过百万时，查询10秒就超时了，应该如何解决

### ISSUE THREAD

**Issue by DrKarev** [zhangdaiscott/jeecg-boot#1295]
##### 版本号：
2.2.0

##### 问题描述：
报表配置中数据过百万时，查询10秒就超时了，应该如何解决

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12276846/83664403-86323380-a5fc-11ea-99fc-764cff3b662f.png)
![image](https://user-images.githubusercontent.com/12276846/83664467-9d712100-a5fc-11ea-96d8-4ad5b96c1735.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
vue的超时时间设置长点

**Comment by DrKarev** [comment]
> vue的超时时间设置长点
> src/utils/request.js
> 
> ![image](https://user-images.githubusercontent.com/3162115/83729954-fc757b00-a67a-11ea-92b7-85341e963eb9.png)
> 
> 如果此处改不生效，哪就得下个版本修复

确实改完以后也部生效，目前无解

**Comment by zhangdaiscott** [comment]
哪等下个版本吧，目前只能发布新版解决
