### ISSUE TITLE
用户表 org_code字段内容有的是A05A04A03,有的却是“财务部”导致数据权限过滤失败

### ISSUE THREAD

**Issue by ggi2003** [zhangdaiscott/jeecg-boot#1296]
##### 问题描述：
用户表 org_code字段内容有的是A05A04A03,有的却是“财务部”导致数据权限过滤失败

##### 截图&代码：

![image](https://user-images.githubusercontent.com/16665184/83677611-05306780-a60f-11ea-8210-bc53cdfa00c9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
为什么会出现中文情况？另外数据权限控制不是根据这个表字段实现的，而是根据用户登录所用部门编码来实现

**Comment by ggi2003** [comment]
感谢回复，当编辑用户时保存时那个字段就会被中文覆盖了，另外，需求是想通过orgCode的邮编功能过滤实现登陆用户查询本部门的用户，但sys_user表中并没有sys_org_code字段，所以就借用org_code字段来实现，这时就发现了问题
&nbsp;


 


张景辉

西安兆格电子信息技术有限公司 系统部

地址:丈八东路与丈八西路十字&nbsp;绿地蓝海1909

手机:17002908770






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年6月6日(星期六) 下午4:48
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: " "<mymailq@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 用户表 org_code字段内容有的是A05A04A03,有的却是“财务部”导致数据权限过滤失败 (#1296)





 
为什么会出现中文情况？另外数据权限控制不是根据这个表字段实现的，而是根据用户登录所用部门编码来实现

**Comment by zhangdaiscott** [comment]
已完成，下个版本修复
