### ISSUE TITLE
关于富文本初始化加载的问题

### ISSUE THREAD

**Issue by jianglei02** [zhangdaiscott/jeecg-boot#1297]
##### 截图&代码：
新建富文本编辑器，可以编辑
![image](https://user-images.githubusercontent.com/48478729/83716974-050e8700-a664-11ea-9e28-d12515068e77.png)
![image](https://user-images.githubusercontent.com/48478729/83716939-e9a37c00-a663-11ea-927e-2bfc08eebdec.png)
切换菜单路由，再次打开富文本编辑器，无法编辑且已存内容消失
![image](https://user-images.githubusercontent.com/48478729/83716995-18215700-a664-11ea-8711-57fe42641e7d.png)
![image](https://user-images.githubusercontent.com/48478729/83717066-41da7e00-a664-11ea-9d3c-08a6c97c5932.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
#1258
