### ISSUE TITLE
表单ERP主题（主表子表）点击下拉、时间控件时候报错appendChild of null

### ISSUE THREAD

**Issue by wb7131642** [zhangdaiscott/jeecg-boot#1298]
##### 版本号：
jeecg-boot 2.2.0（发布日期：2020-05-06）

##### 问题描述：
在线表单开发，选择表单ERP主题（主表子表，非代码）报错appendChild of null ，其他主题就可以用，点击字典类型下拉、表类型下拉、时间控件都报错无法使用

##### 截图&代码：

![DCD3AF8E-83E1-4d95-B3B2-BE71D975230D](https://user-images.githubusercontent.com/15027822/83723527-70ab2100-a671-11ea-80c4-e3eddbab0223.jpg)
![7450AD46-9026-4e36-90D2-2763FBD126FD](https://user-images.githubusercontent.com/15027822/83723541-76086b80-a671-11ea-8bb2-ccb2881cae40.jpg)
![ED76E896-91DB-4d7e-81CE-6649CAB93788](https://user-images.githubusercontent.com/15027822/83723660-9c2e0b80-a671-11ea-90b6-c39dccfbb38f.jpg)
![12786221-323C-45df-901E-AA7C723DD0D5](https://user-images.githubusercontent.com/15027822/83724559-127f3d80-a673-11ea-8b49-3f4350893880.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sunyjgithub** [comment]
同问 我也遇到了

**Comment by zhangdaiscott** [comment]
此问题已经处理，下个版本发布
