### ISSUE TITLE
在线表单开发中生成代码和设计的样式不一致

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1299]
##### 版本号：
v2.2.0

##### 问题描述：
在线表单开发中设置表单中状态属性为下拉框样式，有默认值，并且是无法修改时，通过代码生成器出来的代码样式不一致！
这里是表单设计的样式：
![image](https://user-images.githubusercontent.com/12267648/83841040-99dfb600-a732-11ea-8918-adfb02c6db0f.png)
这里是生成代码的样式：
![image](https://user-images.githubusercontent.com/12267648/83841097-b5e35780-a732-11ea-8fe5-12bcdcdc3a72.png)

这个有什么解决办法吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinwu-yang** [comment]
跟进一步测试之后发现，表单自定义按钮代码生成也没有渲染出来，我是哪里设置的不对吗？

**Comment by ChenGitHub12** [comment]
我也遇到这种问题了

**Comment by zhangdaiscott** [comment]
online生成未实现全部原样生成，目前不支持在线增强，自定义按钮等，默认值也咱不支持，后期待优化。。

目前可以先手工调整代码

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1312
