### ISSUE TITLE
更新业务数据时系统操作日志表插入异常

### ISSUE THREAD

**Issue by ICloveri** [zhangdaiscott/jeecg-boot#130]
更新自定义业务表，如更新的业务表字段较多，将导致系统操作日志日志异常，如下图。建议扩展该字段长度或调整为大字段类型。
![image](https://user-images.githubusercontent.com/8187042/58091150-74e9d500-7bfb-11e9-8bae-4df26d9748dc.png)

**Comment by zhangdaiscott** [comment]
自己把这个字段加长
