### ISSUE TITLE
关于用户选择器、部门选择器

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1300]
##### 版本号：
v2.2.0

##### 问题描述：
因为考虑到项目中还是会有多对多的情况存在，请问关于用户选择器、部门选择器这样的组件能支持自定义吗，一对多的情况下只能新增附表，目前想解决的是新增可以选择已存在数据的情况，有什么好的建议吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以通过popup
http://doc.jeecg.com/1276927

**Comment by xinwu-yang** [comment]
popup弹出报表内容是否支持单选呢，我看生成出来的都是多选！
