### ISSUE TITLE
MiniArea 组件属性传递 大小写错误 

### ISSUE THREAD

**Issue by lenovodn** [zhangdaiscott/jeecg-boot#1301]
##### 截图&代码：
<img width="570" alt="33" src="https://user-images.githubusercontent.com/39508656/83843003-b382fc80-a736-11ea-9976-a2786b853ee9.png">
<img width="1201" alt="22" src="https://user-images.githubusercontent.com/39508656/83843019-bb42a100-a736-11ea-913f-6c9adf21dbf1.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已收录，待分析
