### ISSUE TITLE
在线表单开发中功能测试代码与代码生成的代码功能不一致 （select二级联动）

### ISSUE THREAD

**Issue by ChenGitHub12** [zhangdaiscott/jeecg-boot#1302]
##### 版本号：
2.2

##### 问题描述：
select二级联动在功能测试中能使用，而生成代码之后就无法使用，select下拉框也变成了普通的input框

##### 截图&代码：
这是功能测试的样子
![image](https://user-images.githubusercontent.com/55070662/83845704-00b59d00-a73c-11ea-8b11-aeb52da18316.png)
![image](https://user-images.githubusercontent.com/55070662/83845767-1aef7b00-a73c-11ea-87f8-f0dc412c6e4d.png)
这是代码生成后
![image](https://user-images.githubusercontent.com/55070662/83845836-35295900-a73c-11ea-90c2-de56bd93fe14.png)
idea后台生成的代码
![image](https://user-images.githubusercontent.com/55070662/83845916-58540880-a73c-11ea-9662-286ab6ec1147.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个三级联动组件，不支持生成
