### ISSUE TITLE
vue工程打包之后加载过慢问题

### ISSUE THREAD

**Issue by wpc669418** [zhangdaiscott/jeecg-boot#1303]
##### 版本号：
2.2.0
##### 问题描述：
为什么我删了很多功能进行vue打包 还是比官方的大呢 即使我开了gzip vue工程是需要如何优化呢
vue.config.js 并未修改

##### 截图&代码：
vue.config.js:
![image](https://user-images.githubusercontent.com/18459776/83850865-1a5ae280-a744-11ea-8471-49ef2bfc4e65.png)

这是我的：
![image](https://user-images.githubusercontent.com/18459776/83850587-bb956900-a743-11ea-9b0e-e734dfa790a3.png)

这是官方的：
![image](https://user-images.githubusercontent.com/18459776/83850635-c9e38500-a743-11ea-8715-27634c72dd9f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wpc669418** [comment]
本地压缩完的文件：
![image](https://user-images.githubusercontent.com/18459776/83852270-1e87ff80-a746-11ea-97bd-d22eeb4d779d.png)

**Comment by zhangdaiscott** [comment]
大应该主要是因为依赖antd-vue的问题，因为目前不是动态加载的，可以参考
http://doc.jeecg.com/1658359

**Comment by Fliner** [comment]
我也是，遇到同样的问题，按需加载antd-vue也需要加载很多，登录页特别卡
