### ISSUE TITLE
菜单显示Bug

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1304]
##### 版本号：
v2.2.0

##### 问题描述：
在新建用户和只有一个菜单授权的情况下，显示了多个菜单
未设置首页，系统监控，常见案例，异常页等一级菜单的权限的情况下显示了出来
![image](https://user-images.githubusercontent.com/12267648/83852253-17f98800-a746-11ea-817f-73a49270823c.png)
针对sip_admin用户的授权
![image](https://user-images.githubusercontent.com/12267648/83852362-437c7280-a746-11ea-8c80-375327428a34.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确认下这个人是不是设置了默认角色

**Comment by xinwu-yang** [comment]
没有设置过默认角色，前两天发现是首页是代码里面硬编码上的。
![image](https://user-images.githubusercontent.com/12267648/83984293-017e4700-a967-11ea-8a62-f37f160c3934.png)

其他菜单是数据库里的数据，sys_permission表突然就有了一些数据给我设置了权限，但是create_by 都是null，我把这些数据设置成了del_flag=1就好了

**Comment by xinwu-yang** [comment]
这个是什么情况呢？我也没有主动去生成这些数据……
