### ISSUE TITLE
图表数据排序

### ISSUE THREAD

**Issue by 1204887861** [zhangdaiscott/jeecg-boot#1306]
##### 截图&代码：
[问题截图.xlsx](https://github.com/zhangdaiscott/jeecg-boot/files/4735395/default.xlsx)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你这是老版jeecg,不用再boot版里发，
在这里反馈
https://gitee.com/jeecg/jeecg
