### ISSUE TITLE
online在线表单时间选择组件无法选择，浏览器报错

### ISSUE THREAD

**Issue by sunyjgithub** [zhangdaiscott/jeecg-boot#1307]
##### 版本号：
jeecg-boot 2.2.0（发布日期：2020-05-06）

##### 问题描述：
online在线表单时间选择组件无法选择，浏览器报错
默认主体下 组件ok，erp主体 在线测试无法选择时间
##### 截图&代码：

![image](https://user-images.githubusercontent.com/37937289/83934121-e1bd1680-a7e0-11ea-8813-124a38f8e1e3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此bug已经修复，下个版本发布
