### ISSUE TITLE
online在线表单设计，表名称保存后无法修改

### ISSUE THREAD

**Issue by sunyjgithub** [zhangdaiscott/jeecg-boot#1308]
##### 版本号：
jeecg-boot 2.2.0（发布日期：2020-05-06）

##### 问题描述：
online在线表单设计，保存之后编辑，表名称不允许修改？是加了readonly属性吗？故意不允许修改表名称？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的，特意的设计
