### ISSUE TITLE
关于富文本菜单栏按钮文字找不到问题

### ISSUE THREAD

**Issue by Android-BRUCE** [zhangdaiscott/jeecg-boot#1309]
##### 问题描述：
关于富文本菜单栏按钮文字找不到问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18898962/83941484-56627600-a81e-11ea-8723-aef89fa535ed.png)

**Comment by Android-BRUCE** [comment]
只要点击菜单的-消息中心-模版管理-添加或者编辑，该富文本中菜单文字就失效。打开其他页面的富文本也会失效。

**Comment by zhangdaiscott** [comment]
看看是不是类似问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1268

**Comment by zhangdaiscott** [comment]
已经处理下个版本发布
