### ISSUE TITLE
表单在线配置 ，代码生成器生成的代码 不包括js增强的代码

### ISSUE THREAD

**Issue by sunyjgithub** [zhangdaiscott/jeecg-boot#1311]
##### 版本号：
当前最新版本： 2.2.0（发布日期：2020-05-06）

##### 问题描述：
表单在线配置 ，代码生成器生成的代码 不包括js增强的代码

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1312
