### ISSUE TITLE
markdown编辑器显示格式有问题 在线开发

### ISSUE THREAD

**Issue by sunyjgithub** [zhangdaiscott/jeecg-boot#1314]
##### 版本号：
2.2.0

##### 问题描述：
markdown编辑器显示格式有问题 在线开发，竖版排列

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37937289/84033500-83a05700-a9cb-11ea-82cb-dbe24f9444c1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已解决，下个版本发布
