### ISSUE TITLE
自定义模板javai ，模板参数

### ISSUE THREAD

**Issue by CSuperC** [zhangdaiscott/jeecg-boot#1315]
##### 问题描述：
自定义模板里面的参数，修改了配置文件,jeecg_config.properties文件，加入变量
base_package=com.xxx.xxx
修改javai 模板里面，引入变量base_package ，运行online 表单，不会自动替换，而且freemaker 报错不识别这个变量，这块我该怎么办？

##### 截图&代码：

import FreeMarker template error (DEBUG mode; use RETHROW in production!):
The following has evaluated to null or missing:
==> basePackage  [in template "default\\onetomany\\java\\${bussiPackage}\\${entityPackage}\\controller\\${entityName}Controller.javai" at line 20, column 10]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

FTL stack trace ("~" means nesting-related):
         - Failed at: ${basePackage}  [in template "default\\onetomany\\java\\${bussiPackage}\\${entityPackage}\\controller\\${entityName}Controller.javai" at line 20, column 8]
----

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CSuperC** [comment]
@zhangdaiscott @klniu

**Comment by zhangdaiscott** [comment]
不是这么玩的，不支持这样的自定义变量
