### ISSUE TITLE
建议mybatis-plus升级到3.3.2

### ISSUE THREAD

**Issue by haotian2546** [zhangdaiscott/jeecg-boot#1317]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/13749495/84115244-518d0480-aa60-11ea-8b23-9ad9a5789065.png)

**Comment by zhangdaiscott** [comment]
ok

**Comment by qq781548819** [comment]
同求方案升级

**Comment by Succy** [comment]
> ##### 版本号：2.2.0
> ##### 问题描述：个人业务需求用到mybatis-plus3.3.2的一些新特性，自己折腾有一波报错，希望官方能升级下哦
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/13749495/84115244-518d0480-aa60-11ea-8b23-9ad9a5789065.png)

我也升级了，自己升级的，把对应的报错的位置return的wrapper注释就行了
