### ISSUE TITLE
Online表单开发，点击”功能测试“按钮，页面控制台报错：timeout of 9000ms exceeded

### ISSUE THREAD

**Issue by L-3D2Y** [zhangdaiscott/jeecg-boot#1318]
##### 截图&代码：
<img width="1094" alt="微信截图_20200609144631" src="https://user-images.githubusercontent.com/66663389/84115093-0a9f0f00-aa60-11ea-95e7-8f9e61b42c1b.png">
<img width="882" alt="微信图片_20200609144720" src="https://user-images.githubusercontent.com/66663389/84115160-2b676480-aa60-11ea-93aa-3ff75c05f0a9.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本，超时时间设置长些
