### ISSUE TITLE
应该没有ms单位吧

### ISSUE THREAD

**Issue by star45** [zhangdaiscott/jeecg-boot#132]
![image](https://user-images.githubusercontent.com/5771621/58143348-1e24df80-7c7d-11e9-989d-a50c8c0d8eb1.png)

请求追踪模块的响应状态码。

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布，3Q

**Comment by yihuiluo235** [comment]
我也发现这个问题了。
