### ISSUE TITLE
上传文件出现: The temporary upload location is not valid.

### ISSUE THREAD

**Issue by Royyu1215** [zhangdaiscott/jeecg-boot#1320]
##### 截图&代码：

org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.6239989728636105816.19530/work/Tomcat/localhost/ROOT] is not valid

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
prod配置文件中加入以下代码，以及需要发布到linux系统的时候

server:
    tomcat:
        #修改tomcat临时文件生成位置，避免被linux自动回收机制回收
        #参考系统centos7.4，文件/usr/lib/tmpfiles.d/tmp.conf
        basedir: /opt/jeecg-boot/tomcat

**Comment by Sean-214** [comment]
@zhangdaiscott Spring Boot 从 2.1.4.RELEASE 版本开始已修复，建议更新Spring Boot版本
参考：
https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#boot-features-embedded-container
https://github.com/spring-projects/spring-boot/issues/9616#issuecomment-513346373
