### ISSUE TITLE
首次加载非常慢，#88开启gzip压缩没有解决问题

### ISSUE THREAD

**Issue by J-cafe** [zhangdaiscott/jeecg-boot#1321]
##### 版本号：
2.2.0

##### 问题描述：
首次加载非常慢，#88开启gzip压缩没有解决问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22951972/84145732-03422a80-aa8d-11ea-9d38-59224ac408db.png)

37秒的加载时间

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
nginx配置，请截图

**Comment by J-cafe** [comment]
![image](https://user-images.githubusercontent.com/22951972/84215785-ff98bd00-aaf9-11ea-9fcc-0f586a5434dd.png)

**Comment by zhangdaiscott** [comment]
看配置没问题，你试试boot.jeecg.com是否存在你的30几秒的问题
五、nginx 开启压缩，提高首页访问效率
https://github.com/zhangdaiscott/jeecg-boot/issues/88

**Comment by JaneYork** [comment]
后来怎么解决的，同问，开启了GZIP还是30秒
