### ISSUE TITLE
online表单创建人问题

### ISSUE THREAD

**Issue by Fillovida** [zhangdaiscott/jeecg-boot#1322]
##### 版本号：
2.2.0

##### 问题描述：
online表单新建数据：
1、功能测试时，功能正常。能够获取并插入创建人信息；
2、生成代码后，新增一条数据，创建人是空的。

##### 截图&代码：
![ScreenClip](https://user-images.githubusercontent.com/50174339/84155570-0e03bc00-aa9b-11ea-9781-7cc40a0225dd.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的创建人字段是什么

**Comment by Fillovida** [comment]
@zhangdaiscott 创建人字段是create_by。就是有点疑惑功能测试中是没问题的呢
![微信截图_20200610100305](https://user-images.githubusercontent.com/50174339/84218745-9d43ba80-ab01-11ea-98aa-13163099849d.jpg)

**Comment by Fillovida** [comment]
@zhangdaiscott 确实有排除shiro拦截，是这个导致的，去掉就好了。谢谢！
