### ISSUE TITLE
popup弹出报表内容是否支持单选呢，我看生成出来的都是多选！

### ISSUE THREAD

**Issue by kevin-lr** [zhangdaiscott/jeecg-boot#1323]
版本号：
v2.2.0

问题描述：
popup弹出报表内容是否支持单选呢，我看生成出来的都是多选！

截图&代码：
![image](https://user-images.githubusercontent.com/54308424/84237623-430c1f00-ab2c-11ea-8b68-249198892dd5.png)

**Comment by zhangdaiscott** [comment]
多选属性设置为false即可
![image](https://user-images.githubusercontent.com/3162115/84344512-91c5c180-abdd-11ea-9844-fb78c16ee05d.png)

**Comment by kevin-lr** [comment]
请问开源版JPopup.vue这个文件在哪？

**Comment by kevin-lr** [comment]
没有这个文件 online开发能提供个设置的地方吗

**Comment by qianlei0007** [comment]
你这个问题解决了吗？
