### ISSUE TITLE
下拉联动组件层级有问题

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1324]
##### 版本号：
v2.2.0

##### 问题描述：
下拉联动组件Bug，最外级没有显示父分类字典下的内容，而是显示父分类字典

这里是分类字典
![image](https://user-images.githubusercontent.com/12267648/84245729-15c56e00-ab38-11ea-863a-63ec269b220e.png)

这里是联动组件对应的字段和字典
![image](https://user-images.githubusercontent.com/12267648/84245887-4f967480-ab38-11ea-89b9-41386fee1e87.png)

厂家不应该显示天翼网络内容吗
![image](https://user-images.githubusercontent.com/12267648/84246172-caf82600-ab38-11ea-8d30-c1cc795b808f.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by gelinagg** [comment]
这个是三级联动，可以用么

**Comment by xinwu-yang** [comment]
@gelinagg 不能，我打算自己写一个，这个bug太多

**Comment by tygithub1** [comment]
文档描述如下：
名称	描述
table	数据库表名
txt	控件显示的值
key	控件需要存储的值
linkField	级联组件的其他字段名称，上例配置了市，区字段名
idField	数据的标识
pidField	上下级关系的表示字段
**condition	查询条件，只是第一个级联下拉框的数据筛选条件**
1.这个条件是第一个下拉框数据来源的查询条件，并不是你理解的父id。
2.这个是联动组件，并不是说一定要3级，linkField	级联组件的其他字段名称，这里你配置了几个他就会再多生成几个级联

**Comment by xinwu-yang** [comment]
@tygithub1  是的呢，我也是这么理解的。但是如我上图的问题，我在condition 配置 B03 那么当前字段下拉框出现的选项应该是B03A01 B03A02才对呀，我这里配置B03下拉框就是B03对应的值，难道还是我理解真的出问题了吗
