### ISSUE TITLE
系统用户编辑后org_code会变成中文部门名称。

### ISSUE THREAD

**Issue by zhouyinzhi428** [zhangdaiscott/jeecg-boot#1326]
##### 版本号：
2.2.0

##### 问题描述：
系统自带的用户编辑，编辑后数据库中的sys_org_code会变成中文部门名称。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录确认

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1296
重复问题关闭一个
