### ISSUE TITLE
上传附件名带 # 号等，被url解析，无法下载，部门选择器能否增加父子关联prop

### ISSUE THREAD

**Issue by azunia** [zhangdaiscott/jeecg-boot#1327]
##### 版本号：
v2.2

##### 问题描述：
1. 上传附件名带 # 号等，被url解析，无法下载
2. 部门选择器能否增加父子关联prop

##### 截图&代码：
上传附件名带 # 号等，被url解析，无法下载，部门选择器能否增加父子关联prop

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
