### ISSUE TITLE
linux jar包运行 启动

### ISSUE THREAD

**Issue by fangpengxian** [zhangdaiscott/jeecg-boot#1332]
##### 版本号：

2.2.0
##### 问题描述：

linux 部署jar包运行 启动 黑屏

##### 截图&代码：

-

友情提示： 未按格式要求发帖，会直接删掉。
![1591884307(1)](https://user-images.githubusercontent.com/44767532/84394543-a8950400-ac2f-11ea-9f35-d1db14f57ab0.png)

**Comment by zhangdaiscott** [comment]
内存不够？监控下linux的电脑情况

**Comment by fangpengxian** [comment]
我用了好几台服务器 都试了  都不行--

**Comment by zhangdaiscott** [comment]
自己排查下，这个不清楚，没遇到过这个情况
