### ISSUE TITLE
V2.2.0内一些接口标注@Deprecated的疑问

### ISSUE THREAD

**Issue by Succy** [zhangdaiscott/jeecg-boot#1333]
##### 版本号：
v2.2.0

##### 问题描述：
在做了一些代码改动后，重新编译时提示了很多已经过时的方法，进去review代码之后发现，很多方法被标记了过时，但是在控制器里还是有调用的，是官方还没做好新的适配吗？
##### 截图&代码：
![QQ截图20200612163050](https://user-images.githubusercontent.com/20968762/84482544-87352600-acca-11ea-995f-3ae8cf5c55ac.png)
![QQ截图20200612162928](https://user-images.githubusercontent.com/20968762/84482549-88fee980-acca-11ea-98ab-301db7c3f359.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时标记的，还没抽时间重构，后期会逐步改造
