### ISSUE TITLE
j-dict-select-tag 设置 triggerChange = "true" 下拉选择及单选组件不能选中

### ISSUE THREAD

**Issue by iazeyang** [zhangdaiscott/jeecg-boot#1334]
##### 版本号：
"dependencies": {
    "@antv/data-set": "^0.10.2",
    "@jeecg/antd-online-re": "2.1.3",
    "@tinymce/tinymce-vue": "^2.0.0",
    "ant-design-vue": "^1.4.0",
    "antd": "^4.3.3",
    "apexcharts": "^3.6.5",
    "axios": "^0.18.0",
    "clipboard": "^2.0.4",
    "codemirror": "^5.46.0",
    "crypto-js": "^3.1.9-1",
    "dayjs": "^1.8.0",
    "enquire.js": "^2.1.6",
    "js-cookie": "^2.2.0",
    "lodash.get": "^4.4.2",
    "lodash.pick": "^4.4.0",
    "md5": "^2.2.1",
    "nprogress": "^0.2.0",
    "tinymce": "^5.0.2",
    "viser-vue": "^2.4.4",
    "vue": "^2.6.10",
    "vue-apexcharts": "^1.3.2",
    "vue-class-component": "^6.0.0",
    "vue-cropper": "^0.4.8",
    "vue-i18n": "^8.7.0",
    "vue-loader": "^15.7.0",
    "vue-ls": "^3.2.0",
    "vue-photo-preview": "^1.1.3",
    "vue-print-nb-jeecg": "^1.0.9",
    "vue-property-decorator": "^7.3.0",
    "vue-router": "^3.0.1",
    "vue-splitpane": "^1.0.4",
    "vuedraggable": "^2.20.0",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.1"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.2.5",
    "@vue/cli-plugin-babel": "^3.3.0",
    "@vue/cli-plugin-eslint": "^3.3.0",
    "@vue/cli-service": "^3.3.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.1.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "^2.6.10",
    "html-webpack-plugin": "^4.0.0-beta.11"
  }

##### 问题描述：
j-dict-select-tag 设置 triggerChange = "true" 下拉选择及单选组件不能选中

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54666212/84504442-87471d00-acee-11ea-839e-a65787233743.png)

![image](https://user-images.githubusercontent.com/54666212/84504751-0d636380-acef-11ea-80d6-9f3b257b7e85.png)

![image](https://user-images.githubusercontent.com/54666212/84504797-223ff700-acef-11ea-8f08-e233e336eb2d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
v-model和v-decorator你到底想用哪个？
