### ISSUE TITLE
下拉搜索功能如何传入当前登录用户名过滤数据呢？

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1337]
##### 版本号：
2.2.0

##### 问题描述：
1、下拉框搜索：字典Table列输入的是表名和条件，给添加如何传递当前用户的登录名呢？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59654718/84592306-2f87ed80-ae77-11ea-8a78-0be271861af6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个目前还不支持

**Comment by yanyapeng123** [comment]
老大跪求，很多的功能哈


1、代码生成后，希望带有查询功能


2、代码生成后，设置的订单编号生成没有了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 下午4:13
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"849610355"<15114890832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 下拉搜索功能如何传入当前登录用户名过滤数据呢？ (#1337)





 
这个目前还不支持
