### ISSUE TITLE
Java接口权限不能及时生效，需要重新登录

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1338]
##### 版本号：
v2.2.0

##### 问题描述：
当前账号给自己设置权限之后（使用Shiro @RequiresPermissions设置API权限），如果不重新登录一下，权限还是有依然还是有的，需要登出在登入，这样才能加载到最新权限！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12267648/84597510-f8293900-ae96-11ea-99e2-709bc2dc796e.png)

![image](https://user-images.githubusercontent.com/12267648/84597528-0e36f980-ae97-11ea-80c1-2fcdb33af6fe.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个设计就是这样的
