### ISSUE TITLE
JModal自动退出.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1342]
##### 版本号：
2.2.0
##### 问题描述：
随便找一个JModal的界面,打开后, 拖动浏览器,调整浏览器窗口大小, 会造成自动隐藏,导致用户数据未保存丢失.建议不要使用JModal方式.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
能演示看看吗

**Comment by GordonHuangYong** [comment]
比如: http://boot.jeecg.com/joa/JoaEmployeeLeaveList
打开一个请假单, 缩小浏览器窗口到一定大小,就会出现.全屏更容易出现.

**Comment by GordonHuangYong** [comment]
现在来看, 应该和JModal没有关系, 在列表界面, 会产生页面刷新, 才是导致JModal自动隐藏的原因.

**Comment by zhangdaiscott** [comment]
录个gif或者小视频

**Comment by GordonHuangYong** [comment]
[QQ20200616-102925-HD.mp4.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4784014/QQ20200616-102925-HD.mp4.zip)

**Comment by zhangdaiscott** [comment]
这个问题别人提过，这不是问题，是我们特意为自适应加的，在屏幕缩小的时候，会切换为单tab模式。你可以搜下issue，应该会找到如何去掉此机制
