### ISSUE TITLE
前端打包js文件太大（7M），造成第一次访问速度太慢（60秒以上）

### ISSUE THREAD

**Issue by 224148793** [zhangdaiscott/jeecg-boot#1343]
##### 版本号：
2.2.0

##### 问题描述：
前端打包js文件太大（7M），造成第一次访问速度太慢（60秒以上）

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1306178/84731062-4c810580-afca-11ea-9aee-424ceef8acad.png)
![image](https://user-images.githubusercontent.com/1306178/84731073-5276e680-afca-11ea-8e60-71f50c4af293.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 224148793** [comment]
![微信图片_20200616120822](https://user-images.githubusercontent.com/1306178/84731171-a2ee4400-afca-11ea-93cd-64c0653589d6.png)
![微信图片_20200616120903](https://user-images.githubusercontent.com/1306178/84731174-a41f7100-afca-11ea-82e7-2118e7e1a430.png)

**Comment by 224148793** [comment]
gzip是已经开启（目前的60秒，是在压缩后3M的情况下的速度）

**Comment by zhangdaiscott** [comment]
nginx压缩开启的对吗
你可以用boot.jeecg.com 测试看看
![image](https://user-images.githubusercontent.com/3162115/84747620-15225100-afea-11ea-9a20-ad862d057ef3.png)

**Comment by 224148793** [comment]
我看过boot.jeecg.com，你们是很少。我打包js后大小是7M，开启gzip后，前端是2.5M，访问时间是1分钟。所以想问，是不是你们打包做什么什么特殊配置？你们打包后的文件肯定也没有7M吧

**Comment by zhangdaiscott** [comment]
打包后也是7Mz
你应该是nginx压缩设置未生效
![image](https://user-images.githubusercontent.com/3162115/84753483-a0531500-aff1-11ea-8db7-879e8c61a041.png)

**Comment by 224148793** [comment]
感谢回复，但是如果nginx没有生效，下载的大小不会显示是2.5M，肯定显示7M。另外你们的nginx可以将7M的js，可以gzip压缩到9k ？1000多倍的压缩比？

**Comment by 224148793** [comment]
可能还是我没有表述清楚吧，我不是说整个dist文件夹打包是7M，我是我生成的有一个js文件是7M。可以看前面的图片。chunk-vendors.ee53c28d.js  这个文件有7M，然后gzip以后是2.5M。谢谢。

**Comment by zhangdaiscott** [comment]
如果发布版本不需要online模块，可以把online的依赖删掉会小非常多
![image](https://user-images.githubusercontent.com/3162115/84767413-fd0bfb00-b004-11ea-8239-233849c7f820.png)

**Comment by javaAjun** [comment]
> 如果发布版本不需要online模块，可以把online的依赖删掉会小非常多
> 删掉重新打包
> ![image](https://user-images.githubusercontent.com/3162115/84767413-fd0bfb00-b004-11ea-8239-233849c7f820.png)

这个我试过,没小多少,而且我这边的问题和他的一模一样,有个单js文件7M多,打包后,2.5M,打包后也很大
nginx成功开启了gzip,因为根据请求能看出来,那个js大小就是2.5M,耗时18秒
![image](https://user-images.githubusercontent.com/38597827/85264939-1220d800-b4a4-11ea-863a-1a70846f2237.png)
![image](https://user-images.githubusercontent.com/38597827/85264987-249b1180-b4a4-11ea-8076-72a5517ffe02.png)

**Comment by zhangdaiscott** [comment]
按需加载 减小打包
http://doc.jeecg.com/1658359

**Comment by zhangdaiscott** [comment]
删除@jeecg/antd-online-beta220，换成@jeecg/antd-online-220-mini
详细参考此链接： https://www.npmjs.com/package/@jeecg/antd-online-beta220-mini

**Comment by zd551317** [comment]
换成@ jeecg / antd-online-220-mini  bulid报错了

**Comment by zd551317** [comment]
> **新方案**
> 
> 删除@ jeecg / antd-online-beta220，换成@ jeecg / antd-online-220-mini 
> `online的依赖从5M减少至1.3M`
> 详细参考此链接：[https](https://www.npmjs.com/package/@jeecg/antd-online-beta220-mini) : //www.npmjs.com/package/@jeecg/antd-online-beta220-mini[](https://www.npmjs.com/package/@jeecg/antd-online-beta220-mini)

换成@ jeecg / antd-online-220-mini bulid报错了

**Comment by zhangdaiscott** [comment]
你安装依赖了？

**Comment by zd551317** [comment]
> 你安装依赖了？
> 纱安装
> 
> 重新补充了操作步骤，看四楼

C:\work\jeecg-boot\ant-design-vue-jeecg>yarn add @jeecg/antd-online-220-mini
yarn add v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@jeecg%2fantd-online-220-mini: Not found".
仓库找不到这个依赖？

**Comment by zd551317** [comment]
> 你安装依赖了？
> yarn install
> 
> 重新补充了操作步骤，看四楼

npm i @jeecg/antd-online-beta220-mini执行太慢了，依赖加载不到本地

**Comment by chongyangwang** [comment]
版本号：
2.2.0

问题描述：

前端打包js文件太大   
![image](https://user-images.githubusercontent.com/32251099/88448204-bb753800-ce6d-11ea-96f8-f344f17cdb93.png)


根据此issue解决方法跟进  分别尝试楼上两种解决方案

1.   本地直接删除依赖  "@jeecg/antd-online-beta220": "^1.0.1"   会导致富文本编辑功能失效
    


2.  yarn add @jeecg/antd-online-220-mini  
![image](https://user-images.githubusercontent.com/32251099/88448278-ba90d600-ce6e-11ea-843a-abce40b0eed2.png)

求教

**Comment by zhangdaiscott** [comment]
是这样的，就是因为富文本太大所以去掉了

**Comment by chongyangwang** [comment]
1. 第一种方案
官方的意思是   只在上线的时候把 @jeecg/antd-online-beta220": "^1.0.1   这个包删掉？   本地开发依然留着？  如果删掉  部署到线上有问题怎么办？

2.  第二种方案  @jeecg/antd-online-220-mini 的依赖库始终装不上   感觉这个包根本不存在吧？

**Comment by veranew** [comment]
> 1. 第一种方案
>    官方的意思是   只在上线的时候把 @jeecg/antd-online-beta220": "^1.0.1   这个包删掉？   本地开发依然留着？  如果删掉  部署到线上有问题怎么办？
> 2. 第二种方案  @jeecg/antd-online-220-mini 的依赖库始终装不上   感觉这个包根本不存在吧？

我也一直装不上，有什么解决方法吗

**Comment by rjliulei** [comment]
用最新的版本，体积是小了，可还是慢。。也得接近1M。。。

**Comment by zhangdaiscott** [comment]
1M已经最大努力了

**Comment by devinRex** [comment]
是否考虑提供用url的形式引入呢，通过cdn和浏览器强缓存去做缓存，chunk-vendor做持久化缓存还挺困难的
