### ISSUE TITLE
在线开发里，表生成视图后有几个bug

### ISSUE THREAD

**Issue by wb7131642** [zhangdaiscott/jeecg-boot#1344]
##### 版本号：
jeecg-boot 2.2.0（发布日期：2020-05-06）

##### 问题描述：
1.编辑视图后视图版本未加，加到原表版本上了
2.把视图地址做成菜单后，点击报错，页面不能显示
3.原表查询默认值未成功显示，视图的查询默认值能成功显示

##### 截图&代码： 图片怎么加载不了。。。
问题1图片VVVVVVVVVVV

![1](https://user-images.githubusercontent.com/15027822/84735020-08dfc900-afd5-11ea-9868-7cc0e38cc474.png)
![2](https://user-images.githubusercontent.com/15027822/84735034-0ed5aa00-afd5-11ea-9ab1-6293fe48a30d.png)

问题2图片VVVVVVVVVV
![3](https://user-images.githubusercontent.com/15027822/84735042-1432f480-afd5-11ea-883c-66fe504a1cc0.png)

问题3图片VVVVVVVVV
![4](https://user-images.githubusercontent.com/15027822/84735284-b5ba4600-afd5-11ea-98fe-c640081281f6.png)
![5](https://user-images.githubusercontent.com/15027822/84735327-d4b8d800-afd5-11ea-828a-66bc3f168f2d.png)
![6](https://user-images.githubusercontent.com/15027822/84735336-daaeb900-afd5-11ea-9bcc-d13306f1f7cd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已收录

**Comment by zhangdaiscott** [comment]
此处功能更改过，待下个版本更新
