### ISSUE TITLE
在online-form包内String数组为什么有close()

### ISSUE THREAD

**Issue by Shaoccc** [zhangdaiscott/jeecg-boot#1345]
##### 版本号：
2.2.0

##### 问题描述：
String数组后边为什么有close方法？

##### 截图&代码：
如图
![](http://img.sayounala.cn/qiniu_img/java1.png)
.
![](http://img.sayounala.cn/qiniu_img/java2.png)
607行的 var17.close();
String数组后边为什么有close方法？

**Comment by zhangdaiscott** [comment]
应该属于编译问题，代码是无问题的
