### ISSUE TITLE
关于JSelectDepartModal和JSelectUserByDepModal的一些建议

### ISSUE THREAD

**Issue by azunia** [zhangdaiscott/jeecg-boot#1346]
##### 版本号：
2.2

##### 问题描述：
JSelectDepart 能否增加 props 部门编码 返回对应的部门和下属部门
JSelectUserByDep 能否增加 props 部门编码 返回对应的部门和下属部门来获取其中的成员信息？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
暂不支持
