### ISSUE TITLE
前端分页问题，请老师指教

### ISSUE THREAD

**Issue by Fillovida** [zhangdaiscott/jeecg-boot#1347]
##### 版本号：
2.2.0

##### 问题描述：
老师您好，请问如果同一个页面内有多个<a-table>，且都需要分页的话，应该不能共用混入里的分页数据吧，有什么其他的办法么？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把就把混入拿出来，咱们页面上自己写即可。
