### ISSUE TITLE
代码生成器开发报错：接口访问404，新建模块，前端及在线表单测试都可以正常使用

### ISSUE THREAD

**Issue by Gabriel0402** [zhangdaiscott/jeecg-boot#1348]
##### 版本号：
2.2.0

##### 问题描述：
建立新模块使用生成的代码，模块依赖已配置好。截图如下：pipe-module是新建模块
![Screenshot 2020-06-16 at 23 33 09](https://user-images.githubusercontent.com/2779607/84834637-c5637a00-b029-11ea-978b-2214124634ae.png)

前端也配置好，并且能够发出正确的接口访问，然而接口访问返回404。

##### 截图&代码：
生成代码截图：
![Screenshot 2020-06-16 at 22 56 08](https://user-images.githubusercontent.com/2779607/84832136-9bf41f80-b024-11ea-9c6e-588544e2d8ac.png)

其中@RequestMapping("/demo/pipeInfo")
然而接口访问为404，如图：
![Screenshot 2020-06-16 at 22 57 40](https://user-images.githubusercontent.com/2779607/84832274-dbbb0700-b024-11ea-84cf-e0efef662414.png)

菜单管理配置正确，并且在角色管理中设置了对应的用户权限。同时online表单开发的功能测试可以正常使用，检查数据库里的表正确，是online表单里的内容。然而只是生成代码不可以。不知道是不是因为模块命名问题？

请问有没有方法debug，谢谢！

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成的新代码

1、如果是新路径，注意配置扫码路径
2、后台需要重启

**Comment by Gabriel0402** [comment]
尝试根据帖子https://blog.csdn.net/gwcgwcjava/article/details/95967349配置扫描路径
1. 未找到ComponentScan的扫描配置
2. 更改了mybatis-plus的设置于新的模块，但是还是会出现404的问题。

现在能找到的唯一解决办法：
将生成代码放入org.jeecg.modules。
请问有没有对应扫描配置的帖子可以学习下，谢谢！

**Comment by Bill-TT** [comment]
> 尝试根据帖子https://blog.csdn.net/gwcgwcjava/article/details/95967349
> 配置扫描路径
> 
> 1. 未找到ComponentScan的扫描配置
> 2. 更改了mybatis-plus的设置于新的模块，但是还是会出现404的问题。
> 
> 现在能找到的唯一解决办法：
> 将生成代码放入org.jeecg.modules。
> 请问有没有对应扫描配置的帖子可以学习下，谢谢！

兄弟有找到改的地方吗

**Comment by Gabriel0402** [comment]
@Bill-TT 没有，只能放到module下面可以用。。

**Comment by DachengChen** [comment]
需要 重新 mvn install
