### ISSUE TITLE
多数据源问题

### ISSUE THREAD

**Issue by lanwaixian** [zhangdaiscott/jeecg-boot#1349]
##### 问题描述：多数据源配了SQL SERVER + ORACLE，validationQuery这个该怎么配，现在写的“SELECT 1”仅适用于SQL SERVER，ORACLE对应的不知怎么配上去，可以配两个validationQuery吗？
后端启动时总报错：“druid.sql.Statement:149 - {conn-10001, stmt-20000} execute error. null”

##### 截图&代码：
![Annotation 2020-06-17 081101](https://user-images.githubusercontent.com/13619880/84840574-8574b500-b072-11ea-8ebd-8e66db920a9b.jpg)

![Annotation 2020-06-17 081044](https://user-images.githubusercontent.com/13619880/84840577-8c032c80-b072-11ea-91c4-9a1bf450528d.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
百度druid连接池
