### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ghkyh** [zhangdaiscott/jeecg-boot#135]
Error creating bean with name 'shiroFilter' defined in class path resource [org/jeecg/config/ShiroConfig.class]: BeanPostProcessor before instantiation of bean failed;
 java.lang.NoClassDefFoundError: io/netty/util/Timer

**Comment by zhangdaiscott** [comment]
项目 clean，没自动编译吧。或者不是吗mavan java 项目
