### ISSUE TITLE
关于后台页面滚动问题能不能改造一下

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1350]
##### 问题描述：

 这个后台页面能不能设置左侧功能区域与右侧表单各自滚动，顶部区域固定，不要一滚动，整个页面都跟着滚动了，总是经常要去拉滚动条，体验不太友好。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/85112449-397b6900-b248-11ea-9bc0-4a4c7a489aec.png)

![image](https://user-images.githubusercontent.com/3162115/85112403-2b2d4d00-b248-11ea-92cc-a4f060fe0a54.png)
