### ISSUE TITLE
JPopup组件怎么传递动态参数

### ISSUE THREAD

**Issue by javaAjun** [zhangdaiscott/jeecg-boot#1351]
##### 问题描述：
你这个组件我怎么把动态参数穿进去呀,比如我在报表有个动态参数 where name=${name}这种,我是用这个组件怎么把参数传进去呢,

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38597827/84851860-f1184b80-b08d-11ea-98e9-b65175eba2ca.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273862

**Comment by javaAjun** [comment]
我问的是生成的组件传,而不是测试地址传,我那样传有啥用啊?
![image](https://user-images.githubusercontent.com/38597827/84879780-3a808f00-b0be-11ea-92b0-897516c3cbc9.png)
这种

> http://doc.jeecg.com/1273862
