### ISSUE TITLE
在线生成的代码，配置后，具体提示：资源未找到

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1352]
##### 版本号：
2.2

##### 问题描述：
1、在线生成的一对多表关系

2、配置菜单后，提示，资源未找到

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59654718/84885899-3eb0aa80-b0c6-11ea-8c0a-bf879500cdc6.png)
![image](https://user-images.githubusercontent.com/59654718/84885915-42dcc800-b0c6-11ea-80a4-800190ef1b13.png)
![image](https://user-images.githubusercontent.com/59654718/84885923-45d7b880-b0c6-11ea-8a33-5153e064e811.png)
![image](https://user-images.githubusercontent.com/59654718/84885928-483a1280-b0c6-11ea-939f-b2ccfa9e2005.png)
![image](https://user-images.githubusercontent.com/59654718/84885934-4b350300-b0c6-11ea-975e-b4d3a78924f7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mrbear2019** [comment]
解决了吗  我也遇到这个问题了

**Comment by Fxiao1** [comment]
我也遇到了，请问解决了吗？
