### ISSUE TITLE
常见案例中一对多示例添加子表时，删除存在BUG

### ISSUE THREAD

**Issue by zhaozhixin001** [zhangdaiscott/jeecg-boot#1354]
##### 截图&代码：
![1592444972(1)](https://user-images.githubusercontent.com/61789674/84968480-2897fe00-b149-11ea-9455-beaed1c25b94.jpg)

点击图中的 删除号，会出现下图情况

![1592444992(1)](https://user-images.githubusercontent.com/61789674/84968486-2d5cb200-b149-11ea-9ae4-0923d2f08909.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
已修复
