### ISSUE TITLE
关于首页手机验证码登录的问题

### ISSUE THREAD

**Issue by fangLinYu** [zhangdaiscott/jeecg-boot#1355]
##### 版本号：
2.2.0

##### 问题描述：
首页登录时手机验证码登录, 发送验证码时,smsmode的值为0, 应该为2

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31471718/84976118-a82dc900-b159-11ea-891a-c5d57b1eb9ba.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wangjing1995** [comment]
怎么设置验证码那里的controller啊？

**Comment by fangLinYu** [comment]
controller ->jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/LoginController.java
ant -> ant-design-vue-jeecg/src/views/user/Login.vue
附上两个路径
只要在Login.vue的getCaptcha()方法中修改smsParams.smsmode = "2" 应该就可以了 



fanglin_yu@163.com
 
发件人： wangjing1995
发送时间： 2020-06-18 16:34
收件人： zhangdaiscott/jeecg-boot
抄送： fangLinYu; Author
主题： Re: [zhangdaiscott/jeecg-boot] 关于首页手机验证码登录的问题 (#1355)
怎么设置验证码那里的controller啊？

**Comment by wangjing1995** [comment]
后啦我解决了，因为我用的是自己公司的阿里云短信平台，然后本身代码是不需要改的，改的只是几个签名
