### ISSUE TITLE
需要将行表中的名称带到新建的标签上

### ISSUE THREAD

**Issue by jerometang** [zhangdaiscott/jeecg-boot#1357]
##### 版本号：
2.2.0

##### 问题描述：
需要将行表中的名称带到新建的标签上。
现在通过push路由的方式可以添加新标签，但是名称不能自定义
this.$router.push({ path: url})

##### 截图&代码：
![TIM截图20200618153817](https://user-images.githubusercontent.com/45664016/84992351-5b0e1f00-b17a-11ea-9b09-0d923a72b3b5.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持

**Comment by LancCJ** [comment]
> 不支持

请问下 点击功能测试 然后会新建一个标签，这块代码该如何写？
