### ISSUE TITLE
上传图片，当关掉页面再次进入上传页，图片中＋图标消失

### ISSUE THREAD

**Issue by ZhangYP997** [zhangdaiscott/jeecg-boot#1358]
##### 问题描述：
在上传图片页面，当关掉页面再次进入上传页，图片中＋图标消失

##### 截图&代码：
1.新打开的也页面
![image](https://user-images.githubusercontent.com/29109419/84999829-42a30200-b184-11ea-9ba1-4af936d458d9.png)

2.上传图片后页面，上传后不提交关闭页面
![image](https://user-images.githubusercontent.com/29109419/84999995-67977500-b184-11ea-9b03-1cf0e3376dbf.png)

3.再次打开页面
![image](https://user-images.githubusercontent.com/29109419/85000104-8d247e80-b184-11ea-8651-5901bfc4a7bd.png)

修改方法：修改文件》》》ant-design-vue-jeecg\src\components\jeecg\JImageUpload.vue
 ```
 82   watch:{
 83          value(val){
 84                if (val instanceof Array) {
 85                       this.initFileList(val.join(','))
 86                } else {
 87                    this.initFileList(val)
 88                }
 89               if (!val){
 90                    this.picUrl = false;
 91                }
 92           }
 93     }
```
![image](https://user-images.githubusercontent.com/29109419/85001357-1f795200-b186-11ea-8075-d6ed5ddda5df.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
