### ISSUE TITLE
权限配置后，访问直接出错

### ISSUE THREAD

**Issue by tony2y** [zhangdaiscott/jeecg-boot#1359]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/38598582/85012371-80f4ed00-b195-11ea-8d0d-c2b39f24ff85.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tony2y** [comment]
异常代码：
2020-06-18 18:51:43.708 ERROR 17336 --- [nio-8080-exec-7] o.j.c.e.JeecgBootExceptionHandler        : Subject does not have permission [role:add]

org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [role:add]

**Comment by zhangdaiscott** [comment]
这有什么问题？

**Comment by zhangdaiscott** [comment]
菜单配置上对应的按钮权限，角色授权就可以了

**Comment by blackcatpolice** [comment]
![image](https://user-images.githubusercontent.com/4312114/223083857-d2e2bcfe-27d8-4258-b282-ec2ef893aef1.png)
创建菜单就报错 这种情况呢？ 3.4.0 升级上来的

**Comment by zhangdaiscott** [comment]
那搜索报错指令，暂时注释掉重启，授权后再放开注解

**Comment by blackcatpolice** [comment]
没找到，Java这个封装的太深了。

**Comment by blackcatpolice** [comment]
![image](https://user-images.githubusercontent.com/4312114/223099134-9acb2c5e-65ca-4601-add9-23378606ebaa.png)

怎么编辑这个权限

**Comment by woshinidi2gedie** [comment]
把controller(你自己生成的代码)里面的@RequiresPermissions 这个注解都注释掉  然后正常授权即可
