### ISSUE TITLE
固定Header时菜单tab栏同时固定

### ISSUE THREAD

**Issue by shuperry** [zhangdaiscott/jeecg-boot#136]
如果有选择固定Header时，菜单的tab栏可以同时固定，增加操作方便程度，或者再增加一个配置专门针对是否固定菜单tab栏

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/58632136-61372080-8317-11e9-9702-4bffb4399161.png)
