### ISSUE TITLE
一对多表单校验bug

### ISSUE THREAD

**Issue by liuyang94b** [zhangdaiscott/jeecg-boot#1360]
##### 版本号：
2.20

##### 问题描述：
一对多表单，当子表单有必输项时，点确定不会跳转到对应tab页。
详见官方演示系统中在线开发的T1表，6.18创建与本地测试一致

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51153073/85020786-6de91980-b1a3-11ea-8af9-b058414272e4.png)
![image](https://user-images.githubusercontent.com/51153073/85020859-8bb67e80-b1a3-11ea-852b-9ce1d953f5e1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liuyang94b** [comment]
目前测试看来，是1对1的子表单校验不过的时候，虽然会提示，但是不会跳转到对应的tab，也不会阻断提交

**Comment by zhangdaiscott** [comment]
此问题已经处理，下个版本发布

**Comment by liuyang94b** [comment]
可以把对应文件先提供给我一下吗？我今天也找到问题了，生成代码后调试，发现对于子表单是FROM的，只在getFormData中进行了校验，但校验结果只是弹窗提示了一下this.$emit("validateError",），并没有做拦截

**Comment by liuyang94b** [comment]
还有就是，当子表单既有1对1，又有1对多的时候，1对多的校验是可以检查到，但是tab跳转就有问题了，跳转是按tableKeys的序号去跳转，并不是按照总的refKeys去跳转

**Comment by zhangdaiscott** [comment]
生成代码的，可以自己手工改，我们改的是online功能测试的功能
