### ISSUE TITLE
标签下划线颜色不随主题改变. 这个问题和#1057一样,但是在color.less中添加了代码还是不行

### ISSUE THREAD

**Issue by xmlspyspring** [zhangdaiscott/jeecg-boot#1361]
##### 问题描述：标签下划线颜色不随主题改变. 这个问题和#1057一样,但是在color.less中添加了代码还是不行:
// 侧边导航栏首页颜色跟随主题变化
.ant-menu.ant-menu-root > .ant-menu-item:first-child.ant-menu-item-selected {
  & > a,
  & > a:hover {
    color: @primary-color;
  }
}

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1196481/85061967-482b3700-b1da-11ea-969a-41b3962e7276.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题处理了，下个版本发布

**Comment by xmlspyspring** [comment]
> 此问题处理了，下个版本发布

请问,怎么解决的,我需要在项目中修改
