### ISSUE TITLE
Online表单开发，建议增加时间控件

### ISSUE THREAD

**Issue by J-cafe** [zhangdaiscott/jeecg-boot#1362]
##### 版本号：
2.2.0

##### 问题描述：
目前表单开发只有date和datetime的控制，不支持 时间控件。此功能比较常用建议添加

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22951972/85094909-851b1c00-b222-11ea-8380-f78ba87fec3a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
