### ISSUE TITLE
Jeecg Boot 2.2 【dadf6a7】版本，生成代码后控件失效，变【文本框】

### ISSUE THREAD

**Issue by yayameteh** [zhangdaiscott/jeecg-boot#1363]
##### 版本号：
Jeecg Boot 2.2 【dadf6a7】版本

##### 问题描述：
单表测试所有控件，【功能测试】时都没问题，但生成代码后，【联动组件】【自定义树控件】
【开关】【MarkDown】【后台去自定义的生成编号】，这些控件都页面都显示错误，变【文本框】

##### 截图&代码：
【功能测试】时：
![5418dd61f7f06a1de2b2a5760fa6080](https://user-images.githubusercontent.com/33255775/85101245-8e14e900-b234-11ea-8e91-0dcfbc6de6d4.png)

【生成代码】后：
![7f5c2d80cefd2d2130705819366d3d7](https://user-images.githubusercontent.com/33255775/85101253-90774300-b234-11ea-9151-fab4253570ee.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前并不支持全部控件原样生成，不支持的，可以手工实现
