### ISSUE TITLE
页面滚动问题

### ISSUE THREAD

**Issue by weide86** [zhangdaiscott/jeecg-boot#1365]
##### 版本号：
当前版本

##### 问题描述：
当右侧内容显示区域内容多时，有滚动条的情况下，能不能只滚动内容区域，不要全局滚动

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26314804/85195075-1f9e5c80-b302-11ea-86d9-f1ef375b7727.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1350
