### ISSUE TITLE
popup功能待完善

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1367]
##### 版本号：
2.2

##### 问题描述：
1、popup如何支持多选择？看了对应的bug记录，没有找到JPopup.vue
2、popup实现多选择后，自动将数据填充到对应的表格，如：采购订单，选择了5条商品，则自动显示5行数据。不要显示在一行中。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tianchenglong323** [comment]
也碰到popup这问题了，问qq群也没人回答

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273913
![image](https://user-images.githubusercontent.com/3162115/85485199-d51b2980-b5fa-11ea-8c45-cfcaf8930a49.png)
