### ISSUE TITLE
前端切换标签不会保存原有状态及数据

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#1369]
##### 版本号：
V2.2.0

##### 问题描述：
前端切换标签不会保存原有状态及数据

##### 截图&代码：
比如在用户管理界面，输入了账号admin做查询，切换标签角色管理，再切回用户管理又会查询出所有用户

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
类似问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1571
