### ISSUE TITLE
excel 导入数据不能 保证数据唯一性？

### ISSUE THREAD

**Issue by LiuNet2** [zhangdaiscott/jeecg-boot#137]
以Demo给的“常见案列——一对多来”说，MYSQL表中主键为ID（UUID），不是订单号order_code，

那么通过excel 导入订单数据，同样的一条数据，就可以导入 多次，这个不符合逻辑吧

![image](https://user-images.githubusercontent.com/48855867/58294466-d4630300-7dfc-11e9-9477-2ac8ea194722.png)

**Comment by zhangdaiscott** [comment]
可以加校验，数据库也可以加唯一索引，默认例子没加校验逻辑

**Comment by LiuNet2** [comment]
> 可以加校验，数据库也可以加唯一索引，默认例子没加校验逻辑

这个“可以加校验”，是指在程序中对吧，需要重新写方法，还是原本就已经集成了功能，请告知下，谢谢

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/

AutoPOI EXCEL导出导入工具

**Comment by LiuNet2** [comment]
> http://jeecg-boot.mydoc.io/
> 
> AutoPOI EXCEL导出导入工具

应该是类似这样子吧

![image](https://user-images.githubusercontent.com/48855867/58363683-c2f02880-7eda-11e9-8b99-b235cf5e6a9f.png)

**Comment by softboy99** [comment]
@zhangdaiscott ，http://jeecg-boot.mydoc.io/这个地址访问不了了

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/autopoi/
