### ISSUE TITLE
AutoPoi 导出多Sheet表格报错

### ISSUE THREAD

**Issue by hay313955795** [zhangdaiscott/jeecg-boot#1371]
##### 版本号：
<dependency>
	<groupId>org.jeecgframework</groupId>
	<artifactId>autopoi-web</artifactId>
	<version>1.1.1</version>
	<exclusions>
		<exclusion>
		     <groupId>commons-codec</groupId>
		     <artifactId>commons-codec</artifactId>
		</exclusion>
	</exclusions>
</dependency>

##### 问题描述：
使用了系统自带的excel 多sheet导出功能.
导出报错.
2020-06-22 15:27:04.638 [http-nio-8080-exec-1] ERROR o.j.poi.excel.export.ExcelExportServer:193 - org.apache.poi.hssf.usermodel.HSSFRichTextString cannot be cast to org.apache.poi.xssf.usermodel.XSSFRichTextString
java.lang.ClassCastException: org.apache.poi.hssf.usermodel.HSSFRichTextString cannot be cast to org.apache.poi.xssf.usermodel.XSSFRichTextString
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28912140/85260866-f1558400-b49d-11ea-8c4d-65347e2992e2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
按上述代码不会报错，但是将ExcelExportUtil.exportExcel方法的第二个参数换成XSSF就会出现上述错误，会在下个版本修复
