### ISSUE TITLE
多个公司用的话，数据独立，相同的页面怎么分配权限

### ISSUE THREAD

**Issue by kevin-lr** [zhangdaiscott/jeecg-boot#1372]
##### 版本号：
2.20

##### 问题描述：
多个公司用的话，数据独立，相同的页面怎么分配权限

##### 截图&代码：

😿

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
通过数据权限控制，或者saas多租户模式
   https://github.com/zhangdaiscott/jeecg-boot/issues/166
