### ISSUE TITLE
在部门管理中修改机构名称后，用户管理列表的负责部门列数据未刷新

### ISSUE THREAD

**Issue by tenlisen** [zhangdaiscott/jeecg-boot#1375]
##### 版本号：
v2.2.0

##### 问题描述：
在部门管理中修改机构名称后，用户管理列表的负责部门列数据未及时刷新。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44961488/85296645-4c09d280-b4d4-11ea-88f6-0993900c4503.png)

![image](https://user-images.githubusercontent.com/44961488/85296766-75c2f980-b4d4-11ea-85ba-a160138df5f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是俩页面，目前做不到，表数据更新页面实时刷新，需要可以自己改造
