### ISSUE TITLE
求助+反馈：自定义菜单图标

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1376]
##### 版本号：
2.2.0

##### 问题描述：
**我想自定义菜单图标**，想既保留你们原本的图标，同时拓展iconfont.com里的图标
我在App.vue引入iconfont的文件，并且尝试在菜单配置图标框写 `no iconfont icon-gouwu`，最后图标代码是`class="anticon anticon-no iconfont icon-gouwu"`。这是不行的。。。
请官方说个自定义菜单图标的方法~谢谢啦

##### 截图&代码：
[你们文档里只有这个和图标相关的](http://doc.jeecg.com/1273896)，解决不了。并且相关的这个单词拼写也有前后错误
![image](https://user-images.githubusercontent.com/61787040/85404089-09f29680-b591-11ea-846f-3b7a84fa9254.png)
![image](https://user-images.githubusercontent.com/61787040/85404076-0232f200-b591-11ea-87e1-6fe86948ac9d.png)

**Comment by lvdandan16** [comment]
目前自定义菜单需要单独处理一下，直接使用自定义菜单图标显示时会自动加上.antion样式
可给自定义图标加个标识如：cus_icon-gouwu
修改文件src/components/menu/index.js  
参考修改方法：
renderIcon (icon) {
  if (icon === 'none' || icon === undefined) {
	return null
  }
  if(icon !== 'none' && icon !== undefined && icon.indexOf("cus_") !== -1){
	let className = "iconfont " + icon.substr(4);
	return <span style="margin-right:7px;"><i class={className}></i></span>;
  }else{
	const props = {}
    typeof (icon) === 'object' ? props.component = icon : props.type = icon
    return (
	  <Icon {... { props } }/>
    )
  }
}

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273896
