### ISSUE TITLE
建议：优化架构

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1377]
##### 版本号：
2.2.0

##### 问题描述：
- 目前的架构和配置，默认要在modules包下写代码。其实**不便于开发者隔离自己的业务代码**。
- jeecgboot本身的代码就比较多，如果在modules下单独开个包放业务代码，其实路径挺深的。但是如果要自己抽离的话，比如我把我的业务写在org.jeecg.mypack中，那么我要配置swagger、mybatisplus的mapper扫描包、DictAspect里的数据字典切面(这个问题排查了好久才找到。。)，这感觉不利于新手配置。
- 所以目前框架相对于开发者业务代码的耦合性比较强
###### 给出以下建议
- 如下图，控制层代码全部在jeecg-web模块下，并且建立多个子模块，每个模块有独立的springboot主配置类。**这个最大的好处其实是比较好做多端**，比如我想有多个后台+移动端+.. 每个端对应一个子模块
- 业务代码在jeecg-core模块下，这里有service、mapper
- 所有的bean在jeecg-bean下，这里有entity、dto、vo等
- 差不多就这样

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61787040/85404797-10354280-b592-11ea-9544-2ee68b16f39c.png)

**Comment by J-cafe** [comment]
你这样一样没有隔离业务代码。只是隔离的多端，但是没有隔离多业务。可以看下https://gitee.com/i_mxpio/jeecg-boot这种结构。多端只需要多个webapp模块。根据需要依赖对应的功能模块。

**Comment by zhangdaiscott** [comment]
下个版本会有较大的变化，会支持单体和微服务切换，会提供单独的API模块

**Comment by wushu037** [comment]
> 下个版本会有较大的变化，会支持单体和微服务切换，会提供单独的API模块

给力
