### ISSUE TITLE
GenericObjectPoolConfig异常与控制台样式

### ISSUE THREAD

**Issue by 253506088** [zhangdaiscott/jeecg-boot#1378]
##### 问题描述：
1：2.x版本都存在运行redis报错问题：Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.GenericObjectPoolConfig
2：idea运行时控制台全黑，不知道为什么你们要设置成这样，请不要入侵到控制台输出样式

##### 截图&代码：
![error](https://user-images.githubusercontent.com/16522843/85419278-775bf280-b5a4-11ea-8af4-1d34444a7d18.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 253506088** [comment]
为什么图片上传看不到。。。

**Comment by zhangdaiscott** [comment]
你的问题跟jeecgboot没关系吧

**Comment by tygithub1** [comment]
百度你这个问题1，说是少jar包，但是项目里有那个jar不知道是不是你自己删掉了，亦或是自己新增的jar和他冲突了，我本地测试是没有这个问题的；至于问题2，很抱歉，不知道为啥，也许是你脸黑吧
