### ISSUE TITLE
请教一下 j-popup控件源码放在哪里的   找了很久没找到

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1379]
##### 版本号：

2.2.0
##### 问题描述：
请教一下 j-popup控件源码放在哪里的   找了很久没找到， '@/components/jeecgbiz/JPopup'这路径下没发现有
 还有multi这属性不起作用，  弹出页设置不了单选；还有JPopup返回的值怎么让下拉框选中
##### 截图&代码：
![image](https://user-images.githubusercontent.com/8542824/85487995-27ab1480-b600-11ea-87c1-9f9856c58297.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
未开放
