### ISSUE TITLE
问题：命名错误

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1381]
##### 版本号：
2.2.0

##### 问题描述：
生成的代码，方法里写的也是下载，描述也是下载。
方法名不应该是叫downloadFile()吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61787040/85495398-0270d300-b60d-11ea-8522-97a8597083d7.png)
![image](https://user-images.githubusercontent.com/61787040/85495477-246a5580-b60d-11ea-8876-51f704aa93ec.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
问题已修复，将在下个版本升级
