### ISSUE TITLE
前端开发环境可以启动，打包生产环境报错

### ISSUE THREAD

**Issue by dmgame001** [zhangdaiscott/jeecg-boot#1385]
##### 版本号：
2.2.0

##### 问题描述：

前端构建打包生产环境错误：
##### 截图&代码：

![image](https://user-images.githubusercontent.com/6457986/85917384-50dfd500-b88c-11ea-879d-c7cb11352a7f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
百度一下
