### ISSUE TITLE
JS增强获取表单字段为undefined

### ISSUE THREAD

**Issue by anlem12** [zhangdaiscott/jeecg-boot#1388]
##### 版本号：
2.2 官方测试环境

##### 问题描述：

JS增强获取表单字段为undefined

show(){
  let formData = that.form.getFieldsValue()
  console.log(formData)
}

##### 截图&代码：

![image](https://user-images.githubusercontent.com/32320086/85946111-a1326200-b974-11ea-940f-e72326b54dd9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
show(){
	let formData = that.form.getFieldsValue()
	console.log('show result>>',formData)
}

浏览器控制台打印：
show result>> {name: undefined, age: undefined, bpm_status: undefined, sex: undefined}

是的无论是编辑页面还是新增页面，都不能在show里面获取到表单的数据，因为这个时候表单数据还未加载

**Comment by anlem12** [comment]
> show(){
> let formData = that.form.getFieldsValue()
> console.log('show result>>',formData)
> }
> 
> 浏览器控制台打印：
> show result>> {name: undefined, age: undefined, bpm_status: undefined, sex: undefined}
> 
> 是的无论是编辑页面还是新增页面，都不能在show里面获取到表单的数据，因为这个时候表单数据还未加载

那有其他办法在窗体打开时获取到表单数据
或者在窗体加载后根据表单数据控制按钮

**Comment by tygithub1** [comment]
当前版本不支持，下个版本发布loaded事件

**Comment by zhangdaiscott** [comment]
当前版本已经支持，可以更新代码
