### ISSUE TITLE
online 报表新增  SQL解析  一直提示超时

### ISSUE THREAD

**Issue by askyy1232008** [zhangdaiscott/jeecg-boot#1389]
##### 版本号：
2.2 官方测试环境

##### 问题描述：
online 报表新增  SQL解析  一直提示超时

##### 截图&代码：
![online](https://user-images.githubusercontent.com/17376985/85971460-be604280-b9ff-11ea-8d37-b549eadab37b.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by askyy1232008** [comment]
本地跑的程序，数据库是阿里云的，是否有影响？

**Comment by askyy1232008** [comment]
已解决

**Comment by CodeFly16** [comment]
请问是如何解决的，什么问题导致的

**Comment by askyy1232008** [comment]
需要在项目中，UI前端设置数据库信息，解析sql读取的是这个，而不是你自己配置的配置文件。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;铁头&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月12日(星期二) 晚上8:14
收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;&quot;askyy1232008&quot;<504861378@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] online 报表新增  SQL解析  一直提示超时 (#1389)

**Comment by CodeFly16** [comment]
> 需要在项目中，UI前端设置数据库信息，解析sql读取的是这个，而不是你自己配置的配置文件。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;铁头&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月12日(星期二) 晚上8:14 收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;; 抄送:&nbsp;&quot;askyy1232008&quot;<504861378@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] online 报表新增 SQL解析 一直提示超时 (#1389)

请教下 如何配置？
![image](https://user-images.githubusercontent.com/61872730/104315786-737ac800-5516-11eb-9c82-3891f07ce817.png)
