### ISSUE TITLE
tinymce富文本编辑器

### ISSUE THREAD

**Issue by ysyniko** [zhangdaiscott/jeecg-boot#1390]
##### 问题描述：
我把编辑器迁移到我的项目中，本地运行没事，但是部署后，出现找不到public里的tinymce文件找不到，路径出问题了，导致编辑tools全是not found请问这个路径是还要配置其他东西嘛

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48199952/85982335-39cdee00-ba18-11ea-9692-52e332d09916.png)
![image](https://user-images.githubusercontent.com/48199952/85982672-d1334100-ba18-11ea-8da4-14b3f01f40a8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
issue有类似问题，你搜下，依赖版本的问题
