### ISSUE TITLE
技术文档 是不是中病毒了，右下角有一个广告弹出框

### ISSUE THREAD

**Issue by dzhenjun** [zhangdaiscott/jeecg-boot#1393]
##### 版本号：
V2.0

##### 问题描述：
http://jeecg-boot.mydoc.io/
技术文档 是不是中病毒了，右下角有一个广告弹出框

##### 截图&代码：

![image](https://user-images.githubusercontent.com/38526314/86034561-69f3ac00-ba6d-11ea-9cf6-87e9f73996f1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看最新文档地址http://doc.jeecg.com/1273752

我们这没问题，应该是你的流程劫持了吧
