### ISSUE TITLE
JPopup

### ISSUE THREAD

**Issue by askyy1232008** [zhangdaiscott/jeecg-boot#1395]
##### 版本号：
2.2 测试环境

##### 问题描述：
@/components/jeecgbiz/JPopup   文件未找到，是否未开源？

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by askyy1232008** [comment]
补图
![image](https://user-images.githubusercontent.com/17376985/86110210-d9ae7900-baf7-11ea-8f6b-f6e34061221e.png)

**Comment by zhangdaiscott** [comment]
下个版本开放
