### ISSUE TITLE
表单设计器相关，本地运行项目没有看到表单设计器操作菜单

### ISSUE THREAD

**Issue by wesley5201314** [zhangdaiscott/jeecg-boot#1396]
##### 版本号：
2.2.0

##### 问题描述：

下载代码之后，按照文档说明http://doc.jeecg.com/1623904，没有看到表单设计器相关。本地运行项目没有办法使用表单设计器，看咱们的说明应该是没有开源，希望可以早点开源，这个还是比较实用的。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5622957/86109729-470dda00-baf7-11ea-84c1-45142fd6231e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
非开源功能

**Comment by yoko-murasame** [comment]
你好，请问下我用的商业版，使用表单设计器设计好Form，关联完online表单再导出本地代码，但是表单设计器中的表单未生效，这是不支持吗？
