### ISSUE TITLE
代码生成的代码前后端都放到了指定位置生成后配置好菜单不能访问

### ISSUE THREAD

**Issue by anlem12** [zhangdaiscott/jeecg-boot#1397]
##### 版本号：
2.2

##### 问题描述：

极简模式部署

代码生成的代码前后端都放到了指定位置，重新编译后，配置好菜单，点击菜单页面不能访问，没有任务错误，浏览器network记录也没有，如果配置了一个错误的链接到是能报404错误

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273950

**Comment by anlem12** [comment]
按照文档配置的菜单都没有问题后，检查下一级菜单和二级菜单配置的路径中是否有空格，我出现这个问题原因是一级菜单有空格。

在开发模式时用前后端分离进行测试，这样前端会有错误的console日志显示
