### ISSUE TITLE
在线表单不能设置隐藏字段？

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1398]
##### 版本号：

2.2
##### 问题描述：
在线表单不能设置隐藏字段？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/86200127-7c193b80-bb8e-11ea-8461-2781fca8f643.png)

**Comment by tianchenglong323** [comment]
大神  你发的图片显示不出来
