### ISSUE TITLE
表格合计功能bug

### ISSUE THREAD

**Issue by 15994028931** [zhangdaiscott/jeecg-boot#1399]
##### 问题描述：
表格合计功能，数据达到每页规定数据之后，合计就会不显示。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29727795/86212217-323e4e80-bbaa-11ea-87b8-96a251e72581.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是那个功能，生成代码，自己加的合计？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273896

**Comment by 15994028931** [comment]
常见案列下面的表格合计示例，应该是tableAddTotalRow()这个合计方法暂时不支持分页数据合计

**Comment by 15994028931** [comment]
> 这是那个功能，生成代码，自己加的合计？

常见案列下面的表格合计示例，应该是tableAddTotalRow（）这个合计方法暂时不支持分页数据合计

**Comment by 1298191366** [comment]
已修改，待新版本发布
