### ISSUE TITLE
sqlserver2008 数据库 保存实体报错

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#140]
使用代码生成器 ：单表GUI代码生成工具  

sql 查询数据
![image](https://user-images.githubusercontent.com/5210084/58299389-a76d1b00-7e11-11e9-81ae-ac1f8450a67a.png)

表dba开头ipo_sales

报错提示：如下图
![image](https://user-images.githubusercontent.com/5210084/58299278-47767480-7e11-11e9-9c5d-2be1abeb850f.png)

![image](https://user-images.githubusercontent.com/5210084/58299301-62e17f80-7e11-11e9-9a30-918717e0ca0d.png)
![image](https://user-images.githubusercontent.com/5210084/58299310-6d9c1480-7e11-11e9-96bb-cca5b271f001.png)

**Comment by zhangdaiscott** [comment]
你这个是自己写的功能，自己debug吧

**Comment by shaowen** [comment]
> 你这个是自己写的功能，自己debug吧

问题我找到了，改成dbo.ipo 就是可以保存了， 
我的表台头是dba开始的表  dba.ipo 
  问题是我后台数据库 直接插入到dba.ipo是可以的，說明我的账号是有插入权限的， 
谢谢   希望楼主测试下 dba權限，[jeecg_order_main]表 前面加dba就显示 对象名无效 无法保存
