### ISSUE TITLE
标题可以修改吗

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1400]
##### 版本号：
2.2.0

##### 问题描述：
浏览器标签显示的标题可以修改吗

##### 截图&代码：

![企业微信截图_20200701150145](https://user-images.githubusercontent.com/59555469/86213269-02904600-bbac-11ea-8f52-cdf2f4072799.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
全文搜索找到，即可改
