### ISSUE TITLE
导出数据报表问题

### ISSUE THREAD

**Issue by whitewolf1** [zhangdaiscott/jeecg-boot#1401]
##### 版本号：
Jeecg Boot2.2

##### 问题描述：
在online报表配置中生成的报表，导出的话，只能导出当前页面数据，这个有没有办法弄成导出全部的数据？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/4725497/86228267-c0bdca80-bbc0-11ea-93ef-b1664ac78a11.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此版本bug，已经修复下个版本发布
