### ISSUE TITLE
我想格式化一下代码

### ISSUE THREAD

**Issue by nanaaishangshu** [zhangdaiscott/jeecg-boot#1404]
##### 版本号：
最新版本

##### 问题描述：
代码格式化不统一  我想全部格式化一下。。。。这种可以提交吗 ？

##### 截图&代码：
格式化老代码并不友好，但是提早统一 有助于身心健康。。。。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
No
