### ISSUE TITLE
Online表单主题选择“ERP主题（一对多）”时时间字段不能弹出时间供选择

### ISSUE THREAD

**Issue by waterconstruction** [zhangdaiscott/jeecg-boot#1405]
##### 问题描述：
online表单生成表单时如果主题模板选“ERP主题（一对多）”，则字段设置为时间时时间无法弹出供选择

##### 截图&代码：

![ERP1](https://user-images.githubusercontent.com/39942489/86318664-206db180-bc65-11ea-9c39-88e20a2ec156.png)
![ERP2](https://user-images.githubusercontent.com/39942489/86318671-26639280-bc65-11ea-8406-2272ff38dc6b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此版本存在bug，已经修复，下个版本发布
