### ISSUE TITLE
本地搭建了jeecgboot环境后，用内外网穿透时，带宽只有4M的情况下，首页加载非常慢

### ISSUE THREAD

**Issue by zd551317** [zhangdaiscott/jeecg-boot#1406]
##### 问题描述：
你好，本地搭建了jeecgboot环境后，用内外网穿透时，带宽只有4M的情况下，首页加载非常慢，原因是app.js有34M，请问这个情况该如何解决

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40970878/86321215-1ea6ec80-bc6b-11ea-970b-e9ddb5d80a64.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zd551317** [comment]
带宽只有4M，不是最多只有4M ，上面写错了

**Comment by zhangdaiscott** [comment]
你打的包为什么那么大

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1343

**Comment by zd551317** [comment]
> [＃1343](https://github.com/zhangdaiscott/jeecg-boot/issues/1343)

对照操作了 还是不行 。。。。

**Comment by zd551317** [comment]
> 你打的包为什么那么大

源码clone下来后什么都没改，直接打包的

**Comment by dreamskr** [comment]
我的同样有这个问题，2.4.3时app.js的大小达49.7M，想问如何优化
