### ISSUE TITLE
局域网部署jeecg-boot

### ISSUE THREAD

**Issue by qqLife** [zhangdaiscott/jeecg-boot#1407]
##### 问题描述： 因数据涉密，只能在内网服务器部署后台服务，以及vue打包文件，nginx转发处理。
如何才能做到不使用外网，访问后台服务以及管理系统呢

##### 截图&代码：内网服务器没有联网情况截图
![image](https://user-images.githubusercontent.com/37296782/86324031-7b58d600-bc70-11ea-97e8-a15ddb6729b9.png)

本地访问这个网址登录界面有时候可以打开，但是点击登录按钮后，一直显示加载进不去主页
![image](https://user-images.githubusercontent.com/37296782/86324489-36816f00-bc71-11ea-9136-ee9d3b98a1a4.png)
其中的js文件访问不到。
下面为nginx转发截图：
![image](https://user-images.githubusercontent.com/37296782/86324588-59ac1e80-bc71-11ea-9857-eb37c2590bf9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
内网配置后台的host 域名，nginx转发即可
