### ISSUE TITLE
online报表功能测试显示查询错误，后台报请求被拦截

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#1408]
##### 版本号：
2.2.0

##### 问题描述：
怎么解决

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49867691/86326973-0dfb7400-bc75-11ea-8543-b1f0b9866b11.png)

![image](https://user-images.githubusercontent.com/49867691/86326825-d987b800-bc74-11ea-9bb9-a199adfc7296.png)

![image](https://user-images.githubusercontent.com/49867691/86326708-af35fa80-bc74-11ea-9357-aa0aa877c717.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是不是你这个请求报表配置权限了

**Comment by zhangdaiscott** [comment]
配置了菜单的话，得授权

**Comment by dskl1** [comment]
不是，不管是jpopup还是online表单开发，表的数据都显示查询失败，后台请求都被拦截了

JEECG开源社区 <notifications@github.com> 于 2020年7月2日周四 15:57写道：
