### ISSUE TITLE
使用externals减少build文件大小无效

### ISSUE THREAD

**Issue by liuz7899347** [zhangdaiscott/jeecg-boot#1409]
##### 版本号：
v2.1.4

##### 问题描述：
npm run build后打包文件过大，导致第一次加载时页面加载慢。
解决方案：
在vue.config.js中配置externals，实现打包时排除相关组件，在index.html中通过cdn外部引入，但打包时仍然把排除后的组件打包进去。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/67736503/86343361-70f80580-bc8b-11ea-8864-40fafe0fd7b3.png)
![image](https://user-images.githubusercontent.com/67736503/86343772-fc719680-bc8b-11ea-9f10-0c34957f9c3f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/86346887-22993580-bc90-11ea-9c21-3b8bdb785db4.png)

头三个应该好使，可以不加cdn看看，其他的排除名字怕匹配的不对

**Comment by liuz7899347** [comment]
我配置下面四个走cdn，在当前项目不起作用，打包后大小都在22M左右。
但是我其他非jeecg项目，配置后能减少8M左右的大小。
您能否帮忙看看，是否存在同样的问题，这个问题确实影响页面加载的速度，感谢
![image](https://user-images.githubusercontent.com/67736503/86441139-52067b80-bd3e-11ea-9dd8-af483d5da4c8.png)

**Comment by huanlirui** [comment]
如何处理的？求教？

**Comment by huanlirui** [comment]
> 我配置下面四个走cdn，在当前项目不起作用，打包后大小都在22M左右，和没有配置时打包的大小一样。 但是我其他非jeecg项目，配置后能减少8M左右的大小。 您能否帮忙看看，是否存在同样的问题，这个问题确实影响页面加载的速度，感谢 ![image](https://user-images.githubusercontent.com/67736503/86445904-c2fd6180-bd45-11ea-9e54-b9cdf052144e.png)
> 
> 我其他项目配置走cdn后打包大小是180kb： ![image](https://user-images.githubusercontent.com/67736503/86446146-1cfe2700-bd46-11ea-852b-4a286d4c399d.png)
> 
> 未配置走cdn打包的大小： ![image](https://user-images.githubusercontent.com/67736503/86446525-a57cc780-bd46-11ea-956b-f954e2dfe299.png)

解决了么？同样有这个问题。
