### ISSUE TITLE
SQL注入问题

### ISSUE THREAD

**Issue by zhouyilong** [zhangdaiscott/jeecg-boot#141]
/sys/dict/getDictItems/{dictCode}  其中 dictCode 举例：sys_user,realname,id，没有考虑SQL注入的问题，可以直接注入SQL

**Comment by zhang0001** [comment]
列表的排序中 column 参数也可SQL注入，现在是被 Druid wall 拦截了

**Comment by zhangdaiscott** [comment]
已经修改，下个版本发布
