### ISSUE TITLE
online表单如何指定字段进行排序 或是否支持多个字段进行排序

### ISSUE THREAD

**Issue by yuwanlong8808680** [zhangdaiscott/jeecg-boot#1411]
##### 版本号：
jeecgboot 2.2.0

##### 问题描述：
使用online表单在线生成表单后，数据用excl批量导入，导致分页查询是数据显示重复bug,分析后发现排序是默认createTime字段，但批量导入的数据导致createTime字段数据都一样，所有排序出现问题

##### 截图&代码：
![1593739296(1)](https://user-images.githubusercontent.com/43407642/86422320-67b07c80-bd0f-11ea-805c-8276ef862fad.png)
![1593739357(1)](https://user-images.githubusercontent.com/43407642/86422323-6a12d680-bd0f-11ea-9a3c-248d3069c57e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
经测试无问题，如有问题请再次回复

**Comment by 1298191366** [comment]
排序只需要在online菜单配置，如下图
![image](https://user-images.githubusercontent.com/30997828/88924758-43ac7080-d2a6-11ea-9b78-df29a8b2ba41.png)

**Comment by zhangdaiscott** [comment]
已经解决，下个版本处理
