### ISSUE TITLE
Bug：如果请求参数有request，@AutoLog自动日志 会报异常

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1413]
##### 版本号：
2.2.0

##### 问题描述：
如果请求参数有request，@AutoLog自动日志 会报异常
附解决办法

##### 截图&代码：

![image](https://user-images.githubusercontent.com/61787040/86454904-81bf7e80-bd52-11ea-9fc6-23163bbf7145.png)

![image](https://user-images.githubusercontent.com/61787040/86456515-c21ffc00-bd54-11ea-9041-3417b5f2a358.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待测试

**Comment by 1298191366** [comment]
新版本已修改
