### ISSUE TITLE
自动登陆不起作用

### ISSUE THREAD

**Issue by tyhg001** [zhangdaiscott/jeecg-boot#1415]
##### 问题描述：
1、自动登陆勾选没任何作用；
2、网页开在那一段时间，登陆过期，再点击时不出任何提示，也没有反应，要登出后再登陆才有作用；
      应该有提示登陆已过期的提示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19584941/86504688-365aae00-bdee-11ea-8fd2-733d8e81b261.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tanpenggood** [comment]
请提供一个详细的复现步骤。

**Comment by Ajaxlover** [comment]
问题:不论勾不勾选自动登录,始终会自动登录
复现步骤:
1.打开登录页,勾选[自动登录],登录后,直接关闭,再访问登录页会自动登录
2.打开登录页,不勾选[自动登录],登录后,直接关闭,再访问登录页依然会自动登录

**Comment by tanpenggood** [comment]
实际上，你的复现步骤中描述的问题和自动登录没有任何关系。

如果你希望每一次关闭浏览器后都需要重新登录，可以将`token`转存储到`SessionStorage`中即可满足。
