### ISSUE TITLE
单据编号代码生成后，没有了

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1417]
##### 版本号：

2.2.0
##### 问题描述：

1、单据编号生成后，没有显示出来
2、求，写一个代码生成后的下推生成的功能
3、求，写一个子表表格行内计算功能，如：单价*数量=总价，以及表格中列合计的功能
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持生成，代码生成后，可以手工加上编码规则代码
http://doc.jeecg.com/1398551
