### ISSUE TITLE
online表单配置好以后后再次编辑保存无效了？也不能再次同步数据库？

### ISSUE THREAD

**Issue by zd551317** [zhangdaiscott/jeecg-boot#1418]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/40970878/86524373-8a2bcc80-beac-11ea-91b2-e212251307c7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述太简单
