### ISSUE TITLE
请问J-editor 在Tabs中缓存问题

### ISSUE THREAD

**Issue by mingyangsama** [zhangdaiscott/jeecg-boot#1419]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32919379/86561164-9e49f980-bf92-11ea-870b-3544c0413d19.png)
![image](https://user-images.githubusercontent.com/32919379/86561181-aa35bb80-bf92-11ea-8c9e-74e586215066.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前没这需求，可以自己研究一下
