### ISSUE TITLE
online表单下拉选择，校验字段，字典Table 写上where条件后，在线测试没问题，生成代码后，出现sql注入问题

### ISSUE THREAD

**Issue by xYang98** [zhangdaiscott/jeecg-boot#1423]
##### 问题描述：
online表单下拉选择，校验字段，
字典Table ->写上where条件后，例如：sys_user where sex = '1'
在线测试没问题，生成代码后，出现sql注入问题，换成#{sex}，不知道在哪里传这个sex
(我图片中是另外一个sql)

##### 截图&代码：
![1](https://user-images.githubusercontent.com/52552236/86693618-66e45700-c03d-11ea-90c9-1d3d9c7d0f99.png)
![2](https://user-images.githubusercontent.com/52552236/86693661-706dbf00-c03d-11ea-9546-ae34e4f85924.png)
![3](https://user-images.githubusercontent.com/52552236/86693678-7368af80-c03d-11ea-83b6-8ccc40bea6dc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待测试

**Comment by 1298191366** [comment]
新版本无查询条件

**Comment by 1298191366** [comment]
@xYang98  新版本无查询条件

**Comment by 1298191366** [comment]
如果像代参查询，用这种格式
![image](https://user-images.githubusercontent.com/30997828/87635470-b3344300-c771-11ea-9494-2be0e3d5f970.png)

**Comment by 1298191366** [comment]
如果想代参查询，用这种格式
![image](https://user-images.githubusercontent.com/30997828/87635596-eaa2ef80-c771-11ea-96fc-b2ae45fd819a.png)
