### ISSUE TITLE
jeecg boot 2.2.0 online开发href跳转问题

### ISSUE THREAD

**Issue by huyaru** [zhangdaiscott/jeecg-boot#1424]
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/39981456/86723888-e46a9000-c05a-11ea-8133-0d4ceb3630fc.png)
![图片](https://user-images.githubusercontent.com/39981456/86723982-fb10e700-c05a-11ea-850f-bbe433f52863.png)
![图片](https://user-images.githubusercontent.com/39981456/86724131-1a0f7900-c05b-11ea-8212-c0f2172e97f4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1463259

**Comment by huyaru** [comment]
不好意思，这个并没有解决为提出来的问题，是想通过点击特定字段，自动跳转到这个字段对应的其他表单的详情页
