### ISSUE TITLE
autopoi 1.1 导出列表数据时, 不支持合并后的单元格.提前结束列的循环了.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1426]
##### 版本号：
2.2.0

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/20039800/86736724-54324800-c066-11ea-85a6-5d580ca411f1.png)
![图片](https://user-images.githubusercontent.com/20039800/86736775-601e0a00-c066-11ea-863c-0be868316818.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
请贴出自己的代码和模板

**Comment by 1298191366** [comment]
不支持合并单元格，必须一个一个的写

**Comment by lsqGitHub716** [comment]
已修改

**Comment by zhangdaiscott** [comment]
下个版本发布
