### ISSUE TITLE
autopoi 1.1.2 三元表达式,数字对比的bug

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1427]
##### 版本号：
2.2.0

##### 问题描述：

三元表达式中, 这个表达式,右边表达表, 得不到0数字,得到是空字符串: t.isZero == fn:(0;#)
表达式改为t.isTts == 0的话,右边的0会被当成字符串处理,表达式永不为真;
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
什么功能
