### ISSUE TITLE
autopoi1.1.2 只有一行数据时,会导致崩溃.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1428]
##### 版本号：
2.2.0 

##### 问题描述：
没有数据或有一行以上数据,没有问题.

##### 截图&代码：
当只有一行数据时,会崩溃

![图片](https://user-images.githubusercontent.com/20039800/86769536-e0059d80-c081-11ea-817a-e6760ed7b51a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by GordonHuangYong** [comment]
使用的是$fe: 下移插入的

**Comment by tygithub1** [comment]
sadsad

**Comment by tygithub1** [comment]
什么功能，怎么操作
