### ISSUE TITLE
一对多表单中父表单子表单如何隐藏字段

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1429]
##### 版本号：
2.2

##### 问题描述：

 默认风格的一对多表单中父表单子表单如何隐藏字段，就是类似hidden，没有的话是不是下个版本加一下，这是常用功能吧

##### 截图&代码：

无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
online功能测试还是生成的代码？

目前两个场景都支持
