### ISSUE TITLE
如何缓存一个子菜单的数据，从其他子菜单切换到这个子菜单时，这个子菜单保留原来的状态

### ISSUE THREAD

**Issue by MyAcooL** [zhangdaiscott/jeecg-boot#1430]
##### 问题描述：

如何缓存一个子菜单的数据，从其他子菜单切换到这个子菜单时，这个子菜单保留原来的状态
##### 截图&代码：
如何缓存一个子菜单的数据，从其他子菜单切换到这个子菜单时，这个子菜单保留原来的状态

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/87010458-29c4c400-c1f9-11ea-8718-54c379d9c0eb.png)

菜单配置，是否缓存改成是
