### ISSUE TITLE
JSlider 滑块移动端无法滑动

### ISSUE THREAD

**Issue by gqf1995** [zhangdaiscott/jeecg-boot#1432]
##### 版本号：
2.2.0

##### 问题描述：
在移动端浏览器中，滑块无法滑动

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20791771/86983510-a1293200-c1be-11ea-9e31-2047ea00b1dd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版验证码不是滑块
