### ISSUE TITLE
自定义组件，建议支持多条件查询。

### ISSUE THREAD

**Issue by zhaozhixin001** [zhangdaiscott/jeecg-boot#1433]
##### 版本号：
jeecg-boot 2.2.0

##### 问题描述：
现在看到自定义用户组件、部门组建等都是调用的 JSelectBizComponentModal.vue 文件，但是发现查询条件只有单条件查询，建议增加自定义多条件查询的功能。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61789674/86986677-cae65700-c1c6-11ea-8b67-80a5b6aa69a3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by sjlei** [comment]
现已增加可配置形式的多条件查询功能

![image](https://user-images.githubusercontent.com/34293221/89019817-7ca11f80-d350-11ea-85bd-90cac6a0c313.png)

## 配置方式

### 用户组件默认条件
![image](https://user-images.githubusercontent.com/34293221/89019942-b2de9f00-d350-11ea-9c47-f52e5909f722.png)

### 使用时自定义条件：
![image](https://user-images.githubusercontent.com/34293221/89019849-8b87d200-d350-11ea-8377-ffaab7743d41.png)
![image](https://user-images.githubusercontent.com/34293221/89019885-9c384800-d350-11ea-884e-c640d00d38f5.png)

**Comment by sjlei** [comment]
下版本发布。

**Comment by qq734504513** [comment]
请问，这个功能2.2.1能用了吗
