### ISSUE TITLE
表单自动生成不会生成field_href字段

### ISSUE THREAD

**Issue by whitewolf1** [zhangdaiscott/jeecg-boot#1435]
##### 版本号：
v2.2.0

##### 问题描述：
表单自动生成不会生成field_href字段，即生成的代码没有超链接，但功能测试中又有超链接

##### 截图&代码：
![11](https://user-images.githubusercontent.com/4725497/86993712-47813180-c1d7-11ea-86e0-923e524c404f.png)
测试页

![22](https://user-images.githubusercontent.com/4725497/86993717-4b14b880-c1d7-11ea-8cd6-b1662fc49dfb.png)
导出代码后的页面，没有超链接

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的，这个需要生成后，手工加
