### ISSUE TITLE
radis缓存未更新   导致 修改主表，子表关联数据未更新

### ISSUE THREAD

**Issue by wtongshuai** [zhangdaiscott/jeecg-boot#1436]
##### 问题描述：
radis缓存未更新   导致 修改主表，子表关联数据未更新
例如：修改部门名称    用户负责部门未更新
##### 截图&代码：
![1594274384(1)](https://user-images.githubusercontent.com/50900992/87002773-e8c6b280-c1ec-11ea-88dd-cf7e523f3da6.jpg)
![1594274557(1)](https://user-images.githubusercontent.com/50900992/87002775-e9f7df80-c1ec-11ea-91fb-59608f7815a5.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
@wtongshuai 新版本已修改
