### ISSUE TITLE
online配置的 表单是显示两行的，但生成代码 却是一直是一行

### ISSUE THREAD

**Issue by guoglee** [zhangdaiscott/jeecg-boot#1437]
##### 版本号：
jeecg-boot2020-7-3下载的版本

##### 问题描述：

online配置的 FROM表单 功能测试是显示两行的，但生成代码 却是一直是一行，JS增强在online测试也是可以用，到生成代码后实际也是用不了，报错了
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by guoglee** [comment]
提交不了图片 报错

**Comment by zhangdaiscott** [comment]
下个版本支持

**Comment by guoglee** [comment]
下个版本才支持，现在的不支持是吗
