### ISSUE TITLE
请教三级联动问题

### ISSUE THREAD

**Issue by missKomorebi** [zhangdaiscott/jeecg-boot#1438]
##### 版本号：

v2.2
##### 问题描述：
已知dataSource 数据，初始化数据，如何设置每一行，二级和三级options

场景：编辑的时候，只需要修改区县的，如何设置options，不用从一级重新选

##### 截图&代码：

![{J6@JVNOOBD`Q}YVQOUY7D1](https://user-images.githubusercontent.com/49051538/87075952-ad130380-c253-11ea-9cf0-fb8d48c51b87.png)

![U8KAAGTWRJQNC`1TR{34( N](https://user-images.githubusercontent.com/49051538/87075881-979dd980-c253-11ea-9a34-6652271463f6.png)
![NE}4(5@_{XA_@POZW}J0PY](https://user-images.githubusercontent.com/49051538/87075891-9a98ca00-c253-11ea-8d40-4830603b4ba7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个功能？ 自己写的还是online

**Comment by missKomorebi** [comment]
@zhangdaiscott 
您好，这个是2.2li里的一个示例，我不知道如何在jeditableTable中处理联动回显的问题。
![8DUYHRAQJ5V$_V(ZV%7RAUY](https://user-images.githubusercontent.com/49051538/87225407-4b6fa800-c3bf-11ea-8331-2fb3c38ca62e.png)

**Comment by missKomorebi** [comment]
@zhangdaiscott 
大拿，我真不知道咋弄，能不能指点一下，急哭。。。
