### ISSUE TITLE
常见需求：表格的字段隐藏列，排序，拖拽

### ISSUE THREAD

**Issue by aleiliuwei** [zhangdaiscott/jeecg-boot#144]
用户对于表格的操作。不同的人关注的字段不同，用户一般希望自己关注的字段在前面显示，表字段很多的情况下，不同的人想隐藏自己不想看的字段，按照某个列进行排序，这些在jeecg的easyui版本，这些功能是有的，对于vue这个不太熟悉怎么加

**Comment by zhangdaiscott** [comment]
已经实现列隐藏，下个版本发布；
排序本身table控件就支持；
拖拽暂时不做，有点难度，也可以实现，后期再考虑。。
