### ISSUE TITLE
online表单开发，添加了多于的字段。想删除，怎么删？

### ISSUE THREAD

**Issue by acupoftea** [zhangdaiscott/jeecg-boot#1440]
##### 版本号：
2.2.0

##### 问题描述：
online表单开发，添加了多于的字段。想删除，怎么删？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22152642/87238903-2587e900-c43b-11ea-99d1-2986c9e3f90a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
选中删
