### ISSUE TITLE
内嵌子表单显示字段越多，多选框及其序号宽度也会增加

### ISSUE THREAD

**Issue by pljay** [zhangdaiscott/jeecg-boot#1442]
##### 问题描述：
在线表单开发 内嵌子表单  随着子表单字段增多 多选框及其序号宽度也会增加

##### 截图&代码：
![微信图片_20200713103654](https://user-images.githubusercontent.com/35439240/87265244-e5853c80-c4f4-11ea-9d21-87a3e7b32698.png)
![微信图片_20200713103649](https://user-images.githubusercontent.com/35439240/87265245-e61dd300-c4f4-11ea-9a9a-656ffc009f47.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修复
