### ISSUE TITLE
导出excel,支持动态列吗?

### ISSUE THREAD

**Issue by lihanxie** [zhangdaiscott/jeecg-boot#1443]
##### 版本号：
2.2.1

##### 问题描述：
以前用easypoi 的时候，自己有手动改造支持动态列， 现在新版的autpoi 有没有实现这个功能，如果有怎么使用，如果没有预计什么时候会有？

##### 截图&代码：
比如这样的动态excel
a.
列1 （固定） | 列2（固定） 列3 （固定）| 列4（动态） | 列5（动态）....
b.
列1 （固定） | 列2（固定） 列3 （固定）| 列4（动态） | 列5（动态）| 列6（固定）

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1634498

**Comment by lihanxie** [comment]
有没有根据模版导出的
