### ISSUE TITLE
聚合路由错误

### ISSUE THREAD

**Issue by Sean-214** [zhangdaiscott/jeecg-boot#1444]
##### 版本号：
2.2

##### 问题描述：
聚合路由配置后子菜单路由不显示，子菜单之间的跳转通过页面上的路由链接进行跳转。
既然子菜单在聚合路由页面控制跳转，就不应该在Tab栏显示子菜单的Tab了。
如官网在线演示的个人设置页，左侧“基本设置”，“安全设置”等 `<router-link>` 控制右侧 `<router-view>` 显示的组件，如果再在Tab中显示页签就感觉打开了好几个聚合路由页面。

##### 截图&代码：
官网的在线演示：http://boot.jeecg.com/account/settings/BaseSetting

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
你想表达什么

**Comment by Sean-214** [comment]
@tygithub1 我想表达“既然子菜单在聚合路由页面控制跳转，就不应该在Tab栏显示子菜单的Tab了。”
原因在最后一段写了，再举个例子，就比如chrome浏览器是多标签的，但是如果每打开一个页面除了新增一个标签外，还多打开一个窗口，这样是不是不合理？类似这个聚合路由，明明是在页面中切换Tabs，但是在框架的Tabs中也新增了一个标签页。

**Comment by 1298191366** [comment]
已修改，待新版本发布
