### ISSUE TITLE
固定侧边菜单的时候有些问题

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1445]
##### 问题描述：
开源版好像有点问题，固定侧边菜单的时候，会有部分被遮盖，官网演示地址的好像没这问题。
另外能不能增加个固定顶部的TAB标签栏的选项，不要让它滚动。

##### 截图&代码：
![TIM图片20200714102421](https://user-images.githubusercontent.com/54636793/87375190-b2f34680-c5bd-11ea-93f7-89fc1878b65a.png)
![A2 49VBDOBAKVIO0_$E%IKG](https://user-images.githubusercontent.com/54636793/87375227-b8509100-c5bd-11ea-8c17-0d1a6a2abc4b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
固定头部的配置有
![image](https://user-images.githubusercontent.com/3162115/92378684-c7286f80-f138-11ea-8873-b49db1d63a60.png)

**Comment by zhangdaiscott** [comment]
另外你的问题未重现

**Comment by lijinlang** [comment]
> 另外你的问题未重现

开源版本点下面的固定侧边菜单就存在问题，会把右边部分遮盖，官方演示的地址没问题，是不是少什么文件了

**Comment by Nibbbbbbbb** [comment]
![image](https://user-images.githubusercontent.com/21167262/99136023-dc041080-265d-11eb-80dd-fe28850e22ad.png)

这个问题是偶发的，但是频率挺高的，开发时一个月会遇到几次，强制刷新页面无用，要清缓存或者把浏览器的宽度缩小再放大，它才适配回来   

问题版本：重构前的2.2.1  或者重构后的新版本，都存在这个问题
