### ISSUE TITLE
本地运行没问题，部署Docker，启动失败：Could not resolve placeholder 'jeecg.shiro.excludeUrls' in value "${jeecg.shiro.excludeUrls}"

### ISSUE THREAD

**Issue by Jaydonli2020** [zhangdaiscott/jeecg-boot#1447]
##### 截图&代码：
![微信图片_20200714105755](https://user-images.githubusercontent.com/67999483/87378711-06b35f00-c5c1-11ea-877d-860586f37597.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个没遇到过，你是jeecgcloud 还是jeecgboot

**Comment by Jaydonli2020** [comment]
你好！我是用的jeecgboot

Best regards,
Jaydon Li

在 2020年7月14日，上午11:05，JEECG开源社区 <notifications@github.com> 写道：

﻿ **EXTERNAL MAIL**


这个没遇到过，你是jeecgcloud 还是jeecgboot

**Comment by zhangdaiscott** [comment]
看看是不是配置文件 没打包进去

**Comment by Jaydonli2020** [comment]
[mvn clean package.txt](https://github.com/zhangdaiscott/jeecg-boot/files/4923319/mvn.clean.package.txt)
应该都打包进去了的。
