### ISSUE TITLE
JTreeTable 能不能和 JEditableTable 结合？

### ISSUE THREAD

**Issue by 224148793** [zhangdaiscott/jeecg-boot#1448]
##### 版本号：
2.2.1

##### 问题描述：
目前JEditableTable 不支持tree，JTreeTable 又不支持编辑。能不能两个结合。做一个支持编辑和拖拽的树列表控件？谢谢。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持，正在研发新的行编辑组件
