### ISSUE TITLE
隶属多个部门，登录页面输入正确，点击登录后，弹出部门选择，不选，直接刷新网页，直接进入dashboard了

### ISSUE THREAD

**Issue by azunia** [zhangdaiscott/jeecg-boot#1449]
##### 版本号：
2.2.1

##### 问题描述：
隶属多个部门，登录页面输入正确，点击登录后，弹出部门选择，不选，直接刷新网页，直接进入dashboard了，

感觉应该隶属多个部门，需要选择后，才能进去。

##### 截图&代码：
departConfirm(res){
        if(res.success){
          let multi_depart = res.result.multi_depart
          //0:无部门 1:一个部门 2:多个部门
          if(multi_depart==0){
            this.loginSuccess()
            this.$notification.warn({
              message: '提示',
              description: `您尚未归属部门,请确认账号信息`,
              duration:3
            });
          }else if(multi_depart==2){
            this.departVisible=true
            this.currentUsername=this.form.getFieldValue("username")
            this.departList = res.result.departs
          }else {
            this.loginSuccess()
          }
        }else{          
          this.requestFailed(res)
          this.Logout();
        }
      },

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，带新版本发布
