### ISSUE TITLE
登陆shiro报错

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#145]
![image](https://user-images.githubusercontent.com/27263086/58393509-9c182a80-8071-11e9-9628-fa2f678bf911.png)
上网查好像是说shiro 记住密码配置 编码问题，但是没有解决。

**Comment by zhangdaiscott** [comment]
怎么重现

**Comment by ileadall42** [comment]
这个真的是个问题哈哈，我发现大家都没这个问题，我再捣鼓捣鼓看看。

**Comment by ileadall42** [comment]
本地cookie问题，清除一下就可以了。

**Comment by ileadall42** [comment]
@clo

**Comment by ileadall42** [comment]
@zhangdaiscott https://my.oschina.net/zhike/blog/838702 这个错误网上很多人都有。不知道是不是可以相应配置来避免.
