### ISSUE TITLE
Bug:2.2.1版本 Online排序功能失效

### ISSUE THREAD

**Issue by 5211** [zhangdaiscott/jeecg-boot#1450]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/25277200/87394589-8d2c6880-c5e2-11ea-8f4b-594648ea0ffa.png)
![image](https://user-images.githubusercontent.com/25277200/87394633-9ddcde80-c5e2-11ea-803c-10d5924a0bf6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
演示系统无问题啊
boot.jeecg.com

**Comment by 5211** [comment]
对啊 就是从git上 新下载的啊 你看哔哩哔哩 每天10分钟也有这个问题呢

**Comment by 5211** [comment]
真的不管用，估计代码没传上来，我让我朋友也试了 不行 代码就是从github上重新下载的一份




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 上午9:56
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "Mr.Lee?? "<1014646373@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] Bug:2.2.1版本 Online排序功能失效 (#1450)





 
演示系统无问题啊
 boot.jeecg.com

**Comment by zhangdaiscott** [comment]
升级 hibernate-re为 2.2.11版本

org.hibernate
hibernate-re
2.2.11
