### ISSUE TITLE
列表部门code怎么换成显示部门名称中文

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1452]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/87405803-7f7edf00-c5f2-11ea-9a8e-7e849add9cba.png)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273944
参考

4.字典表翻译用法

@Dict(dicCode = "id",dictTable="sys_user",dicText="realname")

**Comment by jwcjf** [comment]
我用的online表单设计，请问这个怎么设置呢

**Comment by jwcjf** [comment]
还有怎么设置部门的查询，我这样设置查询不到
![image](https://user-images.githubusercontent.com/18321599/87501209-1dc18200-c691-11ea-8da8-e9b63596f7e3.png)
