### ISSUE TITLE
二级部门权限管理拿到登陆用户的所有部门权限

### ISSUE THREAD

**Issue by vaues** [zhangdaiscott/jeecg-boot#1453]
##### 问题描述：
权限管理模块，二级部门管理权限，我在角色管理页面没有给当前登陆用户的角色授权任何菜单的访问权限，其他授权步骤按照官网的步骤给二级部门管理授权，我把这个人授权给两个部门，登陆之后的菜单中这个人同时拿到了这两个部门的所有权限，包括右上角的切换部门之后的菜单依然是两个部门的权限。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么意思？ 分配了部门不就应该拥有部门的权限吗

**Comment by vaues** [comment]
<img width="1205" alt="1" src="https://user-images.githubusercontent.com/13826427/87496339-eef1de80-c685-11ea-9fb9-71b5f18be8ae.png">
<img width="1265" alt="2" src="https://user-images.githubusercontent.com/13826427/87496342-f0bba200-c685-11ea-8a35-81f6d6c5e51c.png">
<img width="346" alt="3" src="https://user-images.githubusercontent.com/13826427/87496349-f31dfc00-c685-11ea-96a7-d1226d2f24a6.png">
<img width="560" alt="4" src="https://user-images.githubusercontent.com/13826427/87496431-23659a80-c686-11ea-8ff6-e6db0267fca6.png">

上面是我给这个人的授权，授权之后左侧菜单这个人所有权限都展示出来了，所以切换部门没有什么用。
登陆的哪个部门就展示哪个权限，我自己修改权限把，你门这个是比较宽泛的，感谢回复。

**Comment by 1298191366** [comment]
如需修改可以修改下面的sql
![image](https://user-images.githubusercontent.com/30997828/88661516-33ac5980-d10b-11ea-87d8-177b9ced8ba8.png)
![image](https://user-images.githubusercontent.com/30997828/88661533-3c049480-d10b-11ea-9c8e-9d3cefe6dea5.png)
![image](https://user-images.githubusercontent.com/30997828/88661544-41fa7580-d10b-11ea-8c24-703305d045e6.png)
