### ISSUE TITLE
2.2.1版本bug，默认主题父子表生成的代码，如果先点击编辑，后点击新增，新增页面明细上会有之前编辑页面上的数据

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1454]
##### 版本号：

2.2.1
##### 问题描述：
2.2.1版本bug，默认主题父子表生成的代码，如果先点击编辑，后点击新增，新增页面明细上会有之前编辑页面上的数据

##### 截图&代码：

![image](https://user-images.githubusercontent.com/8542824/87493956-79cfda80-c680-11ea-94e2-7056b8b19a46.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tianchenglong323** [comment]
看着应该是JEditableTable关闭时没有清空表格

**Comment by zhangdaiscott** [comment]
已经修复了，请更新代码
