### ISSUE TITLE
在线表单配置的页面如何路由缓存？

### ISSUE THREAD

**Issue by rjliulei** [zhangdaiscott/jeecg-boot#1455]
##### 版本号：
前端，2.2.0

##### 问题描述：
如题，我在菜单里配置了缓存路由，没有效果。源码没看明白。。大神指教一下

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rjliulei** [comment]
![image](https://user-images.githubusercontent.com/6119104/87498236-e26f8500-c689-11ea-8098-30148a50bd24.png)
TabLayout里的图示位置meta.keepAlive始终是false，即使我强制改为true，也没有效果

**Comment by zhangdaiscott** [comment]
online功能测试的地址吗

**Comment by rjliulei** [comment]
是的

**Comment by zhangdaiscott** [comment]
online的页面是非路由地址，采用的都是一个统一的组件，目前无法实现路由缓存功能
