### ISSUE TITLE
online表单开发 联动组件怎么设置查询 

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1456]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18321599/87498807-48a8d780-c68b-11ea-840b-1329b5b9f64e.png)

![image](https://user-images.githubusercontent.com/18321599/87498827-56f6f380-c68b-11ea-86e9-83c76af17375.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jwcjf** [comment]
一级行业和二级行业为联动级联关系

**Comment by jwcjf** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
目前好像不支持
