### ISSUE TITLE
doc。html访问问题

### ISSUE THREAD

**Issue by heckerstone** [zhangdaiscott/jeecg-boot#1457]
##### 问题描述：

doc.html访问提示 Whitelabel Error Page，shiro已放行，怎么解决？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没明白，doc.html框架不是已经设置好了吗

**Comment by heckerstone** [comment]
访问不了啊

**Comment by zhangdaiscott** [comment]
这个要设置为true， false是关闭swagger 文档
![image](https://user-images.githubusercontent.com/3162115/87847524-a0557600-c90b-11ea-9482-40838c466e72.png)

**Comment by heckerstone** [comment]
哦  谢谢
