### ISSUE TITLE
2.2.1bugFormTypes.sel_search不能选中

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1458]
##### 版本号：
2.2.1

##### 问题描述：
默认主题生成的父子表，popup带出字段如果是 FormTypes.select能选中，而FormTypes.sel_search不能选中

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，确认

**Comment by 1298191366** [comment]
{
              title: 'popup弹窗',
              key: 'popupok',
              type: FormTypes.popup,
              popupCode:"sys_msg",
              destFields:"popupok,popback",
              orgFields:"username,sex",
              width:"200px",
              placeholder: '请输入${title}',
              defaultValue: '',
            },
            {
              title: '回调',
              key: 'popback',
              type: FormTypes.sel_search,
              dictCode:"sex",
              width:"200px",
              placeholder: '请输入${title}',
              defaultValue: '',
            },
![image](https://user-images.githubusercontent.com/30997828/88377552-fe81cd80-cdd1-11ea-9a96-f80d90ae03d4.png)
