### ISSUE TITLE
启动警告问题，麻烦老师指导一下

### ISSUE THREAD

**Issue by Fillovida** [zhangdaiscott/jeecg-boot#1459]
##### 版本号：
2.2.0

##### 问题描述：
开发时启动项目（配置文件使用的默认的application-dev.xml），控制台每秒打印一次警告，看起来像是定时任务的，但目前开发没有涉及到定时任务的地方。
老师能指导下排查或者解决方法么？

##### 截图&代码：
![微信截图_20200715140908](https://user-images.githubusercontent.com/50174339/87510112-89ade580-c6a5-11ea-92f1-c8d3412ea3a0.png)
![微信截图_20200715140923](https://user-images.githubusercontent.com/50174339/87510115-8d416c80-c6a5-11ea-9cc6-7cf40007728b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
系统用了Quartz定时任务
启动会开启了定时任务，这个不影响
