### ISSUE TITLE
request_param太短导致报错

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#146]
autoLog当参数长度大于255的时候，会报错，有什么办法吗？
1、每次超过255截取255
2、把request_param 改成longtext
3、关掉autolog
官方建议哪一种？

**Comment by galaxist** [comment]
这个根据自己需要来，问赶房干嘛，官方也不知道你们项目需要的撒

**Comment by zhangdaiscott** [comment]
自己改下长度即可
