### ISSUE TITLE
代码疑惑解答

### ISSUE THREAD

**Issue by yql97** [zhangdaiscott/jeecg-boot#1460]
##### 问题描述：
             oa流程发起页面模块代码未找到。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/33898949/87509971-3f2c6900-c6a5-11ea-9589-9cd917dde522.png)

![image](https://user-images.githubusercontent.com/33898949/87510069-713dcb00-c6a5-11ea-8b40-b3df308c0fb8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不开源

**Comment by yql97** [comment]
![image](https://user-images.githubusercontent.com/33898949/87511652-34bf9e80-c6a8-11ea-8f65-c15317f35c22.png)

![image](https://user-images.githubusercontent.com/33898949/87511638-2f625400-c6a8-11ea-948d-046b3721f9af.png)

你们像这样子有种文稿感觉和能打印pdf的表单是怎么做的？可以分享一下思路啥的吗？
