### ISSUE TITLE
功能求解

### ISSUE THREAD

**Issue by yql97** [zhangdaiscott/jeecg-boot#1461]
##### 问题描述：

你们像这样子有种文稿感觉和能打印pdf的表单是怎么做的？可以分享一下思路啥的吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33898949/87511954-cdeeb500-c6a8-11ea-9efb-01700fe56da6.png)

![image](https://user-images.githubusercontent.com/33898949/87511987-dba43a80-c6a8-11ea-8605-1dfb60b1d6c6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考常用示例--打印测试
![image](https://user-images.githubusercontent.com/3162115/87843007-5f496b80-c8e3-11ea-91d1-f02b56e5fa1d.png)
