### ISSUE TITLE
富文本组件在tab页面切换的时候失效

### ISSUE THREAD

**Issue by rill** [zhangdaiscott/jeecg-boot#1462]
##### 版本号：
2.2.1

##### 问题描述：
模板管理里点击新增一个系统类型的模板，富文本内容随便填一点，然后保存。这时候点编辑是正常的。
切换tab菜单到消息管理，然后再切换到模板管理。这时候再点新增富文本的内容无法输入；编辑的时候富文本的内容无法显示也无法输入。
此问题在官方的网站也能复现。
http://boot.jeecg.com/modules/message/sysMessageTemplateList
##### 截图&代码：
![image](https://user-images.githubusercontent.com/836402/87515062-d5648d00-c6ad-11ea-9226-c46f98413fd4.png)
![image](https://user-images.githubusercontent.com/836402/87515108-e7dec680-c6ad-11ea-8847-1848c646bafe.png)
代码直接是jeecg-boot原有的代码，未做任何改动。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by HeAvenLinH** [comment]
有同样的问题

**Comment by zhangdaiscott** [comment]
收录，我们确认下

**Comment by tygithub1** [comment]
1.在TabLayout.vue文件中添加method
```
excuteCallback(callback){
        callback()
      },
```
2.在JEditor.vue文件中initATabsChangeAutoReload方法添加else逻辑
```
initATabsChangeAutoReload() {
        // 获取父级
        let tabs = getVmParentByName(this, 'ATabs')
        let tabPane = getVmParentByName(this, 'ATabPane')
        if (tabs && tabPane) {
          // 用户自定义的 key
          let currentKey = tabPane.$vnode.key
          // 添加事件监听
          tabs.$on('change', (key) => {
            // 切换到自己时执行reload
            if (currentKey === key) {
              this.reload()
            }
          })
        }else{
          let tabLayout = getVmParentByName(this, 'TabLayout')
          tabLayout.excuteCallback(()=>{
            console.log('tabLayout.$vnode.key',tabLayout.$vnode.key)
            this.reload()
          })
        }
      },
```

**Comment by rill** [comment]
@tygithub1 大写的赞。
@zhangdaiscott 看是否可以合并到下个版本里。

**Comment by cooper1x** [comment]
> 1.在TabLayout.vue文件中添加method
> 
> ```
>      excuteCallback(callback){
>         callback()
>       },
> ```
> 
> 2.在JEditor.vue文件中initATabsChangeAutoReload方法添加else逻辑
> 
> ```
>     initATabsChangeAutoReload() {
>         // 获取父级
>         let tabs = getVmParentByName(this, 'ATabs')
>         let tabPane = getVmParentByName(this, 'ATabPane')
>         if (tabs && tabPane) {
>           // 用户自定义的 key
>           let currentKey = tabPane.$vnode.key
>           // 添加事件监听
>           tabs.$on('change', (key) => {
>             // 切换到自己时执行reload
>             if (currentKey === key) {
>               this.reload()
>             }
>           })
>         }else{
>           let tabLayout = getVmParentByName(this, 'TabLayout')
>           tabLayout.excuteCallback(()=>{
>             this.reload()
>           })
>         }
>       },
> ```

我原本的代码就有这个，发现还是有这个bug，我的是keepalive的组件
