### ISSUE TITLE
components文件夹Table组件showPagination参数问题

### ISSUE THREAD

**Issue by ZhouNick** [zhangdaiscott/jeecg-boot#1467]
##### 问题描述：
用到jeecg详情页组件，看到里面引用了stable组件，但表格我不想分页，看参数showPagination应该是显不显示分页的，传入false会报错，如下图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22462099/87655173-7aed2e80-c78a-11ea-9807-454a31ecb1c3.png)
![image](https://user-images.githubusercontent.com/22462099/87655241-92c4b280-c78a-11ea-9413-6aeb86bb7b46.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待下版本发布
