### ISSUE TITLE
orgcode重复,父编码与子编码相同,不是唯一的.

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1468]
##### 版本号：
2.2.1

##### 问题描述：
比如:
父编码
YouBianCodeUtil.getNextYouBianCode("Z99")="Z99A01"
子编码
YouBianCodeUtil.getSubYouBianCode("Z99",null)="Z99A01"

这就导致会出现重复的编码, 会不会影响业务数据?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
使用方法不正确，子编码需传入父级编码
详细可参照文档
https://www.kancloud.cn/zhangdaiscott/jeecg-boot/1833722

**Comment by GordonHuangYong** [comment]
我举的例子中，Z99就是父编码呀！怎么就使用不当了？
