### ISSUE TITLE
关于codegenerate依赖

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1469]
##### 版本号：
1.2.0

##### 问题描述：
org.jeecgframework.boot:codegenerate-1.2.0 能更新一下commons-lang这个依赖, 并将commons-lang和freemarker添加为codegenerate的依赖吗? 谢谢!

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这俩包本身就是依赖，没有问题
