### ISSUE TITLE
Excel导入导出问题灵活性调整问题

### ISSUE THREAD

**Issue by huangbosbos** [zhangdaiscott/jeecg-boot#147]
### 版本信息  

- jeecg版本:  2.0
- 操作系统: win 7 64bit
- 是否修改包名: 没有

### 报错信息    （注意格式化）

无

这里粘贴代码或者、日志  

无

### 问题描述

导入导出功能中，导出功能确少用户自行定义选择字段进行导出。建议，前端用户在选择显示的字段时候，可选择性的方式进行导出相关的数据。而非后端@Excel固定方式进行写死方式导出。

**Comment by judgerzhang** [comment]
这个确实重要不要估计有点麻烦，我处理方式是增加多个不同的实体类来满足导出格式不同。

**Comment by judgerzhang** [comment]
这个确实重要不过估计有点麻烦，我处理方式是增加多个不同的实体类来满足导出格式不同。

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布

**Comment by gxzhou** [comment]
> 已经实现，下个版本发布

为什么现在3,5.1版，还不可以选择呢？点击“导出”，就直接开干了。

**Comment by HideOnIT** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
