### ISSUE TITLE
online前端模板变量有误

### ISSUE THREAD

**Issue by whoisSixbusy** [zhangdaiscott/jeecg-boot#1470]
##### 版本号：
2.2.1

##### 问题描述：
${entityName}Modal.vuei文件中:okButtonProps="{ class:{'jee-hidden': disablesubmit} }"的disablesubmit应为disableSubmit

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待下版本发布
