### ISSUE TITLE
定时任务调用 SysBaseApiImpl.addLog 记录日志报错

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1472]
##### 版本号：
2.2.1

##### 问题描述：
定时任务调用 SysBaseApiImpl.addLog() 方法报错。

(LoginUser)SecurityUtils.getSubject().getPrincipal() 这一步

org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
（原因是定时任务获取不到SecurityManager，建议try catch或者根据参数做判断）

##### 截图&代码：

![42CE9353-727D-4fa1-A21A-F5D77AF34B78](https://user-images.githubusercontent.com/31750150/87751137-f228ce00-c82f-11ea-9307-f39d5aa6a122.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，下版本发布
