### ISSUE TITLE
建议升级shiro依赖  Apach Shiro官方披露其cookie持久化参数rememberMe加密算法存在漏洞

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1473]
##### 版本号：
2.2.1

##### 问题描述：

采用jwt后remember_me是不是没有用了，
前端登录页面勾选‘自动登录’传了参数'remember_me'，但是后台并没有对该参数做处理。

##### 截图&代码：

![F02ADB2A-3330-40db-AE4C-03E16232AF60](https://user-images.githubusercontent.com/31750150/87752904-0242ac80-c834-11ea-9283-3a8813c1cfc2.png)
![D0C1E5FE-F4B2-4d09-AE77-F7F03E90C231](https://user-images.githubusercontent.com/31750150/87753117-7715e680-c834-11ea-8b94-96805e88ee39.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3q

**Comment by zhangdaiscott** [comment]
已改下个版本发布
