### ISSUE TITLE
bug：QRTZ前缀表大小写差异导致程序启动和运行报错

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1475]
##### 版本号：
2.2.0-2.2.1

##### 问题描述：
QRTZ开头的几个表，项目启动和运行时程序中报错不存在。实际上数据库中是小写，而程序连接的是大写。
解决办法有修改数据库忽略大小写，但是linux上的mysql8忽略大小写只能在mysql初始化之前指定。
另一个解决办法是修改表名

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61787040/87787213-d6dcb380-c86d-11ea-87ed-5d1d312ace56.png)
![image](https://user-images.githubusercontent.com/61787040/87787450-3b980e00-c86e-11ea-816b-e82f7553be7a.png)

以下是我改成大写的表。这几个改成大写的是目前发现会导致报错的，其他的可能程序里没用上
![image](https://user-images.githubusercontent.com/61787040/87787744-b5c89280-c86e-11ea-9a1f-44c277e018cd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
需要设置数据库不区分大小写

**Comment by wushu037** [comment]
> 需要设置数据库不区分大小写
MYSQL8忽略大小写需要重新初始化数据库，删除所有数据
