### ISSUE TITLE
jeecg-boot:2.2.1多数据源配置无效

### ISSUE THREAD

**Issue by JunZheChen** [zhangdaiscott/jeecg-boot#1476]
##### 问题描述：
根据文档配置了多数据源，在serviceImpl加上@DS注解后正常启动，加载2个数据源，可是访问不到第二个指定的数据源。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/25046530/87845930-88c3c080-c8fe-11ea-9f46-20d2230d7ce4.png)
![image](https://user-images.githubusercontent.com/25046530/87845922-76498700-c8fe-11ea-95e6-b46f34f5ec4a.png)
![image](https://user-images.githubusercontent.com/25046530/87845948-b0b32400-c8fe-11ea-844d-741692faa741.png)
![image](https://user-images.githubusercontent.com/25046530/87845955-c3c5f400-c8fe-11ea-8180-c94e189ed2a8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lihongguang-lhg** [comment]
帅哥 你这个问题是怎么解决的呢 我现在也是遇到同样的问题
