### ISSUE TITLE
Docker镜像制作问题

### ISSUE THREAD

**Issue by guochunyang2004** [zhangdaiscott/jeecg-boot#1478]
##### 问题描述：
修改项目配置文件 application.yml   active: docker 后，需要手工加application-docker.yml，内容可复制其它yml文件，并把调用mysql、redis等地址改为docker能访问的相应的地址，并加本机hosts，才可以.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25301350/87868458-52eb0e80-c9c8-11ea-806d-60e66234a578.png)
![image](https://user-images.githubusercontent.com/25301350/87868461-60a09400-c9c8-11ea-82e2-f39b03bffd30.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是这样的

**Comment by Jaydonli2020** [comment]
@guochunyang2004 你好，问一下，添加本机host=》是指在docker里面添加？

**Comment by Jaydonli2020** [comment]
@guochunyang2004 原来在本机本地配置的呀，我现在试了可以了
