### ISSUE TITLE
jar简易部署到centos服务器，导入excel报错

### ISSUE THREAD

**Issue by y13810805250** [zhangdaiscott/jeecg-boot#148]
@zhangdaiscott 
![error](https://user-images.githubusercontent.com/7731348/58409456-af8fb980-80a2-11e9-8b7e-bb05bf455274.png)

**Comment by zhangdaiscott** [comment]
你的版本多少，你升级到最新

**Comment by apowder** [comment]
![image](https://user-images.githubusercontent.com/6261856/58447901-96394c80-8138-11e9-96f7-6a69ef1b9428.png)
centos 简易部署,你没有碰到 大小写问题吗。我的直接找不到表，是表名大小写问题

**Comment by zhangdaiscott** [comment]
看常见问题贴
