### ISSUE TITLE
 online开发href跳转到其他表单对应的详情页

### ISSUE THREAD

**Issue by huyaru** [zhangdaiscott/jeecg-boot#1480]
##### 问题描述：online开发中，通过配置href，跳转到其他online表单对应的详情页面，例如点击关联的其他表单ID，直接弹出这个表单ID对弈的详情页面。
之前的http://doc.jeecg.com/1463259 并没有解决这个问题，谢谢

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/39981456/87898654-58f0f600-ca81-11ea-8e97-78ef0c501f41.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
为什么没解决？

**Comment by huyaru** [comment]
您好：
   需求是这样的，我在online表单A，点击一个已经配好的id链接，想弹出online表单B的对应此id的详情页面。
现在只能挑转到对应的表单B。我尝试加id参数等，和配置online表单api的方式都没法完成这个功能。麻烦帮忙看一下，如果确定是可以的，麻烦指点一下，
应该怎么处理这个href










--

  







在 2020-07-25 09:57:11，"JEECG开源社区" <notifications@github.com> 写道：

为什么没解决？

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
