### ISSUE TITLE
表单主附表设计

### ISSUE THREAD

**Issue by turkeymz** [zhangdaiscott/jeecg-boot#1481]
##### 版本号：
    <parent>
        <groupId>org.jeecgframework.boot</groupId>
        <artifactId>swyjt-parent</artifactId>
        <version>2.2.0</version>
    </parent>
##### 问题描述：
我有一个需求，需要3张表关联。其中中间一张表是主表也是附表。也就是1:n:n。
而我想点击第一张主表的编辑，可以添加或修改第二张表数据。
同时点第二张表，也能关联出第三张表的数据
请问这个如何在online表单中配置。

##### 截图&代码：
1:n:n表单开发

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
不支持

**Comment by yanyapeng123** [comment]
> 目前不支持，只能这么做，在A表上增加字段href，跳转B页面，b页面是个1对多的页面，但是跳转似乎没有此功能
> 
> 下个版本可以支持了

咨询：这个功能是不是 主子孙表结构模式呢？
