### ISSUE TITLE
online表单配置数据库表字段类型问题

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1483]
##### 问题描述： 使用online表单配置数据库表的时候，主键生成策略现在是ID_WORKER分布式雪花算法，
这个算法出来的是一个19位的数字，数据库的主键字段类型想定义成bigint，但是目前下拉里没有，
并且对于bigint字段类型生成的entity对象里对应类型应为Long类型。
希望下一个 小版本加上这个的支持

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前暂时还不支持，后续会改进，
可以生成完代码，手工进行调整
