### ISSUE TITLE
修改默认主题部分未生效

### ISSUE THREAD

**Issue by yy879770988** [zhangdaiscott/jeecg-boot#1484]
##### 问题描述：
根据文档修改全局主题颜色，vue.config.js和src/defaultSettings.js中的primaryColor，如图所示table alert颜色未改变。
只当通过系统设置修改颜色后才正常生效。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23287804/88002112-4edbff80-cb34-11ea-9326-ee0e4ee98ae5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/88661865-cc42d980-d10b-11ea-9d83-0d993c92ed57.png)
修改vue.config下代码，再重新启动项目
效果图
![image](https://user-images.githubusercontent.com/30997828/88662011-f5fc0080-d10b-11ea-959f-e638ed63ab55.png)

**Comment by tengshe789** [comment]
请问解决了么?如何解决的?
