### ISSUE TITLE
请问是否可以在online开发里面添加表单字段分组显示功能

### ISSUE THREAD

**Issue by hejinxu** [zhangdaiscott/jeecg-boot#1485]
##### 版本号：
jeecg-boot 2.2.0

##### 问题描述：
请问是否可以在online开发里面，添加表单字段分组展示的功能。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持，再高级的页面排版可以用表单设计器
