### ISSUE TITLE
Result.ok

### ISSUE THREAD

**Issue by hsb786** [zhangdaiscott/jeecg-boot#1487]
##### 问题描述：

Result.ok(Object data) 建议改成用泛型，不然swagger文档返回的一直是object
![图片](https://user-images.githubusercontent.com/16677633/88028195-e9573580-cb6a-11ea-844d-1779f4d334e8.png)

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/16677633/88027987-9b423200-cb6a-11ea-8e45-62b131180123.png)

~~~
public static<T> Result<T> ok(T data) {
		Result<T> r = new Result<>();
		r.setSuccess(true);
		r.setCode(CommonConstant.SC_OK_200);
		r.setResult(data);
		return r;
	}
~~~

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by J-cafe** [comment]
下个版本更新
