### ISSUE TITLE
关于前端项目使用yarn build 构建区分环境的问题

### ISSUE THREAD

**Issue by dustdragonpzc** [zhangdaiscott/jeecg-boot#1488]
##### 问题描述：
前端项目的接口地址定义在index.html页面中,使用的是window._CONFIG['domianURL']的配置,我这边有个需求就是分别使用
yarn build dev 和 yarn build prod 来进行构建, 然后通过process.env.NODE_ENV 进程来获取是哪个环境,使用不同的接口地址,但是在index.html中无法获取process.env.NODE_ENV,请问有什么其他的方法来解决这个问题吗

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liwanyin** [comment]
请问下这个问题你是怎么解决的呢？谢谢
