### ISSUE TITLE
jeece-uniapp

### ISSUE THREAD

**Issue by guoglee** [zhangdaiscott/jeecg-boot#1489]
##### 问题描述：
手动运行调试 链接跳转会报错

##### 截图&代码：
ypeError: undefined is not an object (evaluating 'this.$router.push')
17:41:16.816 App Hide at App.vue:140
17:47:07.036 App Show at App.vue:137
17:47:08.982 [Vue warn]: Error in v-on handler: "TypeError: undefined is not an object (evaluating 'this.$router.push')"
17:47:09.022 found in
17:47:09.062 ---> <Home> at pages/home/home.vue:1
17:47:09.082 　　　　at pages/index/index.vue:1

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
去jeece-uniapp项目提

**Comment by guoglee** [comment]
> 去jeece-uniapp项目提

在那边提了，没有人回
