### ISSUE TITLE
修改包名后，online无法使用

### ISSUE THREAD

**Issue by Linyuxujun** [zhangdaiscott/jeecg-boot#1490]
##### 版本号：

2.2.1

##### 问题描述：

修改包名 online无法使用 ， 原因是因为online包依赖于hibernate.re.jar
   
于是加入在启动类加入@ComponentScan(basePackages = {"com.xxx.*","org.jeecg.*"})

启动报错为：Caused by: java.lang.ClassNotFoundException: org.jeecg.common.api.vo.Result
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 common frames omitted

发现 代码对org.jeecg.common.api.vo 包又有依赖。

包名修改如下 
![image](https://user-images.githubusercontent.com/45812406/88123594-ccb80d80-cbfd-11ea-8616-231b0afa0a00.png)

![image](https://user-images.githubusercontent.com/45812406/88123642-e5c0be80-cbfd-11ea-959b-beee5686f09d.png)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45812406/88123181-f3c20f80-cbfc-11ea-943d-2c741e5a7fd2.png)

![image](https://user-images.githubusercontent.com/45812406/88123516-9bd7d880-cbfd-11ea-881d-bab7d425ce70.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
保留jeecg路径
