### ISSUE TITLE
前端项目打包速度慢

### ISSUE THREAD

**Issue by dustdragonpzc** [zhangdaiscott/jeecg-boot#1491]
##### 问题描述：
使用yarn build命令进行打包发布,耗时差不多要5min左右,很慢,请问没有什么优化的方法

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
vue.config.js
如果开启压缩不需要，注释掉会快一些
![image](https://user-images.githubusercontent.com/3162115/88275501-1133ce00-cd10-11ea-96ba-6c692cbfa87d.png)
