### ISSUE TITLE
页面左边被菜单遮挡一部分

### ISSUE THREAD

**Issue by tenlisen** [zhangdaiscott/jeecg-boot#1493]
##### 版本号：
v2.2.1

##### 问题描述：
用谷歌浏览器调试页面，退出调试时，页面左边被菜单遮挡一部分，首页标签也见了，刷新和重启浏览器无效果。
也就是偶也有这种情况发生。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44961488/88153188-a911b900-cc37-11ea-9f03-dfd03cdacb18.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最好有重现步骤

**Comment by LongYue9608** [comment]
这个问题我也遇见了
