### ISSUE TITLE
关于机构、部门的问题

### ISSUE THREAD

**Issue by semizhou** [zhangdaiscott/jeecg-boot#1494]
##### 问题描述：
1、关于机构、部门在一张表里的设计初衷，设计思想能够在哔哩哔哩的视频里能够从设计的角度讲一讲。
2、目前在controller中获取当前登录人，但是并没有所属机构、所属部门。

##### 截图&代码：无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
那应该怎么设计，请详细描述你的需求

**Comment by zhangdaiscott** [comment]
目前在controller中获取当前登录人，但是并没有所属机构、所属部门。
可以自己扩展下，目前平台暂时不改
