### ISSUE TITLE
生成的代码没有详情的这个按钮了

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1496]
##### 版本号：
2.2.1

##### 问题描述：
代码生成后没有详情按钮，
在线预览的时候有详情按钮

这个是需要在哪块添加功能才能实现呢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.2.1 已经有了，你确认下你的版本和用的那套模板

**Comment by trdmm** [comment]
> 2.2.1 已经有了，你确认下你的版本和用的那套模板

11.12号,2.3.0版本(10月底最后一个commit),ERP模板,一对多,还是没有**详情**按钮
