### ISSUE TITLE
POPUP怎么才能让多选择数据后，自动回填到多行中

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1497]
##### 版本号：
2.2.1

##### 问题描述：
我做了一个销售出库单，选择商品，弹出框有多个，此时选择多个商品，希望根据我选择的商品自动回填到子表多行去，现在是选择后，填写到一行里面了

##### 截图&代码：
跪求，官方支持，这个功能太重要了，死活不会实现

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273911
![image](https://user-images.githubusercontent.com/3162115/88257304-fd786f80-ccef-11ea-9602-60a7ddf68ee6.png)
