### ISSUE TITLE
左侧菜单栏缩放窗口后无法显示

### ISSUE THREAD

**Issue by HanYaodong** [zhangdaiscott/jeecg-boot#1498]
##### 问题描述：

左侧菜单栏在缩放窗口后无法显示。如果将窗口缩小，使菜单栏变为抽屉样式后，再放大窗口，菜单栏就会无法显示。

##### 截图&代码：

**Step 1:** 缩小窗口，直到菜单栏变为抽屉样式

![image](https://user-images.githubusercontent.com/31091101/88245264-2c2f1f80-ccc9-11ea-9dba-73a17e08ea07.png)

**Step 2:** 重新放大窗口

![image](https://user-images.githubusercontent.com/31091101/88245280-3e10c280-ccc9-11ea-8ea1-0bb087f7ce4f.png)

这时候点击左上角的菜单控制是没有用的，只能刷新页面

**Comment by tygithub1** [comment]
i call this behavior is so idle that egg ache

**Comment by HanYaodong** [comment]
> i call this behavior is so idle that egg ache

怎么，缩放窗口不是很常见的操作嘛...

**Comment by 425765923** [comment]
我也发现了，页面宽度缩小到自动弹出左侧菜单栏，再放大到正常尺寸后，点击顶部展开菜单按钮就无效了

**Comment by 1298191366** [comment]
已修改，待下版本发布
