### ISSUE TITLE
swagger 报token失效问题

### ISSUE THREAD

**Issue by Linyuxujun** [zhangdaiscott/jeecg-boot#1499]
##### 问题描述：
swagger测试接口，已把url加入ShiroConfig.java 仍然包token失效，重启过项目

是否因为我改了包名？

请问下图，jeecg.shiro.excludeUrls 是何值是否需要更改
![image](https://user-images.githubusercontent.com/45812406/88247019-da899380-ccce-11ea-9507-9065cbd4bf7f.png)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45812406/88246889-7961c000-ccce-11ea-8b64-6964f9d43a66.png)
![image](https://user-images.githubusercontent.com/45812406/88246896-8088ce00-ccce-11ea-89cd-230f698b5891.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Linyuxujun** [comment]
jeecg.shiro.excludeUrls 值已找到无需更改

**Comment by Linyuxujun** [comment]
找到原因，排除时不必加入请求前缀

**Comment by GordonHuangYong** [comment]
> 找到原因，排除时不必加入请求前缀

请问您是如何解决的,能发出来吗?

**Comment by Linyuxujun** [comment]
因为在配置文件加入了pharmadeer 前缀， shiro 过滤时 是不加入前缀的， 上面截图内容改为filterChainDefinitionMap.put("/customer/register", "anon"); 即可

**Comment by GordonHuangYong** [comment]
还是不行.可能是我的包不在jeecg-boot-module-system之中的原因.

**Comment by Linyuxujun** [comment]
swagger 测试 的时候要加入token

**Comment by GordonHuangYong** [comment]
我过滤掉这个,就是不想用到token.

**Comment by Linyuxujun** [comment]
请求url 放里面就行了  ， 

@RequestMapping("/company/")
    public class CompanyController extends BaseController {

 @PostMapping("add")
    public Result add() 


map的key就是 "/company/add"

**Comment by GordonHuangYong** [comment]
![图片](https://user-images.githubusercontent.com/20039800/90714288-ea9a9000-e2d9-11ea-8235-b24e1247449a.png)
![图片](https://user-images.githubusercontent.com/20039800/90714305-f38b6180-e2d9-11ea-8541-9fd243ed603d.png)

**Comment by GordonHuangYong** [comment]
**是刚才加的.之前是没有的.

**Comment by Linyuxujun** [comment]
不需要前面的**/

**Comment by GordonHuangYong** [comment]
> 不需要前面的**/

试过不加的.各种情况都试了,只有把代码放进jeecg-boot-module-system里才有用.

**Comment by Linyuxujun** [comment]
哦哦，那你及以上jeecg-boot-module-system 模块 未引用 你的模块 ，引用了即可

**Comment by GordonHuangYong** [comment]
引用了的.其它模块都能用.就是想加一个不需要token的接口.这才发现不行

**Comment by GordonHuangYong** [comment]
![图片](https://user-images.githubusercontent.com/20039800/90715530-18350880-e2dd-11ea-96a7-a005c2135b99.png)
找到原因了.不要这里的后面, 放前面即可.
