### ISSUE TITLE
聚合路由如何配置？？？

### ISSUE THREAD

**Issue by QiangFangcn** [zhangdaiscott/jeecg-boot#150]
聚合路由如何配置？？？多谢回复，弄了好久

**Comment by fly1206** [comment]
参见官方文档  https://team.oschina.net/jeecg/document   目前功能还不完善  下个版本发布

**Comment by zhangdaiscott** [comment]
代码已经上传
最新文档
http://jeecg-boot.mydoc.io/?t=346060
