### ISSUE TITLE
bug：JS不支持long型导致精度丢失问题

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1500]
##### 版本号：
2.2.1

##### 问题描述：
**js的Number类型装不下java的long型长度，会导致精度丢失。**
框架中存在这样一些long型的传输，比如分页的total等

##### 截图&代码：

![image](https://user-images.githubusercontent.com/61787040/88353377-cf4a6c80-cd8f-11ea-98bd-0ed062d17520.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
实际中分页total不可能会超出js的number类型长度，这个问题实际开发自己解决 ，将数值转成字符串即可
