### ISSUE TITLE
新建module如何引入system中的类

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1502]
##### 版本号：
2.2.1

##### 问题描述：
新建module如何引入system中的类，如PushMsgUtil

##### 截图&代码：

![11](https://user-images.githubusercontent.com/59555469/88360742-6d96fc00-cda9-11ea-9037-6d238ad47a6c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/88446398-40575600-ce5c-11ea-8865-971c26fe4335.png)
http://doc.jeecg.com/1273938

**Comment by shrto** [comment]
你好，ISysBaseAPI中没有邮件通知的方法，其他模块如何使用system中PushMsgUtil这个类呢
