### ISSUE TITLE
页面按钮样式被覆盖

### ISSUE THREAD

**Issue by ReGan520** [zhangdaiscott/jeecg-boot#1503]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/23241233/88365622-3e888680-cdb9-11ea-895f-a4e5feb7e74c.png)

![image](https://user-images.githubusercontent.com/23241233/88365608-2f093d80-cdb9-11ea-9095-911b10b17f37.png)

**Comment by zhangdaiscott** [comment]
这是具体哪一行？

**Comment by zhangdaiscott** [comment]
[Desktop.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4974752/Desktop.zip)
用附件文件覆盖下本地依赖，看看能解决这个问题不

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1286

**Comment by ReGan520** [comment]
通过你发过来的**OnlineForm.css**文件，发现有很多.ant-btn-danger的定义，有一个属于全局的，导致不能正常使用danger按钮；

![image](https://user-images.githubusercontent.com/23241233/88497024-97426400-cff1-11ea-8cdb-6660e3b33755.png)


请问一下**OnlineForm.css** 的样式文件就是  这个包下的**@jeecg/antd-online-214/dist/OnlineForm.css** 的文件吗？

**Comment by zhangdaiscott** [comment]
对，可以先手工把这段删掉

**Comment by ReGan520** [comment]
替换你最新给的这个包里的样式文件，没问题了，感谢.   ღ( ´･ᴗ･` )比心

**Comment by whitejiang123** [comment]
@jeecg/antd-online-214/dist/OnlineForm.css  这个文件在哪  我怎么找不到
