### ISSUE TITLE
问题：2.2.1如何使用scss语预处理

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1504]
##### 版本号：
2.2.1

##### 问题描述：
之前用2.2.0是可以用scss的，现在2.2.1用scss会报错。两个版本的package.json中都没有写sass-loader
scss比less好用很多

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61787040/88369058-ca9eac00-cdc1-11ea-8ef1-dae6a4872bcb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
scss 去掉了，scss编译各种问题，less也能满足日常需求

**Comment by wushu037** [comment]
> scss 去掉了，scss编译各种问题，less也能满足日常需求

大佬能说一下上个版本scss定义在哪里的么，没看到啊。谢谢大佬
