### ISSUE TITLE
自己自定义的表 数据规则不生效

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1506]
##### 问题描述：已按照文档设置管理用户的数据权限生效，但自己自定义的表 数据规则不生效
http://doc.jeecg.com/1273977

##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/88384097-5cb4ad80-cdde-11ea-9a62-d2a1c63f9868.png)

![image](https://user-images.githubusercontent.com/18321599/88384115-64745200-cdde-11ea-9371-b38a6c1ba5fb.png)

![image](https://user-images.githubusercontent.com/18321599/88384148-735b0480-cdde-11ea-963e-6d3c61389ecf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/88409977-4cb1c380-ce08-11ea-96a9-80f198d5292d.png)

**Comment by jwcjf** [comment]
@zhangdaiscott   这个方法也试过了
