### ISSUE TITLE
tinymce第一次打开正常,页面切换后再切换回来内容空白且无法编辑

### ISSUE THREAD

**Issue by jspang582** [zhangdaiscott/jeecg-boot#1507]
##### 版本号：
2.2.1

##### 问题描述：
页面切换后，tinymce富文本编辑器内容空白且无法编辑

##### 截图&代码：
![image](https://user-images.githubusercontent.com/68464475/88463331-76401d00-cee4-11ea-82eb-01c450d4f87a.png)

以下是我的解决办法：

    <editor
      v-if="active"
      v-model="myValue"
      :init="init"
      :disabled="disabled"
      @onClick="onClick">
    </editor>

    mounted () {
        tinymce.init({})
        this.active = true
    },
    destroyed () {
        this.active = false
    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3q

**Comment by Chrry555** [comment]
帮大忙了，多谢

**Comment by UnicornXU** [comment]
还是不管用 不知道为啥
