### ISSUE TITLE
Cannot resolve org.hibernate:hibernate-re:2.2.11,Cannot resolve org.jeecgframework.boot:codegenerate:1.2.0

### ISSUE THREAD

**Issue by qq471754603** [zhangdaiscott/jeecg-boot#1511]
##### 版本号：
jeecg-boog 2.2.1

Cannot resolve org.hibernate:hibernate-re:2.2.11

Cannot resolve org.jeecgframework.boot:codegenerate:1.2.0

##### 问题描述：
Cannot resolve org.hibernate:hibernate-re:2.2.11

Cannot resolve org.jeecgframework.boot:codegenerate:1.2.0

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23146592/88503904-974c5f00-d005-11ea-8f83-d2ab1514f71f.png)

![image](https://user-images.githubusercontent.com/23146592/88503934-aaf7c580-d005-11ea-99e7-cdc8a234bdd4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273965

**Comment by qq471754603** [comment]
这个设置了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 下午2:06
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"Luckly hu"<471754603@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] Cannot resolve org.hibernate:hibernate-re:2.2.11,Cannot resolve org.jeecgframework.boot:codegenerate:1.2.0 (#1511)





 
http://doc.jeecg.com/1273965

**Comment by MyEclipseyang** [comment]
在maven的setting.xml设置了jeecg私服地址后，重新构建下maven就行了

**Comment by linzhengtian** [comment]
今天我也碰到了，原因是你用的的是idea开发，如果你conf文件下有多个xml配置文件，且你idea里面设置的xml不叫setting.xml，例如叫setting-jeecg.xml，那么你xml即便设置的和官方介绍的一样，也可能会有问题，解决方法很简单，把你conf同目录下没有用的配置文件先删了，然后你就不会报错了！
