### ISSUE TITLE
基础表结构,id能不能改成int自增的,这个这么长,

### ISSUE THREAD

**Issue by qq471754603** [zhangdaiscott/jeecg-boot#1512]
##### 版本号：

2.2.1
##### 问题描述：

主键自增问题,导入的表是主键自增的,主键选择类型没有选项
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成完代码，可以自己手工改

**Comment by qq471754603** [comment]
id那么长有点奇葩




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年7月27日(星期一) 下午2:06
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "Luckly hu"<471754603@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 基础表结构,id能不能改成int自增的,这个这么长, (#1512)





 
Closed #1512.
 
&mdash;
