### ISSUE TITLE
AutoPoi多表头导出，会多出一列空白列

### ISSUE THREAD

**Issue by dyfcx** [zhangdaiscott/jeecg-boot#1513]
##### 版本号：
2.1.4，autopoi是1.1.0，也测试过1.1.1

##### 问题描述：
多表头导出，需要合并表头，会多出一列空列，导出方式参考http://doc.jeecg.com/1570982，两种方式问题一样。

##### 截图&代码：
如下图所示
![image](https://user-images.githubusercontent.com/18730076/88508394-4b9fb280-d011-11ea-99a4-49b9cb8db256.png)
![image](https://user-images.githubusercontent.com/18730076/88508429-5d815580-d011-11ea-991b-b2fea6f85264.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
测试无问题

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/89640886-1a619500-d8e3-11ea-859d-5d0305570ad3.png)

**Comment by dyfcx** [comment]
能看一下您的代码么，或者指出我代码的问题，您是使用什么版本的啊

**Comment by dyfcx** [comment]
@zhangdaiscott 您好，测试有标题的时候会有我提到的问题，代码如下
 Workbook wb = ExcelExportUtil.exportExcel(new ExportParams("主标题", "副标题" , "sheet1"),T.class,list);

**Comment by lsqGitHub716** [comment]
已修复，下版本发布
