### ISSUE TITLE
高级查询构造器条件值是下拉框并且下拉框项目较多时检错报错

### ISSUE THREAD

**Issue by wdong18** [zhangdaiscott/jeecg-boot#1517]
##### 版本号：
2.2.1

##### 问题描述：
高级查询构造器条件值是下拉框并且下拉框项目较多时检错报错.
初步调查是因为高级查询构造器使用get请求,该请求将下拉框中出现的所有可能值都放进了请求参数里,导致请求参数超过了url长度限制导致的.
##### 截图&代码：
![20200728130912](https://user-images.githubusercontent.com/1029657/88621872-10b28300-d0d4-11ea-9d4e-b7d2c3c9411d.jpg)

使用表单生成器零编码
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
