### ISSUE TITLE
iframe内部打开问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#1518]
##### 问题描述：
升级最新版后，发现iframe在内部打开提示报错
Blocked autofocusing on a form control in a cross-origin subframe.
且登录无法跳转。举例：sql监控页面。
原先都是正常的，去官方体验版看了下，已改成外部打开了，由于权限不够，试不了内部打开的结果。
不知道是我升级不完整，还是新版本问题。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/89369939-103c6c80-d712-11ea-8222-eca92c135e1f.png)
平台没问题，应该是你frame里面的url禁止了跨域
