### ISSUE TITLE
同步数据库报错

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1519]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/88629085-693c4d00-d0e1-11ea-9c80-5eb8ef5a879c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jwcjf** [comment]
本地idea报错，放服务器不报错，这是为啥

**Comment by tygithub1** [comment]
你就不是代码问题哦，检查本地环境

**Comment by jwcjf** [comment]
> 你可能就不是代码问题，检查本地环境，看看其他功能会报错吗

其他功能不报错，就这个功能报错，编译之后放服务器就不报错，所以觉得很奇怪
