### ISSUE TITLE
在IDEA中启动后台项目报数据库问题

### ISSUE THREAD

**Issue by Jalone5186** [zhangdaiscott/jeecg-boot#152]
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/
Oracle/SQL server数据库切换

**Comment by Jalone5186** [comment]
我用的是MySQL5.7版本，redis也都启动好的。不存在切换数据库的。

**Comment by Jalone5186** [comment]
@zhangdaiscott 我之前用的是1.0的版本，开发环境都搭建好了的。昨天晚上是下载最新的项目下来重新搭建2.0版本的项目。2.0版本的项目启动就报了shiro缺少shiro.ini文件，和这数据库错误。
