### ISSUE TITLE
希望官方将 QRTZ 前缀表都改成小写

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#1521]
##### 版本号：
 2.2.1

##### 问题描述：
因为 mysql8 修改数据库不区分大小写代价非常大，而且小写下划线可以抹平不同系统不同数据库版本的差异。

##### 截图&代码：
ERROR druid.sql.Statement:149 - {conn-10005, pstmt-20000} execute error. SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = ? FOR UPDATE

**Comment by huyaru** [comment]
windows是默认不区分大小写得，请问你得服务器是什么开发系统。如果是windows得话，可以检查一下创建数据库时候得编码规则。

**Comment by CharlieJ0hn** [comment]
我开发用mac，部署用debian，由于数据库需要创建到原来的生产库里边，但是原来的生产库是mysql8，无法直接修改配置文件使其不区分大小写，需要删除整个数据库在安装的时候改，所以用jeecg写的东西无法部署。

**Comment by anuxs** [comment]
区分大小写、用unicode是程序员的美德。
不明白你说的不区分大小写是什么意思？为什么要不区分大小写？用jeecg自动生成的代码都是严格根据你数据库表明、指端名来的，mysql默认就是分大小写的。程序员要严谨，不分大小写会带来灾难性的后果。
除非你不用java来开发。

**Comment by CharlieJ0hn** [comment]
> 区分大小写、用unicode是程序员的美德。
> 不明白你说的不区分大小写是什么意思？为什么要不区分大小写？用jeecg自动生成的代码都是严格根据你数据库表名、字段名来的，mysql默认就是分大小写的。程序员要严谨，不分大小写会带来灾难性的后果。
> 除非你不用java来开发。

您仔细看我的话了吗？是这个项目在linux和mac跑不起来。目前需要将数据库改成不区分大小写才能跑起来。所以我提了这个issue。希望官方将数据库表名改成区分大小写。你们建表是小写，代码是大写，这样本身就不严谨。

**Comment by xinwu-yang** [comment]
启动的时候加上--lower_case_table_names=1 就好了呗

**Comment by huyaru** [comment]
修改配置文件中，quartz下的，setTablePrefix，改成你要的小写应该就能解决你发现的问题了

**Comment by CharlieJ0hn** [comment]
> 启动mysql的时候加上--lower_case_table_names=1 就好了呗

大哥，你们回答时候不仔细看 issue吗？是写好的项目要上到生产数据库，但是生产数据库不能改配置，不能重启，不能重装。况且lower_case_table_names 改了以后压根不符合 linux 数据库规范。

**Comment by edilyxin** [comment]
大哥们，最后的结论是什么？不用liunx，或者，liunx下修改不区分大小写么？

**Comment by galaxist** [comment]
> > 启动mysql的时候加上--lower_case_table_names=1 就好了呗
> 
> 大哥，你们回答时候不仔细看 issue吗？是写好的项目要上到生产数据库，但是生产数据库不能改配置，不能重启，不能重装。况且lower_case_table_names 改了以后压根不符合 linux 数据库规范。

自己改一下建表语句不就行了，啥时候操作系统还要做数据库规范了？那不是操作系统还要规范个人建文件名的大小写了。

**Comment by CharlieJ0hn** [comment]
> 大哥们，最后的结论是什么？不用liunx，或者，liunx下修改不区分大小写么？

我提过相关pr了，将建表sql文件中所有qurtz相关的表名全部改成大写了。

**Comment by Derickorqq** [comment]
这个问题毫无疑问应该官方该sql脚本啊，真的很不严谨，按照说明改了然后抱着个错。
另外后台项目启动应该说明运行哪个module，结构说明的太简单了

**Comment by leessmin** [comment]
这个iusse以及是4年前的事情了，都没见修改。呃呃呃呃，我也觉得非常不严谨，非常业余的做法，如果不是公司要用，我绝对不用这个玩意。实在不行我已经开始考虑换份工作了，第一次见开发这么不严谨的模板。心里很不爽，很像骂人，但是无可奈何要文明，祝好。

**Comment by leessmin** [comment]
这个issue已经是4年前的事情了，都没见修改。呃呃呃呃，我也觉得非常不严谨，非常业余的做法，如果不是公司要用，我绝对不用这个玩意。实在不行我已经开始考虑换份工作了，第一次见开发这么不严谨的模板。心里很不爽，很想骂人，但是无可奈何要文明，祝好。希望若依越来越强大，干掉jeecgboot,若依万岁！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by zcyc** [comment]
> 这个issue已经是4年前的事情了，都没见修改。呃呃呃呃，我也觉得非常不严谨，非常业余的做法，如果不是公司要用，我绝对不用这个玩意。实在不行我已经开始考虑换份工作了，第一次见开发这么不严谨的模板。心里很不爽，很想骂人，但是无可奈何要文明，祝好。希望若依越来越强大，干掉jeecgboot,若依万岁！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

很抱歉，我之前提了PR。由于我的疏忽，提交了错误的 SQL 上去。后来官方撤回了PR，这个问题就不了了之了。
