### ISSUE TITLE
数据字典项 Redis 缓存冲突

### ISSUE THREAD

**Issue by HanYaodong** [zhangdaiscott/jeecg-boot#1522]
##### 问题描述：

下面两个方法在 redis 中共用一个 key，而且参数形式相同，但是返回对象不同。当两个方法的参数相同的时候，在 redis 中储存的数据不同，一个是 String，一个是 ArrayList，可能会导致报错。建议用不同的 redis key。

（版本<=2.2.0中，两个方法的参数形式不同，所以不会造成冲突）

https://github.com/zhangdaiscott/jeecg-boot/blob/4fd30c495fb4c83dd1858d9af457587bebd43a0b/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/service/impl/SysDictServiceImpl.java#L124-L129

https://github.com/zhangdaiscott/jeecg-boot/blob/4fd30c495fb4c83dd1858d9af457587bebd43a0b/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/service/impl/SysDictServiceImpl.java#L140-L145

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Domain711** [comment]
我也发的这个问题，但是没回复现在

**Comment by Domain711** [comment]
你这个问题解决了没

**Comment by HanYaodong** [comment]
> 你这个问题解决了没

给冲突的方法换个redis key的名字就行了

**Comment by Domain711** [comment]
方便加个QQ不，便于沟通一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Han&amp;nbsp;Yaodong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月9日(星期天) 中午1:04
收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;&quot;Domain711&quot;<691386631@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 数据字典项 Redis 缓存冲突 (#1522)

**Comment by HanYaodong** [comment]
直接把 `@Cacheable(value = CacheConstant.SYS_DICT_TABLE_CACHE)` 里面的 `value` 换成不一样的就行了，就是因为这个冲突了啊

**Comment by tanpenggood** [comment]
已修复，将在下一版本发布。
