### ISSUE TITLE
需求：首页的组件有计划做成可配置的吗？

### ISSUE THREAD

**Issue by anxiaolei** [zhangdaiscott/jeecg-boot#1523]
##### 版本号：
2.2.1

##### 问题描述：
首页的组件有计划做成可配置的吗？因为不是所有人都要看到同样的数据，可能老板要看更全局的报表数据。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jwcjf** [comment]
数据可以通过 数据接口配置权限

**Comment by J-cafe** [comment]
首页组件可以自定义，菜单设置修改成你的自定义组件，然后根据权限控制数据展示
