### ISSUE TITLE
online表单开发里面，控件类型选【富文本】后不显示富文本效果

### ISSUE THREAD

**Issue by zyzTm** [zhangdaiscott/jeecg-boot#1524]
##### 版本号：
2.2.1

##### 问题描述：
online表单开发里面，控件类型选【富文本】后，在功能测试里展示不了富文本效果。
但是在系统管理--系统通告--新增页面里，富文本能展示出来

##### 截图&代码：
![1](https://user-images.githubusercontent.com/49476685/88872013-dcfa6900-d24b-11ea-92bf-1592a52f7086.jpg)
![2](https://user-images.githubusercontent.com/49476685/88872020-e1bf1d00-d24b-11ea-90f4-eba881bb6ffa.jpg)
![3](https://user-images.githubusercontent.com/49476685/88872025-e4ba0d80-d24b-11ea-9e7f-b343ed5b26f4.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/log
![image](https://user-images.githubusercontent.com/3162115/88873708-da017780-d24f-11ea-81ee-212f26cc41bc.png)

**Comment by zyzTm** [comment]
> http://www.jeecg.com/doc/log
> ![image](https://user-images.githubusercontent.com/3162115/88873708-da017780-d24f-11ea-81ee-212f26cc41bc.png)

我这个新手，如何启用富文本和md的支持？
