### ISSUE TITLE
online表单模糊查询

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1527]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？？

**Comment by tygithub1** [comment]
模糊查询会降低查询效率 不会让他默认支持

**Comment by jwcjf** [comment]
> 模糊查询会降低查询效率 不会让他默认支持

那可以有个配置，配置哪个字段支持模糊查询吗

**Comment by tygithub1** [comment]
加*模糊，jeecg传统默认规则，这个暂时不会改动

**Comment by jwcjf** [comment]
> 加*模糊，jeecg传统默认规则，这个暂时不会改动

但作为普通用户，他们不知道需要 加 * ，他们也懒得加。所以最好还是可以配置最好，在online表单可以设置吗
