### ISSUE TITLE
关于quartz 配置单独数据源的问题

### ISSUE THREAD

**Issue by hbyyan** [zhangdaiscott/jeecg-boot#1529]
##### 截图&代码：
图一：
![1596177618(1)](https://user-images.githubusercontent.com/30141572/89007968-65f0cd80-d33c-11ea-8f08-9118ac8e4751.jpg)
图二：
![image](https://user-images.githubusercontent.com/30141572/89008034-815bd880-d33c-11ea-81e0-8ca21943bdbc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jzyadmin** [comment]
quartz 在初始启动过程中会指定使用数据源，初始化完成前进行数据源的获取
```
        @Resource
	DynamicRoutingDataSource dynamicRoutingDataSource;
	@Bean
	public SchedulerFactoryBean quartzScheduler() {
		SchedulerFactoryBean schedulerFactoryBean = new SchedulerFactoryBean();
		schedulerFactoryBean.setDataSource(dynamicRoutingDataSource.getDataSource("基础库"));
		return schedulerFactoryBean;
	}
```
