### ISSUE TITLE
j-category-select、j-dict-select-tag 下拉框如何设置默认值 【v-decorator方式】

### ISSUE THREAD

**Issue by catlvsuger** [zhangdaiscott/jeecg-boot#1530]
##### 问题描述：j-category-select、j-dict-select-tag 下拉框，获取动态options的一个元素为默认值
v-decorator 用initialValue，initialValue设置在从字典缓存中获取下拉数据在前面，initialValue取不到值，请教下有没有好的方式设置默认值

##### 截图&代码：
目前做法：
JDictSelectTag initDictData()添加
this.$emit('update:dictOption', this.dictOptions[0])
调用地方获取初始值：
:dictOption.sync="initialOption"，放不到initialValue去
<j-dict-select-tag type="list"   :dictOption.sync="initialOption"    v-decorator="['grade', validatorRules.grade]" :trigger-change="true" dictCode="grade" placeholder="请选择等级"/>

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinwu-yang** [comment]
在下方validatorRules中设置 initialValue，我是这么做的这样可以获取到对应的字典值

**Comment by lsqGitHub716** [comment]
v-decorator方式  建议使用 this.form.setFieldsValue({name: '设置值'}) 去赋值
