### ISSUE TITLE
抽屉式界面下方有一点奇怪的显示

### ISSUE THREAD

**Issue by archorfight** [zhangdaiscott/jeecg-boot#1532]
##### 版本号：

2.1.3
##### 问题描述：
角色管理界面 点更多 授权，弹出的界面下方的遮罩不美观，里面的按钮也可以点击。该怎么去掉这部分

##### 截图&代码：
![QRY$LXB87IPJ%2SO W0(`0E](https://user-images.githubusercontent.com/16200346/89014573-465fa200-d348-11ea-9a4b-f714bbc69074.png)

**Comment by jspang582** [comment]
css样式去掉

**Comment by archorfight** [comment]
> css样式去掉
用谷歌浏览器  F12   鼠标点不到那部分，不知道这里的css在哪。

**Comment by jspang582** [comment]
![image](https://user-images.githubusercontent.com/68464475/89137995-9ae36700-d56c-11ea-858b-ca645a52526c.png)

**Comment by archorfight** [comment]
谢谢，去掉就可以了。

**Comment by zjafei** [comment]
:wrapStyle="{ height: 'calc(100% - 108px)', overflow: 'auto', paddingBottom: '108px' }"
