### ISSUE TITLE
实体内有多个表字典注解的时候报错，导致翻译失败

### ISSUE THREAD

**Issue by Domain711** [zhangdaiscott/jeecg-boot#1534]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/34387432/89098622-d3bff680-d41b-11ea-865d-0f3d6a7faf5c.png)
![image](https://user-images.githubusercontent.com/34387432/89098642-f81bd300-d41b-11ea-921f-8e12195001e8.png)
package org.jeecg.modules.fish.artical.entity;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.math.BigDecimal;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;
import org.jeecgframework.poi.excel.annotation.Excel;
import org.jeecg.common.aspect.annotation.Dict;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * @Description: 文章信息表
 * @Author: Mr.Qin
 * @Date:   2020-07-31
 * @Version: V1.0
 */
@Data
@TableName("fish_artical")
@Accessors(chain = true)
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="fish_artical对象", description="文章信息表")
public class FishArtical implements Serializable {
    private static final long serialVersionUID = 1L;

	/**主键*/
	@TableId(type = IdType.ASSIGN_ID)
    @ApiModelProperty(value = "主键")
    private java.lang.String id;
	/**文章栏目*/
	@Excel(name = "文章栏目", width = 15)
    @ApiModelProperty(value = "文章栏目")
    @Dict(dictTable = "fish_artical_item",dicCode = "id",dicText = "name")
    private java.lang.String articalItem;
	/**文章标题*/
	@Excel(name = "文章标题", width = 15)
    @ApiModelProperty(value = "文章标题")
    private java.lang.String title;
	/**文章话题*/
	@Excel(name = "文章话题", width = 15)
    @Dict(dictTable = "fish_topic",dicCode = "id",dicText = "topic_name")
    @ApiModelProperty(value = "文章话题")
    private java.lang.String topic;
	/**文章内容*/
	@Excel(name = "文章内容", width = 15)
    @ApiModelProperty(value = "文章内容")
    private java.lang.String content;
	/**状态*/
	@Excel(name = "状态", width = 15, dicCode = "valid_status")
	@Dict(dicCode = "valid_status")
    @ApiModelProperty(value = "状态")
    private java.lang.String status;
	/**创建人*/
    @ApiModelProperty(value = "创建人")
    private java.lang.String createBy;
	/**创建日期*/
	@JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty(value = "创建日期")
    private java.util.Date createTime;
	/**更新人*/
    @ApiModelProperty(value = "更新人")
    private java.lang.String updateBy;
	/**更新日期*/
	@JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty(value = "更新日期")
    private java.util.Date updateTime;
	/**所属部门*/
    @ApiModelProperty(value = "所属部门")
    private java.lang.String sysOrgCode;
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
经测试无问题

**Comment by Domain711** [comment]
有问题的，你看看issue下面，有人跟我提了同样的问题，你缓存用了同一个，key, 一个是返回string, 一个是返回list编辑的时候就报错了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wangshuai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月7日(星期五) 晚上7:07
收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;&quot;Domain711&quot;<691386631@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 实体内有多个表字典注解的时候报错，导致翻译失败 (#1534)

**Comment by Domain711** [comment]
![image](https://user-images.githubusercontent.com/34387432/89698835-e83d4b00-d955-11ea-8e1a-d4d14f191f41.png)
请看问题#1522
