### ISSUE TITLE
Modal弹出框界面，如何修改下方的两个按钮【取消】，【确定】

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#1535]
##### 版本号：

2.2.1
##### 问题描述：
![image](https://user-images.githubusercontent.com/59654718/89125272-e87db680-d50f-11ea-9a1a-55fa057fe3fe.png)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59654718/89125308-2aa6f800-d510-11ea-88cd-b05a302fd448.png)
![image](https://user-images.githubusercontent.com/59654718/89125327-3c889b00-d510-11ea-979b-7781cda797d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://www.antdv.com/components/modal-cn/#components-modal-demo-customize-footer-buttons-props
