### ISSUE TITLE
jeecgboot前端代码如何调整可以使表格内数据表头都居中 ，表内非数字类型的数据靠左 ，表内数字类型的数据靠右

### ISSUE THREAD

**Issue by Admin2020-qixia** [zhangdaiscott/jeecg-boot#1536]
版本号：2.1.4

 问题描述：
jeecgboot前端代码如何调整可以使表格内数据表头都居中 ，表内非数字类型的数据靠左 ，表内数字类型的数据靠右。
目前表内数据位置与表头的数据位置是一致的，表头数据居中，表内的数据都居中

 截图&代码：
![图片](https://user-images.githubusercontent.com/62987999/89138821-69b86600-d56f-11ea-83fc-dca84f1ec872.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by huyaru** [comment]
online表单开发未开源，现有样式为通用样式，如果有特殊需要，可以生成代码后，根据自己的需求更改样式。如果大家遇见相同问题的人比较多，该问题超过多少人关注后，作者应该会考虑在下一版本中进行更新。（我也有这个需求）
