### ISSUE TITLE
漏洞：其他部门可以新增管理员角色

### ISSUE THREAD

**Issue by wushu037** [zhangdaiscott/jeecg-boot#1538]
##### 版本号：
2.2.1

##### 问题描述：
下属部门可以新增管理员角色

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61787040/89144377-27e3eb80-d580-11ea-8dd1-65d197d12bb4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by huyaru** [comment]
分配角色的权限，要给到管理员等高级管理级别，从而人为控制角色分配。如果把管理员角色特殊定义，会降低通用性。

**Comment by lokbun** [comment]
> 分配角色的权限，要给到管理员等高级管理级别，从而人为控制角色分配。如果把管理员角色特殊定义，会降低通用性。

这个确实有漏洞，只要有部门管理权限就可以自己新建一个用户分配最高权限的角色，问题就是出在这里并没有获取部门角色而是获取全局角色。

**Comment by zhangdaiscott** [comment]
收录

**Comment by GordonHuangYong** [comment]
我直接把这个字段隐藏了.部门管理员, 有部门角色就够了.没必要分配全局角色.

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
