### ISSUE TITLE
jeecg-boot-module-system中启动类JeecgApplication

### ISSUE THREAD

**Issue by Ray-Sir-Like** [zhangdaiscott/jeecg-boot#154]
版本2.0
jeecg-boot-module-system中启动类JeecgApplication,

因为已经使用@SpringBootApplication,

这个注解等价于以默认属性使用@Configuration，@EnableAutoConfiguration和@ComponentScan,

个人认为,冗余注解@EnableAutoConfiguration应该予以删除,如有理解错误,还请指正

**Comment by zhangdaiscott** [comment]
可以去掉，我们冗余是方便用户做个性化设置
