### ISSUE TITLE
配置数据权限为包含时，条件为多个时，sql语句报错

### ISSUE THREAD

**Issue by huyaru** [zhangdaiscott/jeecg-boot#1541]
##### 截图&代码：
![I8T77YC DW$FW%9Z7T3C80](https://user-images.githubusercontent.com/39981456/89247896-e9facc00-d640-11ea-89af-6d0ef62e08b1.png)
![图片](https://user-images.githubusercontent.com/39981456/89247927-0139b980-d641-11ea-8d2b-2445e3ee14d4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
