### ISSUE TITLE
数据权限配置冲突问题

### ISSUE THREAD

**Issue by huyaru** [zhangdaiscott/jeecg-boot#1542]
##### 版本号：
2.2.1

##### 问题描述：
用户多角色时，不同角色数据权限配置，导致权限冲突，
例：部门管理角色，拥有查看部门内所有数据权限，
       普通用户，拥有查看属于自己的数据权限，
       当用户同时拥有两种权限时，权限冲突，导致只能显示最低级别的权限控制

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前的确是按照授权生效的方式进行设计的，数据权限是授权了，才生效

**Comment by fjchenxd** [comment]
> 目前的确是按照授权生效的方式进行设计的，数据权限是授权了，才生效

我也遇到同样的困惑，用户授权多个角色，每个角色的自己的条件限制，之间是同时满足的关系，但不同角色之前应该是或的关系，也就是角色1： （角色1条件1 and 角色1条件2 and 角色1条件3）or （角色2条件1 and 角色2条件2 and 角色2条件3）

**Comment by ChengPengYang** [comment]
@fjchenxd 这个问题解决了吗，我也遇到同样的问题了
