### ISSUE TITLE
控件默认值#{sysUserName}无法显示

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1544]
##### 版本号：
2.2.1

##### 问题描述：
控件默认值#{sysUserName}无法显示，且报错如下

##### 截图&代码：
online中新增加表，在页面属性—控件默认值，中写#{sysUserName}，在功能测试中打开无法显示，并报错

![11](https://user-images.githubusercontent.com/59555469/89260255-81bae300-d65e-11ea-8fcc-6b1865eed421.png)

![12](https://user-images.githubusercontent.com/59555469/89260274-88e1f100-d65e-11ea-9824-31f203799ed0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的是那个版本？

**Comment by shrto** [comment]
> 你的是那个版本？

2.2.1

**Comment by zhangdaiscott** [comment]
类似问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1639

此问题确认存在，正在调查中

**Comment by zhangdaiscott** [comment]
已经解决，下个版本2.3发布
