### ISSUE TITLE
富文本编辑器样式不显示

### ISSUE THREAD

**Issue by jiawenzhe** [zhangdaiscott/jeecg-boot#1546]
##### 版本号：

2.2.1
##### 问题描述：

富文本编辑器和markdown都不显示，页面展示就是一个文本域
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/log
优化前端打包js文件太大问题（减小online依赖大小，暂时取消online的富文本和markdown的支持）
