### ISSUE TITLE
支持自定义sql 查询条件 引入#{sys_user_code}  等用户查询条件 能否匹配上权限数据

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1547]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/89262822-c9436e00-d662-11ea-8b89-53449e56bcd9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块暂时不支持

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
