### ISSUE TITLE
JDate控件问题

### ISSUE THREAD

**Issue by wb7131642** [zhangdaiscott/jeecg-boot#1549]
##### 问题描述：JDate控件导出代码时候默认当前日期没有了，如何在新增或修改From代码里面加入默认日期
         <a-col :span="24">
            <a-form-item label="日期" :labelCol="labelCol" :wrapperCol="wrapperCol">
              <j-date placeholder="请选择日期" v-decorator="['date']" :trigger-change="true" style="width: 100%"/>
            </a-form-item>
          </a-col>

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前代码生成器不支持，需要手工加入
