### ISSUE TITLE
version2.0添加@Cacheable(cacheNames="FullDiscountRule", key="#rule.id")报错

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#155]
java.lang.IllegalArgumentException: Cannot find cache named 'FullDiscountRule' for Builder[public java.util.List org.jeecg.modules.storage.biz.promotion.service.impl.FullDiscountRuleServiceImpl.queryFullRuleList(org.jeecg.modules.storage.biz.promotion.entity.FullDiscountRule)] caches=[FullDiscountRule] | key='#rule.basicInfoId,#rule.storeCode' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'

**Comment by zhangdaiscott** [comment]
应该你用法问题，我测试没问题
![image](https://user-images.githubusercontent.com/3162115/58455911-6ba9bc80-8155-11e9-8f3d-54b9e21406b5.png)
