### ISSUE TITLE
localhost和服务器访问的差异性

### ISSUE THREAD

**Issue by xuwei999** [zhangdaiscott/jeecg-boot#1550]
##### 版本号：
2.2.1

##### 问题描述：
将jeecg-boot部署到服务器上，进行Online表单开发，页面上新建表，同步数据库就会报错

##### 截图&代码：

![error](https://user-images.githubusercontent.com/44250182/89375049-6ebc1780-d71f-11ea-8543-1adf257ad0e2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1

65
