### ISSUE TITLE
online表单开发 富文本问题

### ISSUE THREAD

**Issue by xuwei999** [zhangdaiscott/jeecg-boot#1552]
##### 版本号：
2.2.1

##### 问题描述：
进行online表单开发的时候，设置了富文本属性，但是富文本功能没有体现

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44250182/89383738-99ae6780-d72f-11ea-90a9-b9b101c78449.png)

![image](https://user-images.githubusercontent.com/44250182/89383776-acc13780-d72f-11ea-9dc6-b72d5d47ca98.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1546
