### ISSUE TITLE
代码生成功能报错

### ISSUE THREAD

**Issue by yangylGit** [zhangdaiscott/jeecg-boot#1553]
##### 截图&代码：
![微信截图_20200805153621](https://user-images.githubusercontent.com/38969228/89384956-7f758900-d731-11ea-9efb-c69a70663ff8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1684391

**Comment by yangylGit** [comment]
我现在是用docker发布的项目，我也按照文档上方法把模板配置发在和jar包同一个目录，但是还是报一样的错
&nbsp;

水能载舟亦能覆舟！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 中午11:02
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "提灯寻梦"<1440681835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 代码生成功能报错 (#1553)





 
Closed #1553.
 
&mdash;

**Comment by mofangoing** [comment]
> 我现在是用docker发布的项目，我也按照文档上方法把模板配置发在和jar包同一个目录，但是还是报一样的错 &nbsp; 水能载舟亦能覆舟！ &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JEECG开源社区"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 中午11:02 收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 抄送: "提灯寻梦"<1440681835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [zhangdaiscott/jeecg-boot] 代码生成功能报错 (#1553) Closed #1553. &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也遇到的同样的问题，请问你后来解决了吗？
