### ISSUE TITLE
文档提示的权限管理和授权下载最新版找不到

### ISSUE THREAD

**Issue by fei550815954** [zhangdaiscott/jeecg-boot#1559]
##### 版本号：

最新版
##### 问题描述：
刚转后端自学，也不是太懂，看着文档学习的，到按钮权限授权，20200727这个很简单，但是文档图片显示的和最新下载的不一样，也不是大问题可能我操作问题

##### 截图&代码：

![QQ截图20200806172701](https://user-images.githubusercontent.com/16751372/89515860-42c99080-d80a-11ea-8a51-82bf5830934b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
暂未发布到最新版中
