### ISSUE TITLE
单表代码生成现在会导致多生成一个</template>

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1561]
##### 版本号：
2.2.1

##### 问题描述：
![image](https://user-images.githubusercontent.com/12267648/89602756-06de0c00-d89a-11ea-8f8c-bcc834c266ef.png)

单表代码生成现在会导致多生成一个template结束标签

po_index == 2 证明至少是三个元素才会生成template开始标签

下面的判断应该是 if (columns?size>2)
或者是上面的 po_index == 1 且 满足一定执行过上述生成template开始标签的分支行呀

我生成的代码 三个搜索条件都满足分支1了，这个时候根本不会到分支2

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12267648/89600090-c67b8f80-d893-11ea-90cd-4beb5a72c7c7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
这代码你自己改过吧，我没找到和这个源码一样的文件

**Comment by xinwu-yang** [comment]
org.jeecgframework.boot.codegenerate:1.2.0 后面不在维护了吗？

**Comment by zhangdaiscott** [comment]
多个查询条件，请用online

**Comment by lsqGitHub716** [comment]
目前测试未发现您说的问题，您是否修改过默认的配置文件
