### ISSUE TITLE
MybatisPlusException: Failed to process, please exclude the tableName or statementId.

### ISSUE THREAD

**Issue by sywh1234-git** [zhangdaiscott/jeecg-boot#1564]
##### 问题描述：升级到最新版2.2.1之后，发现mybatis-plus启用了多租户功能，导致原有的sql里有mysql关键词时报错，我使用的是sql注解，sql里有select sum(xx),count(xx)之类的都报MybatisPlusException: Failed to process, please exclude the tableName or statementId.这个错，我把MybatisPlusConfig还原到先前那个版本，错误就没有了。
我在mapper层的sql上加上注解 SqlParse(filter=true) 错误也没有了。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/45229537/89648757-46384700-d8f2-11ea-9c7a-41cb9b5045f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sywh1234-git** [comment]
报错的内容如下：我估计是出现了括号的问题，如sum(xx),count(xx)

Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:137)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:62)
	... 154 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 11.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"

**Comment by tygithub1** [comment]
你是怎么升级的

**Comment by sywh1234-git** [comment]
代码覆盖升级到2.2.1，执行了2.2.0升级到2.2.1的sql

**Comment by zhangdaiscott** [comment]
下载当前代码看看是否存在此问题，你自己升级的，我们无法判断

**Comment by zhangdaiscott** [comment]
无继续反馈，此问题先关闭了，因为在官方仓库是没这个问题的

**Comment by xplx** [comment]
问题还是存在，自定义复杂点的sql就接续出错，多租户使用出现的情况。
