### ISSUE TITLE
Online表单开发，普通同步报错

### ISSUE THREAD

**Issue by vip-liutao** [zhangdaiscott/jeecg-boot#1565]
##### 问题描述：
数据库mysql使用root账号开发
数据库中其他数据库存在同名表，导致普通同步报错，强制同步能成功

原因是获取到了其他库下的同名表，来比对现有的Online表单，希望能修复
简单的解决方式是不要使用root账号开发，新建用户仅授权当前库的权限，使用新建用户能解决这个BUG

**Comment by tygithub1** [comment]
是我没跟上mysql的技术更新步伐吗？请问是什么版本的mysql？一个账号还能链接多个数据库？你连接地址是什么

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
