### ISSUE TITLE
Unknown column 'field_value_rule_code' in 'field list'

### ISSUE THREAD

**Issue by yunlaitong** [zhangdaiscott/jeecg-boot#1566]
##### 问题描述：代码生成器新建表时发生错误
 Unknown column 'field_value_rule_code' in 'field list'

##### 截图&代码：
![image](https://user-images.githubusercontent.com/63142556/89707030-67a23d00-d99d-11ea-9105-a16f833daeb4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本太老了，是不是缺字段
