### ISSUE TITLE
登录的验证码key（checkKey）是怎么生成的呢

### ISSUE THREAD

**Issue by fuzhiyou-69** [zhangdaiscott/jeecg-boot#1569]
##### 版本号：
2.2.1

##### 问题描述：

登录的验证码key是怎么生成的呢

##### 截图&代码：

![image](https://user-images.githubusercontent.com/57322717/89748142-5750a600-daf4-11ea-8b0e-e7e369394016.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
通过这个接口获取验证码
org.jeecg.modules.system.controller.LoginController#randomImage

![image](https://user-images.githubusercontent.com/3162115/91012067-083c6200-e618-11ea-881e-e49d72840a93.png)
