### ISSUE TITLE
切换TAB标签能不能设置不要每次都重新刷新页面

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1571]
##### 问题描述：
切换TAB标签能不能设置不要每次都重新刷新页面

##### 截图&代码：
![00810110509](https://user-images.githubusercontent.com/54636793/89749322-cf6d9a80-daf9-11ea-800f-ca43114d8d25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
菜单配置，设置缓存就可以
![image](https://user-images.githubusercontent.com/3162115/91011964-d75c2d00-e617-11ea-9de5-a4273a5e8133.png)
