### ISSUE TITLE
固定查询传参格式优化建议

### ISSUE THREAD

**Issue by sorrythat** [zhangdaiscott/jeecg-boot#1575]
##### 版本号：
jeecg-boot 开源版 2.2.1

##### 问题描述：
啥时候可以考虑把
@RequestParam(name = "pageNo", defaultValue = "1") Integer pageNo, @RequestParam(name = "pageSize", defaultValue = "10") Integer pageSize  
这么长的东西变成Query query  com.baomidou.mybatisplus.core.conditions.query.Query 
反正都已经用了mybatisplus
使用Query query不仅效果一样的可以实现，传参格式也优雅美观，代码还少很多

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17540853/89767816-41aba280-db2d-11ea-8bee-38aa4acdc874.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
明确参数更好，方便服务化调用
