### ISSUE TITLE
前端页面放开个人页后console报错

### ISSUE THREAD

**Issue by JesseHeisenberg** [zhangdaiscott/jeecg-boot#1577]
##### 版本号：
2.2.0

##### 问题描述：
前端页面放开个人页菜单后，console报堆栈溢出错误，屏蔽个人页后设置新的菜单并添加聚合路由，同样出现堆栈溢出问题

##### 截图&代码：

![abdbO1.jpg](https://s1.ax1x.com/2020/08/10/abdbO1.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个路由页面？

**Comment by tanpenggood** [comment]
已修复。将在下个版本更新。

解决方案：[https://www.yuque.com/jeecg-os/index/nscgdt#739c055c](https://www.yuque.com/jeecg-os/index/nscgdt#739c055c)
