### ISSUE TITLE
修改主题色后部分颜色没有改变

### ISSUE THREAD

**Issue by heyuxxxuan** [zhangdaiscott/jeecg-boot#1579]
##### 截图&代码：
![微信截图_20200811143507](https://user-images.githubusercontent.com/48618822/89865315-13d36600-dbe0-11ea-8f08-32fb50e50214.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.21 应该解决了这个问题
