### ISSUE TITLE
代码生成popup组件无效

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1580]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/89869706-4fbdf980-dbe7-11ea-801b-00256beb3351.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jwcjf** [comment]
![image](https://user-images.githubusercontent.com/18321599/89879920-31abc580-dbf6-11ea-91e7-cf7e8ed9d00a.png)

**Comment by zhangdaiscott** [comment]
生成后的代码截图看下

**Comment by tanpenggood** [comment]
`BUG未复现`，测试结果正常

请重点关注你的前端项目是否已将`JPopup`注册为全局组件

`main.js`
```javascript
import JeecgComponents from '@/components/jeecg/index'
Vue.use(JeecgComponents)
```

Popup控件使用文档 [http://doc.jeecg.com/1273877](http://doc.jeecg.com/1273877)
