### ISSUE TITLE
谷歌浏览器开发者模式下,点击屏幕调试后左侧菜单栏收起，且折叠图标失效

### ISSUE THREAD

**Issue by huyu18** [zhangdaiscott/jeecg-boot#1584]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/45663272/89979060-6f195d00-dca1-11ea-9539-377af9d30fee.png)
![image](https://user-images.githubusercontent.com/45663272/89979135-9d973800-dca1-11ea-8b30-29264bcca025.png)
![image](https://user-images.githubusercontent.com/45663272/89979164-b3a4f880-dca1-11ea-862f-55fd8d038b3a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经解决下个版本发布

**Comment by muYouGou** [comment]
将 \src\components\page\GlobalLayout.vue 第5行 v-if 改成v-show 即可 23行添加 v-show="device === 'desktop'" 即可就该这个bug

**Comment by muYouGou** [comment]
将 \src\components\page\GlobalLayout.vue 第5行 v-if 改成v-show 即可 23行添加 v-show="device === 'desktop'" 即可就该这个bug
