### ISSUE TITLE
online生成的列表问题

### ISSUE THREAD

**Issue by jiangjiacheng** [zhangdaiscott/jeecg-boot#1587]
##### 截图&代码：
当前情况：
![image](https://user-images.githubusercontent.com/22400199/89987002-eb1aa180-dcaf-11ea-8fa0-20f247fb4d73.png)

期望：
![image](https://user-images.githubusercontent.com/22400199/89986681-78a9c180-dcaf-11ea-87fc-a81c7a2a9b8c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成完，自己手工调整
