### ISSUE TITLE
JEditableTable的disabledRows如何配置，无法禁用一行

### ISSUE THREAD

**Issue by SeptemberJ** [zhangdaiscott/jeecg-boot#1588]
##### 版本号：
2.2.0

##### 问题描述：

JEditableTable的disabledRows如何配置，文档没有该示例，如何配置能禁用某一行
##### 截图&代码：
<j-editable-table
          ref="editable"
          :loading="ywOrderSkrecordTable.loading"
          :columns="ywOrderSkrecordTable.columns"
          :dataSource="ywOrderSkrecordTable.dataSource"
          :rowSelection="false"
          :disabledRows="ywOrderSkrecordTable.disabledRows"
          :actionButton="true">
          <template v-slot:del="props">
            <a-button v-show="props.index != 0" type="link" block @click="handleDelete(props)">删除</a-button>
          </template>
        </j-editable-table>

ywOrderSkrecordTable: {
        ...
        disabledRows: {},
}

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/90093530-676bbe00-dd5e-11ea-8cc2-cc32be71f1c1.png)
