### ISSUE TITLE
在线演示版本中，报表设计中的报表设计器进入会提示无token异常

### ISSUE THREAD

**Issue by yuhang003** [zhangdaiscott/jeecg-boot#1590]
##### 版本号：
2.2.1

##### 问题描述：
在线演示版本中，报表设计中的报表设计器进入会提示无token异常，但是明明刚登录进来

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55573743/90083144-5b730280-dd44-11ea-97d9-5359cd0fb721.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
了解，尽快重新发布
