### ISSUE TITLE
自定义了消息对象后，调用sendMoreMessage获取到的session为null，请问什么原因

### ISSUE THREAD

**Issue by lulusoft** [zhangdaiscott/jeecg-boot#1591]
##### 问题描述：
在发布消息里添加了消息通告对象CLASS,并对应获取到了String[]的用户ids，调用webSocket.sendMoreMessage时总是session为null，导致无法发送消息。
（而消息对象为UESR调用了同样的webSocket.sendMoreMessage没有问题）
请问是什么原因，谢谢！

##### 截图&代码：
......
if(sysAnnouncement.getMsgType().equals(CommonConstant.MSG_TYPE_CLASS)) {
						String userClass = sysAnnouncement.getUserClasss();
						String[] userClasss = userClass.substring(0, (userClass.length())).split(",");
						//通过班级获取用户信息并发送消息
						 String tempuserIds ="";
						for (int i=0;i<userClasss.length;i++) {
							 List<Map<String,Object>> userIds = nubAppAnnountUserService.getUserIds(userClasss[i]);
							 for(int j=0;j<userIds.size();j++) {
								 String tempuserId = (String)userIds.get(j).get("USERID");
								 tempuserIds+=tempuserId+",";
							 }
						}
						String[] userIds =tempuserIds.substring(0, (tempuserIds.length()-1)).split(",");
						JSONObject obj = new JSONObject();
						obj.put(WebsocketConst.MSG_CMD, WebsocketConst.CMD_USER);
						obj.put(WebsocketConst.MSG_ID, sysAnnouncement.getId());
						obj.put(WebsocketConst.MSG_TXT, sysAnnouncement.getTitile());
						webSocket.sendMoreMessage(userIds, obj.toJSONString());
					}
......

**Comment by zhangdaiscott** [comment]
自己写代码，我们无法判断

**Comment by lulusoft** [comment]
自己代码片段和系统自带的都是调用了org.jeecg.modules.message.websocket下的sendMoreMessage(String[] userIds, String message)
格式也一样，而且userIds也传递过去了，就是不解为啥自己调用获取 Session session = sessionPool.get(userId);为null
请问这个 session 是什么时候set的？或者哪里还需要设置？
