### ISSUE TITLE
从2.2.0 升级 2.2.1后   j-modal style 属性无法指定BUG

### ISSUE THREAD

**Issue by qiuyan12** [zhangdaiscott/jeecg-boot#1592]
##### 版本号：
version:2.2.1

##### 问题描述：
将原来的 2.2.0  升级到 2.2.1 后, a-model 的属性无法使用了. 

##### 截图&代码：
![2 2 0](https://user-images.githubusercontent.com/29660289/90086248-95480700-dd4c-11ea-8552-5ba5ca1b912b.png)

![2 2 1](https://user-images.githubusercontent.com/29660289/90086251-98db8e00-dd4c-11ea-9bcb-4c2fa2df8a8b.png)

![代码](https://user-images.githubusercontent.com/29660289/90086305-b6105c80-dd4c-11ea-8615-0a83128ecdf7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是antd-vue的样式变化，自己改把
