### ISSUE TITLE
主子表中，子表如何添加默认数据

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1593]
##### 版本号：
2.2.1

##### 问题描述：
主子表中，点击新增，子表如何带出几行默认数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59555469/90088383-62ecd880-dd51-11ea-977f-e7c95810eb35.png)

子表如何添加默认数据

![11](https://user-images.githubusercontent.com/59555469/90088538-c0812500-dd51-11ea-8536-0c9efb54bdd6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
试试js增强
