### ISSUE TITLE
从数据库导入表单找不到在数据库新建的表

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1595]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18321599/90090768-713df300-dd57-11ea-9291-2febe8214106.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有一些特殊前缀，给过滤了

**Comment by jwcjf** [comment]
我用 jeecg_前缀也不行，请问有存在哪个表格吗
