### ISSUE TITLE
类型表查找字典项时报错java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by hunji** [zhangdaiscott/jeecg-boot#1596]
##### 版本号：
2.2.1

##### 问题描述：
在有关联字典表的编辑页面中，字典项的内容不能加载出来，报错java.lang.String cannot be cast to java.util.List。
原因是，使用j-tree-select在方法loadItemByCode时会把结果缓存起来，使用的key:SYS_DICT_TABLE_CACHE和加载字典数据的key重复了，会导致返回的结果类型不匹配。新增一个key进行保存即可。

##### 截图&代码：

![QQ截图20200813115305](https://user-images.githubusercontent.com/6678566/90092464-97659200-dd5b-11ea-9483-486b2a8c6fd4.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by HanYaodong** [comment]
一样的问题 #1522，2.2.1版本引入的

**Comment by tanpenggood** [comment]
注意 redis key 的前缀及分组，避免 key 冲突
