### ISSUE TITLE
quartz数据表大小写不统一

### ISSUE THREAD

**Issue by cmxpanda** [zhangdaiscott/jeecg-boot#1599]
##### 版本号：
Jeecg  Boot Version: 2.2.1

##### 问题描述：
为什么quartz的数据表是小写，代码中是大写？请问这么做的意图是什么？如果不做数据库不区分大小的话，会报错找到不数据表。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
设置不区分大小写

**Comment by gsdukbh** [comment]
> 设置不区分大小写

不区分大小写？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
你认真的

**Comment by gsdukbh** [comment]
> 这不是很正常嘛？自己数据库配置设置忽略大小写就可以了！

不解决问题 解决提出问题的人？

**Comment by galaxist** [comment]
哪怕你有一丁点的数据库管理常识，就知道数据库配置里表名和字段名要忽略大小写！

**Comment by gsdukbh** [comment]
> 哪怕你有一丁点的数据库管理常识，就知道数据库配置里表名和字段名要忽略大小写！

是是是您说的对

**Comment by galaxist** [comment]
那必须的！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by cmxpanda** [comment]
别和大神犟了，打他回复我设置不区分大小写，我就放弃了反抗……



---原始邮件---
发件人: "Lee JiaWei"<notifications@github.com&gt;
发送时间: 2020年9月7日(周一) 下午5:02
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"cmxpanda"<471649830@qq.com&gt;;
主题: Re: [zhangdaiscott/jeecg-boot] quartz数据表大小写不统一 (#1599)




  
哪怕你有一丁点的数据库管理常识，就知道数据库配置里表名和字段名要忽略大小写！
  
是是是您说的对

**Comment by galaxist** [comment]
@cmxpanda @gsdukbh 你们是不是大学刚毕业还处在把数据库导论，设计范式当宝典，没事，在社会上多滚打几年就知道，数据库表名和字段名都忽略大小写才是常态了。

**Comment by gsdukbh** [comment]
> @cmxpanda @gsdukbh 你们是不是大学刚毕业还处在把数据库导论，设计范式当宝典，没事，在社会上多滚打几年就知道，数据库表名和字段名都忽略大小写才是常态了。

数据库导论，难道不是宝典吗？ 你当初学习数据不是用这个？难道是你比那些发明数据库作者还有厉害？

**Comment by limengning** [comment]
PostgreSQL如何解决

**Comment by gsdukbh** [comment]
> PostgreSQL如何解决
不推荐使用 jeecg-boot
