### ISSUE TITLE
打包发布到非站点根目录后404问题

### ISSUE THREAD

**Issue by gzzlovezyx** [zhangdaiscott/jeecg-boot#16]
我使用yarn run build打包后，把dist放到非站点根目录http://localhost/dist/后，访问发现css、js文件都是http://localhost/css/app.4dc5f5d2.css， 报404，应该怎么设置呢？

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=342634

**Comment by gzzlovezyx** [comment]
晕，问题没解决就close了，我想问的是发布到非根目录，需要有上下文的如http://localhost/dist/或http://localhost/jeecg-vue/这种，你发的链接是发布到根目录的。

**Comment by Tech--man** [comment]
同存在此问题
