### ISSUE TITLE
新增的时候希望不要弹框 做成table切换页面

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#160]
功能如下图

![image](https://user-images.githubusercontent.com/5210084/58523967-07403900-81f9-11e9-825d-2ce82d254b24.png)

**Comment by zhangdaiscott** [comment]
采用路由跳转
`this.$router.push({ path: '/online/cgformTreeList/' + rd.id })`


![image](https://user-images.githubusercontent.com/3162115/58630745-ecfa7e00-8312-11e9-90cc-666d6a4a3ddc.png)


![image](https://user-images.githubusercontent.com/3162115/58630731-e5d37000-8312-11e9-85f1-607bcb38b3de.png)

**Comment by shaowen** [comment]
直接在list页面不起作用
![image](https://user-images.githubusercontent.com/5210084/61025297-dbf95e00-a3e2-11e9-8f74-b3f3a66d33cb.png)

![image](https://user-images.githubusercontent.com/5210084/61025267-c2581680-a3e2-11e9-88eb-8b12bfab69fb.png)
