### ISSUE TITLE
导入导出数据字典无法转换

### ISSUE THREAD

**Issue by missKomorebi** [zhangdaiscott/jeecg-boot#1603]
##### 版本号：

2.2.0 autopoi 1.1.1
##### 问题描述：
sys_dict_item.item_value  命名规则为下划线  **_**_**   数据字典无法转换
例如：
dicCode ='sex'  iitem_text='男'  item_value = 'sex_man'
导入导出  字典查询数据结构为   男_sex_man,猜测转换已下划线分割，数据解析只能匹配sex，无法匹配为sex_man

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
数据字典不支持带下划线

**Comment by missKomorebi** [comment]
强！
