### ISSUE TITLE
打包为war包后运行，导入xlsx表格速度慢

### ISSUE THREAD

**Issue by kaedesatosi** [zhangdaiscott/jeecg-boot#1606]
##### 版本号：
2.2.1

##### 问题描述：
使用代码生成器生成一张表的代码，将项目打包为war包，使用`java -jar xxx.war`运行。
在生成的前端页面上使用导入功能导入只有一条数据的xlsx表格，平均耗时2-3秒，机器差的话在10-20秒。

##### 截图&代码：

表格如下：
![problem3 (2)](https://user-images.githubusercontent.com/35375573/90237427-d7f60600-de56-11ea-935b-cbf8641010cb.png)

导入xls很快，xlsx很慢。
![problem](https://user-images.githubusercontent.com/35375573/90234165-cc541080-de51-11ea-9ece-12906f3b9008.png)

`ExcelImportUtil.importExcel()`消耗了大量时间。
![problem3](https://user-images.githubusercontent.com/35375573/90235925-a54b0e00-de54-11ea-996b-3344a15e5cfe.png)

打包为jar包运行或者使用ide运行速度正常。
![problem2](https://user-images.githubusercontent.com/35375573/90234696-a8dd9580-de52-11ea-8b3e-d9ae7698b5ff.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
war包请用tomcat跑试试

**Comment by kaedesatosi** [comment]
> war包请用tomcat跑试试

tomcat跑没问题，只是奇怪在war包下为什么会有问题。
创建一个新的springboot项目，再导入easypoi，使用ExcelImportUtil.importExcel()导入表格进行测试，
打包为war包后速度就是正常的，都在几十毫秒以内。

**Comment by kaedesatosi** [comment]
> war包请用tomcat跑试试

tomcat跑没问题，只是奇怪在war包下为什么会有问题。
创建一个新的springboot项目，再导入easypoi，使用ExcelImportUtil.importExcel()导入表格进行测试，
打包为war包后速度就是正常的，都在几十毫秒以内。

**Comment by zhangdaiscott** [comment]
报错没有

**Comment by kaedesatosi** [comment]
> 报错没有

没有报错，就是速度慢。

**Comment by zhangdaiscott** [comment]
有详细日志吗
