### ISSUE TITLE
2.2.1 online代码生成   前端查询区域未生成

### ISSUE THREAD

**Issue by ggjess** [zhangdaiscott/jeecg-boot#1609]
##### 问题描述：
拉取的master代码,
online表单生成的前端代码,  查询区域未生成,无论我怎么配置,换回2.2.0版本正常,我看有人提了一个online表单设置,树结构查询条件无法生成的问题,请查证,是否存在此问题

##### 截图&代码：

    <div class="table-page-search-wrapper">
      <a-form layout="inline" @keyup.enter.native="searchQuery">
        <a-row :gutter="24">
        </a-row>
      </a-form>
    </div>

**Comment by zhangdaiscott** [comment]
用的是那套模板？用的是树列表还是普通列表？  请详细描述

**Comment by ggjess** [comment]
@zhangdaiscott  都试了,不行,我更换为2.2.0  正常恢复正常

**Comment by zhangdaiscott** [comment]
写个重现步骤

**Comment by lsqGitHub716** [comment]
您好，目前测试多套模板，暂未发现查询区域未盛情的情况，建议您写一个具体的操作步骤截图
