### ISSUE TITLE
小需求：一对多erp风格 如何通过权限控制显示子表

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#161]
![image](https://user-images.githubusercontent.com/5210084/58601434-433bd280-82bb-11e9-846d-55a1bfbb2032.png)

一对多erp风格 如何通过权限控制显示子表  

上图关联表 有客户信息 和 机票信息，针对不同人显示不同的子表  显示权限如何控制

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/58630504-30a0b800-8312-11e9-948a-30befce58403.png)

**Comment by zhangdaiscott** [comment]
采用路由跳转
`this.$router.push({ path: '/online/cgformTreeList/' + rd.id })`
![image](https://user-images.githubusercontent.com/3162115/58630678-bcb2df80-8312-11e9-91f8-965eaeb25d0e.png)
