### ISSUE TITLE
表单用自定义树形列表保存数据后，前端展示页面数据为空，后端报转换错误

### ISSUE THREAD

**Issue by Admin2020-qixia** [zhangdaiscott/jeecg-boot#1612]
版本号：2.2.1

 问题描述：表单用自定义树形列表保存数据后，前端展示页面数据为空，后端报转换错误

截图&代码：
    <j-tree-select
                v-decorator="['labelData', validatorRules.labelData]"
                :trigger-change="true"
                dict="dmp_label_class,label_class,id"
                pidField="pid"
                pidValue="0"
                hasChildField="has_child"
                @callback="popupCallback">
              </j-tree-select>

![图片](https://user-images.githubusercontent.com/62987999/90373728-f6e9d780-e0a4-11ea-96fa-e2a4eb1150a6.png)

![图片](https://user-images.githubusercontent.com/62987999/90374164-a626ae80-e0a5-11ea-8437-1c84b2f8369d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
问题描述过于简单，没有提供详细操作步骤，没有重现。
