### ISSUE TITLE
Online表单开发-代码生成-卡顿(ERP数据库存在较多表)

### ISSUE THREAD

**Issue by qiuyan12** [zhangdaiscott/jeecg-boot#1613]
##### 版本号：
2.2.1

##### 问题描述：
使用 Online表单开发-代码生成 进行代码生产时候, 由于erp数据库 存在的表格很多,读取的时候特卡顿.要等好久表才出来

问题点:现有的模式点开后就直接加载. 这样数据量很大,导致操作卡顿,效率很特(读一次表要10分钟+ 才加载好) 

建议:先按条件框栏位 模糊查询,在加载数据库

##### 截图&代码：
![Image 14](https://user-images.githubusercontent.com/29660289/90377815-1e43a300-e0ab-11ea-9b4a-0837faebb8f6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你这边数据库连接很慢吗，还是表很多，正常不会这么慢

**Comment by qiuyan12** [comment]
表很多 (2W张表). 
慢的情况 
由于 antd table 的表格在没有分页的情况,单页数据多,会造成整个页面的严重卡顿,

**Comment by zhangdaiscott** [comment]
做了一定的优化，下个版本发布
