### ISSUE TITLE
根据列表id跳转新页面，两个不同id页面之间的操作会相互影响

### ISSUE THREAD

**Issue by Shikyh** [zhangdaiscott/jeecg-boot#1617]
##### 问题描述：
根据列表id跳转新页面，两个不同id页面之间的操作会相互影响，如果要做到在页面1操作不影响页面2的话，需要怎么设置或者怎么修改代码

##### 截图&代码：

![image](https://user-images.githubusercontent.com/27214224/90484805-4560aa00-e169-11ea-8bf9-ac324a18d554.png)

![image](https://user-images.githubusercontent.com/27214224/90484874-5f01f180-e169-11ea-90e4-4ef722d57a17.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liupeng1991** [comment]
请问你解决这个问题了？ 我也是这个问题困扰了好久！因为会打开多个的窗口，如果有办法只打开一个窗口的话，倒是还没什么问题，但是会打开多个的窗口！

**Comment by zhangdaiscott** [comment]
已经了，请更新代码
