### ISSUE TITLE
side menu响应式有bug

### ISSUE THREAD

**Issue by RichardPear** [zhangdaiscott/jeecg-boot#1619]
##### 版本号：
2.2.1

##### 问题描述：
layoutMode = "sidemenu"的时候，调整窗口触发mobile模式，再调整窗口至desktop模式，左边菜单无法toggle出现

##### 截图&代码：
![image](https://s1.ax1x.com/2020/08/19/dQPwOf.png)
![image](https://s1.ax1x.com/2020/08/19/dQPBm8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经改了，下个版本发布
