### ISSUE TITLE
生成一对多 页面显示问题

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1624]
##### 问题描述：
生成的表单 最后操作一列 会多一列

生成代码 不带width属性 或者去掉 fixed:"right"
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26251311/90707393-19a90580-e2ca-11ea-9616-ff472fa65616.png)

![image](https://user-images.githubusercontent.com/26251311/90707418-2594c780-e2ca-11ea-9f75-26ed4ba2ea0e.png)

**Comment by zhangdaiscott** [comment]
请问用的是那套模板？

**Comment by 1195999342** [comment]
默认的
