### ISSUE TITLE
查询数据问题

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1626]
##### 问题描述：
返回数据的id 不一定是string类型 
JEditableTableMixin.js 
##### 截图&代码：

for(let i=0;i<dataSource.length;i++){
          dataSource[i].id+="";
        }

![image](https://user-images.githubusercontent.com/26251311/90707749-d9965280-e2ca-11ea-934e-59544ec74a4b.png)
![image](https://user-images.githubusercontent.com/26251311/90707844-0a768780-e2cb-11ea-8ba0-a33c0caed1e9.png)

**Comment by zhangdaiscott** [comment]
目前我们的系统的规则主键ID都是str类型的，可以根据自己需求改造
