### ISSUE TITLE
表单开发编辑表单JS报错

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#1627]
##### 版本号：
2.2.1

##### 问题描述：

表单开发，点编辑表单浏览器控制台报错
##### 截图&代码：

![微信图片_20200820141919](https://user-images.githubusercontent.com/55084864/90724087-8505ce00-e2f0-11ea-9348-a2eb0580cb9c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不影响功能的话，请忽略

**Comment by tb2888** [comment]
好的！暂时没发现影响功能，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 下午2:01
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "　"<283129183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 表单开发编辑表单JS报错 (#1627)





 
不影响功能的话，请忽略
