### ISSUE TITLE
model中子表位置使用时间控件展示不全

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#1628]
##### 版本号：
2.2.1

##### 问题描述：
在model中使用除input以外的控件会出现展示不全的问题

##### 截图&代码：
![1](https://user-images.githubusercontent.com/30401919/90748560-eafc5080-e304-11ea-99a2-3d4a8ed391fa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个示例应该没改，可以忽略，现在online和生成代码都改过此逻辑。
