### ISSUE TITLE
重大安全隐患, 数据权限只对查询有作用,对于增,删,改完全就不设防!!!

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1630]
##### 版本号：
2.2.1

##### 问题描述：
在浏览器获取到任意用户的token后, 可以构造任意数据, 提交到任意接口;(除了部分写死了只有admin可用的接口之外.)
可以使用curl等工具, 执行任意数据操作.即使用户没有菜单和view的权限.
数据权限中, 只有查询是有限制作用.
目前没有发现, 数据权限对增,删,改有作用限制.
如果没有数据权限限制,则任意用户都可以查询所有数据; 菜单的权限限制就是一个笑话
数据存在重大安全问题.

项目已经快要交付, 突然出现这种问题, 心量好慌的.希望作者尽快给出解决方案
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
增删改查等请求，需要控制自己加权限注解即可
http://doc.jeecg.com/1273973

**Comment by GordonHuangYong** [comment]
自己好好看看吧。看不懂可以聊，对此项目有好处，不是只是我。这么草率就关闭问题。呵呵。
