### ISSUE TITLE
作者你删除我贴干嘛？那我只好发博客上去了。给你提出问题，不应该受到这种待遇吧！

### ISSUE THREAD

**Issue by GordonHuangYong** [zhangdaiscott/jeecg-boot#1631]
##### 问题描述：
问题这么重大，你都 还 没看清楚就删除了。我无语。
这个你看到就删除吧。我明天再给你图文并茂。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你不懂不要乱发，等有一天你懂了，别笑自己就行
