### ISSUE TITLE
多值查询问题

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1632]
##### 问题描述：
只会查询第一个值的数据吧
QueryGenerator

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26251311/90847853-0ebfa500-e39e-11ea-92f6-3ab1c3831707.png)

//多值查询
				if (parameterMap != null && parameterMap.containsKey(name + MULTI)) {
					**endValue = parameterMap.get(name + MULTI)[0].trim();**
					addQueryByRule(queryWrapper, name.replace(MULTI,""), type, endValue, QueryRuleEnum.IN);
				}
-----》
//多值查询
				if (parameterMap != null && parameterMap.containsKey(name + MULTI)) {
					**endValue = StringUtils.join(parameterMap.get(name + MULTI),",").trim();**
					addQueryByRule(queryWrapper, name.replace(MULTI,""), type, endValue, QueryRuleEnum.IN);
				}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
多值（in）查询时，从代码中看，这段代码没有被使用。
- 多值查询时，没有搜索拼接后缀_MultiString的代码。
- JeecgBoot工程，java代码没有。
- AntDesign_vue工程，js代码没有。
- 下拉框支持多选时，没有动态为属性名称增加后缀_MultiString


总结：
1，搜索代码时，一定要全工程搜索。
2，有些不合常理的bug，原因也许是意料之外。
3，静态看代码，如果觉得有bug，但是功能使用和操作没有问题，这时不排除代码是多余的，根本没用。
