### ISSUE TITLE
dictText名称解析报错，想问下这个问题如何解决，需要解析的表是单表（树）

### ISSUE THREAD

**Issue by Admin2020-qixia** [zhangdaiscott/jeecg-boot#1634]
版本号：2.2.1

问题描述：dictText名称解析报错，想问下这个问题如何解决，需要解析的表是单表（树）

 截图&代码：
![图片](https://user-images.githubusercontent.com/62987999/90865874-a684b980-e3c5-11ea-8a15-7272a71bb320.png)
![图片](https://user-images.githubusercontent.com/62987999/90866065-eba8eb80-e3c5-11ea-8603-7e78de2b8ac7.png)
![图片](https://user-images.githubusercontent.com/62987999/90866166-12672200-e3c6-11ea-9f47-88574cafec66.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
debug跟踪吧，你发的截图分析不出原因

**Comment by yizheLiu** [comment]
遇到同样问题 ，debug 到行报错， dictService debug 不进去了。
这个是查询的部门根节点的名字
![image](https://user-images.githubusercontent.com/9362187/91383908-e2a19980-e85f-11ea-8a60-4882221da8a3.png)
参数：
![image](https://user-images.githubusercontent.com/9362187/91383942-fb11b400-e85f-11ea-8180-b1da44bf2b8f.png)
异常
![image](https://user-images.githubusercontent.com/9362187/91383965-11b80b00-e860-11ea-9912-9afbfe17b151.png)

**Comment by HanYaodong** [comment]
一样的问题 #1522

**Comment by tanpenggood** [comment]
已修复，将在下一版本发布。
