### ISSUE TITLE
建议：增加[更新计划]菜单，方便大家了解到平台新版本的迭代方向

### ISSUE THREAD

**Issue by tanpenggood** [zhangdaiscott/jeecg-boot#1638]
##### 版本号：
2.2.1

##### 问题描述：

现在已有[更新日志](http://www.jeecg.com/doc/log)菜单，能方便大家查看每个版本更新/修复的功能。

希望能增加一个[更新计划](http://www.jeecg.com/doc/log) 的菜单，能方便大家了解到对平台新版本的迭代方向。

**Comment by zhangdaiscott** [comment]
ok
