### ISSUE TITLE
在线表单开发中数据表的某一字段的默认值设为#{sysUserName}时，无法获取到值。

### ISSUE THREAD

**Issue by 13123728813** [zhangdaiscott/jeecg-boot#1639]
##### 版本号：
v2.2.1

##### 问题描述：
在线表单开发中数据表的某一字段的默认值设为#{sysUserName}时，无法获取到值。

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/58758268/90946322-5443a700-e45e-11ea-9c48-a2632e23cb8f.png)
![图片](https://user-images.githubusercontent.com/58758268/90946376-a97fb880-e45e-11ea-8929-5c933bf0aa12.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
有重复的，关闭此问题
