### ISSUE TITLE
菜单删除父节点报错

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#164]
解决办法：SysPermissionServiceImpl第60行对pid进行null值判断改为 pid == null ? "" : pid
int count = this.count(new QueryWrapper<SysPermission>().lambda().eq(SysPermission::getParentId, pid == null ? "" : pid));
使用的是Oracle版本。

**Comment by zhangdaiscott** [comment]
3Q
这么改
`/**
	  * 真实删除
	 */
	@Override
	@Transactional
	@CacheEvict(value = "permission",allEntries=true)
	public void deletePermission(String id) throws JeecgBootException {
		SysPermission sysPermission = this.getById(id);
		if(sysPermission==null) {
			throw new JeecgBootException("未找到菜单信息");
		}
		String pid = sysPermission.getParentId();
		if(oConvertUtils.isNotEmpty(pid)) {
			int count = this.count(new QueryWrapper<SysPermission>().lambda().eq(SysPermission::getParentId, pid));
			if(count==1) {
				//若父节点无其他子节点，则该父节点是叶子节点
				this.sysPermissionMapper.setMenuLeaf(pid, 1);
			}
		}
		sysPermissionMapper.deleteById(id);
		// 该节点可能是子节点但也可能是其它节点的父节点,所以需要级联删除
		this.removeChildrenBy(sysPermission.getId());
	}`
