### ISSUE TITLE
加入多租户管理后数据表无法正常更新

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1640]
##### 版本号：
2.2.1

##### 问题描述：
某个表加入多租户管理后，无法正常更新，报错误：“sql injection violation, part alway true condition not allow”
应该是有个永真式 1=1在中间。

##### 截图&代码：

<img width="644" alt="错误" src="https://user-images.githubusercontent.com/8335270/90946681-c36eca80-e461-11ea-97db-dd98237fe34f.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
1=1 是jeecg加的还是你这边编码加的？

**Comment by yanchenchen** [comment]
系统自己加的。

**Comment by yanchenchen** [comment]
通过online的功能测试有这个问题，生产代码部署则没有这个问题。

**Comment by tygithub1** [comment]
这个可以临时修改MybatisPlusConfig类，判断如果是update操作不走过滤器，他就不会报这个错误了
paginationInterceptor.setSqlParserFilter(new ISqlParserFilter() {
            @Override
            public boolean doFilter(MetaObject metaObject) {
                MappedStatement ms = SqlParserHelper.getMappedStatement(metaObject);
                if(ms.getSqlCommandType()== SqlCommandType.UPDATE){
                     return true;
                 }
                return false;
            }
        });

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
