### ISSUE TITLE
【建议】多数据源时校验是否有重复数据

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1641]
##### 问题描述：
duplicateCheck  校验数据重复 

我这边是多数据源 可不可以在校验重复数据的时候 可以指定数据源 我这里是两个数据源 就只做了简单的两个方法区分一下 
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26251311/90949621-3be28500-e47c-11ea-9c46-ba9454a1f19a.png)

![image](https://user-images.githubusercontent.com/26251311/90949608-16ee1200-e47c-11ea-901b-d5cf63bfe95e.png)

![image](https://user-images.githubusercontent.com/26251311/90949634-603e6180-e47c-11ea-83ce-74018d64dd8c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持得自己改造
