### ISSUE TITLE
【bug】postgresql 查看已删除用户类型错误

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1642]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26251311/90949874-333f7e00-e47f-11ea-9728-e22d5fbc0720.png)
wrapper.eq(SysUser::getDelFlag, "1");

private Integer delFlag;

"1" --> 1

**Comment by zhangdaiscott** [comment]
什么错？

**Comment by 1195999342** [comment]
postgresql  这个库不会自动把string 转 int 查询的时候 应该传1  你们实体类存的也是int类型

**Comment by zhangdaiscott** [comment]
明白了，3Q
已改，下个版本发布
