### ISSUE TITLE
【咨询】有无一键关闭打开的所有标签页的功能

### ISSUE THREAD

**Issue by qingjing0606** [zhangdaiscott/jeecg-boot#1643]
##### 版本号：
2.2.1

##### 问题描述：
当菜单打开太多时，是否支持一键关闭所有的菜单，如果没有，我们可以在代码的什么位置进行修改。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/10215599/90993264-c21ada80-e5e6-11ea-969b-f2c1a8dd7dd5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以参考关闭其他
