### ISSUE TITLE
新建表之后同步数据库出现NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1644]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18321599/91000657-43309c80-e5fc-11ea-8e33-0b63b430078e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jwcjf** [comment]
在开发环境中

**Comment by zhangdaiscott** [comment]
没遇到过，看看是不是依赖冲突了

**Comment by liudonghua123** [comment]
@jwcjf 这个问题是JDK的版本，你用了9+（例如我因为使用vscode，要求JDK 11+，所以使用了JDK 11 LTS），JAXB已经分离出去，需要在 jeecg-boot/pom.xml 中添加如下依赖

```

		<jaxb.version>2.3.2</jaxb.version>


		<!--Fix java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException -->
		<!--https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j-->
		<!-- API, java.xml.bind module -->
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
		<!-- Runtime, com.sun.xml.bind module -->
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
```

**Comment by jwcjf** [comment]
> @jwcjf 这个问题是`JDK`的版本，你用了9+（例如我因为使用vscode，要求`JDK` 11+，所以使用了`JDK` 11 LTS），`JAXB`已经分离出去，需要在 `jeecg-boot/pom.xml` 中添加如下依赖
> 
> ```
> 		<jaxb.version>2.3.2</jaxb.version>
> 
> 
> 		
> 		
> 		
> 		<dependency>
> 			<groupId>jakarta.xml.bind</groupId>
> 			<artifactId>jakarta.xml.bind-api</artifactId>
> 			<version>${jaxb.version}</version>
> 		</dependency>
> 		
> 		<dependency>
> 			<groupId>org.glassfish.jaxb</groupId>
> 			<artifactId>jaxb-runtime</artifactId>
> 			<version>${jaxb.version}</version>
> 		</dependency>
> ```
> 
> 其实 JDK 8 也已经很多年了，有时候的确需要升级了，可能到2022年就停止更新维护了，但不同发行版不太一样！
> 
> https://endoflife.date/java
> https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> https://access.redhat.com/articles/1299013
> https://adoptopenjdk.net/support.html

确实是JDK版本的问题，我之前用的是jdk14
现在切换为JDK8就可以了
非常感谢
