### ISSUE TITLE
你这边数据库连接很慢吗，还是表很多，正常不会这么慢

### ISSUE THREAD

**Issue by qiuyan12** [zhangdaiscott/jeecg-boot#1645]
你这边数据库连接很慢吗，还是表很多，正常不会这么慢

_Originally posted by @zhangdaiscott in https://github.com/zhangdaiscott/jeecg-boot/issues/1613#issuecomment-678922841_

表很多 (2W张表).
慢的情况
由于 antd table 的表格在没有分页的情况,单页数据多,会造成整个页面的严重卡顿,

**Comment by zhangdaiscott** [comment]
ok，哪后面可以改成分页的
