### ISSUE TITLE
DynamicNotice.vue 导致首次加载时, 加载了过多的 .js 文件

### ISSUE THREAD

**Issue by Aaron-Bird** [zhangdaiscott/jeecg-boot#1648]
##### 版本号：

2.2.1

##### 问题描述：

DynamicNotice.vue 导致在首次加载时, 加载了 views 文件夹下的全部组件.
看起来似乎是下面这段代码导致的.

https://github.com/zhangdaiscott/jeecg-boot/blob/4fd30c495fb4c83dd1858d9af457587bebd43a0b/ant-design-vue-jeecg/src/components/tools/DynamicNotice.vue#L22  

##### 截图&代码：
如果不注释掉这行代码, 首次加载时有 400 多个请求, 其中大部分是 .js 文件.

![1](https://user-images.githubusercontent.com/25508292/91051493-c977cd80-e652-11ea-8330-646a5b4f2253.PNG)

注释掉代码后,首次加载只有 30 多个请求.  

![2](https://user-images.githubusercontent.com/25508292/91051558-da284380-e652-11ea-8605-ca3ba9c3bce7.PNG)

##### 我的问题

没有搞懂这个组件是干什么用的,您可以解释一下它的用途吗?
这个组件是否是必选的,我可以注释掉这个组件不用它吗?

**Comment by Aaron-Bird** [comment]
是我搞错了,似乎注释掉后也会包在同一个 js 文件里.

**Comment by 820895362** [comment]
你好,请问最后是怎么解决的?注释掉有用吗
