### ISSUE TITLE
online报表动态参数设置不生效

### ISSUE THREAD

**Issue by FirstMemory** [zhangdaiscott/jeecg-boot#1649]
##### 版本号：
2.2.1

##### 问题描述：
online报表动态参数设置不生效

##### 截图&代码：

![image](https://user-images.githubusercontent.com/31384429/91116559-3759de80-e6bf-11ea-8fc8-3c34f7974fd9.png)
![image](https://user-images.githubusercontent.com/31384429/91116567-3cb72900-e6bf-11ea-8f38-ce0935b3c934.png)
![image](https://user-images.githubusercontent.com/31384429/91116574-417bdd00-e6bf-11ea-8c18-4482afc38e3e.png)
hou'ta后台打印参数为空

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你传参了？
![image](https://user-images.githubusercontent.com/3162115/91126731-43ea3100-e6d7-11ea-8836-47de1ed5bb52.png)
http://doc.jeecg.com/1273862

**Comment by FirstMemory** [comment]
用的JPopupOnlReport组件，不过看后台应该走的方法是一样的。通过数据库插入
![image](https://user-images.githubusercontent.com/31384429/91127416-cc1d0600-e6d8-11ea-8813-64535cb6e90f.png)
并且将参数设置为
![image](https://user-images.githubusercontent.com/31384429/91127819-a04e5000-e6d9-11ea-872c-aa5381f6e8e2.png)才实现动态参数。
