### ISSUE TITLE
【bug】生成实体类主键类型

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1650]
##### 问题描述：
id-type 不管设置为多少  主键类型都为IdType.ASSIGN_ID 

##### 截图&代码：
/**主键id*/
	@TableId(type = IdType.ASSIGN_ID)
    @ApiModelProperty(value = "主键id")
    private java.lang.Integer id;

#主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
去掉@TableId(type = IdType.ASSIGN_ID)注解
