### ISSUE TITLE
隐藏高级查询按钮

### ISSUE THREAD

**Issue by zhenghanwen** [zhangdaiscott/jeecg-boot#1651]
##### 版本号：

2.2.1
##### 问题描述：
如何隐藏高级查询按钮

##### 截图&代码：
第一步，在ui前端开发技巧中的自定义组件中找到了JSuperQuery 高级查询，找不到按钮编码

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没明白

**Comment by zhenghanwen** [comment]
![问题](https://user-images.githubusercontent.com/49750758/91511152-a595df80-e911-11ea-9df6-04e557653a8a.png)

**Comment by zhangdaiscott** [comment]
online开发的话，可以通过权限隐藏掉
