### ISSUE TITLE
二级下拉联动组件 一级只出来一个值

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1652]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/91153667-1ad79980-e6f3-11ea-91ad-0940993aef12.png)

![image](https://user-images.githubusercontent.com/18321599/91153822-4e1a2880-e6f3-11ea-9c12-db2f3f105470.png)

只出来 产品分类
![image](https://user-images.githubusercontent.com/18321599/91153973-786be600-e6f3-11ea-8189-899becacb457.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
等我们测测

**Comment by tygithub1** [comment]
https://www.kancloud.cn/zhangdaiscott/jeecg-boot/1513409
