### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by xu2604980** [zhangdaiscott/jeecg-boot#1653]
##### 版本号：
2.2.1

##### 问题描述：
登录页面：
  |-账号密码登录验证码 404
  |- 第三方登录网页链接出错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33078468/91250777-6ab66f00-e78c-11ea-80f1-0807545ff7a0.png)

![image](https://user-images.githubusercontent.com/33078468/91250817-80c42f80-e78c-11ea-8093-5e46b024b4c4.png)

**Comment by zhangdaiscott** [comment]
第三方登录你配置了吗

**Comment by xu2604980** [comment]
> 第三方登录你配置了吗

这是你们线上的演示环境，现在又出现了下面这种情况
![image](https://user-images.githubusercontent.com/33078468/91654238-c01ab500-ead9-11ea-8e45-6f53df2e3d12.png)
