### ISSUE TITLE
online表单开发功能问题

### ISSUE THREAD

**Issue by yanym168** [zhangdaiscott/jeecg-boot#1654]
##### 截图&代码：

![9CAHF L}UA}(}4AKV_T08{R](https://user-images.githubusercontent.com/70201550/91272315-25a33480-e7ae-11ea-962b-4bdbf8cb4d12.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请详细描述如何重现

**Comment by yanym168** [comment]
重现步骤：
步骤1：Online表达开发->新增，配置好信息后同步数据库
步骤2：修改步骤1新增的记录，新增或修改数据属性，保存后，同步数据库，选择普通同步报错
备注：数据库采用 Oracle 12c

**Comment by zhangdaiscott** [comment]
收录，测试

**Comment by zhangdaiscott** [comment]
已经修复下个版本发布
