### ISSUE TITLE
框架启动后会一直提示连接数据库超时

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#1657]
##### 版本号：
2.2.1

##### 问题描述：
框架代码启动时报错，启动后不影响其他功能，但是后台会一直提示错误，数据库表没有被锁表

##### 截图&代码：
![20200826163207](https://user-images.githubusercontent.com/30401919/91280840-f266a280-e7b9-11ea-8a49-c83b1c6897d4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
数据库配置有问题吧
