### ISSUE TITLE
在ipad用浏览器访问，输入法遮住了表格，无法看到输入框了，无法输入

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1658]
##### 版本号：
2.2.1

##### 问题描述：
表格第5行开始，输入法遮住了表格的输入框，无法看到，没法输入

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请按照格式发图
