### ISSUE TITLE
实体字段单词错误

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#1660]
##### 版本号：
2.2.1

##### 问题描述：
SysAnnouncement titile 单词错误了 title 对应数据库也是

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12267648/91410708-e3dfc000-e879-11ea-8afb-65fcda1fba2b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，3Q

**Comment by zhangdaiscott** [comment]
牵扯的代码地方太多了，为了稳定暂时不改了
