### ISSUE TITLE
如果已经建了用户，企业微信登陆会提示已经存在

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1661]
##### 版本号：
2.2.1

##### 问题描述：
如果已经建了用户，企业微信登陆会提示已经存在
意思是只能用企业微信登陆创建用户，如果先创建，再用企业微信登陆就会提示已经存在

##### 截图&代码：
数据库中已存在该记录
Duplicate entry 'test' for key 'index_user_name'

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
