### ISSUE TITLE
【BUG】有以下三点，麻烦帮忙看一下

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#1662]
##### 问题描述：
  
1、小屏下，“欢迎您”消失，导致个人中心等功能无法使用
![image](https://user-images.githubusercontent.com/26954826/91427444-7f7c2b00-e890-11ea-936a-d3c0ec0efda6.png)

2、小屏回到大屏，不刷新页面的情况下，左上角按钮失效，左侧菜单不显示
![image](https://user-images.githubusercontent.com/26954826/91427539-a4709e00-e890-11ea-8f8b-870cc48af335.png)
![image](https://user-images.githubusercontent.com/26954826/91427554-a9cde880-e890-11ea-81b5-674e869f34cf.png)

3、token失效时，导入导出功能只提示undefined，无法弹出请重新登陆的弹框，检查了代码，没有调用request.js里error的方法，导致用户不知道是因为超时原因上传失败的。
![image](https://user-images.githubusercontent.com/26954826/91427960-e7cb0c80-e890-11ea-915f-2645efea1660.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
1、2问题已经处理了，下个版本发布

**Comment by qq734504513** [comment]
请问2.2.2版本大概什么时候更新呢
