### ISSUE TITLE
实用功能  能否支持横屏 (加个参数给用户选择)?

### ISSUE THREAD

**Issue by qiuyan12** [zhangdaiscott/jeecg-boot#1663]
##### 版本号：
2.2.1

##### 问题描述：
发布手机APP后,发现不能横屏.  实际应用中,表格内容行在太多, 竖排太窄,看起来很不友好. 

能否加个支持横屏的参数??  让用户在打包APP前,根据实际情况,,自行选择. 

##### 截图&代码：

![IMG_20200828_093715](https://user-images.githubusercontent.com/29660289/91511915-594b9f00-e913-11ea-8207-86a5e2f58aed.jpg)
![IMG_20200828_094503](https://user-images.githubusercontent.com/29660289/91511922-5c468f80-e913-11ea-9581-f5b0dedc363f.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个自己搞吧
