### ISSUE TITLE
[popup相关]如何实现带动态参数的报表在popup中使用

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1666]
##### 版本号：

2.2.1
##### 问题描述：
需求：
popup数据来源的报表需要获取一个参数来筛选数据，这个参数来自与popup同个表单中某字段值。
在线开发能实现吗？
如果不能可以可以怎么实现？帮助文档中popup相关的资料不多，没看到怎么实现popup数据接口调用。
多谢！

##### 截图&代码：

popup的报表地址类似这样：

/online/cgreport/1299249740273524737?dev_config_id=${dev_config_id}
带有动态参数：dev_config_id。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rickding** [comment]
表单定义Popup数据来源时引用Report报表，目前不支持动态参数。

功能开发中，计划下一版本发布。

**功能设计：**
定义表单字段时，如果引用Popup类型，可以在字典Table名字后面加上参数，静态参数现已支持。

如果使用动态参数，引用字段值写法为${field_name}
![image](https://user-images.githubusercontent.com/5389183/92340715-07aecb80-f0ee-11ea-8ff8-e6f89d2d2d94.png)

**动态参数功能开发：**
1，表单查询、新增数据时，去除动态参数。

2，编辑数据时，根据当前行数据，替换动态参数。
![image](https://user-images.githubusercontent.com/5389183/92340915-9f141e80-f0ee-11ea-9b6e-ae23ba6883bf.png)

**Comment by zhangdaiscott** [comment]
已经完成，下个版本发布

**Comment by cooper1x** [comment]
传一个 params 就好了，我是 3.0 的版本，组件里面会拼接 self_xxxx
