### ISSUE TITLE
自动生成的代码不能保存和上传图片、文件等

### ISSUE THREAD

**Issue by waterconstruction** [zhangdaiscott/jeecg-boot#1667]
##### 截图&代码：
[JEECG Bugs2.2.1.xlsx](https://github.com/zhangdaiscott/jeecg-boot/files/5142379/JEECG.Bugs2.2.1.xlsx)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rickding** [comment]
不能重现完全一样的错误。

当配置字段类型错误时，见到了如下错误提示：
![image](https://user-images.githubusercontent.com/5389183/91844886-d0be5d00-ec8a-11ea-9631-b032f94e2074.png)


配置数据库时注意字段类型的选择，因为文件和图片保存的是文件路径和名称，所以需要string, text或者blob类型，注意string的长度限制，建议使用text或者blob，支持多文件选择。
![image](https://user-images.githubusercontent.com/5389183/91845100-2c88e600-ec8b-11ea-89f0-b911f04db8a1.png)


操作演示视频：https://www.ixigua.com/6867483870481089036/
