### ISSUE TITLE
自定义列当全部取消选中时 刷新页面 再次进入仅显示ID和操作列

### ISSUE THREAD

**Issue by JayceTsien** [zhangdaiscott/jeecg-boot#1668]
#### 版本号：
2.2.0 （包括线上演示平台）

#### 问题描述：
自定义列当全部取消选中时 刷新页面 再次进入仅显示ID和操作列，应该对空的自定义列进行重新加载源数据列。

#### 截图&代码：

<img width="904" alt="image" src="https://user-images.githubusercontent.com/42892849/91587231-0f050500-e989-11ea-808f-dc3c2a163b30.png">

#### 其他说明
个人理解 “全部取消选中”的操作应该是无法被执行的（应该至少保留一项数据列），（举例）简单处理是在 https://github.com/zhangdaiscott/jeecg-boot/blob/master/ant-design-vue-jeecg/src/views/jeecg/JeecgDemoList.vue#L342 该行进行变量长度的判断或者在onColSettingsChange进行判空

**Comment by zhangdaiscott** [comment]
这个不做修改，用户自己取消所有列的展示，这属于用户自己操作问题
