### ISSUE TITLE
Online在线表单开发，在查询配置中勾选“是否启用”，将会取消选中“页面配置”中的是否查询选项

### ISSUE THREAD

**Issue by rickding** [zhangdaiscott/jeecg-boot#1669]
##### 版本号：
2.2.1

##### 问题描述：
1，进入菜单：在线开发 -> Online表单开发
2，新增表单：输入表名、描述，其它选项默认
3，配置”页面属性”：勾选“是否查询”
4，配置“查询配置”：勾选“是否启动”
5，重新切换到“页面属性”，发现“是否查询”被自动取消。

如果此时同步数据库后进入功能测试页面，将没有查询配置。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5389183/91681662-b64c8c80-eb81-11ea-9b5f-7d36d21398f8.png)

![image](https://user-images.githubusercontent.com/5389183/91681550-53f38c00-eb81-11ea-8136-757a6520cf0a.png)

![image](https://user-images.githubusercontent.com/5389183/91681643-a7fe7080-eb81-11ea-8201-a5f9a2a54663.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的，是否启用更高级，查询配置启用的话，可以设置更加丰富的查询操作。
他的级别大于“是否查询”

**Comment by rickding** [comment]
勾选“查询配置-是否启用”，此时会自动取消勾选“页面属性-是否查询”，然后页面中就不出现查询字段了。

为了出现查询字段，还需要再次勾选“页面属性-是否查询”。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
