### ISSUE TITLE
【bug】in 类型多值查询 不适配postgresql

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1671]
##### 版本号：
2.2.1

##### 问题描述：
postgresql中string不能自动转int  需要适配多种类型的字段
##### 截图&代码：
类：QueryGenerator
![image](https://user-images.githubusercontent.com/26251311/91696313-f6bc0280-eba1-11ea-99a6-6036b3a0132b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
请把您的操作贴出来

**Comment by tygithub1** [comment]
已修复

**Comment by zhangdaiscott** [comment]
下个版本发布
