### ISSUE TITLE
【bug】一对多代码生成 主键为Int 生成mapper的参数为String

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1672]
##### 问题描述：
主键是int类型 一对多生成的mapper.xml 方法:deleteByMainId selectByMainId  参数是string
postgresql 会有问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26251311/91697385-9c23a600-eba3-11ea-9729-58f6b1e9f681.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
改主键类型，可以手工修改代码生成器的模板文件
jeecg.code-template-online
 *.ftl
