### ISSUE TITLE
【bug】一对多主题模版 选择ERP 代码生成还是默认模版

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1673]
##### 问题描述：
一对多主题模版 选择ERP 代码生成还是默认模版
点击功能测试是ok的  生成代码不对

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成代码的时候，选择了吗



![Uploading QQ图片20200831183849.png…]()
