### ISSUE TITLE
导出文件名由后端指定，前端获取不到

### ISSUE THREAD

**Issue by catlvsuger** [zhangdaiscott/jeecg-boot#1674]
##### 问题描述：

后端设置response
response.setHeader("Content-Disposition", "attachment;fileName=" + new String(file.getName().getBytes(StandardCharsets.UTF_8), StandardCharsets.ISO_8859_1));

按照网上几种方式设置 
 Access-Control-Expose-Headers: Content-Disposition
均无法生效，请教下该如何解决

##### 截图&代码：
            response.setHeader("Access-Control-Expose-Headers", "Content-Disposition");
            response.setHeader("Content-Disposition", "attachment;fileName=" + new String(file.getName().getBytes(StandardCharsets.UTF_8), StandardCharsets.ISO_8859_1));
            

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前导出的名字是前端设置的，在混入js里面
