### ISSUE TITLE
返回值问题：this.$refs.editableTable.getValuesSync()

### ISSUE THREAD

**Issue by lanwaixian** [zhangdaiscott/jeecg-boot#1675]
##### 版本号：
2.2.1

##### 问题描述：

let { error, values } = this.$refs.editableTable.getValuesSync()
若使用{ error, values } 可正常获取返回值
若使用{ error1, values1 } 或其他变量名，则接收到的返回值均为undefined

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
百度参考es6的解构函数

**Comment by rickding** [comment]
解构赋值时的写法，let {a} = {a: 1}，相当于let {a: a} = {a: 1}，注意简写时需要属性名称相同。
