### ISSUE TITLE
[开源安排]“Online权限配置( 新版 20200727)”什么时候开源

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1676]
##### 版本号：
2.2.1

##### 问题描述：
文档中提到的“Online权限配置( 新版 20200727)”功能计划开源吗？
如果开源的话预计什么时候能开源。
多谢！

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本
