### ISSUE TITLE
数据导入报错

### ISSUE THREAD

**Issue by DT-Kim** [zhangdaiscott/jeecg-boot#1677]
##### 版本号：
V2.2.0

##### 问题描述：
问题同 #1292
部署：nginx+jar部署
操作：代码同步下来后仅简化了登陆接口，配置了mysql，redis；其他内容未做修改
情况：一对多示例中的导入功能报错（导入的文件为导出功能下载的文件）

##### 截图&代码：
![001](https://user-images.githubusercontent.com/30312585/91829148-a44b1680-ec73-11ea-8015-096069ce9f92.png)
![02](https://user-images.githubusercontent.com/30312585/91829491-1facc800-ec74-11ea-91ef-b40a3a91e98a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by DT-Kim** [comment]
本地可以成功导入数据，服务器上运行报错

**Comment by DT-Kim** [comment]
项目实际使用的是2.1.1版本，因为出现同样的问题，所以想看下最新的版本会不会报错。
不知道能不能提供什么解决思路？

**Comment by zhangdaiscott** [comment]
用最新版本的autopoi

**Comment by DT-Kim** [comment]
打包姿势不对，建议翻看最新文档
