### ISSUE TITLE
关于项目改微服务相关问题

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#1679]
##### 版本号：
2.2.1

##### 问题描述：
修改system下pom时，手动添加jeecg-system-local-api然后reload项目提示包不存在在aliyun，并且项目中原先没有local-api这个配置，请问是使用官网提供的源码进性修改吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30401919/91854898-00736200-ec97-11ea-937d-27fa95fccba1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个版本还没发布呢，9月初会发布，快了

**Comment by aliaizhetaozi** [comment]
现在文档里的单体转微服务的功能还未实现吗？

**Comment by zhangdaiscott** [comment]
下个版本才发布

**Comment by aliaizhetaozi** [comment]
好的，知道了，谢谢

**Comment by aliaizhetaozi** [comment]
微服务这个是免费的吗？
