### ISSUE TITLE
Data truncation: Data too long for column 'request_param' at row 1

### ISSUE THREAD

**Issue by mxl530268618** [zhangdaiscott/jeecg-boot#168]
Error updating database. Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'request_param' at row 1
 ### The error may involve org.jeecg.modules.system.mapper.SysLogMapper.insert-Inline
 ### The error occurred while setting parameters
 ### SQL: INSERT INTO sys_log ( id, create_by, create_time, cost_time, ip, request_param, method, username, userid, log_content, log_type ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
 ### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'request_param' at row 1 ; Data truncation: Data too long for column 'request_param' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'request_param' at row 1

**Comment by mxl530268618** [comment]
代码生成后倒入 测试报错

**Comment by zhangdaiscott** [comment]
字段长度手工改长
