### ISSUE TITLE
Cannot resolve symbol 'SimpleFormat'

### ISSUE THREAD

**Issue by jianfenghuo** [zhangdaiscott/jeecg-boot#1681]
##### 版本号：
4.0.0

##### 问题描述：
org.jeecg.common.util.dynamic.db.FreemarkerParseFactory
paras.put(MINI_DAO_FORMAT, new SimpleFormat());
Cannot resolve symbol 'SimpleFormat'
##### 截图&代码：
![image](https://user-images.githubusercontent.com/41938864/91977368-27906900-ed55-11ea-9dde-d6d661628f8b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么意思？
