### ISSUE TITLE
 左侧导航栏，我们自己动态生成的，加进去的导航栏内容，如何国际化？

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#1682]
##### 版本号：
2.2.1

##### 问题描述：
左侧导航栏，我们自己动态生成的，加进去的导航栏内容，如何国际化？菜单配置里没有发现相关配置
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26954826/92059200-331a7900-edc3-11ea-8163-b5768dbc4f68.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
得自己改造
