### ISSUE TITLE
【提问】多数据源事务 有什么建议吗

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1684]
##### 问题描述：
 多数据源事务一致性问题

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1195999342** [comment]
我尝试了 阿里的seata 不知道是不是配置问题  事务并不会整体提交 而是在每一次操作数据库的地方都会自动提交事务 回滚也只会回滚最后一个

**Comment by zhangdaiscott** [comment]
这个没研究过
