### ISSUE TITLE
权限支持配置全局通用吗 根据数据权限规则  每个角色配好一个菜单全局数据权限规则

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1685]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18321599/92079030-d4b8bf00-edf1-11ea-97a3-0a42fdb1deed.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前没有，得自己改造
