### ISSUE TITLE
this.$router.push 无法打开新页面

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#1686]
##### 版本号：
2.2.1

##### 问题描述：
this.$router.push 无法打开新页面

##### 截图&代码：

![11](https://user-images.githubusercontent.com/59555469/92101178-523ef800-ee0f-11ea-86ac-63b5bad4504e.jpg)

![12](https://user-images.githubusercontent.com/59555469/92101198-579c4280-ee0f-11ea-81ae-8901b7453cc4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
菜单路由授权
