### ISSUE TITLE
实体类关联的表和关联的字典特别多，  列表显示时特别慢

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#1688]
##### 版本号：
2.2.1

##### 问题描述：
实体类关联的表和关联的字典特别多，  列表显示时特别慢，这种情况下系统怎么处理比较好

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以换成前端字典翻译，现在最新版已经支持前端字典缓存了
