### ISSUE TITLE
自定义组件下选择职务失败

### ISSUE THREAD

**Issue by hehongzhe** [zhangdaiscott/jeecg-boot#1690]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/45585702/92323799-36855d00-f06e-11ea-8869-2f10014a93e3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
经测试无问题

**Comment by rickding** [comment]
遇到点击输入框没有响应时，建议点击右边的“选择”按钮。

代码修复：响应下拉框展开事件，弹出选择模态框。下一版本发布。
