### ISSUE TITLE
JeecgBoot2.2.1不能用IE11浏览器访问的问题

### ISSUE THREAD

**Issue by yijian0645** [zhangdaiscott/jeecg-boot#1692]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/14273752/92340886-8572d700-f0ee-11ea-87ed-522f4c3e28f8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yijian0645** [comment]
![image](https://user-images.githubusercontent.com/14273752/92341800-6164c500-f0f1-11ea-83ca-dc0cc291182b.png)

**Comment by yijian0645** [comment]
![image](https://user-images.githubusercontent.com/14273752/92341810-6de91d80-f0f1-11ea-87aa-70010cafa920.png)

**Comment by yijian0645** [comment]
我让好几个同事的不同机器的IE11访问官网2.2.1示例都一样的问题哦。。。

**Comment by zhangdaiscott** [comment]
不要管演示系统，演示系统改动了一些东西，开源版本没问题
