### ISSUE TITLE
用户管理导入的模板没有

### ISSUE THREAD

**Issue by zhenghanwen** [zhangdaiscott/jeecg-boot#1693]
##### 版本号：
2.2.1

##### 问题描述：
在系统管理--用户管理里面，没有用户模板，导入不进去。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49750758/92347085-6893cf00-f101-11ea-895e-85438e5760e6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用导出数据的模板

**Comment by zhenghanwen** [comment]
模板里能增加密码的字段吗

**Comment by zhangdaiscott** [comment]
可以自己改，目前我们做的是导入设置默认密码

**Comment by luokehezi** [comment]
可以出个教程不
