### ISSUE TITLE
多租户环境下无法获取租户id

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1696]
##### 版本号：

2.2.1
##### 问题描述：
多租户环境下无法获取租户id
开发模式下，功能正常。
部署到服务器后，则无法登入系统，后台报的错误是空指针，原因就是无法获取租户id。
用的是同一套代码，同一套数据
##### 截图&代码：
<img width="744" alt="空指针" src="https://user-images.githubusercontent.com/8335270/92393280-3c546e80-f152-11ea-9545-5fac87e9118e.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
发帖太简单，无法分析

**Comment by yanchenchen** [comment]
嗯，因为我也不清楚是什么原因造成的，就是登录的时候直接跳出了。
前端页面报错：
<img width="657" alt="登录页面" src="https://user-images.githubusercontent.com/8335270/92432266-44e98b00-f1cc-11ea-847d-ab1844d8a1a4.png">
后台报错：
<img width="909" alt="后台错误" src="https://user-images.githubusercontent.com/8335270/92432278-4adf6c00-f1cc-11ea-9987-aaffd9e1496b.png">

**Comment by zhangdaiscott** [comment]
无法判断

**Comment by yanchenchen** [comment]
登录过程中调用这个方法：
org.jeecg.modules.system.mapper.SysUserMapper.getUserByName
因为表sys_user进行了多租户控制，所以会调用MybatisPlusConfig下的getTenantId方法，
![image](https://user-images.githubusercontent.com/8335270/92449347-81c57a00-f1ec-11ea-976b-39428f57f4fb.png)
该方法获取到的tenant_id为空，所以造成了空指针
![image](https://user-images.githubusercontent.com/8335270/92449520-c6e9ac00-f1ec-11ea-9f5e-1763e941cda6.png)
