### ISSUE TITLE
关于子表popup弹窗

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1697]
##### 问题描述：
1、如何实现popup弹窗记录多选并返回相关记录
2、如何实现子表中用自定义组件的popup弹窗，不是用online报表

##### 截图&代码：
![1](https://user-images.githubusercontent.com/54636793/92424666-83c11600-f1b7-11ea-9830-30ae9f79cb1f.png)
![2](https://user-images.githubusercontent.com/54636793/92424673-87ed3380-f1b7-11ea-9a49-481bf674f06b.png)

**Comment by zhangdaiscott** [comment]
自己写的代码还是online功能？

**Comment by lijinlang** [comment]
我已经生成代码了，自己定义了一个档案参照的组件，想替换online报表的popup弹窗，我想左边是商品分类，online这个不满足需求。就是想请教下在子表中怎么使用这个自定义组件

**Comment by lijinlang** [comment]
> 自己写的代码还是online功能？
我已经生成代码了，自己定义了一个档案参照的组件，想替换online报表的popup弹窗，我想左边是商品分类，online这个不满足需求。就是想请教下在子表中怎么使用这个自定义组件

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273911#slot_437
