### ISSUE TITLE
[bug]无法获取tenant_id

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1699]
##### 版本号：
2.2.1

##### 问题描述：

登录过程中无法获取tenant_id.

##### 截图&代码：

登录过程中调用这个方法：
org.jeecg.modules.system.mapper.SysUserMapper.getUserByName
因为表sys_user进行了多租户控制，所以会调用MybatisPlusConfig下的getTenantId方法，
![image](https://user-images.githubusercontent.com/8335270/92449347-81c57a00-f1ec-11ea-976b-39428f57f4fb.png)
该方法获取到的tenant_id为空，所以造成了空指针
![image](https://user-images.githubusercontent.com/8335270/92449520-c6e9ac00-f1ec-11ea-9f5e-1763e941cda6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yanchenchen** [comment]
为什么已经登录成功了但是无法获取到tenant_id呢？

**Comment by tygithub1** [comment]
你自己在用户表里面加了一个字段 tenant_id?

**Comment by yanchenchen** [comment]
对。进行租户管理的话，在相应的表要添加一个字段tenant_id，是这样的吧？
没有用relTenantIds，因为这个字段是对组织内部的，我的需求是用租户id区分不同的组织机构。

**Comment by tygithub1** [comment]
用户表不支持这么处理  只能通过设置relTenantIds才行，并且，  登录完成之后 进入首页 才会有tanent_id，这之前的所有的表操作 都是不经过多租户处理的，如果想要自定义 修改登录所有的sql抽出方法 并且 为其方法添加注解@SqlParser(filter = true)不走多租户逻辑保证不会报错

**Comment by yanchenchen** [comment]
是在LoginController类中的login方法上加@sqlparser(filter = true)，还是在sysUserService.getOne(queryWrapper)方法上加@sqlparser(filter = true)

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/101349198-f4b3bf00-38c7-11eb-8777-58afe715060f.png)

**Comment by CharlieJ0hn** [comment]
user 表不需要自己加字段，你到用户管理给他分配租户，登录的时候就有租户选择了。
