### ISSUE TITLE
代码生成 vue前端文件，列表缺失表字段

### ISSUE THREAD

**Issue by cnn007** [zhangdaiscott/jeecg-boot#17]
代码生成
1.生成的后端代码没有问题，可以正常使用。
2.生成的前端代码 vue ，会有字段省略生成吗？
发现列表字段不全，会缺失字段，
3.使用filter 的时候，必须是create_time,否则报错，
这个可能表设计要遵循规范。

**Comment by zhangdaiscott** [comment]
create_time 是表设计规范要求，你是想怎么用？

**Comment by cnn007** [comment]
create_time,我知道了。
  
第2条.生成的前端代码 vue ，会有表字段省略生成吗？
发现列表字段不全，缺失字段，

**Comment by zhangdaiscott** [comment]
会有，创建人，创建时间，修改人，修改时间，默认不生成
