### ISSUE TITLE
建议升级一下POI的版本号。

### ISSUE THREAD

**Issue by wrs645776258** [zhangdaiscott/jeecg-boot#1700]
##### 版本号：
2.2.1

##### 问题描述：
建议升级一下POI的版本号。依赖版本太低了。
不清楚你们内置的EXCEL导入使用的是否是流式解析。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重复问题，先关闭了
https://github.com/zhangdaiscott/autopoi/issues/14
