### ISSUE TITLE
设置全局模糊查询不好使

### ISSUE THREAD

**Issue by chuvenus** [zhangdaiscott/jeecg-boot#1701]
##### 版本号：

2.2.1
##### 问题描述：
按照常用问题汇总中得方法
6、想要设定查询模式为模糊查询，怎么作全局修改？

修改后端/jeecg-boot-base-common/src/main/java/org/jeecg/common/system/query/QueryGenerator.java,找到installMplus方法下述代码修改即可
修改后仍无法模糊查询，需要输入*才可以

##### 截图&代码：
是在线表单

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持，会有问题。
可以用这个组件  JInput 特殊查询组件（模糊查询）
http://doc.jeecg.com/1297210

**Comment by wolfsheep** [comment]
> 不支持，会有问题。
> 可以用这个组件 JInput 特殊查询组件（模糊查询）
> http://doc.jeecg.com/1297210

这个地址失效了
