### ISSUE TITLE
JCategorySelect 分类字典选择器获取的是id，如何获取到选项对应的文本值

### ISSUE THREAD

**Issue by iceMusic** [zhangdaiscott/jeecg-boot#1702]
##### 版本号：
v2.2.1
##### 问题描述：
JCategorySelect 分类字典选择器获取的是id，如何获取到选项对应的文本值

##### 截图&代码：

<a-col :span="12">
            <a-form-item label="分类" :labelCol="labelCol" :wrapperCol="wrapperCol">
              <j-category-select v-decorator="['type', {}]" pcode="A01" />
            </a-form-item>
          </a-col>

**Comment by zhangdaiscott** [comment]
目前不支持，自己改造代码即可
