### ISSUE TITLE
在线报表怎么设置聚合参数，怎么做聚合，表格支持列统计吗

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1703]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述过于简单，请图文并茂描述你的需求

**Comment by jwcjf** [comment]
> 描述过于简单，请图文并茂描述你的需求

![image](https://user-images.githubusercontent.com/18321599/92679153-3b8e2900-f35a-11ea-8063-a4c314ebc5da.png)

这个查询接口可以动态配置吗，有接口可以调用吗

**Comment by zhangdaiscott** [comment]
目前不支持
