### ISSUE TITLE
数据库密码加密存储不支持吗？

### ISSUE THREAD

**Issue by 15773200610** [zhangdaiscott/jeecg-boot#1704]
##### 版本号：
jeecg-boot 2 

##### 问题描述：
数据库密码配置是不支持加密存储吗？
我看了DruidConfig类的代码，感觉没有将publicKey这个属性的值赋值到properties里面去。。。。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前没做加密逻辑
