### ISSUE TITLE
高级查询方面的问题

### ISSUE THREAD

**Issue by zhenghanwen** [zhangdaiscott/jeecg-boot#1708]
##### 版本号：
2.2.0

##### 问题描述：
我有一个online表--成绩表，有练习科目id,学生id,成绩三个字段，把练习科目id用数据字典，使他在页面上显示的是科目，学生id显示的学生姓名，如何用高级查询的时候，用学生姓名去查

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/49750758/92673361-83f31a00-f34d-11ea-9da5-0b027ac2cd0e.png)
![图片](https://user-images.githubusercontent.com/49750758/92673644-21e6e480-f34e-11ea-87a8-2bc2d94d8c58.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhenghanwen** [comment]
还有就是，高级查询，比如学生ID的控件选择为下拉框的时候，查询成功，如果是文本框的时候，查询失败

**Comment by zhangdaiscott** [comment]
如果是自己开发的话，可以灵活实现

**Comment by zhenghanwen** [comment]
数据字典用法：表单字段，通过配置系统字典或者表字典，实现下拉、Checkbox、Radio等效果。
文本框能用数据字典吗？
