### ISSUE TITLE
新建表单表名不存在也提示存在

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#1710]
##### 问题描述：

新建表单表名不存在也提示存在，暂时只碰到这个表名有问题
##### 截图&代码：

![image](https://user-images.githubusercontent.com/55084864/92694890-45278900-f37a-11ea-9193-2057860de7c8.png)
![image](https://user-images.githubusercontent.com/55084864/92694930-507ab480-f37a-11ea-8f99-13a32fce8df3.png)
![image](https://user-images.githubusercontent.com/55084864/92694960-5a9cb300-f37a-11ea-8a8a-69c7c5ade8c5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该是其他库有这个表，已经解决，下个版本发布

**Comment by tb2888** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 下午4:04
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "　"<283129183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 新建表单表名不存在也提示存在 (#1710)





 
应该是其他库有这个表，已经解决，下个版本发布
