### ISSUE TITLE
省市区三级联动支持后台配置字典输出对应的text吗

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#1711]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/92697470-f67bee00-f37d-11ea-99f7-2f1e5575c328.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以自己改造，目前是ID
