### ISSUE TITLE
功能测试标签页能不能显示表名？

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#1712]
##### 版本号：
2.2.1

##### 问题描述：
点开了几个表的功能测试的话想切换到想要的表的功能测试不好找，如果在标签页那里加上表名就好了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55084864/92699755-90dd3100-f380-11ea-97a3-5ec5e0fa047a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持，配置菜单后可以记录名字
