### ISSUE TITLE
当进入登录页时，有一定几率出现验证码错误

### ISSUE THREAD

**Issue by Nibbbbbbbb** [zhangdaiscott/jeecg-boot#1714]
##### 版本号：
 2.2.1

##### 问题描述：

当进入登录页时，有一定几率出现验证码错误
（包括本地测试以及官网演示都有这个问题）

##### 截图&代码：

随机出现，找不到复现规律（打开网站立刻输入验证码的，不是验证码过期）

**Comment by zhangdaiscott** [comment]
收录

**Comment by jiangrulei** [comment]
if(checkCode==null || !checkCode.toString().equals(lowerCaseCaptcha)) {
			result.error500("验证码错误");
			return result;
		}
验证码登陆我也遇到这个问题，我将object对象转换成字符串解决了，看了一下jdkd的Object.equals()，使用是的(this == object)

**Comment by zhangdaiscott** [comment]
感谢

**Comment by szyuppie** [comment]
验证码404啊，什么问题呢

**Comment by Nibbbbbbbb** [comment]
> 验证码404啊，什么问题呢

你后台没开吧

**Comment by zhangdaiscott** [comment]
已经修正，下个版本发布
