### ISSUE TITLE
JS加了断点没去掉

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#1716]
##### 版本号：
2.2.1

##### 问题描述：
配置查询的时候点启用，会进入断点，配好查询后打开列表也会进断点

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55084864/92714618-05b76780-f38f-11ea-9133-286dbbc8ee2e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确定不是你自己加的?

**Comment by tb2888** [comment]
我自己没加，好像今天又没有，应该不是你们那边的问题吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JEECG开源社区&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月10日(星期四) 晚上6:21
收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;&quot;tb2888&quot;<283129183@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JS加了断点没去掉 (#1716)
