### ISSUE TITLE
主附表中，附表的表单类型没有树类型

### ISSUE THREAD

**Issue by Admin2020-qixia** [zhangdaiscott/jeecg-boot#1719]
版本号：2.2.1

问题描述：主附表中，附表的表单类型没有树类型

 [截图&代码：
![图片](https://user-images.githubusercontent.com/62987999/92981859-4a95e800-f4ce-11ea-9fd2-b568f4dedf2c.png)
![图片](https://user-images.githubusercontent.com/62987999/92981870-55e91380-f4ce-11ea-9f8d-c111e762e7c5.png)
![图片](https://user-images.githubusercontent.com/62987999/92981884-61d4d580-f4ce-11ea-8a09-002264e61a1b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持，可以自定义
