### ISSUE TITLE
新版本添加表单条目时报错。

### ISSUE THREAD

**Issue by ShellMount** [zhangdaiscott/jeecg-boot#1724]
##### 版本号：
master: 2.2.1

##### 问题描述：
在线表单生成后，向列表中添加一条记录时，报错。
```
操作失败，Invalid bound statement (not found): org.jeecg.modules.ngalain.mapper.NgAlainMapper.insert
```

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12572507/93016983-fab34000-f5f7-11ea-9c16-752ade8485e3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本太老了，印象中处理过这个问题，可以在issue里面搜一下
