### ISSUE TITLE
最新版私服包不能下载（已替换私服maven）

### ISSUE THREAD

**Issue by JiangHoumin** [zhangdaiscott/jeecg-boot#1725]
##### 问题描述：按照官方文档替换私服maven，有2个包下不下来
+ Cannot resolve org.hibernate:hibernate-re:2.3.0
+ Cannot resolve org.jeecgframework.boot:codegenerate:1.2.2

##### 截图&代码：
```
<mirrors>
       <mirror>
            <id>nexus-aliyun</id>
            <mirrorOf>*,!jeecg,!jeecg-snapshots,!getui-nexus</mirrorOf>
            <name>Nexus aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror> 
 </mirrors>
```

![QQ截图20200914105310](https://user-images.githubusercontent.com/20291253/93038814-88367480-f678-11ea-9c1d-d68b490b386a.png)

**Comment by zhangdaiscott** [comment]
官方仓库有的
http://maven.jeecg.org/nexus/#nexus-search;quick~codegenerate

你删除本地依赖，重新下载试试
