### ISSUE TITLE
所有类型的角色都没有编辑用户管理的权限

### ISSUE THREAD

**Issue by qq734504513** [zhangdaiscott/jeecg-boot#1726]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/39591043/93040664-17de2200-f67d-11ea-9808-165a69feb703.png)
![image](https://user-images.githubusercontent.com/39591043/93040692-23c9e400-f67d-11ea-9567-701b8a69af16.png)
![image](https://user-images.githubusercontent.com/39591043/93040823-7dcaa980-f67d-11ea-85d0-f7b534d417c2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
本地还是演示环境？

**Comment by qq734504513** [comment]
> 本地还是演示环境？

本地环境

**Comment by zhangdaiscott** [comment]
全文搜索@RequiresRoles({ "admin" })
注释掉

**Comment by qq734504513** [comment]
本地环境




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年9月14日(星期一) 中午11:38
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "陈洪圣"<734504513@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 所有类型的角色都没有编辑用户管理的权限 (#1726)





 
本地还是演示环境？
