### ISSUE TITLE
jeecg 2.3 管理员还是没有编辑用户管理的权限

### ISSUE THREAD

**Issue by qq734504513** [zhangdaiscott/jeecg-boot#1729]
##### 截图&代码：更新后的类如下：
![image](https://user-images.githubusercontent.com/39591043/93050302-3a7c3500-f695-11ea-8397-e2f59c0bda88.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没权限提示什么？

**Comment by zhangdaiscott** [comment]
@RequiresPermissions("user:edit")
这个也注释掉

**Comment by qq734504513** [comment]
> 没权限提示什么？

没有权限，请联系管理员授权，似乎像这种@RequiresPermissions注解失效了

**Comment by qq734504513** [comment]
> @RequiresPermissions("user:edit")
> 这个也注释掉

这个注释掉，权限的功能不是没了吗，而且还有上传功能也不行

**Comment by zhangdaiscott** [comment]
上传了更新代码吧

**Comment by qq734504513** [comment]
> 上传了更新代码吧
请问这边注释掉后，后端是不是失去了对权限的控制，只能通过前端按钮的显示隐藏，或者禁用来进行权限的控制

**Comment by zhangdaiscott** [comment]
需要控制，就放开

**Comment by tudyzhb** [comment]
请注意，**/sys/user/edit** 接口目前处在不受 **@RequiresRoles({"admin"})** 保护的状态！希望官方尽快处理这个问题。

**Comment by zhangdaiscott** [comment]
默认都注释了，是不是你自己放开注释了

**Comment by mmt1202** [comment]
为什么现在用在线开发生成的代码也没有编辑权限呀
