### ISSUE TITLE
修改 qutz_ 前缀的表名为大写，用于修复 jeecg 项目中 Qrutz 表名不区分大小写在 Linux 和 Mac 上的报错

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#1732]
我创建了一个 pr，如果有时间您可以审阅一下，谢谢。🙏🙏🙏

##### 版本号：
2.3

##### 问题描述：
由于在 Linux 和 Mac 下 MySQL 默认是区分大小写，且官方不建议修改为不区分大小写。
目前 MySQL8 无法在不删除数据的情况下改为不区分大小写，所以 Qurtz 相关的表会报错

##### 截图&代码：
我创建了一个 pr，修改 qutz_ 前缀的表名为大写，用于修复 jeecg 项目中 Qrutz 表名不区分大小写在 Linux 和 Mac 上的报错。我这里测试是没问题。gitee 我也提了 pr。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，感谢

**Comment by CharlieJ0hn** [comment]
我发现还有其他 SYS_ 开头的表也这样，这就比较麻烦了。mysql8 必须在初始化数据库之前就写好配置，后期是无法修改配置的。

**Comment by eelzs** [comment]
为了解决这个问题前几天我还特意把自己docker中的mysql8整成了 表名不区分大小写😂

**Comment by 224148793** [comment]
这个确实是个大问题，我们原来也碰到这个问题，mysql是客户维护的，我们还不能修改，就非常麻烦

**Comment by zhangdaiscott** [comment]
[Uploading qutz_单独执行数据库脚步——支持多数据库.zip…]()

**Comment by CharlieJ0hn** [comment]
@zhangdaiscott 还有sys开头的表有这个问题。
