### ISSUE TITLE
online表单新增表时,全屏问题

### ISSUE THREAD

**Issue by csainx** [zhangdaiscott/jeecg-boot#1734]
##### 问题描述：
online表单，新增表，全屏时，表格控件无法自动大小

##### 截图&代码：

![Image 067](https://user-images.githubusercontent.com/50067476/93069873-bd5eb900-f6b0-11ea-92b0-21befb4d9cb8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自动大小什么意思

**Comment by csainx** [comment]
重新贴了图，说明
那个表格，距离下面还有好大距离

**Comment by csainx** [comment]
> 自动大小什么意思
重新贴了图，说明
那个表格，距离下面还有好大距离

**Comment by zhangdaiscott** [comment]
目前暂时没实现这功能
