### ISSUE TITLE
2.3.0单体升级微服务后，swagger有多个分组时出现错误

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1736]
##### 问题描述：
2.3版本 单体升级微服务后，swagger有多个分组时出现错误，控制台报错，找不到http://127.0.0.1:9999/jeecg-system/v2/api-docs
（直接访问7001不走geteway可以正常访问）
造成原因： geteway模块拼接swagger地址 ，没有带上?group=系统system
地址应该为：http://127.0.0.1:9999/jeecg-system/v2/api-docs?group=系统system

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31750150/93154634-b084a880-f736-11ea-840e-c6c89eb3f9bc.png)

![image](https://user-images.githubusercontent.com/31750150/93154554-77e4cf00-f736-11ea-891b-18c97074f086.png)

![image](https://user-images.githubusercontent.com/31750150/93154513-613e7800-f736-11ea-8cfa-92f8c6986394.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不太清楚你的操作，这边测试无问题
![image](https://user-images.githubusercontent.com/3162115/94224929-4209cc80-ff26-11ea-985b-9cbca2fe0586.png)
