### ISSUE TITLE
【JEditableTable 】求教！获取某行某列的控件，控制是否可编辑

### ISSUE THREAD

**Issue by missKomorebi** [zhangdaiscott/jeecg-boot#1737]
##### 版本号：
v2.2.0

##### 问题描述：
目标：JEditableTable  控制某一行某一列的控件，不可编辑
问题：不知道如何获取到某一行某一列的控件
请教

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49051538/93155133-ee360100-f737-11ea-8216-88be47509393.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你可以循环判断json数据，修改disable属性值
![image](https://user-images.githubusercontent.com/3162115/93298812-827e9180-f826-11ea-9cd8-774f86a6623d.png)
