### ISSUE TITLE
[问题]如何处理对sys_user多租户管理产生的问题

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1739]
##### 版本号：

2.3
##### 问题描述：

把sys_user加入多租户管理会出现一个问题，即登录的时候还没有租户id，以下代码不起作用

String tenant_id = httpServletRequest.getHeader(CommonConstant.TENANT_ID);
TenantContext.setTenant(tenant_id);

所以在login方法中查询用户会报错。
SysUser sysUser = sysUserService.getOne(queryWrapper);

这种情况怎么处理？
##### 截图&代码：

![image](https://user-images.githubusercontent.com/8335270/93180933-65848880-f76a-11ea-8f0f-a8de800e9f6d.png)

![image](https://user-images.githubusercontent.com/8335270/93180912-5f8ea780-f76a-11ea-905e-1465d9c42be4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重复问题关闭
https://github.com/zhangdaiscott/jeecg-boot/issues/1699
