### ISSUE TITLE
JAVA访问权限控制 无法使用的问题

### ISSUE THREAD

**Issue by qq734504513** [zhangdaiscott/jeecg-boot#1740]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/39591043/93183847-15a7c080-f76e-11ea-8ad6-85be23bb401a.png)
![image](https://user-images.githubusercontent.com/39591043/93183914-307a3500-f76e-11ea-9dbe-97f0f66a8343.png)
![image](https://user-images.githubusercontent.com/39591043/93183969-44be3200-f76e-11ea-81b0-836d9c7058d8.png)
![image](https://user-images.githubusercontent.com/39591043/93184856-52c08280-f76f-11ea-9563-1faa9c95c9f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by qq734504513** [comment]
我回到2.2.1测试了这个功能是可以的，步骤一样

**Comment by zhangdaiscott** [comment]
的确存在问题

修改方案：
修改
org.jeecg.common.constant.CommonConstant#PREFIX_USER_SHIRO_CACHE
值为 "shiro:cache:org.jeecg.config.shiro.ShiroRealm.authorizationCache:";

**Comment by zhangdaiscott** [comment]
代码也已经上传更新了

**Comment by Linyuxujun** [comment]
更改了包名，还是直接使用shiro:cache:org.jeecg.config.shiro.ShiroRealm.authorizationCache: ？  还是说是 shiro:cache:com.test.config.shiro.ShiroRealm.authorizationCache: ?
