### ISSUE TITLE
[bug]online表单开发中权限控制的勾选框没反应。

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1741]
##### 版本号：
2.3

##### 问题描述：
online表单开发->权限控制，字段权限中的“可见”、“可编辑”点击后没反应。
点击后应该是起作用了，但是勾选框没有相应勾选或取消勾选。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/8335270/93214428-c1b1d180-f797-11ea-833a-ed6d7be0a53a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在问题

**Comment by zhangdaiscott** [comment]
修改配置文件 jeecg-boot-base-common/pom.xml 把依赖hibernate-re版本改成2.3.01

<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-re</artifactId>
  <version>2.3.02</version>
</dependency>

**Comment by zhangdaiscott** [comment]
相关问题
https://github.com/zhangdaiscott/jeecg-boot/issues/1733

**Comment by yanchenchen** [comment]
已经改过了，改过后的问题。

**Comment by zhangdaiscott** [comment]
改成 2.3.02
