### ISSUE TITLE
online表单开发，同步数据库失败

### ISSUE THREAD

**Issue by csainx** [zhangdaiscott/jeecg-boot#1742]
##### 问题描述：
online表单开发，同步数据库失败

##### 截图&代码：

![jeecgboot-error02](https://user-images.githubusercontent.com/50067476/93220689-6d125480-f79f-11ea-9166-dc2e7b583713.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
错误太少了

**Comment by csainx** [comment]
> 错误太少了

今天我又测试了下，我在idea中运行项目，是可以同步成功的，但打成jar包后，运行，就会同步数据失败
jar包启动的时候，会提示一个问：（下图）
![Image 068](https://user-images.githubusercontent.com/50067476/93288642-f14ff080-f80e-11ea-8c4f-b41b97fc3f86.png)
在前端点击数据同步时，后提报错：（下图）
![Image 070](https://user-images.githubusercontent.com/50067476/93288687-0f1d5580-f80f-11ea-8125-07e4be32905e.png)

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
65

**Comment by csainx** [comment]
👍✔✔✔😊😁💪
