### ISSUE TITLE
jeecg-boot-2.2.1编译提示缺少jar

### ISSUE THREAD

**Issue by qhyu** [zhangdaiscott/jeecg-boot#1744]
##### 版本号：
jeecg-boot-2.2.1

##### 问题描述：
后端代码编译时，提示缺少jar包。

##### 截图&代码：

[ERROR] Failed to execute goal on project jeecg-boot-base-common: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-base-common:jar:2.2.1: The following artifacts could not be resolved: org.hibernate:hibernate-re:jar:2.2.11, org.jeecgframework.boot:codegenerate:jar:1.2.0: Failure to find org.hibernate:hibernate-re:jar:2.2.11 in https://maven.aliyun.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyunmaven has elapsed or updates are forced -> [Help 1]

![image](https://user-images.githubusercontent.com/18611059/93297077-2a925b80-f823-11ea-879c-15b41b8304c4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273965
