### ISSUE TITLE
建议定时器使用id去区分唯一，目前使用class，很不方便

### ISSUE THREAD

**Issue by 2767321434** [zhangdaiscott/jeecg-boot#1745]
##### 问题描述：建议定时器使用id去区分唯一，目前使用class，很不方便，无法启动多个，实现同一功能需要重复写多个定时器方法
最新版的看源码还是使用classname做为唯一定时器区分

##### 截图&代码：
jeecg-boot/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/quartz/service/impl/QuartzJobServiceImpl.java  

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版已经支持xxl-job了
