### ISSUE TITLE
没有提供Nacos配置文件

### ISSUE THREAD

**Issue by wskqqw** [zhangdaiscott/jeecg-boot#1746]
版本号：2.3.0

问题描述：没有提供Nacos配置文件jeecg-cloud-application-beta.yml和jeecg-cloud-gateway-beta.yml

截图&代码：
文档截图
![image](https://user-images.githubusercontent.com/48768539/93312557-efe7ed80-f839-11ea-894d-bcd7014c85a9.png)
代码截图
![image](https://user-images.githubusercontent.com/48768539/93312908-5836cf00-f83a-11ea-8402-e0dce4fbd2c8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
application-dev.yml
![image](https://user-images.githubusercontent.com/3162115/93324400-6986d800-f848-11ea-8633-aaea0d8d148a.png)
