### ISSUE TITLE
jeecg-boot单体应用中，往数据库sys_depart中添加数据后，在页面上不显示

### ISSUE THREAD

**Issue by zhangsir001** [zhangdaiscott/jeecg-boot#1747]
##### 版本号：
2.3

##### 问题描述：

jeecg-boot单体应用中，往数据库sys_depart中添加数据后，重启应用，清楚浏览器缓存，部门管理页面不显示添加的内容  只有点级添加部门的按钮，添加上一条新的数据后，原先在数据库中添加的数据才会被显示。

##### 截图&代码：
![1 原先的页面](https://user-images.githubusercontent.com/51689206/93316004-422b0d80-f83e-11ea-9e9e-169dc8ad87b3.png)
![2往数据库中插入一条数据](https://user-images.githubusercontent.com/51689206/93316017-45be9480-f83e-11ea-8eb6-49b200c9a24d.png)
![3只有再页面上添加一条数据](https://user-images.githubusercontent.com/51689206/93316029-49521b80-f83e-11ea-9771-72d8829b9c91.png)
![4页面上才显示](https://user-images.githubusercontent.com/51689206/93316036-4bb47580-f83e-11ea-82ba-67c15b41139a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tanpenggood** [comment]
因为查询接口`sys/sysDepart/queryTreeList`做了缓存优化。

如果绕过后端，直接对数据库中的数据进行操作，缓存中的数据并没有更新。
