### ISSUE TITLE
系统中使用popup插件数据不刷新，需要点击查询或者刷新才可以，请问是有地方可以配置或者在哪里改？

### ISSUE THREAD

**Issue by FirstMemory** [zhangdaiscott/jeecg-boot#1749]
##### 版本号：
2.2

##### 问题描述：
系统中使用popup插件数据不刷新，需要点击查询或者刷新才可以，请问是有地方可以配置或者在哪里改？
表体中使用FormTypes.popup同样存在该问题
##### 截图&代码：
![image](https://user-images.githubusercontent.com/31384429/93342976-87f9cd00-f862-11ea-91c3-8efa438c3ac4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修改完成，下个版本发布
