### ISSUE TITLE
打jar包运行报错找不到文件

### ISSUE THREAD

**Issue by awayzhou** [zhangdaiscott/jeecg-boot#175]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/jeecg/common/system/base/controller
/JeecgController.class] cannot be opened because it does not exist

**Comment by zhangdaiscott** [comment]
pom打包加上

<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

**Comment by zhangdaiscott** [comment]
打jar包加上
![image](https://user-images.githubusercontent.com/3162115/58801348-da4ab680-863c-11e9-86d3-064dc7ce2371.png)

**Comment by awayzhou** [comment]
> 打jar包加上
> ![image](https://user-images.githubusercontent.com/3162115/58801348-da4ab680-863c-11e9-86d3-064dc7ce2371.png)

已经加了
<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
