### ISSUE TITLE
online模块中，js增强的mounted函数无效

### ISSUE THREAD

**Issue by bokix** [zhangdaiscott/jeecg-boot#1752]
##### 版本号：
2.3.0 ， 2.2.0

##### 问题描述：
从上个版本就有此问题，在js增强中定义了list的mounted钩子函数，页面加载时此函数无效。

##### 截图&代码：
mounted(){
alert('mounted');
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
确有此问题 并且已弃用 因为页面加载数据和mounted执行 是平行的  有可能是当前JS增强还未加载出来 就执行了mounted的内容导致实际的js增强方法未按预期走  请尝试使用created  或者有别的需求？

**Comment by bokix** [comment]
最根本的原因是：在线表单模块生成的页面，其组件并不能完全满足业务上的需求，比如复杂的联动下拉框、日期组件需要自定义的格式化、以及其他一些组件的个性化定义，本想着在mounted函数中可以对组件进行修改，这样一来就行不通了。

另外，在线表单生成的组件上，是不是都可以把 ref id 加上？

**Comment by tygithub1** [comment]
表单页走loaded 列表走created

**Comment by bokix** [comment]
created的时候，页面上的子组件生命周期都还没开始呢，怎么搞？

**Comment by tygithub1** [comment]
那就整不了

**Comment by bokix** [comment]
Thanks
