### ISSUE TITLE
选取职务名称出现全选

### ISSUE THREAD

**Issue by createnana** [zhangdaiscott/jeecg-boot#1753]
##### 版本号：
2.3

##### 问题描述：
连续勾选几个角色之后点击搜索, 角色全部勾选了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12572607/93436562-8a5d3500-f8fd-11ea-9af5-79b14b83c70a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
覆盖此文件

[JSelectBizComponentModal.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5288083/JSelectBizComponentModal.zip)
