### ISSUE TITLE
找不到jeecg-cloud-module在其子目录config下有两个配置文件

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-boot#1754]
##### 问题描述：找不到jeecg-cloud-module在其子目录config下有两个配置文件，jeecg-cloud-application-beta.yml ： 每一个服务使用的配置
jeecg-cloud-gateway-beta.yml ：gateway使用的配置。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg-cloud-module\jeecg-cloud-gateway\src\main\resources\application-dev.yml
用这个

**Comment by zhangdaiscott** [comment]
已经上传代码了，请更新
