### ISSUE TITLE
主子表固定列样式问题

### ISSUE THREAD

**Issue by lch245298** [zhangdaiscott/jeecg-boot#1755]
##### 问题描述：
在主子表页面中，如果固定主表后边几列，展开子表时出现样式问题
##### 截图&代码：
 
![QQ截图20200917170006](https://user-images.githubusercontent.com/62693683/93449873-dca35380-f907-11ea-898f-b6b70504e52f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个是自己写的代码吗？
如果自己写的自己调整代码即可

**Comment by lch245298** [comment]
> 这个是自己写的代码吗？
> 如果自己写的自己调整代码即可

这是按照官方教程做的主子表，做出来就是这效果
