### ISSUE TITLE
导入Excel，随便一个Excel都能被导入

### ISSUE THREAD

**Issue by xu-bin-bin** [zhangdaiscott/jeecg-boot#1756]
##### 版本号：
jar包   autopoi-web  1.1.1和1.2.1版本

##### 问题描述：
导入Excel，随便一个Excel都能被导入，只不过存储到数据库中的值除了创建人，修改人、创建时间和修改时间以外，其他都为null。即使实体类的属性上设置了@ExcelVerify(notNull = true)，还是存在可以导入。

##### 截图&代码：
    @ExcelVerify(notNull = true)
    private java.lang.String business;
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经提供方案，下个版本发布

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2004485
