### ISSUE TITLE
请教在去掉路径中的jeecg-boot后，nginx该如何配置呢？

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#176]
请教在去掉路径中的jeecg-boot后，nginx该如何配置呢？
目前的情况是开发环境去掉了没问题，但是部署到nginx下无法登陆。
我个人理解是proxy_pass的配置错误，但是nginx实在不熟悉。
请教下，谢谢！

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
5
