### ISSUE TITLE
切换微服务后无法使用Online相关功能

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-boot#1760]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你怎么配置的

**Comment by Qiang-Ming** [comment]
> 你怎么配置的

按文档说明配置的，只改了数据库连接，如果是配置问题，我应该检查哪些配置呢？

**Comment by zhangdaiscott** [comment]
用这个配置文件
https://github.com/zhangdaiscott/jeecg-boot/blob/master/jeecg-boot/jeecg-cloud-module/config/jeecg-cloud-gateway-beta.yml
