### ISSUE TITLE
切换导航模式，导致菜单栏丢失

### ISSUE THREAD

**Issue by helloquan** [zhangdaiscott/jeecg-boot#1763]
##### 问题描述：
1、导航模式为【侧边栏导航】
     点击左上角按钮，收缩文字后，滚动条消失，无法查看页面下面的内容

2、导航模式切换到【顶部栏导航】，然后再切回【侧边栏导航】
     导致菜单栏丢失，无法唤出

将GlobalLayout.vue还原成v2.2.1的版本后，问题消失

##### 截图&代码：
1、
![image](https://user-images.githubusercontent.com/19152564/93546288-17070200-f995-11ea-9045-9709d4d84b6b.png)

2、
![image](https://user-images.githubusercontent.com/19152564/93546484-6d744080-f995-11ea-944b-ced6665c8fae.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tanpenggood** [comment]
已修复，将在下一版本更新。


解决方案
`src/components/page/GlobalLayout.vue`：
```
6 - v-show="device === 'mobile'"
6 + v-if="device === 'mobile'"
```

**Comment by zhangdaiscott** [comment]
改这个问题 https://github.com/zhangdaiscott/jeecg-boot/issues/1763
导致的
