### ISSUE TITLE
j-select-user-by-dep 组件bug

### ISSUE THREAD

**Issue by ssuhvs** [zhangdaiscott/jeecg-boot#1764]
##### 问题描述：

`  <j-select-user-by-dep placeholder="请选择人员"  v-decorator="['operator', {}]" :trigger-change="true"></j-select-user-by-dep>`
   组件无法回显之前保存下来的信息
目前只能改为： 
   `<j-select-user-by-dep placeholder="请选择人员"   v-model="model.operator"  :trigger-change="false"></j-select-user-by-dep>`
虽然可以实现，但是无法直接使用规则校验了
请问是不是bug 
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tanpenggood** [comment]
经测试，你描述的问题未能复现。

在使用时`v-decorator`指令进行绑定数据，请确保你的`form`对象为：`this.$form.createForm(this)`
