### ISSUE TITLE
JAVA访问权限控制 错误

### ISSUE THREAD

**Issue by Linyuxujun** [zhangdaiscott/jeecg-boot#1766]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/45812406/93561632-24cd7f00-f9b7-11ea-8aa2-58baa11a1fa1.png)

![image](https://user-images.githubusercontent.com/45812406/93561782-5f371c00-f9b7-11ea-9106-24bf7e862ba7.png)
![image](https://user-images.githubusercontent.com/45812406/93561820-7249ec00-f9b7-11ea-88d0-dff6c0c0b706.png)
![image](https://user-images.githubusercontent.com/45812406/93561836-78d86380-f9b7-11ea-819f-2a9fa9f76f8b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经解决了，看这个
https://github.com/zhangdaiscott/jeecg-boot/issues/1740
