### ISSUE TITLE
前端框架上Eslint代码规范之后报JDate `default value` can not collect,  please use `option.initialValue` to set default value.

### ISSUE THREAD

**Issue by lifizer** [zhangdaiscott/jeecg-boot#1767]
**版本： 2.2.1**
问题描述：
Warning: JDate `default value` can not collect,  please use `option.initialValue` to set default value.
Warning: j-editor `default value` can not collect,  please use `option.initialValue` to set default value.

**截图如下**
![setDefaultValue](https://user-images.githubusercontent.com/9350574/93573832-32d8cb00-f9ca-11ea-8097-344cf1b9a33e.png)

**Comment by zhangdaiscott** [comment]
现在支持v-model模式绑定值
