### ISSUE TITLE
内嵌子表主题(一对多) 生成 菜单 问题

### ISSUE THREAD

**Issue by woszzc** [zhangdaiscott/jeecg-boot#1769]
##### 问题描述：
内嵌子表主题(一对多) 生成 菜单 问题,展开内嵌  行内菜单有问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30471937/93728306-f12a6900-fbf1-11ea-974b-6c06211e71c2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经解决，请更新代码
