### ISSUE TITLE
代码生成一对多在idea中报红，生成代码其它没问题，唯独mapper生成失败

### ISSUE THREAD

**Issue by 1783681442** [zhangdaiscott/jeecg-boot#177]
<#list subTables as subTab>
<#assign originalForeignKeys = subTab.originalForeignKeys>
#segment#${subTab.entityName}Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="${bussiPackage}.${entityPackage}.mapper.${subTab.entityName}Mapper">

	<delete id="deleteByMainId" parameterType="java.lang.String">
		DELETE 
		FROM  ${subTab.tableName} 
		WHERE
		<#list originalForeignKeys as key>
		<#if key?lower_case?index_of("${primaryKeyField}")!=-1>
			 ${key} = ${r'#'}{${primaryKeyField}} <#rt/>
		<#else>
			 ${key} = ${r'#'}{${key}} <#rt/>
		</#if>
		<#if key_has_next>AND</#if>
		</#list>
	</delete>
	
	<select id="selectByMainId" parameterType="java.lang.String" resultType="${bussiPackage}.${entityPackage}.entity.${subTab.entityName}">
		SELECT * 
		FROM  ${subTab.tableName}
		WHERE
		<#list originalForeignKeys as key>
		<#if key?lower_case?index_of("${primaryKeyField}")!=-1>
			 ${key} = ${r'#'}{${primaryKeyField}} <#rt/>
		<#else>
			 ${key} = ${r'#'}{${key}} <#rt/>
		</#if>
		<#if key_has_next>AND</#if>
		</#list>
	</select>
</mapper>
</#list>

**Comment by 1783681442** [comment]
上面三行报红，其它零星地方报红，不知何故

**Comment by zhangdaiscott** [comment]
那个版本？

**Comment by 1783681442** [comment]
新版本2.0啊

**Comment by 1783681442** [comment]
![生成后的 1-n Mapper xml文件](https://user-images.githubusercontent.com/31495623/58842830-7c50ba00-86a2-11e9-9c58-70896adf4a59.jpg)

**Comment by 1783681442** [comment]
代码生成的Mapper.xml文件在idea中报错
![xml文件报错](https://user-images.githubusercontent.com/31495623/58843141-cb4b1f00-86a3-11e9-95b4-341c85345e43.jpg)

**Comment by 1783681442** [comment]
刚试了的，连最新版2.0.1导入idea中代码生成的Mapper.xml文件都报错

**Comment by zhangdaiscott** [comment]
升级2.0.1不会有问题

**Comment by 1783681442** [comment]
把新下载的2.0.1版导入idea还是一样啊！模板mapper.xml文件一样报红，是不是跟idea工具有关系

**Comment by zhangdaiscott** [comment]
模板报错 不影响
