### ISSUE TITLE
【bug】树类型的列表 编辑之后 不加载子节点

### ISSUE THREAD

**Issue by 1195999342** [zhangdaiscott/jeecg-boot#1770]
##### 问题描述：
js写错了  生成的页面里面 loadDataByExpandedRows 方法里面 
![image](https://user-images.githubusercontent.com/26251311/93729494-49179e80-fbf7-11ea-9b9e-b4a34e602947.png)
父id你们还是用的默认的属性 我这边自定义了父id字段
下面的map set的时候建议key转成字符串 
##### 截图&代码：
修改后的代码
`      // 根据已展开的行查询数据（用于保存后刷新时异步加载子级的数据）
      loadDataByExpandedRows(dataList) {
        let that = this;
        if (this.expandedRowKeys.length > 0) {
          return getAction(this.url.getChildListBatch,{ parentIds: this.expandedRowKeys.join(',') }).then(res=>{
            if (res.success && res.result.records.length>0) {
              //已展开的数据批量子节点
              let records = res.result.records
              const listMap = new Map();
              for (let item of records) {
                let pid = item[that.pidField];
                if (this.expandedRowKeys.join(',').includes(pid)) {
                 let mapList = listMap.get(pid+"");
                  if (mapList == null) {
                    mapList = [];
                  }
                  mapList.push(item);
                  listMap.set(pid+"", mapList);
                }
              }
              let childrenMap = listMap;
              let fn = (list) => {
                list.forEach(data => {
                  if (this.expandedRowKeys.includes(data.id)) {
                    data.children = this.getDataByResult(childrenMap.get(data.id+""))
                    if(data.children)fn(data.children)
                  }
                })
              }
              fn(dataList)
            }
          })
        } else {
          return Promise.resolve()
        }
      },`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待新版本发布
