### ISSUE TITLE
微服务版本的其他业务模块的Dict切面不生效问题

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1771]
##### 问题描述：
当前版本的其他业务模块（自己编写的业务代码，类似提供的demo模块）中的Dict切面不生效，导致分页查询后返回给前端的数据，只有字典值列，没有名称列，即没有翻译出 xxx_dictText 这样的字段。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by jave-joe** [comment]
> 收录

我把写在system模块的dict的service里的一些方法（translateDict和translateDictFromTable等）提到common模块里了，其他所有的业务模块都引用common模块，这样就可以了。

**Comment by zhangdaiscott** [comment]
是不是因为通过服务接口，调用返回字典值太慢？
目前逻辑是没问题的

**Comment by jave-joe** [comment]
> 是不是因为通过服务接口，调用返回字典值太慢？
> 目前逻辑是没问题的

我这边再测测。

**Comment by zhangdaiscott** [comment]
这边测试没有问题，有问题你再反馈吧

**Comment by lanwaixian** [comment]
遇到同样的问题：在自己新增的后端module里，原本后端一样的代码，升级到2.3以后，现在前端返回json里都不带_dictText后缀的属性了

**Comment by luoliang222** [comment]
我重新了这个问题，跟踪问题是因为不能正确获得子模块的类信息，导致不能翻译出字典内容；
![image](https://user-images.githubusercontent.com/8930106/103021205-c222eb00-4584-11eb-9882-22f8f267521c.png)
