### ISSUE TITLE
JPopup 是否支持动态参数？

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#1772]
##### 问题描述：
看开发文档里面JPopup弹窗控件有动态参数对象param，但查看源码JPopup没有定义这个属性。
请问动态参数要如何使用，能否开发文档上弄个示例，谢谢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本发布
