### ISSUE TITLE
jeecg-cloud-application-beta.yml有配置重复问题

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#1775]
##### 版本号：

2.3
##### 问题描述：
jeecg-cloud-module/config/jeecg-cloud-application-beta.yml的配置有重复

##### 截图&代码：
具体重复的配置是210行和233行的jmreport节点

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
感谢，已经修复，其实也不影响功能，放心用
