### ISSUE TITLE
[bug]online表单开发相关，自定义字段名称是否不能用type

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1777]
##### 版本号：

2.3
##### 问题描述：

如果定义了一个字段是type，则在列表页面是没有办法展示的？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/8335270/93744573-a7a74180-fc24-11ea-9868-cfa4fb664226.png)

![image](https://user-images.githubusercontent.com/8335270/93743433-a2e18e00-fc22-11ea-99bf-6f015ee8e0cf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该不会吧，报错吗

**Comment by yanchenchen** [comment]
没有报错，就是不能展示
定义了name（设备名称）、model（设备型号）、type（设备类型）
列表展示了设备名称（name）和设备型号（model），没有设备类型（type）

**Comment by i-Hu** [comment]
![QQ图片20200925092806](https://user-images.githubusercontent.com/26364818/94216305-9d7d8f80-ff11-11ea-9893-dcc8e5cc22f4.png)
![QQ图片20200925092813](https://user-images.githubusercontent.com/26364818/94216312-a0788000-ff11-11ea-8fe6-7dda233452e6.png)
是不是页面属性里没有勾选显示，我测试没问题

**Comment by zhangdaiscott** [comment]
测试没问题，关闭

![image](https://user-images.githubusercontent.com/3162115/94252428-7eedb780-ff56-11ea-87a7-0e9beb7d28f1.png)

![image](https://user-images.githubusercontent.com/3162115/94252403-74332280-ff56-11ea-82d0-29ed4c01bc3b.png)
