### ISSUE TITLE
正式环境Redis的keys问题

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#1778]
##### 问题描述：
基本生产环境的redis是不允许使用keys的，都会使用scan来替代；
目前spring框架的@CacheEvict注解，allEntries=true会使用keys，建议做下优化 。

##### 截图&代码：
目前在RedisUtil中添加了以下方法来做替代，以供参考

        /**
	 *  获取指定前缀的一系列key
	 *  使用scan命令代替keys, Redis是单线程处理，keys命令在KEY数量较多时，
	 *  操作效率极低【时间复杂度为O(N)】，该命令一旦执行会严重阻塞线上其它命令的正常请求
	 * @param keyPrefix
	 * @return
	 */
	public Set<String> scan(String keyPrefix) {
		return redisTemplate.execute((RedisCallback<Set<String>>) connection -> {
			Set<String> keys = new HashSet<>();
			Cursor<byte[]> cursor = connection.scan(new ScanOptions.ScanOptionsBuilder()
					.match(keyPrefix).count(Long.MAX_VALUE).build());
			while (cursor.hasNext()) {
				keys.add(new String(cursor.next()));
			}
			return keys;
		});
	}

	/**
	 *  删除指定前缀的一系列key
	 * @param keyPrefix
	 */
	public void removeAll(String keyPrefix) {
		try {
			Set<String> keys = scan(keyPrefix);
			redisTemplate.delete(keys);
		} catch (Throwable e) {
			e.printStackTrace();
		}
	}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录

**Comment by jajasper** [comment]
I hava find the same questions.
I use method to solute this quesion.

`//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package org.jeecg.common.modules.redis.writer;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;
import java.util.function.Function;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.PessimisticLockingFailureException;
import org.springframework.data.redis.cache.CacheStatistics;
import org.springframework.data.redis.cache.CacheStatisticsCollector;
import org.springframework.data.redis.cache.RedisCacheWriter;
import org.springframework.data.redis.connection.RedisConnection;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.RedisStringCommands.SetOption;
import org.springframework.data.redis.core.Cursor;
import org.springframework.data.redis.core.ScanOptions;
import org.springframework.data.redis.core.types.Expiration;
import org.springframework.lang.Nullable;
import org.springframework.util.Assert;

public class JeecgRedisCacheWriter implements RedisCacheWriter {
    private static final Logger log = LoggerFactory.getLogger(JeecgRedisCacheWriter.class);
    private final RedisConnectionFactory connectionFactory;
    private final Duration sleepTime;
    private final CacheStatisticsCollector statistics;

    public JeecgRedisCacheWriter(RedisConnectionFactory connectionFactory) {
        this(connectionFactory, Duration.ZERO);
    }

    public JeecgRedisCacheWriter(RedisConnectionFactory connectionFactory, Duration sleepTime) {
        this.statistics = CacheStatisticsCollector.create();
        Assert.notNull(connectionFactory, "ConnectionFactory must not be null!");
        Assert.notNull(sleepTime, "SleepTime must not be null!");
        this.connectionFactory = connectionFactory;
        this.sleepTime = sleepTime;
    }

    public void put(String name, byte[] key, byte[] value, @Nullable Duration ttl) {
        Assert.notNull(name, "Name must not be null!");
        Assert.notNull(key, "Key must not be null!");
        Assert.notNull(value, "Value must not be null!");
        this.execute(name, (connection) -> {
            if (shouldExpireWithin(ttl)) {
                connection.set(key, value, Expiration.from(ttl.toMillis(), TimeUnit.MILLISECONDS), SetOption.upsert());
            } else {
                connection.set(key, value);
            }

            return "OK";
        });
    }

    public byte[] get(String name, byte[] key) {
        Assert.notNull(name, "Name must not be null!");
        Assert.notNull(key, "Key must not be null!");
        return (byte[]) ((byte[]) this.execute(name, (connection) -> {
            return connection.get(key);
        }));
    }

    public byte[] putIfAbsent(String name, byte[] key, byte[] value, @Nullable Duration ttl) {
        Assert.notNull(name, "Name must not be null!");
        Assert.notNull(key, "Key must not be null!");
        Assert.notNull(value, "Value must not be null!");
        return (byte[]) ((byte[]) this.execute(name, (connection) -> {
            if (this.isLockingCacheWriter()) {
                this.doLock(name, connection);
            }

            Object var7;
            try {
                boolean put;
                if (shouldExpireWithin(ttl)) {
                    put = connection.set(key, value, Expiration.from(ttl), SetOption.ifAbsent());
                } else {
                    put = connection.setNX(key, value);
                }

                if (!put) {
                    byte[] var11 = connection.get(key);
                    byte[] var9 = var11;
                    return var9;
                }

                var7 = null;
            } finally {
                if (this.isLockingCacheWriter()) {
                    this.doUnlock(name, connection);
                }

            }

            return (byte[]) ((byte[]) var7);
        }));
    }

    public void remove(String name, byte[] key) {
        Assert.notNull(name, "Name must not be null!");
        Assert.notNull(key, "Key must not be null!");
        String keyString = new String(key);
        log.info("redis remove key:" + keyString);
        String keyIsAll = "*";
        if (keyString != null && keyString.endsWith(keyIsAll)) {
            this.execute(name, (connection) -> {
                Set<byte[]> keys = connection.keys(key);
                int delNum = 0;

                byte[] keyByte;
                for (Iterator var4 = keys.iterator(); var4.hasNext(); delNum = (int) ((long) delNum + connection.del(new byte[][]{keyByte}))) {
                    keyByte = (byte[]) var4.next();
                }

                return delNum;
            });
        } else {
            this.execute(name, (connection) -> {
                return connection.del(new byte[][]{key});
            });
        }

    }

    public void clean(String name, byte[] pattern) {
        Assert.notNull(name, "Name must not be null!");
        Assert.notNull(pattern, "Pattern must not be null!");
        this.execute(name, (connection) -> {
            boolean wasLocked = false;

            try {
                if (this.isLockingCacheWriter()) {
                    this.doLock(name, connection);
                    wasLocked = true;
                }

                //byte[][] keys = (byte[][])((byte[][])((Set)Optional.ofNullable(connection.keys(pattern)).orElse(Collections.emptySet())).toArray(new byte[0][]));

                Set<byte[]> binaryKeys = new HashSet();
                Cursor cursor = connection.scan(ScanOptions.scanOptions().match(pattern).count(2147483647L).build());
                while(cursor.hasNext()) {
                    binaryKeys.add((byte[])cursor.next());
                }

                byte[][] keys = (byte[][]) ((byte[][]) ((Set) Optional.ofNullable(binaryKeys).orElse(Collections.emptySet())).toArray(new byte[0][]));
                if (keys.length > 0) {
                    connection.del(keys);
                }
            } finally {
                if (wasLocked && this.isLockingCacheWriter()) {
                    this.doUnlock(name, connection);
                }

            }

            return "OK";
        });
    }

    void lock(String name) {
        this.execute(name, (connection) -> {
            return this.doLock(name, connection);
        });
    }

    void unlock(String name) {
        this.executeLockFree((connection) -> {
            this.doUnlock(name, connection);
        });
    }

    private Boolean doLock(String name, RedisConnection connection) {
        return connection.setNX(createCacheLockKey(name), new byte[0]);
    }

    private Long doUnlock(String name, RedisConnection connection) {
        return connection.del(new byte[][]{createCacheLockKey(name)});
    }

    boolean doCheckLock(String name, RedisConnection connection) {
        return connection.exists(createCacheLockKey(name));
    }

    private boolean isLockingCacheWriter() {
        return !this.sleepTime.isZero() && !this.sleepTime.isNegative();
    }

    private <T> T execute(String name, Function<RedisConnection, T> callback) {
        RedisConnection connection = this.connectionFactory.getConnection();

        try {
            this.checkAndPotentiallyWaitUntilUnlocked(name, connection);
            return callback.apply(connection);
        } finally {
            connection.close();
        }

    }

    private void executeLockFree(Consumer<RedisConnection> callback) {
        RedisConnection connection = this.connectionFactory.getConnection();

        try {
            callback.accept(connection);
        } finally {
            connection.close();
        }

    }

    private void checkAndPotentiallyWaitUntilUnlocked(String name, RedisConnection connection) {
        if (this.isLockingCacheWriter()) {
            try {
                while (this.doCheckLock(name, connection)) {
                    Thread.sleep(this.sleepTime.toMillis());
                }
            } catch (InterruptedException var4) {
                Thread.currentThread().interrupt();
                throw new PessimisticLockingFailureException(String.format("Interrupted while waiting to unlock cache %s", name), var4);
            }
        }

    }

    private static boolean shouldExpireWithin(@Nullable Duration ttl) {
        return ttl != null && !ttl.isZero() && !ttl.isNegative();
    }

    private static byte[] createCacheLockKey(String name) {
        return (name + "~lock").getBytes(StandardCharsets.UTF_8);
    }

    public CacheStatistics getCacheStatistics(String cacheName) {
        return this.statistics.getCacheStatistics(cacheName);
    }

    public void clearStatistics(String name) {
    }

    public RedisCacheWriter withStatisticsCollector(CacheStatisticsCollector cacheStatisticsCollector) {
        return null;
    }
}
`

**Comment by whiletrue2009** [comment]
挺好的回答，不知道是否收录了。JeecgRedisCacheWriter  貌似没有开源？想改还不方便
