### ISSUE TITLE
详情时图片显示不了

### ISSUE THREAD

**Issue by csainx** [zhangdaiscott/jeecg-boot#1779]
##### 问题描述：
online生成代码后，如果将 j-image-upload 控件设置成 禁止多张上传，在显示 详情 的时候 图片是显示不了的~

##### 截图&代码：

![Image 071](https://user-images.githubusercontent.com/50067476/93845113-3756f980-fcd2-11ea-8be1-6281b7a39c7c.png)

![Image 072](https://user-images.githubusercontent.com/50067476/93845116-3aea8080-fcd2-11ea-95a0-456b2760857f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待测试

**Comment by zhangdaiscott** [comment]
已经处理了，请更新代码
