### ISSUE TITLE
打开的tab切换，会重新加载

### ISSUE THREAD

**Issue by aleiliuwei** [zhangdaiscott/jeecg-boot#178]
当打开多个tab时，第一个tab输入条件搜索后，进行其他tab操作，在返回的话会发现tab将重新加载，个人认为打开的tab只是切换就可以，不需要重新发送请求后台

**Comment by zhangdaiscott** [comment]
这个具体页面需要自己加缓存

**Comment by zhangdaiscott** [comment]
给需要的页面加 keep-alive

**Comment by aleiliuwei** [comment]
好的，谢谢

**Comment by dg81381749** [comment]
如果是打开的外部链接即路由的component为IframePageView.vue的iframe界面，怎么保证tabs切换的时候iframe里面内容不刷新呢
