### ISSUE TITLE
jeecg-boot 2.3版本 swagger文档里的接口文档显示不全

### ISSUE THREAD

**Issue by Victoryli** [zhangdaiscott/jeecg-boot#1780]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mark0614** [comment]
猜测有两种可能：
1、如果你使用的是微服务方式，需要你在gateway的application-dev.yml配置文件中加入jeecg-boot-module-hello这个服务的路由配置，只有加了这个，Swagger才能进行聚合；
2、如果你使用的是单体方式，你可以检查jeecg-boot-module-hello这个组件中的包结构是否符合jeecg的开发规范

**Comment by zhangdaiscott** [comment]
看看是不是gateway路由网关没有做配置
jeecg-cloud-module\jeecg-cloud-gateway\src\main\resources\application-dev.yml
![image](https://user-images.githubusercontent.com/3162115/94224774-dd4e7200-ff25-11ea-8d3e-18cac7552b6f.png)

![image](https://user-images.githubusercontent.com/3162115/94224752-d0318300-ff25-11ea-9696-cc33136bfd0d.png)
