### ISSUE TITLE
内嵌子表风格生成的代码，子表数据不显示

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#1782]
##### 版本号：
2.3

##### 问题描述：

内嵌子表风格，代码生成后有bug，子表数据不能出来
原因是：模板中多了records，应该是res.result

列表显示有样式问题，右边操作栏错位

见下图图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5564707/93856747-113e5300-fcec-11ea-9fd1-d5e8f5a8813e.png)

![image](https://user-images.githubusercontent.com/5564707/93857575-60d14e80-fced-11ea-8a6d-71b9472f7bbe.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by rickding** [comment]
问题不能重现。

- 数据：请查看对应的Controller代码，在接口使用Page分页返回时，数据访问使用records

![image](https://user-images.githubusercontent.com/5389183/95082671-f9d08280-074d-11eb-9e96-8c0cf129995a.png)

- F12查看接收到的接口数据，调整vue代码和Java一致：

![image](https://user-images.githubusercontent.com/5389183/95083490-2b961900-074f-11eb-8ed0-e18b02ee25ba.png)

- 界面显示样式问题不能重现，请先试试在线演示 http://boot.jeecg.com/

**Comment by 1298191366** [comment]
1、代码生成后有bug，子表数据不能出来未发现问题
2、样式已修改，待新版本发布

**Comment by aaronyin** [comment]
> 问题不能重现。
> 
> * 接口代码和返回数据：请查看对应的Controller代码，在接口使用Page分页返回时，数据访问使用records
> 
> ![image](https://user-images.githubusercontent.com/5389183/95084446-7bc1ab00-0750-11eb-87ef-18eb6b26acbe.png)
> 
> * F12查看接收到的接口数据，调整vue代码和Java一致：
> 
> ![image](https://user-images.githubusercontent.com/5389183/95083490-2b961900-074f-11eb-8ed0-e18b02ee25ba.png)
> 
> * 界面显示样式问题不能重现，请先试试在线演示 http://boot.jeecg.com/

是列表里面的内嵌子表单，不是弹出框的子表单
