### ISSUE TITLE
online开发label字数太多被输入框遮挡

### ISSUE THREAD

**Issue by kin1994** [zhangdaiscott/jeecg-boot#1783]
##### 版本号：
2.2.0

##### 问题描述：
online开发label字数太多被输入框遮挡
##### 截图&代码：
![image](https://user-images.githubusercontent.com/11944421/93870482-e0681900-fcff-11ea-8a30-b4bf964329cf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个因为表单是自适应的，不太好改。
你可以把表单改成单列
