### ISSUE TITLE
vue页面 消息中心刷新页面BUG

### ISSUE THREAD

**Issue by x522491416** [zhangdaiscott/jeecg-boot#1786]
##### 版本号：
2.3.0

##### 问题描述：
消息中心及子菜单刷新页面有bug

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么bug，请按照格式要求详细描述

**Comment by x522491416** [comment]
> 什么bug，请按照格式要求详细描述

开发环境下，点击消息中心任一菜单，然后刷新页面，显示找不到页面

**Comment by zhangdaiscott** [comment]
刷新无问题
![image](https://user-images.githubusercontent.com/3162115/94362311-fc4b3080-00ec-11eb-97bc-27bbf4810ba8.png)
