### ISSUE TITLE
能不能提供版本升级功能呀？

### ISSUE THREAD

**Issue by 224148793** [zhangdaiscott/jeecg-boot#1787]
##### 版本号：
2.3

##### 问题描述：

能不能提供版本升级功能呀？jeecg目前不支持版本升级，要靠自己一行行代码去对比然后修改代码升级，这个太痛苦了。本来我们团队，经过一段时间考察预研，发现这个框架功能很不错，已经打算决定使用这个框架了。但是突然发现这个版本不能升级的问题，整个团队目前只有停下来，不敢使用了。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
小版本可以，大版本没办法，改动太大
