### ISSUE TITLE
[开发计划]jeecgboot的前端组件后续会开发定位组件吗？

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1788]
##### 版本号：

2.3
##### 问题描述：

jeecgboot的前端组件后续会开发定位组件吗？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yanchenchen** [comment]
另外，online表单开发会支持定位组件吗？

**Comment by zhangdaiscott** [comment]
目前没这计划，需求量不大

**Comment by yanchenchen** [comment]
嗯，能否提供一下设计思路或者是类似的组件实现方式，多谢！

**Comment by zhangdaiscott** [comment]
没有代码，这块改不了的
