### ISSUE TITLE
Mybatis-plus的IdType配置问题

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#1789]
##### 版本号：

2.3
##### 问题描述：
application-dev.yml中：
mybatis-plus:
   db-config:
     id-type: 4

该id-type应该填写IdType的枚举名称，例如：UUID、AUTO、ID_WORKER
##### 截图&代码：
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'mybatis-plus.global-config.db-config.id-type' to com.baomidou.mybatisplus.annotation.IdType:

    Property: mybatis-plus.global-config.db-config.id-type
    Value: 4
    Origin: "mybatis-plus.global-config.db-config.id-type" from property source "bootstrapProperties"
    Reason: failed to convert java.lang.String to com.baomidou.mybatisplus.annotation.IdType

Action:

Update your application's configuration. The following values are valid:

    ASSIGN_ID
    ASSIGN_UUID
    AUTO
    ID_WORKER
    ID_WORKER_STR
    INPUT
    NONE
    UUID

Process finished with exit code 1

**Comment by zhangdaiscott** [comment]
ok

**Comment by zhangdaiscott** [comment]
已经提交了
