### ISSUE TITLE
启动速度慢

### ISSUE THREAD

**Issue by janmson** [zhangdaiscott/jeecg-boot#179]
我在本地部署后,启动速度非常慢. 大概在40秒左右.请问是什么原因

**Comment by janmson** [comment]
大概下载了20多M的文件.

**Comment by huanlirui** [comment]
我也是这个问题。app.js有30多m。首次加载极慢，求解决方案。

**Comment by zhangdaiscott** [comment]
前端开发就这样，发布后开启Nginx压缩很快

**Comment by GordonHuangYong** [comment]
不行.发布后也是这样,下载一堆js文件,登录界面迟迟不显示,一直在加载.

**Comment by huanlirui** [comment]
nginx的压缩也开了。还是慢

**Comment by bibichuan** [comment]
为什么这么多的下载呢？确实太慢了，有些东西我根本不需要的。

**Comment by zhangdaiscott** [comment]
不需要的可以在全局注册里面注释掉
src/components/registerGlobComp.ts
