### ISSUE TITLE
切面打印日志时，参数序列化异常

### ISSUE THREAD

**Issue by justspeedming** [zhangdaiscott/jeecg-boot#1790]
##### 版本号：

Jeecg Boot 2.2.1
##### 问题描述：
AOP拦截日志报错llegalStateException: It is illegal to call this method if the current request is not in asynchronous mode
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37864253/94095689-d6a3fa00-fe54-11ea-941f-7475be18a30a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by justspeedming** [comment]
建议切面保存日志时，过滤掉httpRequest参数

**Comment by zhangdaiscott** [comment]
日志全一点

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/94362384-682d9900-00ed-11eb-8457-c3dc6f93af2f.png)


最新代码是这样，请确认
