### ISSUE TITLE
[疑问]填值规则的formData如何获取？

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1791]
##### 版本号：

2.3
##### 问题描述：

定义了一个填值规则，如何获取该表单的数据，即下面方法的formData？
 public Object execute(JSONObject params, JSONObject formData)；

因为该编号方法需要在多处用到，需要有个动态参数做识别。

debug调试了，获取到的都是空值。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/8335270/94116857-1cc18380-fe7e-11ea-9eeb-30fac65f06a6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yanchenchen** [comment]
在online表单开发中用到填值规则

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1398551
