### ISSUE TITLE
annountCement!!!

### ISSUE THREAD

**Issue by Yuer-shizi** [zhangdaiscott/jeecg-boot#1792]
##### 版本号：
之前很多版本至JeecgBoot 2.3

##### 问题描述：
这是一个明显的单词拼写错误！
annountCement的正确拼写是 announcement
好多版本了，包括前端，数据库，都是这样跟着错，这都不改一下，求解释！
（来自一个强迫症的疑惑）

##### 截图&代码：
jeecg-boot/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/SysAnnouncementController.java
下
@RequestMapping("/sys/annountCement")

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
ok  3Q
