### ISSUE TITLE
网关的路由配置问题

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#1793]
##### 版本号：
2.3

##### 问题描述：
1、前端界面点击“路由网关”后，没有数据可显示
2、查看了代码，该请求的数据来源是“/sys/gatewayRoute/**”这个端点。该端点的列表数据时来自于查询sys_gateway_route表，这个表中的数据时空的。查看了数据初始化脚本，并没有发现有insert语句
3、另外查看了网关服务的application-dev.yml的配置，网关服务的路由规则是配置在该配置文件当中
4、疑惑：路由网关这块功能是不是还没有完成？数据库配置的路由规则如何加载到网关服务的GatewayRouter中？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前这个功能只是做了界面配置，gateway目前还没用这个逻辑
目前都是gateway那边手工的配置文件

**Comment by zhangdaiscott** [comment]
看看是不是gateway路由网关没有做配置
![image](https://user-images.githubusercontent.com/3162115/94224774-dd4e7200-ff25-11ea-8d3e-18cac7552b6f.png)

![image](https://user-images.githubusercontent.com/3162115/94224752-d0318300-ff25-11ea-9696-cc33136bfd0d.png)
