### ISSUE TITLE
于SpringBoot 请求参数包含 []　特殊符号　返回400状态

### ISSUE THREAD

**Issue by laozhu001** [zhangdaiscott/jeecg-boot#1795]
##### 版本号：

2.2
##### 问题描述：
于SpringBoot 请求参数包含 []　特殊符号　返回400状态

##### 截图&代码：

解决方案类似springMvc修改tomcat配置

springBoot 启动类 添加 bean

@Bean
public TomcatServletWebServerFactory tomcatServletWebServerFactory (){
 
   // 修改内置的 tomcat 容器配置
   TomcatServletWebServerFactory tomcatServlet = new TomcatServletWebServerFactory();
   tomcatServlet .addConnectorCustomizers(
      (TomcatConnectorCustomizer) connector -> connector.setProperty("relaxedQueryChars", "[]{}")
   );
 
   return tomcatServlet ;

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录
