### ISSUE TITLE
 2.3 版本的 JVXETable 是否是必选组件,可以自己移除掉吗?

### ISSUE THREAD

**Issue by Aaron-Bird** [zhangdaiscott/jeecg-boot#1796]
##### 版本号：
2.3

##### 问题描述：

原来的项目基于 jeecg-boot 2.2, 其中的一些表格用到了 vxe-table 2.9.22
现在想升级到 jeecg-boot 2.3,但发现新出 jeecg-boot 2.3 版本里依赖了 vxe-table 2.9.13,并且锁了版本.
(似乎 vxe-table  版本 2.9.16 和 2.9.18 有一些 api 不兼容)

想咨询一下:
1 官方未来会升级  vxe-table 的依赖版本吗?
2 JVXETable 是否是可选的,可以自己移除掉吗? 当前是否在其他地方用到了JVXETable (例如代码自动生成之类的)
 未来官方是否会基于JVXETable 开发一些必选的功能?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级版本应该没什么影响

**Comment by Aaron-Bird** [comment]
@zhangdaiscott

试了一下, 升级到 vxe-table 2.9.22 版本之后 JeecgBoot 会报错,跑不起来.
