### ISSUE TITLE
popup弹出框代码生成有问题

### ISSUE THREAD

**Issue by shiyongcui** [zhangdaiscott/jeecg-boot#1797]
##### 版本号：
2.1.4

##### 问题描述：
popup弹出框在online表单开发中功能测试没有问题，生成的代码无法无法选择带回信息

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55284347/94213664-082acd00-ff0a-11ea-99ec-7228c8834b37.png)
此处在online表单开发中是正常的
![image](https://user-images.githubusercontent.com/55284347/94213704-21cc1480-ff0a-11ea-8772-0f519b92367f.png)
生成后的代码提示这个问题

![image](https://user-images.githubusercontent.com/55284347/94216653-7ecbc880-ff12-11ea-975b-eb7c34afff7b.png)
项目里缺少这块代码，能不能给加上呢

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是不是生成的只支持单选？

**Comment by shiyongcui** [comment]
> 是不是生成的只支持单选？

单选也不可以，虽然不提示请选择一条记录了，但是值无法带回

**Comment by zhangdaiscott** [comment]
把生成的popup代码贴一下

**Comment by shiyongcui** [comment]
> 把生成的popup代码贴一下

![image](https://user-images.githubusercontent.com/55284347/94217190-f5b59100-ff13-11ea-9677-738fbf7bbec5.png)
看这些够吗

**Comment by shiyongcui** [comment]
[](url)

**Comment by shiyongcui** [comment]
> 把生成的popup代码贴一下

![image](https://user-images.githubusercontent.com/55284347/94217848-96f11700-ff15-11ea-90af-850d4be58624.png)
项目里面缺少说明文档里的这块代码

**Comment by shiyongcui** [comment]
JPopup.vue 可以开放这块代码吗，这个popup弹出框还挺实用的

**Comment by zhangdaiscott** [comment]
帖的不对，看使用了popup组件代码不是引用逻辑

**Comment by shiyongcui** [comment]
> 代码不是引用逻辑

最新版程序已没有这个问题，多谢
