### ISSUE TITLE
文档显示异常

### ISSUE THREAD

**Issue by PLAhui** [zhangdaiscott/jeecg-boot#1798]
##### 问题描述：
切换微服务后文档显示只有default，其他模块文档不显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35413994/94216464-fe0ccc80-ff11-11ea-8bb3-79c2b66af11c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
其他模块启动了吗

**Comment by PLAhui** [comment]
> 其他模块启动了吗
全部启动了，nacos中服务也注册正常，所有模块都是在org.jeecg.modules.包下

**Comment by zhangdaiscott** [comment]
测了下，没有问题啊
![image](https://user-images.githubusercontent.com/3162115/94223863-8c3d7e80-ff23-11ea-8e6e-ffaee607cf0c.png)
