### ISSUE TITLE
大屏设计下的两个示例没有样式和JS

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#1799]
##### 版本号：
2.3

##### 问题描述：
微服务版中，大屏设计的两个示例Demo无法显示：
问题重现：
   1、点击生产销售监控，出现大白板。查看页面源代码，发现html代码已经加载，JS和CSS未加载
   2、由于大屏的demo是在jeecg-demo服务中，不通过网关直接访问jeecg-demo服务的大屏示例地址，所有的页面是可以显示的
##### 截图&代码：
![1](https://user-images.githubusercontent.com/2269399/94222729-c6595100-ff20-11ea-8672-a433bf2bce90.png)
![1](https://user-images.githubusercontent.com/2269399/94222849-0b7d8300-ff21-11ea-8257-136cd82cfa6f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确实有问题，网关配置加上
,/bigscreen/template1/**,/bigscreen/template2/**
![image](https://user-images.githubusercontent.com/3162115/94224500-20f4ac00-ff25-11ea-908b-d52280e3e172.png)
