### ISSUE TITLE
点击一级菜单之后，子菜单的创建详情是错误的。

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#18]
### 环境
最新版本的代码v1.0 
前端显示错误，当创建菜单的时候，一级菜单点击后状态就永久绑定了，除非手动再点击切换。如图：
![image](https://user-images.githubusercontent.com/27263086/54473236-de222600-480f-11e9-8aeb-cefc39310b9c.png)

**Comment by zhangdaiscott** [comment]
这个发现了，下个版本修复
