### ISSUE TITLE
增强字典表带过滤条件功能

### ISSUE THREAD

**Issue by lulusoft** [zhangdaiscott/jeecg-boot#180]
前端：  <j-dict-select-tag @change="" v-decorator="['jg', {}]" placeholder="请选择第一级组织机构" :triggerChange="true" dictCode="sys_depart,depart_name,id,org_type=1  order by org_code"/>
后端：
SysDictController：getDictItems增加
 if(params.length==4) {	 
ls = sysDictService.queryTableDictItemsByCodeAndFilter(params[0],params[1],params[2],params[3]);
}
ISysDictService增加：  List<DictModel> queryTableDictItemsByCodeAndFilter(String table, String text, String code,String filter);

**Comment by zhangdaiscott** [comment]
ok

**Comment by zhangdaiscott** [comment]
已经修改，下个版本发布
