### ISSUE TITLE
导入数据字典Excel，格式其实不对，但导入成功。导致系统无法登陆

### ISSUE THREAD

**Issue by speshowzhu** [zhangdaiscott/jeecg-boot#1800]
##### 版本号：
官网的在线演示

##### 问题描述：
对不起啊，弄蹦了，导入数据字典Excel，格式其实不对，但导入成功。导致系统无法登陆

##### 截图&代码：

![image](https://user-images.githubusercontent.com/46705291/94224660-9791a980-ff25-11ea-92ec-86effa3a2f0d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
还原 了
