### ISSUE TITLE
mysql 中qrtz_开头的表名有问题

### ISSUE THREAD

**Issue by szyuppie** [zhangdaiscott/jeecg-boot#1801]
##### 问题描述：
 linux 环境下数据库mysql默认配置为0，对大小写敏感。这里脚本sql需要改成大写。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以执行这个脚本，或者把数据库设置不区分大小写
[tables_mysql.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5281664/tables_mysql.zip)

**Comment by KID-joker** [comment]
执行脚本报错：
![image](https://user-images.githubusercontent.com/42445388/109018121-ce493700-76f2-11eb-943b-a013b564276b.png)

**Comment by KID-joker** [comment]
@zhangdaiscott 大佬帮忙看一下
