### ISSUE TITLE
Online表单开发问题

### ISSUE THREAD

**Issue by ChenAGit** [zhangdaiscott/jeecg-boot#1803]
##### 版本号：
2.3

##### 问题描述：
Online表单开发，数据类型选择Date，字段长度自动变成0，是否需要手动改

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/46208555/94229770-01fd1680-ff33-11ea-96be-6c06d6ee544a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不需要，时间类型0没问题
