### ISSUE TITLE
Online表单开发问题

### ISSUE THREAD

**Issue by ChenAGit** [zhangdaiscott/jeecg-boot#1804]
##### 版本号：
2.3

##### 问题描述：
用eclipse运行后台，同步数据库正常，但是maven package之后，运行jeecg-boot-module-system-2.3.0.jar，同步数据库失败，报错内容：同步数据库失败，Unable to perform unmarshalling at line number 0 and column 0. Message: null : origin(null)，命令行界面上提示：Could not parse mapping document:null(INPUT_STREAM)...

##### 截图&代码：
![QQ图片20200925133843](https://user-images.githubusercontent.com/46208555/94230438-84d2a100-ff34-11ea-970b-46a922712d35.png)
![QQ图片20200925133900](https://user-images.githubusercontent.com/46208555/94230444-89975500-ff34-11ea-9c98-e420f65a028b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
65

**Comment by ChenAGit** [comment]
> 
> 
> http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 65

没找到怎么解决，能说具体点吗

**Comment by ChenAGit** [comment]
> 
> 
> http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 65

第7条代码生成器怎么用，打开后是技术文档，但是对于我的问题没有解答，我现在是eclipse调试运行就正常，但是发布上线后就有问题，我发布是照着文档做的，先mvn install，再mvn package
