### ISSUE TITLE
内嵌子表一对多代码生成，后端会报错

### ISSUE THREAD

**Issue by whitejiang123** [zhangdaiscott/jeecg-boot#1808]
##### 版本号：
2.3

##### 问题描述：
内嵌子表一对多代码生成后，后端service层会报错。主要是外键这个字段报错。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/65378480/94353067-5c1aea80-009f-11eb-918a-8aaf9b6a2ac7.png)

![image](https://user-images.githubusercontent.com/65378480/94353072-66d57f80-009f-11eb-8272-45fb49e9df25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
外键配置截图看下

**Comment by wyc194** [comment]
mapper在代码层没有实现，idea提示Could not autowire不是很正常吗，mybatis会在运行时生成代理类处理的，不影响。
第一张图先看实体类中外键字段是否正常生成(如果没有，那确实就是代码生成问题，可能操作使用配置的不对或者其他原因)，不过照你截第二张图的疑惑显示的水平，我感觉你是不是Lombok没配。

**Comment by zhangdaiscott** [comment]
待测试

**Comment by rickding** [comment]
代码生成器生成的外键读取代码有错误，应该调用主表getId()读取，然后调用附表set函数设置。

## 1，手动修改代码解决方法
修改代码，针对问题中的代码，应该这样修改：entity.setWai(testCeshi.getId());

注意getId()指的是附表外键引用的主表字段。
![image](https://user-images.githubusercontent.com/5389183/95013377-6b3b0300-0672-11eb-8180-20479c34181b.png)

## 2，代码生成器问题修复
解决代码生成时的错误，引用主表、附表不同字段。@zhangdaiscott 

## 3，问题中提到的不能找到autoWired变量，是开发环境的显示问题，建议先试试能否编译通过。
![image](https://user-images.githubusercontent.com/5389183/95013412-b6551600-0672-11eb-9b25-9d961628511c.png)

**Comment by whitejiang123** [comment]
不好意思回复晚了。您看下我这在online表单中设置的外键对不对。谢谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午3:02
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"想起"<358254771@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 内嵌子表一对多代码生成，后端会报错 (#1808)





 
外键配置截图看下

**Comment by whitejiang123** [comment]
您好 ，回复晚了，请您看一下 lombok是不是这样就好了。在设置中打开lombok，还需要别的配置吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 中午12:56
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"想起"<358254771@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 内嵌子表一对多代码生成，后端会报错 (#1808)





 
mapper在代码层没有实现，idea提示Could not autowire不是很正常吗，mybatis会在运行时生成代理类处理的，不影响。
 第一张图先看实体类中外键字段是否正常生成(如果没有，那确实就是代码生成问题，可能操作使用配置的不对或者其他原因)，不过照你截第二张图的疑惑显示的水平，我感觉你是不是Lombok没配。

**Comment by zhangdaiscott** [comment]
未重现
