### ISSUE TITLE
online表单

### ISSUE THREAD

**Issue by woniu0503** [zhangdaiscott/jeecg-boot#1809]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你自己升级的？还是改了什么

**Comment by woniu0503** [comment]
服务端代码用咱们新发布的全部，数据库用2.3的增量升级的；前端除了自己的业务view也全是2.3的。用2.3的前端连2.2.1的服务端在线表单的功能就好用，都用新的就不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午3:01
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"刘胜高"<809238126@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] online表单 (#1809)





 
你自己升级的？还是改了什么

**Comment by zhangdaiscott** [comment]
其他人未反馈此问题，你自己排查下，是否升级有遗漏

**Comment by woniu0503** [comment]
请问如果不使用微服，只用单体是不是可以不加载启动jeecg-cloud-module ？在线表单功能不好用和没加载这个module有关系吗？谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午3:01
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"刘胜高"<809238126@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] online表单 (#1809)





 
你自己升级的？还是改了什么

**Comment by zhangdaiscott** [comment]
不用微服务，jeecg-cloud-module不需要用。
online不好用跟这个没关系
