### ISSUE TITLE
如果是自定义包（如com.**）的实例中使用字典表下拉不生效

### ISSUE THREAD

**Issue by lulusoft** [zhangdaiscott/jeecg-boot#181]
bug：
生成自定义包（如com.**）下的实例代码，使用@Dict(dicCode = "*") 后，前端json里不生成_dictText结尾的字段属性

**Comment by zhangdaiscott** [comment]
jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/aspect/DictAspect.java
自己修改
![image](https://user-images.githubusercontent.com/3162115/58865039-6665e800-86e8-11e9-8389-482eb81febe2.png)

**Comment by lulusoft** [comment]
我改为    @Pointcut("execution(public * org.jeecg.modules.*.*.*Controller.*(..)) or execution(public * com.mypackage.modules.*.*.*Controller.*(..)) ")
还是不生效，请问有错吗？

**Comment by muYouGou** [comment]
您好。针对这个问题，我正好也遇到了。我的做法是将or 替换成 || 即可 。
spring的帮助手册里有关于execution的连接方式的一句话：
Pointcut expressions can be combined using '&&', '||' and '!'.
