### ISSUE TITLE
j-image-upload图片组件单张图片详情回显空白

### ISSUE THREAD

**Issue by chenluby** [zhangdaiscott/jeecg-boot#1810]
##### 版本号：
2.2.1

##### 问题描述：
组件源码
https://github.com/zhangdaiscott/jeecg-boot/blob/master/ant-design-vue-jeecg/src/components/jeecg/JImageUpload.vue
组件参数文档
http://doc.jeecg.com/1524927
问题：
1、设置isMultiple为false时(单张图片)。新增，编辑能正常回显，**详情**回显**空白**(多张图片不存在这个情况)
![图片](https://user-images.githubusercontent.com/35733171/94356550-7c0fd580-00c2-11eb-8d3f-8d6c4c7d562f.png)
2、如果把xxXModal的
`<j-form-container :disabled="disableSubmit">`
的:disabled设置为false或者不设置，并设置j-image-upload的:disabled="false"时。**详情**正常回显(并能正常禁用)，但是这样详情**其它**输入框禁用就会失效。
![23](https://user-images.githubusercontent.com/35733171/94356683-a9a94e80-00c3-11eb-872c-e17a72bf6dbc.png)

3、初步怀疑设置`<j-form-container :disabled="disableSubmit">`的disabled和`<j-image-upload> `的:disabled有冲突
##### 截图&代码：
```
  <a-form-item label="封面图片" :labelCol="labelCol" :wrapperCol="wrapperCol">
              <j-image-upload :isMultiple="false" :disabled="true" v-decorator="['imageCover']"></j-image-upload>
 </a-form-item>
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待分析

**Comment by chenluby** [comment]
更正一下第二点，并设置j-image-upload的`:disabled="false"`时为`:disabled="true"`

**Comment by zhangdaiscott** [comment]
代码已经上传，请更新
