### ISSUE TITLE
用户管理模块新增、编辑接口事务不一致，会导致脏数据产生

### ISSUE THREAD

**Issue by quzehu** [zhangdaiscott/jeecg-boot#1812]
##### 版本号：
2.3

##### 问题描述：
用户管理模块 添加和编辑接口（/sys/user/add，/sys/user/edit）controller在调用多个service时，事务不能保持一致，如果最后一个service发生了异常，回滚，那么前面的service不会回滚，返回给前端页面是添加/编辑失败，最后导致出现脏数据，sys_user表、sys_user_depart表、sys_user_role表数据不一致。

##### 截图&代码：
虽然每个service都加了@Transactional，但是事务之间是没有关系的，应该controller调用一个加事务的service方法，service中再调用其他的service方法
![image](https://user-images.githubusercontent.com/33826388/94384421-22b4ae80-0175-11eb-95de-53c8ca8b3c5b.png)
![image](https://user-images.githubusercontent.com/33826388/94384472-395b0580-0175-11eb-93dc-4eac31088a29.png)
![image](https://user-images.githubusercontent.com/33826388/94384617-96ef5200-0175-11eb-866d-eed47590dbd1.png)
![image](https://user-images.githubusercontent.com/33826388/94384811-12510380-0176-11eb-9250-566ce61d30f4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，后期优化
