### ISSUE TITLE
在线online表单--js增强实现下拉联动效果  (代码生成报错)

### ISSUE THREAD

**Issue by hanzanr123** [zhangdaiscott/jeecg-boot#1813]
##### 问题描述：在线online表单---js增强实现下拉联动效果  (代码生成报错)
(1)在线功能测试 正常
(2)生成代码报错:  vue代码, form那个组件异常
(3)其他地方引用联动组件 ,生成代码也是这样的错误

##### 截图&代码：

![image](https://user-images.githubusercontent.com/43511761/94391805-218d7c80-0189-11eb-9b14-a0d6492055af.png)
![image](https://user-images.githubusercontent.com/43511761/94391846-3538e300-0189-11eb-8497-b7f90cd5e9fd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是不是配置的字典字段，但是字典code没有配置

**Comment by hanzanr123** [comment]
![image](https://user-images.githubusercontent.com/43511761/94404825-31658a80-01a2-11eb-86f3-f6cbc93a646f.png)

**Comment by hanzanr123** [comment]
vue代码 form表单 那个组件生成错误,主要是想看 里面 如何引用分类字典的,纠结

**Comment by zhangdaiscott** [comment]
临时可以先把下拉联动改成普通的，就可以生成了

**Comment by zhangdaiscott** [comment]
待测试

**Comment by lvdandan16** [comment]
![image](https://user-images.githubusercontent.com/54099258/96248862-d5429900-0fde-11eb-81f1-005ab2af0174.png)
province 配置为联动
其他配置为文本框
确认是否有问题
