### ISSUE TITLE
每次首页进来都是admin 如何去掉这个默认

### ISSUE THREAD

**Issue by sunyjgithub** [zhangdaiscott/jeecg-boot#1814]
##### 问题描述：
每次首页进来都是admin 如何去掉这个默认

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37937289/94504675-e730e780-023b-11eb-8cf8-50657d4e698b.png)

![image](https://user-images.githubusercontent.com/37937289/94504738-0b8cc400-023c-11eb-8ed6-7b86959aa549.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
src/views/user/Login.vue
![image](https://user-images.githubusercontent.com/3162115/94508189-fddb3c80-0243-11eb-82da-8f1bc6115176.png)
