### ISSUE TITLE
能否补充文档中动态的控制字段组件是否禁用的代码示例

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#1816]
##### 版本号：
2.3

##### 问题描述：
希望可以动态控制编辑时字段是否只读，文档中(动态的控制字段组件是否禁用)这个部分缺失，能否补充一下

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个组件？

**Comment by i-Hu** [comment]
> 那个组件？
比如希望在新增时姓名字段可以录入，但是编辑时不能编辑，赋予disabled或者readonly属性，现有的只读控制都是新增和编辑一起disabled

**Comment by zhangdaiscott** [comment]
这个自己编码实现即可
