### ISSUE TITLE
js增强附表内置方法调用问题

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#1819]
##### 版本号：
2.3

##### 问题描述：
1. js增强that.clearSubRows()和that.clearThenAddRows()都不能清空附表，addSubRows()可以正常调用
2. 如果填写了id也不是如文档所说更新同id行的值，而是新增一行，同时控制台报错

##### 截图&代码：

1.js增强代码
onlChange(){
return {
base_arch_bed_name(){
console.log("床位名修改");
let rows = [{base_charge_type_id:'',base_charge_type_name:'服务费',price:'1000'}]
that.clearThenAddRows('contract_charge',rows);}}}

2.控制台信息
vue.runtime.esm.js?2b0e:619 [Vue warn]: Duplicate keys detected: '_jet-m3h4je-40289782653687de0165371328010012'. This may cause an update error.

found in

---> <JEditableTable>
       <ATabPane>
         <TabContent>
           <Tabs>
             <ATabs>
               <OnlineForm>
                 <ASpin>
                   <Anonymous>
                     <Anonymous>
                       <Portal>
                         <PortalWrapper>
                           <Anonymous>
                             <AModal>
                               <JModal> at src/components/jeecg/JModal/index.vue
                                 <OnlCgformAutoModal>
                                   <ACard>
                                     <OnlCgFormAutoList>
                                       <RouteView> at src/components/layouts/RouteView.vue
                                         <Anonymous>
                                           <ALayoutContent>
                                             <Anonymous>
                                               <ALayout>
                                                 <Anonymous>
                                                   <ALayout>
                                                     <GlobalLayout> at src/components/page/GlobalLayout.vue
                                                       <TabLayout> at src/components/layouts/TabLayout.vue
                                                         <ALocaleProvider>
                                                           <LocaleReceiver>
                                                             <AConfigProvider>
                                                               <App> at src/App.vue
                                                                 <Root>
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1631191

**Comment by i-Hu** [comment]
> http://doc.jeecg.com/1631191

参考这个文档调用的方法，没有成功，在线演示里有这个方法调用的示例么

**Comment by zhangdaiscott** [comment]
此问题修复了，下个版本发布
