### ISSUE TITLE
模糊查询通配符问题

### ISSUE THREAD

**Issue by petma** [zhangdaiscott/jeecg-boot#1820]
##### 版本号：
2.2.1

##### 问题描述：
演示系统>系统管理>用户管理>账号 输入_ 点查询，返回的所有。期望返回用户名包含“_”的用户。

##### 截图&代码：
SELECT * FROM sys_user WHERE del_flag = 0 AND (username LIKE '%_%' AND third_id IS NULL AND username <> '_reserve_user_external') ;

未对通配符进行转义

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个需要非常规，你可以先改造代码

'%\_%'

**Comment by zhangdaiscott** [comment]
已经修复，直接替换这个类

org.jeecg.common.system.query.QueryGenerator
[QueryGenerator.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5420905/QueryGenerator.zip)
