### ISSUE TITLE
online 报表通过参数进行排序无效

### ISSUE THREAD

**Issue by orange2003** [zhangdaiscott/jeecg-boot#1821]
##### 问题描述：
按照文档中编辑跳转链接如下
http://localhost:3000/online/cgreport/1311854216832856066?mchid=20000000&column=createtime&order=desc
但是排序未生效创建时间还是asc 的查看日志生成的sql语句也未包含排序部分

##### 截图&代码：

![image](https://user-images.githubusercontent.com/272932/94891941-020e9080-04b6-11eb-8694-fd9f756eb616.png)
![image](https://user-images.githubusercontent.com/272932/94892034-3da95a80-04b6-11eb-906a-e19fc1916189.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
文档中编辑跳转链接适用于SqlServer数据库，mysql数据库下在报表SQL中直接写即可
![image](https://user-images.githubusercontent.com/54099258/98673804-d8893480-2392-11eb-954e-1d59bd548086.png)
