### ISSUE TITLE
【BUG】两个online报表之间跳转。排序后排序条件未清空造成报错

### ISSUE THREAD

**Issue by orange2003** [zhangdaiscott/jeecg-boot#1822]
##### 问题描述：
从A online 报表中通过字段herf 跳转到B online 报表，然后点击B 报表的任意字段进行排序。然后切回 A online 报表这时排序拼接字串并未清空造成sql 查询报错
可用狠简单的复现此问题。 同时打开两个不同的online报表。在后打开的报表上进行字段排序操作。然后切回A报表。由于排序条件未清空。排序字段在A表中不存在此时sql报错
##### 截图&代码：

![image](https://user-images.githubusercontent.com/272932/94894824-b7444700-04bc-11eb-9f77-9da075d7aa90.png)
![image](https://user-images.githubusercontent.com/272932/94894880-d5aa4280-04bc-11eb-82ae-cd780ba47b6a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
分配

**Comment by zhangdaiscott** [comment]
已经处理请更新代码 2.4
