### ISSUE TITLE
切换微服务定时任务有问题

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-boot#1824]
##### 问题描述：
1、切换微服务后，定时任务只能建立在system模块下，否则报错找不到指定类；
2、在页面上启动定时任务后，任务执行一次后就不执行了；
3、自己建的微服务模块，如何屏蔽定时任务？我自己写的两个模块会抛出找不到job类的异常。
请问有什么解决方案？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
1.定时任务等下个版本将从system中抽离，或者你可以自行改造
2.未发现你说的启动一次就不执行问题
3.未复现

**Comment by Nicky213Zhang** [comment]
> 1.定时任务等下个版本将从system中抽离，或者你可以自行改造
> 2.未发现你说的启动一次就不执行问题
> 3.未复现
你好，针对问题1，我的理解是即使从system抽离，如果按照现有的页面结构来看的话，各个应用也需要写一套相应的代码。或者参照xxl-job独立为一个应用服务。我的选择是参照jeecg-cloud微服务文档，引入的xxl-job作为分布式任务调度。

**Comment by zhangdaiscott** [comment]
xxl-job集成已经完成，下个版本发布
