### ISSUE TITLE
后端项目启动报错

### ISSUE THREAD

**Issue by BoSeal** [zhangdaiscott/jeecg-boot#1825]
##### 问题描述：报错：java程序包：org.jeecgframework.codegenerate.generate.util不存在
![1](https://user-images.githubusercontent.com/39556913/95540398-47d1d880-0a23-11eb-8d1f-e1bed0bdc599.jpg)

##### 截图&代码：
![2 ](https://user-images.githubusercontent.com/39556913/95540417-54563100-0a23-11eb-8535-362826cc97dd.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
依赖下载成功了吗
http://doc.jeecg.com/1273965

**Comment by BoSeal** [comment]
@zhangdaiscott ，你好，我是在公司内网上搭建jeecgboot，所以并没有使用jeecgboot的Maven私服

**Comment by zhangdaiscott** [comment]
哪不行，依赖没下载成功怎么用
