### ISSUE TITLE
登入生成token的小bug

### ISSUE THREAD

**Issue by smilove** [zhangdaiscott/jeecg-boot#1829]
##### 问题描述：
登入接口的用户信息方法中,生成token的密码应该进行MD5加密,否则在登入成功之后,shiro 进行自定义的shirorealm鉴权器的jwtTokenRefresh方法会校验token有效性失败,redis会重新赋值,虽然不影响正常流程业务(因为JwtUtil的verify方法捕获了所有异常),但是这里的目的应该是为了给长时间操作的用户更新token.登入成功之后对redis进行多余的一次赋值没有必要.

##### 截图&代码：
<img width="506" alt="微信截图_20201009172753" src="https://user-images.githubusercontent.com/42567321/95568434-d01da100-0a56-11eb-82fe-31170d461716.png">
<img width="543" alt="222" src="https://user-images.githubusercontent.com/42567321/95568450-d449be80-0a56-11eb-9db1-5abee30a9026.png">

**Comment by zhangdaiscott** [comment]
已经解决，请更新代码
