### ISSUE TITLE
jeecg权限丢失问题

### ISSUE THREAD

**Issue by zihuanouba** [zhangdaiscott/jeecg-boot#1830]
##### 版本号：
未知

##### 问题描述：
管理员角色登录进去没有系统管理等各种菜单权限，（可能在配置角色权限的时候误删）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57122899/95570703-e11be180-0a59-11eb-8f5f-5a63a72d5f32.png)

![image](https://user-images.githubusercontent.com/57122899/95570736-eda03a00-0a59-11eb-8abb-9d0d784b7ebe.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
还原数据库即可
