### ISSUE TITLE
左侧边栏收缩,右侧界面不能上下滚动

### ISSUE THREAD

**Issue by liyu137218** [zhangdaiscott/jeecg-boot#1835]
##### 正常情况:
![jecgbug1](https://user-images.githubusercontent.com/28554078/95644842-035e3f80-0aec-11eb-93c7-319969153d4d.png)
##### bug情况:
![bug1-1](https://user-images.githubusercontent.com/28554078/95644848-08bb8a00-0aec-11eb-9401-3b181b9519b3.png)

##### 侧边按钮方法 但是找不到是哪里的js修改了body的overflow:hidden,导致不能上下滚动了
```
toggle() {
      this.collapsed = !this.collapsed
      this.setSidebar(!this.collapsed)
      triggerWindowResizeEvent()
    },
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liyu137218** [comment]
已经暴力笨方法解决,每次点击时候,方法 toggle()里 强制js重写overflow='auto'
      setTimeout(() => {
      document.getElementById('bodydiv').style.overflow='auto'
      }, 30);
谁有更好方法,请指教

**Comment by zhangdaiscott** [comment]
已经处理了，下个版本发布

**Comment by LongYue9608** [comment]
能说下怎么解决吗 本地项目不能更新 @zhangdaiscott

**Comment by WaitingforPu** [comment]
能说下怎么解决吗 本地项目不能更新  @zhangdaiscott  在线等等

**Comment by WaitingforPu** [comment]
@zhangdaiscott    使用的是2,3版本的升级不了！在线等解决方案

**Comment by WaitingforPu** [comment]
@zhangdaiscott  等等

**Comment by WaitingforPu** [comment]
@liyu137218    你找到好的解决方案了吗  切换也会触发

**Comment by GOODNames** [comment]
> @liyu137218 你找到好的解决方案了吗 切换也会触发

请问最后怎么解决的，遇到同样问题

**Comment by WaitingforPu** [comment]
暂未解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 左侧边栏收缩,右侧界面不能上下滚动 (#1835)





  
@liyu137218 你找到好的解决方案了吗 切换也会触发
  
请问最后怎么解决的，遇到同样问题

**Comment by GOODNames** [comment]
发现body中的overflow属性修改是有a-drawer组件造成的，尝试给添加a-drawer添加 :get-container="false" 属性后，问题解决

**Comment by WaitingforPu** [comment]
谢谢，谢谢。远方传来的解决方案！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 中午12:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 左侧边栏收缩,右侧界面不能上下滚动 (#1835)





 
发现body中的overflow属性修改是有a-drawer组件造成的，尝试给添加a-drawer添加 :get-container="false" 属性后，问题解决
