### ISSUE TITLE
swagger的接口显示不全

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#1836]
##### 版本号：
2.3.0

##### 问题描述：
单体模式下，新增的扩展新模块项目中的接口在swagger中不显示，已经在system中添加了引用，之前2.2.0的时候该配置可以生效，但是2.3.0就不好使

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30401919/95651735-f3ac1e80-0b1e-11eb-8e50-2eed737c9c06.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
扫码路径配置了吗

**Comment by Antony-Jia** [comment]
同样遇到这个问题了，扫描路径已经改为org.jeecg都不好用

**Comment by zhangdaiscott** [comment]
代码贴出

**Comment by Antony-Jia** [comment]
![QQ截图20201014085254](https://user-images.githubusercontent.com/58219593/95931227-22661580-0dfb-11eb-8d8e-4a67530d8c8b.png)
![QQ截图20201014085459](https://user-images.githubusercontent.com/58219593/95931235-24c86f80-0dfb-11eb-84a3-a43951518ca6.png)
![QQ截图20201014085530](https://user-images.githubusercontent.com/58219593/95931237-25f99c80-0dfb-11eb-9458-73cf725e22f8.png)
![QQ截图20201014085547](https://user-images.githubusercontent.com/58219593/95931239-27c36000-0dfb-11eb-8bd2-f9b359147906.png)
![QQ截图20201014085610](https://user-images.githubusercontent.com/58219593/95931245-2a25ba00-0dfb-11eb-81c8-c4a31ad2c8d3.png)

**Comment by Antony-Jia** [comment]
@zhangdaiscott

**Comment by Antony-Jia** [comment]
已经解决了，需要刷新一下idea的maven导入
