### ISSUE TITLE
在线演示

### ISSUE THREAD

**Issue by zccqwc** [zhangdaiscott/jeecg-boot#1837]
##### 版本号：
20/10/11

##### 问题描述：
在线演示登录不上

##### 截图&代码：

操作失败，Could not write JSON: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: org.jeecg.common.api.vo.Result["result"]->com.alibaba.fastjson.JSONObject["sysAllDictItems"]->java.util.HashMap["null"])

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好了
