### ISSUE TITLE
列表开关控件数据未展示

### ISSUE THREAD

**Issue by tangxinmao** [zhangdaiscott/jeecg-boot#1838]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/12179996/95670826-cfa21900-0bc2-11eb-967b-1d66cd4cb680.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
怎么配置的

**Comment by tangxinmao** [comment]
![Uploading image.png…]()

**Comment by tangxinmao** [comment]
> 怎么配置的

![image](https://user-images.githubusercontent.com/12179996/95726445-85e12d80-0cab-11eb-9ec5-72ad055b2c24.png)

**Comment by tangxinmao** [comment]
> 怎么配置的

![image](https://user-images.githubusercontent.com/12179996/95726509-9b565780-0cab-11eb-92b1-1c349972abc4.png)

**Comment by tangxinmao** [comment]
> 怎么配置的

![image](https://user-images.githubusercontent.com/12179996/95726643-c50f7e80-0cab-11eb-97be-d32e8c37bc4f.png)

**Comment by zhangdaiscott** [comment]
还没明白

**Comment by tangxinmao** [comment]
> 还没明白

![image](https://user-images.githubusercontent.com/12179996/95844930-1ab35c00-0d7c-11eb-8866-e2aa76cab2f2.png)
![image](https://user-images.githubusercontent.com/12179996/95845018-3b7bb180-0d7c-11eb-8e57-5508de9cc42b.png)
在线测试是可以的 生成代码后有问题

**Comment by tangxinmao** [comment]
> 还没明白
![image](https://user-images.githubusercontent.com/12179996/95845161-69f98c80-0d7c-11eb-8d6c-59ca56cbf288.png)
![image](https://user-images.githubusercontent.com/12179996/95845204-74b42180-0d7c-11eb-9f03-b066090d817a.png)
在线测试是可以的，生成代码的页面数据错位

**Comment by tangxinmao** [comment]
> 还没明白
![image](https://user-images.githubusercontent.com/12179996/95845412-b6dd6300-0d7c-11eb-81c6-bdf66849f29f.png)
![image](https://user-images.githubusercontent.com/12179996/95845439-bf359e00-0d7c-11eb-9787-c4c67c4c15ef.png)

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/96693775-3c36c800-13ba-11eb-9a3e-7213f5d70f11.png)
问题未重现，这个是代码生成以后的，且如果是开关组件应该默认是关闭的，列表不会有值，是否有其他操作
