### ISSUE TITLE
online表单开发自定义action按钮能否在报错时前端抛出错误信息

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#1839]
##### 版本号：
2.3

##### 问题描述：
能否在online表单开发调用自定义action按钮java增强报错时，前端也显示报错的信息，就像新增按钮java增强有报错信息，方便抛出提示信息

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持
