### ISSUE TITLE
批量保存异常，事务不回滚

### ISSUE THREAD

**Issue by yuxishua** [zhangdaiscott/jeecg-boot#184]
案例：方法foo中有两步保存，且方法foo上加了@Transactional 注解，第一步保存正常，第二步保存时构建一个实体属性值长度超出表字段长度的问题。
问题：
1.  service1.save,正常，service2.saveBatch异常 ，异常捕获为：org.apache.ibatis.executor.BatchExecutorException，不会回滚
2.   service1.save正常，service2.save异常：org.springframework.dao.DataIntegrityViolationException，且事务会回滚

**Comment by zhangdaiscott** [comment]
代码截图出来

**Comment by yuxishua** [comment]
![image](https://user-images.githubusercontent.com/7563822/58940552-4b5cac00-87ac-11e9-942a-c316d976e93b.png)

**Comment by yuxishua** [comment]
> 代码截图出来
![image](https://user-images.githubusercontent.com/7563822/58940577-5a435e80-87ac-11e9-8f78-b9148a32bff0.png)

**Comment by zhangdaiscott** [comment]
事务注解是加在service的方法上，不是加在control 的方法
