### ISSUE TITLE
AutoPOI（Excel工具）一对多导出needMerge  有某条数据对应数量小于2时报错

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1840]
##### 版本号：
2.3.0

##### 问题描述：
当一对多导出一个list时，某list中某条数据没有对应到多条，即@ExcelCollection注解的list的size小于2时会报错

##### 截图&代码：

![QzpcVXNlcnNceXVuZHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDUxNzU5NzE1Ml92MlxJbWFnZUZpbGVzXDk0MTIyMzNcMTYwMjQ5MTg1NDg4OV80RERGODc1MC02NTlDLTQzYTYtOTZFNC03NjdBOEYzMEQyOTIucG5n](https://user-images.githubusercontent.com/31750150/95725634-7e6d5480-0caa-11eb-8b5f-2a88a7322b2d.png)
![QzpcVXNlcnNceXVuZHVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDUxNzU5NzE1Ml92MlxJbWFnZUZpbGVzXDk0MTIyMzNcMTYwMjQ5MTgzODc5MF81QTREMDRCNS03Q0IxLTQwOTUtQkZDMi02REIxRDg1MEI2MDYucG5n](https://user-images.githubusercontent.com/31750150/95725643-82997200-0caa-11eb-8f05-4fb0d2bcbab0.png)

解决方案：
AutoPOI
ExcelExportBase第133行sheet.addMergedRegion(new CellRangeAddress(index, index + maxHeight - 1, cellNum, cellNum));
增加判断
![1](https://user-images.githubusercontent.com/31750150/95727747-313eb200-0cad-11eb-9ebe-27ea82590ca0.png)
![2](https://user-images.githubusercontent.com/31750150/95727758-34d23900-0cad-11eb-9ae8-5733db4cf73c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待新版本发布

**Comment by zhangdaiscott** [comment]
autopoi版本号改为  1.2.2
https://search.maven.org/artifact/org.jeecgframework/autopoi/1.2.2/jar
