### ISSUE TITLE
j-model

### ISSUE THREAD

**Issue by baobeiyatou** [zhangdaiscott/jeecg-boot#1841]
##### 版本号：
2.3

##### 问题描述：
j-model点击确认后，怎么回调上个页面的上方法

##### 截图&代码：
![微信截图_20201012182443](https://user-images.githubusercontent.com/39516154/95736026-410fc380-0cb8-11eb-967e-909769a30189.png)
![微信截图_20201012182457](https://user-images.githubusercontent.com/39516154/95736036-42d98700-0cb8-11eb-8158-a0b3bebf452c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
重写自己的ok方法如下所示
@ok="myOk"
