### ISSUE TITLE
切换微服务后，部署到服务器上启动时quartz报错

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-boot#1842]
##### 问题描述：
ClusterManager: Error managing cluster: Failure updating scheduler state when checking-in: Lock wait timeout exceeded; try restarting transaction

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://www.cnblogs.com/beiyeren/p/4191570.html
