### ISSUE TITLE
生成的表单复制到项目内,如果菜单配置为一级菜单后,各一级菜单切换时,页面刷新有问题

### ISSUE THREAD

**Issue by happyzsz** [zhangdaiscott/jeecg-boot#1843]
##### 问题描述：生成的表单复制到项目内,如果菜单配置为一级菜单后,各一级菜单切换时,页面刷新有问题
给人的感觉是先加载页面,再隐藏掉之前的页面

##### 截图&代码：

![image](https://user-images.githubusercontent.com/16953034/95813504-9b596480-0d4a-11eb-80d4-d3e86e90defb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by chongyangwang** [comment]
确实存在，就是切换时不流畅，盲猜是布局的问题

**Comment by witcube** [comment]
尤其在一级菜单页面和二级菜单页面切换时尤为明显，望重视下这个问题。

**Comment by hlzfr** [comment]
同样发现有这个问题

**Comment by zhangdaiscott** [comment]
[TabLayout.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5724897/TabLayout.zip)
 已解决，用附件覆盖代码
