### ISSUE TITLE
部署到服务器上，tomcat报错

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#1845]
##### 版本号：
2.3.0

##### 问题描述：
部署到服务器上，tomcat报错，本地没问题，这文件我也没动过，不知道问题在哪

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49867691/95828380-8212e100-0d67-11eb-8390-2dd0fa68ef04.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
单体还是集群，光发这一个图，无法分析

**Comment by dskl1** [comment]
单体
