### ISSUE TITLE
菜单权限为什么不能做到权限限制？

### ISSUE THREAD

**Issue by Hachiko-JQ** [zhangdaiscott/jeecg-boot#1846]
##### 版本号：
2.0.2

##### 问题描述：
角色赋予的菜单权限，只是可见和不可见，具体的页面初始接口可以越权调用

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273973
