### ISSUE TITLE
Online报表系统变量应用

### ISSUE THREAD

**Issue by shiyongcui** [zhangdaiscott/jeecg-boot#1847]
##### 版本号：
2.3.0

##### 问题描述：
当登录用户属于多个部门时，sys_org_code获取的部门信息还是上次登录所选的部门，不是本次登录所属的部门，这个变量值我在哪修改呢

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55284347/95835461-d1114400-0d70-11eb-8837-aead67e87a89.png)
![image](https://user-images.githubusercontent.com/55284347/95835553-f30ac680-0d70-11eb-8a81-73aa8cf6f7fd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
更新代码吧，近期修改了这个问题
