### ISSUE TITLE
在线开发同步数据库功能问题

### ISSUE THREAD

**Issue by kin1994** [zhangdaiscott/jeecg-boot#1849]
##### 版本号：
2.2.0

##### 问题描述：
在线开发同步数据库功能，有中文无法同步。服务器系统版本window版本server 2016,系统默认编码GBK。其他功能使用中文是没问题的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11944421/95878316-aabacb00-0da7-11eb-9b78-9e19189c9d83.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
65
