### ISSUE TITLE
Table表格修改表头背景颜色问题

### ISSUE THREAD

**Issue by MyAcooL** [zhangdaiscott/jeecg-boot#1852]
##### 版本号：
2.3

##### 问题描述：
我想替换Table表头的背景颜色，根据Api：customHeaderCell 更改了表头的颜色，但是表格有复选框，复选框没有改变背景，我想问怎么才能将复选框的背景颜色也改掉，

##### 截图&代码：

![image](https://user-images.githubusercontent.com/21095161/96089961-2331a100-0efa-11eb-8f6b-3cef46aeb06f.png)

![image](https://user-images.githubusercontent.com/21095161/96089991-2dec3600-0efa-11eb-8701-475212223378.png)

![image](https://user-images.githubusercontent.com/21095161/96090105-52e0a900-0efa-11eb-8b40-bb1597675679.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
建议复写table的样式来修改，如果不知道如何写样式，建议问下你们的前端人员
