### ISSUE TITLE
dict_item中的item_value如果存在_字典会失效

### ISSUE THREAD

**Issue by wl0927** [zhangdaiscott/jeecg-boot#1854]
##### 问题描述：
dict_item中的item_value如果存在_字典会失效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40060109/96100113-93462400-0f06-11eb-93bb-fc1aacf0f0a6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待下版本发布
