### ISSUE TITLE
建议升级swagger-bootstrap-ui依赖版本

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1856]
##### 版本号：
2.3

##### 问题描述：
SwaggerBootstrapUi提供的增强功能开启后也不生效，忽略参数等功能不管用
建议升级com.github.xiaoymin-swagger-bootstrap-ui依赖版本
[https://gitee.com/xiaoym/knife4j](https://doc.xiaominfo.com/guide/)

##### 截图&代码：
![03B1895A-A1AC-44fa-B176-A6DD4F532958](https://user-images.githubusercontent.com/31750150/96104256-313bed80-0f0b-11eb-9b6d-ceb5526ebd60.png)

```
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>swagger-bootstrap-ui</artifactId>
	<version>1.9.6</version>
</dependency>
```
1.9.6可升级到2.0.5
```
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-spring-boot-starter</artifactId>
	<version>2.0.5</version>
</dependency>
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
等下个版本升级发布
