### ISSUE TITLE
怎么去掉报表页面上的“导出”按钮，或者说报表页面的代码在哪里？

### ISSUE THREAD

**Issue by Atticusw** [zhangdaiscott/jeecg-boot#1858]
##### 版本号：
jeecg boot 2.2.0

##### 问题描述：
在线报表生成的页面中有一个excel的导出按钮，想隐藏掉。

##### 截图&代码：

![1602816214(1)](https://user-images.githubusercontent.com/34791192/96206966-a73c6500-0f9c-11eb-8397-b61367f35a97.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持
