### ISSUE TITLE
代码向后兼容问题

### ISSUE THREAD

**Issue by Ray-Sir-Like** [zhangdaiscott/jeecg-boot#186]
版本jeecg-boot V2.0.1 
之前V1.0版本使用了org.jeecg.modules.system.mapper.SysUserMapper中的SysUser getUserById(@Param("id") String id)这个方法,在把代码合并到现在的版本时,发现没有了这个方法,是不是jeecg-boot社区的更新不考虑向后兼容问题?

**Comment by zhangdaiscott** [comment]
改动应该不大，可以自己手工调整
