### ISSUE TITLE
导出参数没有高级查询参数

### ISSUE THREAD

**Issue by justspeedming** [zhangdaiscott/jeecg-boot#1860]
##### 版本号：

2.3
##### 问题描述：

excel表导出没有高级查询参数  建议将let param = {...this.queryParam};改为let param = { ...this.getQueryParams() }
##### 截图&代码：
handleExportXls(fileName){
      if(!fileName || typeof fileName != "string"){
        fileName = "导出文件"
      }
      let param = {...this.queryParam};
      if(this.selectedRowKeys && this.selectedRowKeys.length>0){
        param['selections'] = this.selectedRowKeys.join(",")
      }
      console.log("导出参数",param)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修改下个版本更新
