### ISSUE TITLE
360浏览器兼容模式和IE浏览器，IE11内核完全进不去，一直处于加载状态 ，进不了首页，最新代码本地进不去，打包之后也进不去

### ISSUE THREAD

**Issue by Luohan-123** [zhangdaiscott/jeecg-boot#1863]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/72602089/96246840-ce665700-0fdb-11eb-9335-98f755f0ea70.png)
IE浏览器
![image](https://user-images.githubusercontent.com/72602089/96246881-e047fa00-0fdb-11eb-96a6-2f77a2f3a1c1.png)
360兼容模式IE11内核
![image](https://user-images.githubusercontent.com/72602089/96238546-32cfe900-0fd1-11eb-964f-7e3845d8daaf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下载最新代码试试

**Comment by Luohan-123** [comment]
我用的就是最新代码呀，一直保持这个状态，登录页都进不去呀！您本地测试
一下咯![image](https://user-images.githubusercontent.com/72602089/96325663-2fce0a80-105c-11eb-9faa-e7a5820cf6b9.png)

**Comment by OnlyOne2048** [comment]
@Luohan-123 请问您解决了吗，我也遇到了同样的问题

**Comment by LYHHS** [comment]
我也遇到同样的问题，请问您解决了没有
