### ISSUE TITLE
[组件相关]前端的组件可以在移动端使用吗

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1864]
##### 版本号：

2.3.0
##### 问题描述：

前端的组件，如popup，人员选择，部门选择，可以在移动端使用吗，有没有例子可以展示？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
移动端，指的是那个？ jeecg-uniapp吗

**Comment by yanchenchen** [comment]
嗯嗯，是的。

**Comment by zhangdaiscott** [comment]
等后面发布新移动版本就会有这功能

**Comment by yanchenchen** [comment]
冒昧问一句，有具体的发版时间吗？
现在在开发移动版本，目前的方案是用其他的ui组件来实现。如果后续开发，能够pc和移动端都能有统一的组件那是最好了。
