### ISSUE TITLE
【popup】如何控制popup只能选择一条记录

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1866]
##### 版本号：

2.3
##### 问题描述：
目前popup可以选择多条数据记录。
能否限制只能选择一条?
##### 截图&代码：

![image](https://user-images.githubusercontent.com/8335270/96430309-9574ef00-1234-11eb-87e8-8e747c9e4203.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273913

**Comment by yanchenchen** [comment]
在online的模式下能否实现这个功能，只选取一条记录？
不是使用这个组件

**Comment by zhangdaiscott** [comment]
下个版本会支持
