### ISSUE TITLE
[用户选择器，部门选择器相关]使用这两种选择器能否获得其他字段的数据，类似popup功能

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1867]
##### 版本号：

2.3
##### 问题描述：

目前使用用户选择器、部门选择器对应获得的是用户的账号和部门编号
能否如同popup那样，选择某个人员以后可以获得对应该人员的其他数据字段，比如realname

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273915

**Comment by yanchenchen** [comment]
在online的模式下能否实现这个功能，获取其他字段信息？
不是使用这个组件

**Comment by zhangdaiscott** [comment]
online可以用popup方式，自己配置
