### ISSUE TITLE
开发版本 类修改后，热加载无法生效

### ISSUE THREAD

**Issue by freedomme** [zhangdaiscott/jeecg-boot#1869]
##### 问题描述：
JeecgDemoController  在Controller 类修改后，如果不是重新启动程序，修改的内容是无法生效的. 无论是 eclipse还是 Idea都一样。

上述的开发环境 已经按照springboot-devtools 配置，例如 增加依赖 和 设置开发环境的 build project automatically .

##### 截图&代码：

    @GetMapping(value = "/hello")
    public Result<String> hello() {
        Result<String> result = new Result<String>();
        String s = "Hello.World " ;
        result.setResult(s );
        result.setSuccess(true);
        return result;
    }

修改成 ：

    @GetMapping(value = "/hello")
    public Result<String> hello() {
        Result<String> result = new Result<String>();
        String s = "Hello...................................World " ;
        result.setResult(s );
        result.setSuccess(true);
        return result;
    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用jrebel

**Comment by freedomme** [comment]
感谢提示
