### ISSUE TITLE
新增maven模块问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#187]
如果同时新增俩个模块，其中一个依赖另一个，打包的时候会自动去阿里云仓库拉取，结果肯定是拉不到的，即打包失败，请问这个问题有办法解决吗

**Comment by yuxishua** [comment]
A 依赖B，先执行B 的  mvn install,会把B 打包到你的本地maven库中，A打包时，也会先从本地库中找，本地找到了，也不会去阿里云库找，根源是你B没有在本地库中

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/
3、底层共通业务接口说明（新创建Maven模块项目）

jeecg-boot-module-system 项目禁止其他独立模块直接引用，如果需要共通API或者调用系统信息接口请使用
统一的业务接口：        jeecg-boot-base-common/org.jeecg.common.system.api.ISysBaseAPI(所有子模块需要的接口都在这里定义)
接口实现类在system里：  jeecg-boot-module-system/org.jeecg.modules.system.service.impl.SysBaseApiImpl
jeecg-boot-module-system不让直接引用的目的是，防止相互调用，另外让子模块项目更轻量，如果调用system，随着项目累计，会导致乱也不好维护。

**Comment by Nicky213Zhang** [comment]
> A 依赖B，先执行B 的 mvn install,会把B 打包到你的本地maven库中，A打包时，也会先从本地库中找，本地找到了，也不会去阿里云库找，根源是你B没有在本地库中

谢谢，谢谢。对maven多模块业务不熟悉，maven原理理解也不够，谢谢大佬了。
