### ISSUE TITLE
按部门选择用户控件问题

### ISSUE THREAD

**Issue by kin1994** [zhangdaiscott/jeecg-boot#1871]
##### 问题描述：
1.按部门选择用户要选择两次才能选中在控件上
2.用户列表部门显示不出来

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11944421/96562100-f4993900-12f2-11eb-9a91-bb99c529fa19.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
未发现你所说的问题
请检查你部门表数据

**Comment by zhangdaiscott** [comment]
第二个问题已经修复，下个版本发布
