### ISSUE TITLE
多个客户端同时登陆一个账号会导致客户端退出重新登录

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#1872]
##### 问题描述：多个客户端同时登陆同一个账号进入系统，会导致已经登录的账号正在操作中退出，
请问下这个相互踢人的操作的开关是在哪里控制的。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该不会啊，没做这个处理

**Comment by jave-joe** [comment]
> 应该不会啊，没做这个处理

测试的时候，之前就我一个人再搞，所以一直没有出现过这情况，最近登录的人逐渐增多，发现有时候正在界面操作中，结果弹出token失效要重新登录了。随着同时登录相同账号的人越来越多，出现的频率也越来越大。

**Comment by zhangdaiscott** [comment]
哪你跟踪下是redis中token丢失了

**Comment by jave-joe** [comment]
> 哪你跟踪下是redis中token丢失了

找到问题了，我在登录的controller里做了一些改造，生成token的工具类做了一些扩展，让token储存用户的更多信息，以提供别的应用拿到token后不用查库就能解出来当前用户的很多其他相关信息，而ShiroRealm类里的jwtTokenRefresh方法，刷新token生命周期的方法里生成token的签名没有改成我扩展的那个方法，所以导致token失效。
我的问题，这个issues可以关掉了。
