### ISSUE TITLE
新追加的菜单页面，刷新后直接进入系统404

### ISSUE THREAD

**Issue by Antony-Jia** [zhangdaiscott/jeecg-boot#1873]
##### 问题描述：新追加的菜单页面，刷新后直接进入系统404
新追加的菜单页面，刷新后直接进入系统404，在devserver和nginx都会出现

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58219593/96662587-3e306500-1381-11eb-957b-37a8770f47d0.png)
![image](https://user-images.githubusercontent.com/58219593/96662600-47213680-1381-11eb-875b-f5eba55261f1.png)
![image](https://user-images.githubusercontent.com/58219593/96662619-4ee0db00-1381-11eb-8118-b3164e459b5b.png)
![image](https://user-images.githubusercontent.com/58219593/96662640-5607e900-1381-11eb-893f-430540aff0af.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
nginx没配置好
http://doc.jeecg.com/1273922

**Comment by Antony-Jia** [comment]
![image](https://user-images.githubusercontent.com/58219593/96675541-aa20c680-139d-11eb-97f9-b2c21e09d6be.png)
我就这这样配置的，但是依然存在问题，我打开了 proxy_intercept_errors on;
再次转发进入才可以
        error_page 404 /404.html;
        location = /404.html {
                root /root/jeecg/dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;

        }

**Comment by Antony-Jia** [comment]
补充一下，是因为添加的路径和后台路径前缀相同了，Nginx配置出现了覆盖的情况，修改后可以了
