### ISSUE TITLE
jeecg-boot代码生成提示成功但是并没有生成代码

### ISSUE THREAD

**Issue by yangmc0609** [zhangdaiscott/jeecg-boot#1874]
##### 截图&代码：
![QQ图片20201021095328](https://user-images.githubusercontent.com/72962076/96663511-5e612380-1383-11eb-99c5-fbd870cb618e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yangmc0609** [comment]
后台也没有报错

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1684391

**Comment by yangmc0609** [comment]
> http://doc.jeecg.com/1684391

还是一样不生成代码。。

**Comment by 408043749** [comment]
我试了下也无法生成 @zhangdaiscott

**Comment by 408043749** [comment]
@yangmc0609  你的项目目录下是不是有中文 我试了下中文是没法生成的，改成英文就可以了
@zhangdaiscott 2.3版本如果项目目录存在中文，代码生成错误日志没有打印出来，2.2.1版本是有日志的，建议文档加个说明

**Comment by laichenchen** [comment]
请问这个问题怎么解决的，我的也无法生成代码

**Comment by freeorder** [comment]
昨天也遇到这个问题，在打过一次jar包之后代码生成就不能用了，重新切换成dev配置，install之后重启解决问题
