### ISSUE TITLE
职位/部门选择器， buttons设为false，disabled为true时，还可以点击修改

### ISSUE THREAD

**Issue by catlvsuger** [zhangdaiscott/jeecg-boot#1876]
##### 问题描述：
    职位选择器， buttons设为false，disabled为true时，还可以点击修改

##### 截图&代码：
components/jeecgbiz/JSelectBizComponent/index.vue
![image](https://user-images.githubusercontent.com/39261781/96685894-579cd580-13b0-11eb-8fe5-cadf52498bfe.png)
@click.native="visible=(buttons?visible:true)"
修改为：@click.native="visible=(buttons || disabled ?visible:true)"，问题解决

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
感谢，已采纳，等下个版本发布
