### ISSUE TITLE
online表单配置，是否只读选项在一对表模板中无效

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1878]
##### 截图&代码：

![微信图片_20201022104156](https://user-images.githubusercontent.com/54636793/96818104-66889400-1453-11eb-9482-30397fd7d340.png)
![微信图片_20201022104125](https://user-images.githubusercontent.com/54636793/96818118-6b4d4800-1453-11eb-91b2-66b82e31bced.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你说功能测试不好用吗

**Comment by lijinlang** [comment]
> 你说功能测试不好用吗

是的，生成代码也没用，我已经勾选了只读了，还实际还是可以编辑的。但是对单表的有效的，像一对多的话这个是否只读就没用了。另外我想修改生成模板，但是没有is_read_only这列数据，所以也没办法弄

**Comment by zhangdaiscott** [comment]
代码生成器下个版本支持

**Comment by zhangdaiscott** [comment]
功能测试用的是那个模板，我们测试是好用的

**Comment by lijinlang** [comment]
我的是一对多的

> 功能测试用的是那个模板，我们测试是好用的

这个附表
![微信图片_20201022113625](https://user-images.githubusercontent.com/54636793/96821628-e49c6900-145a-11eb-8baa-24df59820677.png)

**Comment by lijinlang** [comment]
另下问下这个POPUP弹出框，多选怎么实现啊
![微信图片_20201022114455](https://user-images.githubusercontent.com/54636793/96822205-1c57e080-145c-11eb-86be-e99897ecf702.png)

**Comment by 1298191366** [comment]
经测试无问题
