### ISSUE TITLE
官方代码中没有找到【queryAllAuth】【queryUserAuth】相关代码

### ISSUE THREAD

**Issue by wlgshf** [zhangdaiscott/jeecg-boot#1879]
##### 版本号：
当前最新版本： 2.3（发布日期：2020-09-14）

##### 问题描述：
列表列字段导出权限控制 官方代码中没有找到【queryAllAuth】【queryUserAuth】相关代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28797161/96820275-398ab000-1458-11eb-9b6c-5ea5e67ab26b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![Uploading image.png…]()

**Comment by wlgshf** [comment]
github上代码是没有的 能把您本地代码提交下吗？

**Comment by wlgshf** [comment]
gihub上最新版本是没有上面这段代码的，你截图应该是你本地的代码吧 ！！没有上传提交！

**Comment by zhangdaiscott** [comment]
哪应该是近期开发的，等下个版本发布

**Comment by wlgshf** [comment]
能否先给我xml文件  我先跑跑功能！
