### ISSUE TITLE
j-image-upload控件循环图片不显示

### ISSUE THREAD

**Issue by henguofang** [zhangdaiscott/jeecg-boot#1882]
##### 版本号：
2.3

##### 问题描述：
j-image-upload控件循环图片不显示

##### 截图&代码：
 
![image](https://user-images.githubusercontent.com/9315465/96945784-39022000-1511-11eb-8b7a-e7965888cfd9.png)

 <a-row type="flex" style="margin-bottom:10px;margin-left:50px" :gutter="16" v-for="(item, index) in recommendList" :key="index">
                    <a-col :span="5">
                      <a-form-item>
                        <j-image-upload  v-decorator="['recommendList['+index+'].templatePictureUrl',{'initialValue':item.templatePictureUrl}]"/>
                      </a-form-item>
                    </a-col>

![image](https://user-images.githubusercontent.com/9315465/96945827-57681b80-1511-11eb-969c-466e1e6e4016.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
watch监听问题，JImageUpload 中watch 加入 immediate: true

**Comment by zhangdaiscott** [comment]
升级文件
[JImageUpload.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5479574/JImageUpload.zip)
