### ISSUE TITLE
如何实现JEditableTable中的POPUP 弹窗记录多选

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#1885]
##### 截图&代码：
![96822205-1c57e080-145c-11eb-86be-e99897ecf702](https://user-images.githubusercontent.com/54636793/96960226-6a401780-1534-11eb-97fd-bf1f66d8d853.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
2.3版本已实现
