### ISSUE TITLE
sql注入

### ISSUE THREAD

**Issue by jinnywc** [zhangdaiscott/jeecg-boot#1887]
##### 版本号：
2.3

##### 问题描述：
After testing, it is found that the code parameter of /jeecg boot/sys/dict/loadtreedata interface of jeecg-boot has SQL injection

##### 截图&代码：
Reuse https://github.com/zhangdaiscott/jeecg-boot After the source code of the project starts the project, click "custom component" and grab the package to get the interface with SQL injection, and use sqlmap to prove the existence of SQL injection

![1-1](https://user-images.githubusercontent.com/30540295/97078366-6a1c4680-161e-11eb-9c29-6d66dc5179ec.png)
![1-2](https://user-images.githubusercontent.com/30540295/97078370-6f799100-161e-11eb-875c-49e2f9715fb9.png)
![1-3](https://user-images.githubusercontent.com/30540295/97078373-743e4500-161e-11eb-8e62-ec94efbbb694.png)
The vulnerability code exists in the following code:\jeecg-boot\jeecg-boot-module-system\src\main\java\org\jeecg\modules\system\controller\SysDictController.java At line 290 of
![1-4](https://user-images.githubusercontent.com/30540295/97078446-f0d12380-161e-11eb-8cfe-34f72410f730.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已加入關鍵詞過濾
