### ISSUE TITLE
  There is an arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by jinnywc** [zhangdaiscott/jeecg-boot#1888]
##### 版本号：
2.3

##### 问题描述：
After testing, it is found that there is an arbitrary file upload vulnerability in the image upload function of "custom component" of jeecg boot, and the interface is /jeecg-boot/sys/common/upload

##### 截图&代码：

Reuse https://github.com/zhangdaiscott/jeecg-boot After the source code of the project is started, click "custom component" and grab the package to get the interface with arbitrary file upload vulnerability
![1-1](https://user-images.githubusercontent.com/30540295/97079126-1876ba80-1624-11eb-80c1-8272fb9b7afe.png)
Modify the upload suffix name and upload content through packet capture
![任意文件上传1-2](https://user-images.githubusercontent.com/30540295/97079157-4bb94980-1624-11eb-8a8b-6614de52c268.png)
The vulnerability code exists in the following code:\jeecg-boot\jeecg-boot-base-common\src\main\java\org\jeecg\common\system\controller\CommonController.java At line 76 of
![1-3](https://user-images.githubusercontent.com/30540295/97079179-6986ae80-1624-11eb-9043-082a6a961382.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
具體的功能驗證細節可以自行修改，這個上傳也僅僅是個實例

**Comment by Conan924** [comment]
上传到什么目录可以解析？
