### ISSUE TITLE
j-editor组件选上传图片浏览器直接卡死

### ISSUE THREAD

**Issue by hiyaojie** [zhangdaiscott/jeecg-boot#189]
官网演示和本地测试都是卡死
![image](https://user-images.githubusercontent.com/14881927/59014785-faae8700-886f-11e9-840b-64e3d8a98043.png)

**Comment by ileadall42** [comment]
@hiyaojie 建议你看一下tinymce文档，然后配置一下url就可以了。

**Comment by tygithub1** [comment]
我测试是可以的，你是哪个页面，哪个浏览器？
