### ISSUE TITLE
首页点击其他菜单跳转页面时,2个页面会出现同时出现的问题

### ISSUE THREAD

**Issue by ZhouNick** [zhangdaiscott/jeecg-boot#1893]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/22462099/97129912-ff345200-177a-11eb-84e5-2d50c14214d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
录个视频

**Comment by ZhouNick** [comment]
是用了三级的routeView造成,APP.vue里有一个router-view,components文件夹下的layouts -&gt; TabLayout有个router-view,然后layouts -&gt;Routeview.vue里也有router-view,这样写没问题,但是router-view出口渲染的时候可能会有个时间差,造成这种现象




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午11:40
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"whisper"<2715826867@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 首页点击其他菜单跳转页面时,2个页面会出现同时出现的问题 (#1893)





 
录个视频

**Comment by kevin-lr** [comment]
一级路由也有这个问题，请问怎么解决

**Comment by tygithub1** [comment]
什么浏览器

**Comment by zhangdaiscott** [comment]
[TabLayout.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5724897/TabLayout.zip)
 已解决，用附件覆盖代码
