### ISSUE TITLE
Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist

### ISSUE THREAD

**Issue by Derickorqq** [zhangdaiscott/jeecg-boot#1894]
##### 版本号：
v2.3

##### 问题描述：

问题1: 数据库QRTZ_LOCKS表真实存在 异常提示 Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist
看大家很早就提出这个问题了，但是这么久了sql脚本竟然还是存在这么不严谨的错误，我也是醉了。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
10

**Comment by Derickorqq** [comment]
> http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 10

这个我也看到了，确实也可以解决，但是如果是我的开源产品，别人按照文档修改完后运行报bug，然后还要在这边搜一下解决方法，但是其实只需要你们修改一下就行了，想想是不是不太好。明知道是一个不严谨bug，但是就非要留着，真的有点说不过去啊。

**Comment by Drun1baby** [comment]
同样遇到了这个问题，麻了
