### ISSUE TITLE
Spring Framework反射型文件下载漏洞风险报告

### ISSUE THREAD

**Issue by OnTheWay6** [zhangdaiscott/jeecg-boot#1896]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/49018425/97138529-63fba680-1793-11eb-8e7d-7a313836482f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
在Spring Framework（5.2.x之前的5.2.x版本，5.1.13之前的5.1.x版本和5.0.16之前的5.0.x版本）中，应用程序容易受到反射型文件下载（RFD）攻击。攻击是通过在响应中设置“ Content-Disposition”响应标头引起的，其中文件名属性来自用户提供的输入。

我们认为漏洞级别很高，危害/影响很大。建议Spring MVC或Spring WebFlux用户及时安装最新的补丁程序，以避免被黑客入侵。

受影响的版本

5.2.0至5.2.2
5.1.0至5.1.12
5.0.0至5.0.15
解决方法

建议Spring Framework 5.2.x用户升级到Spring Framework 5.2.3。 Spring Framework 5.1.x用户应升级到Spring Framework 5.1.13。 Spring Framework 5.0.x用户应升级到Spring Framework 5.0.16。
