### ISSUE TITLE
设置token过期时间，并没有起到实际作用

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#1897]
##### 版本号：
2.2.1

##### 问题描述：
修改了后台的token过期时间，但是实际在登录过程中，token过期时间还是没有根据设置的进行变化，请问还有什么其他地方需要设置token过期时间才能生效吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30401919/97248892-bb565100-183d-11eb-90e4-2186f241373d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wlgshf** [comment]
你这是设置token缓存时间，下载这个地方设置token有效时长
![image](https://user-images.githubusercontent.com/28797161/97252073-1ab75f80-1844-11eb-8dc4-394f4e12d1c8.png)

**Comment by wlgshf** [comment]
这个地方再设置下看看
![image](https://user-images.githubusercontent.com/28797161/97252162-49cdd100-1844-11eb-8089-5fefb62c35f2.png)

**Comment by aliaizhetaozi** [comment]
我将这里修改为1分钟还是没有起到实际效果


| |
白乐天
|
|
qdbailetian@163.com
|
签名由网易邮箱大师定制
在2020年10月27日 11:04，songc<notifications@github.com> 写道：

你这是设置token缓存时间，下载这个地方设置token有效时长

**Comment by wlgshf** [comment]
修改为一分钟后  你观察下redis里面  等他有效时间一到 这时候在登陆就会提示token失效，源代码失效时长给设置的是你token有效时间的2倍
![image](https://user-images.githubusercontent.com/28797161/97261047-f87c0c80-1858-11eb-8fce-db8123d77656.png)
