### ISSUE TITLE
JeecgBoot2.3微服务版前端直接访问某页面报错问题

### ISSUE THREAD

**Issue by womeng2009** [zhangdaiscott/jeecg-boot#1899]
##### 截图&代码：
devServer配置:
![image](https://user-images.githubusercontent.com/64006143/97269915-3da83a80-1869-11eb-9d40-aca7574804d3.png)
刷新页面通过URL访问其他页面报错：
![image](https://user-images.githubusercontent.com/64006143/97269938-4567df00-1869-11eb-820e-6f240296350e.png)

**Comment by wlgshf** [comment]
vue路由模式调整下就可以了
开发期间你可以注销掉下面红框内代码就可以了
![image](https://user-images.githubusercontent.com/28797161/97385954-cb3d6600-190d-11eb-8458-3149dddc8de2.png)
生成环境下这块不要调整，建议nginx配置
location / {
  try_files $uri $uri/ /index.html;
}

**Comment by wlgshf** [comment]
vue路由模式调整下就可以了
开发期间你可以注销掉下面红框内代码就可以了

![image](https://user-images.githubusercontent.com/28797161/97386106-19eb0000-190e-11eb-8e09-65f082579645.png)

**Comment by wlgshf** [comment]
![image](https://user-images.githubusercontent.com/28797161/97386155-3424de00-190e-11eb-8414-417355b6db46.png)
标记代码注释掉，调整下路由模式即可
生成环境下建议配置nginx

**Comment by zhangdaiscott** [comment]
给后端gateway项目加一个根路径
![Uploading image.png…]()

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1899
类似问题
