### ISSUE TITLE
js增强that.changeOptions设置下拉框选项不能及时生效

### ISSUE THREAD

**Issue by helloWorldPsyduck** [zhangdaiscott/jeecg-boot#1901]
##### 版本号：
2.3

##### 问题描述：
Online表单开发，生成表test_table。
通过js增强，实现下拉框A的值改变时，下拉框B的值同步修改。
目前效果：
在test_table的在线测试页面，点击【新增】，修改下拉框A的选项，js执行了that.changeOptions，但是打开下拉框B发现内容并没有更新。
此时如果关闭【新增】弹窗，然后再次点击【新增】，打开下拉框B，发现内容被更新

##### 截图&代码：
js增强代码如下：（选择班级后显示对应班级的学生信息）
onlChange(){
	return {
		clazz_id(){
    		let value = event.value
		getAction('****',{clazz_id:value}).then(res=>{
			let stuOptions = []
			for(let i=0;i<res.length;i++){
				stuOptions.push({text:res[i].name,value:res[i].id})
			}
			that.changeOptions('student_id',stuOptions)
			}
		)
    	}
  	}
}

**Comment by zhangdaiscott** [comment]
分配

**Comment by lvdandan16** [comment]
参考文档：http://doc.jeecg.com/1833670

**Comment by mifunc** [comment]
> 参考文档：http://doc.jeecg.com/1833670

文档失效了，可以更新一下吗？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044101

**Comment by mifunc** [comment]
@zhangdaiscott  that.changeOptions  需要关闭，重新再打开的问题新版本有解决吗？

**Comment by mifunc** [comment]
这上面好像也没有说明怎么解决。http://doc.jeecg.com/2044101
