### ISSUE TITLE
省市区组件校验必填配置无效

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#1902]
##### 版本号： 
2.3

##### 问题描述：
online表单开发，选择省市区控件，并勾选校验必填，类型非空，功能测试时校验未生效

##### 截图&代码：
在线演示中ss_test表配置了测试
![image](https://user-images.githubusercontent.com/26364818/97387289-a8f91780-1910-11eb-82a2-c93bf13c90d6.png)
![image](https://user-images.githubusercontent.com/26364818/97387347-c1693200-1910-11eb-8831-b7df7676e778.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
等下个版本修复
