### ISSUE TITLE
在线开发JS增强导入到本地后不起作用

### ISSUE THREAD

**Issue by Seizedays233** [zhangdaiscott/jeecg-boot#1903]
##### 版本号：
 v2.3

##### 问题描述：
在线编辑的js增强代码 在线编辑时起作用 导入到本地之后JS增强的功能失效，不起作用

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
js增强不支持代码生成器生成
