### ISSUE TITLE
前端打包上线之后，首页加载慢

### ISSUE THREAD

**Issue by hiniwo** [zhangdaiscott/jeecg-boot#1906]
##### 问题描述：
打包上线之后，默认会加重所有的js文件，导致首页加载慢。理想应该是按需加载

##### 截图&代码：
![20201028191546](https://user-images.githubusercontent.com/35565618/97429463-6b1ce300-1952-11eb-9a25-6964edd8fbf9.png)

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&extra=page%3D1
53
