### ISSUE TITLE
前端项目部署到nginx时访问不到，希望官方最好出一个部署linux教学视频

### ISSUE THREAD

**Issue by taolovelx** [zhangdaiscott/jeecg-boot#1908]
##### 问题描述：
前后端分离的项目打包部署到linux上，前端项目部署到nginx时访问不到，确实有点解决不了，希望官方可以出一个部署linux教学视频，这样最好，我遇到的问题如下

##### 截图&代码：
[
![1](https://user-images.githubusercontent.com/56075723/97448106-3a957300-196b-11eb-8d72-d17cc6919812.gif)

](url)
![2](https://user-images.githubusercontent.com/56075723/97448931-1f773300-196c-11eb-908c-cebd7e3d84f5.gif)
![3](https://user-images.githubusercontent.com/56075723/97449308-7d0b7f80-196c-11eb-97b3-4c9d0460d5f1.gif)
![image](https://user-images.githubusercontent.com/56075723/97449521-b93ee000-196c-11eb-9345-da8954365c1f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273922
