### ISSUE TITLE
Jeecg-boot后端项目，构建过程shiro报依赖错误

### ISSUE THREAD

**Issue by Pa-Star-Home** [zhangdaiscott/jeecg-boot#1909]
##### 版本号：
最新版本： 2.3（发布日期：2020-09-14）

##### 问题描述：
步骤： git clone the 2.3 version , 编译后端jeecg-boot项目失败，有依赖冲突或是依赖错误(shiro依赖未导入)

##### 截图&代码：
构建错误提示： ShiroConfig.java
Error:(61, 51) java: 不兼容的类型: java.lang.SecurityManager无法转换为org.apache.shiro.mgt.SecurityManager

##### 个人后续解决：
将版本向前切换为 v2.2.1版本，构建成功

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该是环境问题
