### ISSUE TITLE
部门和部门角色权限丢失

### ISSUE THREAD

**Issue by gqf1995** [zhangdaiscott/jeecg-boot#1910]
##### 版本号：
2.2

##### 问题描述：
部门和部门角色权限丢失

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20791771/97534042-48dba180-19f4-11eb-8e34-6d4eede277ad.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述太简单

**Comment by gqf1995** [comment]
比如原来部门是有仪表盘这个权限的，过一天之后这个部门就没有了。 还有一个问题是，最顶级公司的部门角色管理员，首页菜单权限丢失，导致旗下所有子部门菜单权限丢失。没有人动权限这部分。

**Comment by Xiaotian0617** [comment]
我也出现了，系统没有修改过，我甚至还加了日志，还以为是我个人的问题

**Comment by zhangdaiscott** [comment]
怎么重现

**Comment by gqf1995** [comment]
正常多编辑编辑菜单，部门下设置多点子部门，子部门都有一个部门角色作为管理员，每个子部门都有上级用户授权部门管理员角色。然后就是等待。大概每天都会丢失1-2个权限这样子

**Comment by gqf1995** [comment]
部门的用户是没有角色管理里的角色， 只有部门角色哈

**Comment by gqf1995** [comment]
最开始用户少部门少角色少，出现不频繁，出现这个问题也没在意，现在用户多了点，几十个部门就频繁出现了

**Comment by zhangdaiscott** [comment]
收录，我们试试看，是否能重现

**Comment by lvdandan16** [comment]
2.3版本下未复现问题，可否提供详细重现步骤？
