### ISSUE TITLE
前端页面改变浏览器窗口大小后，菜单展开按钮失效，无法展开菜单，无法操作

### ISSUE THREAD

**Issue by HanLinfeng** [zhangdaiscott/jeecg-boot#1913]
##### 截图&代码：
![视频_2020-10-30_104514 00_00_00-00_00_30](https://user-images.githubusercontent.com/17738551/97654558-200fe680-1a9e-11eb-9b6a-7cb7e6b22af3.gif)

视频文件：
[视频_2020-10-30_104514.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5462732/_2020-10-30_104514.zip)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已经修复了，更新最新代码

**Comment by HanLinfeng** [comment]
昨天刚更新的代码

**Comment by zhangdaiscott** [comment]
用这个覆盖
src/components/page/GlobalLayout.vue

[GlobalLayout.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5463723/GlobalLayout.zip)
