### ISSUE TITLE
【BUG】文件下载异常错误

### ISSUE THREAD

**Issue by lokbun** [zhangdaiscott/jeecg-boot#1915]
##### 版本号：

v2.2.1
##### 问题描述：

当文件名中含有[]方括号时，保存至服务器时按原文件名保存时，下载的时候会有异常错误，导致下载文件失败。
目前临时方案将方括号替换为小括号
##### 截图&代码：

![image](https://user-images.githubusercontent.com/4335617/97713523-e9b48480-1afa-11eb-8d18-6a12d0d169bf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个自己处理吧
