### ISSUE TITLE
切换微服务后，前端登录后，强制刷新页面会报token为空错误

### ISSUE THREAD

**Issue by zombietramp** [zhangdaiscott/jeecg-boot#1917]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/1066758/97778288-4f634800-1bb1-11eb-9b0c-43121f9b28c5.png)

![image](https://user-images.githubusercontent.com/1066758/97778350-9c471e80-1bb1-11eb-9410-645d85be0aa9.png)

![image](https://user-images.githubusercontent.com/1066758/97778368-b2ed7580-1bb1-11eb-8a25-8aa6db4e94c6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zombietramp** [comment]
找到其他解决方法

**Comment by CodeFly16** [comment]
请问如何解决的
