### ISSUE TITLE
页面左边被菜单遮挡一部分

### ISSUE THREAD

**Issue by gqf1995** [zhangdaiscott/jeecg-boot#1918]
##### 版本号：
2.2

##### 问题描述：
页面左边被菜单遮挡一部分，该情况不定时出现，出现一阵过后恢复正常

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20791771/97840097-64111e80-1d1e-11eb-9a83-a9b4a7034bf0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请提供重现步骤
