### ISSUE TITLE
数据库导入表单功能BUG

### ISSUE THREAD

**Issue by hualongchen** [zhangdaiscott/jeecg-boot#1919]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/11953958/97840564-32e51e00-1d1f-11eb-813f-9ef08cd48afa.png
            @RequiresRoles({"admin"}) 在该方法头上加这个比较好点

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
因为这个操作涉及到数据库，比较敏感，所以admin没什么问题
