### ISSUE TITLE
j-search-select-tag 使用下拉搜索框 加载字典数据 因数据太多 选择点击时 慢 甚至卡死 请求优化方案

### ISSUE THREAD

**Issue by asevfish** [zhangdaiscott/jeecg-boot#1924]
##### 问题描述：
j-search-select-tag 使用下拉搜索框 加载字典数据 因数据太多(差不多5000条) 选择点击时 慢 甚至卡死 请求优化方案

##### 截图&代码：
![image](https://user-images.githubusercontent.com/73863060/97937499-d5ea7600-1db9-11eb-91a8-6b279b631864.png)

![image](https://user-images.githubusercontent.com/73863060/97937488-ce2ad180-1db9-11eb-9cff-7319bf5b8cd8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以改成异步分页加载

**Comment by asevfish** [comment]
> 可以改成异步分页加载

有示例嘛 我想学习下

**Comment by tygithub1** [comment]
设置async属性即可  后续版本发布
