### ISSUE TITLE
后台在线生成表单校验规则修改

### ISSUE THREAD

**Issue by yhjlsy123** [zhangdaiscott/jeecg-boot#1925]
##### 版本号：
2.3

##### 问题描述：
这个页面校验规则可以修改吗？怎么去修改？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17937790/97957617-8e2e1380-1de6-11eb-852c-65ebd4c2ca36.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个不支持，一个字母不规范
