### ISSUE TITLE
Online表单开发生成代码后，新增操作表单校验未通过却能保存成功

### ISSUE THREAD

**Issue by wanwhy27** [zhangdaiscott/jeecg-boot#1926]
##### 问题描述：
主子表单新增操作，子表单页面校验未通过也能操作成功，通过在Online表单开发-功能测试打开的页面新增操作没有问题，但是通过代码生成之后的页面操作就会出现问题。

##### 截图&代码：
通过菜单【在线开发-Online表单开发】将附表【ces_order_customer】订单客户的客户名字设为必填
![image](https://user-images.githubusercontent.com/73879785/97970881-28995180-1dfd-11eb-9c95-c1f060b982c9.png)
通过主表【ces_order_main】商城订单表的功能测试页面新增操作没有问题
![image](https://user-images.githubusercontent.com/73879785/97971830-9bef9300-1dfe-11eb-814e-b44b5fc7b404.png)
但是通过代码生成的页面新增操作确定之后
![image](https://user-images.githubusercontent.com/73879785/97971961-ce998b80-1dfe-11eb-94bc-46780ed36559.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成的代码目前不支持校验的生成，得下个版本，或者提前获取代码生成器加强版
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=9166
