### ISSUE TITLE
菜单重复出现，频闪

### ISSUE THREAD

**Issue by chengjinming** [zhangdaiscott/jeecg-boot#1928]
##### 版本号：
2.3

##### 问题描述：
菜单重复出现，

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54760504/98065324-58913500-1e8f-11eb-893d-224a222b39b7.png)
![image](https://user-images.githubusercontent.com/54760504/98065412-870f1000-1e8f-11eb-851f-320ec33a3bad.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请提供重现步骤

**Comment by chengjinming** [comment]
导航栏采用顶部导航栏 git clone下的代码无任何改动 
![image](https://user-images.githubusercontent.com/54760504/98079617-10820a80-1eaf-11eb-903d-d81ea82e76ea.png)
![image](https://user-images.githubusercontent.com/54760504/98079676-2ee80600-1eaf-11eb-8a2f-b00d07bd1cfc.png)
![image](https://user-images.githubusercontent.com/54760504/98079760-4fb05b80-1eaf-11eb-9588-efd81aba4c61.png)
![image](https://user-images.githubusercontent.com/54760504/98079844-77072880-1eaf-11eb-95fd-b55f7b31fa29.png)
clone下来的代码只改过 配置文件  数据库和redis
![image](https://user-images.githubusercontent.com/54760504/98079919-9900ab00-1eaf-11eb-8b60-9cd9a4a58227.png)

**Comment by lvdandan16** [comment]
问题未复现，可否提供详细重现步骤？
