### ISSUE TITLE
JEditaTable,子表默认添加一条数据，addDefaultRowNum设置无效

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#1930]
##### 问题描述：
   
   在data里设置0，1，2...都没有效果，最后在代码里直接写死一个数字也没有效果
   

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26954826/98186452-b71ae980-1f49-11eb-9797-277d52cfc40a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修正，下个版本发布
