### ISSUE TITLE
按照教程使用代码生成器测试demo

### ISSUE THREAD

**Issue by tanxvyang** [zhangdaiscott/jeecg-boot#1931]
##### 版本号：
2.3.0

##### 问题描述：
菜鸟一个，初次使用jeecgboot
按照教程使用代码生成器测试demo，代码生成成功但测试访问时显示资源未找到，浏览器报Uncaught (in promise) Error: Request failed with status code 404
请问是为什么？
##### 截图&代码：

![微信图片_20201105113518](https://user-images.githubusercontent.com/27222868/98194739-06b5e100-1f5b-11eb-82c8-67f5dc3082fc.png)

![微信图片_20201105113311](https://user-images.githubusercontent.com/27222868/98194591-bb033780-1f5a-11eb-9034-9a1e1bf3f19e.png)

![微信图片_20201105113319](https://user-images.githubusercontent.com/27222868/98194657-d706d900-1f5a-11eb-9995-8bc959974ea5.png)

Uncaught (in promise) Error: Request failed with status code 404
    createError createError.js:16
    settle settle.js:18
    handleLoad xhr.js:59
    dispatchXhrRequest xhr.js:34
    xhrAdapter xhr.js:11
    dispatchRequest dispatchRequest.js:59
    promise callback*request Axios.js:51
    wrap bind.js:9
    getAction manage.js:43
    loadData JeecgListMixin.js:75
    created JeecgListMixin.js:58

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
扫码路径配置了吗

**Comment by tanxvyang** [comment]
> 
> 
> 扫码路径配置了吗
菜单管理，角色授权都操作了

![03](https://user-images.githubusercontent.com/27222868/98235411-b790a000-1f9c-11eb-9b55-8605542e5b81.png)
后台查询语句及结果为0，如下。
![16](https://user-images.githubusercontent.com/27222868/98236434-4ce06400-1f9e-11eb-8b88-8ee1fb653a8b.png)
前台页面没有数据
![4](https://user-images.githubusercontent.com/27222868/98236532-77cab800-1f9e-11eb-9889-7d0f98f4f808.png)
![微4](https://user-images.githubusercontent.com/27222868/98236714-c5472500-1f9e-11eb-8947-34dccf588434.png)

另外
![x454](https://user-images.githubusercontent.com/27222868/98235693-21a94500-1f9d-11eb-9232-aeea1ae58947.png)
，教程此处所指的数据库是需要填表单同步的那个数据库（jeecg-boot）还是重新创建一个？
我的数据库安装在虚拟机里，Online表单开发里数据可以查到
![257](https://user-images.githubusercontent.com/27222868/98237057-47374e00-1f9f-11eb-97f9-90b94311c903.png)

**Comment by tanxvyang** [comment]
![图片](https://user-images.githubusercontent.com/27222868/98241583-1eff1d80-1fa6-11eb-9be1-2bca567d2e50.png)
路径也是有的，
点击之后后台如下？
![图片](https://user-images.githubusercontent.com/27222868/98242100-e6ac0f00-1fa6-11eb-9c54-94d1c3c17bf3.png)
