### ISSUE TITLE
菜单收缩为图标模式时,右侧区域滚动失效

### ISSUE THREAD

**Issue by happyzsz** [zhangdaiscott/jeecg-boot#1932]
##### 问题描述：
菜单收缩为图标模式时,右侧区域滚动失效
控制台无错误
##### 截图&代码：
![image](https://user-images.githubusercontent.com/16953034/98318099-d2a0f580-2018-11eb-976e-db53e868fb5e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
更新最新代码，已经修复
