### ISSUE TITLE
程序发布jar运行后，执行代码生成，结果页面显示空白

### ISSUE THREAD

**Issue by zjwang1234** [zhangdaiscott/jeecg-boot#1933]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/29996416/98318348-65da2b00-2019-11eb-9dfe-afa41edbb497.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1684391

**Comment by zjwang1234** [comment]
> http://doc.jeecg.com/1684391

我根据这个方法设置之后，再次打开代码生成，会提示表信息加载失败，如下图：
![image](https://user-images.githubusercontent.com/29996416/98323743-8f994f00-2025-11eb-88b6-810c56f08199.png)

我的数据库是mssql2008，jeecg_database.properties里的设置是：
#SQLServer 2008
driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
url=jdbc:sqlserver://192.168.8.100:1433;SelectMethod=cursor;DatabaseName=jeecg-boot
username=sa
password=${PASSWORD}
database_name=jeecg-boot
这个和系统主数据库是一样的，系统能登陆，说明数据库连接没问题吧。。。
