### ISSUE TITLE
后续问题。。。（程序发布jar运行后，执行代码生成，结果页面显示空白）

### ISSUE THREAD

**Issue by zjwang1234** [zhangdaiscott/jeecg-boot#1935]
> http://doc.jeecg.com/1684391

我根据这个方法设置之后，再次打开代码生成，会提示表信息加载失败，如下图：
![image](https://user-images.githubusercontent.com/29996416/98323743-8f994f00-2025-11eb-88b6-810c56f08199.png)

我的数据库是mssql2008，jeecg_database.properties里的设置是：
#SQLServer 2008
driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
url=jdbc:sqlserver://192.168.8.100:1433;SelectMethod=cursor;DatabaseName=jeecg-boot
username=sa
password=${PASSWORD}
database_name=jeecg-boot
这个和系统主数据库是一样的，系统能登陆，说明数据库连接没问题吧。。。

**Comment by zjwang1234** [comment]
![image](https://user-images.githubusercontent.com/29996416/98324803-3979db00-2028-11eb-8103-c9b8590f0e13.png)
docker日志里报这个错了

**Comment by zhangdaiscott** [comment]
说明打包少配置文件

**Comment by zjwang1234** [comment]
> 说明打包少配置文件

![image](https://user-images.githubusercontent.com/29996416/98326531-71831d00-202c-11eb-8a74-725e6783b022.png)
没有这个config的时候，可以加载表信息，就是生成代码页面会空白，按照http://doc.jeecg.com/1684391加了config文件夹后就换这个错误了。。。

**Comment by zjwang1234** [comment]
不好意思，可以了，我把diver_name写成了driver-class-name，直接复制的application.yml里的数据库连接名。。。这算个小坑么，o(*￣︶￣*)o
