### ISSUE TITLE
修改主题样式后，退出登录，登录界面样式BUG

### ISSUE THREAD

**Issue by huangyunjie** [zhangdaiscott/jeecg-boot#1936]
##### 版本号：
2.3.0

##### 问题描述：
修改主题样式后，退出登录，登录界面样式BUG

##### 截图&代码：

![微信截图_20201106120045](https://user-images.githubusercontent.com/32405710/98324652-d720da80-2027-11eb-9a57-b6a8b81660f2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己改的，无法处理
