### ISSUE TITLE
数据库字段是以单个字母和下划线开通的这个校验在哪里可以去除

### ISSUE THREAD

**Issue by li617913830** [zhangdaiscott/jeecg-boot#1938]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/49982274/98338775-ab145200-2045-11eb-8256-588d2e6d3a54.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
单字母不符合规范
