### ISSUE TITLE
【错误】无法加载验证码

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1939]
##### 版本号：
2.3

##### 问题描述：
部署服务到服务器后，无法加载验证码，网络错误是：net::ERR_CONNECTION_REFUSED

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8335270/98370303-54267100-2075-11eb-9159-c0071c9b46c2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by JoyTroy** [comment]
redis服务是否开启？

**Comment by yanchenchen** [comment]
redis 开启了。
参照https://github.com/zhangdaiscott/jeecg-boot/issues/1228
修改了src/utils/request.js，解决这个问题了。

登录后，还是出现同样的问题
![image](https://user-images.githubusercontent.com/8335270/98436831-9d300100-2119-11eb-9c55-97f5b8661798.png)

**Comment by yanchenchen** [comment]
系统管理下的子菜单，比如用户管理，请求不报错。
在线开发下的online表单开发，请求报错。

**Comment by dapsjj** [comment]
我也遇到这个问题了，看不到验证码，登录提示net::ERR_CONNECTION_REFUSED

**Comment by zhangdaiscott** [comment]
index.html页面的后台API地址改吗

**Comment by yanchenchen** [comment]
嗯嗯，后台地址改后就可以了。

**Comment by WangHao1221** [comment]
> 嗯嗯，后台地址改后就可以了。

我也遇到了，请详细指点迷津，谢谢
