### ISSUE TITLE
生成的代码导入，报错required a single bean, but 2 were found:

### ISSUE THREAD

**Issue by Pa-Star-Home** [zhangdaiscott/jeecg-boot#1940]
##### 版本号：
v2.2.1

##### 问题描述：
环境： 将jeecg框架代码移植改造
      ( 改造内容注释：改造完成之后，online在线开发提示资源不存在，通过查看代码得知，修改org.jeecg.modules包名之后，会有org.jeecg.modules.online.cgform包下面的请求找不到，所以增加了两个扫描包@ComponentScan(basePackages = {"org.jeecg.*","com.xxx.*"})。）

使用online在线开发，将生成的代码导入项目中，报错，错误提示：required a single bean, but 2 were found:
下面的报错，一个是生成的接口，它的实现类。

##### 截图&代码：

2020-11-06 20:04:28.974 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter:42 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field service in org.jeecg.common.system.base.controller.JeecgController required a single bean, but 2 were found:
	- movieServiceImpl: defined in file [E:\03-Additional-Repositories\modules-service\target\classes\com\xxx\api\modules\movie\service\impl\MovieServiceImpl.class]
	- IMovieService: defined in file [E:\03-Additional-Repositories\modules-service\target\classes\com\xxx\api\modules\movie\service\IMovieService.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

暂时未能解决，只能先把接口删除，直接使用实现类注册

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己的代码，还需求自己多排查，我们无法判断

**Comment by qzh99** [comment]
是不是mybatis的@MapperScan扫描了service接口，这个注解只需要扫描mapper接口
@MapperScan(basePackages = { "org.jeecg.**.mapper"})
