### ISSUE TITLE
求助贴  Online表单开发和报表配置，功能测试 跳转404

### ISSUE THREAD

**Issue by catlvsuger** [zhangdaiscott/jeecg-boot#1941]
##### 问题描述：
Online表单开发和报表配置，点击功能测试 跳转404，不知道改了哪里，下了最新的前端代码，比对还原，也更新了依赖，新的正常，原来的还是404

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是不是把online的隐藏路由菜单给删掉了，或者取消了授权

**Comment by catlvsuger** [comment]
嗯，对了下菜单发现被删掉了，恢复就好了，谢谢
