### ISSUE TITLE
导入数据后，前台卡死（一直上传中）

### ISSUE THREAD

**Issue by Livon** [zhangdaiscott/jeecg-boot#1943]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/5563469/98425215-53222d80-20cf-11eb-93e7-87e2eea76c27.png)

chrome 控制台：

![image](https://user-images.githubusercontent.com/5563469/98425308-a300f480-20cf-11eb-8d50-8fdbbc832e8b.png)

后台控制台显示已经上传完成，数据也可以在数据库中看到：

![image](https://user-images.githubusercontent.com/5563469/98425251-6fbe6580-20cf-11eb-80f2-1d0908eca354.png)

**Comment by zhangdaiscott** [comment]
多少数据量？

**Comment by Livon** [comment]
只有 96 条数据，但数据库在远程，耗时大约 20 秒

![image](https://user-images.githubusercontent.com/5563469/98469042-52e17980-2218-11eb-962f-a275c059f6c0.png)

**Comment by zhangdaiscott** [comment]
应该是导入时间长，超时了

**Comment by zhangdaiscott** [comment]
@jeecg/antd-online-mini
这里面搜9000 改成90000，把超时时间设置长了

**Comment by Livon** [comment]
多谢！
