### ISSUE TITLE
War部署方案，token超时后，继续操作，浏览器会提示跨域问题

### ISSUE THREAD

**Issue by CenMinghao** [zhangdaiscott/jeecg-boot#1944]
##### 版本号：
2.3

##### 问题描述：
上线发布使用War部署方案，系统可以正常运行。
但是当token超时后，继续操作，浏览器会提示跨域问题，无法正常提示用户重新登录

##### 截图&代码：
浏览器截图：
![微信图片_20201107095701](https://user-images.githubusercontent.com/29631645/98429273-b1a3d780-20e0-11eb-9aec-e40965e67cb5.png)
Tomcat截图：
![微信图片_20201107100116](https://user-images.githubusercontent.com/29631645/98429277-c2ece400-20e0-11eb-99ff-46acc0076b80.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CenMinghao** [comment]
本地使用spring-boot开始后台不会出现此问题。tomcat部署后台会出现此问题

**Comment by 1298191366** [comment]
将src\utils\request.js删掉即可，目的是走vue代理（vue.config.js）
![image](https://user-images.githubusercontent.com/30997828/98676253-500c9300-2396-11eb-9a00-a3afaf73b3ab.png)
![image](https://user-images.githubusercontent.com/30997828/98676325-6b779e00-2396-11eb-8802-63cc5360110d.png)

**Comment by CenMinghao** [comment]
①devServer的开发环境允许跨域吧。我的情况是生产环境，后台使用tomcat进行部署，前端使用nginx进行部署。

**Comment by CenMinghao** [comment]
①1298191366 您的回答指的开发环境允许跨域吧。我的情况是生产环境种，后台使用tomcat进行部署，前端使用nginx进行部署。
②我的情况时，系统在生产环境正常部署后使用时没有出现跨域问题的(即不是一开始就提示存在跨域问题)，只有在登录超时的时候，再次对系统进行操作，就会出现跨域问题。

**Comment by CenMinghao** [comment]
> 将src\utils\request.js删掉即可，目的是走vue代理（vue.config.js）
> ![image](https://user-images.githubusercontent.com/30997828/98676253-500c9300-2396-11eb-9a00-a3afaf73b3ab.png)
> ![image](https://user-images.githubusercontent.com/30997828/98676325-6b779e00-2396-11eb-8802-63cc5360110d.png)

①1298191366 您的回答指的开发环境允许跨域吧。我的情况是生产环境种，后台使用tomcat进行部署，前端使用nginx进行部署。
②我的情况时，系统在生产环境正常部署后使用时没有出现跨域问题的(即不是一开始就提示存在跨域问题)，只有在登录超时的时候，再次对系统进行操作，就会出现跨域问题。

**Comment by CenMinghao** [comment]
③这个问题，在旧版本(v2.2.1)不会出现。

**Comment by 1298191366** [comment]
你好，我是在本地windows下，用的tomcat和nginx进行的部署，一开始也是你所说的错误登录超时就显示跨域的问题，你把target中的localhost改成访问后台地址，可以去尝试一下。

**Comment by CenMinghao** [comment]
> 你好，我是在本地windows下，用的tomcat和nginx进行的部署，一开始也是你所说的错误登录超时就显示跨域的问题，你把target中的localhost改成访问后台地址，可以去尝试一下。

问题解决了，感谢帮忙！

**Comment by OrangeLiWang** [comment]
怎么修改的啊，target里的localhost在哪里

**Comment by xuemw** [comment]
> > 你好，我是在本地windows下，用的tomcat和nginx进行的部署，一开始也是你所说的错误登录超时就显示跨域的问题，你把target中的localhost改成访问后台地址，可以去尝试一下。
> 
> 问题解决了，感谢帮忙！

请问是怎么解决的
