### ISSUE TITLE
数据库同步失败

### ISSUE THREAD

**Issue by Coande** [zhangdaiscott/jeecg-boot#1945]
##### 版本号：

2.3

##### 问题描述：

在线开发，在同步数据库时，表中不存在A字段，却报错提示无法删除A字段。排查发现，在另一个数据库中有同名表，更改另一个数据库的同名表名称后同步成功。

原因猜测：
在同步数据库，查询数据库表的列信息时，没有对数据库进行过滤，查询到了另一个数据库中同名表的列信息。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个问题已经处理了，你更新最新代码就可以了
