### ISSUE TITLE
编码规则的第二个参数如何推送？

### ISSUE THREAD

**Issue by Livon** [zhangdaiscott/jeecg-boot#1946]
##### 版本号：

2.3（发布日期：20200914）

##### 问题描述：

请问，编码规则的第二个参数如何推送？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5563469/98452947-ecfcdf80-218e-11eb-959e-9732c66d28f3.png)

![image](https://user-images.githubusercontent.com/5563469/98452986-57158480-218f-11eb-9736-9aceba04d3ba.png)

![image](https://user-images.githubusercontent.com/5563469/98453137-db1c3c00-2190-11eb-9e27-fcae73fe0e35.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvdandan16** [comment]
编码规则参数设置：
{"prefix":"PMON","aaa":"b33"}
示例：
![image](https://user-images.githubusercontent.com/54099258/98528211-f4b7a380-22b6-11eb-94cc-f98ff0f7ae05.png)
![image](https://user-images.githubusercontent.com/54099258/98528557-6ee82800-22b7-11eb-87e1-16a84b8cbb6e.png)

**Comment by Livon** [comment]
首先，感谢回答，但我问的是第二个参数：formData，而不是第一个参数：params 的多个值。

：）

我的目的不只是想传多个参数，只想弄清楚第二个参数的存在意义。

**Comment by lvdandan16** [comment]
在系统规则编码功能里，不支持传递第二个参数，JAVA代码调用时可传入第二个参数

**Comment by Livon** [comment]
@lvdandan16 多谢！
