### ISSUE TITLE
登陆安全问题

### ISSUE THREAD

**Issue by zhouyilong** [zhangdaiscott/jeecg-boot#195]
目前登陆验证接口中密码是明文传输的，验证码采用的是纯前端验证，是否会考虑验证码从后端生成，存储到redis中再显示到前端，密码传输过程中进行加密处理。

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布

**Comment by zhanjunfeng** [comment]
2.0.2中只是把密码加密了，加密的方法和参数还是能看到的，图形验证码还是在前端，和没有一样
