### ISSUE TITLE
通配符问题

### ISSUE THREAD

**Issue by petma** [zhangdaiscott/jeecg-boot#1952]
##### 版本号：
2.2

##### 问题描述：
在用户列表查包含_的符号的用户，查不出来
后来发现应该是通配符问题
##### 截图&代码：
修改了queryGenerator类中的replaceValue方法
  String val = (value + "").toString().trim();
        if (rule == QueryRuleEnum.LIKE) {
            String temp = val.substring(1, val.length() - 1);
            value = temp.replace("_", "\\_").replace("%", "\\%");

        } else if (rule == QueryRuleEnum.LEFT_LIKE || rule == QueryRuleEnum.NE) {
            String temp = val.substring(1);
            value = temp.replace("_", "\\_").replace("%", "\\%");
        } else if (rule == QueryRuleEnum.RIGHT_LIKE) {
            String temp = val.substring(0, val.length() - 1);
            value = temp.replace("_", "\\_").replace("%", "\\%");
        }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已经修复，下个版本发布
