### ISSUE TITLE
yarn run build  报错

### ISSUE THREAD

**Issue by rose312** [zhangdaiscott/jeecg-boot#1954]
##### 版本号：
2.3
##### 问题描述：

yarn run build  报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5534736/98519816-40188480-22ac-11eb-934b-b7681a69706b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://www.cnblogs.com/xyyt/p/11384818.html
