### ISSUE TITLE
登陆时能否跳转到指定页面

### ISSUE THREAD

**Issue by chongyangwang** [zhangdaiscott/jeecg-boot#1956]
##### 版本号：
v2.2.0

##### 问题描述：
  用户登陆时  能否指定跳转的页面？ 目前默认登入首页   想登录到一个自定义的菜单页

`

  loginSuccess() {

      this.$router.push({ path: '/dashboard/analysis' })

      this.$router.push({ path: 'xxxxxx' })    // 如果替换成这样  登陆时依然会走上面那个路径

      this.$notification.success({

        message: '欢迎',

        description: `${timeFix()}，欢迎回来`

      })

    },

`
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32251099/98620095-94207900-233f-11eb-997a-d58c683fccd7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以，自己改造即可

**Comment by chongyangwang** [comment]
@zhangdaiscott    这是什么狗屁回答呢

**Comment by chongyangwang** [comment]
我觉得这个问题 应该不止一个用户有反馈吧   作为官方态度真好
