### ISSUE TITLE
前端Dict支持查询过滤，但后端的@Dict不支持过滤条件，希望同步支持！

### ISSUE THREAD

**Issue by luoliang222** [zhangdaiscott/jeecg-boot#1957]
##### 版本号：
2.3.0

##### 问题描述：
使用自定义字典表时，前端使用条件过滤，比如：
<j-dict-select-tag ... dictCode="enum_general, enum_text, enum_name, enum_type='TCDZCY'" />

后端的目前不支持这种条件过滤
@Dict(dicCode = "enum_name", dicText = "enum_text", dictTable = "enum_general", filter="enum_type='TCDZCY'")

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
考虑下你的建议

**Comment by luoliang222** [comment]
我仔细思考了一下，这个需求是在 enum_id 不唯一的时候会有用，如果id唯一则现有接口是足够的

**Comment by zhangdaiscott** [comment]
好的
