### ISSUE TITLE
JEditableTable  创建1对多问题

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#196]
问题1:
一对多子表 如果不填子表数据  但是创建的时候自己的创建一列子表数据，如图1  导致问题2

问题2： 子表不需要录入数据
取消子表验证 (图2)  传后空值到后台 导致不能保存 变成空对象(如3) 

主要功能就是在增加一对多的时候 如果不填写子表数据 不影响保存， 
是否可以不显示增加子表 空列在哪里 希望这样(图4)

图1
![image](https://user-images.githubusercontent.com/5210084/59240414-f3ec8f00-8c36-11e9-8a1d-973e1b93580b.png)

图2
![image](https://user-images.githubusercontent.com/5210084/59241092-df10fb00-8c38-11e9-9112-0a4f58a2ddb5.png)

图3
![image](https://user-images.githubusercontent.com/5210084/59241065-bc7ee200-8c38-11e9-85b3-0c57d58168aa.png)

图4
![image](https://user-images.githubusercontent.com/5210084/59241231-6e1e1300-8c39-11e9-95d8-1066e3cfdc49.png)

**Comment by zhangdaiscott** [comment]
你这个需求属于特殊的，自己灵活调整代码即可。

**Comment by shanggushenlong** [comment]
@shaowen 你好，请教下，这个 JEditableTable 这个表格是游代码生成器生成的吗？如果是的话？是哪一个代码模板生成的？？
