### ISSUE TITLE
[错误]使用online在线开发无法新建数据

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#1961]
##### 版本号：
2.3

##### 问题描述：
使用online在线开发功能，配置好表单后进行功能测试
无法新建表单数据，填入数据后点击“确定”后没有反应
前台和后台都没有错误。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8335270/98686221-42113f00-23a3-11eb-809c-2032d2e7c32f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有什么特殊的操作？别人用的都没问题

**Comment by yanchenchen** [comment]
是，其他的新建的online表单用起来也没有问题。
没有特殊操作，但是有改过数据库的表名。
重新新建了一模一样的，也可以使用。
