### ISSUE TITLE
图片或者文件上传超过1m就上传失败

### ISSUE THREAD

**Issue by speshowzhu** [zhangdaiscott/jeecg-boot#1963]
##### 版本号：
线上官网演示

##### 问题描述：
图片上传或者文件上传超过1m就上传失败，没有超过就能正常上传和预览

##### 截图&代码：

![image](https://user-images.githubusercontent.com/46705291/98760173-af59ba00-240d-11eb-8759-5d2271f16ebc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不影响，演示环境nginx做了大文件限制
