### ISSUE TITLE
[ERROR] Failed to execute goal on project jeecg-system-local-api

### ISSUE THREAD

**Issue by Livon** [zhangdaiscott/jeecg-boot#1969]
##### 版本号：
2.3

##### 问题描述：

在 Maven 的 install 过程中，先 install common , 顺利完成，在 install jeecg-system-local-api 时，发生如下错误：

[ERROR] Failed to execute goal on project jeecg-system-local-api: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-system-local-api:jar:2.3.0: Failed to collect dependencies at org.jeecgframework.boot:jeecg-boot-base-common:jar:2.3.0: Failed to read artifact descriptor for org.jeecgframework.boot:jeecg-boot-base-common:jar:2.3.0: Failure to find org.jeecgframework.boot:jeecg-boot-parent:pom:2.3.0 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced -> [Help 1]

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5563469/98773487-010d3f00-2424-11eb-841e-41ba7a4a1c6f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/98780527-dd4ff600-242f-11eb-8419-303a12a1375f.png)
