### ISSUE TITLE
postgresql 类型转换 问题

### ISSUE THREAD

**Issue by liusk98** [zhangdaiscott/jeecg-boot#1971]
##### 截图&代码：

create cast (bool as int2) with function bool_to_int(boolean) as implicit
> ERROR:  must be owner of type boolean or type smallint

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
我们都是这么用的，没问题

**Comment by liusk98** [comment]
已经解决了，是因为 Implicit 未开启导致的

**Comment by hlzfr** [comment]
> 已经解决了，是因为 Implicit 未开启导致的

麻烦问一下，怎么开启Implicit
