### ISSUE TITLE
online 表单新版本授权只能在online表单页面 旧版本菜单里授权的方式不支持了吗

### ISSUE THREAD

**Issue by kevin-lr** [zhangdaiscott/jeecg-boot#1973]
##### 问题描述：online 表单新版本授权只能在online表单页面点击”角色授权“进行授权， 旧版本菜单里授权的方式不支持了吗？
用户新建角色需要授权online部分只能这样单独授权了吗

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
旧版也支持权限，需要人工配置
http://doc.jeecg.com/1297211

**Comment by kevin-lr** [comment]
我现在升级到新版了 但是想用旧版人工配置，需要降级吗

**Comment by zhangdaiscott** [comment]
是的，旧版模式就不能用了
