### ISSUE TITLE
【bug】一级菜单切换时会有短暂的页面重叠

### ISSUE THREAD

**Issue by Seizedays233** [zhangdaiscott/jeecg-boot#1974]
##### 版本号：
 v2.3 开源版

##### 问题描述：
项目新增页面设置的是一级菜单 在和其他页面切换的时候 两个页面会有短暂的重叠 新打开的页面会从原页面的下方出现 然后卡顿一会再将原页面覆盖

##### 截图&代码：

![截图](https://user-images.githubusercontent.com/54106885/98887658-5eab9500-24d1-11eb-8f62-1ee150ed2f32.png)

**Comment by Seizedays233** [comment]
- [ ] 

- [ ]

**Comment by Seizedays233** [comment]
官方的能不能来解决一下呀？ 屏幕大一点的就会有这种问题 笔记本的屏幕倒是不会出现这种情况

**Comment by zhangdaiscott** [comment]
您好，请用演示系统试试，提供重现步骤，我们这边无法重现

**Comment by Fliner** [comment]
@zhangdaiscott 我也遇到这个问题，本地开发才会有，演示系统没法设置。
重现步骤是：

1. 用在线开发随意设计一个表单
2. 生成代码
3. 将前端代码粘贴至前端工程src/view/test文件夹下
4. 配置菜单，设置刚刚生成的页面为一级菜单
5. 来回切换这个一级菜单和其他表单就会出现重叠问题

**Comment by zhangdaiscott** [comment]
试试最新版，看看是否已经解决

**Comment by Fliner** [comment]
@zhangdaiscott 已经试出问题了，您按照以下方式简单操作就可以在演示系统复现

1. 将现有的用户管理设置成一级目录（其实任意的表单都行）
2. 在线开发->Online表单开发->表名为`csmc_tbl_settle_rslt`的表单->点击功能测试（其实任意表单，只要保证这个页面没有记录，为的是不填充满页面）
3. 然后在这两个页面切换就可以看出用户管理页面顶着这个功能测试表出现的，重新重叠
