### ISSUE TITLE
微服务下提示登陆已过期，点重新登录没有跳转到登陆页面。

### ISSUE THREAD

**Issue by zjwang1234** [zhangdaiscott/jeecg-boot#1975]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/29996416/98903540-c9b99380-24f2-11eb-92c8-0570b796e17f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
我这边测试是可以的，可以跳转到登录页面
