### ISSUE TITLE
同步数据库，对于一些关键字的表名 实际并没有创建成功

### ISSUE THREAD

**Issue by bear5share** [zhangdaiscott/jeecg-boot#1977]
[#####](url) 版本号：

##### 问题描述：
同步数据库，对于一些关键字的表名 实际并没有创建成功

##### 截图&代码：

![企业微信截图_16051646772390](https://user-images.githubusercontent.com/13477644/98906766-a98cd300-24f8-11eb-8832-195085fdbe5d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CharlieJ0hn** [comment]
order 是 mysql 关键字，最好不要用。其他 mysql 的关键字也不要用。比如 class，要写成 clazz

**Comment by zhangdaiscott** [comment]
分配

**Comment by zhangdaiscott** [comment]
已经处理，请更新代码

**Comment by bear5share** [comment]
强。
