### ISSUE TITLE
（咨询）项目改名后打包失败问题

### ISSUE THREAD

**Issue by muYouGou** [zhangdaiscott/jeecg-boot#198]
我把jeecg-boot项目名字改为 sayNo。然后打包时候就报错了。信息如下，启动是没有问题的
[ERROR] Failed to execute goal on project sayNo-module-system: Could not resolve dependencies for project org.jeecgframework.boot:sayNo-module-system:jar:2.0.1: 
The following artifacts could not be resolved: org.jeecgframework.boot:sayNo-base-common:jar:2.0.1, 
org.jeecgframework.boot:sayNo-module-mes:jar:2.0.1: Failure to find org.jeecgframework.boot:sayNo-base-common:jar:2.0.1 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyun

**Comment by zhangdaiscott** [comment]
sayNo-base-common 这个项目install

低级问题不要再这里提
