### ISSUE TITLE
AutoPOI excel根据模板导出数据，图片导不出来

### ISSUE THREAD

**Issue by liangsheng123** [zhangdaiscott/jeecg-boot#1981]
##### 版本号：
jeecg-boot 2.3

##### 问题描述：
用AutoPOI excel根据模板导出表格，能获取到图片路径，但是图片导不出来

##### 截图&代码：
导出图片代码截图：
![微信图片_20201113100446](https://user-images.githubusercontent.com/45448131/99019746-fa9fd400-2597-11eb-9ee5-f5b45c4443a5.png)

导出excel表格截图：
![微信图片_20201113101116](https://user-images.githubusercontent.com/45448131/99020017-a0ebd980-2598-11eb-9170-b8d90d74fffc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用法不对吧
http://doc.autopoi.jeecg.com/1623954

**Comment by liangsheng123** [comment]
首先谢谢你的回复，你发给我的文档我看了。这个ImageEntity是easyPoi的，咱们现在用的框架没有封装这个，只能



现在的框架只能用WordImageEntity，导出来的就是不加载图片


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 下午2:00
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"凉生"<1048169002@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] AutoPOI excel根据模板导出数据，图片导不出来 (#1981)





 
用法不对吧
 http://doc.autopoi.jeecg.com/1623954

**Comment by liangsheng123** [comment]
首先谢谢你的回复，你发给我的文档我看了。这个ImageEntity是easyPoi的，咱们现在用的框架没有封装这个，只能



现在的框架只能用WordImageEntity，导不出图片


用WordImageEntity导出，excel 显示如图所示：






麻烦你们自己试下，你发给我的文档我之前早已试过，但凡能解决我也不会提问题




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 下午2:00
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"凉生"<1048169002@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] AutoPOI excel根据模板导出数据，图片导不出来 (#1981)





 
用法不对吧
 http://doc.autopoi.jeecg.com/1623954

**Comment by hk19950707** [comment]
我目前也是存在楼主说的这种问题，ImageEntity根本就没有可以引入的包， http://doc.autopoi.jeecg.com/1623954文档有问题！！！！！1
