### ISSUE TITLE
关于online在线表单开发的一点疑问

### ISSUE THREAD

**Issue by bear5share** [zhangdaiscott/jeecg-boot#1982]
##### 版本号：
jeecg-boot 2.3 版本

##### 问题描述：
建议表单元素的控制能不能 根据操作来控制表单的元素可见、可编辑状态；因为往往很多需求在修改的时候要控制一些元素不能再进行修改。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以写js增强
