### ISSUE TITLE
侧边菜单有偶发bug，使正常页面被遮挡部分

### ISSUE THREAD

**Issue by Nibbbbbbbb** [zhangdaiscott/jeecg-boot#1984]
##### 版本号：

重构前的2.2.1  、重构后的2.3

##### 问题描述：

这个问题是偶发的，但是频率挺高的，开发时一个月会遇到几次，强制刷新页面无用，要清缓存或者把浏览器的宽度缩小再放大，它才适配回来   

相同issue：#1445

##### 截图&代码：

![image](https://user-images.githubusercontent.com/21167262/99136023-dc041080-265d-11eb-80dd-fe28850e22ad.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
您好，请用演示系统试试，提供重现步骤，我们这边无法重现
