### ISSUE TITLE
jeecgboot-mysql-5.7.sql被别人提交导致不完整，管理员没注意吗？

### ISSUE THREAD

**Issue by cmlanche** [zhangdaiscott/jeecg-boot#1985]
##### 版本号：2.3.0  
在master分支

##### 问题描述：
某用户修改了mysql的sql文件，这个文件有严重错误，根本无法生成数据库，被社区管理员合并到master分支了，管理员重视一下吧，怎么把一个无意义的merge合到主分支了？

##### 截图&代码：
<img width="1278" alt="error" src="https://user-images.githubusercontent.com/5886757/99144360-1ababa80-26a0-11eb-87cd-bc0abe14d216.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by cmlanche** [comment]
里面不止有这一个sql错误，速度修复了吧

**Comment by zhangdaiscott** [comment]
已经还原

**Comment by CharlieJ0hn** [comment]
@cmlanche 首先，请注意您的言辞，这不是一个毫无意义的 pr，程序员说话要严谨一点，您没有阅读我提交的原因，没有验证我提交的代码就说这个毫无意义，你这样不负责任就提 issue 的行为非常影响社区开发者的积极性。我不是第一个发现这个问题，社区有人提出了多次，但是我第一个提出 pr 修复这个问题的人，并且经过多次测试，确定没有问题才提交到主分支的。
这次的错误出在 merge 中发生冲突的错误。
还有，我再解释一遍，这个 pr 修复了 qrtz 表名是大写，但是 linux 等数据库默认区分大小写的问题，jeecg 访问小写表名会在windows以外的系统中报错。

@zhangdaiscott 
问题出在我提出 pr 以后数据库经过了其他提交以后，merge 中发生的冲突没有被解决。
我已经提交了另一个 pr 来解决这个问题。但是管理员没有合并进去。现在如果合并的话要注意是不是又发生了冲突，得解决冲突。

**Comment by CharlieJ0hn** [comment]
@zhangdaiscott @cmlanche 当然我也承认错误，我 merge 主分支代码的时候没注意，对大家造成了影响。我给各位道歉。

**Comment by CharlieJ0hn** [comment]
https://github.com/zhangdaiscott/jeecg-boot/pull/1979#issue-519936732

这是我五天前提交的修复错误的 pr，没有被合并，不然你应该不会遇到昨天这个错误的。
