### ISSUE TITLE
excel主子表导入可以在一个sheet中吗

### ISSUE THREAD

**Issue by gelinagg** [zhangdaiscott/jeecg-boot#1987]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by gelinagg** [comment]
主子表拉平方式导入，通过主表的code，例如，用户表有子表，子表信息为用户的家庭成员，excel导入方式

>
例如：
主表---编码 |主表--- 姓名 | 主表---手机号 | 子表---家庭成员编码 | 子表---家庭成员姓名
001 | 小米 | 13813812122 | 00101 | 小米爸爸
001 | 小米 | 13813812122 | 00102 | 小米媽媽

**Comment by zhangdaiscott** [comment]
现在的主子表导入不就在一个excel里面吗，请参考jeecgboot的结构
