### ISSUE TITLE
使用js增强动态计算列表某一列的值

### ISSUE THREAD

**Issue by But-Always** [zhangdaiscott/jeecg-boot#1988]
##### 版本号：
2.2.3

##### 问题描述：
想问一下
使用js增强可以在列表页实现某一个字段的值为其他字段计算生成的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23469175/99232598-166fd800-282d-11eb-9d52-3c030243cc84.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
列表目前不支持
