### ISSUE TITLE
在线开发能否生成继承关系，如何生成？

### ISSUE THREAD

**Issue by pear-li1015** [zhangdaiscott/jeecg-boot#1992]
##### 问题描述：
假设数据库中有以下2张表：  
man: id, name, gender  人类表: id,姓名,性别  
teacher: man_id, age  教师表：人类表中对应的id, 年龄

前端添加教师页面  
name: 张三  
age: 18  
gender: 男  

前端教师列表页面  
|  name   | age  |  gender  |
|  ----  | ----  |  ----  |  
|张三|18|男|  
|李四|18|男|  

求告知，这种需求如何实现？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
