### ISSUE TITLE
JEditableTable,validateRules配置规则unique的问题

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#1993]
##### 版本号：
2.2.1

##### 问题描述：
具体问题见下图中的描述，想问下有没有办法优化一下。关于JEditableTable示例五里面的校验重复的方法也都试过了，问题和图片中描述是一样的。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26954826/99508100-2f0ff780-29bf-11eb-9d27-2c55d8937197.png)

![image](https://user-images.githubusercontent.com/26954826/99365568-6f557400-28f2-11eb-8dd1-ffd4c3157e76.png)

![image](https://user-images.githubusercontent.com/26954826/99365716-9f9d1280-28f2-11eb-81f6-7269f441d9c7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
分配

**Comment by tygithub1** [comment]
这个真没问题
