### ISSUE TITLE
选择部门弹出框超出屏幕

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#1995]
##### 问题描述：

部门选择器，部门条数多时，弹出框没有控制大小，直接超出一屏大小，
希望能将滚动条调整到modal里边，控制弹出框大小不超出屏幕，只有中间数据进行滑动

用户管理->编辑/查看->部门选择

##### 截图&代码：

![F33C9E23-2B86-4c72-9B1B-97DF1BEF9C2F](https://user-images.githubusercontent.com/31750150/99369112-fc9ac780-28f6-11eb-93ba-f2587cb995b8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
分配

**Comment by 1298191366** [comment]
已修改，待新版本发布
