### ISSUE TITLE
请问如何进行单元测试？

### ISSUE THREAD

**Issue by SmileCocc** [zhangdaiscott/jeecg-boot#1996]
##### 版本号：

1
##### 问题描述：

采用junit进行单元测试，结果总是找不到注入的类，各种错误
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考这个配置

/**
 * 表单设计器 API 接口单元测试
 */
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@SuppressWarnings({"FieldCanBeLocal", "SpringJavaAutowiredMembersInspection"})
public class DesformApiTest {
