### ISSUE TITLE
配置了个新的用户（分配了跟管理员一样的角色），使用sql增强时提示“没有权限，请联系管理员授权”

### ISSUE THREAD

**Issue by chenyurou** [zhangdaiscott/jeecg-boot#1998]
##### 版本号：

2020-11-17号下载的master代码。

##### 问题描述：

新添加了个超级管理员，授权了跟默认管理员一样的角色，却不可以使用sql增强功能。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23472237/99478314-26073200-298f-11eb-938a-8025f9e3eea6.png)
新添加的用户是“超级管理员”
![image](https://user-images.githubusercontent.com/23472237/99478347-30293080-298f-11eb-95d8-234e7eec7c2f.png)
超级管理员（新添加的用户）详情：
![image](https://user-images.githubusercontent.com/23472237/99478383-433c0080-298f-11eb-82e9-04a2cf1d236a.png)
管理员详情：
![image](https://user-images.githubusercontent.com/23472237/99478415-50f18600-298f-11eb-8763-c1174eb754a4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块限制了，只运行admin用户操作，因为这块的在线开发有安全风险

**Comment by chenyurou** [comment]
手动改数据库中admin的名称改为super_admin，是否会出现问题？

**Comment by zhangdaiscott** [comment]
会

**Comment by chenyurou** [comment]
请问是会出现什么问题？现在已经把名称和密码和盐改掉，已经能正常登陆上来，是会有其他什么隐藏问题呢？

“手动改数据库中admin的名称改为super_admin（界面上无法修改用户账号），是否会出现问题？”
