### ISSUE TITLE
登录时出现请求用户信息失败，请重试

### ISSUE THREAD

**Issue by PLAhui** [zhangdaiscott/jeecg-boot#2]
![image](https://user-images.githubusercontent.com/35413994/53390535-6ca04600-39ce-11e9-983c-15986deeb1db.png)
![image](https://user-images.githubusercontent.com/35413994/53390560-83469d00-39ce-11e9-82b4-24483f069398.png)

说明：
1.重启后台程序及redis服务器未能解决
2.前端程序及后台程序 无任何报错信息

**Comment by zhangdaiscott** [comment]
提了一版本代码，看看解决没
