### ISSUE TITLE
打开的选项卡，属于外部链接的iframe

### ISSUE THREAD

**Issue by dg81381749** [zhangdaiscott/jeecg-boot#200]
打开的选项卡，属于外部链接的iframe，怎么保证tabs切换时候，iframe页面内容不刷新呢；比如打开的是百度页面，并输入搜索内容了，切换到其他tabs页面，然后再切换回来，页面还是保持在搜索的具体内容，该如何实现

**Comment by zhangdaiscott** [comment]
路由缓存

**Comment by dg81381749** [comment]
默认的就已经存在路由缓存了吧，你们开源的这个里面，iframe打开的百度，搜索了切换也是重新加载的，我看你们后台代码里面 已经都设置了meta.put("keepAlive", "true");的，但是对iframe不起效果？

**Comment by zhangdaiscott** [comment]
前台没设置，需要手工设置，需要的话

**Comment by dg81381749** [comment]
这个我理解的是如果是项目内的路由页面设置router的meta的keepAlive属性就可以保持缓存不需要重新加载，但是如果需要对iframe保持不重刷新，需要怎么加呢？因为每次切换tabs时都是打开IframePageView.vue组件，组件里面是iframe标签，每次都会给iframe设置src属性，就会刷新？然后控制不重新刷新呢？好像keepAlive属性对打开的iframe不起作用？？？
