### ISSUE TITLE
在线代码生成为空

### ISSUE THREAD

**Issue by onlyll** [zhangdaiscott/jeecg-boot#2002]
##### 版本号：
2.3

##### 问题描述：
在线代码生成时，提示成功，但是没有生成任何代码，下载也是空文件

##### 截图&代码：
![bug](https://user-images.githubusercontent.com/24950004/99653259-c3e42500-2a93-11eb-95b6-7356663421ba.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1684391
