### ISSUE TITLE
谷歌浏览器，JEditableTable输入校验提示框位置偏移

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2005]
##### 版本号：
2.2.1

##### 问题描述：

谷歌浏览器，JEditableTable输入框校验提示框位置偏移（同时用了长度和格式校验的时候）
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26954826/99771618-64921d80-2b44-11eb-8399-9a19c3c0fbf2.png)
![image](https://user-images.githubusercontent.com/26954826/99771674-7673c080-2b44-11eb-82d4-551097d16f46.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
分配

**Comment by zhangdaiscott** [comment]
已经解决，请更新最新代码
