### ISSUE TITLE
登录界面的滚动条如何去除

### ISSUE THREAD

**Issue by keepstraight** [zhangdaiscott/jeecg-boot#2008]
##### 截图&代码：
![QQ图片20201121085102](https://user-images.githubusercontent.com/33247602/99862932-bb483780-2bd6-11eb-8d1d-fba42a21d6f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己改造的登录页面请自己研究修改
