### ISSUE TITLE
online表单开发中，行按钮多了“权限控制”，“角色授权”这两个选项

### ISSUE THREAD

**Issue by handsomeFatty** [zhangdaiscott/jeecg-boot#2009]
##### 问题描述：
online表单开发中，行按钮多了“权限控制”，“角色授权”这两个选项，请问是否是我配置问题还是其他

##### 截图&代码：

![68](https://user-images.githubusercontent.com/54500818/99866811-30276b80-2bef-11eb-81bc-2b59ab3a4a40.png)
![69](https://user-images.githubusercontent.com/54500818/99866814-34ec1f80-2bef-11eb-87ff-042253aab924.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是2.3的新功能，简化online权限配置的
