### ISSUE TITLE
前端项目中router的meta的keepAlive对 iframe页签不起作用？

### ISSUE THREAD

**Issue by dg81381749** [zhangdaiscott/jeecg-boot#201]
这个我理解的是如果是项目内的路由页面设置router的meta的keepAlive属性就可以保持缓存不需要重新加载，但是如果需要对iframe保持不重刷新，需要怎么加呢？因为每次切换tabs时都是打开IframePageView.vue组件，组件里面是iframe标签，每次都会给iframe设置src属性，就会刷新？然后控制不重新刷新呢？好像keepAlive属性对打开的iframe不起作用？？？

**Comment by zhangdaiscott** [comment]
这个你得自己研究下了

**Comment by dg81381749** [comment]
我看你们这里面嵌入了外部系统的iframe（百度），tabs标签页切换的时候，打开的百度页面搜索的内容会被重新刷新到百度首页，想知道你们有这方面的解决方案吗？
