### ISSUE TITLE
主键id加了IdType=AUTO，但是插入数据后还是会自动生成一个很长的主键

### ISSUE THREAD

**Issue by shadow--walker** [zhangdaiscott/jeecg-boot#2010]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/4071550/99867491-efcaec00-2bf4-11eb-975d-fad7c03dfee1.png)
![image](https://user-images.githubusercontent.com/4071550/99867502-0b35f700-2bf5-11eb-9666-ad23778812ce.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
auto的话默认走的是配置文件的注解策略
![image](https://user-images.githubusercontent.com/3162115/99899622-b45c1a80-2ce5-11eb-8592-de9d82ab486a.png)

**Comment by shadow--walker** [comment]
哦 这样啊，谢谢了。 我理解注解配置的优先级是不是应该更高呢，注解没配的话才读默认的配置文件配置。

**Comment by PietyXiao** [comment]
> 哦 这样啊，谢谢了。 我理解注解配置的优先级是不是应该更高呢，注解没配的话才读默认的配置文件配置。
请教一下，关于使用数据库的自增ID，这个应该怎么去解决？

**Comment by shadow--walker** [comment]
配置成AUTO就行啦
