### ISSUE TITLE
使用war方式部署的正式环境，调用delete请求，后台无响应

### ISSUE THREAD

**Issue by CenMinghao** [zhangdaiscott/jeecg-boot#2011]
##### 版本号：
2.3

##### 问题描述：
使用war方式部署的正式环境，调用delete请求，后台无响应
其他请求，例如post，get，put有响应
后台接口是通过nginx来转发的，请问是不是nginx的限制？

##### 截图&代码：
delete请求无响应截图
![image](https://user-images.githubusercontent.com/29631645/99874077-bd82b400-2c1f-11eb-93b7-c5210bed271c.png)
post请求有响应截图
![image](https://user-images.githubusercontent.com/29631645/99874090-e1de9080-2c1f-11eb-8ab9-95714d27f8be.png)
nginx转发后台接口截图
![image](https://user-images.githubusercontent.com/29631645/99874158-70eba880-2c20-11eb-971e-a67fb1a757b9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
跟nginx没关系，看看是不是你用法不对

**Comment by Caisen1988** [comment]
@CenMinghao 兄弟问题你解决了吗

**Comment by CenMinghao** [comment]
> @CenMinghao 兄弟问题你解决了吗

解决了，原因是网络那边禁止了delete请求

**Comment by Caisen1988** [comment]
谢谢您，我这边也是被网络禁用了，那您的项目是请他们开通delete还是全部转为post呢？
