### ISSUE TITLE
图片execl导出

### ISSUE THREAD

**Issue by cmxpanda** [zhangdaiscott/jeecg-boot#2015]
##### 版本号：
Jeecg  Boot Version: 2.2.1
Spring Boot Version: 2.1.3.RELEASE (v2.1.3.RELEASE)

##### 问题描述：
使用而execl导出图片会添加红色背景

##### 截图&代码：
![99947432-f1421300-2db2-11eb-9d59-8ee8e61479d8](https://user-images.githubusercontent.com/21009035/99948026-c60bf380-2db3-11eb-945d-8187c3596d18.png)
![99947559-20f11b00-2db3-11eb-9107-93ad26a588f5](https://user-images.githubusercontent.com/21009035/99948030-c73d2080-2db3-11eb-892b-96951087b2c2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by cmxpanda** [comment]
图片格式问题，对jpg或jpeg格式的图片支持不行，修改png格式不会出现问题

**Comment by JDshi** [comment]
@cmxpanda 你是如何导出多图的，我一个字段里存了好几张图片，但只导出了一张
