### ISSUE TITLE
首次加载太慢了

### ISSUE THREAD

**Issue by zhanghaifei1997** [zhangdaiscott/jeecg-boot#2016]
##### 版本号：
Jeecg Boot Version: 2.2.1
Spring Boot Version: 2.1.3.RELEASE (v2.1.3.RELEASE)

##### 截图&代码：
暂无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
53.前端项目编译大，正式部署访问慢解决方法
解决方案： nginx 开启压缩，提高首页访问效率
https://github.com/zhangdaiscott/jeecg-boot/issues/88
