### ISSUE TITLE
从2.2升级到2.3以后，部分之前老页面的样式缺失，请问是否有除“重新生成页面”以外的方法

### ISSUE THREAD

**Issue by handsomeFatty** [zhangdaiscott/jeecg-boot#2018]
##### 问题描述：
前端从2.2升级到2.3以后，部分之前老页面的样式缺失，页面太多，请问是否有除“重新生成页面”以外的方法

##### 截图&代码：
![gg](https://user-images.githubusercontent.com/54500818/100036443-2abe6100-2e3b-11eb-9835-1ddc3450c23d.png)
![hh](https://user-images.githubusercontent.com/54500818/100036460-3447c900-2e3b-11eb-8aa7-d149f526399f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪你看下新老代码编写有什么区别，我们自己升级不存在这个问题
