### ISSUE TITLE
online表单设置中，设置“两列”，但是生成vue页面后，都是只生成一列

### ISSUE THREAD

**Issue by handsomeFatty** [zhangdaiscott/jeecg-boot#2019]
##### 问题描述：
online表单设置中，设置“两列”，但是生成vue页面后，都是只生成一列

##### 截图&代码：
![gg](https://user-images.githubusercontent.com/54500818/100038698-21cf8e80-2e3f-11eb-8772-373949dede26.png)

![hh](https://user-images.githubusercontent.com/54500818/100038353-cdc4aa00-2e3e-11eb-9b8e-0b25d43faa7d.png)

![dd](https://user-images.githubusercontent.com/54500818/100038362-d1f0c780-2e3e-11eb-954f-3fbbe330b2e2.png)
![kk](https://user-images.githubusercontent.com/54500818/100038370-d4532180-2e3e-11eb-865c-e33e32072ed8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本支持
