### ISSUE TITLE
我的部门-人员录入有bug

### ISSUE THREAD

**Issue by dingzhongyu2019** [zhangdaiscott/jeecg-boot#202]
在我的部门里面添加人员时，角色分配和部门分配录不了，只能在修改时添加

**Comment by zhangdaiscott** [comment]
部门可以添加，角色有问题；
感谢

**Comment by dingzhongyu2019** [comment]
![UM$ZG67S Q7}E~3Z3L0G%Y7](https://user-images.githubusercontent.com/51330069/59397162-2ffe2c00-8dbe-11e9-9af5-114b282f109d.png)
在下级部门添加，部门分配就会保存成这个部门的上级部门，您这边看看

**Comment by dingzhongyu2019** [comment]
添加人员后，页面必须要刷新一下，才能进行修改部门的操作

**Comment by didoupeanut** [comment]
添加人员时，添加部门时，选择了“卓尔互动公司”，添加完人员，点击编辑后，显示结果变成了这个公司的研发部

**Comment by zhangdaiscott** [comment]
下个版本发布
