### ISSUE TITLE
请问一下，online表单中的 js增强，java增强，自定义按钮之类的功能，如果生成代码，是不是就全部失效了

### ISSUE THREAD

**Issue by handsomeFatty** [zhangdaiscott/jeecg-boot#2021]
##### 问题描述：
请问一下，online表单中的 js增强，java增强，自定义按钮之类的功能，如果生成前端页面代码，是不是生成的页面中，这些共嗯那个全部失效了

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
js增强，java增强，自定义按钮 目前不支持生成
