### ISSUE TITLE
为什么本地部署后 缺失很多功能比如online中的额图表配置 组合图表配置

### ISSUE THREAD

**Issue by java-baby** [zhangdaiscott/jeecg-boot#2023]
##### 版本号：
2.3.0

##### 问题描述：
为什么本地部署后 缺失很多功能比如online中的额图表配置 组合图表配置

##### 截图&代码：

![image](https://user-images.githubusercontent.com/74033481/100072851-ba820080-2e77-11eb-8546-9365e333d431.png)
上图是在线开发的全部功能。
下图是我本地部署的项目 功能很少：

![image](https://user-images.githubusercontent.com/74033481/100073000-e2716400-2e77-11eb-8126-3e0da2f83d03.png)
并且菜单中很多功能也缺失了如下图

![image](https://user-images.githubusercontent.com/74033481/100073107-0af95e00-2e78-11eb-9cda-9d81d645e68e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zlwaiwjj** [comment]
被打成@jeecg/antd-online-mini，且不开源

**Comment by zhangdaiscott** [comment]
不开源功能
