### ISSUE TITLE
表单开发的时候，数据源pgsql中的数据表 测试查询报错

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2027]
##### 版本号：
2.3

##### 问题描述：
表单开发的时候，数据源pgsql中的数据表 测试查询报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32193518/100175030-9c181580-2f08-11eb-9ef1-caeb3774a856.png)

![image](https://user-images.githubusercontent.com/32193518/100175116-c073f200-2f08-11eb-80d6-4e0926c32fc1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by iwen-git** [comment]
麻烦 大佬看下是不是pgsql兼容问题

**Comment by zhangdaiscott** [comment]
这个表存在吗，是不是没同步生成
