### ISSUE TITLE
数据权限规则  同一个菜单配置多个规则怎么使用OR链接呢  目前是AND

### ISSUE THREAD

**Issue by sleeeeeeepa** [zhangdaiscott/jeecg-boot#2029]
##### 版本号：
2.3

##### 问题描述：
数据权限规则  同一个菜单配置多个规则怎么使用OR链接呢  目前是AND

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sleeeeeeepa** [comment]
![CSF}%0D_64GEXBE MHA79G2](https://user-images.githubusercontent.com/26105843/100190714-d34aee80-2f29-11eb-9b94-3047eaec7fa9.png)

**Comment by sleeeeeeepa** [comment]
如果单用户多角色配置不同的数据权限, 依然是and  这好像有逻辑问题,

**Comment by zhangdaiscott** [comment]
目前是这样设计的

**Comment by tqrao** [comment]
> 如果单用户多角色配置不同的数据权限, 依然是and 这好像有逻辑问题,

可以按角色分类，将每个角色的条件and连接后拼成自定义sql，再把这些sql按照自定义的方式用or连接

**Comment by ChengPengYang** [comment]
@tqrao 可以详细讲一下吗，我也遇到了这个问题，同一用户多角色，一个角色的多个数据权限用and拼接没问题，不同角色的数据权限应该使用or拼接的

**Comment by tqrao** [comment]
看了下多年前的代码，好陌生😂😂😂 有兴趣的话可以加下微信讨论下， 17730011692发自我的 iPhone在 2025年4月26日，09:20，Yy ***@***.***> 写道：﻿
ChengPengYang left a comment (jeecgboot/JeecgBoot#2029)
@tqrao 可以详细讲一下吗，我也遇到了这个问题，同一用户多角色，一个角色的多个数据权限用and拼接没问题，不同角色的数据权限应该使用or拼接的
