### ISSUE TITLE
必看常见问题

### ISSUE THREAD

**Issue by zhangdaiscott** [zhangdaiscott/jeecg-boot#203]
1、必看常见问题（这里汇总了从环境搭建、入门、开发会遇到的各种问题）
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
2、在线文档
http://jeecg-boot.mydoc.io
3. 入门教程&视频
http://jeecg-boot.mydoc.io/?t=345660
4. 反馈问题请发issue
https://github.com/zhangdaiscott/jeecg-boot/issues/new

**Comment by Shaoccc** [comment]
online 表单 生成的数据表主键只有id  编辑后也无效果

**Comment by java-baby** [comment]
你好 我为什么本地下载部署了 online图表配置 和很多功能都没有呢？ 
![image](https://user-images.githubusercontent.com/74033481/100069661-f9ae5280-2e73-11eb-886a-b57f4f97819a.png)
上面这张是官网展示用的 功能齐全； 下面这张是我自己部署的 为什么不存在呢？好多功能都没有呢？
![image](https://user-images.githubusercontent.com/74033481/100069868-324e2c00-2e74-11eb-8a61-2930cc5410ac.png)

**Comment by colddark123** [comment]
您好，为什么我使用js增强后提示that未定义
![image](https://user-images.githubusercontent.com/39893172/104612106-ce502300-56c0-11eb-8f19-3ef03b34e91c.png)
