### ISSUE TITLE
列表自定义项,弹出的popover会随columns的个数及title长度而不合理地变宽

### ISSUE THREAD

**Issue by trdmm** [zhangdaiscott/jeecg-boot#2030]
##### 问题描述：
表单上面的列表自定义项,弹出的popover太宽.如下图

1. 列表项越多,越宽
2. 列表项title越长,越宽

比如:
`JeecgDemoList`中的`defColumns`宽度感觉刚刚好,
但是如果再加4个,每个的title变成4个字,弹出来的popover会非常宽.

![popover太宽.png](https://i.loli.net/2020/11/25/VnQMqKw27xX9rye.png)

**Comment by 1298191366** [comment]
已修改，待新版本发布

**Comment by zhangdaiscott** [comment]
你指的是online功能测试还是那个功能点？

**Comment by trdmm** [comment]
> 你指的是online功能测试还是那个功能点？

**代码生成** 生成的,再发布到菜单.

列表自定义项是按文档写的添加的

**Comment by zhangdaiscott** [comment]
参考demo吧，demo我们已经设置固定宽度了
