### ISSUE TITLE
集成jimu-report失败: 授权菜单时没有报表设计

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2033]
##### 版本号：
2.3.0

##### 问题描述：
按照文档的要求集成了jimu-report，在给角色授权菜单的时候，弹出的菜单中没有“报表设计-->报表设计器”菜单，是不是由于我的jeecg-boot版本是开源免费版的? 配置菜单的时候，积木报表的菜单路径、前端组件、是否路由菜单这些该怎么填、怎么写？
我的环境是微服务版的，访问localhost:9999/design/report/list这个地址时，页面是可以出来的，但是点击打印设计、数据报表、图形报表这些菜单时，提示token无效

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4694834
