### ISSUE TITLE
图表设计问题，查询数据时所用数据源错误

### ISSUE THREAD

**Issue by MCSophie** [zhangdaiscott/jeecg-boot#2035]
##### 截图&代码：
![企业微信截图_20201126135834](https://user-images.githubusercontent.com/26766152/100315064-f55c7380-2ff2-11eb-8d24-367965a79d8d.png)
![企业微信截图_20201126135856](https://user-images.githubusercontent.com/26766152/100315069-f8effa80-2ff2-11eb-9b79-f5a18503988b.png)
![企业微信截图_20201126141950](https://user-images.githubusercontent.com/26766152/100315082-fdb4ae80-2ff2-11eb-9181-046f1894c38c.png)
![企业微信截图_1606371632842](https://user-images.githubusercontent.com/26766152/100315089-00170880-2ff3-11eb-886d-dcb03bd16229.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
积木报表依赖升级到 1.0.2-beta

**Comment by MCSophie** [comment]
> 积木报表依赖升级到 1.0.2-beta

我看了，确实是1.0.2-beta
![image](https://user-images.githubusercontent.com/26766152/100589301-e39a0980-332d-11eb-8dce-d1ce150733f3.png)
