### ISSUE TITLE
数据报表SUM()求和问题，求和不是循环数据的总计

### ISSUE THREAD

**Issue by MCSophie** [zhangdaiscott/jeecg-boot#2037]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26766152/100316803-31dd9e80-2ff6-11eb-8f2a-25cf3876c98e.png)

![image](https://user-images.githubusercontent.com/26766152/100316816-386c1600-2ff6-11eb-962b-d161bee0540c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本就支持了
