### ISSUE TITLE
如何新建一个路由菜单，点击后在新标签页打开

### ISSUE THREAD

**Issue by keepstraight** [zhangdaiscott/jeecg-boot#2039]
##### 问题描述：
目前系统有大屏设计要求，需要在菜单栏点击菜单然后在新标签页打开此页面。
但是我配置的菜单都没有办法在新标签页打开，而我看了官网文档上的【菜单配置说明】，文档中给出的例子都是在新标签页打开的外部网站或者是请求的后台项目文件，而不是自己前端项目的文件，所以想请问一下有没有办法可以实现，新建路由菜单在新标签打开此菜单对应的页面。
http://doc.jeecg.com/2043933

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33247602/100354586-59029300-302b-11eb-8862-55d01e6c2028.png)
![image](https://user-images.githubusercontent.com/33247602/100354618-61f36480-302b-11eb-892f-1992196a9325.png)
![image](https://user-images.githubusercontent.com/33247602/100354643-6881dc00-302b-11eb-9c6a-264e348a3a27.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by shen-lan** [comment]
@HoraceZ919  你解决了吗  ？看代码似乎需要在 TabLayout.vue改

**Comment by HoraceZ919** [comment]
> @HoraceZ919 你解决了吗 ？看代码似乎需要在 TabLayout.vue改

src\components\menu\Contextmenu 这里用window.open弹出新标签页
src\config\router.config.js 这里改地址
然后jeecg里菜单设置，前端组件空着就行

**Comment by shen-lan** [comment]
@HoraceZ919 
‘src\config\router.config.js 这里改地址
然后jeecg里菜单设置，前端组件空着就行’
这两点有demo吗 ？试了下不行  routeview渲染不出来。
