### ISSUE TITLE
swagger 访问不了

### ISSUE THREAD

**Issue by wtus** [zhangdaiscott/jeecg-boot#204]
弹窗登录，进不去

**Comment by zhangdaiscott** [comment]
描述太简单

**Comment by wtus** [comment]
> 描述太简单

Sorry, 我補充一下

登陸后訪問
http://boot.jeecg.org/#/dashboard3/10b80437abc6eee8c3e3daabb5e9f59e

我看了一下 ShiroConfig 配置 ，感覺沒問題，不知道問題出在哪裏

**Comment by zhangdaiscott** [comment]
jeecg
jeecg1314
访问没问题

**Comment by liudonghua123** [comment]
我也是访问 http://localhost:8080/jeecg-boot/swagger-ui.html 一直访问不了，一直弹窗输入用户名密码都不对。
![image](https://user-images.githubusercontent.com/2276718/62283972-4e5eda80-b485-11e9-9c5e-257a879e43d3.png)

从下图 可以看到 /swagger-ui.html 应该是可以匿名访问的
![image](https://user-images.githubusercontent.com/2276718/62284063-7d754c00-b485-11e9-8b1d-499cf08a176b.png)
