### ISSUE TITLE
打包的时候，报错了

### ISSUE THREAD

**Issue by yanyanpeng** [zhangdaiscott/jeecg-boot#2040]
##### 版本号：
2.3
##### 问题描述：

运行如下  mvn package 报错了....

$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] jeecg-boot-parent                                                  [pom]
[INFO] jeecg-boot-base-common                                             [jar]
[INFO] jeecg-boot-module-system                                           [war]
[INFO]
[INFO] -------------< org.jeecgframework.boot:jeecg-boot-parent >--------------
[INFO] Building jeecg-boot-parent 2.2.1                                   [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- spring-boot-maven-plugin:2.1.3.RELEASE:repackage (repackage) @ jeecg-boot-parent ---
[INFO]
[INFO] -----------< org.jeecgframework.boot:jeecg-boot-base-common >-----------
[INFO] Building jeecg-boot-base-common 2.2.1                              [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ jeecg-boot-base-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ jeecg-boot-base-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ jeecg-boot-base-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\git\emkboot\jeecg-boot\jeecg-boot-base-common\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ jeecg-boot-base-common ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ jeecg-boot-base-common ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ jeecg-boot-base-common ---
[INFO] Building jar: E:\git\emkboot\jeecg-boot\jeecg-boot-base-common\target\jeecg-boot-base-common-2.2.1.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:2.1.3.RELEASE:repackage (repackage) @ jeecg-boot-base-common ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jeecg-boot-parent 2.2.1:
[INFO]
[INFO] jeecg-boot-parent .................................. SUCCESS [  3.983 s]
[INFO] jeecg-boot-base-common ............................. FAILURE [  3.714 s]
[INFO] jeecg-boot-module-system ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.141 s
[INFO] Finished at: 2020-11-26T22:31:16+08:00
[INFO] ------------------------------------------------------------------------
【如下信息是报错的信息-------------------------------------------------------------------|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||】
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.3.RELEASE:repackage (repackage) on project jeecg-boot-base-common: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.1.3.RELEASE:repackage failed: Unable to find a single main class from the following candidates [org.jeecg.common.util.DySmsHelper, org.jeecg.common.util.YouBianCodeUtil, org.jeecg.common.system.util.JwtUtil, org.jeecg.common.util.encryption.AesEncryptUtil] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jeecg-boot-base-common

##### 截图&代码：

![image](https://user-images.githubusercontent.com/60538506/100364129-a76a5e80-3038-11eb-9722-e3fe42b2a807.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CherryRum** [comment]
可以先 clean下 在打包

mvn -rf :jeecg-boot-base-common

**Comment by yanyanpeng** [comment]
> 可以先 clean下 在打包
> 
> mvn -rf :jeecg-boot-base-common
您好，可以给我远程指导一下吗？
我的QQ号码，849610355
跪求指导一下下.

**Comment by yanyanpeng** [comment]
您好，可以给我远程指导一下吗？
我的QQ号码，849610355
跪求指导一下下.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 上午9:25
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"849610355"<849610355@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 打包的时候，报错了 (#2040)





 
可以先 clean下 在打包
 
mvn -rf :jeecg-boot-base-common
