### ISSUE TITLE
系统设置等页面权限校验问题

### ISSUE THREAD

**Issue by changruhe** [zhangdaiscott/jeecg-boot#2045]
##### 版本号：
jeecg-boot-2.3

##### 问题描述：
管理员登录后，点击系统设置等菜单后退出登录，登录一个没有系统设置权限的用户，浏览器点击后退，可以看到相应的设置页面

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
友情提示： 未按格式要求发帖，会直接删掉。
