### ISSUE TITLE
管理员登录后退出，登录其他账号能过看见一些未授权的页面

### ISSUE THREAD

**Issue by changruhe** [zhangdaiscott/jeecg-boot#2046]
##### 版本号：
2.3

##### 问题描述：
管理员登录后点击系统管理的角色管理，菜单管理等页面后退出，登录其他账户，浏览器点击后退，可以看到账户未授权的系统管理等页面（管理员点击过的历史页面）

##### 截图&代码：
<img width="1219" alt="截屏2020-11-30 上午11 40 12" src="https://user-images.githubusercontent.com/37977711/100566474-1aa5f600-3301-11eb-9808-dd02feec9b08.png">

退出登录后，切换其他低权限账号，浏览器后退，可以看见这个“职务管理”页面（该账号未授权“职务管理”页面）
<img width="1222" alt="截屏2020-11-30 上午11 44 28" src="https://user-images.githubusercontent.com/37977711/100566662-956f1100-3301-11eb-8f9e-d43d91f07346.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
未授权还能访问吗，不对吧

**Comment by changruhe** [comment]
> 未授权还能访问吗，不对吧

可以的，因为后退是基于浏览器缓存，未授权的角色还是可以看到未授权的页面的

**Comment by 1298191366** [comment]
非常规操作
