### ISSUE TITLE
大屏设计器无法使用

### ISSUE THREAD

**Issue by BruceYuj** [zhangdaiscott/jeecg-boot#2047]
##### 版本号：
2020年 11 月 30 日
http://boot.jeecg.com:8080/jeecg-boot/bigscreen

##### 问题描述：
大屏设计器很多资源报 net::ERR_SLL_PROTOCOL_ERROR 

##### 截图&代码：

![2](https://user-images.githubusercontent.com/19621739/100578746-db39d280-331d-11eb-93b1-3aa0cd4f3f1d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好了
