### ISSUE TITLE
online报表查询排序问题

### ISSUE THREAD

**Issue by FirstMemory** [zhangdaiscott/jeecg-boot#2048]
##### 版本号：
2.2.1

##### 问题描述：
sqlserver 2008 版本的数据库 online报表查询排序不生效，请问是数据库版本问题还是什么原因导致？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31384429/100584195-bb5adc80-3326-11eb-8d82-8ac5964c7003.png)
![image](https://user-images.githubusercontent.com/31384429/100584635-518f0280-3327-11eb-830b-a6cb0e6d181c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044154

**Comment by FirstMemory** [comment]
就是按这个配置的，不生效

**Comment by FirstMemory** [comment]
![image](https://user-images.githubusercontent.com/31384429/101608626-e76e1000-3a40-11eb-9810-82f39af244c4.png)
