### ISSUE TITLE
定时任务问题

### ISSUE THREAD

**Issue by Ray-Sir-Like** [zhangdaiscott/jeecg-boot#205]
1.从前台新建一个定时任务

2.设置为启动状态,

3.这个时候如果重启后台, 重启后的后台 不会自动执行处于启动状态的任务

1.0版本中存在这个问题,得到的答复时2.0发布时解决,
2.0.1版本依然存在这个问题

**Comment by zhangdaiscott** [comment]
收录，我测试下

**Comment by zhangdaiscott** [comment]
测试没问题啊
