### ISSUE TITLE
请问大佬有计划前台用vue3.0开发吗

### ISSUE THREAD

**Issue by ggunmo** [zhangdaiscott/jeecg-boot#2050]
##### 版本号：
2.4

##### 问题描述：

请问大佬有计划前台用vue3.0开发吗
##### 截图&代码：

请问大佬有计划前台用vue3.0开发吗

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
vue3.0还不稳定，等明年稳定了会出新UI
