### ISSUE TITLE
jeecgboot-mysql-5.7.sql导入不成功

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2051]
##### 版本号：

2.4
##### 问题描述：

使用Naviccat创建数据库，导入jeecgboot-mysql-5.7.sql错误：[ERR] 1046 - No database selected
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么时候下载的代码

**Comment by zhangdaiscott** [comment]
修复了，请更新代码
