### ISSUE TITLE
微服务启动报错

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2052]
##### 版本号：
2.4

##### 问题描述：
微服务启动报错，属性值找不到。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32193518/100840540-ff79e880-34b0-11eb-80e9-c9d7debb0d71.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by iwen-git** [comment]
![image](https://user-images.githubusercontent.com/32193518/100840791-5c759e80-34b1-11eb-9026-56e7766c48c2.png)

**Comment by zhangdaiscott** [comment]
nacos配置了吗
http://doc.jeecg.com/2043906

**Comment by iwen-git** [comment]
nacos配置了 
![image](https://user-images.githubusercontent.com/32193518/100844586-0572c800-34b7-11eb-9276-801f92751515.png)
![image](https://user-images.githubusercontent.com/32193518/100844618-0e639980-34b7-11eb-8154-33b7ed84de14.png)

**Comment by huangguocai** [comment]
你的配置呢老铁，配置列表空的啊

**Comment by iwen-git** [comment]
哦哦 谢谢 @huangguocai 现在可以了，nacos上配置参数 和 代码上配置参数优先级是什么样子的，比如nacos我现在新建的是jeecg.yaml  他这个是全局的参数吗
