### ISSUE TITLE
当用户单租户多部门时存在未setTenant的BUG

### ISSUE THREAD

**Issue by huangguocai** [zhangdaiscott/jeecg-boot#2053]
##### 截图&代码：

show(loginResult){
        this.clear();
        this.bizDepart(loginResult);

        let user = Vue.ls.get(USER_INFO)
        this.username = user.username
        let ids = user.relTenantIds
        this.bizTenant(ids);

       //多部门单租户时visible为true，租户未设置
        if(this.visible===false){
          this.$store.dispatch('saveTenant', this.tenant_id);
          this.$emit('success')
        }

      }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/101348507-b538a300-38c6-11eb-8630-443e80db2a5a.png)

**Comment by zhangdaiscott** [comment]
已处理，请更新代码
