### ISSUE TITLE
微服务启动之后，验证码不显示，麻烦请教下是否哪个没配置好？

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2054]
##### 版本号：
2.4

##### 问题描述：
微服务启动之后，验证码不显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32193518/100848426-0f4afa00-34bc-11eb-8baa-fbeae4f12ddd.png)

![image](https://user-images.githubusercontent.com/32193518/100848332-ef1b3b00-34bb-11eb-8016-0ba07e63acaf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看你后台接口地址配置

**Comment by iwen-git** [comment]
@zhangdaiscott 谢谢 已解决
