### ISSUE TITLE
后台启动提示相关jar包打不开

### ISSUE THREAD

**Issue by CoolITDog** [zhangdaiscott/jeecg-boot#2055]
##### 版本号：
2.3.0

##### 问题描述：
后台启动提示相关jar包打不开（已经设置了maven私服）

##### 截图&代码：

java: 读取D:\Program Files\local-repository-jeecg\org\hibernate\hibernate-re\2.3.01\hibernate-re-2.3.01.jar时出错; error in opening zip file
java: 读取D:\Program Files\local-repository-jeecg\org\jeecgframework\boot\codegenerate\1.2.2\codegenerate-1.2.2.jar时出错; error in opening zip file

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043876
