### ISSUE TITLE
Online表单开发字段类型是否可以新增多一些类型

### ISSUE THREAD

**Issue by jiangjiacheng** [zhangdaiscott/jeecg-boot#2056]
##### 问题描述：
Online表单开发选择字段类型最大只能为Blob,能否新增mediumtext等类型。如果手动更改数据库字段类型，但是在Online表单开发列表同步状态依旧显示未同步，后续更改字段也无法同步。或者可以指导一下在哪里改，新增一些字段类型

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22400199/100860146-17f6fc80-34cb-11eb-91db-5870213935d3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
online得包括各个数据库的兼容性，所以mediumtext暂时不会加
