### ISSUE TITLE
I think the front-end judgment method of login failure is very dirty

### ISSUE THREAD

**Issue by andotorg** [zhangdaiscott/jeecg-boot#2057]
##### 版本号：
last

##### 问题描述：
I think the front-end judgment method of login failure is very dirty

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25116294/100867532-4e397980-34d5-11eb-9ed2-bb19615888b5.png)

![image](https://user-images.githubusercontent.com/25116294/100867541-509bd380-34d5-11eb-95c0-2f96f282d67c.png)

##### 修改建议
In Result class add static write method：
/**
	 * 专门在response写入
	 * @param code
	 * @param message
	 * @param servletRequest
	 * @param servletResponse
	 */
	public static void write(Integer code, String message, ServletRequest servletRequest, ServletResponse servletResponse) {
		PrintWriter out = null;
		try{
			HttpServletResponse response = (HttpServletResponse)servletResponse;
			HttpServletRequest request = (HttpServletRequest)servletRequest;
			response.setContentType("application/json;charset=utf-8");
			if(code == null){
				code = 0;
			}
			Result result = new Result();
			result.setMessage(message);
			result.setCode(code);
			out = response.getWriter();
			out.write(JSONObject.toJSONString(result));
			log.error(request.getRequestURI()+message);
		}catch (Exception ex){
			log.error(ex.getMessage());
		}finally {
			IOUtils.closeQuietly(out);
		}
	}

In ShiroRealm add override onAccessDenied method：

@Override
	protected boolean onAccessDenied(ServletRequest request, ServletResponse response) throws Exception {
		if(request.getAttribute("message") != null){
			Result.write(Integer.parseInt(request.getAttribute("xcode").toString()), request.getAttribute("message").toString(), request, response);
		}else{
			Result.write(401, "登录失效，请重新登录！", request, response);
		}
		return false;
	}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Fliner** [comment]
支持

**Comment by tygithub1** [comment]
onAccessDenied 没用到
