### ISSUE TITLE
2.4版本更新后子表onlChange方法不生效

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2059]
##### 版本号：
2.4

##### 问题描述：
1.更新版本以后修改子表控件值的方法不生效了，控制台也不报错
2.子表新增行时，控制台报错
3.子表的输入框能否改成原来不隐藏的样式

##### 截图&代码：
1.
![image](https://user-images.githubusercontent.com/26364818/100955211-1243fa00-3551-11eb-9524-33d7cf23abf1.png)
2.
![image](https://user-images.githubusercontent.com/26364818/100955035-c09b6f80-3550-11eb-9289-2fbe2840dd6d.png)
3.
![image](https://user-images.githubusercontent.com/26364818/100955105-dd37a780-3550-11eb-8f31-1dd6bbf5a8d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
问题1 已修复 后续发布新版 请按照官方文档示例  使用triggleChangeValues
![image](https://user-images.githubusercontent.com/27989856/100977158-898e8380-357b-11eb-8806-63c52c0e0e9b.png)
问题2 未重现 可能已经修复
问题3 不能

**Comment by zhangdaiscott** [comment]
已经提交代码了，请更新
