### ISSUE TITLE
如何快速和和spring cloud集成呢？

### ISSUE THREAD

**Issue by sotier** [zhangdaiscott/jeecg-boot#206]
如何快速和和spring cloud集成呢？

**Comment by zhangdaiscott** [comment]
快速改造： 先实现服务注册、统一配置中心、路由、路由授权（这块有点成本）
              
技术选型可以参考：
![image](https://user-images.githubusercontent.com/3162115/62761716-f560f900-bab9-11e9-8623-81fa4c28c9ff.png)

**Comment by zhangdaiscott** [comment]
暂时先关闭，后面提供专题博客
