### ISSUE TITLE
JVxeTable待优化

### ISSUE THREAD

**Issue by 17504418001** [zhangdaiscott/jeecg-boot#2060]
##### 问题描述：
JVxeTable 和JEditableTable.vue都存在这个问题，多选下拉框，启用编辑后，会导致行高不对齐，

##### 截图&代码：

![QQ图片20201203111923](https://user-images.githubusercontent.com/43158623/100959698-ccd7fa80-3559-11eb-9b1f-b6c079da9df0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 17504418001** [comment]
![QQ图片20201203111923](https://user-images.githubusercontent.com/43158623/100959764-f42ec780-3559-11eb-9560-f1af06016b1f.png)

**Comment by lvdandan16** [comment]
1.JVxeTable 下可将下拉多选框width调至合适长度
![image](https://user-images.githubusercontent.com/54099258/101892029-d1498680-3bdd-11eb-9dad-a6b948ac4803.png)
2.JEditableTable下可在JEditableTable.vue下拉多选框处添加:maxTagCount="1"
![image](https://user-images.githubusercontent.com/54099258/101892249-1e2d5d00-3bde-11eb-9b0a-48a41e21475a.png)
