### ISSUE TITLE
前端增加用户模块 密码的校验规则没有生效

### ISSUE THREAD

**Issue by huiyup** [zhangdaiscott/jeecg-boot#2063]
##### 版本号：
2.3

##### 问题描述：
前端增加用户模块 密码的校验规则没有生效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34112957/100986671-7a620280-3588-11eb-8aff-235220fd1b0a.png)

**Comment by zhangdaiscott** [comment]
自己加的，还是默认的代码不好使？

**Comment by huiyup** [comment]
默认的不好使

**Comment by zhangdaiscott** [comment]
我们本地无问题啊，你确认下你是那个功能点
或者看看boot.jeecg.com

**Comment by huiyup** [comment]
创建用户时的密码不是加了8位的校验规则，为什么没有生效，输入几位都会创建， 你给的事例也是这样

**Comment by 1298191366** [comment]
已修改，待新版本发布
