### ISSUE TITLE
非id外键关联主子表,关联查询任然用的id查询

### ISSUE THREAD

**Issue by maomao321** [zhangdaiscott/jeecg-boot#2064]
##### 版本号：

2.3.0
##### 问题描述：
用id外的其他字段关联主子表，详情查看时候，还是用的主表id查询的，但是想用关联的字段查询

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20788725/100998077-0e869680-3596-11eb-9f05-04ecf0b8bd9f.png)
![image](https://user-images.githubusercontent.com/20788725/100998142-2231fd00-3596-11eb-8bfe-1c8598cec71c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/qa
79

再不行可以生成完代码，手工改造
