### ISSUE TITLE
 项目一启动直接 JwtFilter 会报————————身份认证失败——————————

### ISSUE THREAD

**Issue by zombietramp** [zhangdaiscott/jeecg-boot#2065]
##### 版本号：
2.4

##### 问题描述：
切换到微服务模式后，启动 module 下面的 system-start  systemApplication 项目一启动直接 JwtFilter 会报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1066758/101110381-d756ca80-3613-11eb-926c-8c39bcc2c57d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
功能有影响？

**Comment by zombietramp** [comment]
上线直接报这个错误 不适合吧，而且 会一直报。

**Comment by 1298191366** [comment]
未重现该问题，请提供操作步骤
