### ISSUE TITLE
2,4版本问题如果url中有包括中文（已编码），就报400 Bad Request 

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#2069]
##### 问题描述：2,4版本问题如果url中有包括中文（已编码），就报400 Bad Request There was an unexpected error (type=Bad Request, status=400).
Invalid request

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8542824/101126096-bacb8a00-3635-11eb-97e8-16763ecdb232.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在问题，收录

**Comment by justwang33** [comment]
我也碰到过，如果上传图片名称包含中文，也报同样的错误

**Comment by catlvsuger** [comment]
同样碰到这个问题，没找到问题出在哪？是什么原因呢

**Comment by tianchenglong323** [comment]
> 的确存在问题，收录

帅哥  什么原因呢

**Comment by catlvsuger** [comment]
把 shiro 版本1.7.0降到1.6.0，可以解决该问题
		
		<dependency>
		    <groupId>org.apache.shiro</groupId>
		    <artifactId>shiro-spring-boot-starter</artifactId>
		    <version>1.6.0</version>
		</dependency>

**Comment by zhangdaiscott** [comment]
good

**Comment by CherryRum** [comment]
@zhangdaiscott 大佬看下这个，在看看是不是还是修复下，降级修复是不是不太好呀
https://blog.csdn.net/qq_35598240/article/details/110310638

**Comment by zhangdaiscott** [comment]
> @zhangdaiscott 大佬看下这个，在看看是不是还是修复下，降级修复是不是不太好呀
> https://blog.csdn.net/qq_35598240/article/details/110310638

好的
