### ISSUE TITLE
添加人员BUG

### ISSUE THREAD

**Issue by dingzhongyu2019** [zhangdaiscott/jeecg-boot#207]
![image](https://user-images.githubusercontent.com/51330069/59478997-f0067a00-8e8d-11e9-9cb5-4883d5140f2f.png)

部门选择正常，但数据库没有添加值，添加，修改都不行

![image](https://user-images.githubusercontent.com/51330069/59479027-090f2b00-8e8e-11e9-8e96-3c2e562041f3.png)

**Comment by zhangdaiscott** [comment]
那个菜单，描述太简单
