### ISSUE TITLE
2.4在线表单导入配置java增强，不会抛出异常，即使导入不成功也不会。

### ISSUE THREAD

**Issue by kevin19860812** [zhangdaiscott/jeecg-boot#2070]
##### 版本号：
2.4

##### 问题描述：
2.4版本，在线表单开发中，对某一表单的导入按钮添加了java增强，在实现代码中手动抛出异常，前端仍然提示导入成功，数据没有插入进去。后端有捕获到异常。

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/45220316/101128120-f36d6280-3639-11eb-8be5-529d8b1b3ad3.png)

![图片](https://user-images.githubusercontent.com/45220316/101128146-02ecab80-363a-11eb-8bf9-aebfbaa3954c.png)
代码如下:
import com.alibaba.fastjson.JSONObject;
import org.jeecg.common.exception.JeecgBootException;
import org.jeecg.modules.online.cgform.enhance.CgformEnhanceJavaInter;
import org.jeecg.modules.online.config.exception.BusinessException;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * 财务收入导入处理
 */
@Component("financialIncomeImport")
public class FinancialIncomeImport implements CgformEnhanceJavaInter {
    @Override
    public int execute(String s, Map<String, Object> map) throws BusinessException {

        //默认返回1 走新增逻辑
        return 1;
    }

    @Override
    public int execute(String s, JSONObject jsonObject) throws BusinessException {
//        try {
            System.out.println(jsonObject.toJSONString());
            if(1==1) {
                throw new JeecgBootException("测试报错");
            }
//        }catch (Exception e){
//            e.printStackTrace();
//        }
        //默认返回1 走新增逻辑
        return 1;
    }
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
目前这里处理了 org.jeecg.modules.online.config.exception.BusinessException

**Comment by kevin19860812** [comment]
不行的。不管抛出什么Exception，页面上都是提示导入成功，数据没进去。


@Component("financialIncomeImport")
public class FinancialIncomeImport implements CgformEnhanceJavaInter {
    @Override
    public int execute

(String s, Map<String, Object&gt; map) throws BusinessException {

        //默认返回1 走新增逻辑
        return 1;
    }

    @Override
    public int execute(String s, JSONObject jsonObject) throws BusinessException {
//        try {
            System.out.println(jsonObject.toJSONString());
            if(1==1) {
                throw new BusinessException("测试报错");
            }
//        }catch (Exception e){
//            e.printStackTrace();
//        }
        //默认返回1 走新增逻辑
        return 1;
    }
}







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 晚上7:19
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"鱼摆摆缺水"<642080176@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 2.4在线表单导入配置java增强，不会抛出异常，即使导入不成功也不会。 (#2070)





 
目前这里处理了 org.jeecg.modules.online.config.exception.BusinessException

**Comment by zhangdaiscott** [comment]
处理完成，下个版本发布
