### ISSUE TITLE
2.4Redis工具存入key,value取不出来

### ISSUE THREAD

**Issue by klhgithub** [zhangdaiscott/jeecg-boot#2071]
##### 版本号：
2.4

##### 问题描述：
在SysGatewayRouteServiceImpl.java 40行存入geteway_routes路由信息，在JeecgRedisClient.java 41行取出路由信息时取不到

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49932434/101134641-ab543d00-3645-11eb-9c98-9f01b0b6fc11.png)

![image](https://user-images.githubusercontent.com/49932434/101134842-f1a99c00-3645-11eb-8204-a568ce8e961e.png)

![image](https://user-images.githubusercontent.com/49932434/101136343-24ed2a80-3648-11eb-9c73-f5e7b2bb39bf.png)
![image](https://user-images.githubusercontent.com/49932434/101136438-4bab6100-3648-11eb-8e14-f507bdc11136.png)
![image](https://user-images.githubusercontent.com/49932434/101136627-9200c000-3648-11eb-8bfe-80698db0db62.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by klhgithub** [comment]
用geteway_routes这个key把路由信息存入redis，启动网关用geteway_routes在redis查找路由信息，找不到

**Comment by zhangdaiscott** [comment]
更新代码吧，已经修复了
