### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by Linyuxujun** [zhangdaiscott/jeecg-boot#2072]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/45812406/101146662-3ccbab00-3656-11eb-943d-a6e0b4484db6.png)
![image](https://user-images.githubusercontent.com/45812406/101146705-49500380-3656-11eb-9c9d-18c30a050e00.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Linyuxujun** [comment]
**### 是不是不能修改包名？ 修改包名会有问题？**

**Comment by zhangdaiscott** [comment]
是的
