### ISSUE TITLE
怎样正确关闭eslint。

### ISSUE THREAD

**Issue by DDtoken** [zhangdaiscott/jeecg-boot#2073]
##### 版本号：
2.2

##### 问题描述：
怎样关闭eslint？
按照备注的做法
关闭 Eslint (不推荐) 移除 package.json 中 eslintConfig 整个节点代码

然后 yarn run serve 。仍然显示

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
删除.eslintrc.js 或者禁用Eslint
