### ISSUE TITLE
j-editor bug

### ISSUE THREAD

**Issue by qlanto224** [zhangdaiscott/jeecg-boot#2074]
##### 版本号：
2.2.1

##### 问题描述：
当j-deitor的父级是a-modal时,会出现首次加载编辑器内容无法显示

##### 截图&代码：
`<j-modal :title="title" :width="1000" :visible="visible" :confirmLoading="confirmLoading" switchFullscreen
    @ok="handleOk" @cancel="handleCancel" cancelText="关闭">

    <a-spin :spinning="confirmLoading">
      <a-form :form="form">

        <a-form-item :labelCol="labelCol" :wrapperCol="wrapperCol" label="标准名称">
          <a-input placeholder="请输入标准名称" v-decorator="['standardName', validatorRules.standardName]" />
        </a-form-item>
        <a-form-item :labelCol="labelCol" :wrapperCol="wrapperCol" label="标准类别">
          <a-input placeholder="请输入标准类别" v-decorator="['standardCategoryId', {}]" />
        </a-form-item>
        <a-form-item :labelCol="labelCol" :wrapperCol="wrapperCol" label="标准内容" style="height: 470px;">
          <a-row :gutter="24">
            <a-col :span="20">
              <j-editor :height="450" v-if="visible" :triggerChange="triggerChange" v-model="model.content" />
            </a-col>
          </a-row>
          <a-row>
            <a-upload name="file" :action="url.getWordContent" :headers="headers" @change="uploadChange">
              <a-button>
                <a-icon type="upload" />文件上传 </a-button>
            </a-upload>
          </a-row>
        </a-form-item>
      </a-form>
    </a-spin>
  </j-modal>`

友情提示： 未按格式要求发帖，会直接删掉。
### 解决方法
修改initATabsChangeAutoReload()
代码如下:
`
initATabsChangeAutoReload() {
        // 获取父级
        let tabs = getVmParentByName(this, 'ATabs')
        let tabPane = getVmParentByName(this, 'ATabPane')
        let modal = getVmParentByName(this,'AModal')
        if (tabs && tabPane ) {
          // 用户自定义的 key
          let currentKey = tabPane.$vnode.key
          // 添加事件监听
          tabs.$on('change', (key) => {
            // 切换到自己时执行reload
            if (currentKey === key) {
              this.reload()
            }
          })
        }else if(modal){
          console.log("tinymce reload!")
          this.reload();
        }
      },
`

**Comment by 1298191366** [comment]
请升级到版本2.4，新版本已修改
