### ISSUE TITLE
Jackson配置WRITE_NUMBERS_AS_STRINGS 之后，页面崩溃，精度丢失问题没法解决

### ISSUE THREAD

**Issue by RobinsChens** [zhangdaiscott/jeecg-boot#2075]
##### 版本号：
v2.0.2 估计所有版本都有这个问题

##### 问题描述：
由于分布式的id生成器，字段过长，所以我们之前采用WRITE_NUMBERS_AS_STRINGS： true 配置处理的，但是
jeecg代码npm框架依赖里面total那些字段都强制使用number了，没法兼容使用，麻烦作者关注一下呢

##### 截图&代码：

spring:
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
#    generator:
#      WRITE_NUMBERS_AS_STRINGS: true

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
类org.jeecg.config.WebMvcConfiguration加上这段代码可以解决精度问题

```
  /**
    * 添加Long转json精度丢失是配置
    * @Return: void
    */
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        MappingJackson2HttpMessageConverter jackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter();
        ObjectMapper objectMapper = new ObjectMapper();
        SimpleModule simpleModule = new SimpleModule();
        simpleModule.addSerializer(Long.class, ToStringSerializer.instance);
        simpleModule.addSerializer(Long.TYPE, ToStringSerializer.instance);
        objectMapper.registerModule(simpleModule);
        jackson2HttpMessageConverter.setObjectMapper(objectMapper);
        converters.add(jackson2HttpMessageConverter);
    }
```

**Comment by johnyhi** [comment]
ObjectMapper objectMapper = jackson2HttpMessageConverter.getObjectMapper();

**Comment by BringChen** [comment]
> 类org.jeecg.config.WebMvcConfiguration加上这段代码可以解决精度问题
> 
> ```
>   /**
>     * 添加Long转json精度丢失是配置
>     * @Return: void
>     */
>     @Override
>     public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>         MappingJackson2HttpMessageConverter jackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter();
>         ObjectMapper objectMapper = new ObjectMapper();
>         SimpleModule simpleModule = new SimpleModule();
>         simpleModule.addSerializer(Long.class, ToStringSerializer.instance);
>         simpleModule.addSerializer(Long.TYPE, ToStringSerializer.instance);
>         objectMapper.registerModule(simpleModule);
>         jackson2HttpMessageConverter.setObjectMapper(objectMapper);
>         converters.add(jackson2HttpMessageConverter);
>     }
> ```



> 类org.jeecg.config.WebMvcConfiguration加上这段代码可以解决精度问题
> 
> ```
>   /**
>     * 添加Long转json精度丢失是配置
>     * @Return: void
>     */
>     @Override
>     public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>         MappingJackson2HttpMessageConverter jackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter();
>         ObjectMapper objectMapper = new ObjectMapper();
>         SimpleModule simpleModule = new SimpleModule();
>         simpleModule.addSerializer(Long.class, ToStringSerializer.instance);
>         simpleModule.addSerializer(Long.TYPE, ToStringSerializer.instance);
>         objectMapper.registerModule(simpleModule);
>         jackson2HttpMessageConverter.setObjectMapper(objectMapper);
>         converters.add(jackson2HttpMessageConverter);
>     }
> ```
这个情况，我也遇到了，虽然解决了long类型的id经度丢失问题，但是jeecg的web端分页也会提示报错，虽然报错不影响使用，报错大概内容就是提示 分页的那些页码，total是字符串，应该要number的类型。所以这个全局方法不可取，应当换成在id上面加注解@JsonSerialize(using= ToStringSerializer.class)
