### ISSUE TITLE
接口会调用两次

### ISSUE THREAD

**Issue by shadow--walker** [zhangdaiscott/jeecg-boot#2077]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/4071550/101327342-84964080-38a9-11eb-9738-cb7d32ccd157.png)
![image](https://user-images.githubusercontent.com/4071550/101327429-a1cb0f00-38a9-11eb-9834-217cacae5bf8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个没关系，是谷歌自己的模拟

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/weixin_43275277/article/details/119858417
