### ISSUE TITLE
使用ant的菜单会同时在左上角出现二级列表

### ISSUE THREAD

**Issue by qw12152** [zhangdaiscott/jeecg-boot#2078]
##### 问题描述：
使用ant的菜单组件，会在左上角出现重复的二级列表，并且ant列表位置显示不正确

##### 截图&代码：

![image](https://user-images.githubusercontent.com/54138726/101331578-28361f80-38af-11eb-82c2-1eea411cdefa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本有点老，如何重现？

**Comment by qw12152** [comment]
> 版本有点老，如何重现？

切换成顶部菜单栏。然后鼠标移动到省略号的二级菜单就会复现

**Comment by 1298191366** [comment]
未重现此bug，抢升级到最新版本进行尝试
