### ISSUE TITLE
设置菜单消失

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2079]
##### 版本号：
2.4

##### 问题描述：
在系统设置中没有其他设置了，导致默认的多页签模式无法关闭，尝试在defaultsetting.js中修改，还是没有用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/101437291-ce833300-394a-11eb-9e56-b63fdad1e54a.png)
![image](https://user-images.githubusercontent.com/63634402/101437307-dc38b880-394a-11eb-85f9-db034f878378.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪你改什么了？

**Comment by FreedomStark** [comment]
就把图二的默认true改成false，其他没有改动的地方，这问题在做在线开发的时候突然看到了

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经处理了，请更新代码
