### ISSUE TITLE
注册用户总是提示“手机验证码错误”

### ISSUE THREAD

**Issue by letbingo** [zhangdaiscott/jeecg-boot#2081]
##### 版本号：
 2.4.0（发布日期：2020-12-01）
##### 问题描述：
jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/SysUserController#userRegister(@RequestBody JSONObject jsonObject, SysUser user);方法中，拿equals方法对比Object与String是不合理的，应该将object转为String之后再进行对比

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49687347/101448376-e0240500-3961-11eb-86a0-6ca42ac451d1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修改，待新版本发布

**Comment by letbingo** [comment]
同文件中，存在另一个类似的问题
![image](https://user-images.githubusercontent.com/49687347/102216541-42f33e80-3f16-11eb-8190-b757893138c1.png)
