### ISSUE TITLE
jeecg-boot-module-demo项目的pom缺少打包插件

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2082]
##### 版本号：
2.4

##### 问题描述：
在微服务环境下，使用mvn package打包后，打出的jar包不是一个可运行的spring-boot jar包，需要在pom中加入

<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经在文档中补充了
http://doc.jeecg.com/2043906

**Comment by zhangdaiscott** [comment]
已经在文档中补充了
