### ISSUE TITLE
怎么不用Spring Integration实现分布式锁？

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#2084]
##### 版本号：
2.4

##### 问题描述：
Spring Integration分布式锁是spring自带的，基层更方便，没有多余的redisson配置

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
后续考虑的还有跟redisson的结合的其他功能
