### ISSUE TITLE
网关gateway启动后访问doc.html异常

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2085]
##### 版本号：
2.4

##### 问题描述：
启动了gateway[9999]、system[7001]以及demo[8080]服务，通过http://172.20.13.124:9999/doc.html访问接口文档，下拉选择jeecg-demo，提示knife4j异常。但是直接访问http://172.20.13.124:8080/doc.html接口文档是正常的，各接口也可以调通。这个问题很费解啊。

请求http://172.20.13.124:9999/jeecg-demo/v2/api-docs 直接404

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你是采用微服务方式启动的吗

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043906
