### ISSUE TITLE
codegenerate没有这个文件夹

### ISSUE THREAD

**Issue by daye** [zhangdaiscott/jeecg-boot#2086]
##### 版本号：

2.4.0
##### 问题描述：
import org.jeecgframework.codegenerate.generate.util.SimpleFormat; 引入的这个框架 没有这个工具类

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12163431/101560330-00a19d00-39fe-11eb-9763-6bd94bcf4a0f.png)

如图所示

**Comment by zhangdaiscott** [comment]
？
