### ISSUE TITLE
缩小或扩大浏览器页面时，菜单展开咨询

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2088]
##### 版本号：
2.3、2.4

##### 问题描述：
缩小或扩大浏览器页面时，菜单会自动展开一下然后缩进去，可以在哪可以设置为默认不展开那一下？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32193518/101563573-790b5c80-3a04-11eb-9507-952e878727fb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/804
