### ISSUE TITLE
首页加载很慢！预加载的文件太多，部分文件又太大了怎么处理啊？

### ISSUE THREAD

**Issue by yankangZhou** [zhangdaiscott/jeecg-boot#2092]
##### 版本号：

2.2.0
##### 问题描述：

首页加载很慢！预加载的文件太多，部分文件又太大了怎么处理啊？
##### 截图&代码：
css/chunk-vendors.ded36fe7.css  9.5M
css/chunk-06f5f676.ffbf3b4d.css 7.3M
几十K的文件很多很多

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考最新版开启压缩

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/qa
53

**Comment by zhengqingxin** [comment]
vue 脚手架默认开启了预加载，可以禁用 https://github.com/vuejs/vue-cli/issues/979#issuecomment-373027130
