### ISSUE TITLE
maven 设置私服以后依然拉包失败

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#2094]
##### 版本号：
2.4

##### 问题描述：
2.4设置maven私服以后依然拉包失败，但是2.3可以。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/9925064/101642817-6594db80-3a6e-11eb-8db8-9675b1f80d62.png)
私服配置如下：
![image](https://user-images.githubusercontent.com/9925064/101642915-8826f480-3a6e-11eb-9d02-34536037f5a2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CharlieJ0hn** [comment]
[ERROR] Failed to execute goal on project jeecg-boot-module-system: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-module-system:jar:2.4.0: The following artifacts could not be resolved: org.jeecgframework.boot:jeecg-system-local-api:jar:2.4.0, org.jeecgframework.boot:jeecg-boot-module-demo:jar:2.4.0, org.jeecgframework.boot:jeecg-boot-module-takeaway:jar:2.4.0: Failure to find org.jeecgframework.boot:jeecg-system-local-api:jar:2.4.0 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by zhangdaiscott** [comment]
install root
