### ISSUE TITLE
基础管理功能的安全性问题

### ISSUE THREAD

**Issue by wishinlife** [zhangdaiscott/jeecg-boot#2096]
##### 问题描述：
目前的模板代码里，system模块的所有接口都没有添加权限要求（SysUserController加了几个但都注释了），这样只要有一个系统账号，就可以通过postman等工具来修改角色、用户等内容，会造成系统的重大安全隐患。虽然这个权限每个项目都可以自己通过修改controller接口代码加上（有些小公司或小项目团队的可能不会关注到这一块），但这又不利用将来整个模板框架有bug修复后的更新操作，一旦有更新后，所有的这个权限又都需要修改一遍，不如模板里都带好权限，采用统一的模式会较好。

##### 建议：

1. 所有系统基础功能的接口都添加上权限要求；
2. 在菜单项上也可以添加授权标识（可选设置），这样可以采用“sys:user:*"这样的模式来给此菜单所用到的所有接口统一授权，同时也避免了很多菜单或按钮不需要独立授权时需要添加多个按钮/权限项，在角色权限设置时也可以减少选择项，在需要细分权限时，也可以在菜单项上不设置授权标识，通过添加子项来细分权限。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by KuanKuanya** [comment]
普通版的也有这个问题

**Comment by KuanKuanya** [comment]
也是注销了会影响嘛

**Comment by zhangdaiscott** [comment]
众口难调 觉得需要，自己改代码生成器模板加上吧

**Comment by wishinlife** [comment]
@zhangdaiscott 我说的系统的集成管理功能部分，如用户管理、角色管理、权限管理等jeecg-boot-module-system模块里的接口权限，这部分如果自己重新用生成器模板重新生成，应该是不行的；要是自己建表生成的部分倒好说些，哪怕自己写都不影响。

**Comment by Sean-214** [comment]
@zhangdaiscott 我认为这不是众口难调的问题，目前的角色权限方案，是只防君子不防小人。只是在前端页面上控制是没意义的。

**Comment by liangwenzhong** [comment]
这个应该算是这个开源项目的漏洞吧，只是控制了页面能否看到。数据接口可以直接调用。

**Comment by zhangdaiscott** [comment]
接口需要控制，自己加权限注解

**Comment by liangwenzhong** [comment]
@zhangdaiscott  非常感谢您的高效回复。新开发的模块，是可以加上权限注解。但是原有的基础模块，例如：职务管理，角色管理等。这些基础模块，基本不会去动，建议这些模块可以默认加上。
要不这些基础模块，每个都手动加上后，后续版本升级。就显得不大可能了。
