### ISSUE TITLE
请求更换前端图表绘制viser

### ISSUE THREAD

**Issue by gsdukbh** [zhangdaiscott/jeecg-boot#2098]
##### 版本号：
2.4.1

##### 问题描述：
此项目使用的前端图表绘制组件 viser 已经长期没有更新，相关的文档不够完善，[viser](https://github.com/viserjs/viser/releases) 上一个release 已经是两年前了，为了此项目 `xxxx-boot` 能够更好的发展下去，
在此建议更换，或者移除viser 的支持。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by gsdukbh** [comment]
viser是G2的二次封装，或许直接更换到 G2

**Comment by zhangdaiscott** [comment]
积木报表马上出了，一个专门的报表工具
http://jimureport.com/
