### ISSUE TITLE
高级查询组件中无法关闭popup

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2099]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/102032404-9882fa80-3df3-11eb-9256-c7c712cf8c40.png)
![image](https://user-images.githubusercontent.com/63634402/102032453-c23c2180-3df3-11eb-986f-120c3d31acea.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经支持查询，下个版本发布
