### ISSUE TITLE
jeecg-boot:仓库jeecg/org/jeecgframework/boot/下核心包缺失

### ISSUE THREAD

**Issue by AmbroseRen** [zhangdaiscott/jeecg-boot#2100]
##### 版本号：
2.4.0

##### 问题描述：
jeecg-boot-module-demo;jeecg-system-local-api仓库核心镜像包缺失←……

##### 截图&代码：

![image](https://user-images.githubusercontent.com/35362717/102033564-bb62de00-3df6-11eb-8918-ffff4deaf925.png)

![image](https://user-images.githubusercontent.com/35362717/102033583-c87fcd00-3df6-11eb-8aac-96badb291ea4.png)

![image](https://user-images.githubusercontent.com/35362717/102033599-d2a1cb80-3df6-11eb-9af1-8ced4465d4b9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/102034730-ba7f7b80-3df9-11eb-9fe8-e8d920decec6.png)
