### ISSUE TITLE
pgsql 数据库 代码生成，配置 之后  取得表是public下面的

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2101]
##### 版本号：
2.3

##### 问题描述：
pgsql 数据库 代码生成，配置 之后  取得表是public下面的，怎么配置为其他的下面，比如下面截图ods下面的表。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/32193518/102044299-7ef0ab80-3e11-11eb-9767-d709819310b7.png)
![image](https://user-images.githubusercontent.com/32193518/102044328-8ca63100-3e11-11eb-8258-0288701e5542.png)
![image](https://user-images.githubusercontent.com/32193518/102044370-a2b3f180-3e11-11eb-990e-df93caa0e4a0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by iwen-git** [comment]
@zhangdaiscott  pgsql数据库下有多个schema，目前这个好像取得表都是public模式下，如何取其它模式下呢。

**Comment by iwen-git** [comment]
@zhangdaiscott 麻烦大佬告知下  这个在哪修改，找了半天没找到

**Comment by beichenhpy** [comment]
ex:  url: jdbc:postgresql://localhost:5432/test?currentSchema=short-url

**Comment by zhangdaiscott** [comment]
收录 待测试 sq

**Comment by zhangdaiscott** [comment]
代码生成器依赖升级到
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.3.4</version>
</dependency>
```

配置文件jeecg/jeecg_database.properties增加属性
```
#PostgreSQL模式，多个逗号分隔
schemaName=public,test
```
