### ISSUE TITLE
开发文档，war线上发布能否更新一下，现在的说明已经不能用了

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#2102]
##### 问题描述：
开发文档的war包线上发布太老了，用不了，麻烦可以更新一下吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经更新请确认
http://doc.jeecg.com/2043887
