### ISSUE TITLE
online表单开发-功能测试报错

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#2103]
##### 版本号：
2.4

##### 问题描述：
启用了多租户的表，online表单开发就不能进行功能测试了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9925064/102048631-7781d000-3e1a-11eb-8df0-98eae87ec0a1.png)
![image](https://user-images.githubusercontent.com/9925064/102048779-b44dc700-3e1a-11eb-85fd-9628ecd82524.png)
![image](https://user-images.githubusercontent.com/9925064/102048939-f0812780-3e1a-11eb-9934-935d113ebf68.png)

看起来是在线开发的功能测试没有传tenantId过去

**Comment by zhangdaiscott** [comment]
你怎么加的？online配置里面有对应的字段吗

**Comment by CharlieJ0hn** [comment]
按照您的文档加的，多租户的表都添加了 tenant_id 字段，然后在 MyBatisPlusConfig 里边 tenantTable 添加了对应的表。
现在生成的代码可以正常使用，但是 online 功能测试不能用了。

**Comment by zhangdaiscott** [comment]
详细说明吧，没明白

**Comment by CharlieJ0hn** [comment]
就是不管什么表，只要给这个表开了多租户，就不能用online表单开发了。在online表单开发里边点一个开了多租户的表功能测试就报错。
