### ISSUE TITLE
有两个jar包无法下载

### ISSUE THREAD

**Issue by Len888** [zhangdaiscott/jeecg-boot#2104]
##### 版本号：
2.4.0

##### 问题描述：
Cannot resolve org.jeecgframework.boot:codegenerate:1.2.5
Cannot resolve org.hibernate:hibernate-re:2.3.07

##### 截图&代码：
按照提示设置了xml，但是还是下载不下来jar包

![image](https://user-images.githubusercontent.com/45664532/102059571-08ad7280-3e2c-11eb-9af3-29c5cb191a9a.png)
![image](https://user-images.githubusercontent.com/45664532/102059609-12cf7100-3e2c-11eb-86d9-1fa17d64468c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
依赖没下载好吧，删除这俩本地的仓库文件，重新下载

http://doc.jeecg.com/2043876

**Comment by Len888** [comment]
好的~

**Comment by JiangHoumin** [comment]
同样的问题，按照楼主的方法试过了，换源+删除本地包，还是不管用，是不是你们私服挂了？

**Comment by JiangHoumin** [comment]
> 好的~

你现在可以了吗？
