### ISSUE TITLE
开源版本是否提供接口权限配置功能？

### ISSUE THREAD

**Issue by bantu4me** [zhangdaiscott/jeecg-boot#2105]
##### 版本号：
2.3

##### 问题描述：
开源版本是否提供接口权限配置功能？
我在文档里面看到有相关描述，但是在该版本中没有对应菜单
http://idoc.jeecg.com/1275967

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11781345/102062959-5e841980-3e30-11eb-9ba6-3892bb363e92.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecgboot是前后端分离的，默认就是接口，不需要跟老版本哪样配置

参考新文档
http://doc.jeecg.com/2044036
