### ISSUE TITLE
Websocket 总是断开重连

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#2106]
##### 版本号：
2.4

##### 问题描述：
已经取消了Nginx 的 proxy_read_timeout，开启了 HeaderNotice 中的心跳，但是还是一直断线重连，想问大佬您有没有开启了Websocket不断线的例子和配置。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/9925064/102097595-17624c80-3e61-11eb-9f81-3cf671745a57.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CharlieJ0hn** [comment]
文档中也没有和常见问题没有找到和websocket心跳相关的内容

**Comment by SunWenBiao** [comment]
你那边能链接上websocket吗？websocket的配置能看看吗？
location /websocket/ {
			proxy_pass http://127.0.0.1:8080/jeecg-boot/websocket/;
			proxy_set_header Origin '';
     			proxy_http_version 1.1;
    			proxy_set_header Upgrade $http_upgrade;
    			proxy_set_header Connection "upgrade";
		}
我这边这样配置一直连不上

**Comment by CharlieJ0hn** [comment]
#WSS-BEGIN
    location /websocket {
           proxy_pass http://127.0.0.1:8080/jeecg-boot; 
           #proxy_read_timeout 60s;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection 'Upgrade';
    }    
    #WSS-END
@SunWenBiao 你这样就能脸上了，proxy_pass最后不要有/websocket

**Comment by SunWenBiao** [comment]
我这边按你说的配置之后还是不行的我自己也用了ssl证书了

**Comment by jooejooe** [comment]
@CharlieJ0hn 我也出现这种问题，什么原因，解决了吗？

**Comment by CharlieJ0hn** [comment]
> @CharlieJ0hn 我也出现这种问题，什么原因，解决了吗？

没有解决，不知道为啥😳

**Comment by Caisen1988** [comment]
@CharlieJ0hn @jooejooe 你们好，请问解决了吗？
