### ISSUE TITLE
接口权限配置功能

### ISSUE THREAD

**Issue by bantu4me** [zhangdaiscott/jeecg-boot#2108]
##### 版本号：
2.3

##### 问题描述：
https://github.com/zhangdaiscott/jeecg-boot/issues/2105
这是之前反馈的问题，我描述不清楚，作者已经关闭。
我的应用场景是：基于jeccg-boot开发了几个对外接口，每个接口是个不同的第三方调用的（原则上系统A只能调用接口a，系统B只能调用接口b），这些接口也不需要配置菜单，不需要界面操作，是纯接口用来同步数据的。目前第三方调用接口的方式是，先通过登录接口/jeecg-boot/sys/mLogin获取token，然后再通过token调用接口，这样的话，无法保证接口调用安全性，系统A也可能调用接口b。我查看了权限控制相关的文档，没有查到现成的解决方案。想确认目前开源2.3版本能否实现上述功能。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个没有得自己搞
