### ISSUE TITLE
请问下jeecg-boot是否提供上下文类可以获取当前用户信息？

### ISSUE THREAD

**Issue by bantu4me** [zhangdaiscott/jeecg-boot#2109]
##### 版本号：
2.3开源版本

##### 问题描述：
请问下jeecg-boot是否提供上下文类可以获取当前用户信息？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CharlieJ0hn** [comment]
LoginUser sysUser = (LoginUser)SecurityUtils.getSubject().getPrincipal();

还有通过 token 获取：org.jeecg.common.system.util.JwtUtil.getUsername(token)
