### ISSUE TITLE
2.3版本修改项目名和包名后点击online在线开发出现资源未找到。网上的方法都试过了。还是不行

### ISSUE THREAD

**Issue by SmileCocc** [zhangdaiscott/jeecg-boot#2110]
##### 版本号：
2.3

##### 问题描述：
online在线开发生成代码异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57064716/102182974-11fc1500-3ee8-11eb-906d-ee59ec4191aa.png)
![image](https://user-images.githubusercontent.com/57064716/102183032-28a26c00-3ee8-11eb-9274-e2bbef951489.png)
![image](https://user-images.githubusercontent.com/57064716/102183100-4079f000-3ee8-11eb-8a27-dab616f3803c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你自己改什么了
改默认jeecg的根路径了？
