### ISSUE TITLE
微服务布署jeecg-cloud-system-start-2.4.0时 报错，提示缺少单体服务 system 的依赖

### ISSUE THREAD

**Issue by yangfuhua2009** [zhangdaiscott/jeecg-boot#2111]
##### 

> 截图&代码：

![error](https://user-images.githubusercontent.com/15136732/102184265-2214f400-3eea-11eb-810d-4b9aa5798c78.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yangfuhua2009** [comment]
![code](https://user-images.githubusercontent.com/15136732/102184742-e595c800-3eea-11eb-8dfd-7e9c4738282c.png)

**Comment by zhangdaiscott** [comment]
jeecg-boot-module-system/pom.xml

这个参数改了吗
![image](https://user-images.githubusercontent.com/3162115/102326656-a1282c00-3fbf-11eb-9601-3737942e7d4d.png)
