### ISSUE TITLE
Online在线代码生成器无法在linux下面工作吗

### ISSUE THREAD

**Issue by Capricornwqh** [zhangdaiscott/jeecg-boot#2112]
##### 版本号：
2.4.0

##### 问题描述：
Online在线代码生成，显示生成成功，但在目录下面找不到代码，下载的压缩包也损坏。
jeecg-boot开发环境安装在linux下面

##### 截图&代码：
![1](https://user-images.githubusercontent.com/37462508/102186647-e67c2900-3eed-11eb-99ea-a8c32d3bed3f.png)
![2](https://user-images.githubusercontent.com/37462508/102186664-ea0fb000-3eed-11eb-8474-a1663f71ec0f.png)
![3](https://user-images.githubusercontent.com/37462508/102186681-ee3bcd80-3eed-11eb-8f34-cf43205dd0ff.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043922
