### ISSUE TITLE
前端项目打包后生成的chunk-vendors.XX.js 大小有8M，首次加载非常慢。

### ISSUE THREAD

**Issue by yinglw** [zhangdaiscott/jeecg-boot#2114]
##### 问题描述：

前端项目打包后生成的chunk-vendors.XX.js 有8M首次加载非常慢。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/qa
53
