### ISSUE TITLE
FormTypes.popup重复点击会将子表值置空

### ISSUE THREAD

**Issue by HeAvenLinH** [zhangdaiscott/jeecg-boot#2117]
##### 版本号：
2.4.0

##### 问题描述：
子表使用FormTypes.popup，第一次点击会正常返回值，再一次选择重复数据点击会将子表值置空，而且不能进行赋值

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12153749/102325454-1e52a180-3fbe-11eb-9e42-7fcff9cf165d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
代码贴一下

**Comment by HeAvenLinH** [comment]
![image](https://user-images.githubusercontent.com/12153749/102326569-86ee4e00-3fbf-11eb-9e51-080ff7a46965.png)

**Comment by HeAvenLinH** [comment]
title: '盒子编码' ,
            key: 'boxCode' ,
            type: FormTypes.popup ,
            popupCode: 'box_manage' ,
            field: 'boxid,boxcode,remainnum' ,
            orgFields: 'boxid,boxcode,remainnum' ,
            destFields: 'boxId,boxCode,remainNum',
            validateRules: [{required: true, message: '${title}不能为空'}],

**Comment by HeAvenLinH** [comment]
并且给这个加validateRules会出错，明明有数据，还是未填写状态
![image](https://user-images.githubusercontent.com/12153749/102327420-ac2f8c00-3fc0-11eb-8015-d8a0d580341d.png)

**Comment by lsqGitHub716** [comment]
你把 field: 'boxid,boxcode,remainnum' ,这个配置去掉再试一下看看

**Comment by sjlei** [comment]
问题已修复，下个版本更新

**Comment by sjlei** [comment]
你的用法不对，`field`字段不能用逗号分割，只能填一个字段，如下所示：
``` js
{
        title: '盒子编码' ,
        key: 'boxCode' ,
        type: FormTypes.popup ,
        popupCode: 'box_manage' ,
        field: 'boxId' , // 从destFields中选择一个属性的值返回给当前组件
        orgFields: 'boxid,boxcode,remainnum' ,
        destFields: 'boxId,boxCode,remainNum',
        validateRules: [{required: true, message: '${title}不能为空'}],
}
```

参考文档：
![image](https://user-images.githubusercontent.com/34293221/113088158-a3815f80-9217-11eb-8258-077065d3789c.png)
