### ISSUE TITLE
附表如何添加部门、用户等基础资料的选择

### ISSUE THREAD

**Issue by mianfeidog** [zhangdaiscott/jeecg-boot#2118]
##### 版本号：
2.4

##### 问题描述：
online表单中，主表的控件类型可以选部门选择、用户选择，附表设计的时候没有这两个选择，请问如何解决。这个问题在ERP开发中特别常见，比如在附表中选择客户、供应商、物料、计量单位等，都会用到。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by mianfeidog** [comment]
用popup使用场景比较受限，数据库表会存在冗余字段，比如附表显示 部门编码、部门名称、部门id，表中就会存在3个字段，实际上存一个部门id就可以

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/102466452-047e9080-408a-11eb-949b-e362c6647fda.png)

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
