### ISSUE TITLE
liunx线上SSL环境配置 websocket访问报错 failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by SunWenBiao** [zhangdaiscott/jeecg-boot#2119]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/15643858/102364762-c6359280-3ff1-11eb-8d39-54d2313e0c86.png)
		
		location /websocket/ {
			proxy_pass http://127.0.0.1:8080/jeecg-boot/websocket/;
			proxy_set_header Origin '';
     			proxy_http_version 1.1;
    			proxy_set_header Upgrade $http_upgrade;
    			proxy_set_header Connection "upgrade";
		}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
nginx不用额外配置

**Comment by SunWenBiao** [comment]
不用配置这个   location /websocket/ {
		proxy_pass http://127.0.0.1:8080/jeecg-boot/websocket/;
		proxy_set_header Origin '';
 			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
	}

**Comment by SunWenBiao** [comment]
您这边说nginx不用什么额外配置？我去掉websocket配置也是不行

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4494367

**Comment by Nicky213Zhang** [comment]
> ##### 版本号：2.2.0
> ##### 问题描述：liunx线上SSL环境配置websocket访问报错 failed: Error during WebSocket handshake: Unexpected response code: 404
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/15643858/102364762-c6359280-3ff1-11eb-8d39-54d2313e0c86.png)
> 
> ```
> 	location /websocket/ {
> 		proxy_pass http://127.0.0.1:8080/jeecg-boot/websocket/;
> 		proxy_set_header Origin '';
>  			proxy_http_version 1.1;
> 			proxy_set_header Upgrade $http_upgrade;
> 			proxy_set_header Connection "upgrade";
> 	}
> ```
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

请问线上https连接websocket解决了吗，我这边网关处理了之后前端不会出404，显示连接成功了，但是后端netty报错：io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record，暂时没找到解决方法
