### ISSUE TITLE
固定Header时菜单tab页签栏同时固定

### ISSUE THREAD

**Issue by shuperry** [zhangdaiscott/jeecg-boot#212]
### 版本号
2.0.1

### 问题描述&截图
如果有选择固定Header时，菜单的tab页签栏可以同时固定，增加操作方便程度，或者再增加一个配置专门针对是否固定菜单tab页签栏

![image](https://user-images.githubusercontent.com/12183336/59647326-53a1e780-91ad-11e9-8387-794967d7b1bb.png)

**Comment by fly1206** [comment]
修改src/components/layouts/TabLayout.vue
（1）style  增加样式
  .ant-layout-content{
    .ant-tab-fixedTab {
      position: fixed;
      top: 60;
      z-index: 10;
      width: 100%;
      transition: width .2s;
    }
  }

（2）代码修改
a-tabs   class修改
:class="['tab-layout-tabs', fixedHeader ? 'ant-tab-fixedTab' : null ]"
a-tabs   下面div样式修改
<div :style="fixedHeader ? 'margin: 64px 12px 0;':'margin: 12px 12px 0;'">


![1](https://user-images.githubusercontent.com/23536399/59991471-1b514c00-967a-11e9-912f-ee5cfd78f0a4.png)
![2](https://user-images.githubusercontent.com/23536399/59991483-26a47780-967a-11e9-8ce2-36c66f3f47fb.png)

**Comment by shuperry** [comment]
@fly1206  请问下这个代码在下一版中会加进去吗？

**Comment by fly1206** [comment]
你自己加吧  短期应该不会加进去

**Comment by shuperry** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，多谢
    
        
            
        
    
    
    
    

    

    

    在2019年06月24日 15:28，fly1206<notifications@github.com> 写道： 


你自己加吧  短期应该不会加进去
