### ISSUE TITLE
部门编码，权限问题

### ISSUE THREAD

**Issue by PrintNext** [zhangdaiscott/jeecg-boot#2120]
##### 问题描述：
部门编码生成规则是A+数字，部门过多就会出现 A10，A100，然后部门权限是右模糊查询 A10%则会查询出A100的数据，这类问题如果修改

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
每一级
默认是36个字母+0-99数 不够用吗

**Comment by PrintNext** [comment]
是够用，但是数据中出现A100的情况了

**Comment by zhangdaiscott** [comment]
数字最高到99 ，你改了编码生成规则？

**Comment by PrintNext** [comment]
发现问题了，导入机构的时候，机构编码超过100了

**Comment by zhangdaiscott** [comment]
收录

**Comment by lvdandan16** [comment]
机构导入时编码是获取文件里的编码，文件中的部门编码不可出现超过99数据

**Comment by PrintNext** [comment]
Excel的文件机构编码是用户填写的，然后数量超过100了，他直接Excel下拉从A99添加到A100，我看导入源码是直接读取的，然后就出现A100的情况了
