### ISSUE TITLE
一对多内嵌表显示问题

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2121]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/102435286-4ccd8c80-4051-11eb-9843-f2297cba30ee.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个列字段的宽度可以通过设置控件长度
![image](https://user-images.githubusercontent.com/3162115/102710564-106a8c80-42ee-11eb-9817-e6dcd8e9f6c6.png)

来实现
