### ISSUE TITLE
popup权限问题

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2122]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/102454630-4c48ec00-4079-11eb-9256-9b97c7f05b1b.png)
![image](https://user-images.githubusercontent.com/63634402/102454691-6256ac80-4079-11eb-862c-512981803ee8.png)
![image](https://user-images.githubusercontent.com/63634402/102454759-78fd0380-4079-11eb-9ce0-3e59313d70db.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪就针对popup的报表配置数据权限
