### ISSUE TITLE
代码生成器功能不生成附表vue？

### ISSUE THREAD

**Issue by bantu4me** [zhangdaiscott/jeecg-boot#2124]
##### 版本号：
2.3

##### 问题描述：
online开发，主表A和附表B，生成代码。后端代码包含附表B的相关service层，但是生成的前端代码，只有主表A的相关内容吗？

##### 截图&代码：
online表单功能测试如图
![image](https://user-images.githubusercontent.com/11781345/102468299-4dcfdf80-408c-11eb-8b93-24b7b0b9c5a0.png)
生成的前端代码配置菜单后如图
![image](https://user-images.githubusercontent.com/11781345/102468328-56281a80-408c-11eb-8ed4-866ec133fcb8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
选中主键数据就可以对子表进行操作
