### ISSUE TITLE
通过字段href实现3张表的关联问题

### ISSUE THREAD

**Issue by banxiu** [zhangdaiscott/jeecg-boot#2125]
##### 版本号：
jeecg-boot.V2.4.0

##### 问题描述：

设置了主表跳转字段的地址后  ，测试功能是能跳转到二级菜单，但是生成代码后，导入前后台代码后，发现并未实现一级表单点击功能，且设置了跳转功能的字段并未变成<a>标签。
##### 截图&代码：

一级表字段为Id：/online/cgformList/ff80a8751de2435f8724117c8f4c9e55?id=${id}
二级表配置地址：/online/cgformList/ff80a8751de2435f8724117c8f4c9e55

旌启 盼回

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
此部分链接代码生成未实现，先暂时手工调整吧
