### ISSUE TITLE
online建表，复杂表结构 中的 数据权限 问题

### ISSUE THREAD

**Issue by whx511jim** [zhangdaiscott/jeecg-boot#2130]
##### 版本号：
2.4，但是我没有用cloud

##### 问题描述：

我有这样一个需求，
数据库的大致结构如下图所示
其中，
部门表：就是jeecg自带的部门表
仓库表：用来记录仓库名称，一个部门有一个或多个仓库
规格表：用于记录物品的规格，材质
批次表：用于记录一个批次物品的入库时相关数据的表，一个批次的物品必然只属于一个仓库，同时只属于一个规格
物品表：用于记录物品实际归属的表，通过批次表来关联物品的规格，一个批次可以有多个物品，同样，一个仓库也可以有多个物品。

这个里面，因为物品在初次入库后，可能会被调整去别的仓库，所以 “仓库-物品” 的关系不能被 “仓库-批次-物品”的关系替代。

然后这个里面就出现了一个问题，
用户的需求很自然，规格是所有人可见的；各个部门，能看且只能看“同单位内所有部门的”仓库信息、批次信息、物品信息。
（单位就是部门树的第一级）

基于这个结构，我把仓库、批次、规格、物品表都建成了单表（我的理解是主附表中，附表内容只能在主表页面中增删改查，附表没有单独的自动生成的页面，所以我用了单表+外键+popup控件的形式实现，有其他的办法吗？）
对于仓库这个表，我可以用数据权限的功能让用户只看到对应的信息
对于批次、物品这两个表，因表内没有sys_org_code属性，我能在不额外引入sys_org_code的情况下实现数据权限吗？
如何实现比较方便？
亦或是我应该添加sys_org_code字段？

问题总结：
1、online开发中，我有除了全部用单表之外的更好的方式来实现这个结构吗？
2、online开发中，我怎么做能最方便的实现这个权限控制

##### 截图&代码：
图一
![微信图片_20201219174408](https://user-images.githubusercontent.com/76245686/102686352-0c713880-4222-11eb-93ba-878fa32a94ce.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by whx511jim** [comment]
啊，我的图倒了，重新传一个吧
![微信图片_20201219174408](https://user-images.githubusercontent.com/76245686/102686697-44797b00-4224-11eb-8377-7d22dd5107b7.jpg)

**Comment by whx511jim** [comment]
今天起来又看了下这个问题，感觉描述的不是很好，换个方式描述：
在sql中，我如果想实现这个数据权限过滤，我只需要 
select * 
from 物品表 inner join 批次表 on 外键与id一致
                    inner join 仓库表 on 外键与id一致
即可。
那么，online 开发中有类似 join 的功能或者结构吗？

**Comment by zhangdaiscott** [comment]
有自定义sql
![image](https://user-images.githubusercontent.com/3162115/102738265-8f120900-4384-11eb-897a-6f02419932f4.png)

**Comment by whx511jim** [comment]
> 有自定义sql
> ![image](https://user-images.githubusercontent.com/3162115/102738265-8f120900-4384-11eb-897a-6f02419932f4.png)

ok，自定义Sql 是否支持正则表达式？语法是否就是按照Mybatis的与法规则？还是使用对应数据库的语法规则？
