### ISSUE TITLE
在线表单能否自行配置目标数据库

### ISSUE THREAD

**Issue by freewind1977** [zhangdaiscott/jeecg-boot#2131]
##### 截图&代码：
在线表单同步数据库时，能否指标生成的目标数据库，要是业务表全部存放在jeecg-boot不太合适，业务表还是独立出来比较好管理和维护。
目前在jeecg-boot的数据表中有sys_data_source表（个人理解是做数据源管理的），但没有看到关于这个的管理界面，能否在在线表单数据同步时可以指定一个数据源，让在线表单可以生成在目标数据库中。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
