### ISSUE TITLE
Online报表的数据权限不起作用

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2133]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/102849037-3197be00-4451-11eb-9452-fa3aee1b9313.png)
![image](https://user-images.githubusercontent.com/63634402/102849056-3d838000-4451-11eb-8e95-bcad12f0e464.png)
![image](https://user-images.githubusercontent.com/63634402/102849121-69066a80-4451-11eb-9d16-5070d9697b97.png)
![image](https://user-images.githubusercontent.com/63634402/102849136-758ac300-4451-11eb-9fce-3308d7a7b0dc.png)
![image](https://user-images.githubusercontent.com/63634402/102849167-86d3cf80-4451-11eb-9629-7ba8b4f25254.png)
![image](https://user-images.githubusercontent.com/63634402/102849203-a1a64400-4451-11eb-8f6b-a3aaf8356ee0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
退出重新登录了吗

**Comment by FreedomStark** [comment]
有尝试过，还是没用

**Comment by zhangdaiscott** [comment]
你的字段对吗，怎么是中文
![image](https://user-images.githubusercontent.com/3162115/103183844-ecabd580-48ef-11eb-9917-82491652bda2.png)
