### ISSUE TITLE
常见案例=>JVXETable示例(NEW)=>普通示例页面下高级示例 前端页面报错误！

### ISSUE THREAD

**Issue by jyh11111** [zhangdaiscott/jeecg-boot#2134]
##### 问题描述：前端页面中 常见案例=>JVXETable示例(NEW)=>普通示例页面下高级示例
                            点击新增, 页面报错误: 
                         JVxeCellMixins.js?c86d:301 Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26827394/102857299-20f04380-4463-11eb-9bbb-cae39c93036f.png)

友情提示：

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
