### ISSUE TITLE
联动组件代码生成没有

### ISSUE THREAD

**Issue by czjmalong** [zhangdaiscott/jeecg-boot#2135]
##### 截图&代码：
![Uploading _@%})VU%`2@}_Z~VI~$9@SC.png…](
![X$K} HN(_DGA PRCX`V$Z@2](https://user-images.githubusercontent.com/48177524/102886715-94f51080-4490-11eb-8aa1-90b298b33731.png)
![}D`) ZMG~44UN923XE@$B`V](https://user-images.githubusercontent.com/48177524/102886725-99b9c480-4490-11eb-9a2a-34571260f9fa.png)

)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
