### ISSUE TITLE
本地代码生成 编码增值不生效

### ISSUE THREAD

**Issue by rose312** [zhangdaiscott/jeecg-boot#2138]
##### 版本号：
2.4

##### 问题描述：

通过在线表单配置编码增值规则，导出本地代码后，新增页编码增值不生效。

##### 截图&代码：

文本框，原样返回 显示 ${code}
并没有解析，而在线表单预览的形式，增值编码生效

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持

**Comment by rose312** [comment]
有没有解决办法？比如js加强等
