### ISSUE TITLE
模板导出功能，#fe: 横向遍历怎么用不了呢 {{#fe:maplist t.xxx}} 是这样格式吧？

### ISSUE THREAD

**Issue by chenshouzuo** [zhangdaiscott/jeecg-boot#2139]
##### 版本号：

2.0
##### 问题描述：
模板导出功能，#fe: 横向遍历怎么用不了呢 {{#fe:maplist t.xxx}} 是这样格式吧？

##### 截图&代码：

{{#fe:maplist d.reqBillNo}}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
excel的情况，已经修复，请用这个版本
```
<dependency>
	<groupId>org.jeecgframework</groupId>
	<artifactId>autopoi-web</artifactId>
	<version>2.0.1</version>
</dependency>
```
附件有测试模板
[test.xlsx](https://github.com/zhangdaiscott/jeecg-boot/files/5892656/test.xlsx)

**Comment by wlgshf** [comment]
<dependency>
	<groupId>org.jeecgframework</groupId>
	<artifactId>autopoi-web</artifactId>
	<version>2.0.1</version>
</dependency>
最新版本是1.3.6  也没有2.0.1版本啊？？？？？

**Comment by wlgshf** [comment]
> excel的情况，已经修复，请用这个版本
> 
> ```
> <dependency>
> 	<groupId>org.jeecgframework</groupId>
> 	<artifactId>autopoi-web</artifactId>
> 	<version>2.0.1</version>
> </dependency>
> ```
> 
> 附件有测试模板 [test.xlsx](https://github.com/zhangdaiscott/jeecg-boot/files/5892656/test.xlsx)

org.jeecgframework autopoi-web 2.0.1 最新版本是1.3.6 也没有2.0.1版本啊？？？？？
