### ISSUE TITLE
【建议】sys_log中request_param的字段类型问题

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#214]
### 版本号
2.0 - mysql

### 问题描述&截图
【建议】sys_log中request_param的字段类型问题

### 重现步骤&代码
当使用富文本编辑器时，由于记录操作和请求的值，导致这个字段一直提示data too long。建议修改为longtext类型。

**Comment by zhangdaiscott** [comment]
收录
