### ISSUE TITLE
MySQL 8 persist关键字问题报错

### ISSUE THREAD

**Issue by mdongsheng** [zhangdaiscott/jeecg-boot#2140]
##### 版本号：
 2.4.0

##### 问题描述：
MySQL 8.0.15 启动报错，MySQL 8新增了关键字`persist`

##### 截图&代码：
<img width="947" alt="image" src="https://user-images.githubusercontent.com/2139673/103071111-ea9afb80-45fd-11eb-80aa-c42a6bc52e2f.png”>

##### 解决办法：
<img width="375" alt="image" src="https://user-images.githubusercontent.com/2139673/103075472-a4966580-4606-11eb-807a-8c6050ebc7b7.png">
@TableField(value = "`persist`")
private Integer persist;

**Comment by zhangdaiscott** [comment]
已经改了，下个版本发布了，你先手工自己改了吧
