### ISSUE TITLE
OA模块咨询

### ISSUE THREAD

**Issue by fengqidonggood** [zhangdaiscott/jeecg-boot#2142]
##### 版本号：
2.4

##### 问题描述：

http://boot.jeecg.com/ 中的 OA模块的代码 在哪里可以找到
##### 截图&代码：

![image](https://user-images.githubusercontent.com/45030811/103076852-985fd780-4609-11eb-9ce2-cf4c1f32fe31.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
非开源功能
