### ISSUE TITLE
请问online表单中，编辑弹框可以实现弹出的表单中版本号字段自增吗？

### ISSUE THREAD

**Issue by hxianshun** [zhangdaiscott/jeecg-boot#2143]
##### 版本号：
2.4.0

##### 问题描述：
请问online表单中，编辑弹框可以实现弹出的表单中版本号字段自增吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34292183/103099277-cf091280-4648-11eb-9483-b1409e953f06.png)

THX！

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以通过编码规则实现
