### ISSUE TITLE
某字段用的下拉树用的分类字典，把该字段带到其他表中关联不上字典

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2144]
##### 版本号：
2.4

##### 问题描述：
![image](https://user-images.githubusercontent.com/55084864/103135853-71330400-46f6-11eb-8bf1-69bf75dd16d9.png)

![image](https://user-images.githubusercontent.com/55084864/103135848-5eb8ca80-46f6-11eb-83ee-f342f27bb1e6.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
配置截图出来

**Comment by tb2888** [comment]
![image](https://user-images.githubusercontent.com/55084864/103201810-cd329e00-492b-11eb-8999-f43984cf7e5f.png)

![image](https://user-images.githubusercontent.com/55084864/103201651-601f0880-492b-11eb-8123-0a18cf6ae1c7.png)

![image](https://user-images.githubusercontent.com/55084864/103201586-31089700-492b-11eb-916e-c6dbb1292a95.png)

**Comment by tb2888** [comment]
> 配置截图出来
![image](https://user-images.githubusercontent.com/55084864/103214192-c404f980-494a-11eb-8d3b-bd51733837af.png)
![image](https://user-images.githubusercontent.com/55084864/103214241-df700480-494a-11eb-9cb4-9f4035c26e49.png)
![image](https://user-images.githubusercontent.com/55084864/103214288-03334a80-494b-11eb-882f-83b601191360.png)
![image](https://user-images.githubusercontent.com/55084864/103214358-28c05400-494b-11eb-8ec7-09645ffffbbe.png)
![image](https://user-images.githubusercontent.com/55084864/103214402-42619b80-494b-11eb-98be-cc8582ed97ba.png)
![image](https://user-images.githubusercontent.com/55084864/103214410-4e4d5d80-494b-11eb-9ffd-40e2faed0a7e.png)

**Comment by lsqGitHub716** [comment]
一对多的附表目前没有实现分类字典控件，所以回显未翻译。后期会优化

**Comment by tb2888** [comment]
好的！感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 某字段用的下拉树用的分类字典，把该字段带到其他表中关联不上字典 (#2144)





 
一对多的附表目前没有实现分类字典控件，所以回显未翻译。后期会优化

**Comment by tygithub1** [comment]
我大致理一下你的配置，  主表字段配置的是分类字典，然后子表配置的是popup，数据从主表里取，有个特殊的地方在于子表的某个字段要取主表分类字典字段的值。  那么这里需要了解两个关键点： 1.分类字典存的是id，显示的是文本，但是子表不支持分类字典的配置。2.popup拿到的数据即显示的数据，也就是说popup没有字典文本转换，你数据库子表popup选过来的就是id，所以只能显示id

**Comment by tb2888** [comment]
对，子表通过popup带过来的是id，应该就是因为子表不支持分类字典配置，这个能不能做到支持呢？大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 某字段用的下拉树用的分类字典，把该字段带到其他表中关联不上字典 (#2144)





 
我大致理一下你的配置，  主表字段配置的是分类字典，然后子表配置的是popup，数据从主表里取，有个特殊的地方在于子表的某个字段要取主表分类字典字段的值。  那么这里需要了解两个关键点： 1.分类字典存的是id，显示的是文本，但是子表不支持分类字典的配置。2.popup拿到的数据即显示的数据，也就是说popup没有字典文本转换，你数据库子表popup选过来的就是id，所以只能显示id

**Comment by tygithub1** [comment]
暂不支持
