### ISSUE TITLE
微服务下的数据库分库

### ISSUE THREAD

**Issue by lanwaixian** [zhangdaiscott/jeecg-boot#2145]
##### 问题描述：
目前我在测试一种微服务对应的数据库分库方案：
Moudle System（jeecg boot启动module）对应数据库db_a（即现在jeecg boot中的所有表），
Module B（新建的module）对应数库db_b（Module B服务所需的表），
Module C（新建的module）对应数库db_c（Module C服务所需的表），

现在的问题是：Module B的controller里写注解@AutoLog，则会报错，提示不存在表sys_log，类似的切面涉及到表的都有这个问题。
应该如何配置才可以Module B既可以读取jeecgboot的表，又可以都去本服务下的表。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪就把日志那块做成服务化的，调用接口取存日志，或者日志先存到mQ里
