### ISSUE TITLE
上传附件如果比较大，在哪个地方修改上传附件的大小呢？

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#2147]
##### 问题描述：

上传附件如果比较大，在哪个地方修改上传附件的大小呢？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/103183803-ae161b00-48ef-11eb-922f-e663bbb60872.png)

**Comment by yanyapeng123** [comment]
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 上午9:33
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"闫亚鹏"<15114890832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 上传附件如果比较大，在哪个地方修改上传附件的大小呢？ (#2147)





 
Closed #2147.
