### ISSUE TITLE
jeecg-boot 2.0.1 版本代码生成器生成的字段无法模糊搜索

### ISSUE THREAD

**Issue by yaominyuan** [zhangdaiscott/jeecg-boot#215]
### 通过代码生成器生成的代码，前台搜索都是精确查找，按照MybatisPlus中@TableField注解 在实体类字段上加了，但是就是没用。
![image](https://user-images.githubusercontent.com/27772934/59669689-44428e80-91ed-11e9-9ef2-236568333b9d.png)

**Comment by zhangdaiscott** [comment]
jeecg自带查询过滤器，需要默认查询，文字： “张*”
http://jeecg-boot.mydoc.io/?t=345707

**Comment by zhangdaiscott** [comment]
如果需要默认全部模糊查询，可以这么改
jeecg-boot-base-common/org/jeecg/common/system/query/QueryGenerator.java:152
加上这段代码
// add -begin 添加判断为字符串时设为全模糊查询
					if("class java.lang.String".equals(type)) {
						// 可以设置左右模糊或全模糊，因人而异
						rule = QueryRuleEnum.LIKE;
					}
					// add -end 添加判断为字符串时设为全模糊查询

[图片]

**Comment by xiaojx-959** [comment]
> > 如果需要全部完全模糊查询，可以这么改
> > jeecg-boot-base-common / org / jeecg / common / system / query / QueryGenerator.java：152 
> > 加上以下代码
> 
> // add -begin添加判断为字符串时创建全模糊查询
> if（“ class java.lang.String” .equals（type））{
> //可以设置左右模糊或全模糊，因人而异
> rule = QueryRuleEnum 。喜欢;
> }
> //添加-end添加判断为字符串时添加全模糊查询
> 
> ![图片](https://user-images.githubusercontent.com/3162115/61507108-02d51700-aa17-11e9-9a64-2d445252e705.png)
> 
> 此改法的弊端：
> 会导致所有的查询都走模糊查询，有一种情况会出问题，此类通过拖放性别查询，男女值分别为0,1
> 这个时候采用混淆匹配，如果字典值有以0开头或者最终的字典值，就会导致查询出多个（非正常匹配）

online在线开发的可以开模糊查询吗  ，   上面这个方法在online测试页面就没有效果了

**Comment by zhouyunxu** [comment]
![image](https://user-images.githubusercontent.com/49867618/120765888-3f975200-c54c-11eb-834f-0bff68dbea57.png)
一楼的这个问题解决了吗? 我也想了解一下, 有些单个字段模糊查询不了怎么, 但不开启全局匹配的模糊查询,该怎么处理
