### ISSUE TITLE
点击按钮进行tab页跳转

### ISSUE THREAD

**Issue by awefire** [zhangdaiscott/jeecg-boot#2151]
##### 版本号：

v3.7
##### 问题描述：

怎么点击按钮进行tab页的跳转，求问？网上方法看起来不靠谱
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/103432338-4d9d1b80-4c18-11eb-861c-82de70077bad.png)
