### ISSUE TITLE
自动生成代码

### ISSUE THREAD

**Issue by xiaoguolong** [zhangdaiscott/jeecg-boot#2155]
##### 版本号：
v2.4

##### 问题描述：
本地可以生成代码，部署到Linux服务器就下载不了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/33684988/103328027-1866c100-4a92-11eb-8110-d7ad6332e3f2.png)
下载的是个空包

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043922

**Comment by xiaoguolong** [comment]
thanks
