### ISSUE TITLE
Autopoi的@Excel注解 disctTable、dicCode dicText 导出解析不成功

### ISSUE THREAD

**Issue by Fnckerpoi** [zhangdaiscott/jeecg-boot#2158]
##### 问题描述：
Autopoi的@Excel注解 disctTable、dicCode dicText 导出解析不成功

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38403438/103402158-da979480-4b86-11eb-9eef-b056ccf26f56.png)
![image](https://user-images.githubusercontent.com/38403438/103402206-15013180-4b87-11eb-87a6-f2417e90eaea.png)
![image](https://user-images.githubusercontent.com/38403438/103402233-34985a00-4b87-11eb-89f4-12d929c2e299.png)

autopoi对数据的缓存组装采用“_ 下划线”来拼接text和value
如果数据源text中有"_ 下划线"如截图1那么在导出时候无法导出，excel内容是value没有转译成text的内容

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复，请用这个版本
```
<dependency>
	<groupId>org.jeecgframework</groupId>
	<artifactId>autopoi-web</artifactId>
	<version>2.0.1</version>
</dependency>
```

**Comment by Fnckerpoi** [comment]
> 已经修复，请用这个版本
> 
> ```
> <dependency>
> 	<groupId>org.jeecgframework</groupId>
> 	<artifactId>autopoi-web</artifactId>
> 	<version>2.0.1</version>
> </dependency>
> ```

pom 里面替换后 maven找不到该以来的版本。在maven仓库中只有一点几的版本。这个是需要替换maven源么
