### ISSUE TITLE
自动生成的代码还是下载不了到本地

### ISSUE THREAD

**Issue by xiaoguolong** [zhangdaiscott/jeecg-boot#2161]
##### 问题描述：
按照 http://doc.jeecg.com/2043922 步骤
jar 包部署到linux上  能生成代码 但是下载不了
![image](https://user-images.githubusercontent.com/33684988/103500034-27c87e80-4e85-11eb-923e-c9690831a64b.png)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/33684988/103500101-4a5a9780-4e85-11eb-8368-2ffa26e978e6.png)
下载下来是个空包

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台报错没有

**Comment by xiaoguolong** [comment]
没报错 linux是不是还需要配置什么东西

**Comment by zhangdaiscott** [comment]
哪不清楚了，我们这里是可以的
