### ISSUE TITLE
表单提交唯一性效验是哪个地方控制呢？

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#2163]
##### 问题描述：
我现在用的是今年5月份时候的代码，因为子啊里面修改的内容比较多，没有更新最新的代码。
咨询，表单比较时，唯一性效验这个后台代码最新的版本中，代码是哪个文件中的呢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043990
