### ISSUE TITLE
想问一下ant-design-vue-jeecg\src\utils\request.js里面。this指向是Undefined

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2165]
##### 版本号：
2.2.1

##### 问题描述：
做国际化的项目，一些静态文字需要通过this.$t()的方式来动态加载，request.js显示this是undefined

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26954826/103719647-6cc6ef00-5004-11eb-87c5-fca8d5ba9e29.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这段代码没用可以删掉

**Comment by pwyGouxiong** [comment]
> 这段代码没用可以删掉

请问怎么能让它有用。。。
