### ISSUE TITLE
源码部署成功后，报表部分得功能缺失，online图表配置，online组合报表模块功能缺失

### ISSUE THREAD

**Issue by smartmingjieli** [zhangdaiscott/jeecg-boot#2166]
##### 版本号：
2.4

##### 问题描述：
报表部分得功能缺失，online图表配置，online组合报表模块功能缺失

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38684470/103735275-a7db1980-5028-11eb-91c4-5637ba744db4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
非开源内容
