### ISSUE TITLE
版本2.4.0：用IE11打开系统，一直停留在登录的加载页面。

### ISSUE THREAD

**Issue by humadivinty** [zhangdaiscott/jeecg-boot#2169]
##### 问题描述：
用IE11打开系统，一直停留在登录的加载页面。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
测试无问题
http://boot.jeecg.com

![image](https://user-images.githubusercontent.com/3162115/104288497-d8242b80-54f2-11eb-962c-e48e2e500b44.png)
