### ISSUE TITLE
2.4.0版本online表单生成的前端页面排版有问题（Tab主题一对多）

### ISSUE THREAD

**Issue by wangyan2258** [zhangdaiscott/jeecg-boot#2170]
##### 版本号：
版本号：2.4.0

##### 问题描述：
Tab主题一对多主题的表单页面排版有问题，字段名称超过5，6个字就不能完全显示，会被后面的控件遮挡

##### 截图&代码：
![image](https://user-images.githubusercontent.com/77095154/103865683-84cf6900-50ff-11eb-8f3f-35e4785fc6cd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以设置为两列的模式
