### ISSUE TITLE
切换微服后,被调用服务要求鉴权怎么办

### ISSUE THREAD

**Issue by happyzsz** [zhangdaiscott/jeecg-boot#2171]
##### 版本号：
2.4.0

##### 问题描述：
比如我B服务是由服务端后台发起的,需要调用A服务,B没持有token,就会导致调用失败.

##### 截图&代码：

后台定时任务这种情况太常见了.

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
获取当前登录的token，调用接口的时候传递token即可

**Comment by zhubinsheng** [comment]
请问解决了吗

> ##### 版本号：
> 2.4.0
> 
> ##### 问题描述：
> 比如我B服务是由服务端后台发起的,需要调用A服务,B没持有token,就会导致调用失败.
> 
> ##### 截图&代码：
> 后台定时任务这种情况太常见了.
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhubinsheng** [comment]
> 获取当前登录的token，调用接口的时候传递token即可

后台定时任务这种情况下也要去获取token再调用吗

**Comment by zhangdaiscott** [comment]
微服务之间调用免Token方案
http://doc.jeecg.com/2725212
