### ISSUE TITLE
JSelectMultiUser returnKeys 选项和账号搜索有冲突

### ISSUE THREAD

**Issue by xinwu-yang** [zhangdaiscott/jeecg-boot#2172]
##### 版本号：
2.4.1

##### 问题描述：
JSelectMultiUser returnKeys 选项和账号搜索有冲突

如果组件中要求 :returnId=true，那么组件提供的根据账号搜索用户列表也对应修改成根据id搜索了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12267648/103963406-2607ff00-5194-11eb-9266-0f83ea854155.png)

![image](https://user-images.githubusercontent.com/12267648/103963390-1ab4d380-5194-11eb-99d8-f6de32b0c08c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
你可以通过给组件设置 queryParamCode="username" 来让账号根据username去查询（一般不会根据id查询）
