### ISSUE TITLE
代码生成不了

### ISSUE THREAD

**Issue by marswon** [zhangdaiscott/jeecg-boot#2173]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/794665/103964459-797b4c80-5196-11eb-8802-b02397621a07.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确认下代码路径里面是不是有中文或者乱码

**Comment by marswon** [comment]
> 确认下代码路径里面是不是有中文或者乱码

没有中文，也没有乱码，就/Users/wangzheng/Document/mywork  这样

**Comment by marswon** [comment]
是否BigSur有文件权限？

**Comment by zhangdaiscott** [comment]
不清楚

**Comment by fengxl0** [comment]
Macbook pro big sur 可以生成代码的，如果用的是这个模块的 jeecg-boot-module-system，maven打完jar包之后，在target目录下执行 mkdir config;cp -r classes/jeecg config，然后再把代码拉起来就可以生成代码了，升级文档大佬有讲解的。
