### ISSUE TITLE
online在线开发在日志管理捕捉不到

### ISSUE THREAD

**Issue by 354752672** [zhangdaiscott/jeecg-boot#2174]
##### 截图&代码：
1.添加
![image](https://user-images.githubusercontent.com/56473652/103969961-1d1e2a00-51a2-11eb-8929-b762bcfef6f2.png)
2.删除
![image](https://user-images.githubusercontent.com/56473652/103969995-29a28280-51a2-11eb-8e33-de2d5b124c52.png)
3.查询日志管理中操作日志，无日志显示
![image](https://user-images.githubusercontent.com/56473652/103970029-3fb04300-51a2-11eb-8d7c-848bdc28119e.png)
4.online表单截图
![image](https://user-images.githubusercontent.com/56473652/103970076-56569a00-51a2-11eb-9ad1-73f921c53742.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版已经支持
