### ISSUE TITLE
消息通知缺少 系统 模板类型的实现类 

### ISSUE THREAD

**Issue by yanmaoda** [zhangdaiscott/jeecg-boot#2175]
##### 问题描述：
后台代码中只有微信，短信，邮件的实现类，没有系统类型的实现类

##### 截图&代码：

![image](https://user-images.githubusercontent.com/77142469/103985564-21f3d580-51c4-11eb-9576-d636361224c2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
系统消息不是采用这种方式，如果需要这种方式的，也可以自己实现一个
