### ISSUE TITLE
JAVA访问权限控制无效

### ISSUE THREAD

**Issue by yuanxu-xsmy** [zhangdaiscott/jeecg-boot#2177]
##### 版本号：
 2.4

##### 问题描述：
JAVA访问权限控制，取消了添加用户时的权限代码注释，然后在角色管理中不勾选当前登陆角色的用户添加权限，却发现仍然能够成功添加用户，是什么原因？

##### 截图&代码：

@RequestMapping(value = "/add", method = RequestMethod.POST)
@RequiresPermissions("user:add")  //取消注释
public Result<SysUser> add(@RequestBody JSONObject jsonObject) {}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
退出重新登录

**Comment by yuanxu-xsmy** [comment]
> 退出重新登录

我操作的是admin角色，退出登陆后仍然能够添加用户成功

**Comment by zhangdaiscott** [comment]
你加注解重启了吗

**Comment by yuanxu-xsmy** [comment]
> 你加注解重启了吗

没有，文档上没有说这些啊。不过重启服务，重新登陆后确实无法添加新用户了。建议：文档的一些操作步骤可以再详尽些，比如如何才能生效，只看核心内容修改代码有时显得稍有不足。
谢谢解答！
