### ISSUE TITLE
后端省市区ProvinceCityArea读取json文件bug

### ISSUE THREAD

**Issue by qlanto224** [zhangdaiscott/jeecg-boot#2179]
##### 版本号：
2.2.1
2.4.0

##### 问题描述：
通过spring容器来读取classpath下的静态文件,打jar包时没有问题,但是当打package时,会找不到文件,读取为null

##### 截图&代码：

`
@Component("pca")
`
`
public class ProvinceCityArea {
`
`
    @Value("classpath:static/pca.json")
`
`
    private Resource jsonData;
`
##### 解决方案

初始化方法initAreaList();
修改代码:
`
String jsonData = this.jsonRead("static/pca.json");
`

jsonRead()方法:

`
private String jsonRead(String path) {
`
`
        ClassPathResource classPathResource = new ClassPathResource(path);
`
`
        BufferedInputStream fis = null;
`
`
        try {
`
`
            fis = new BufferedInputStream(classPathResource.getInputStream());
`
`
            byte[] buffer = new byte[fis.available()];
`
`
            fis.read(buffer);
`
`
            return new String(buffer,"utf-8");
`
`
        }catch (Exception e){
`
`
            log.error("读取省市区文件失败",e);
`
`
            return "";
`
`
        }finally {
`
`
            try {
`
`
                if(null != fis){
`
`
                    fis.reset();
`
`
                    fis.close();
`
`
                }
`
`
            }catch (Exception e){
`
`
            }
`
`
        }
`
`
    }
`

**Comment by zhangdaiscott** [comment]
3Q
