### ISSUE TITLE
JEditableTable中disabledRows属性如何使用，官方文档中没有使用方式

### ISSUE THREAD

**Issue by CodeFly16** [zhangdaiscott/jeecg-boot#2180]
##### 版本号：
2.2

##### 问题描述：
disabledRows属性不知如何使用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61872730/104114505-23e2a380-5340-11eb-88e6-382c4088cc67.png)
![image](https://user-images.githubusercontent.com/61872730/104114511-2e04a200-5340-11eb-96a1-63ecb8ac2849.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
全文搜索，找例子
![image](https://user-images.githubusercontent.com/3162115/104259531-91b3da00-54bc-11eb-9658-a2602da3ad85.png)

**Comment by CodeFly16** [comment]
> 全文搜索，找例子
> ![image](https://user-images.githubusercontent.com/3162115/104259531-91b3da00-54bc-11eb-9658-a2602da3ad85.png)

![image](https://user-images.githubusercontent.com/61872730/104815040-24ea6800-584d-11eb-974f-ead691a9badd.png)
全文搜索例子，貌似是存放在了npm包中，我无法查看

**Comment by zhaozhao24011** [comment]
你好，请问你的问题现在解决了吗？我目前遇到和你相同的问题，不知道如何配置disabledrows。如果你已解决，可以指导我一下吗，谢谢
