### ISSUE TITLE
下拉联动组件相关问题

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#2181]
##### 版本号：
2.4

##### 问题描述：
使用sys_category作为数据表，存储key用的是code，显示text是name。新增没有问题，但是列表查询出来的显示都是code。

##### 截图&代码：
红色是希望的结果，绿色是实际的结果。
![image](https://user-images.githubusercontent.com/8335270/104120202-fd3c6100-536f-11eb-81ca-eaab3ea3e5f0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
online还是生成代码

**Comment by yanchenchen** [comment]
online，选用的组件是下拉联动组件：http://doc.jeecg.com/2044081

**Comment by zhangdaiscott** [comment]
收录

**Comment by yanchenchen** [comment]
online报表配置也有这个问题。查询出来是code，不是name。
这个功能什么时候发布？

**Comment by a3576419** [comment]
在线测试是正常的，不能生成代码？

**Comment by yanchenchen** [comment]
不是为了生成代码。
是使用online在线表单开发，不生成代码，直接配置使用。

**Comment by zhangdaiscott** [comment]
生成代码，目前得手工调整，此组件代码生成器支持没那么好
