### ISSUE TITLE
不同路径使用了相同的组件，发现组件内的数据是相互影响的

### ISSUE THREAD

**Issue by xys1989** [zhangdaiscott/jeecg-boot#2183]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/25168729/104260385-5dd9b400-54be-11eb-8ed5-3a1a6e0122bb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xys1989** [comment]
![image](https://user-images.githubusercontent.com/25168729/104260587-c32da500-54be-11eb-86dc-62570e58cd3a.png)

**Comment by zhangdaiscott** [comment]
数据不隔离是什么现象？

**Comment by xys1989** [comment]
> 数据不隔离是什么现象？
不同的路径使用同一个组件时，正常是这两个页面的数据相互不影响，但是因为没加这个key，第二个页面打开时，数据没有初始化，用的还是组件1的数据

**Comment by xys1989** [comment]
![image](https://user-images.githubusercontent.com/25168729/104401359-f8092d00-558e-11eb-96d9-0fb537d2fedb.png)
这个是我的测试页面   正常来说  第二个页面打开时，执行this.init() 方法   num应该是2   但是现在的现象是在组件1的基础上+1了

**Comment by xys1989** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
待分析

**Comment by accpman** [comment]
> @zhangdaiscott



> ![image](https://user-images.githubusercontent.com/25168729/104401359-f8092d00-558e-11eb-96d9-0fb537d2fedb.png)
> 这个是我的测试页面 正常来说 第二个页面打开时，执行this.init() 方法 num应该是2 但是现在的现象是在组件1的基础上+1了

在每次打开组件进行数据初始化操作呢，不是很理解内的用法

**Comment by zhangdaiscott** [comment]
你这边是不是因为路由缓存的问题？

**Comment by xys1989** [comment]
s

> 你这边是不是因为路由缓存的问题？
应该是之前没加key，然后组件不会被重新渲染

**Comment by sjlei** [comment]
这是正常的情况，vue的特性，是因为不同路由都渲染同一个组件，相当于复用组件了，组件就没有销毁再创建，即生命周期钩子函数就不会再被调用。所以就不会重新渲染。
目前我们项目里的解决方案就是在`watch.$route` 里写初始化逻辑。
![image](https://user-images.githubusercontent.com/34293221/119428948-6e3d4d80-bd40-11eb-9eff-13e03e92d548.png)
