### ISSUE TITLE
一对多导出needMerge 子表数据对应数量小于2时报错 

### ISSUE THREAD

**Issue by doudecheng** [zhangdaiscott/jeecg-boot#2186]
##### 问题描述：
一对多导出needMerge 子表数据对应数量小于2时报错.代码判断
if (list != null && list.size() > maxHeight) {
					maxHeight = list.size();
				}
当数据只有一条或者没有数据的时候导致
if (region.getNumberOfCells() < 2) {
            throw new IllegalArgumentException("Merged region " + region.formatAsString() + " must contain 2 or more cells");
        }
一直抛异常
##### 截图&代码：

![image](https://user-images.githubusercontent.com/23658062/104283692-e15dca00-54eb-11eb-81e3-ac238253c01c.png)
![image](https://user-images.githubusercontent.com/23658062/104283782-04887980-54ec-11eb-8f43-dc95e447d570.png)

**Comment by zhangdaiscott** [comment]
印象中这个问题改过了

改下autopoi依赖为
1.2.4

**Comment by doudecheng** [comment]
19:23:42.643 [main] ERROR org.jeecgframework.poi.excel.export.base.ExcelExportBase - 合并单元格错误日志：Merged region P5 must contain 2 or more cells

**Comment by doudecheng** [comment]
修改版本为1.2.4后依然报这个错

**Comment by zhangdaiscott** [comment]
说明你改的不对，这个问题很早已经处理了
![image](https://user-images.githubusercontent.com/3162115/104320971-f8b5ab00-551d-11eb-904a-fa5d86059fd3.png)

**Comment by doudecheng** [comment]
方便加个微信么？15755107583
