### ISSUE TITLE
oracle导入数据表后， 更新在线表结构无法同步数据库结构，并且无法从Oracle源数据库中加载数据

### ISSUE THREAD

**Issue by lxnnao** [zhangdaiscott/jeecg-boot#2187]
##### 版本号：
2.4

##### 问题描述：
oracle导入数据表后， 更新在线表结构无法同步数据库结构，并且无法从Oracle源数据库中加载数据

报错提示：
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
 ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM productdemandrequest WHERE 1 = 1 
 ### The error may exist in URL [jar:file:/C:/Users/liux24/.m2/repository/org/hibernate/hibernate-re/2.3.07/hibernate-re-2.3.07.jar!/org/jeecg/modules/online/cgform/mapper/xml/OnlCgformFieldMapper.xml]
 ### The error may involve org.jeecg.modules.online.cgform.mapper.OnlCgformFieldMapper.selectPageBySql-Inline
 ### The error occurred while setting parameters
 ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM productdemandrequest WHERE 1 = 1
 
 数据库同步报错：
 Unable to perform unmarshalling at line number 7 and column 20. Message: cvc-complex-type.2.4.a: Invalid content was found starting with element 'property'. One of '{"http://www.hibernate.org/xsd/orm/hbm":meta, "http://www.hibernate.org/xsd/orm/hbm":tuplizer, "http://www.hibernate.org/xsd/orm/hbm":subselect, "http://www.hibernate.org/xsd/orm/hbm":cache, "http://www.hibernate.org/xsd/orm/hbm":natural-id-cache, "http://www.hibernate.org/xsd/orm/hbm":synchronize, "http://www.hibernate.org/xsd/orm/hbm":comment, "http://www.hibernate.org/xsd/orm/hbm":id, "http://www.hibernate.org/xsd/orm/hbm":composite-id}' is expected. : origin(null)
 
Oracle源数据库中加载数据：
 nested exception is org.apache.ibatis.exceptions.PersistenceException: 
 ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM productdemandrequest2 WHERE 1 = 1 
 ### The error may exist in URL [jar:file:/C:/Users/liux24/.m2/repository/org/hibernate/hibernate-re/2.3.07/hibernate-re-2.3.07.jar!/org/jeecg/modules/online/cgform/mapper/xml/OnlCgformFieldMapper.xml]
 ### The error may involve org.jeecg.modules.online.cgform.mapper.OnlCgformFieldMapper.selectPageBySql-Inline
 ### The error occurred while setting parameters
 ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM productdemandrequest2 WHERE 1 = 1

oracle 数据库表结构示例;
  CREATE TABLE ACC_TEST.PRODUCTDEMANDREQUEST2 
   (	RECORDID VARCHAR2(14 BYTE) PRIMARY key, 
	SITE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	DIVISION VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRODUCTLINE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRODUCTIONLINENAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	CONTACTNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	DEMANDNAME VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	DEMANDSUPPLIER VARCHAR2(50 BYTE), 
	SOLUTIONTYPE VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	PROJECTMANGEMENTID VARCHAR2(50 BYTE), 
	CEA VARCHAR2(50 BYTE), 
	BUDGET VARCHAR2(50 BYTE), 
	REQUIREDCOMPLETEDATE VARCHAR2(20 BYTE), 
	ASSIGNEE VARCHAR2(50 BYTE), 
	DEMANDSHORTDESCRIPTION VARCHAR2(4000 BYTE), 
	USERNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	REMARK VARCHAR2(500 BYTE), 
	RESERVER1 VARCHAR2(50 BYTE), 
	RESERVER2 VARCHAR2(50 BYTE), 
	CREATEAT DATE, 
	UPDATEAT DATE, 
	SY VARCHAR2(100 BYTE), 
	RECEIVEDDATE VARCHAR2(20 BYTE), 
	INTERNALCOST NUMBER(*,0), 
	EXTERNALCOST NUMBER(*,0)
   )
##### 截图&代码：
![image](https://user-images.githubusercontent.com/5283992/104293415-f0974480-54f8-11eb-8399-e18a66f5f408.png)

**Comment by zhangdaiscott** [comment]
oracle什么版本
错误日志全部贴出来

**Comment by lxnnao** [comment]
问题描述及总计更新下：
1 问题：主模块配置的系统数据库为oracle12版A，在线报表开发导入数据库表使用  jeecg_database.properties中使用数据库oracle12版B。  从B中导入A中不存在的表table_a，  会发生上面的两个报错。  在A在添加table_a 后问题解决，没有报错。
总结： B数据库中的数据有偶尔会被后台取出， 虽然默认是连接A主数据库，说明 这个方面的数据源管理可能有漏洞。原因不名。建议外部导入的数据表可以指定数据库源管理。
问题2： ID 栏位是默认并且不可以被覆盖的内置栏位，外部导入数据表如果没有ID 同名栏位会被自动添加。 有的话被覆盖。
 其他内置栏位， 如create_by, create_at等不会自动添加。   ID 自动策略也是无法选择的。

**Comment by lsqGitHub716** [comment]
问题1：你的数据库连接配置和 jeecg_database.properties中的数据库信息要保持一致，否则会报错，你可以修改成一致的试试

问题2：id是我们系统目前表中必须存在的字段

**Comment by gjl2011yn** [comment]
我遇到了相同的问题用的是 19c ，把ID字段挪到第一个位置才行
![ID必须是第一个字段](https://user-images.githubusercontent.com/749010/156507740-043e48ce-b81e-4ef8-bb27-7585240e072c.png)

**Comment by bettergsh** [comment]
请问有解决吗

**Comment by bettergsh** [comment]
> 我遇到了相同的问题用的是 19c ，把ID字段挪到第一个位置才行 ![ID必须是第一个字段](https://user-images.githubusercontent.com/749010/156507740-043e48ce-b81e-4ef8-bb27-7585240e072c.png)

我用的11也遇到了这个问题

**Comment by martinzh717** [comment]
> 我遇到了相同的问题用的是 19c ，把ID字段挪到第一个位置才行 ![ID必须是第一个字段](https://user-images.githubusercontent.com/749010/156507740-043e48ce-b81e-4ef8-bb27-7585240e072c.png)

弱智的bug，迄今为止还没有修复掉@v3.6.3 | 2024-03-11
