### ISSUE TITLE
登录提示Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by Lenlyl** [zhangdaiscott/jeecg-boot#2189]
##### 版本号：
2.4.0

##### 问题描述：
可以调用贵平台的服务生产接口https://bootapi.jeecg.com登录吗，我看验证码是过了，但登录提示"Cannot read property 'show' of undefined"

##### 截图&代码：
![image](https://user-images.githubusercontent.com/10959952/104298355-d19bb100-54fe-11eb-88ff-506800b89ad8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
按道理是可以，是不是你的版本与演示环境不一致？
