### ISSUE TITLE
前端页面直接打不开，控制台报错

### ISSUE THREAD

**Issue by bourry** [zhangdaiscott/jeecg-boot#2191]
##### 问题描述：
服务端，前端正常启动，前端报错，页面一直打不开
Cannot read property 'device' of undefined

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15206859/104316471-775b1a00-5517-11eb-961a-69a1a6db22b5.png)

![image](https://user-images.githubusercontent.com/15206859/104316543-98236f80-5517-11eb-977b-226f20a793c1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
按照要求补充版本号等信息
