### ISSUE TITLE
后端启动后页面打不开，IDEA报错

### ISSUE THREAD

**Issue by Xun-xx** [zhangdaiscott/jeecg-boot#2193]
##### 问题描述：

后端启动后页面打不开，IDEA报错，执行数据库脚本，一部分成功，一部分失败。
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/60042450/104401265-c85a2500-558e-11eb-8d15-f84fee653774.png)
![图片](https://user-images.githubusercontent.com/60042450/104401281-d314ba00-558e-11eb-995a-5e0ad830a755.png)
![图片](https://user-images.githubusercontent.com/60042450/104401336-ef185b80-558e-11eb-98c0-a6ee57f36292.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
手工执行，不要通过程序
