### ISSUE TITLE
新版本代码跟教程不一样

### ISSUE THREAD

**Issue by ywuyi** [zhangdaiscott/jeecg-boot#2194]
##### 版本号：
2.4

##### 问题描述：
在github上下载的最新代码，然后按技术文档编写helloworld例子，有个权限过滤的配置，但是最新代码里面没有这部分代码？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/46707808/104414204-d3bb4980-55aa-11eb-9c01-37bfece6dac7.png)
![image](https://user-images.githubusercontent.com/46707808/104414245-ec2b6400-55aa-11eb-837e-3f2c30f45d50.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg-boot-base/jeecg-boot-base-core/org.jeecg.config.shiro.ShiroConfig
