### ISSUE TITLE
get请求失效

### ISSUE THREAD

**Issue by zhubinsheng** [zhangdaiscott/jeecg-boot#2196]
##### 版本号：
<version>2.1.2</version>

##### 问题描述：
将war放在了宝塔面板的java项目管理器中，Tomcat8，我在另个server tomcat9暂时作为apk下载服务器，当下载一次后，
我的后台程序中的一个get请求接口就出现问题了，但是我讲get请求的参数长度减少一位的时候又可以正常请求；
正常情况下，这个参数再怎么长也没有出现过问题。
跪求大佬们提供问题出现的可能原因 QAQ

##### 截图&代码：
下面是正常情况下log中的请求日志
ip - - [13/Jan/2021:15:30:17 +0800] "GET /jeecgboot/app_esp_ip/app_esp_ip_bean/selectByUUID?uuid=13 HTTP/1.1" 200 107
出问题的时候没有打印这种日志

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个接口是自己写的，得自己分析
