### ISSUE TITLE
最新2.4版本war包部署时下载不到核心包jeecg-boot-base:pom:2.4.0；

### ISSUE THREAD

**Issue by ywuyi** [zhangdaiscott/jeecg-boot#2198]
##### 版本号：
2.4

##### 问题描述：
下载的最新的代码，
war包部署时下载不到核心包jeecg-boot-base:pom:2.4.0；
1.已按技术文档更新maven地址，
2.修改pom.xml,配置了<packaging>war</packaging>，
3.注释了spring-boot-maven-plugin插件，
4.修改了 jeecg-boot-module-system/org.jeecg.JeecgSystemApplicatio文件

对jeecg-boot-module-system模块打war包提示：
[ERROR] Failed to execute goal on project jeecg-boot-module-system: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-module-system:war:2.4.0: Could not find artifact org.jeecgframework.boot:jeecg-system-local-api:jar:2.4.0 in jeecg (http://maven.jeecg.org/nexus/content/repositories/jeecg) -> [Help 1]

于是对jeecg-system-local-api模块install，提示：
[ERROR] Failed to execute goal on project jeecg-system-local-api: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-system-local-api:jar:2.4.0: Could not find artifact org.jeecgframework.boot:jeecg-boot-base-core:jar:2.4.0 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]

继续对jeecg-boot-base-core模块install，提示：
[ERROR] Failed to execute goal on project jeecg-boot-base-core: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-base-core:jar:2.4.0: Failed to collect dependencies at org.jeecgframework.boot:jeecg-boot-base-tools:jar:2.4.0: Failed to read artifact descriptor for org.jeecgframework.boot:jeecg-boot-base-tools:jar:2.4.0: Could not find artifact org.jeecgframework.boot:jeecg-boot-base:pom:2.4.0 in jeecg (http://maven.jeecg.org/nexus/content/repositories/jeecg) -> [Help 1]

切换到阿里云仓库也不行，提示：
[ERROR] Failed to execute goal on project jeecg-boot-base-core: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-base-core:jar:2.4.0: Failed to collect dependencies at org.jeecgframework.boot:jeecg-boot-base-tools:jar:2.4.0: Failed to read artifact descriptor for org.jeecgframework.boot:jeecg-boot-base-tools:jar:2.4.0: Could not find artifact org.jeecgframework.boot:jeecg-boot-base:pom:2.4.0 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]

重新对jeecg-boot-base-tools模块install，jeecg-boot-base-tools.jar能正常生成，但是再对jeecg-boot-base-core模块install还是不行，报错跟上面一样。关键还是在jeecg-boot-base吧，请问如何改？

##### 截图&代码：

![core的pom文件](https://user-images.githubusercontent.com/46707808/104497758-cdae8280-5615-11eb-9e88-01901bc24d2c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
先通过parent install
