### ISSUE TITLE
online代码生成中，数据表的默认值处理中字符串类型设为''

### ISSUE THREAD

**Issue by landcast** [zhangdaiscott/jeecg-boot#2199]
##### 版本号：
2.4.1

##### 问题描述：

online代码生成中，数据表的默认值处理中字符串类型希望生成not null default '', 如果在默认值的表单上不输入，则没有default ''部分

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成后的代码，暂时不支持默认值的生成
