### ISSUE TITLE
我的部门-人员编辑bug

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#220]
##### 版本号：
jeecg-boot 2.0.1

##### 问题描述：
在我的部门页面，对已有的用户进行编辑提交的时候，后台发生报错，显示操作失败。
这个操作是当`用户录入`之后，再进行该`用户编辑`或者其他`用户编辑`，发生报错。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27263086/59731505-fa06ef00-9278-11e9-9b12-4549a39916c0.png)
![image](https://user-images.githubusercontent.com/27263086/59731515-01c69380-9279-11e9-982e-a3290144710b.png)

**Comment by ileadall42** [comment]
#202 这里好像提到了，的确要刷新之后才可以进行编辑.

**Comment by zhangdaiscott** [comment]
下个版本修复
