### ISSUE TITLE
增强问题

### ISSUE THREAD

**Issue by haozhangzh** [zhangdaiscott/jeecg-boot#2200]
##### 问题描述：
按照官方给定的文档测试“JS增强”以及“自定义按钮”，配置完成之后，进行功能测试，跟预期一样，所见即所得。但【代码生成】之后的页面上却没有“自定义按钮”和“JS增强”逻辑。不知道是不是我什么地方没有操作对
另外，官方是否有将前端自定义的组件打成可直接引用的类库包

##### 截图&代码：
如下两张图是在online开发上做功能测试时的情形，自定义按钮有显示，而且也能满足预期
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/11895362/104567243-8b268d80-5689-11eb-9bd6-ce9dfd99b926.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11895362/104567310-9da0c700-5689-11eb-9834-8baafd94c867.png">

下图是【生成代码】后测试情形，没有看到自定义按钮
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/11895362/104567673-00925e00-568a-11eb-9b8b-ac522d777300.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持自定义按钮和增强的生成
