### ISSUE TITLE
部门表太大导致的问题

### ISSUE THREAD

**Issue by wangleigithub** [zhangdaiscott/jeecg-boot#2204]
##### 版本号：
2.4.0

##### 问题描述：
部门表数据量太大，层次太多的时候，涉及到部门表的模块都会有问题
##### 截图&代码：
代码中涉及部门的模块，一般都是拉去整棵树，但是整棵树数据量巨大(>50W)的时候，就基本出不来结果了，希望优化

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
具体那个功能点？

**Comment by wangleigithub** [comment]
用户管理-部门选择，部门管理

**Comment by zhangdaiscott** [comment]
已经实现，异步加载树部门管理，下个版本发布
