### ISSUE TITLE
插件市场下载的文件是损坏的

### ISSUE THREAD

**Issue by liangdtels** [zhangdaiscott/jeecg-boot#2206]
##### 版本号：
1.0

##### 问题描述：
插件市场下载的文件是损坏的

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个插件？

**Comment by liangdtels** [comment]
所有免费的插件，比如摇一摇，刮刮乐，发红包这些插件------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JEECG开源社区&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月18日(星期一) 上午9:44
收件人:&nbsp;&quot;zhangdaiscott/jeecg-boot&quot;<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;&quot;liangdtels&quot;<1713354254@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 插件市场下载的文件是损坏的 (#2206)

**Comment by zhangdaiscott** [comment]
好了
