### ISSUE TITLE
docker中的容器跑起来了，http://localhost:8080/jeecg-boot/doc.html不能访问

### ISSUE THREAD

**Issue by harryheng** [zhangdaiscott/jeecg-boot#2208]
##### 版本号：
master

##### 问题描述：

docker中的容器跑起来了，http://localhost:8080/jeecg-boot/doc.html不能访问
##### 截图&代码：
该网页无法正常运作localhost 未发送任何数据。
ERR_EMPTY_RESPONSE
-
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/104901011-c8578c00-59b7-11eb-832c-b4d38c23fcae.png)
