### ISSUE TITLE
idea运行没问题，打包成jar包运行时代码生成不了

### ISSUE THREAD

**Issue by lixz509** [zhangdaiscott/jeecg-boot#2209]
##### 版本号：
2.4.0分布式

##### 问题描述：
在idea中运行时没问题，打包成jar包，运行jar包后代码生成生成出来的代码是空白的，且后台没有报错。
提示是代码生成 成功了，但目录下没有，下载下来也没有

##### 截图&代码：
![111](https://user-images.githubusercontent.com/48518263/104887239-e050f080-5962-11eb-99f6-2f8460deed3b.png)
![222](https://user-images.githubusercontent.com/48518263/104887253-e47d0e00-5962-11eb-92e6-13d4de4421bd.png)

**Comment by lixz509** [comment]
有的，并且后台还有打印出模板，但生成的就是空白

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043922

**Comment by lixz509** [comment]
同样是在本地测试的，直接运行可以，打包成jar包不行，都有打印模板。 jar包有打印以下: 
com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl@510cc6e5
2021-01-18 16:57:47.468 [http-nio-7001-exec-1] ?[34mINFO ?[0;39m ?[36mo.j.codegenerate.generate.impl.CodeGenerateOne:119?[0;39m - load template data: {primaryKeyPolicy=java.lang.String, serialVersionUID=5190949
100388435263, entityPackage=1111, entityName=Station, primaryKeyField=id, columns=[{"fieldDbName":"code","fieldName":"code","filedComment":"宸ヤ綅缂栧彿","fieldType":"java.lang.String","fieldDbType":"string","c
lassType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"N","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldSho
wType":"text","fieldOrderNum":"7","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dic
tText":""}, {"fieldDbName":"name","fieldName":"name","filedComment":"宸ヤ綅鍚嶇О","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength"
:"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"8","isKey":"N","isShow":"Y","isShowList"
:"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"machine_code","fieldName":"machineCode","fi
ledComment":"璁惧缂栧彿","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fi
eldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"9","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null
","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"machine_type","fieldName":"machineType","filedComment":"璁惧绫诲瀷","fieldType":"java.lang.String
","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null",
"fieldDefault":"","fieldShowType":"text","fieldOrderNum":"10","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictF
ield":"","dictTable":"","dictText":""}, {"fieldDbName":"device_code","fieldName":"deviceCode","filedComment":"杞﹂棿瀹濈紪鍙?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_
row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum
":"11","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":
"department","fieldName":"department","filedComment":"宸ヤ綔缁?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"sel_depart","classType_row":"sel_depart","optionType":"","charmaxLength":"","pr
ecision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"sel_depart","fieldOrderNum":"12","isKey":"N","isShow":"Y","isShowList"
:"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"mobile_card","fieldName":"mobileCard","file
dComment":"鐗╄仈鍗″彿","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","field
Length":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"13","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null",
"sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"file","fieldName":"file","filedComment":"鏂囦欢","fieldType":"java.lang.String","fieldDbType":"string
","classType":"file","classType_row":"file","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fiel
dShowType":"file","fieldOrderNum":"14","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":""
,"dictText":""}], tableVo={"tableName":"station","ftlDescription":"宸ヤ綅琛?,"primaryKeyPolicy":"null","sequenceCode":"null","entityPackage":"1111","entityName":"Station","fieldRowNum":"1","searchFieldNum":"-1"
,"fieldRequiredNum":"4"}, originalColumns=[{"fieldDbName":"id","fieldName":"id","filedComment":"涓婚敭","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionTyp
e":"","charmaxLength":"","precision":"null","scale":"null","nullable":"N","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"1","isKey":"Y","isS
how":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"Y","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"create_by","fieldName"
:"createBy","filedComment":"鍒涘缓浜?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullab
le":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"2","isKey":"N","isShow":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaul
tVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"create_time","fieldName":"createTime","filedComment":"鍒涘缓鏃ユ湡","fieldType":"java.ut
il.Date","fieldDbType":"Date","classType":"datetime","classType_row":"datetime","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValid
Type":"null","fieldDefault":"","fieldShowType":"datetime","fieldOrderNum":"3","isKey":"N","isShow":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode"
:"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"update_by","fieldName":"updateBy","filedComment":"鏇存柊浜?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"text","clas
sType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOr
derNum":"4","isKey":"N","isShow":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbN
ame":"update_time","fieldName":"updateTime","filedComment":"鏇存柊鏃ユ湡","fieldType":"java.util.Date","fieldDbType":"Date","classType":"datetime","classType_row":"datetime","optionType":"","charmaxLength":"","
precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"datetime","fieldOrderNum":"5","isKey":"N","isShow":"N","isShowList":
"N","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"sys_org_code","fieldName":"sysOrgCode","file
dComment":"鎵€灞為儴闂?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fiel
dLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"6","isKey":"N","isShow":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaultVal":"null",
"sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"code","fieldName":"code","filedComment":"宸ヤ綅缂栧彿","fieldType":"java.lang.String","fieldDbType":"
string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"N","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":""
,"fieldShowType":"text","fieldOrderNum":"7","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTabl
e":"","dictText":""}, {"fieldDbName":"name","fieldName":"name","filedComment":"宸ヤ綅鍚嶇О","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","char
maxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"8","isKey":"N","isShow":"Y","i
sShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"machine_code","fieldName":"machin
eCode","filedComment":"璁惧缂栧彿","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullabl
e":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"9","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","default
Val":"null","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"machine_type","fieldName":"machineType","filedComment":"璁惧绫诲瀷","fieldType":"java.l
ang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidTyp
e":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"10","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"sing
le","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"device_code","fieldName":"deviceCode","filedComment":"杞﹂棿瀹濈紪鍙?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"text","
classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fie
ldOrderNum":"11","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"Y","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fie
ldDbName":"department","fieldName":"department","filedComment":"宸ヤ綔缁?,"fieldType":"java.lang.String","fieldDbType":"string","classType":"sel_depart","classType_row":"sel_depart","optionType":"","charmaxLeng
th":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"sel_depart","fieldOrderNum":"12","isKey":"N","isShow":"Y","i
sShowList":"Y","isQuery":"Y","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"mobile_card","fieldName":"mobileC
ard","filedComment":"鐗╄仈鍗″彿","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":
"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"13","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVa
l":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"file","fieldName":"file","filedComment":"鏂囦欢","fieldType":"java.lang.String","fieldDbTyp
e":"string","classType":"file","classType_row":"file","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault
":"","fieldShowType":"file","fieldOrderNum":"14","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dic
tTable":"","dictText":""}], bussiPackage=org.jeecg.modules.demo, tableName=station}
ation}

**Comment by lixz509** [comment]
http://doc.jeecg.com/2043922这个试过了，还是不行...

**Comment by lixz509** [comment]
jar包后台打印
load template from templateRootDir 和 ----- jeecg-boot ---- generate  code  success =======> 表名：
中间的这段《
[generate]	 template:default\one\java\${bussiPackage}\${entityPackage}\controller\${entityName}Controller.javai ==>
》没有打印出来，其余正常

**Comment by zhangdaiscott** [comment]
模板没找到吧，仔细看这个文档
http://doc.jeecg.com/2043922

**Comment by lixz509** [comment]
config文件 是文件还是文件夹?文件夹的话我试过把jeecg目录下的那几个文件和文件夹都放进去，没效果，生成路径一直是E:\workspace-ui\jeecg-boot-framework\jeecg-boot-module-demo。文件的话，我试过在里面写入jeecg的路径，也没生效。
