### ISSUE TITLE
单表模型代码生成器运行时报错

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#221]
##### 版本号：
2.0.1

##### 问题描述：
单表模型代码生成器运行时报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31814666/59733628-21fa5080-9281-11e9-80a7-af2d3aff5cc4.png)
![image](https://user-images.githubusercontent.com/31814666/59733648-2fafd600-9281-11e9-91d3-0cd63146bf6f.png)

**Comment by zhangdaiscott** [comment]
jeecg-boot-module-system/src/main/resources/jeecg/jeecg_database.properties
看看这个配置文件在不在，有没有编译到class里面
