### ISSUE TITLE
移动端查询列表左右滑动字段显示不全

### ISSUE THREAD

**Issue by smallayu** [zhangdaiscott/jeecg-boot#2212]
![image](https://user-images.githubusercontent.com/61266030/104925552-f77ef500-59d9-11eb-97af-75c6ec8de439.png)

**Comment by zhangdaiscott** [comment]
可以设置成左右拖动

**Comment by smallayu** [comment]
左右是可以滑动的，但是左右滑到头吗，有几个字段在后面没显示出来，移动端自适应会出现这种情况，pc端全部显示
