### ISSUE TITLE
【online表单开发】popup如何使用online报表的动态参数

### ISSUE THREAD

**Issue by yanchenchen** [zhangdaiscott/jeecg-boot#2213]
##### 版本号：

2.4
##### 问题描述：

看到文档 online报表可以支持动态参数http://doc.jeecg.com/2044149，不清楚这种动态参数能否在online表单开发的popup中使用？
举例来说，
online报表地址为：/online/cgreport/***?sex=${sex}。
在线表单中有选择控件（对应字段为 sex）和 popup控件（数据来自以上报表/online/cgreport/***?sex=${sex}）
要实现popup的数据会根据sex的选择进行动态的联动

如何实现这个功能？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044000
