### ISSUE TITLE
控件默认值显示不正确，#{sysUserName}，没有做转换

### ISSUE THREAD

**Issue by fengxl0** [zhangdaiscott/jeecg-boot#2214]
##### 版本号：
JeecgBoot Version: 2.4.0

##### 问题描述：
Online表单开发，新增表创建人字段设置控件默认值是填#{sysUserName},功能测试时控件可以正常默认值（登录用户名），但是通过生成的代码做添加操作时显示还是#{sysUserName}，没有做转换

##### 截图&代码：
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/16396025/105038234-07f6a480-5a9a-11eb-89e7-7a8f2fa48a60.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的，生成代码，暂时不支持

**Comment by lcy-132056117** [comment]
希望可以尽早加上此功能,加油!
