### ISSUE TITLE
BindingResult无法使用

### ISSUE THREAD

**Issue by yangwen27** [zhangdaiscott/jeecg-boot#2219]
##### 版本号：
2.4

##### 问题描述：

在Controller中使BindingResult 获取参数检验结果的时候，在AutoLogAspect中记录日志的时候会报错
write javaBean error, fastjson version 1.2.75, class org.springframework.validation.BeanPropertyBindingResult, fieldName : 1, write javaBean error, fastjson version 1.2.75, class org.springframework.beans.GenericTypeAwarePropertyDescriptor, fieldName : 4",

##### 截图&代码：

  @PostMapping(value = "/syncShop")
    public Result<?> AddShop(@Valid ShopSyncRequest request,BindingResult bindingResult) {
        if(bindingResult.hasErrors()){
            return Result.error(bindingResult.getFieldError().getDefaultMessage());
        }
        return shopSyncService.addShop(request);

    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请把详细的错误日志贴一下

**Comment by yangwen27** [comment]
其原因是在jeecg-boot/jeecg-boot-base/jeecg-boot-base-core/src/main/java/org/jeecg/common/aspect/AutoLogAspect.java 中 使用JSONObject.toJSONString(arguments, profilter); 序列化请求的参数，而BindingResult 是支持序列化的。我增加了BindingResult参数的过滤就好了。
![image](https://user-images.githubusercontent.com/5896222/106681853-4e044a00-65fc-11eb-939f-3e7bbe680f06.png)

**Comment by accpman** [comment]
已采纳
