### ISSUE TITLE
多页签模式下，菜单切换的时候会刷新页面

### ISSUE THREAD

**Issue by cooooode** [zhangdaiscott/jeecg-boot#222]
##### 版本号：
2.0.1 版本

##### 问题描述：
多页签模式下，菜单切换的时候会刷新页面，是因为vue的路由 不是 keep-alive，具体是因为下图的代码，没有获取到 keepAlive
![image](https://user-images.githubusercontent.com/31137050/59745458-70224a80-92a7-11e9-888f-73abe8c2d40f.png)

我暂时这么解决的，把判断删掉了
<template>
  <keep-alive>
    <router-view />
  </keep-alive>
</template>

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31137050/59745309-1d489300-92a7-11e9-8f1b-8244bb461932.png)

**Comment by cooooode** [comment]
![image](https://user-images.githubusercontent.com/31137050/59838002-cca56880-9380-11e9-953d-b485ead08e94.png)
建议规范引入less文件，在某种情况外部样式不起作用。上个留言我直接删除判断keepAlive才发现的

**Comment by becky1992** [comment]
试过，确实可以，这样页面切来切去数据不会一直在刷新了。打印了一下，组件并没有destroyed销毁了  赞

**Comment by zhangdaiscott** [comment]
收录，感谢，下个版本我们会给菜单增加一个字段，是否路由缓存  keepAlive

**Comment by zhangdaiscott** [comment]
新版菜单已经增加了 “是否缓存” 字段，请更新代码
