### ISSUE TITLE
在https情况下参数中包含特殊字符会报错：404

### ISSUE THREAD

**Issue by renmengkai** [zhangdaiscott/jeecg-boot#2220]
##### 版本号：
     系统版本：JEECG-BOOT  2.4.0
     在线开发模块："@jeecg/antd-online-mini": "2.4.0-beta4"

##### 问题描述：
     在https情况下访问在线开发模块的SQL解析功能时报错（系统中的通病，特殊字符未处理）：404，在修改sql参数（将sql中空格转换为的“+”替换为“%20”）之后才可成功访问返回正确结果。http情况下没有问题。

##### 截图&代码：
     
![image](https://user-images.githubusercontent.com/31378513/105466611-71abc400-5ccf-11eb-85d1-9488d5e45791.png)
![image](https://user-images.githubusercontent.com/31378513/105466652-7ff9e000-5ccf-11eb-882b-5223c3e7a096.png)
![image](https://user-images.githubusercontent.com/31378513/105466661-84be9400-5ccf-11eb-8fec-3143fb2c61b3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by renmengkai** [comment]
在 axios 拦截器配置中增加get请求的参数encdode就可以了，代码如下：
```javascript
    // get参数编码
    let url = config.url
    if (config.method === 'get' && config.params) {
      url += '?'
      let keys = Object.keys(config.params)
      for (let key of keys) {
        url += `${key}=${encodeURIComponent(config.params[key])}&`
      }
      url = url.substring(0, url.length - 1)
      config.params = {}
    }
    config.url = url
```
## 请更新下 "@jeecg/antd-online-mini": "2.4.0-beta4" axios的请求配置

**Comment by africaadonis** [comment]
https环境下online报表还是存在此问题，点击【SQL解析】或查询日期时间中间有空格的时候，还是存在此问题

**Comment by zhangdaiscott** [comment]
用附件覆盖本地前台的静态资源试试，提醒：这个是最新版本2,.4.2前端

**Comment by renmengkai** [comment]
> [OnlineForm.umd.min.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5909510/OnlineForm.umd.min.zip)
> 
> ant-design-vue-jeecg\node_modules@jeecg\antd-online-mini\dist
> 
> 用附件覆盖本地前台的静态资源试试，提醒：这个是最新版本2,.4.2前端

之前就试过将@jeecg\antd-online-mini升到2.4.22-beta最新版本，没有效果。

**Comment by zhangdaiscott** [comment]
附件包不好使？

**Comment by renmengkai** [comment]
> 附件包不好使？
> ![image](https://user-images.githubusercontent.com/3162115/109957460-ec7ceb80-7d1f-11eb-8185-c9af041d95c4.png)

是的，尝试后不好使

**Comment by zhangdaiscott** [comment]
如何附件包不好使，说明你提供的写法有问题，附件包就是按照你的写法改造打包的

**Comment by renmengkai** [comment]
> 如何附件包不好使，说明你提供的写法有问题，附件包就是按照你的写法改造打包的

项目中的所有访问在https情况下都有这个问题。
除了这个“在线报表”模块之外，其他部分用我的方式更改后都可以正常访问，应该是你的附件包改的有问题，之后你们在https环境下部署时碰到这个问题再说吧。
