### ISSUE TITLE
数据库同步问题

### ISSUE THREAD

**Issue by CenMinghao** [zhangdaiscott/jeecg-boot#2221]
##### 版本号：
2.3

##### 问题描述：
本地环境有两个相似的数据库(假设数据库A:project_manager;数据库B:project_manager_temp1)，里面有个project表，其中数据库A有del_reson字段，数据库B没有del_season，当我在使用连接数据库B的系统在Online表单开发页面修改表后，点击同步按钮，会报异常:java.sql.SQLSyntaxErrorException: Can't DROP 'del_reason'; check that column/key exists

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29631645/105563068-c3982c80-5d57-11eb-9a96-18d2cf517f0c.png)
![image](https://user-images.githubusercontent.com/29631645/105563185-1a9e0180-5d58-11eb-9561-a146c21d2c55.png)

原因应该是检测到数据库存在del_reason这个字段，而提交的表单没有del_reason字段，因此系统判断需要删除del_reason字段，但实际上数据库B没有del_reason字段，因此提示删除失败。
请问为什么会检测到del_reason字段，是不是读到了数据库A？但是我检查了整个代码的数据库连接配置，能确定都已改成数据库B

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版2.4+已经处理了此问题
