### ISSUE TITLE
屏幕适配

### ISSUE THREAD

**Issue by xiangxutao** [zhangdaiscott/jeecg-boot#2224]
##### 版本号：
2.4.2

##### 问题描述：
按钮超出没有适应屏幕换行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52102546/105682932-03b10800-5f2e-11eb-879e-0742414f85ae.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
已修复
