### ISSUE TITLE
locale change to english

### ISSUE THREAD

**Issue by dpnkrg** [zhangdaiscott/jeecg-boot#2226]
##### 版本号：
How to Change project front end to English?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
Sorry, there is no simple method now. It needs to be changed manually

**Comment by dpnkrg** [comment]
Hi @zhangdaiscott, 

Steps?


I tried following the steps was provided in the documentation but the changes are didn't reflect.
