### ISSUE TITLE
绕过验证码漏洞

### ISSUE THREAD

**Issue by dangzhenghui1985** [zhangdaiscott/jeecg-boot#2227]
##### 版本号：

2.4.2
##### 问题描述：
登录验证码存在漏洞， 我输入了正确的验证码，然后不停输入错误的密码进行尝试，这个验证码每次都是一个不会失效，
这样就会被人利用暴力破解，绕过验证码无限尝试。直到尝试成功都是同一个图片验证码

##### 截图&代码：

![image](https://user-images.githubusercontent.com/16914422/105782536-b2e1f380-5faf-11eb-9cfe-4b3ad2f117b3.png)
![image](https://user-images.githubusercontent.com/16914422/105782595-cb520e00-5faf-11eb-9f35-b55702aefd87.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by dangzhenghui1985** [comment]
![1611620748(1)](https://user-images.githubusercontent.com/16914422/105782919-47e4ec80-5fb0-11eb-8f66-6b27a69acff0.jpg)
![1611620775(1)](https://user-images.githubusercontent.com/16914422/105782928-49aeb000-5fb0-11eb-895c-4d3ab6dbde13.jpg)

**Comment by galaxist** [comment]
这不应该在nginx上配置直接封ip吗？

**Comment by dangzhenghui1985** [comment]
正常的流程应该是你用户名密码 和验证码输完 如果密码错误，验证码必须要在重新获取 然后在输入账号密码才能验证密码登录是否正确，现在的情况这一个验证码可以用到死

**Comment by qianlei0007** [comment]
可以自己改一下。 密码错误，刷新一下验证码

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
