### ISSUE TITLE
集成xxl-job-2.2.0之后，注解没有删掉，导致启动报端口冲突

### ISSUE THREAD

**Issue by changruhe** [zhangdaiscott/jeecg-boot#2228]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37977711/105792660-b8950480-5fc2-11eb-9e5b-249d5880e228.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3q

**Comment by der20044** [comment]
这样好像也不行，第一个服务开启后第二个服务开始还是会报 Address already in use: bind错误。求解。。

**Comment by wzsyanly** [comment]
> 这样好像也不行，第一个服务开启后第二个服务开始还是会报 Address already in use: bind错误。求解。。

把nacos配置列表里jeecg-dev.yaml文件中jeecg.xxljob下的配置删了，然后把删掉的内容在每个独立的服务中单独配置，每个服务配置上不同的port。  实测就算JobHandler的名字一样，也可以分别在不同的服务中独立定时运行

**Comment by zhangdaiscott** [comment]
已经修复

**Comment by blowing-in-the-wind** [comment]
> 
> 
> > 这样好像也不行，第一个服务开启后第二个服务开始还是会报 Address already in use: bind错误。求解。。
> 
> 把nacos配置列表里jeecg-dev.yaml文件中jeecg.xxljob下的配置删了，然后把删掉的内容在每个独立的服务中单独配置，每个服务配置上不同的port。 实测就算JobHandler的名字一样，也可以分别在不同的服务中独立定时运行

请教下基于nacos配置的话怎么做，如何实现在独立的服务里使用不同的配置

**Comment by blowing-in-the-wind** [comment]
> 
> 
> > 这样好像也不行，第一个服务开启后第二个服务开始还是会报 Address already in use: bind错误。求解。。
> 
> 把nacos配置列表里jeecg-dev.yaml文件中jeecg.xxljob下的配置删了，然后把删掉的内容在每个独立的服务中单独配置，每个服务配置上不同的port。 实测就算JobHandler的名字一样，也可以分别在不同的服务中独立定时运行

@wzsyanly 请教下基于nacos配置的话怎么做，如何实现在独立的服务里使用不同的配置
