### ISSUE TITLE
excel导出 夺表关联的时候 如果连解表删除数据 会导出数据库存在内容

### ISSUE THREAD

**Issue by FXXSIX** [zhangdaiscott/jeecg-boot#2229]
##### 版本号：2.3.0
已经切换成微服务 开发 jeecg-boot

##### 问题描述：
实体类以sys__user例子(只想知道是不是自己得问题  测试sys_user表也这样了就不是自己问题)  属性 例如 性别    
@Excel(dicCode="sex",name="性别")
private Integer sex;

我在数据库中 更改掉 sex 数据为8时候   导出 结果也变成8

数据库内容
id  username   realname  sex
1   admin        管理员     1
2   test            测试         8

导出excel 内容
用户信息 表
               导出人:admin
账号     真实姓名     性别
admin   管理员        男
test      测试             8

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by galaxist** [comment]
不，这就是你的问题，请自己查看开发文档，关于 
>@Excel(dicCode="sex",name="性别")
中的dictCode部分。

**Comment by FXXSIX** [comment]
> 不，这就是你的问题，请自己查看开发文档，关于
> 
> > @Excel（dicCode =“ sex”，name =“性别”）
> > 中的dictCode部分。
q请问 我的问题你看明白了？ 不是导出字典 失败 是数据库数据更改掉后没有导出字典     而且我看了一下文档 文档里面导出字典跟我的问题不一样
以系统表 为例子    sysy_user有一个性别字段 我数据库存入 12  他导出会按照男女导出  但是我存入8  字典是没有的 他会导出8  直接导出8这个数据库存在的数据并没有导出空

**Comment by galaxist** [comment]
你知不知道dicCode =“ sex”对应的数据字典怎么配置，而且你的8对应是啥？

**Comment by FXXSIX** [comment]
> 你知不知道dicCode =“ sex”对应的数据字典怎么配置，而且你的8对应是啥？

我知道sex 怎么配置的 ，他不是有个value 和text吗  数据库存1  或者2  前面展示男女 但是我把数据库数据改掉了8 ，他没对应上 我觉得应该展示空，结果没展示空，所以我题出了这个问题，因为我觉得这是个问题  在你们看来不是问题  那我就没问题了

**Comment by galaxist** [comment]
我以前看，这里是有缓存的，如果你在数据库直接改，可能缓存还没到过期时间，所以有问题。
