### ISSUE TITLE
国际化建议用以前的JEECG方式，方便快捷，可以在线修改

### ISSUE THREAD

**Issue by liujx2016** [zhangdaiscott/jeecg-boot#2230]
##### 问题描述：国际化实现，包括前端和后端，目前官方提供的解决方案，实现不太方便，且只实现了前端的国际化，后端应该没有。前端的国际化方式不太方便。
建议：按以前JEECG的国际方式，将翻译保存到数据库。这样可以在线修改，方便快捷。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecgboot暂时不打算默认做国际化，老jeecg因为做国际化有一些性能牺牲，也存在有点重的问题，所以需要的话，只能自己改造了
