### ISSUE TITLE
有图表的报表导出时，图表打印丢失

### ISSUE THREAD

**Issue by Pace2Car** [zhangdaiscott/jeecg-boot#2231]
##### 版本号：
2.4.2

##### 问题描述：
有图表的报表导出时，图表打印丢失

如截图所示，报表设计器中，第一页有一个表格和一个图表，第二页有一个环形图

导出为pdf时，文档中 仅正确导出了第一页内容，第二页文档为空白页

希望能够解答出现原因或者修复此bug，感谢。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37339007/105810864-a75def00-5fe6-11eb-8079-22c542ee143d.png)
![image](https://user-images.githubusercontent.com/37339007/105811041-f572f280-5fe6-11eb-8b5b-be4766dff86d.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
已修复 正式版1.1.05++ 会发布
