### ISSUE TITLE
关于 token 命名问题

### ISSUE THREAD

**Issue by x522491416** [zhangdaiscott/jeecg-boot#2232]
##### 版本号：
2.4.0

##### 问题描述：
当前token 命名方式，导致只能用token 解密获取用户名，而不能通过用户名清除redis的token，比如踢用户下线会因为查找不到token导致无法实现。目前系统是冻结方案是修改status值，在token校验时抛出异常，局限性太强

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yichengxian** [comment]
> 收录

在cas源码中CasClientController设置失效时间如下，是不是太过草率？
// 设置超时时间
	 		redisUtil.set(CommonConstant.PREFIX_USER_TOKEN + token, token);
	 		redisUtil.expire(CommonConstant.PREFIX_USER_TOKEN + token, JwtUtil.EXPIRE_TIME*2 / 1000);

**Comment by zhangdaiscott** [comment]
在线用户管理和踢掉用户功能已经实现，下个版本发布
