### ISSUE TITLE
建议文档开放编辑功能，支持通过 Pull requests 完善文档

### ISSUE THREAD

**Issue by jk2K** [zhangdaiscott/jeecg-boot#2233]
##### 问题描述：
![image](https://user-images.githubusercontent.com/4025839/105813708-34a34280-5feb-11eb-8ba4-b8e461e8d910.png)

有错字，应该是 `http://localhost:8080/jeecg-boot/test/jeecgDemo/hello`

建议像其他开源项目一样，页面可以编辑，跳到 github 页面，合并 PR 后，自动更新文档

参考项目

- [VuePress 文档](https://vuepress.vuejs.org/zh/guide/#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%98%AF)

![image](https://user-images.githubusercontent.com/4025839/105813885-79c77480-5feb-11eb-8001-57f3ab827abd.png)

**Comment by zhangdaiscott** [comment]
3q  暂时不放开，放开参与的人也不多
