### ISSUE TITLE
JVxeTable 如何动态添加columns

### ISSUE THREAD

**Issue by lvdong** [zhangdaiscott/jeecg-boot#2235]
##### 版本号：
2.4

##### 问题描述：
JVxeTable 如何动态添加columns,直接操作columns好像没有效果，

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
请详细描述一下你的操作步骤和遇到的问题

**Comment by lsqGitHub716** [comment]
请详细描述一下你要实现的功能和遇到的问题
