### ISSUE TITLE
此方法标注弃用，有其他的替代方法吗？

### ISSUE THREAD

**Issue by smt2235** [zhangdaiscott/jeecg-boot#2237]
##### 版本号：
2.4.1

##### 问题描述：
	@Deprecated
	public List<DictModel> queryTableDictItemsByCode(@Param("table") String table,@Param("text") String text,@Param("code") String code);
此方法标注弃用，有其他的替代方法吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
org.jeecg.common.system.api.ISysBaseAPI#queryTableDictItemsByCode
