### ISSUE TITLE
最后一页中分页删除问题

### ISSUE THREAD

**Issue by mbh1210554992** [zhangdaiscott/jeecg-boot#2239]
##### 问题描述：分页删除问题。
在表格中，当最后一页只有一项时，删除这一项，会重新查询分页数据，这时查询到的并不是前一页的数据，而是空（相当于还是查询了最后一页的数据，但这是最后一页已经没有数据了，应该查询前一页的数据）

##### 截图&代码：
![QQ截图20210127151651](https://user-images.githubusercontent.com/49233247/105956407-b7430500-60b2-11eb-95b2-4e25bba42a55.png)
本次删除第二页最后一个数据后，直接会显示无数据。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by x522491416** [comment]
修改 /src/mixins/JeecgListMixin.js
batchDel和 handleDelete


batchDel: function () {
      if(!this.url.deleteBatch){
        this.$message.error("请设置url.deleteBatch属性!")
        return
      }
      if (this.selectedRowKeys.length <= 0) {
        this.$message.warning('请选择一条记录！');
        return;
      } else {
        var ids = "";
        for (var a = 0; a < this.selectedRowKeys.length; a++) {
          ids += this.selectedRowKeys[a] + ",";
        }
        var that = this;
        this.$confirm({
          title: "确认删除",
          content: "是否删除选中数据?",
          onOk: function () {
            that.loading = true;
            deleteAction(that.url.deleteBatch, {ids: ids}).then((res) => {
              if (res.success) {
                that.$message.success(res.message);
                if(that.ipagination.total%that.ipagination.pageSize===this.selectedRowKeys.length){
                  that.loadData(this.ipagination.current===1?this.ipagination.current:this.ipagination.current-1);
                }else{
                  that.loadData();
                }
                that.onClearSelected();
              } else {
                that.$message.warning(res.message);
              }
            }).finally(() => {
              that.loading = false;
            });
          }
        });
      }
    },
    handleDelete: function (id) {
      if(!this.url.delete){
        this.$message.error("请设置url.delete属性!")
        return
      }
      var that = this;
      deleteAction(that.url.delete, {id: id}).then((res) => {
        if (res.success) {
          that.$message.success(res.message);
          if(that.ipagination.total%that.ipagination.pageSize===1){
            that.loadData(this.ipagination.current===1?this.ipagination.current:this.ipagination.current-1);
          }else{
            that.loadData();
          }
        } else {
          that.$message.warning(res.message);
        }
      });
    },

**Comment by zhangdaiscott** [comment]
已经修复了，下个版本发布
