### ISSUE TITLE
AutoPOI jar 找不到模板

### ISSUE THREAD

**Issue by qianlei0007** [zhangdaiscott/jeecg-boot#2241]
jeecgboot  2.4.0  版本号：
问题描述：  TemplateExportParams params=new TemplateExportParams("c:\\dev\\te.xls");
模板导出，依旧有找不到模板的问题。

 截图&代码：

java.io.FileNotFoundException: class path resource [c:/dev/te.xls] cannot be opened because it does not exist

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请参考这个类，我们测试没问题
[DaoChuTest.zip](https://github.com/zhangdaiscott/jeecg-boot/files/5892671/DaoChuTest.zip)
