### ISSUE TITLE
用online报表配置设计的报表，每页会多出一条空行，导致分页总数合计不对

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/jeecg-boot#2242]
##### 版本号：
 2.4.2

##### 问题描述：
1、用online报表配置设计的报表，每页会多出一条空行，导致分页总数合计不对，不确定是在列加了合计之后或大数据量查询的时候
2、日期时间类型的字段，按范围查询时，宽度太小了
3、数据量大导致导出Excel失败
4、非键值字典的下拉框取值，只显示本本页内的数据值

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40649464/105996376-32bdaa00-60e5-11eb-9966-3f80d334f3f1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by africaadonis** [comment]
列加了合计之后或大数据量查询的时候
	通过ref连接过去的数据不对

**Comment by africaadonis** [comment]
再次测试确认，通过A页面ref至B页面，如果A页面中加了合计，那么跳转到B页面后，会导致B页面的分页不对，比如每页10条，其实会有9条数据+1条空行，导致总页数不对。

**Comment by africaadonis** [comment]
再追加一个问题：
被ref的页面排序后，点击浏览器的回退按钮之后，查询结果为空。或在ref调用页面共有2页，选了第二页，被ref的页面只有一页，那么ref之后，会继承分页参数，导致第二页查询结果为空

**Comment by lsqGitHub716** [comment]
1.非键值字典的下拉框取值，只显示本本页内的数据值？这个你是怎么设置的？
2.数据量是多少条？
3.A href B的时候，你配的路径是传参数的吗？
4.A和B两个页面有关联吗？还是完全没关联的两个页面，就是普通的跳转？
5.导出excel失败抱什么错呢？
6.能把你具体的配置步骤描述一下吗？

**Comment by africaadonis** [comment]
1.非键值字典的下拉框取值，只显示本本页内的数据值？这个你是怎么设置的？
回复：
比如业务表中科室字段的值有5个，A科室、B科室、C科室、D科室、E科室，我将select distinct 科室字段值 from 业务表，作为报表"字典Code"的取值语句，然后查询结果返回每页10条，如果这10条业务数据中仅有A科室、B科室的记录，那么在动态生成的查询条件科室下拉框中仅有A、B两个科室，而不是5个科室。

2.数据量是多少条？
回复：
18000条

3.A href B的时候，你配的路径是传参数的吗？
回复：
是的，形如：/online/cgreport/1352583206540427266?idcardNo=${idcardNo}

4.A和B两个页面有关联吗？还是完全没关联的两个页面，就是普通的跳转？
回复：
有关联，和问题3一样，感觉是分页参数作为公共变量被共享了。

5.导出excel失败抱什么错呢？
回复：
大数据量的时候没有反应，小数据量的时候有时候有时候导出为空，对此还没有测试出具体的规律，有时候最左侧的复选框打钩后会导出，理论上这个【导出】应该是导出全部吧？

6.能把你具体的配置步骤描述一下吗？
回复：
（1）A页面ref至B页面，A页面15条数据，每页显示10条，共两页，B页面3条数据共1页，A ref B 是通过问题3描述中的ref方式，如果A页面翻到第2页，然后将idCardNo作为参数ref到B页面，但是查询结果为空，其实是应该查询到5条数据的，刷新一下B页面或调一下右下角的分页参数，这5条数据就查询出来了。
（2）再次测试确认，通过A页面ref至B页面，如果A页面中加了合计，那么跳转到B页面后，会导致B页面的每页的数据不对，如果A页每页10条，那么B页会有9条数据+1条空行，如果A页每页20条，那么B页会有19条数据+1条空行，导致总页数不对，就是受了A页加了合计属性的影响。

7、追加问题：
（1）日期时间类型的字段，按范围查询时，宽度太小了
（2）能实现给某个查询条件赋默认值吗？比如我按身份证查询，我想给身份证查询框给一个默认值123，故意让其查询不出数据来

**Comment by africaadonis** [comment]
![image](https://user-images.githubusercontent.com/40649464/106462155-ab9b7800-64d0-11eb-9dc5-8478d9efdd44.png)

**Comment by africaadonis** [comment]
![image](https://user-images.githubusercontent.com/40649464/106479490-59b11d00-64e5-11eb-9845-94e066ba1dc6.png)
还有这个日期范围条件，挤到一起了

**Comment by zhangdaiscott** [comment]
你录个视频吧，更快

**Comment by lsqGitHub716** [comment]
1.目前报表之间跳转是存在问题，已收录
2.日期时间类型的字段的考混，测试宽度是正常，未复现你说的样式
3.目前未实现给某个查询条件赋默认值

**Comment by lsqGitHub716** [comment]
1.非键值字典的下拉框取值：因为字典取值是从另外的一张表获取，考虑到性能问题，设置的查询条件只展示了报表当前列表页所有的字典对应值。（例如字典取值对应表有10w条数据，全部当成查询条件下拉也不现实）

**Comment by africaadonis** [comment]
> 1.目前报表之间跳转是存在问题，已收录
> 2.日期时间类型的字段，测试宽度是正常，未复现你说的样式
> 3.目前未实现给某个查询条件赋默认值

回复问题2：将某日期时间字段类型当做查询条件，查询模式为“范围查询”，字段文本为“发生日期”，会出现此问题

**Comment by africaadonis** [comment]
> 1.非键值字典的下拉框取值，只显示本本页内的数据值？这个你是怎么设置的？
> 2.数据量是多少条？
> 3.A href B的时候，你配的路径是传参数的吗？
> 4.A和B两个页面有关联吗？还是完全没关联的两个页面，就是普通的跳转？
> 5.导出excel失败抱什么错呢？
> 6.能把你具体的配置步骤描述一下吗？

回复2:   1万多条数据的时候超时，online报表导出功能超时，有地方可以设置一下吗？
![image](https://user-images.githubusercontent.com/40649464/107461680-7f998a00-6b95-11eb-9973-b73b69fa63ef.png)

**Comment by tygithub1** [comment]
有点乱了，就第一次提问的4个问题回复一下，还有问题另开帖子吧，
12新版已修复
3如果超时 前端设置一下超时时间src/utils/request.js  timeout  
4.源码写死的不需要配置，根据界面展示的数据初始化下拉框
