### ISSUE TITLE
2.2.1版本Online在线开发删除表还存在「急，谢谢！」

### ISSUE THREAD

**Issue by commanding** [zhangdaiscott/jeecg-boot#2249]
##### 版本号：
2.2.1

##### 问题描述：
Online在线开发，我pms_product表”删除“了，想重新建这个表，但是老提示我这张表存在。我在onl_cgform_head表已经看过已经不存在了。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/15892514/106589661-36d74500-6587-11eb-8f3d-1c44a34b1210.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪采用导入
