### ISSUE TITLE
为什么把权限相关的RequiresPermissions RequiresRoles都注释掉了

### ISSUE THREAD

**Issue by iorilchen** [zhangdaiscott/jeecg-boot#2250]
##### 截图&代码：
//@RequiresRoles({"admin"})
    //@RequiresPermissions("user:add")
	@RequestMapping(value = "/add", method = RequestMethod.POST)
	public Result<SysUser> add(@RequestBody JSONObject jsonObject) {

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
众口难调啊，需要的话，可以自己放开
