### ISSUE TITLE
代码生成器生成不了代码

### ISSUE THREAD

**Issue by dfsbbbbb** [zhangdaiscott/jeecg-boot#2252]
##### 版本号：
2.4.2

##### 问题描述：
提示代码生成成功，但是文件夹里并没有代码

##### 截图&代码：
![$ROBQDTRJ}F%R)799G E(ZV](https://user-images.githubusercontent.com/35921244/106860166-f6023c00-66fe-11eb-8bcf-1df4c5f397be.png)

![87 MG~GD)Z@W T63$@P (~D](https://user-images.githubusercontent.com/35921244/106860218-07e3df00-66ff-11eb-8c76-16538e501465.png)

日记如下：
load template data: {primaryKeyPolicy=java.lang.Integer, serialVersionUID=7988530542494700733, entityPackage=com, entityName=TestUser, primaryKeyField=id, columns=[{"fieldDbName":"name","fieldName":"name","filedComment":"名字","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"2","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"age","fieldName":"age","filedComment":"年龄","fieldType":"java.lang.Integer","fieldDbType":"int","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"3","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}], tableVo={"tableName":"test_user","ftlDescription":"test_user","primaryKeyPolicy":"null","sequenceCode":"null","entityPackage":"com","entityName":"TestUser","fieldRowNum":"1","searchFieldNum":"-1","fieldRequiredNum":"4"}, originalColumns=[{"fieldDbName":"id","fieldName":"id","filedComment":"主键","fieldType":"java.lang.Integer","fieldDbType":"int","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"N","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"1","isKey":"Y","isShow":"N","isShowList":"N","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"Y","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"name","fieldName":"name","filedComment":"名字","fieldType":"java.lang.String","fieldDbType":"string","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"2","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}, {"fieldDbName":"age","fieldName":"age","filedComment":"年龄","fieldType":"java.lang.Integer","fieldDbType":"int","classType":"text","classType_row":"text","optionType":"","charmaxLength":"","precision":"null","scale":"null","nullable":"Y","fieldLength":"120","fieldHref":"","fieldValidType":"null","fieldDefault":"","fieldShowType":"text","fieldOrderNum":"3","isKey":"N","isShow":"Y","isShowList":"Y","isQuery":"N","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"single","dictField":"","dictTable":"","dictText":""}], bussiPackage=com.abd, tableName=test_user}
2021-02-04 15:20:46.326 [http-nio-8080-exec-3] INFO  org.jeecgframework.codegenerate.generate.impl.a.a:50 -   load template from templateRootDir = 'D:\project\%e5%bc%80%e6%ba%90\jeecg-boot\jeecg-boot\jeecg-boot-module-system\target\classes\jeecg\code-template-online',stylePath ='default.one',  out GenerateRootDir:E:\test
2021-02-04 15:20:46.326 [http-nio-8080-exec-3] INFO  o.j.codegenerate.generate.impl.CodeGenerateOne:140 -  ----- jeecg-boot ---- generate  code  success =======> 表名：test_user 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/2209
