### ISSUE TITLE
swagger密码访问不生效

### ISSUE THREAD

**Issue by CenMinghao** [zhangdaiscott/jeecg-boot#2253]
##### 版本号：
2.4

##### 问题描述：
swagger密码访问不生效

##### 截图&代码：
swagger密码访问不生效，配置如下:
![image](https://user-images.githubusercontent.com/29631645/106979879-29de6f80-679a-11eb-9f02-1c776959300a.png)
改成如下配置后才生效：
![image](https://user-images.githubusercontent.com/29631645/106979734-e3891080-6799-11eb-8711-b012308d05f9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已修复，代码已经上传
