### ISSUE TITLE
租户功能可否使用？

### ISSUE THREAD

**Issue by jerrylees2000** [zhangdaiscott/jeecg-boot#2254]
##### 版本号：
        v 2.3.0

##### 问题描述：
   租户功能可否使用？
##### 截图&代码：
 'com.baomidou.mybatisplus.extension.plugins.tenant.TenantSqlParser' is deprecated 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以用
