### ISSUE TITLE
关于测边菜单遮挡内容问题详细说明

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#2255]
##### 版本号：
2.4

##### 问题描述：
看了之前好几个提该问题的，可能都没找到复现步骤，在这里说明下最新复现情况。
1、2.4之前的版本，当菜单栏缩进后，刷新页面，即出现菜单栏显现，内容还处于菜单栏缩进的位置，故而被遮挡；
2、2.4之后，修复了该问题，本地更新后发现仍未解决，故而继续查找原因，发现是系统设置：固定侧边菜单 的原因，设置为true，菜单栏缩进后，刷新仍会遮挡。

##### 截图&代码：

![QQ图片20210205145246](https://user-images.githubusercontent.com/25654842/106999833-d8e27180-67c1-11eb-8cdd-d3a5dad9933d.png)
![QQ图片20210205145251](https://user-images.githubusercontent.com/25654842/106999837-da139e80-67c1-11eb-8f92-f20396ff0d06.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，待验证

**Comment by lcm245748753** [comment]
在GlobalLayout.vue页面 中的 created函数中 加上一句：this.collaped = !this.sidebarOpened,可解决该问题，watch监控函数中，初始化页面时，没有执行更新左侧菜单栏隐藏状态

**Comment by zhangdaiscott** [comment]
2.4.2测试未出现此问题

**Comment by Nicky213Zhang** [comment]
> 2.4.2测试未出现此问题

在线演示版本也有此问题，是没更新还是操作步骤不对，侧边菜单缩进再刷新(固定侧边菜单设为true)

**Comment by Nicky213Zhang** [comment]
> 在GlobalLayout.vue页面 中的 created函数中 加上一句：this.collaped = !this.sidebarOpened,可解决该问题，watch监控函数中，初始化页面时，没有执行更新左侧菜单栏隐藏状态

感谢，确实是这样

**Comment by zhangdaiscott** [comment]
处理完成，请更新代码
