### ISSUE TITLE
请求url里面带分号，绕过token校验

### ISSUE THREAD

**Issue by jinkelazzz** [zhangdaiscott/jeecg-boot#2256]
##### 版本号：
2.1.0

##### 问题描述：
filterChainDefinitionMap.put("/", "anon");
好像这个排除会导致不校验token，接口被攻击

##### 截图&代码：

https://ae01.alicdn.com/kf/Ude00cb66398a4a2d87cdb6f888ada2dbX.jpg

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jinkelazzz** [comment]
![1612521412(1)](https://user-images.githubusercontent.com/35250831/107023110-228e8480-67e1-11eb-9cf9-07a1e753878a.jpg)

**Comment by zhangdaiscott** [comment]
收录

**Comment by lch245298** [comment]
集成Apache Shiro权限框架的，请检查版本，如果低于1.7.1，可能存在权限绕过漏洞，即无需任何认证信息就能直接访问后端获取敏感数据。及时升级版本

**Comment by jinkelazzz** [comment]
> 集成Apache Shiro权限框架的，请检查版本，如果低于1.7.1，可能存在权限绕过漏洞，即无需任何认证信息就能直接访问后端获取敏感数据。及时升级版本

感谢
