### ISSUE TITLE
我在的部门里添加人员后，人员列表还是显示为空

### ISSUE THREAD

**Issue by xuepingXu** [zhangdaiscott/jeecg-boot#2259]
##### 问题描述：
我在的部门里添加人员后，人员列表还是显示为空

##### 截图&代码：
Screenshot-0444fa1c-3c6a-4ee0-933d-ec04984cdbd4.png

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xuepingXu** [comment]
发现后台有报错
2021-02-07 09:32:56.052 [http-nio-8080-exec-9] ERROR druid.sql.Statement:149 - {conn-10002, pstmt-20791} execute error. select id from sys_depart where del_flag = '0' and org_code like concat((select org_code from sys_depart where id=?),'%')
com.microsoft.sqlserver.jdbc.SQLServerException: 'concat' 不是可以识别的 内置函数名称。

是SQL语句的问题，我是在MSSQL上运行的，请问这个数据库上运行还需要修改些什么呢？
是否可以把系统的数据库运行在MYSQL上，然后业务的数据库运行在MSSQL上？
文档里写的是mysql5.7+, 我用mysql8.0.15可以吗？

**Comment by zhangdaiscott** [comment]
select id from sys_depart where del_flag = '0' and org_code like concat((select org_code from sys_depart where id=?),'%')

这句sql mysql8不兼容吗

**Comment by zhangdaiscott** [comment]
com.microsoft.sqlserver.jdbc.SQLServerException 看着驱动异常是SqlServer

**Comment by xuepingXu** [comment]
> com.microsoft.sqlserver.jdbc.SQLServerException 看着驱动异常是SqlServer

是运行在 mssql2008,和2017上报的错，原因是 mssql里没有 CONCAT函数，
重点是下面2个问题
1.，我是在MSSQL上运行的，请问这个数据库上运行还需要修改些什么呢？
2.是否可以把系统的数据库运行在MYSQL上，然后业务的数据库运行在MSSQL上？

**Comment by zhangdaiscott** [comment]
那个功能？ 我们针对SqlServer2017做过兼容测试，没问题。

**Comment by lsqGitHub716** [comment]
SQL Server2012中才新增CONCAT函数的，你用的应该是2008，所以没有这个函数
