### ISSUE TITLE
数据库适配问题，MYSQL5.7 ,MYSQL8.0.15, MSSQL

### ISSUE THREAD

**Issue by xuepingXu** [zhangdaiscott/jeecg-boot#2260]
##### 问题描述：
发现后台有报错
2021-02-07 09:32:56.052 [http-nio-8080-exec-9] ERROR druid.sql.Statement:149 - {conn-10002, pstmt-20791} execute error. select id from sys_depart where del_flag = '0' and org_code like concat((select org_code from sys_depart where id=?),'%')
com.microsoft.sqlserver.jdbc.SQLServerException: 'concat' 不是可以识别的 内置函数名称。

是SQL语句的问题，我是在MSSQL上运行的，请问这个数据库上运行还需要修改些什么呢？
是否可以把系统的数据库运行在MYSQL上，然后业务的数据库运行在MSSQL上？
文档里写的是mysql5.7+, 我用mysql8.0.15可以吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是那个功能，我们针对oracle11g、SqlServer2017、mysql5.7做过适配测试，按道理不应该不问题

**Comment by xuepingXu** [comment]
mssql 是没有concat 这个函数的，有concat的地方都得改

**Comment by xuepingXu** [comment]
> 这是那个功能，我们针对oracle11g、SqlServer2017、mysql5.7做过适配测试，按道理不应该不问题

mssql 是没有concat 这个函数的，有concat的地方都得改

**Comment by lsqGitHub716** [comment]
SQL Server2012中才新增CONCAT函数的，你用的应该是2008，所以没有这个函数
