### ISSUE TITLE
如何生成数据库更新脚本？

### ISSUE THREAD

**Issue by yangwen27** [zhangdaiscott/jeecg-boot#2261]
##### 问题描述：
使用OL表单设计，同步生成的数据表如何导出更新的sql？项目发布之后避免不了升级改造，开发的时候直接通过OL表单设计可以很方便的修改数据库，但发布到线上就要自己核对数据库的差异然后写sql脚本。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
官方提供了同步工具
http://cloud.jeecg.com/page?id=1322087025830039554

**Comment by JokerQueue** [comment]
> 官方提供了同步工具 http://cloud.jeecg.com/page?id=1322087025830039554

链接打不开了，请问下有新的地址吗？
