### ISSUE TITLE
微服务Feign调用Provider报错Token为空的问题

### ISSUE THREAD

**Issue by huangguocai** [zhangdaiscott/jeecg-boot#2263]
##### 截图&代码：
官网拉的2.4.2最新代码，按照视频教程去新建微服务和Feign调用测试，请求走token直接通过网关调用是OK的，通过Feign转一道调用就报错token为空，请问是什么原因？

Feign客户端报错：
2021-02-08 16:36:57.884 [http-nio-7001-exec-3] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - [500] during [GET] to [http://jeecg-cloud-test/testt/hello] [MyTestClient#test()]: [{"timestamp":"2021-02-08 16:36:57","status":500,"error":"Internal Server Error","exception":"org.apache.shiro.authc.AuthenticationException","trace":"org.apache.shiro.authc.AuthenticationException: To... (7756 bytes)]
feign.FeignException$InternalServerError: [500] during [GET] to [http://jeecg-cloud-test/testt/hello] [MyTestClient#test()]: [{"timestamp":"2021-02-08 16:36:57","status":500,"error":"Internal Server Error","exception":"org.apache.shiro.authc.AuthenticationException","trace":"org.apache.shiro.authc.AuthenticationException: To... (7756 bytes)]

Feign Provider报错：
org.apache.shiro.authc.AuthenticationException: token为空!
	at org.jeecg.config.shiro.ShiroRealm.doGetAuthenticationInfo(ShiroRealm.java:96) ~[classes/:na]

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by huangguocai** [comment]
附上几张图片：
直接调用成功图片：[网关直接调用成功图](http://chuantu.xyz/t6/741/1612774245x1700340463.png)

网关配置图片：[网关配置](http://chuantu.xyz/t6/741/1612774363x1700338641.png)

**Comment by huangguocai** [comment]
附上几张图片：
网关配置图片:[点击查看](http://chuantu.xyz/t6/741/1612774363x1700338641.png)
直接通过网关调用成功图片：[点击查看](http://chuantu.xyz/t6/741/1612774245x1700340463.png)
系统模块走微服务Feign调用报错图片:[点击查看](http://chuantu.xyz/t6/741/1612774786x2073530386.png)
Feign Provider控制台报错图片:[点击查看](http://chuantu.xyz/t6/741/1612774848x1700338641.png)
Feign Client控制台报错图片:[点击查看](http://chuantu.xyz/t6/741/1612774940x1700338641.png)

**Comment by huangguocai** [comment]
解决了，是FeignConfig重复注册的问题，现在的代码直接注释掉了starter-cloud模块里面的FeignClientConfig，但是视频里面的是加了一个override-bean的配置，所以官网的代码还是有坑的，望验证并修正。

**Comment by zhangdaiscott** [comment]
你的意思，github上的代码注释掉starter-cloud模块里面的FeignClientConfig，导致有问题？
还是你改了什么内容

**Comment by zhangdaiscott** [comment]
已经知道问题了，感谢
