### ISSUE TITLE
OnLine表单开发，页面属性--控件类型 选不出：分类字典树、省市区组件、多行文本等。 

### ISSUE THREAD

**Issue by jerrylees2000** [zhangdaiscott/jeecg-boot#2264]
##### 截图&代码：

 
![image](https://user-images.githubusercontent.com/7495541/107196114-2adaff80-6a2d-11eb-995f-8f0a578bf840.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
子表？

**Comment by jerrylees2000** [comment]
是的 ，是子表。 为何子表的页面属性不能显示。

**Comment by zhangdaiscott** [comment]
收录，我们后面扩展下

**Comment by muqiufeng-zang** [comment]
发现同样的问题，期待修复。

**Comment by SafeWinter** [comment]
请问 @zhangdaiscott  这个提议目前的进度如何？有具体的开发计划吗？本想在子表的编辑页面加入分类字典下拉框，现在卡住了，不知道有没有什么替代方案或大致的解决思路，谢谢！
