### ISSUE TITLE
无法访问自己添加的 module 中的方法

### ISSUE THREAD

**Issue by zaocha321** [zhangdaiscott/jeecg-boot#2265]
##### 版本号：
2.4.0

##### 问题描述：
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=9301&extra=
jeecg-boot 2.4.0 新建 module 中的Controller 无法访问。

##### 截图&代码：
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=9301&extra=
1、创建新模块 jeecg-boot-module-jyjy ，项目结构如下，代码是通过 online功能生成的。
![image](https://user-images.githubusercontent.com/5121980/107307288-5dced300-6ac1-11eb-8ac0-4c5f6d708527.png)
其中 pom.xml 中的配置如下，已经引用了jeecg-boot-base-core 模块：
![image](https://user-images.githubusercontent.com/5121980/107307951-ae92fb80-6ac2-11eb-9165-379c05dbf2be.png)
![image](https://user-images.githubusercontent.com/5121980/107307994-c4082580-6ac2-11eb-9427-ead8c60e3dc3.png)

2、jeecg-boot-module-system 模块中添加了 jeecg-boot-module-jyjy 引用，在 jeecg-boot-parent 的pom.xml 中也自动添加了 jeecg-boot-module-jyjy 模块
jeecg-boot-module-system 模块：

![image](https://user-images.githubusercontent.com/5121980/107307778-4cd29180-6ac2-11eb-9c3f-5a7241869cf9.png)

jeecg-boot-parent 的 pom.xml 中：
![image](https://user-images.githubusercontent.com/5121980/107307750-3c221b80-6ac2-11eb-86e9-be6ecbd3be75.png)

然后通过 配置菜单、菜单赋权访问这个页面时报错，提示 资源未找到 ：

![image](https://user-images.githubusercontent.com/5121980/107307345-8060ec00-6ac1-11eb-8af5-e263eaf77ddc.png)

但是，我将 jeecg-boot-module-jyjy 模块中的代码 移动到 jeecg-boot-module-demo 项目中后，这个菜单就可以正常访问了。

请教一下，我是什么地方弄错了啊？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重启idea  刷新maven试试

**Comment by zaocha321** [comment]
> 重启idea 刷新maven试试
解决了，提交git，重启idea，刷新 maven 。
