### ISSUE TITLE
online表单开发必须要create_time字段吗？

### ISSUE THREAD

**Issue by Jiangshutao365** [zhangdaiscott/jeecg-boot#2267]
##### 版本号：
2.4.2

##### 问题描述：
在online表单开发中 导入数据库表  但是数据库的表中没有create_time字段，在进入这个表单页面查询数据时后端报错：
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Unknown column '**create_time**' in 'order clause'

这个怎么解决？（数据库是已经导入的表，符合规范无法添加create_time字段），怎么能在代码层面不用按create_time排序查询？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Nicky213Zhang** [comment]
重写查询方法或者前端复写排序，设置为空啥的

**Comment by zhangdaiscott** [comment]
默认是这样的，不想用的话得改造很多代码
