### ISSUE TITLE
用户角色应和部门分别绑定

### ISSUE THREAD

**Issue by ares007** [zhangdaiscott/jeecg-boot#227]
##### 版本号：
2.0.1

##### 问题描述：
现在可以设置用户多个部门多个角色，导致的问题是在每个部门都有相同的菜单，权限也一样。
应该按部门分别设置角色，进入相应的部门对应的功能菜单也不同。

**Comment by zhangdaiscott** [comment]
这个需求，你可以自己开发，暂时不支持
