### ISSUE TITLE
代码生成器生成自定义树，下载代码时树失效问题

### ISSUE THREAD

**Issue by forReak** [zhangdaiscott/jeecg-boot#2271]
##### 版本号：
2.4.2

##### 问题描述：
使用online表单开发时，对【自定义树控件】进行【代码生成】时，生成的vue页面【查询条件栏】及【表格】没有自定义控件功能。
补充：在【功能测试】页面，控件正常显示。

##### 截图&代码：
页面属性部分截图：
![image](https://user-images.githubusercontent.com/25656286/107622351-b0131e00-6c92-11eb-9aa3-bad478143331.png)
检验字段截图：
![image](https://user-images.githubusercontent.com/25656286/107622398-c02afd80-6c92-11eb-8acb-5dd2c0f88686.png)
【功能测试】页面能正常显示自定义树：
![image](https://user-images.githubusercontent.com/25656286/107622490-de90f900-6c92-11eb-9e8e-651815806776.png)
【代码生成】后，无法显示自定义树
![image](https://user-images.githubusercontent.com/25656286/107622534-f36d8c80-6c92-11eb-84ac-8f0283e60864.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前代码生成器还不支持一些特殊组件，可以生成后，手工加上逻辑
