### ISSUE TITLE
一级菜单之间切换出现异常的问题

### ISSUE THREAD

**Issue by cafecai** [zhangdaiscott/jeecg-boot#2272]
##### 版本号：
2.4.0（发布日期：20201201）

##### 问题描述：
当有多个像首页这样的只有一级菜单项的时候，一级菜单项之间切换会出现两个菜单项的页面同时出现在页面的情况。

##### 截图&代码：
![图片1](https://user-images.githubusercontent.com/30945460/108011903-0d1c2480-7043-11eb-99da-3301244ef20c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Shikyh** [comment]
请将src/components/layouts/TabLayout.vue文件的router-view那一块的那个transition标签移除即可

**Comment by sjlei** [comment]
这个问题新版已经改过了，参考 @Shikyh 的回答即可解决
