### ISSUE TITLE
JEditableTable批量新增并赋值的问题

### ISSUE THREAD

**Issue by vuvivian** [zhangdaiscott/jeecg-boot#2273]
##### 版本号：
2.4.0

##### 问题描述：
JEditableTable手动新增多行，但是added只返回了最后一条的rowid，导致在新增多行之后无法实现给新增行设置值setvalue

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28998321/108297632-8bf59680-71d6-11eb-9eeb-6550092375ee.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
字段定义的时候不是可以设置默认值吗
defaultValue
http://doc.jeecg.com/2043998

**Comment by lsqGitHub716** [comment]
http://doc.jeecg.com/2043998#_115    可以通过getValues()获取数值

**Comment by vuvivian** [comment]
> 字段定义的时候不是可以设置默认值吗
> defaultValue
> http://doc.jeecg.com/2043998
