### ISSUE TITLE
图表预览模式没数据显示

### ISSUE THREAD

**Issue by liujianbao666** [zhangdaiscott/jeecg-boot#2274]
##### 问题描述：
图表设计时不设置定时刷新，直接预览没有数据，相关数据接口已调用，但设计器中运行存在数据。并且没有报错。设置为定时刷新时可以看到图表

##### 截图&代码：

![image](https://user-images.githubusercontent.com/29687087/108299453-6c13a200-71d9-11eb-8c59-6b21ae54467e.png)

![image](https://user-images.githubusercontent.com/29687087/108299478-77ff6400-71d9-11eb-9637-7ae4bc4330d5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by accpman** [comment]
无法复现，提供下你的数据集
