### ISSUE TITLE
feign 动态创建client，拦截器执行多次

### ISSUE THREAD

**Issue by wzsyanly** [zhangdaiscott/jeecg-boot#2275]
##### 版本号：
2.4.2

##### 问题描述：
按照视屏教程，在controller中n次调用newInstance的话，拦截器里的代码就会执行多次，感觉是注册了n个拦截器。造成的结果是：log日志会打印多次。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/21212784/108331912-30dd9700-720a-11eb-8252-2e45c0f7cabd.png)

解决方案：将下图的代码移到构造器中就不会产生上述问题。
![image](https://user-images.githubusercontent.com/21212784/108332330-a0538680-720a-11eb-9299-bcffa439134a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
感谢，已经修正
