### ISSUE TITLE
JVXETable 中级联怎么做，A下拉框选中以后 要改变B下拉框的下拉选项？ A的valueChange事件是如何获取B下拉框组件呢

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#2278]
##### 问题描述：
JVXETable 中级联怎么做，A下拉框选中以后 要改变B下拉框的下拉选项？ A的valueChange事件是如何获取B下拉框组件呢
求教求教大神
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
参考 ：常见案例=》JEditableTable示例

**Comment by tianchenglong323** [comment]
> 参考 ：常见案例=》JEditableTable示例
   试过的， 像JEditableTable示例级联中直接修改column的options，JVXETable的B下拉框只显示初始值，不修改

**Comment by lsqGitHub716** [comment]
你可以通过传入的target参数，来设置columns的options数值

**Comment by tianchenglong323** [comment]
> 你可以通过传入的target参数，来设置columns的options数值
   大神，代码大概怎么写呢

**Comment by lsqGitHub716** [comment]
参考 ：常见案例=》JEditableTable示例
把handleValueChange方法里面的this.columns改成target.$refs.vxe.columns

**Comment by tianchenglong323** [comment]
> 参考 ：常见案例=》JEditableTable示例
> 把handleValueChange方法里面的this.columns改成target.$refs.vxe.columns

大神厉害 可以了 谢谢
