### ISSUE TITLE
online报表中字段类型为长整形时，合计的显示能否不加.00，数值类型的时候加上.00

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/jeecg-boot#2279]
##### 版本号：
2.4.2

##### 问题描述：
online报表中字段类型为长整形时，合计的显示能否不加.00，数值类型的时候加上.00

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40649464/108577504-46fb6c80-735c-11eb-9b9e-c78e0a981cc5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
截图看看你的配置

**Comment by zhangdaiscott** [comment]
收录

**Comment by africaadonis** [comment]
> 截图看看你的配置

![image](https://user-images.githubusercontent.com/40649464/108586249-2ba65680-7388-11eb-9515-38dcf6273edc.png)
![image](https://user-images.githubusercontent.com/40649464/108586268-411b8080-7388-11eb-9cc1-63e085df195e.png)

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
