### ISSUE TITLE
根据阿里规约检查扫描调整

### ISSUE THREAD

**Issue by huangbosbos** [zhangdaiscott/jeecg-boot#228]
##### 版本号：
v2.0.1

##### 问题描述：
使用idea 2019.1 版本 插件阿里规约检查发现，代码需要调整

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17606795/59778328-e004f500-92e8-11e9-8ac0-414c26e45d97.png)

**Comment by huangbosbos** [comment]
![image](https://user-images.githubusercontent.com/17606795/59778626-70433a00-92e9-11e9-931b-84096d48d310.png)

**Comment by zhangdaiscott** [comment]
感谢，我内部有这个，代码规范得逐步改，工作量大
