### ISSUE TITLE
Online表单开发功能，附表外键配置非主表主键问题

### ISSUE THREAD

**Issue by kevinchuxu** [zhangdaiscott/jeecg-boot#2281]
##### 版本号：
2.4.2

##### 问题描述：
在线代码功能中，附表配置**外键非主表主键**且**对应关系为一对一**时，**修改无法带出数据显示**，保存修改数据生效

##### 截图&代码：
配置截图
![image](https://user-images.githubusercontent.com/9587300/108585906-09133e00-7386-11eb-8bed-e278b324cb93.png)
现象截图
![image](https://user-images.githubusercontent.com/9587300/108585948-627b6d00-7386-11eb-916c-c30998c0274e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
已修复
