### ISSUE TITLE
鉴权登录拦截器抛出的异常是在哪里捕获并配置返回的json

### ISSUE THREAD

**Issue by luoqiuqiu** [zhangdaiscott/jeecg-boot#2282]
##### 截图&代码：
图1：
![图1](https://user-images.githubusercontent.com/52776176/108589961-0d4a5600-739c-11eb-8f81-e5490df9b225.png)
图2：
![图2](https://user-images.githubusercontent.com/52776176/108589971-1b987200-739c-11eb-8154-105d6da35bd5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你是不是升级springboot版本或者改什么了

**Comment by luoqiuqiu** [comment]
@zhangdaiscott 恩恩，发现同事代码添加了/error页面
