### ISSUE TITLE
对象存储预览不好使

### ISSUE THREAD

**Issue by pansy629** [zhangdaiscott/jeecg-boot#2283]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
截图

**Comment by pansy629** [comment]
![image](https://user-images.githubusercontent.com/46204219/108642940-290c4400-74e3-11eb-8a4f-837fc8381265.png)

**Comment by pansy629** [comment]
![image](https://user-images.githubusercontent.com/46204219/108642977-5b1da600-74e3-11eb-97e5-56cb7735bcbc.png)

**Comment by zhangdaiscott** [comment]
确认下你的访问地址，外网通？
