### ISSUE TITLE
角色权限问题

### ISSUE THREAD

**Issue by huiyup** [zhangdaiscott/jeecg-boot#2284]
##### 版本号：

master
##### 问题描述：

通过角色权限只是在前端显示的控制，并排除相应的接口，例如，临时角色应该没有操作角色的权限，通过临时角色的token发送请求依然可以操作角色
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044037
加权限注解
