### ISSUE TITLE
FeignConfig重复

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2286]
##### 版本号：

2.4.2
##### 问题描述：

/jeecg-boot-base/jeecg-boot-base-api/jeecg-system-cloud-api/src/main/java/org/jeecg/config/FeignConfig.java

/jeecg-boot-starter/jeecg-boot-starter-cloud/src/main/java/org/jeecg/config/FeignConfig.java
这两个重复，启动jeecg-demo时会报bean重复的错误，应该将jeecg-system-cloud-api中的删掉
##### 截图&代码：

Failed to parse configuration class [org.jeecg.JeecgDemoApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'feignConfig' for bean class [org.jeecg.config.FeignConfig] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.starter.cloud.config.FeignConfig]

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/108685284-ef612a80-752e-11eb-9392-a2e0110a30d5.png)

你代码没更新到最新，你可以把org.jeecg.starter.cloud.config.FeignConfig弄成跟api一样的路径，就可以了

**Comment by mark0614** [comment]
我已经更新到了最新了，我查看了github上的master主干，确实有两个FeignConfig

**Comment by zhangdaiscott** [comment]
是俩，但是路径跟你的不同
