### ISSUE TITLE
数据库设计界面，不方便操作

### ISSUE THREAD

**Issue by qingjiaorose157** [zhangdaiscott/jeecg-boot#2287]
##### 问题描述：online表单开发-新增-数据库属性
建议表格直接在屏幕上往下铺开，不要用滚动条的形式，我还以为新增按钮失效了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28780934/108681941-ab6c2680-752a-11eb-8891-c8de5dac3d14.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by i-Hu** [comment]
有相同的需求
