### ISSUE TITLE
bug：online报表配置的sql不会加上多租户字段，不能用于多租户，怎么破

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#2288]
##### 版本号：
2.4.2

##### 问题描述：
bug：online报表配置的sql不会自动加上多租户字段，不能用于多租户，怎么破

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个得有代码才能改造，暂时不行
