### ISSUE TITLE
打包部署至nginx下，使用浏览器上面的刷新按钮，刷新页面404

### ISSUE THREAD

**Issue by roneywei** [zhangdaiscott/jeecg-boot#229]
##### 问题描述：
打包部署至nginx下，使用浏览器上面的刷新按钮，刷新页面404

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5858867/59816420-9e0e9a00-934e-11e9-8cbc-b1607b21ed00.png)
![image](https://user-images.githubusercontent.com/5858867/59816433-ab2b8900-934e-11e9-9fc8-67380d326486.png)

**Comment by zhangdaiscott** [comment]
那个按钮？

**Comment by roneywei** [comment]
就是这个按钮
![image](https://user-images.githubusercontent.com/5858867/59823263-4416d000-9360-11e9-89e2-2ac408a2e8b1.png)

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=345682
参考这个文档，不用少步骤
