### ISSUE TITLE
JEditableTable页面关闭时，数据没清空， 下次点击新增出来的还是之前明细，可以在close关闭时清除数据

### ISSUE THREAD

**Issue by tianchenglong323** [zhangdaiscott/jeecg-boot#2290]
##### 问题描述：
JEditableTable页面关闭时，数据没清空， 下次点击新增出来的还是之前明细，可以在close关闭时清除数据

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块改造过，请详细描述你的功能和代码

**Comment by lsqGitHub716** [comment]
请描述一下你测试的功能

**Comment by tygithub1** [comment]
新版无此问题，见演示：http://boot.jeecg.org/  访问菜单【常见案例】 --> 【一对多JEditable】
