### ISSUE TITLE
生成代码访问后提示：很抱歉，资源未找到!

### ISSUE THREAD

**Issue by c-java-father** [zhangdaiscott/jeecg-boot#2291]
##### 版本号：
2.4.0

##### 问题描述：
生成代码访问后提示：很抱歉，资源未找到!

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26218096/108813460-06198700-75ec-11eb-8b4c-9fba51b21647.png)

在菜单里面这么配置
![image](https://user-images.githubusercontent.com/26218096/108813561-3cef9d00-75ec-11eb-97e3-18aee3473e23.png)

访问生成的菜单提示“很抱歉资源未找到”
![image](https://user-images.githubusercontent.com/26218096/108813775-96f06280-75ec-11eb-8fe4-fa845b283dac.png)

浏览器查看每次都请求两次接口，第一次报错
![image](https://user-images.githubusercontent.com/26218096/108813856-bd160280-75ec-11eb-85c4-37bb3c7169b5.png)

期待大佬回复

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你这是后台请求无法访问，看看扫码路径或者重启了没有

**Comment by c-java-father** [comment]
ok
