### ISSUE TITLE
popup控件修改字段值后，不能触发onlChange()方法

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2292]
##### 版本号：
2.4.2

##### 问题描述：
使用popup控件修改字段值后，不能触发onlChange()方法

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己改造吧，popup一般是用来选择新值，没有加change事件吧
