### ISSUE TITLE
online表单开发新增表或者强制同步数据库的时候无法在数据库建表

### ISSUE THREAD

**Issue by Nocccc** [zhangdaiscott/jeecg-boot#2293]
##### 版本号：
2.4.2

##### 问题描述：
online表单开发新增表或者强制同步数据库的时候无法在数据库建表

##### 截图&代码：
![image](https://user-images.githubusercontent.com/79438420/108857137-bc4d9280-7625-11eb-9358-1caaae1d63bb.png)

数据库
![image](https://user-images.githubusercontent.com/79438420/108857283-e606b980-7625-11eb-8f1c-defca6406eb0.png)
![image](https://user-images.githubusercontent.com/79438420/108857374-fdde3d80-7625-11eb-82c3-19462db0fb1f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
啥意思？同步数据库没有创建表？

**Comment by Nocccc** [comment]
> 啥意思？同步数据库没有创建表？

对

**Comment by zhangdaiscott** [comment]
错误截图

**Comment by Nocccc** [comment]
> 错误截图

![image](https://user-images.githubusercontent.com/79438420/108964658-b653c200-76b6-11eb-8d3c-3e186ae27410.png)

**Comment by zhangdaiscott** [comment]
信息太少，无法分析

**Comment by sonhineboy** [comment]
你的这个问题解决了吗？

**Comment by zhangdaiscott** [comment]
http://www.jeecg.com/doc/qa
65
