### ISSUE TITLE
请问微服务怎么实现，每个模块各自配置各种的数据库呢？

### ISSUE THREAD

**Issue by BringChen** [zhangdaiscott/jeecg-boot#2294]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
每个模块弄自己的nacos文件即可，nacos里面配置什么数据库就链接那个数据库

**Comment by huangguocai** [comment]
同问一下，如果每个模块弄自己的数据库，在线开发是不是就不能灵活同步到自己库了

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2188439
