### ISSUE TITLE
积木报表api数据源带参，解析时参数无效

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2295]
##### 版本号：
2.4.2

##### 问题描述：
积木报表api数据源带参，解析时参数无效，不能正确获取接口数据
建议在解析时用默认值替换参数
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/108942586-3a478300-7692-11eb-9ca2-87aed24111a2.png)

![image](https://user-images.githubusercontent.com/26364818/108942485-0e2c0200-7692-11eb-83d4-deab52c547e1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个功能意义不大，成本反而太高了，可以手工配置参数的

**Comment by liujianbao666** [comment]
建议查询条件可以与报表参数绑定

**Comment by i-Hu** [comment]
2.4.2不能手动配置参数，解析时会自动替换成'${}'，如果api需要传参查询的话，现在没有办法正确获取列名，也没有办法手动配置

**Comment by zhangdaiscott** [comment]
已经支持了
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta2</version>
</dependency>
```
