### ISSUE TITLE
online报表配置，sql不支持使用开窗函数

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2296]
##### 版本号：
2.4.2
sqlserver2008
##### 问题描述：
online报表配置，sql不支持使用开窗函数，提示SqlServer不支持SQL内排序!

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
错误日志截图

**Comment by i-Hu** [comment]
![image](https://user-images.githubusercontent.com/26364818/109121835-bae5ac80-7782-11eb-88d6-dffa55c63eb9.png)
参考语句：
        SELECT ROW_NUMBER() OVER (PARTITION BY bcc.b01_contract_id ORDER BY bcc.change_date DESC) num
        FROM dbo.b01_contract_change bcc
        WHERE bcc.type LIKE '%4%'

**Comment by tygithub1** [comment]
这个问题存在，报表使用时，建议sqlserver数据库下不要在sql语句中写order by
