### ISSUE TITLE
页面启动报错

### ISSUE THREAD

**Issue by Young5416** [zhangdaiscott/jeecg-boot#23]
![image](https://user-images.githubusercontent.com/34014756/54731934-f73e2480-4bcb-11e9-8cc3-262db089ba91.png)

**Comment by ileadall42** [comment]
这个是npm的一些问题，昨天群里有个人也是这样，多试几次，node版本要新，缓存要每次清掉，设置的源是国内的，然后多试几次。

**Comment by zhangdaiscott** [comment]
用yarn，npm慢问题很多
