### ISSUE TITLE
配置栏只在开发环境用于预览，生产环境不会展现，请问在生产环境使用配置栏会有什么影响吗

### ISSUE THREAD

**Issue by ggunmo** [zhangdaiscott/jeecg-boot#230]
##### 版本号：
2.0.1

##### 问题描述：

配置栏只在开发环境用于预览，生产环境不会展现，请问在生产环境使用配置栏会有什么影响吗？
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18226120/59826866-c0fa7780-9369-11e9-934e-ce34424570a6.png)

**Comment by sunshixiong789** [comment]
这不是ant design pro的东西么？还是不能在线切换主题啊？还是要用css in js

**Comment by ggunmo** [comment]
> 这不是ant design pro的东西么？还是不能在线切换主题啊？还是要用css in js

嗯，开始没注意，后来知道了就close了

**Comment by brade080710** [comment]
> > 这不是ant design pro的东西么？还是不能在线切换主题啊？还是要用css in js
> 
> 嗯，开始没注意，后来知道了就close了

这个配置栏是如何关闭的
