### ISSUE TITLE
官方文档描述错误

### ISSUE THREAD

**Issue by chenyuzhuGit** [zhangdaiscott/jeecg-boot#2300]
##### 问题描述：
JeecgBoot开发文档：http://doc.jeecg.com/2044224
菜单:AutoPOI(Excel工具)--->快速文档
SpringMvc的无缝融合，自定义试图的描述是不是写反了。如图所示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/47171610/109092558-b94fc080-7751-11eb-86f3-ca0346024993.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已修正
