### ISSUE TITLE
online表单开发，数据库连接问题。

### ISSUE THREAD

**Issue by qianlei0007** [zhangdaiscott/jeecg-boot#2302]
##### 问题描述：
online 表单开发， 是否使用的是项目配置的数据库？ 本机有两个库， jeecg-boot  和 jeecg242 , 连接池 配置的 jeecg242库，但是online表单开发，导入数据库表的时候，居然是访问的 jeecg-boot 库。 很神奇。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
代码生成器的数据库配置改下就好了
