### ISSUE TITLE
autpoi 2.0.1版本导出报错

### ISSUE THREAD

**Issue by Fnckerpoi** [zhangdaiscott/jeecg-boot#2303]
##### 问题描述：
该版本导出有遇到如下报错
2021-02-24 22:20:07.155 [http-nio-9999-exec-1] ERROR o.a.c.c.C.[.[.[/yuns].[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/yuns] threw exception [Request processing failed; nested exception is org.jeecgframework.poi.exception.excel.ExcelExportException: Excel导出错误] with root cause

切换回1.2.2却没有问题

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么功能？请补充issue描述

**Comment by Fnckerpoi** [comment]
> 什么功能？请补充issue描述

```
 ModelAndView mv = new ModelAndView(new JeecgEntityExcelView());
        mv.addObject(NormalExcelConstants.FILE_NAME, title);
        mv.addObject(NormalExcelConstants.CLASS, pojoClass);
        mv.addObject(NormalExcelConstants.PARAMS, new ExportParams(title, "导出人:" + sysUser.getRealname(), "导出信息"));
        mv.addObject(NormalExcelConstants.DATA_LIST, array);
```
在使用导出autopoi导出功能的时候
采用@Excel标注字段的方式
在2.0.1就会出现上述报错信息
但是切换回1.2.2却没有这个问题

**Comment by zhangdaiscott** [comment]
收录

**Comment by lsqGitHub716** [comment]
测试未重现你说的问题，请描述一下你重现问题的整个流程步骤，方便的话，建议把相关代码或者实体配置贴出来

**Comment by Fnckerpoi** [comment]
> 测试未重现你说的问题，请描述一下你重现问题的整个流程步骤，方便的话，建议把相关代码或者实体配置贴出来

我也不知道还能怎么描述，就是单纯的excel导出。在字段类对字段使用@Excel注解标记我需要导出的字段。完全是按照官方文档的教程使用来使用autopoi导出功能；
没有像其中一个issues那样有自己重写过里面相关内容。

**Comment by zhangdaiscott** [comment]
把请把详细的错误日志帖一下
