### ISSUE TITLE
JVXETable组件，当Column类型JVXETypes.normal或label时，无法正确按照formatter转换

### ISSUE THREAD

**Issue by gz-tianfengming** [zhangdaiscott/jeecg-boot#2304]
##### 截图&代码：
        {
              title: '折扣金额',
              key: 'discountAmount',
              type: JVXETypes.normal,
              width: "90px",
              formatter: 'amount_format',
              statistics: ['sum']
        },

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
normal 就是普通的文本框，不支持的

**Comment by P1casso** [comment]
那我要转换显示怎么弄，用input不美观，只能自己把数据格式化后再传过来？
