### ISSUE TITLE
sql解析成功但动态报表配置明细无法解析

### ISSUE THREAD

**Issue by liujianbao666** [zhangdaiscott/jeecg-boot#2305]
##### 问题描述：
sql解析成功，只因为加了一个固定的查询条件，动态报表配置明细无法解析

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29687087/109117230-aef6ec00-777c-11eb-8658-4d1de55195bd.png)

![image](https://user-images.githubusercontent.com/29687087/109117249-b6b69080-777c-11eb-9326-ad844c6a8bd4.png)
加了一个条件导致动态报表配置明细变为空

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
这不是提示你解析成功了吗？sql查询不到数据 就找不到字段 这是必然的

**Comment by cc19920815** [comment]
你这个肯定不对呀  我的列名是有的  只是暂时查不到数据   马上我查到数据了该如何现实呢     
动态配置没有我sql数据源也没法配置 
难道是有数据才能反推列名？
