### ISSUE TITLE
积木报表sql数据集，带参条件解析错误

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2306]
##### 版本号：
2.4.2

##### 问题描述：
1.积木报表sql数据集，带参条件解析错误
例如：where 1=1 AND (termination_date>='${end_date}' or termination_date is null) 会被解析成 where 1=1 or termination_date is null)  多了个括号
CASE WHEN ISNULL(termination_date, maturity_date)<maturity_date THEN termination_date ELSE maturity_date END BETWEEN '${begin_date}' AND '${end_date}' 解析成 CASE WHEN ISNULL(termination_date, maturity_date)<maturity_date THEN termination_date ELSE maturity_date 1=1
2.相同参数重复生成，暂不影响使用
##### 截图&代码：
问题二截图
![image](https://user-images.githubusercontent.com/26364818/109123429-cb972200-7784-11eb-994b-1bb4e43f4b8b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
2个问题都修复了，下个版本有【v1.2.0+】

**Comment by 1298191366** [comment]
不支持between and 你可以尝试用第一种写法》=或《=，现最新版本已修复

**Comment by zhangdaiscott** [comment]
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta</version>
</dependency>
```
