### ISSUE TITLE
积木报表，合并单元格的文字，预览显示不全

### ISSUE THREAD

**Issue by ChangYunQing** [zhangdaiscott/jeecg-boot#2307]
##### 版本号：
2.4.2

##### 问题描述：
积木报表，合并单元格的文字显示不全

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31750150/109134654-3b130e80-7791-11eb-98aa-c00d9d576dbc.png)

步骤：
报表设计器->在线设计->打印设计->模板案例，复制模板《XXX有限公司员工登记表》->预览

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本就解决了

**Comment by zhangdaiscott** [comment]
升级到这个版本就可以了
```
<dependency> 
<groupId>com.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.2.0-beta</version> 
</dependency>
```
