### ISSUE TITLE
postgres int类型 实体布尔类型插入数据失败

### ISSUE THREAD

**Issue by xu-bin-bin** [zhangdaiscott/jeecg-boot#2308]
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/34916924/109252368-55e49200-7828-11eb-8fa9-5ffadfbc918e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044271

**Comment by xu-bin-bin** [comment]
你们提供的这个解决办法在购买的云数据库中没办法执行，云数据库没给开放权限。

**Comment by zhangdaiscott** [comment]
不能申请权限？

**Comment by xu-bin-bin** [comment]
向华为提交了工单，给的回复是他联系了他们的内核工程师，说是不可以进行修改。

**Comment by zhangdaiscott** [comment]
哪你调整代码吧，把tinyint定义的都改成int

**Comment by xu-bin-bin** [comment]
好吧，谢谢
