### ISSUE TITLE
能否提供一个后端环境的docker镜像方便新手使用呢？

### ISSUE THREAD

**Issue by qianlizhe** [zhangdaiscott/jeecg-boot#2309]
能否提供一个后端环境的docker镜像方便新手使用呢？

看文档发现想把这个项目运行起来需要的环境和配置挺多的，但是我对后端的这些配置和环境不熟悉，能否提供一个docker镜像方便使用呢？

**Comment by zhangdaiscott** [comment]
可以，会尽快出
