### ISSUE TITLE
JEditable中，datepicker和select控件被遮挡

### ISSUE THREAD

**Issue by frh0792** [zhangdaiscott/jeecg-boot#231]
##### 版本号：
v2.0

##### 问题描述：
JEditable中，datepicker和select控件被遮挡

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/6119455/59889399-c48c0e00-93fe-11e9-91e9-cae978ab64d8.png)
![图片](https://user-images.githubusercontent.com/6119455/59889406-cce44900-93fe-11e9-80c7-b43aecba10b0.png)

**Comment by zhangdaiscott** [comment]
你升级2.0.1试试，下拉这块微调过

**Comment by frh0792** [comment]
> 
> 
> 你升级2.0.1试试，下拉这块微调过

好的 谢谢
