### ISSUE TITLE
字典【是否启用】按钮会错误的保存状态

### ISSUE THREAD

**Issue by Nibbbbbbbb** [zhangdaiscott/jeecg-boot#2311]
##### 版本号：
2.4

##### 问题描述：
编辑某个字典项时 ，禁用他
更新下个值时点保存，也会被禁用

##### 截图&代码：
选项A  切换为禁用
![image](https://user-images.githubusercontent.com/21167262/109446489-ba982a80-7a7c-11eb-81c7-b814b50e6d5a.png)
此时编辑选项B   是否启用按钮不更改，点击保存，他会错误的更新为禁用（反过来也一样）
![image](https://user-images.githubusercontent.com/21167262/109446510-c5eb5600-7a7c-11eb-91e8-f72054a789fd.png)
![image](https://user-images.githubusercontent.com/21167262/109446620-faf7a880-7a7c-11eb-8a6d-bf9cc13b049f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在，收录

**Comment by zhangdaiscott** [comment]
已经修复，代码已经上传
