### ISSUE TITLE
能否给出一个将微服务代码架构的，视频和文档只是很浅的说了怎么切换，没讲代码的架构

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#2312]
##### 版本号：

2.4.2
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，你可以细化下你想听的内容

**Comment by tyjohn** [comment]
想知道jeecg-boot-start和jeecg-cloud-module这两个项目的架构，是如何通过这两个项目将单体服务变为微服务项目的，谢谢！！！

**Comment by zhangdaiscott** [comment]
https://www.bilibili.com/video/BV1sZ4y1G7LL?p=27
