### ISSUE TITLE
system服务和demo服务有办法同时使用xxl-job吗

### ISSUE THREAD

**Issue by blowing-in-the-wind** [zhangdaiscott/jeecg-boot#2313]
##### 版本号：
2.4.2

##### 问题描述：
单体升级为微服务版，system服务和demo服务有办法同时使用xxl-job吗，如果都引入启动会报错（Address already in use: bind）、xxl-job管理台的“执行器管理”只能识别到先启动的服务的OnLine机器地址

##### 截图&代码：
![QQ图片20210301151546](https://user-images.githubusercontent.com/23657582/109464181-386e2d00-7aa1-11eb-99df-fbcf2331a09f.png)

**Comment by zhangdaiscott** [comment]
看看是不是这个问题
https://github.com/zhangdaiscott/jeecg-boot/issues/2228

**Comment by blowing-in-the-wind** [comment]
大佬好，我看了#2228 是同一个问题，我目前使用的最新的代码仍然有这个问题，因为两个微服务模块引用的同一套配置（相同的端口），唯一不同的配置是appname（由于是引用的${spring.application.name}）。我看到wzsyanly的答复提到了一种解决方式但是不太清楚system和demo服务在nacos里应该如何分别配置：https://github.com/zhangdaiscott/jeecg-boot/issues/2228#issuecomment-771399005

**Comment by zhangdaiscott** [comment]
jeecg-cloud-xxljob
作为服务端，启动一份就可以了
其他服务项目改配置即可
![image](https://user-images.githubusercontent.com/3162115/109589571-7d4b9f80-7b45-11eb-8ecd-b4b1c95efddd.png)

**Comment by zhangdaiscott** [comment]
org.jeecg.boot.starter.job.config.XxlJobConfiguration

这个注释掉
![image](https://user-images.githubusercontent.com/3162115/110091758-c44ec480-7dd3-11eb-9764-2f174245e7f5.png)
