### ISSUE TITLE
TimePicker 时间选择框默认值问题

### ISSUE THREAD

**Issue by AmonitorA** [zhangdaiscott/jeecg-boot#2314]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/42309576/109474006-fba93280-7aae-11eb-8ad6-fc1cbaeaac9c.png)
![image](https://user-images.githubusercontent.com/42309576/109474068-111e5c80-7aaf-11eb-88a2-b4898c23dd51.png)
![image](https://user-images.githubusercontent.com/42309576/109474133-25625980-7aaf-11eb-9b94-408bb07f6a2f.png)
![image](https://user-images.githubusercontent.com/42309576/109474196-33b07580-7aaf-11eb-8897-687c69d77f56.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
你测试的是代码生成器时间组件吗？具体操作的功能是什么？有没有修改什么代码呢？目前未测试出你说的问题
