### ISSUE TITLE
OnLine报表ref属性链接页面，由于在调用页面翻页，导致被ref的页面为空，其实是有数据的

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/jeecg-boot#2315]
##### 版本号：
2.4.2

##### 问题描述：
1、在ref调用页面共有2页数据，然后选择第二页的某条数据，被ref的页面只有一页，那么ref之后，会继承分页参数，导致第二页查询结果为空，举例：
A页面ref至B页面，A页面15条数据，每页显示10条，共两页，B页面3条数据共1页，A ref B 是通过"/online/cgreport/1352583206540427266?idcardNo=${idcardNo}"方式，如果A页面翻到第2页，然后将idCardNo作为参数ref到B页面，但是查询结果为空，其实是应该查询到5条数据的，刷新一下B页面或调一下右下角的分页参数，这5条数据就查询出来了。
2、点击某列排序之后，再ref至子页面，也会出现这个问题

此问题是根据如下问题单独出来！
https://github.com/zhangdaiscott/jeecg-boot/issues/2242

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
2.4.3已经解决，请更新代码确认
