### ISSUE TITLE
登录界面报错

### ISSUE THREAD

**Issue by yuan199696** [zhangdaiscott/jeecg-boot#2317]
##### 问题描述：登录界面报错：弹框内容：登陆失败，不支持GET请求，支持以下POST。
后台登录接口请求状态为200，且后台接口是POST请求。刚下载的代码，没有修改。

##### 截图&代码：
[截图一](https://gitee.com/bfanfanfan/img/raw/master/docsify/微信图片_20210302170747.jpg)
[截图二](https://gitee.com/bfanfanfan/img/raw/master/docsify/微信图片_20210302170815.jpg)

**Comment by zhangdaiscott** [comment]
不应该，那个接口？

**Comment by yuan199696** [comment]
![image](https://user-images.githubusercontent.com/32838333/109667242-e87b8d00-7baa-11eb-8331-cc1fe20f50e7.png)
![image](https://user-images.githubusercontent.com/32838333/109667513-2ed0ec00-7bab-11eb-87d0-653cb4dbe294.png)
登录接口：http://localhost:8080/jeecg-boot/sys/login

**Comment by yuan199696** [comment]
> 不应该，那个接口？

登录接口：http://localhost:8080/jeecg-boot/sys/login
![image](https://user-images.githubusercontent.com/32838333/109667771-6fc90080-7bab-11eb-8b69-daa62be6d0a7.png)
![image](https://user-images.githubusercontent.com/32838333/109667814-7a839580-7bab-11eb-9209-ac1f8d043f2f.png)

**Comment by zhangdaiscott** [comment]
后台服务启动有问题，自己排查看看
