### ISSUE TITLE
vue-print-nb-jeecg 打印选中所有多选框问题

### ISSUE THREAD

**Issue by yaomindong** [zhangdaiscott/jeecg-boot#2321]
##### 版本号：
1.0.9

##### 问题描述：
vue-print-nb-jeecg 打印的时候选中了所有的多选框。
##### 截图&代码：

![image](https://user-images.githubusercontent.com/38147794/109780712-37283600-7c42-11eb-9d1b-7279438201fa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
打印的时候，默认选中  实际上没选中？

**Comment by yaomindong** [comment]
是的 实际选中了 打印的时候那个√没有了



在 2021-03-04 10:27:29，"JEECG开源社区" ***@***.***> 写道：

打印的时候，默认选中 实际上没选中？

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/111128348-bce7a200-85af-11eb-9a49-e5bd05adac46.png)
