### ISSUE TITLE
微服务发布后，代码生成功能失效。

### ISSUE THREAD

**Issue by wangjidilidun** [zhangdaiscott/jeecg-boot#2322]
##### 版本号：
2.4.2

##### 问题描述：
微服务发布后，代码生成功能失败。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/4100843/109781880-4196ff80-7c43-11eb-8da5-65fe65c3f226.png)

后台打印中，load template from templateRootDir的路径有问题

![image](https://user-images.githubusercontent.com/4100843/109782180-8b7fe580-7c43-11eb-83c0-c9a5449c316e.png)
请帮忙看看

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043922

**Comment by wangjidilidun** [comment]
感谢回复，此文等我看过了（http://doc.jeecg.com/2043922），用单体的方式启动是可以的，但是采用微服务的方式是不可行的。
下图这个可以
![image](https://user-images.githubusercontent.com/4100843/109817146-884d1f80-7c6c-11eb-9408-98840e4c3ae0.png)

下图这个目录结构不行
![image](https://user-images.githubusercontent.com/4100843/109817248-a9ae0b80-7c6c-11eb-96a0-0c63c61ecfd4.png)



> http://doc.jeecg.com/2043922
