### ISSUE TITLE
请问创建demo的原因

### ISSUE THREAD

**Issue by loongw513029** [zhangdaiscott/jeecg-boot#2326]
我看项目里面创建了一个demo，并且启动它，
他引用了 starter-cloud -> cloud-api 

启动gateway和colud-system-start就因该可以运行了吧，
之前也看过alibaba的框架，创建demo的原因不是很明白，
我也试了不启动demo，前端无法获取数据
谢谢！！

**Comment by zhangdaiscott** [comment]
？

**Comment by loongw513029** [comment]
我的意思是jeecg-demo 这个服务的作用

**Comment by zhangdaiscott** [comment]
常用示例的功能，就是示例
