### ISSUE TITLE
是否缓存路由好像不太好使哦

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#2327]
##### 问题描述：
在配置界面菜单的时候，勾选是否缓存路由为是，但是发现每次切换到对应菜单tab页签的时候，
页面的数据还是重新初始化请求了一次。并没有把那个页面的内容做缓存。keepAlive这块好像有点问题

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
录个视频看下

**Comment by LeeSheeQee** [comment]
> 录个视频看下

我也遇到了，第一次的时候不会缓存，后面就会缓存

**Comment by Nicky213Zhang** [comment]
同，时灵时不灵，有时候以为好了，再用用又发现不行了，特别是不按顺序关闭中间菜单的时候，更明显

**Comment by LeeSheeQee** [comment]
只能看框架的代码是怎么实现的了，然后自己修改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月11日(星期四) 中午11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 是否缓存路由好像不太好使哦 (#2327)





 
同，时灵时不灵，有时候以为好了，再用用又发现不行了，特别是不按顺序关闭中间菜单的时候，更明显

**Comment by tygithub1** [comment]
经测试，没问题！如果发现不可用的情况，如果是自带的菜单，请说明菜单，如果是自己写的代码再配置的新菜单，请把代码贴出来

**Comment by chenzhaoti** [comment]
需要在vue文件里加上name
