### ISSUE TITLE
online表单中添加自定义按钮  , 表单生成代码时, 代码中没有加入按钮.

### ISSUE THREAD

**Issue by Mrxiang** [zhangdaiscott/jeecg-boot#2328]
##### 版本号：

 2.4.2
##### 问题描述：
online表单中添加自定义按钮  , 功能测试时,按钮功能正常.  表单生成代码后, 生成的vue代码中没有加入按钮.

##### 截图&代码：

![QQ图片20210305162122](https://user-images.githubusercontent.com/4049643/110088599-06760700-7dd0-11eb-8382-d20d2676b64f.png)

使用 已带的单表 test_note, 

![QQ图片20210305162131](https://user-images.githubusercontent.com/4049643/110088714-2efe0100-7dd0-11eb-9be7-4d251af4a83d.png)

点击"测试功能", 自定义按钮 是正常的. 点击"生成代码",

 
![QQ图片20210305162559](https://user-images.githubusercontent.com/4049643/110089193-c2373680-7dd0-11eb-84c7-79747cbc1355.png)

 在生成的vue 代码中没有 自定义按钮相关的代码.

![QQ图片20210305162325](https://user-images.githubusercontent.com/4049643/110089195-c2373680-7dd0-11eb-981c-b357664f9a34.png)

在将这个表单添加为其他菜单的子菜单,   这个菜单也没有自定义按钮显示出来.

![QQ图片20210305163813](https://user-images.githubusercontent.com/4049643/110089863-936d9000-7dd1-11eb-8993-5bcd42e10309.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自定义按钮，增强等暂时不支持生成

**Comment by pkaq** [comment]
@zhangdaiscott 那这个功能的意义是啥？好看？
