### ISSUE TITLE
生成代码提示成功，但是什么都没有

### ISSUE THREAD

**Issue by laichenchen** [zhangdaiscott/jeecg-boot#2329]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
1、生成代码为空
解决： 确认下代码路径是否有空格或者中文，去掉空格或者中文就好了
比如：E:/workspace/jeecg-boot-framework
2、JAR方式发布如何使用代码生成器
http://doc.jeecg.com/2043922

**Comment by wang1597538789** [comment]
load template from templateRootDir 
templateRootDir 路径不对也是生成成功 但是什么都没有
templateRootDir 路径不对怎么修改
