### ISSUE TITLE
如何传多个参数到后台报错

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#233]
##### 版本号：

2.1
##### 问题描述：

如何传多个参数到后台报错
##### 截图&代码：

测试 单个值ipo 传后台正常   两个值传后台就是空，  后台代码postman 测试正常
 1、前台请求正常 
![image](https://user-images.githubusercontent.com/5210084/59901628-70991d80-942e-11e9-9d0a-246df5c89114.png)
2 后台 无数据
![image](https://user-images.githubusercontent.com/5210084/59901657-827ac080-942e-11e9-80c9-3861318054ab.png)

vue代码
![image](https://user-images.githubusercontent.com/5210084/59901675-945c6380-942e-11e9-8762-97158fae965b.png)
![image](https://user-images.githubusercontent.com/5210084/59901694-9f16f880-942e-11e9-8a8c-04b158b899d6.png)

**Comment by zhangdaiscott** [comment]
多个值用   POST
