### ISSUE TITLE
开发文档，疑似存在错字

### ISSUE THREAD

**Issue by liuwenlu1006** [zhangdaiscott/jeecg-boot#2332]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/75970537/110199215-4ef5f900-7e92-11eb-95ac-8c7ef8eb0d28.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3Q 这是老jeecg的文档了，建议使用新版jeecgboot
