### ISSUE TITLE
后台搭建使用jeecg-cloud,前台项目无法登录

### ISSUE THREAD

**Issue by TuShengTao** [zhangdaiscott/jeecg-boot#2333]
##### 问题描述：前端项目是2.4.2，后端项目是最新的jeecg-cloud,
前端queryPermissionsByUser函数没有传token参数，后端getUserPermissionByToken获取不到token

##### 截图&代码：

![image](https://user-images.githubusercontent.com/50161350/110239284-197c0900-7f81-11eb-9424-58fa8a57c1a7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg-boot已经支持微服务，jeecg-cloud不维护了，请切换jeecgboot
