### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by xgktv007** [zhangdaiscott/jeecg-boot#2334]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/29972316/110262012-377f5300-7fed-11eb-90e5-4c76c70d1634.png)

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这边测没问题啊

**Comment by xgktv007** [comment]
重新拉取代码后，正常。感谢反馈！

**Comment by xgktv007** [comment]
Git重新拉取代码后正常，感谢反馈！
