### ISSUE TITLE
省市区组件无限递归

### ISSUE THREAD

**Issue by JaylinLee** [zhangdaiscott/jeecg-boot#2335]
##### 版本号：

 2.4.2

##### 问题描述：

前端：ant-design-vue-jeecg\src\components\_util\Area.js => 由于前端库 ”area_data“ 键值存在重复，导致无限递归;

##### 截图&代码：

截图
![1615167249(1)](https://user-images.githubusercontent.com/33442971/110263499-defe8480-7ff1-11eb-8b43-a19ddb2fe0f6.jpg)
![1615167274(1)](https://user-images.githubusercontent.com/33442971/110263500-e02fb180-7ff1-11eb-8d10-ff76c98ce43f.jpg)

代码：
jeecg-boot 省市区组件

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个值重复了？

**Comment by JaylinLee** [comment]
是的，“市”级和”区“级的编码一样这种情况还不只这一个。

我加了个index来索引。。。这办法有点笨但是有效，不过之后Online报表生成后产生了另外的问题

ant-design-vue-jeecg\src\components_util\Area.js 
![1615194752(1)](https://user-images.githubusercontent.com/33442971/110300211-95ce2500-8031-11eb-8d02-0718c0d7b2ab.jpg)

新的问题
![1615195087(1)](https://user-images.githubusercontent.com/33442971/110300799-4b00dd00-8032-11eb-9823-bca75fabe05c.jpg)
![1615195029(1)](https://user-images.githubusercontent.com/33442971/110300797-49cfb000-8032-11eb-966d-49556cc0c4ef.jpg)

**Comment by JaylinLee** [comment]
想知道解析生成省市区字符串的代码

**Comment by tygithub1** [comment]
还是那个文件 getAreaBycode方法调用也要加index判断
