### ISSUE TITLE
atuopoi 2.0.1版本使用word模板导出功能报错

### ISSUE THREAD

**Issue by x522491416** [zhangdaiscott/jeecg-boot#2336]
##### 问题描述：
使用autipoi.exportWord07方法导出报错，报空

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45849273/110282147-f0a75280-8018-11eb-846a-a875ac7ac722.png)

![image](https://user-images.githubusercontent.com/45849273/110282166-fa30ba80-8018-11eb-9ae4-5bb16da37a46.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，待测试

**Comment by lsqGitHub716** [comment]
map里面的字段和word的字段都匹配吗？word里面有没有多余的字段没有在map中设置值

**Comment by x522491416** [comment]
> map里面的分段和word的分段都匹配吗？word里面有没有多余的分段没有在map中设置值
![Uploading image.png…]()

**Comment by lsqGitHub716** [comment]
没有phone字段

**Comment by x522491416** [comment]
> 没有phone字段

我这个修改了的，字段是一样的，麻烦您测试一次
![image](https://user-images.githubusercontent.com/45849273/112407366-edb69c80-8d50-11eb-91f6-1a9e69ccaf16.png)

**Comment by zhangdaiscott** [comment]
```
 <dependency>
            <groupId>com.deepoove</groupId>
            <artifactId>poi-tl</artifactId>
            <version>1.9.1</version>
        </dependency>
```

用这个框架，导出word更简单

**Comment by x522491416** [comment]
> 没有phone字段

我防止因为图片插入的问题，把图片字段已经去掉了，这几个字段已经对照过了

**Comment by x522491416** [comment]
> ```
>  <dependency>
>             <groupId>com.deepoove</groupId>
>             <artifactId>poi-tl</artifactId>
>             <version>1.9.1</version>
>         </dependency>
> ```
> 
> 用这个框架，导出word更简单

好的，我去看看
