### ISSUE TITLE
新建模块启动报错

### ISSUE THREAD

**Issue by HartleyLau** [zhangdaiscott/jeecg-boot#2338]
##### 版本号：
2.4.2

##### 问题描述：
在项目的根目录下新建模块device，添加依赖及Application，添加配置文件，运行报错。
nacos，system，gateway都已经启动

##### 截图&代码：

![Snipaste_2021-03-08_19-00-33](https://user-images.githubusercontent.com/7857624/110313062-e305c300-8040-11eb-851b-dc7094931b97.png)
![Snipaste_2021-03-08_19-00-47](https://user-images.githubusercontent.com/7857624/110313069-e4cf8680-8040-11eb-8691-103763684de0.png)
![Snipaste_2021-03-08_19-01-25](https://user-images.githubusercontent.com/7857624/110313071-e6994a00-8040-11eb-8a2b-3d18ceb154ca.png)
![Snipaste_2021-03-08_19-02-05](https://user-images.githubusercontent.com/7857624/110313082-e9943a80-8040-11eb-9da9-39fca072b444.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你改了路径，jeecg的默认路径没配置的问题
