### ISSUE TITLE
在线表单开发，列表字段长度设置无效

### ISSUE THREAD

**Issue by kin1994** [zhangdaiscott/jeecg-boot#2339]
##### 问题描述：
列表字段长度设置无效

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11944421/110414942-e3976b80-80cb-11eb-9c88-c4c306428cbc.png)
![image](https://user-images.githubusercontent.com/11944421/110415003-0033a380-80cc-11eb-85a9-65fb2f8a169e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本老了
