### ISSUE TITLE
单标生成时,如果表字段过少,vue页面会出错

### ISSUE THREAD

**Issue by fatemimipang** [zhangdaiscott/jeecg-boot#234]
##### 问题描述：当我表字段过少时,生成的vue页面会有问题,在查询条件的模板那少了展开,并会出现</template> 闭标签

<img width="899" alt="屏幕快照 2019-06-22 上午11 19 29" src="https://user-images.githubusercontent.com/51980977/59958854-a8ac6900-94df-11e9-89ed-c1855b951e05.png">
正常的vue页面是这样的:
![Uploading 屏幕快照 2019-06-22 上午11.21.03.png…]()

**Comment by fatemimipang** [comment]
<img width="899" alt="屏幕快照 2019-06-22 上午11 21 03" src="https://user-images.githubusercontent.com/51980977/59958877-26707480-94e0-11e9-8354-8956f29d6ea2.png">

**Comment by zhangdaiscott** [comment]
？ 图标一下

**Comment by fatemimipang** [comment]
有问题的
<img width="899" alt="fail" src="https://user-images.githubusercontent.com/51980977/60063814-c15f8d80-9730-11e9-8308-28231b15d25f.png">
正常的
<img width="899" alt="succ" src="https://user-images.githubusercontent.com/51980977/60063822-cb818c00-9730-11e9-8c1e-cc8a8b7c3b1b.png">

**Comment by fatemimipang** [comment]
图一是生成有问题的,图二是正常的

**Comment by zhangdaiscott** [comment]
ok  我们看看

**Comment by zhangdaiscott** [comment]
已经修正，下个版本发布
