### ISSUE TITLE
Online表单无法按部门授权

### ISSUE THREAD

**Issue by ZevenFang** [zhangdaiscott/jeecg-boot#2342]
##### 版本号：
2.4.2

##### 问题描述：
在线开发->online表单开发->更多，没有权限管理功能，无法按部门授权

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11134329/110469920-2fbace00-8115-11eb-9264-9062873b391f.png)

**Comment by zhangdaiscott** [comment]
收录，规划中

**Comment by tygithub1** [comment]
新版已支持 `v 2.4.3+`
