### ISSUE TITLE
如何通过js增强，控制字段是否可编辑

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2344]
##### 版本号：
2.4.2

##### 问题描述：
如何通过js增强，控制字段是否可编辑
文档中缺少示例

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/110724409-af00ec80-8250-11eb-9297-e3eb40eab1fc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，待补充文档

**Comment by tygithub1** [comment]
目前不支持通过js增强动态控制
