### ISSUE TITLE
启动不了，数据库连接报错

### ISSUE THREAD

**Issue by XiaoChuangYi** [zhangdaiscott/jeecg-boot#2346]
##### 问题描述：Failed to determine a suitable driver class
WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:559 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jimuReportTokenService': Unsatisfied dependency expressed through field 'sysBaseAPI'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysBaseApiImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysLogMapper' defined in file [C:\Users\dell\.babun\cygwin\home\dell\myworkspace\jeecg-boot-2.4.2\jeecg-boot\jeecg-boot-module-system\target\classes\org\jeecg\modules\system\mapper\SysLogMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class

##### 截图&代码：
![image](https://user-images.githubusercontent.com/47819221/110742422-4bd38200-8271-11eb-86b2-95c69989ba55.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
采用什么方式启动、启动的那个类

**Comment by XiaoChuangYi** [comment]
![image](https://user-images.githubusercontent.com/47819221/111016489-4600ac80-83e9-11eb-9a19-70244b1fc158.png)

**Comment by XiaoChuangYi** [comment]
![Uploading image.png…]()

**Comment by XiaoChuangYi** [comment]
![image](https://user-images.githubusercontent.com/47819221/111016534-7ea08600-83e9-11eb-83a8-f05e4be76047.png)
现在是这个问题，debug DynamicRoutingDataSource源码，是datasource没有被初始化进去

**Comment by XiaoChuangYi** [comment]
application-dev.yml文件没有被加载进去

**Comment by XiaoChuangYi** [comment]
打包成jar包是可以run起来的
intellij 版本的问题？！

**Comment by zhangdaiscott** [comment]
环境没弄好

**Comment by XiaoChuangYi** [comment]
什么环境需要特别注意这个版本的项目

**Comment by XiaoChuangYi** [comment]
jdk,maven ,mysql ,redis都没什么问题
