### ISSUE TITLE
关于JSelectBizComponent组件

### ISSUE THREAD

**Issue by aliaizhetaozi** [zhangdaiscott/jeecg-boot#2347]
##### 版本号：
2.2.1

##### 问题描述：
使用JSelectBizComponent仿照用户搜索功能自定义了一个组件，选取数据后，再次查看会显示id而不是指定的name【图片1】。
并且进入选择页后，会默认选中第一条数据而不是之前选择的数据【图片2】

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30401919/110749811-8989d800-827c-11eb-8eb4-a50dc353cdee.png)
![image](https://user-images.githubusercontent.com/30401919/110749899-a9b99700-827c-11eb-84a0-d4ec80f3c488.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自定义的得自己调试
