### ISSUE TITLE
系统用户逻辑删除代码

### ISSUE THREAD

**Issue by tokeneros** [zhangdaiscott/jeecg-boot#2350]
##### 问题描述：
系统管理模块，用户删除会做逻辑删除，这一块的代码没有找到在哪里发生的变更，方便的话，可以告知一下吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41360910/110924780-67b45200-835d-11eb-9652-186b50e5aa32.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Nicky213Zhang** [comment]
![image](https://user-images.githubusercontent.com/25654842/111244615-39c15d00-863e-11eb-997b-128a79ccd1ad.png)
