### ISSUE TITLE
使用过程小建议

### ISSUE THREAD

**Issue by 597800451** [zhangdaiscott/jeecg-boot#2352]
##### 版本号：
2.4.2

##### 问题描述：

在online表单设计过程中的页面属性用 Popup控件 时的字典table使用的是自己创建的报表
其中报表可能存在报表参数，如果此时支持参数传入会更加灵活。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5043738/111065551-5bfb9380-84f5-11eb-8323-d06cf9447f9a.png)

![image](https://user-images.githubusercontent.com/5043738/111065556-69b11900-84f5-11eb-87ed-c8b4ceaded19.png)

报表
![image](https://user-images.githubusercontent.com/5043738/111065589-84838d80-84f5-11eb-8b75-b9e892f26159.png)

本以为可以这样
![image](https://user-images.githubusercontent.com/5043738/111065618-9c5b1180-84f5-11eb-96eb-231b984d1f66.png)

但好像不行，查看代码似乎并不支持
![image](https://user-images.githubusercontent.com/5043738/111065669-c4e30b80-84f5-11eb-9512-854fdbc5bed4.png)
似乎只接收传入的报表名称

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
支持自定义参数
//popup动态参数 支持系统变量语法
![image](https://user-images.githubusercontent.com/3162115/111899121-77bae880-8a65-11eb-9795-ab88d2f1a61b.png)


http://doc.jeecg.com/2044000


http://doc.jeecg.com/2044000
