### ISSUE TITLE
浏览器界面放大放小，数据和输入框的数据会清空，并重新渲染

### ISSUE THREAD

**Issue by tanshion** [zhangdaiscott/jeecg-boot#2358]
##### 版本号：
2.x 版本都有问题

##### 问题描述：
浏览器界面放大放小，数据和输入框的数据会清空，并重新渲染

##### 截图&代码：

![image](https://user-images.githubusercontent.com/9196558/111410018-ed941c80-8712-11eb-8bbc-b83c82410e7a.png)

![image](https://user-images.githubusercontent.com/9196558/111410146-28965000-8713-11eb-9ac9-34a7272a255a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/804
