### ISSUE TITLE
能否把单体和微服务拆分成两个模块？

### ISSUE THREAD

**Issue by oldtime0726** [zhangdaiscott/jeecg-boot#2361]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/20368103/111609001-ccb3f000-8814-11eb-8983-7030e273a6f4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/111871507-6de1a880-89c5-11eb-99d0-23e5e9123444.png)

不需要 微服务，这俩模块删掉即可
