### ISSUE TITLE
用户名称检查有安全漏洞，可以字典猜测破解密码

### ISSUE THREAD

**Issue by chenshaoqin4796** [zhangdaiscott/jeecg-boot#2362]
##### 版本号：
2.2.X - 2.4.X

##### 问题描述：

用户名称检查有安全漏洞，可以字典猜测破解密码

##### 截图&代码：
src\main\java\org\jeecg\modules\system\controller\SysUserController.java

![image](https://user-images.githubusercontent.com/76674393/111720893-c3b93200-8899-11eb-8afa-a32988090bf6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录感谢
