### ISSUE TITLE
验证码加载404

### ISSUE THREAD

**Issue by autumnLei** [zhangdaiscott/jeecg-boot#2363]
##### 版本号：
2.4.3

##### 问题描述：
验证码加载不出来，外网内网都不行
https://github.com/zhangdaiscott/jeecg-boot/issues/1228 试了这个也不行
##### 截图&代码：
<img width="488" alt="企业微信截图_cf7386b5-8cfe-427b-ad43-4616fc5745ce" src="https://user-images.githubusercontent.com/26919908/111740651-1574b300-88c0-11eb-8c6d-fe686d90407b.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台服务接口配置了吗

**Comment by autumnLei** [comment]
要先配置后台接口吗 我还以为完全分离没后台也能看效果

**Comment by WangHao1221** [comment]
请问一下后台接口怎么配置呀，我也是直接拉下来跑前端发现验证码404，是因为后台没开启，请问怎么弄

**Comment by zhangdaiscott** [comment]
需要后台，验证码是后台的接口

**Comment by WangHao1221** [comment]
如何开启后台？这个流程在哪里 请提供一下 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JEECG开源社区 ***@***.***&gt;
发送时间: 2021年4月8日 10:52
收件人: zhangdaiscott/jeecg-boot ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[zhangdaiscott/jeecg-boot] 验证码加载404 (#2363)

**Comment by WangHao1221** [comment]
> 后台服务接口配置了吗

有后台配置和启动的相关文档吗？谢谢

**Comment by ProwDong** [comment]
> > 后台服务接口配置了吗
> 
> 有后台配置和启动的相关文档吗？谢谢

这个地址：http://doc.jeecg.com/2043873
