### ISSUE TITLE
jeecg-boot一定要依赖alibaba全家桶么？

### ISSUE THREAD

**Issue by w6m6** [zhangdaiscott/jeecg-boot#2366]
##### 版本号：
2.4.3

##### 问题描述：

jeecg-boot一定要依赖alibaba全家桶么？目前公司项目依赖的都是eureka，apollo，等等。
总不能又来一套吧。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的
