### ISSUE TITLE
无法访问org.jeecg.common.util.jsonschema.validate

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#2367]
##### 问题描述：
导入数据库以后，执行maven安装报错。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9925064/111954355-ef028200-8b22-11eb-9254-2e09e388ae3b.png)

![image](https://user-images.githubusercontent.com/9925064/111954266-caa6a580-8b22-11eb-8036-af76e0294bd4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
clean试试，你这个错没遇到过

**Comment by CharlieJ0hn** [comment]
clean也是一样的错误，直接pull下来就这样了。我感觉是pom有问题。
