### ISSUE TITLE
微服务下数据权限bug

### ISSUE THREAD

**Issue by han1396735592** [zhangdaiscott/jeecg-boot#2369]
##### 版本号：
2.1.3.RELEASE

##### 问题描述：
微服务下数据权限错误问题。`system`服务下线，业务系统在线。访问业务系统是：通过 `FeignClient` 查询权限时，会进入`fallback`函数，但是 `fallback`默认返回了 `null`, 数据权限切面处理类(**PermissionDataAspect**) 则认为没有匹配到权限数据规则，不注入数据拦截过滤规则，造成数据严重外泄。

- 2.1.3 版本存在该问题，最新版本是否已经解决，如已经解决，解决方法是?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by accpman** [comment]
system服务目前作为底层基础服务，是不允下线的
