### ISSUE TITLE
前端报路由dashboard不存在

### ISSUE THREAD

**Issue by li-yx** [zhangdaiscott/jeecg-boot#237]
##### 问题描述：[vue-router] Route with name 'dashboard' does not exist

在登录时，前端报路由dashboard不存在， 

##### 截图&代码：      loginSuccess () {
        this.loginBtn = false
        this.$router.push({ name: 'dashboard' })  ----------路由找不到
        this.$notification.success({
          message: '欢迎',
          description: `${timeFix()}，欢迎回来`,
        });
      },

**Comment by zhangdaiscott** [comment]
截图看看

**Comment by li-yx** [comment]
搞错了，是用户的权限问题。 已经解决了。
