### ISSUE TITLE
elasticsearch做一个全文检索遇到的问题

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2371]
##### 版本号：
v2.4.3

##### 问题描述：
elasticsearch 高级查询介绍不太全面？为什么看代码只是做了mybatisPlus的拼接，跟elasticsearch没什么关系？
JeecgElasticsearchTemplate这个es工具也没有用起来呀，想要集成使用elasticsearch应该怎么做？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33947373/112074058-561a4800-8bb0-11eb-9be9-f71928ee4184.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
开源部分没用到ES，你需要可以自己优化下
