### ISSUE TITLE
代码启动后访问会报错

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2372]
##### 版本号：
v2.4.3

##### 问题描述：
启动代码后，登录页面访问验证码会报错，等10分钟再访问就好了，错误信息中不包含业务代码具体行号，请问这个是什么问题？异常如下：
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe

##### 截图&代码：

![image](https://user-images.githubusercontent.com/33947373/112077335-418d7e00-8bb7-11eb-9ac8-e4cb8620c600.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没遇到过，你得自己排查
