### ISSUE TITLE
有菜单缓存的tab切换到没有菜单缓存的tab会请求有菜单缓存页面的接口

### ISSUE THREAD

**Issue by wumingluren** [zhangdaiscott/jeecg-boot#2373]
##### 问题描述：从有菜单缓存的tab切换到没有菜单缓存的tab会请求有菜单缓存页面的
loadData 和 initDictConfig方法，在2.1.1测试的时候方法体里面也获取不到有缓存页面输入的查询参数，并且有缓存页面的数据并没有被重复请求的数据覆盖掉。
2.4.3是在演示站看的，也有调用有缓存页面接口的问题。

##### 截图&代码：
![34ed68ad3bd8b58e5fe50dc1e559b17](https://user-images.githubusercontent.com/41581133/112081170-2ffba480-8bbe-11eb-9dfb-cd535de73907.png)

**Comment by wumingluren** [comment]
在演示站的操作是：查询表格页面（无缓存路由-且没有查询接口）   流程设计（有缓存路由），先打开查询表格，在打开流程设计，再切换回查询表格就会看到，流程设计页面的接口被调用了。

**Comment by zhangdaiscott** [comment]
得看菜单的配置 “是否缓存”

**Comment by wumingluren** [comment]
> 得看菜单的配置 "是否缓存"

你可能没有看清楚问题描述，是从有缓存菜单跳转到没有缓存的菜单，有缓存的菜单接口被执行了一次，不是说没缓存的的菜单接口被执行了。

没有缓存的页面也不应该去请求上个被缓存了的页面的接口啊。
