### ISSUE TITLE
jeecgboot没有单体版本吗 不想使用微服务

### ISSUE THREAD

**Issue by mawencai-oss** [zhangdaiscott/jeecg-boot#2374]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
默认就是单体的，删除这俩模块就行
![image](https://user-images.githubusercontent.com/3162115/112090604-d0f25b80-8bce-11eb-98b1-c794972b7d00.png)
