### ISSUE TITLE
微服务模式部署下，nacos的账户密码如果不使用默认提供的nacos/nacos，会导致gateway读取路由信息失败

### ISSUE THREAD

**Issue by slppls** [zhangdaiscott/jeecg-boot#2375]
##### 版本号：
v2.4.3

##### 问题描述：
如果是自己配置的nacos，且账户密码不为nacos/nacos，且在修改了parent/boot-starter下的cloud模块的nacos相关参数，启动gateway的时候，虽然可以正常读取应用的配置，但是读取路由信息文件(route.json)失败，经过debug跟踪，发现gateway项目内对于路由信息读取，如果为nacos类型，会重新创建一次nacos的配置信息进行读取路由信息，但是没有自定义的nacos账户密码配置，因此导致访问nacos出现403，读取失败

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18140796/112110614-212ce600-8bee-11eb-907a-77003d5e6310.png)
![image](https://user-images.githubusercontent.com/18140796/112110613-212ce600-8bee-11eb-83ad-1eaedfc22c4e.png)
目前我这边的做法是直接设置读取了boot-starter-cloud模块下的nacos的账户密码进行置入，问题解决。

不清楚是否我自己的项目启动方式有误还是真的是这里出现了问题，望指教

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
修改默认密码确实需要加入配置，你理解的没错，感谢分享

**Comment by zhangdaiscott** [comment]
已经修复
