### ISSUE TITLE
官方仓库该更新了

### ISSUE THREAD

**Issue by wangleigithub** [zhangdaiscott/jeecg-boot#2376]
##### 版本号：
2.4.3

##### 问题描述：

官方仓库又没有更新2.43的依赖，但是master分支中的POM版本号全部升级了。
又是一次rollback，这样的情况2.4.2也出现过
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
私服上有2.4.3 建议配置jeecg私服
http://doc.jeecg.com/2043876

**Comment by wangleigithub** [comment]
已经加了私服设置了，jeecg的私服上没有更新啊，http://maven.jeecg.org/nexus/content/repositories/jeecg/org/jeecgframework/boot/jeecg-boot-parent/

**Comment by zhangdaiscott** [comment]
上传了，我们不太建议上传这个，base的逻辑大家会自己改

**Comment by wangleigithub** [comment]
base里面会改的应该就是个commonapi，其他的逻辑改了的话，不是你推荐的最佳实践啊
