### ISSUE TITLE
代码生成器生成成功但是没有任何代码

### ISSUE THREAD

**Issue by wang1597538789** [zhangdaiscott/jeecg-boot#2377]
##### 版本号：
2.4

##### 问题描述：
代码生成器生成成功但是没有任何代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32223833/112250236-fe550d00-8c93-11eb-869c-a08cf5036415.png)
已经排查了生成路径的问题。
经查发现控制台输出的信息中templateRootDir路径不对
![image](https://user-images.githubusercontent.com/32223833/112250170-ea111000-8c93-11eb-92b5-746b011c8f8d.png)
请问这种情况如何解决

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jar发布？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043922

**Comment by wang1597538789** [comment]
不是jar 是本地代码调试的时候

**Comment by wang1597538789** [comment]
我弄错了 调试选的jar
