### ISSUE TITLE
缺少表 jeecg-boot.user_tab_cols

### ISSUE THREAD

**Issue by sweethuaihaizi** [zhangdaiscott/jeecg-boot#2379]
##### 版本号：
V2.4.3

##### 问题描述：
代码生成报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33407039/112267774-ecce2e00-8cb0-11eb-9e67-60f931e96e31.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是你自己的表
