### ISSUE TITLE
导入比较大excel文件，500+数据，报数据库连接关闭

### ISSUE THREAD

**Issue by linekite** [zhangdaiscott/jeecg-boot#238]
##### 版本号：
2.0.1 版本

##### 问题描述：
导入比较大excel文件，500+数据，报数据库连接关闭

##### 截图&代码：
 文件导入失败:Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Tue Jun 25 16:03:55 CST 2019.

**Comment by zhangdaiscott** [comment]
excel数据提供下

**Comment by linekite** [comment]
[全部库存.xls.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3325501/xls.zip)

**Comment by zhangdaiscott** [comment]
建议把插入改成批量插入试试

**Comment by zhangdaiscott** [comment]
我们最新版，导入改成批量插入，一万条数据，插入没有任何压力，请参考
