### ISSUE TITLE
关于Nacos的config问题

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#2381]
##### 版本号：

2.4.3
##### 问题描述：
cloud环境下，使用nacos作为配置中心，jeecg-system加载的是jeecg.yml和jeecg-dev.yml这两个配置文件，这个都没有问题。假如现在有一个订单服务，也是加载的这两个配置文件，如果订单服务连接的是另一个数据（比如：order-db）或者有一些个性化的配置，貌似没有地方去修改数据库的jdbc配置了，因为jeecg-dev.yml这个文件已经配置了jdbc连接（spring.datasource.druid.datasource.master.url: jdbc:mysql://172.20.5.50:3306/jeecg-boot），请问这个该怎么解决？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2188439
