### ISSUE TITLE
JImageUpload组件单张无法预览

### ISSUE THREAD

**Issue by csainx** [zhangdaiscott/jeecg-boot#2382]
##### 版本号：
2.3-2.4

##### 问题描述：

JImageUpload组件，转为单张上传的情况下，上传后无法删除和预览，只能重新上传
##### 截图&代码：

![temp](https://user-images.githubusercontent.com/50067476/112277811-17be7f00-8cbd-11eb-9122-1a8a1bca0d41.jpg)

期望不管单张还是多张的情况下，都可以有预览和删除按钮

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
已修改 `version 2.4.3+`

**Comment by csainx** [comment]
什么时间可以发布呀？
