### ISSUE TITLE
POP弹出框选中一项时默认选中所有项

### ISSUE THREAD

**Issue by Admin2020-qixia** [zhangdaiscott/jeecg-boot#2385]
版本号：2.4.2

 问题描述：POP弹出框选中一项时默认选中所有项
![2021-03-25_203746](https://user-images.githubusercontent.com/62987999/112473988-fbe4d700-8da9-11eb-8f8c-0846714d0fcd.png)

截图&代码：
![2021-03-25_203309](https://user-images.githubusercontent.com/62987999/112473886-e2dc2600-8da9-11eb-824e-bf83b6d659a1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己写的吗？自己写的话，得自己排查，如果是我们的例子功能，请详细说明具体位置如何重现
