### ISSUE TITLE
hystrix和sentinel同时使用?

### ISSUE THREAD

**Issue by chenshanhai-mc** [zhangdaiscott/jeecg-boot#2386]
##### 问题描述：
jeecg-boot-starter-cloud 模块依赖的是sentinel,  jeecg-cloud-gateway用的还是hystrix, 为啥不统一使用sentinel呢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
java框架的技术方案本就多样化，萝卜白菜各有所爱而已，如果你喜欢用自己看好的框架，自行改造就可以
