### ISSUE TITLE
2.4.3菜单微服务redis监控打开报错

### ISSUE THREAD

**Issue by chenshanhai-mc** [zhangdaiscott/jeecg-boot#2389]
##### 问题描述：
微服务启动, 菜单 统计报表->redis监控打开报错, , 数据请求的路径是 http://localhost:9999/jmreport/getQueryInfo?reportId=xxx , 

从2.4.2升2.4.3增量sql文件来看, 是升级版本的时候加上的这个菜单

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25859421/112613801-7a4d8180-8e5b-11eb-8eb2-0cb189117be3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by hou649726274** [comment]
这个问题我也发现了。主要还是token的问题
