### ISSUE TITLE
调用字典列表时，未过滤“是否启用”为0的数据

### ISSUE THREAD

**Issue by ares007** [zhangdaiscott/jeecg-boot#239]
##### 版本号：
2.0.1

##### 问题描述：
调用字典列表时，未过滤“是否启用”为0的数据

##### 截图&代码：
jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/mapper/xml/SysDictMapper.xml

queryDictItemsByCode
增加
and s.status=1

**Comment by zhangdaiscott** [comment]
特意不过滤，这样可以保证老数据字典可以正常使用
