### ISSUE TITLE
online报表，给某一列设置合计属性后，每页会多出一条空行，导致分页总数合计不对，还会导致ref子页中的数据每页都加一个空行

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/jeecg-boot#2390]
##### 版本号：
2.4.3

##### 问题描述：
online报表配置设计的报表：
1、给某一列设置合计属性后，每页会多出一条空行，导致分页总数合计不对，还会导致ref子页中的数据每页都加一个空行
2、日期类型字段设置查询模式为“范围查询”后，两个日期框的长度太窄

##### 截图&代码：见录屏

https://user-images.githubusercontent.com/40649464/112636216-bdb5e900-8e77-11eb-8f58-bf7b9b777baa.mp4

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，待测试

**Comment by sjlei** [comment]
关于“导致ref子页中的数据每页都加一个空行”这个问题，由于合计功能的实现方式，就是给dataSource里添加一行，所以这个问题暂时无法解决，可以自行处理，去掉空行。

**已修复：**
* 给某一列设置合计属性后，每页会多出一条空行，导致分页总数合计不对。

**未复现：**
* 日期类型字段设置查询模式为“范围查询”后，两个日期框的长度太窄
   *  可能是分辨率或者窗口大小的问题
![image](https://user-images.githubusercontent.com/34293221/113683244-8d334200-96f6-11eb-9845-09082723c212.png)

**Comment by africaadonis** [comment]
“可以自行处理，去掉空行。”能给个思路吗？这个封装的啊！

**Comment by sjlei** [comment]
> “可以自行处理，去掉空行。”能给个思路吗？这个封装的啊！

基本思路就是用 `splice`方法截取最后一行啊，例如：`dataSource.splice(dataSource.length-1,1)`
你可以贴出来你的代码，看看你是怎么用的，然后我再看看怎么写。
