### ISSUE TITLE
代码生成的疑问：自定义列的按钮

### ISSUE THREAD

**Issue by masaiaaaa** [zhangdaiscott/jeecg-boot#2392]
##### 截图&代码：

![自定义列](https://user-images.githubusercontent.com/49604210/112743917-2e6f1980-8fce-11eb-89a3-cdcd5ff46655.PNG)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自定义按钮目前还不支持生成，生成后手工merge吧
