### ISSUE TITLE
代码生成疑问：表关系是一对一，生成的代码用list？

### ISSUE THREAD

**Issue by masaiaaaa** [zhangdaiscott/jeecg-boot#2393]
##### 截图&代码：@ExcelCollection(name="学员基本信息表")
	@ApiModelProperty(value = "学员基本信息表")
	private List<StuBaseInfo> stuBaseInfoList;
	@ExcelCollection(name="联系信息表")
	@ApiModelProperty(value = "联系信息表")
	private List<ContactInfo> contactInfoList;
![一对一](https://user-images.githubusercontent.com/49604210/112743991-b2290600-8fce-11eb-973c-1088eecccc35.PNG)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你先通过功能测试，看看是不是一对一的模型，确认是的话，
再生成看看，最好给给录屏图
