### ISSUE TITLE
在线开发代码生成为空

### ISSUE THREAD

**Issue by freeorder** [zhangdaiscott/jeecg-boot#2394]
##### 版本号：
2.4.2

##### 问题描述：
生成代码显示生成成功，但是没有生成任何文件，前后台也没有报错
跑项目的时候还会报一个LoggingFailureAnalysisReporter错误

##### 截图&代码：
![QQ图片20210329170946](https://user-images.githubusercontent.com/18523630/112814187-96e2f700-90b1-11eb-97d2-228d21b53eb7.png)
![QQ图片20210329171017](https://user-images.githubusercontent.com/18523630/112814233-a5c9a980-90b1-11eb-91a0-95c292dcc11c.png)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2088984
