### ISSUE TITLE
微服务前端（微前端）拆分问题

### ISSUE THREAD

**Issue by huangguocai** [zhangdaiscott/jeecg-boot#2395]
##### 截图&代码：
微服务后台拆开了，前端是不是也得拆，不然前端部署也是一大难题，想问一下这一块平台这边有没有考虑对应的方案

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不需要拆，前端是一体的，有兴趣的可以百度下微前端
