### ISSUE TITLE
菜单页配置积木报表产生的token bug

### ISSUE THREAD

**Issue by hou649726274** [zhangdaiscott/jeecg-boot#2397]
##### 版本号：
jeecg 2.4.3
jimu 1.2.1

##### 问题描述：
将自己建立的“积木报表”按照文档规范配置到菜单页后，首次登陆直接点击自己配置的积木报表，会出现后台报错。Token失效，请重新登录!（为了数据安全，开了权限验证，shiro代码里面注释掉了jimureport）
菜单页面配置的：
{{ window._CONFIG['domianURL'] }}/jmreport/view/609a2aa29ab4c1e8a8c72a90f425533b?token=${token}
经过我的排查，发现如果先点击 jeecg默认自带的积木报表二级菜单链接，再点击自己配置的积木报表就不会出现报错。但是这个问题还是个bug，希望能得到解决~
代码报错主要在org.jeecg.config.shiro.filters.JwtFilter的executeLogin() 的 getSubject(request, response).login(jwtToken);
首次登录 即访问 自己配置的积木报表jwtToken是能获取到的，但是这个方法仍旧抛出异常。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7751899/112982931-a46eae80-918f-11eb-8cbe-ff7918b87266.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
1.升级依赖到最新版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta</version>
</dependency>
```
2.参考文档
http://report.jeecg.com/2208864
