### ISSUE TITLE
直接拉下来就跑不起来

### ISSUE THREAD

**Issue by CharlieJ0hn** [zhangdaiscott/jeecg-boot#2399]
##### 版本号：
github 当前最新的代码，2.4.3

##### 问题描述：
现在主分支的代码运行时有一些问题，我找了好几个人分别跑，没人能跑起来。
建议您拉一下这份代码跑一下，我这边没有找到确切的原因，无法详细反馈给您。

还有一个问题，目前是依然需要私服吗？还是已经完全上中央仓库，看提交记录反复修改。
现在不管是否设置私服都跑不起来。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9925064/113107086-10a3ed80-9236-11eb-83a7-25519c190873.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你这依赖下载不成功，自己先排查问题
![image](https://user-images.githubusercontent.com/3162115/113107851-f8809e00-9236-11eb-8773-a8244986e4bb.png)

**Comment by CharlieJ0hn** [comment]
我这里排插了我的网络问题，代码github和gitee都试过了。现在需要私服吗？

**Comment by zhangdaiscott** [comment]
https://search.maven.org/artifact/com.baomidou/dynamic-datasource-spring-boot-starter/3.3.0/jar

**Comment by CharlieJ0hn** [comment]
嗯，确实是拉库问题。谢谢您。
