### ISSUE TITLE
希望可以提供react版本的前端

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#24]
看截图，使用的是antd pro的前端，这个前端是react系的，希望可以支持react的前端，这样前端层面上可以更好的合并上游的新特性、改进。

**Comment by zhangdaiscott** [comment]
目前精力有限，暂时只提供 vue 和 angular的版本

**Comment by liudonghua123** [comment]
@zhangdaiscott 嗯，还有angular版本，没找到在哪呀？
