### ISSUE TITLE
【建议】xml的生成建议还是同时生成resultMap，方便后期做二次开发联表查询的时候使用。

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#240]
##### 版本号：
2.0

##### 问题描述：
xml的生成建议还是同时生成resultMap，方便后期做二次开发联表查询的时候使用。

**Comment by zhangdaiscott** [comment]
没明白

**Comment by gudufun** [comment]
> 没明白

就是在mapper的xml里面，如果没有resultMap，那么做二次开发的时候，若有联表查询操作，就需要自己重新去定义这个表的resultMap。

**Comment by galaxist** [comment]
干嘛要定义map？直接定义一个vo不是更好，还能实现导出。比你这个好用多了 
![image](https://user-images.githubusercontent.com/3365218/60252689-41d2e980-98fd-11e9-874f-561bff227f34.png)
![image](https://user-images.githubusercontent.com/3365218/60252722-53b48c80-98fd-11e9-8a50-dff45f253fc3.png)

**Comment by gudufun** [comment]
> 干嘛要定义map？直接定义一个vo不是更好，还能实现导出。比你这个好用多了
> ![image](https://user-images.githubusercontent.com/3365218/60252689-41d2e980-98fd-11e9-874f-561bff227f34.png)
> ![image](https://user-images.githubusercontent.com/3365218/60252722-53b48c80-98fd-11e9-8a50-dff45f253fc3.png)

那联表查询的呢？你如何处理？

**Comment by galaxist** [comment]
不是跟你说了专门定义一个vo吗？我这个就是专门定义的报表展示导出一个搞定。
![image](https://user-images.githubusercontent.com/3365218/60254580-ca9f5480-9900-11e9-8811-435a0f09dc24.png)

**Comment by gudufun** [comment]
> 不是跟你说了专门定义一个vo吗？我这个就是专门定义的报表展示导出一个搞定。
> ![image](https://user-images.githubusercontent.com/3365218/60254580-ca9f5480-9900-11e9-8811-435a0f09dc24.png)

你这样只能把所有字段都放到vo里面。如果遇到vo的嵌套就不行了。

**Comment by galaxist** [comment]
jeecg-boot本来就是个单表或简单1对多的代码生成器，如果你要做成嵌套map，那同名字段怎么搞呢？随机加123后缀吗？

**Comment by gudufun** [comment]
> jeecg-boot本来就是个单表或简单1对多的代码生成器，如果你要做成嵌套map，那同名字段怎么搞呢？随机加123后缀吗？

可以设定别名。但是，这样就需要使用到resultMap。而resultMap没有生成，导致需要自己去写resultMap。我的意思就是设定一个resultMap放在xml里面。需要用的时候就直接复制或者继承。当然，这个需求不做也可以，因为我现在的处理就是找一个mybatis的生成器，那个会自动生成resultMap。然后在需要的时候先生成，然后再复制进来。

**Comment by galaxist** [comment]
如果只是个空map 。自己在resources/jeecg/code-template下面自己改一下咯
