### ISSUE TITLE
jar包问题

### ISSUE THREAD

**Issue by madingludeAu** [zhangdaiscott/jeecg-boot#2400]
##### 版本号：

2.4.3
##### 问题描述：
私服地址配置了，该jar包下载不下来（其余jar包可以下载下来），无法通过编译

##### 截图&代码：
               <dependency>
			<groupId>org.jeecgframework.jimureport</groupId>
			<artifactId>spring-boot-starter-jimureport</artifactId>
			<version>1.2.1</version>
			<exclusions>
				<exclusion>
					<groupId>org.jeecgframework</groupId>
					<artifactId>autopoi-web</artifactId>
				</exclusion>
			</exclusions>
	           </dependency>
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
更新代码吧>1.2.1>1.2.0
