### ISSUE TITLE
前台代码制作docker镜像，容器启动报错

### ISSUE THREAD

**Issue by freeorder** [zhangdaiscott/jeecg-boot#2402]
##### 版本号：
2.4.2

##### 问题描述：
按照官方文档制作docker镜像，使用命令docker run --name jeecg-boot-nginx -p 80:80 -d nginx:jeecgboot后，前台项目docker容器启动失败报错， host not found in upstream "jeecg-boot-system"
##### 截图&代码：

![6}GZM}~_17Z8}_5J7C8W8)B](https://user-images.githubusercontent.com/18523630/113172221-cd1fa280-927a-11eb-87dd-59b1c57ad39d.png)

![image](https://user-images.githubusercontent.com/18523630/113172316-e7598080-927a-11eb-8e67-6921a70a32c3.png)

**Comment by zhangdaiscott** [comment]
本地配置host，或者改成其他的
![image](https://user-images.githubusercontent.com/3162115/113232381-9aec6000-92cf-11eb-8678-5bbd46ba90ee.png)

**Comment by freeorder** [comment]
OK，已解决，非常感谢
