### ISSUE TITLE
适配pc端不同屏幕的大小

### ISSUE THREAD

**Issue by cheng11231456** [zhangdaiscott/jeecg-boot#2403]
##### 版本号：
    "@antv/data-set": "^0.11.4",
    "@jeecg/antd-online-mini": "2.3.0",
    "@tinymce/tinymce-vue": "^2.1.0",
    "@toast-ui/editor": "^2.1.2",
    "ant-design-vue": "^1.7.3",
##### 问题描述：
下载postcss-px2rem与px2rem-loader依赖后发现与@jeecg/antd-online-mini的依赖包冲突，经过排查后发现，css文件中使用了less语法导致项目无法运行。

##### 截图&代码：

![Uploading image.png…]()

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
增加less支持？
