### ISSUE TITLE
excel导出 字段内容添加下划线

### ISSUE THREAD

**Issue by guicaimayongjian** [zhangdaiscott/jeecg-boot#2404]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32028870/113237934-6205b880-92da-11eb-853e-3f1474bb2d66.png)

![image](https://user-images.githubusercontent.com/32028870/113238042-90839380-92da-11eb-9c81-670c83cdaf12.png)
  */
    @RequestMapping(value = "/exportXls")
    public ModelAndView exportXls(HttpServletRequest request, YtzmqTz ytzmqTz ) {
        // Step.1 组装查询条件
        QueryWrapper<YtzmqTz> queryWrapper = QueryGenerator.initQueryWrapper(ytzmqTz, request.getParameterMap());
        LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();

        // Step.2 获取导出数据
        List<YtzmqTz> pageList = ytzmqTzService.list(queryWrapper);
        List<YtzmqTz> exportList = null;
        for(YtzmqTz misson : pageList){
            String dutyDepartId = misson.getDutyDepart();
            LambdaQueryWrapper<SysDepart> query1 = new LambdaQueryWrapper<>();
            query1.eq(SysDepart::getId, dutyDepartId);
            SysDepart sysDepart1 = sysDepartService.getOne(query1);
            misson.setDutyDepartName(sysDepart1.getDepartName());

            String leadingDepartId = misson.getLeadingDepart();
            LambdaQueryWrapper<SysDepart> query2 = new LambdaQueryWrapper<>();
            query2.eq(SysDepart::getId, leadingDepartId);
            SysDepart sysDepart2 = sysDepartService.getOne(query2);
            misson.setLeadingDepartName(sysDepart2.getDepartName());

            String projectId = misson.getProjectId();
            LambdaQueryWrapper<YtzmqProject> query3 = new LambdaQueryWrapper<>();
            query3.eq(YtzmqProject::getId, projectId);
            YtzmqProject ytzmqProject = ytzmqProjectService.getOne(query3);
            misson.setProjectName(ytzmqProject.getProjectName());

            String chargePerson = misson.getChargePerson();
            LambdaQueryWrapper<SysUser> query4 = new LambdaQueryWrapper<>();
            query4.eq(SysUser::getId, chargePerson);
            SysUser sysUser2 = sysUserService.getOne(query4);
            misson.setChargePersonName(sysUser2.getUsername());

            String missionId = misson.getId();
            LambdaQueryWrapper<YtzmqMissionManage> query5 = new LambdaQueryWrapper<>();
            query5.eq(YtzmqMissionManage::getMissionId, missionId);
            query5.eq(YtzmqMissionManage::getMissionType, 'A');
            List<YtzmqMissionManage> missionManageList1 = ytzmqMissionManageService.list(query5);
            String missionContext1 = "";
            for (int j=0;j<missionManageList1.size();j++){
                if(oConvertUtils.isNotEmpty(missionManageList1.get(j).getUpdateTime())) {
                    if (isValidDate(missionManageList1.get(j).getUpdateTime())) {
                        missionContext1 += "(当月修改部分）" + (j + 1) + "." + missionManageList1.get(j).getMissionContext() + "\r\n";
                    } else {
                        missionContext1 += (j + 1) + "." + missionManageList1.get(j).getMissionContext() + "\r\n";
                    }
                }else{
                    missionContext1 += (j + 1) + "." + missionManageList1.get(j).getMissionContext() + "\r\n";
                }
            }
            misson.setMissionDocumentId(missionContext1);

            LambdaQueryWrapper<YtzmqMissionManage> query6 = new LambdaQueryWrapper<>();
            query6.eq(YtzmqMissionManage::getMissionId, missionId);
            query6.eq(YtzmqMissionManage::getMissionType, 'B');
            List<YtzmqMissionManage> missionManageList2 = ytzmqMissionManageService.list(query6);
            String missionContext2 = "";
            for (int j=0;j<missionManageList2.size();j++){
                if(oConvertUtils.isNotEmpty(missionManageList2.get(j).getUpdateTime())){
                    if(isValidDate(missionManageList2.get(j).getUpdateTime())){
                        missionContext2 += "(当月修改部分）"+(j+1)+"." + missionManageList2.get(j).getMissionContext()+"\r\n";
                    }else{
                        missionContext2 +=  (j+1)+"." + missionManageList2.get(j).getMissionContext()+"\r\n";
                    }
                }else{
                    missionContext2 +=  (j+1)+"." + missionManageList2.get(j).getMissionContext()+"\r\n";
                }
            }
            misson.setInnovationPoint(missionContext2);

            LambdaQueryWrapper<YtzmqMissionManage> query7 = new LambdaQueryWrapper<>();
            query7.eq(YtzmqMissionManage::getMissionId, missionId);
            query7.eq(YtzmqMissionManage::getMissionType, 'C');
            List<YtzmqMissionManage> missionManageList3 = ytzmqMissionManageService.list(query7);
            String missionContext3 = "";
            for (int j=0;j<missionManageList3.size();j++){
                if(oConvertUtils.isNotEmpty(missionManageList3.get(j).getUpdateTime())){
                    if(isValidDate(missionManageList3.get(j).getUpdateTime())){
                        missionContext3 += "(当月修改部分）"+(j+1)+"." + missionManageList3.get(j).getMissionContext()+"\r\n";
                    }else{
                        missionContext3 +=  (j+1)+"." + missionManageList3.get(j).getMissionContext()+"\r\n";
                    }
                }else{
                    missionContext3 +=  (j+1)+"." + missionManageList3.get(j).getMissionContext()+"\r\n";
                }
            }
            misson.setNextStep(missionContext3);

            LambdaQueryWrapper<YtzmqMissionManage> query8 = new LambdaQueryWrapper<>();
            query8.eq(YtzmqMissionManage::getMissionId, missionId);
            query8.eq(YtzmqMissionManage::getMissionType, 'D');
            List<YtzmqMissionManage> missionManageList4 = ytzmqMissionManageService.list(query8);
            String missionContext4 = "";
            for (int j=0;j<missionManageList4.size();j++){
                if(oConvertUtils.isNotEmpty(missionManageList4.get(j).getUpdateTime())){
                    if(isValidDate(missionManageList4.get(j).getUpdateTime())){
                        missionContext4 += "(当月修改部分）"+(j+1)+"." + missionManageList4.get(j).getMissionContext()+"\r\n";
                    }else{
                        missionContext4 +=  (j+1)+"." + missionManageList4.get(j).getMissionContext()+"\r\n";
                    }
                }else{
                    missionContext4 +=  (j+1)+"." + missionManageList4.get(j).getMissionContext()+"\r\n";
                }
            }
            misson.setDifficultProblem(missionContext4);
            String documentList = misson.getPolicyDocument();
            if(oConvertUtils.isNotEmpty(documentList)) {
                String[] arr = documentList.split(",");
                QueryWrapper<YtzmqDocument> query9 = new QueryWrapper<>();
                query9.in("id", arr);
                List<YtzmqDocument> documentList1 = ytzmqDocumentService.list(query9);
                String missionContext5 = "";
                for (int j=0;j<documentList1.size();j++){
                    if(oConvertUtils.isNotEmpty(documentList1.get(j).getUpdateTime())){
                        if(isValidDate(documentList1.get(j).getUpdateTime())){
                            missionContext5 += "(这里面的字段内容需要添加下划线）"+(j+1)+"." + documentList1.get(j).getDocumentName()+"\r\n";
                        }else{
                            missionContext5 +=  (j+1)+"." + documentList1.get(j).getDocumentName()+"\r\n";
                        }
                    }else{
                        missionContext5 +=  (j+1)+"." + documentList1.get(j).getDocumentName()+"\r\n";
                    }
                }
                misson.setPolicyDocument(missionContext5);
            }
        }
        exportList = pageList;

        // Step.3 AutoPoi 导出Excel
        ModelAndView mv = new ModelAndView(new JeecgEntityExcelView());
        mv.addObject(NormalExcelConstants.FILE_NAME, "烟台市自贸区工作台账"); //此处设置的filename无效 ,前端会重更新设置一下
        mv.addObject(NormalExcelConstants.CLASS, YtzmqTz.class);
        mv.addObject(NormalExcelConstants.PARAMS, new ExportParams("烟台市自贸区工作台账" + "报表", "导出人:" + sysUser.getRealname(), "烟台市自贸区工作台账"));
        mv.addObject(NormalExcelConstants.DATA_LIST, exportList);
        return mv;
    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待分析

**Comment by lsqGitHub716** [comment]
目前配置不支持

**Comment by zhangdaiscott** [comment]
可以下载https://github.com/zhangdaiscott/autopoi
自己实现
