### ISSUE TITLE
redis监控的token获取了2次不同的值，导致后台报错

### ISSUE THREAD

**Issue by hou649726274** [zhangdaiscott/jeecg-boot#2405]
##### 版本号：
jeecg-boot-parent  2.4.3
spring-boot-starter-jimureport  1.3.1-beta

##### 问题描述：
菜单管理配置 jimureport地址 ，token 后台获取错误。
{{ window._CONFIG['domianURL'] }}/jmreport/view/1352160857479581696?token=${token}

##### 截图&代码：
第一次登录 ， 后台日志org.jeecg.config.shiro.ShiroRealm.checkUserTokenIsEffect() 方法获取的登陆系统token： eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTcyNDkyNzYsInVzZXJuYW1lIjoiYWRtaW4ifQ.P1yRobQqDHUluuEAEDRjrT5b0XFu6XiM-XAKIsD-Y2I;cacheToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTcyNDkyNzYsInVzZXJuYW1lIjoiYWRtaW4ifQ.P1yRobQqDHUluuEAEDRjrT5b0XFu6XiM-XAKIsD-Y2I
![image](https://user-images.githubusercontent.com/7751899/113239248-f53fed80-92dc-11eb-907a-3ff2169fdecd.png)

接着点开【统计报表】-【redis监控】，后台日志
后台日志org.jeecg.config.shiro.ShiroRealm.checkUserTokenIsEffect() 方法获取的登陆系统token（这里应该有问题，token跟系统登录的不一样）： 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTcyNTA5ODUsInVzZXJuYW1lIjoiYWRtaW4ifQ.v3SLcS5BnSV-cdRzVmycGOIQUv8m5VkWH3be39arTT4
![image](https://user-images.githubusercontent.com/7751899/113241425-46ea7700-92e1-11eb-8005-48937732f10f.png)
之后又有 登录的token，导致报错。
![image](https://user-images.githubusercontent.com/7751899/113241604-9b8df200-92e1-11eb-8eb8-40ff5c32b7db.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的意思 【统计报表】-【redis监控 这个功能有问题？？

**Comment by hou649726274** [comment]
> 你的意思 【统计报表】-【redis监控 这个功能有问题？？

另外，还有个bug，就是我另外新增一个 【redis监控】，以页面弹出的形式，然后也加上 ?token=${token} ，同时把 shiroRealm代码注释。重新登录，打开这个【redis监控】 ，后台也报错， 在后台日志会有 2段不同的token。 
但是如果我 登录 不是打开 【redis监控】，而是先选择打开 【报表设计】--【积木报表设计】，然后再去打开这个新增的【redis监控】，就不会有问题~

 //积木报表排除
//        filterChainDefinitionMap.put("/jmreport/**", "anon");
//        filterChainDefinitionMap.put("/**/*.js.map", "anon");
//        filterChainDefinitionMap.put("/**/*.css.map", "anon");

**Comment by zhangdaiscott** [comment]
已经修改了，尽快发布
