### ISSUE TITLE
js增强putAction提示未定义

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2406]
##### 版本号：
2.4.3

##### 问题描述：
js增强putAction提示未定义

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/113252974-24635880-92f7-11eb-8ddd-5f508f19b4df.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有截图吗

**Comment by zhangdaiscott** [comment]
目前只支持这三种，不支持put
