### ISSUE TITLE
本地docker镜像传到服务器上启动后，后台无法正常使用

### ISSUE THREAD

**Issue by freeorder** [zhangdaiscott/jeecg-boot#2407]
##### 版本号：
2.4.2

##### 问题描述：
将本地跑通的docker镜像传到ubuntu18.04服务器上启动后，前台正常运行，后台无法连接。服务器上docker的log和本地相比有部分信息缺失，似乎是没法收到A cookie header was received之后的信息

##### 截图&代码：
服务器上正常容器正常运行：
![image](https://user-images.githubusercontent.com/18523630/113328394-d1b58b00-934e-11eb-8477-8a0f53b66c78.png)
win10本地docker正常运行jeecg-boot-system打印信息
![image](https://user-images.githubusercontent.com/18523630/113328852-67e9b100-934f-11eb-9dff-4beaffd911ec.png)
ubuntu18.04运行jeecg-boot-system打印信息（和本地相比有缺失）
![image](https://user-images.githubusercontent.com/18523630/113328899-73d57300-934f-11eb-951a-1a2133af564a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
服务器端host配置了吗

**Comment by freeorder** [comment]
配置过了 在etc/hosts配置：
127.0.0.1   jeecg-boot-redis
127.0.0.1   jeecg-boot-mysql
127.0.0.1   jeecg-boot-system
这样应该可以吧

**Comment by freeorder** [comment]
是初始化没办法完成吗？
