### ISSUE TITLE
online联动组件问题

### ISSUE THREAD

**Issue by gtqxcm** [zhangdaiscott/jeecg-boot#2408]
##### 版本号：
2.4.3
##### 问题描述：
在online表单设计中，加入联动组件，在功能测试可以使用，生成代码后，加入到工程中，提示资源不可用，下拉框没有内容。

##### 截图&代码：
auto在线表单：
![image](https://user-images.githubusercontent.com/81938410/113528157-5d027b00-95f2-11eb-824b-0de9eaa32295.png)
生成代码表单：
![image](https://user-images.githubusercontent.com/81938410/113528240-9a670880-95f2-11eb-8201-93156378743e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
三级联动不支持生成
