### ISSUE TITLE
第一次加载在慢

### ISSUE THREAD

**Issue by dreamskr** [zhangdaiscott/jeecg-boot#2409]
##### 问题描述：
从https://gitee.com/jeecg/jeecg-boot直接下载源码，编译，第一次加载时很慢，查看app.js的大小达49.7M，还有其它js 200多个，想问是什么原因，如何优化

##### 截图&代码：

![截图](https://user-images.githubusercontent.com/43511466/113533795-565a1080-95be-11eb-87d3-1173bd2be4b1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
前端开发就这样，编译后就快了

**Comment by zhengqingxin** [comment]
vue 脚手架默认开启了预加载，可以禁用 https://github.com/vuejs/vue-cli/issues/979#issuecomment-373027130
