### ISSUE TITLE
希望增加多帐套的功能

### ISSUE THREAD

**Issue by dreamskr** [zhangdaiscott/jeecg-boot#2410]
##### 问题描述：
一个客户部署一套接口和前端web，占的资源太多了，建议增加多帐套的功能，每个客户完全独立一套数据。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个需求是个性化的，自己实现吧，我们得满足不同的用户需求
