### ISSUE TITLE
生成代码后和online表单开发中展现的不一样

### ISSUE THREAD

**Issue by jojce** [zhangdaiscott/jeecg-boot#2411]
##### 版本号：
2.4.3

##### 问题描述：
online表单开发中,我按照官方课程教程中自动生成了订单号,可是代码生成后的页面上不会自动生成订单号, online开发中的功能测试中是正常结果
在F12调试中   online开发中有调用http://localhost:8080/jeecg-boot/sys/fillRule/executeRuleByCode/shop_order_num这个请求
生成出来后的没有.  有大佬可以解答下是什么原因吗

##### 截图&代码：

![image](https://user-images.githubusercontent.com/32671881/113585236-8bb63b00-965e-11eb-8e0d-71b5276e82af.png)

![image](https://user-images.githubusercontent.com/32671881/113585309-a5578280-965e-11eb-84a6-a5b5eaee7362.png)

![image](https://user-images.githubusercontent.com/32671881/113585373-ba341600-965e-11eb-82cb-c6e5c9de01c5.png)

![image](https://user-images.githubusercontent.com/32671881/113585431-cae48c00-965e-11eb-8f83-9cf5d7804015.png)

![image](https://user-images.githubusercontent.com/32671881/113585445-d1730380-965e-11eb-8807-d425e3bb08ad.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持，手工补充逻辑吧
