### ISSUE TITLE
JAR方式发布,代码生成器报code-template-online does not exist异常

### ISSUE THREAD

**Issue by hexiaoleione** [zhangdaiscott/jeecg-boot#2415]
##### 版本号：
2.2.0

##### 问题描述：
JAR方式发布,代码生成器报异常：jeecg-boot-module-system-2.2.0.jar!/jeecg/code-template-online does not exist

已经按照 http://doc.jeecg.com/2043922配置，但还是不行，我缺少了哪个配置吗

##### 截图&代码：
特殊配置config目录：
<img width="766" alt="WeChatc7898336183034a22150255bbc3975ab" src="https://user-images.githubusercontent.com/10452634/113696006-10a76000-9704-11eb-9b66-c3bb70b50be7.png">

报错信息
<img width="1830" alt="WeChat9a00c3827ed9ce8a34b48fa5a27bff18" src="https://user-images.githubusercontent.com/10452634/113695649-ad1d3280-9703-11eb-8b4a-991078b4787b.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
启动命令是什么样的
