### ISSUE TITLE
使用archetype生成微服务模块，parent artifactId错误

### ISSUE THREAD

**Issue by leego86** [zhangdaiscott/jeecg-boot#2416]
##### 版本号：
jeecg-cloud-gen-2.4.2.jar和jeecg-cloud-gen-2.4.3.jar

##### 问题描述：
使用archetype生成微服务模块，生成服务的父pom中parent的artifactId值为jeecg-boot-module，代码和仓库中都没有此模块，代码编译报错，开发文档中截图显示的是jeecg-boot-parent

##### 截图&代码：
jeecg-cloud-gen-2.4.3.jar中archetype-resources中的pom
![image](https://user-images.githubusercontent.com/31645800/113697121-5fa1c500-9705-11eb-99c9-358c79c363a7.png)

生成的项目pom
![image](https://user-images.githubusercontent.com/31645800/113698064-a5ab5880-9706-11eb-84f7-a50d7ac6f05a.png)

开发文档中的截图：

![image](https://user-images.githubusercontent.com/31645800/113697082-53b60300-9705-11eb-985a-966aa5a373a6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你可以创建这个模块jeecg-boot-module，我们项目多，是放到这里面
