### ISSUE TITLE
手机端验证码异常

### ISSUE THREAD

**Issue by FreedomStark** [zhangdaiscott/jeecg-boot#2418]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/113805845-d4bbdb80-9793-11eb-911d-a87f05a838e1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后端服务接口通吗

**Comment by zhangdaiscott** [comment]
你手机网络和你的服务接口是一个网络吗
