### ISSUE TITLE
登录跳转首页出错，这个错误从哪来的

### ISSUE THREAD

**Issue by kios996** [zhangdaiscott/jeecg-boot#2422]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/82084531/113831542-4c046600-97ba-11eb-944f-7f6d5fd870c7.png)

**Comment by zhangdaiscott** [comment]
升级到最新的代码看看，印象中解决了

**Comment by kios996** [comment]
麻烦可以帮忙解答一下具体是什么问题吗，项目等着部署了，现在换新的代码来不及了，我比对代码没发现哪里的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JEECG开源社区 ***@***.***&gt;
发送时间: 2021年4月7日 16:20
收件人: zhangdaiscott/jeecg-boot ***@***.***&gt;
抄送: kios996 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[zhangdaiscott/jeecg-boot] 登录跳转首页出错，这个错误从哪来的 (#2422)





 
升级到最新的代码看看，印象中解决了

**Comment by zhangdaiscott** [comment]
忘记了，好像是跟样式有关style

**Comment by zhangdaiscott** [comment]
src/components/setting/SettingDrawer.vue
--date:20201230---for: Error in render: "TypeError: Cannot read property 'style' of undefined"
