### ISSUE TITLE
采用极简部署方案，前端build之后dist包体积过大

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2423]
##### 问题描述：

采用极简部署方案，前端build之后dist包体积过大，大概有26M，并且打开项目很慢，请问可否优化
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043891
