### ISSUE TITLE
项目名与访问链接修改

### ISSUE THREAD

**Issue by qiangyujia** [zhangdaiscott/jeecg-boot#2424]
##### 问题描述：
           修改了项目名和访问路径之后 项目的在线开发功能就不能使用了，而且我已经修改了
           node_modules\@jeecg\antd-online-mini\dist 中的OnlineForm.umd.min.js 中的项目名
##### 截图&代码：
![image.png](http://ww1.sinaimg.cn/large/9df861c6ly1gpbbm6rejdj20gd03tq2v.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
java的扫码路径加上jeecg的

**Comment by qiangyujia** [comment]
请问扫码路径指的是？

**Comment by qiangyujia** [comment]
> java的扫码路径加上jeecg的

您能说的再详细一点吗？没太懂

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/797
