### ISSUE TITLE
关于多租户的数据权限配置问题

### ISSUE THREAD

**Issue by slppls** [zhangdaiscott/jeecg-boot#2425]
##### 版本号：
v2.4.3

##### 问题描述：
情况是这样的，我创建了一个租户，然后对这个租户下的角色的某项菜单分配了数据权限，具体规则在图上，配置完之后，更换到该账户，发现数据没有了，然后通过日志查看，发现是租户id获取为空的问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18140796/113849560-3861fb00-97cc-11eb-960c-2254de05cad3.png)
![image](https://user-images.githubusercontent.com/18140796/113849668-53346f80-97cc-11eb-8f0d-6bcce4ba5d43.png)
依照文档的说明，进行了数据权限的配置，但是通过日志，发现执行的sql中，直接将该变量#{tenant_id}作为字符串传入了，但是试过其他的变量，是可以转换为具体值的，例如编码，用户名等，就是这个租户id不行，执行的sql如图

![image](https://user-images.githubusercontent.com/18140796/113850545-2a60aa00-97cd-11eb-8b2b-23c25f021e59.png)

猜测是获取不到tenant_id导致的，但是debug这块的时候发现无从下手，没办法找到获取当前用户tenant_id或设置tenant_id这一块的东西，实在惭愧，只能来此询问

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by slppls** [comment]
配置的菜单为用户管理这个菜单

**Comment by slppls** [comment]
登陆的角色账户是有权限的，并且是处于该租户下的，且该租户下具备多条用户数据，目前就是这个#{tenant_id}没有转换为当前登陆用户的tenant_id

**Comment by zhangdaiscott** [comment]
下个版本才支持 3.4.4+
