### ISSUE TITLE
maven install时出错

### ISSUE THREAD

**Issue by libinjp** [zhangdaiscott/jeecg-boot#2427]
##### 问题描述：
本地可以运行的很好，可是在使用maven install的时候（为了生成jar文件），确报 org.jeecg.common.api.vo不存在的错误

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15372418/113876634-e1235100-97f2-11eb-9c47-091a3da85073.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
先手工install core看看
