### ISSUE TITLE
redis配置max-active为0后，前端启动时读取不到验证码

### ISSUE THREAD

**Issue by bb3239** [zhangdaiscott/jeecg-boot#2428]
##### 问题描述：

1，项目组多个成员共同使用服务器上的同一个redis，redis配置max-active为0后，前端启动时读取不到验证码
2，当打开某个功能页面时，redis连接数增加，关功能后，redis连接数没有减少，也就是说，redis连接数始终都在增加，很容易就超出了配置的max-active值，导致前端再操作界面就无响应

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.4.3好像改了，你可以看看

**Comment by zhangdaiscott** [comment]
org.jeecg.config.shiro.ShiroConfig
![image](https://user-images.githubusercontent.com/3162115/113966645-0ef3ae80-9862-11eb-93b5-dceaab0fb77f.png)

**Comment by zhangdaiscott** [comment]
max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
