### ISSUE TITLE
权限是否可以控制到url级别

### ISSUE THREAD

**Issue by FikaCode** [zhangdaiscott/jeecg-boot#2429]
##### 版本号：
官网的演示版本

##### 问题描述：
权限控制只能控制到菜单，有没有这种可能，如果我登录了，然后我知道了一个删除用户的api，直接去调用删除用户的api会怎么样？（假设参数全部正确）会直接删除么？或者可否对api的调用做一下控制。

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
多看文档
http://doc.jeecg.com/2044037

**Comment by FikaCode** [comment]
OK，谢谢
