### ISSUE TITLE
一对多JEditable弹窗里表格信息的日期显示不全

### ISSUE THREAD

**Issue by ggunmo** [zhangdaiscott/jeecg-boot#243]
##### 版本号：

2.0.1
##### 问题描述：
一对多JEditable弹窗里表格信息的日期显示不全

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18226120/60244029-28757180-98ec-11e9-857c-9ca5a145b6cd.png)

**Comment by zhangdaiscott** [comment]
此问题已经解决，下个版本发布
