### ISSUE TITLE
demo中 oa模块-会议管理功能是实现的吗?

### ISSUE THREAD

**Issue by gruntling** [zhangdaiscott/jeecg-boot#2430]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/37258275/113983889-0d83af80-987d-11eb-9609-0861f2c94850.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by gruntling** [comment]
demo中 oa模块-会议管理功能是实现的吗?

**Comment by zhangdaiscott** [comment]
非开源功能
