### ISSUE TITLE
部门管理功能无法添加下级部门

### ISSUE THREAD

**Issue by wushengfa233** [zhangdaiscott/jeecg-boot#2431]
##### 版本号：
 2.4.3（发布日期：20210322）

##### 问题描述：
jeecg-boot系统  =》  系统管理 =》 部门管理 , 无法添加下级部门，添加好上级部门后，选中上级部门，但是所选部门没有实时更新在 【当前选择】栏，添加下级部门时提示 “请先点击选中上级部门！”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/43536040/113983371-69016d80-987c-11eb-9f7b-cce5943bdc2b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
点击部门名称来选中数据，勾选不行，勾选用于批量删除。

![image](https://user-images.githubusercontent.com/34293221/114339139-16c79180-9b87-11eb-85d7-c9d8c4150e92.png)

**Comment by chenbihao** [comment]
同，发现sys_depart表里有一条财务部的数据，删除后即可解决这个问题
