### ISSUE TITLE
采用fortify工具进行代码扫描，存在诸多安全隐患

### ISSUE THREAD

**Issue by GuXingFei** [zhangdaiscott/jeecg-boot#2432]
##### 截图&代码：扫描结果截图如下：
![1](https://user-images.githubusercontent.com/42603953/113993119-ae2a9d00-9886-11eb-97ad-5b0e77b68d1f.png)

![2](https://user-images.githubusercontent.com/42603953/113993139-b2ef5100-9886-11eb-953b-cfa95673c9ef.png)

**Comment by zhangdaiscott** [comment]
字典这块的mapper写法是有漏洞，为了通用做的牺牲，但是调用的地方，已经加了sql注入check所以没问题
