### ISSUE TITLE
JEditableTable 查看时，内容过长显示有问题

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2435]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26954826/114001596-ac64d780-988e-11eb-9a6b-036b64744183.png)
![image](https://user-images.githubusercontent.com/26954826/114001637-b2f34f00-988e-11eb-869e-6b43ccf91f1e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，下个版本更新

**Comment by zhangdaiscott** [comment]
修改src/components/jeecg/JEditableTable.vue

```
<span class="comp-normal" v-else :key="i" :title="inputValues[rowIndex][col.key]" v-bind="buildProps(row,col)">{{ inputValues[rowIndex][col.key] }}</span>

替换原来的写法
<span v-else :key="i" v-bind="buildProps(row,col)">{{ inputValues[rowIndex][col.key] }}</span>
```
