### ISSUE TITLE
打开报表设计器报错

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2438]
##### 版本号：
jeecg-boot 2.4.3
spring-boot-starter-jimureport 1.3.1-beta2

##### 问题描述：
错误语句
SELECT * FROM jimu_report jr WHERE 1=1 and jr.CREATE_BY = ? and jr.TYPE = ? and jr.DEL_FLAG = ? and jr.TEMPLATE = ? ORDER BY jr.create_time DESC) tmp_count

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/114122100-298d5c80-9922-11eb-8782-78c320492f48.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
SqlServer数据库吗，参考这个
https://github.com/zhangdaiscott/JimuReport/issues/176
