### ISSUE TITLE
自定义按钮问题

### ISSUE THREAD

**Issue by bagen18** [zhangdaiscott/jeecg-boot#2439]
##### 版本号：
2.4.3

##### 问题描述：
添加自定义按钮无法显示，也试过重新生成代码，重启过，都不行？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/45376035/114124270-a3274980-9926-11eb-8d57-117a84c6b15f.png)
![image](https://user-images.githubusercontent.com/45376035/114124279-a7ebfd80-9926-11eb-8649-2b21d901479f.png)
![image](https://user-images.githubusercontent.com/45376035/114124299-b63a1980-9926-11eb-8dd4-38fe77eb56b9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by bagen18** [comment]
是不是漏了什么操作？？

**Comment by bagen18** [comment]
有人清楚吗，急求？？？

**Comment by bagen18** [comment]
有人清楚吗，急求？？？

**Comment by zhangdaiscott** [comment]
不支持生成
https://github.com/zhangdaiscott/jeecg-boot/issues/1312
