### ISSUE TITLE
表格数据排序问题

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#244]
##### 问题描述：
前端在表格列信息上增加属性sorter: true即可实现点击表头进行排序,但是如果遇到_dictText字段的时候(即查询显示的列是系统字典里翻译过来的字段),的时候传递给后台order by的时候应该要去掉 _dictText才行,不然带入到sql中会提示字段不存在.
另外,在前端JeecgListMixin.js中isorter有个默认排序字段的设置,create_time desc,这样个人觉得不太妥当,如果需要排序可以在前台传递,而没必要给一个默认排序,如果当前的查询没有create_time字段呢?

**Comment by zhangdaiscott** [comment]
第二个问题解答：

   /* 排序参数 */
      isorter:{
        column: 'createTime',
        order: 'desc',
      },

可以再每个页面重写

**Comment by zhangdaiscott** [comment]
第一个问题，已经处理，下个版本发布

**Comment by w1lkin** [comment]
请问多字段排序应该怎么写？例如第一个字段倒序，第二段正序...

**Comment by w1lkin** [comment]
> 请问多字段排序应该怎么写？例如第一个字段倒序，第二段正序...
已解决：
 isorter: {
        column: 'busiDate desc,scrNum',
        order: 'asc'
      },

**Comment by w1lkin** [comment]
> 请问多字段排序应该怎么写？例如第一个字段倒序，第二段正序...

已解决，附上代码 
isorter: {
        column: 'a desc,b',
        order: 'asc'
      },
