### ISSUE TITLE
online报表, 除了mysql数据源, 其他数据源类型返回了所有数据, 未按照分页参数进行返回

### ISSUE THREAD

**Issue by chenwei1015** [zhangdaiscott/jeecg-boot#2440]
##### 版本号：
2.4.2

##### 问题描述：
online报表

其他数据源未按照分页参数进行返回数据, 而是将所有数据返回了
mysql数据源没有这个问题.

例:
数据总条数50条, 分页参数pageSize = 10
mysql数据源返回了10条数据, 
其他数据源返回了50条.

##### 截图&代码：

![其他数据源](https://user-images.githubusercontent.com/76138872/114129400-133acd00-9931-11eb-9b3c-ae596781f692.png)
![mysql数据源](https://user-images.githubusercontent.com/76138872/114129407-17ff8100-9931-11eb-914d-d2d72cec79dc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
【Online报表】没有复现你说的这个问题，你是怎么测试的？

![image](https://user-images.githubusercontent.com/34293221/114555276-1c61cc00-9c9a-11eb-8004-36ebfaf37f9d.png)

![image](https://user-images.githubusercontent.com/34293221/114555257-1966db80-9c9a-11eb-8009-90cf0e7acd94.png)

**Comment by chenwei1015** [comment]
不好意思, 之前测的时候搞混了, 我又重新测试了下, SqlServer数据库没有问题,  

是 PostgreSql , GP 有这个问题.   都是用 org.postgresql.Driver

**Comment by accpman** [comment]
![image](https://user-images.githubusercontent.com/4446237/118446004-b7c6e080-b721-11eb-81c0-9f9b0364a8ae.png)
![image](https://user-images.githubusercontent.com/4446237/118446046-c2817580-b721-11eb-92cc-d741b76824fd.png)
经测试未发现异常
