### ISSUE TITLE
【在线开发】online组合报表  无法 选择图表

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2442]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/114159261-2dd46c80-9958-11eb-8598-2dac0e9371c4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
刷新F5看看

**Comment by kasidier** [comment]
刷新了，你这个组件是只能出现10个，我删掉一个就会出现一个新的

**Comment by kasidier** [comment]
![image](https://user-images.githubusercontent.com/7098009/114370490-1db7c980-9bb2-11eb-90b3-ba6e0948421c.png)
11个图表，但是下拉菜单就只有10个
![image](https://user-images.githubusercontent.com/7098009/114371232-e0a00700-9bb2-11eb-93b2-c0a2826a0d33.png)

![image](https://user-images.githubusercontent.com/7098009/114371166-cebe6400-9bb2-11eb-81cb-30c9eda82254.png)

**Comment by kasidier** [comment]
跟我刷不刷新没关系

**Comment by sjlei** [comment]
该问题已修复，下个版本更新
