### ISSUE TITLE
online表单数据库导入缺少表

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2443]
##### 问题描述：
online表单数据库导入缺少表，且配置文件中不包含在已排除的前缀

##### 截图&代码：
导入shop开头的只有三个表，且列表中没有：
![image](https://user-images.githubusercontent.com/33947373/114159925-e8fd0580-9958-11eb-8cdb-59b879d6ba75.png)
数据库中的表图：
![image](https://user-images.githubusercontent.com/33947373/114160039-0b8f1e80-9959-11eb-8961-f65afd224b81.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by qianlei0007** [comment]
缓存问题吧，确认一下数据连接是否正确。

**Comment by zhangdaiscott** [comment]
是一个库吗

**Comment by bestitxq** [comment]
没错，是同一个数据库，缓存的话重启过服务器结果还是一样呢

**Comment by zhangdaiscott** [comment]
哪如何重现呢，我们这边没问题，无法解决
