### ISSUE TITLE
【省市区组件】如何控制联动级别和显示样式？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2444]
##### 截图&代码：
图1  组件使用效果如下，但我只想要红框中的部分，需要怎样设置？
![image](https://user-images.githubusercontent.com/7098009/114162338-953feb80-995b-11eb-94fd-5c8fd0251fe7.png)

图2

![image](https://user-images.githubusercontent.com/7098009/114164543-01bbea00-995e-11eb-8cf4-59ff25f4b1da.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己改造代码，实现一个新组件

**Comment by kasidier** [comment]
图2的样式也得自己实现？不是有样式选择？
