### ISSUE TITLE
jeditable slot 用自定义的input

### ISSUE THREAD

**Issue by czzltp** [zhangdaiscott/jeecg-boot#2445]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18019128/114256015-c6ff9380-99e9-11eb-85ff-b1fda0c76f56.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by sjlei** [comment]
`props.text`是只读的，不能通过`v-model`设置值，且就算设置上了，也不会触发校验之类的。
请用 `props.handleChange`方法来设置值，如下图所示
![image](https://user-images.githubusercontent.com/34293221/114532150-24604280-9c7f-11eb-83bb-bec22f2c6f14.png)
