### ISSUE TITLE
列表中的popup弹出框是否支持多选？

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/jeecg-boot#2446]
##### 版本号：
2.4.3

##### 问题描述：
在列表的popup弹出框，是否支持勾选多条明细带出？

##### 截图&代码：
<img width="619" alt="image" src="https://user-images.githubusercontent.com/48822119/114271941-8124e880-9a46-11eb-9029-d924de97a4bd.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/48822119/114271992-b9c4c200-9a46-11eb-9cc5-8a71fcc3ef4c.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你指的是online还是编写的代码

**Comment by iGuozy** [comment]
online在线表单的和online代码生成器生成的代码都支持吗？？

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
JPopup组件支持多选，只是配置方式不一样。
多选之后返回的数据以逗号分割的形式保存。

### 行编辑配置方式
![image](https://user-images.githubusercontent.com/34293221/115988192-126d9080-a5eb-11eb-9b82-ff6a0d427c70.png)

### 代码配置方式
![image](https://user-images.githubusercontent.com/34293221/115988208-21ecd980-a5eb-11eb-8d6d-f04f6f80b972.png)

### Online表单配置方式
注意，Online表单的Popup是默认多选的，所以默认不用做任何配置，下图里是配置单选。
文档：<http://doc.jeecg.com/2044137>
![image](https://user-images.githubusercontent.com/34293221/115988247-43e65c00-a5eb-11eb-8de8-e65b3e3589c0.png)

### 效果
![image](https://user-images.githubusercontent.com/34293221/115988174-01bd1a80-a5eb-11eb-866c-25548de2ddea.png)
![image](https://user-images.githubusercontent.com/34293221/115988163-fd90fd00-a5ea-11eb-8af0-5cc2186ea899.png)

**Comment by iGuozy** [comment]
不是要这种带出合并一行的效果，是要多选了三行，返回到table那里是三行。

**Comment by sjlei** [comment]
那你说的这个功能还不支持，而且很难支持

**Comment by caodaqing** [comment]
![image](https://user-images.githubusercontent.com/38416754/118231920-5bb25100-b4c2-11eb-9353-97e62b01c792.png)
![image](https://user-images.githubusercontent.com/38416754/118231973-74bb0200-b4c2-11eb-878f-e2b65fd12359.png)
设置了之后还是可以多选

**Comment by HelloZhiwen** [comment]
> 不是要这种带出合并一行的效果，是要多选了三行，返回到table那里是三行。

这种效果有实现方案吗
