### ISSUE TITLE
加载页面卡死

### ISSUE THREAD

**Issue by libinjp** [zhangdaiscott/jeecg-boot#2447]
##### 版本号：
2.4.3

##### 问题描述：
生产环境编译后，发布到服务器上，可是在加载页面卡死，没有进入登录页。console报错：Uncaught SyntaxError: Unexpected token <
非常期待您的答复。🙏
##### 截图&代码：

![image](https://user-images.githubusercontent.com/15372418/114273951-365f9c80-9a57-11eb-9eec-3389d1782ac6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by libinjp** [comment]
问题找到了，不用回答，谢谢啦

**Comment by LongYue9608** [comment]
> 问题找到了，不用回答，谢谢啦

请问咋解决的

**Comment by LongYue9608** [comment]
@libinjp
