### ISSUE TITLE
导入功能性能问题

### ISSUE THREAD

**Issue by qianlei0007** [zhangdaiscott/jeecg-boot#2448]
##### 问题描述：
导入功能， 如果导入的数据在 800条以上， 前端一直是文件上传中，其实数据库中记录没有变化了。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by qianlei0007** [comment]
createError.js?2d83:16 Uncaught (in promise) Error: timeout of 9000ms exceeded
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleTimeout (xhr.js?b50d:77)

**Comment by zhangdaiscott** [comment]
这是导入超时了，可以手工修改改下online的js超时设置

**Comment by qianlei0007** [comment]
这个是动态表单里面的，JS 哪里能改超时的时间？
