### ISSUE TITLE
账号安全问题

### ISSUE THREAD

**Issue by thzdbdp** [zhangdaiscott/jeecg-boot#2449]
##### 版本号：
2.4.3
##### 问题描述：
校验验证码后，验证码没有从redis中去除，可以实现暴力破解账号密码，所以在验证码进行校验之后，无论是否校验成功，都应该去除redis中存储的验证码

##### 截图&代码：

 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
问题已收录

**Comment by lsqGitHub716** [comment]
验证码有设置60秒失效，并且密码错误会刷新验证码
