### ISSUE TITLE
在jeecg_database.properties中修改online表单数据源后报错

### ISSUE THREAD

**Issue by odmtest777** [zhangdaiscott/jeecg-boot#2450]
##### 版本号：
2.4.3

##### 问题描述：
1.按照文档,在jeecg-boot-module-system/jeecg/jeecg_database.properties中修改代码生成器的数据源为自己的数据库
2.把CodeGenerateDbConfig中@Configuration注解注释掉,使jeecg_database.properties生效
3.在online表单开发中点击导入数据库中的表,在自己的数据库中随便选择一张表生成表单
4.在新生成的表单点击功能测试报错,看报错应该是还是到老的数据库去找表了

##### 截图&代码：
![3](https://user-images.githubusercontent.com/43691039/114347184-23ec7c80-9b97-11eb-896c-9aee8f4d16e4.png)
![1](https://user-images.githubusercontent.com/43691039/114347234-3797e300-9b97-11eb-8a61-6d6cc0a77f68.png)
![2](https://user-images.githubusercontent.com/43691039/114347233-3797e300-9b97-11eb-8726-83c1904b4310.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
功能测试走的是代码生成器的配置

**Comment by odmtest777** [comment]
> 功能测试走的是代码生成器的配置

所以在线表单是不支持多数据源的哇?

**Comment by zhangdaiscott** [comment]
不支持
