### ISSUE TITLE
在线表单设计没有模糊查询设置

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2451]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/114368919-74240880-9bb0-11eb-9bbb-0e92cd23f7a9.png)

![image](https://user-images.githubusercontent.com/7098009/114367333-ec89ca00-9bae-11eb-96c2-5b3622488e83.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
文本前后带*
