### ISSUE TITLE
自定义树控件填写pid出错

### ISSUE THREAD

**Issue by 1118steven** [zhangdaiscott/jeecg-boot#2452]
##### 版本号：
2.4.2

##### 问题描述：
自定义树控件填写pid报错，而且改完以后下拉绑定的分类名称都变成0和1了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40009211/114424449-b36f4b00-9bea-11eb-8b82-75400e4e120c.png)

![image](https://user-images.githubusercontent.com/40009211/114424598-db5eae80-9bea-11eb-8ef1-77b3b445e72b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1118steven** [comment]
自定义树控件填写pid报错，而且改完以后下拉绑定的分类名称都变成0和1了

**Comment by geosmart** [comment]
注意检查：
页面属性中-字段的控件类型，是自定义树，而不是下拉框
