### ISSUE TITLE
online生成的代码表现形式和online预览的不一致

### ISSUE THREAD

**Issue by wangleigithub** [zhangdaiscott/jeecg-boot#2453]
##### 版本号：
2.4.3

##### 问题描述：
online模式下生成一对多(ERP模式)，新增时是弹出模态框，但是生成代码后，新增是edittable的形式了

##### 截图&代码：
online在线测试

![image](https://user-images.githubusercontent.com/755879/114484668-37522300-9c3d-11eb-8920-4d83980e9888.png)

生成代码模式
![image](https://user-images.githubusercontent.com/755879/114484917-9c0d7d80-9c3d-11eb-823e-a86b5d5a334b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你生成的是，选择ERP模板了吗。肯定没选

**Comment by wangleigithub** [comment]
> 你生成的是，选择ERP模板了吗。肯定没选

哈，还真是，没注意，“以为”只要在表单那边选了ERP一对多就行了

**Comment by wangleigithub** [comment]
> 你生成的是，选择ERP模板了吗。肯定没选
按你的那个试了，是模态框了，但是分列没了，都变成1列了
