### ISSUE TITLE
RedisConfig里注释了enableDefaultTyping这行代码，websocket会失效

### ISSUE THREAD

**Issue by TechnicolorTheClown** [zhangdaiscott/jeecg-boot#2454]
版本号：
2.4.3

问题描述：
需求： 我需要在reids里存 CookieManager

我的解决：直接存进去，在取的时候会报错，于是我去改了 RedisConfig 注解里的

`objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);`

把这个注释了，存储正常了；但是在启动时候发现 websocket消息失效了，前端接收不到消息，ws://链接里没有接收到消息

问题截图：
![image](https://user-images.githubusercontent.com/30717835/114485170-0b836d00-9c3e-11eb-9e0d-c88f11b29ce0.png)

![image](https://user-images.githubusercontent.com/30717835/114485182-10482100-9c3e-11eb-9def-d833b7886151.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
推送消息用到了redis的发布订阅模式，具体问题自己调查吧
