### ISSUE TITLE
微服务中关于子模块使用ftl模板路径问题

### ISSUE THREAD

**Issue by marissa521** [zhangdaiscott/jeecg-boot#2455]
##### 版本号：
2.4.3

##### 问题描述：
使用单体应用升级微服务，之前的模块ftl文件中的路径全部不可用，前端都是localhost:9999/***,请问怎么跳转到对应模块下面的路径进行访问？

##### 截图&代码：

所有script标签都报错，提示Failed to load resource: the server responded with a status of 404 (Not Found

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？错误截图看看

**Comment by marissa521** [comment]
解决了，网关gateway没有配置相关资源的路径，再问下，其他微服务模块想要动态获取网关的ip和端口怎么处理呢？
