### ISSUE TITLE
生成的代码缺少XXXModal.vue文件

### ISSUE THREAD

**Issue by alexwanghc** [zhangdaiscott/jeecg-boot#2459]
##### 版本号：
2.4.3

##### 问题描述：
一对多代码生成后，没有XXXXModal.vue文件，导致XXXXForm.vue中报错 找不到Modal，在线功能测试使用正常，控制台也不报错

##### 截图&代码：

![1](https://user-images.githubusercontent.com/21185908/114522642-21ad1f80-9c76-11eb-95ef-80e519f0c8ec.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个模板，看看后台是不是报错了

**Comment by alexwanghc** [comment]
一对多的模板，后台没有报错。
我已自行解决，解决方式是：mvn clean + idea invalidate and restart，并且清除所有target。
偶发现象，建议优化一下
