### ISSUE TITLE
开发文档无法访问

### ISSUE THREAD

**Issue by masaiaaaa** [zhangdaiscott/jeecg-boot#2461]
##### 截图&代码：
![222](https://user-images.githubusercontent.com/49604210/114525601-d0525f80-9c78-11eb-80e3-6872ec26184f.PNG)
我网络没问题，可以正常访问jeecg官网

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/114526034-32ab6000-9c79-11eb-80e2-559ffef5372d.png)


你的网络问题吧
