### ISSUE TITLE
为什么AES中的key和iv要使用硬编码？

### ISSUE THREAD

**Issue by GuXingFei** [zhangdaiscott/jeecg-boot#2462]
##### 截图&代码：
public class  EncryptedString {

    public static  String key = "1234567890adbcde";//长度为16个字符

    public static  String iv  = "1234567890hjlkew";//长度为16个字符
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块逻辑废弃了，没有用的了
