### ISSUE TITLE
请问是否能实现列头筛选功能？

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/jeecg-boot#2463]
##### 版本号：
2.4.3

##### 问题描述：
请问现在的JVXE-table能否实现列头筛选功能？

##### 截图&代码：
<img width="844" alt="image" src="https://user-images.githubusercontent.com/48822119/114596031-aec99600-9cc1-11eb-919d-0f06e0e71e2f.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
咱无计划
