### ISSUE TITLE
性能监控模块相关

### ISSUE THREAD

**Issue by shaowei0522** [zhangdaiscott/jeecg-boot#2464]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by shaowei0522** [comment]
这是我的一个想法，可能有不太现实或者难以实现的地方，我个人见识有限，希望大佬可以不吝赐教

**Comment by zhangdaiscott** [comment]
目前监控还是仅限当前的服务，你可以自己扩展看看
