### ISSUE TITLE
用代码生成器生成代码在idea中报错

### ISSUE THREAD

**Issue by 1118steven** [zhangdaiscott/jeecg-boot#2465]
##### 版本号：
 jeecg-boot 2.4.2

##### 问题描述：
用代码生成器生成代码在idea中报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40009211/114649054-61294980-9d12-11eb-859e-4ae3eaec78d3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
pom设置有问题吧

**Comment by 1118steven** [comment]
感谢，解决了，pom的dependency引用错了
