### ISSUE TITLE
微服务模式下quartz定时任务不能定时运行

### ISSUE THREAD

**Issue by klhgithub** [zhangdaiscott/jeecg-boot#2467]
##### 版本号：
2.4.0

##### 问题描述：
微服务模式下在system模块下建了定时任务，在管理页面启动后不能定时执行

##### 截图&代码：
![1](https://user-images.githubusercontent.com/49932434/114675810-40c1b500-9d3b-11eb-8300-bca874cddcd9.png)
![2](https://user-images.githubusercontent.com/49932434/114675834-44edd280-9d3b-11eb-9ff3-d611242114f7.png)
![3](https://user-images.githubusercontent.com/49932434/114675843-47502c80-9d3b-11eb-9682-c909e244c8e5.png)
![4](https://user-images.githubusercontent.com/49932434/114675853-4ae3b380-9d3b-11eb-8597-b208c2f68af9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是这样，微服务下就得换成用xxljob了

**Comment by zhangdaiscott** [comment]
关闭quartz定时任务
![image](https://user-images.githubusercontent.com/3162115/123596157-5d429900-d824-11eb-8af3-0c8f269b715e.png)
