### ISSUE TITLE
请问jeecg-boot后端API接口中，执行insert/update时，有什么数据库字段通用的校验方式吗？

### ISSUE THREAD

**Issue by wan84** [zhangdaiscott/jeecg-boot#2468]
##### 版本号：
2.4.3

##### 问题描述：

如果通过postman请求接口
在java后端新增和编辑接口，如何做数据校验，比如定义某个字段必须满足有效格式，必要的长度限制等等

api层面的校验，没有找到相关文档

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wan84** [comment]
@zhangdaiscott api层面的数据校验，没有发现相关文档

**Comment by beichenhpy** [comment]
`@Valid`相关，百度一下就行

**Comment by wan84** [comment]
> @Valid

感谢
