### ISSUE TITLE
online表单开发，配置菜单代码存在哪

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2469]
##### 版本号：
v2.4.3

##### 问题描述：
就是有个疑问，online表单开发，表生成后配置好菜单功能就能用了，但是这功能的代码在哪里存着？给公司用的项目，功能开发完了找不到代码，有些功能想修改一下

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by alexwanghc** [comment]
如果想要生成代码、修改代码，需要选中表数据，点击生成代码，后修改
