### ISSUE TITLE
代码生成器新生成的module，后台运行报错，该如何解决

### ISSUE THREAD

**Issue by 1118steven** [zhangdaiscott/jeecg-boot#2471]
##### 版本号：
2.4.2

##### 问题描述：
代码生成器新生成的module，后台运行报错，该如何解决

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40009211/114894157-f9bde780-9e40-11eb-8132-f8c96849bd28.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
maven环境问题，自己搞了
