### ISSUE TITLE
无法导入七牛云jar包

### ISSUE THREAD

**Issue by h742004725** [zhangdaiscott/jeecg-boot#2475]
##### 版本号：
v2.2.1

##### 问题描述：
无法导入七牛云jar包，一直报红，已经镜像那些也都改了都还是不行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/65902133/115003939-dd6d8980-9ed8-11eb-8a12-db5a432c67a7.png)
![image](https://user-images.githubusercontent.com/65902133/115004010-f118f000-9ed8-11eb-9b3c-f344a5f861fb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by h742004725** [comment]
无论是七牛云哪个版本都不行

**Comment by zhangdaiscott** [comment]
可以删掉，不用也行
