### ISSUE TITLE
popup组件设置单选在单表和主表状态下不起效

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2478]
##### 截图&代码：
我的设置
![image](https://user-images.githubusercontent.com/7098009/115104925-7f9b7900-9f8e-11eb-8ea4-60c92760eda3.png)
单表设置不起作用
![image](https://user-images.githubusercontent.com/7098009/115105192-d786af80-9f8f-11eb-8bef-d505ce179dbc.png)
如果我改为附表，设置起作用
![image](https://user-images.githubusercontent.com/7098009/115105361-02bdce80-9f91-11eb-91db-5d520ab08adb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本才支持
![image](https://user-images.githubusercontent.com/3162115/115692247-62511b00-a391-11eb-83a2-daabe0281175.png)
