### ISSUE TITLE
Could not resolve placeholder 'jeecg.route.config.data-type' in value "${jeecg.route.config.data-type}"

### ISSUE THREAD

**Issue by sweethuaihaizi** [zhangdaiscott/jeecg-boot#2479]
##### 版本号：
V2.4.3

##### 问题描述：
微服务版本启动org.jeecg.JeecgGatewayApplication 报错，已经按照文档进行完成修改
![image](https://user-images.githubusercontent.com/33407039/115176558-ed1ae700-a0ff-11eb-99dd-5d7547ac03c0.png)

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33407039/115176377-944b4e80-a0ff-11eb-914b-cd03e063a9d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
nacos没联上吧
