### ISSUE TITLE
2.0.1版本多页签切换会刷新页面，导致值被刷新了

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#248]
##### 版本号：
2.0.1版本

##### 问题描述：
在填写一个页面时，到另外的页面查看信息，切回来的时候页面刷新，导致数据又要重新录入。

**Comment by zhangdaiscott** [comment]
参考这个
https://github.com/zhangdaiscott/jeecg-boot/issues/222
