### ISSUE TITLE
菜单管理编辑子级菜单不能选择上级菜单

### ISSUE THREAD

**Issue by Luohan-123** [zhangdaiscott/jeecg-boot#2481]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/72602089/115204144-be663600-a12a-11eb-9d46-64bc29bf8e55.png)
![image](https://user-images.githubusercontent.com/72602089/115204263-de95f500-a12a-11eb-8819-65a6c2baf0a1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以改啊
