### ISSUE TITLE
火狐45.02版本打包后不兼容

### ISSUE THREAD

**Issue by heguanxi** [zhangdaiscott/jeecg-boot#2483]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/39206655/115325257-daff7e00-a1bd-11eb-8593-d44a57e0fd50.png)

TypeError: Object.entries is not a function
堆栈跟踪：
["28c1"]/S@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:825:19324
["35d6"]/En.render/<@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:856:57843
["35d6"]/En.render@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:856:57806
.a593/</yn/e.prototype._render@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:23731
.a593/</jn/r@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:27822
.a593/</nr.prototype.get@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:30672
.a593/</nr.prototype.run@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:31412
Xn@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:29622
.a593/</pt/<@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:12759
lt@http://localhost:8828/cspbasic/js/chunk-vendors.d14c48ba.js:1012:12152

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by heguanxi** [comment]
1

**Comment by zhangdaiscott** [comment]
下载最新版试试
