### ISSUE TITLE
autopoi导入excel 如果单元格被设置边框，即使没有内容也会被当做是一条数据导入

### ISSUE THREAD

**Issue by Fnckerpoi** [zhangdaiscott/jeecg-boot#2484]
##### 版本号：
V1.2.2

##### 问题描述：
excel有多行空白行不小心被操作人员设置了边框，实际上都没有填入数据，但是会识别成一行数据。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38403438/115333469-47817980-a1cc-11eb-9a6e-2b53f9449ce9.png)

之前有提过issues，最新版V2.2.1不知道什么原因导出会报错，1.2.2没有该问题。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Fnckerpoi** [comment]
![image](https://user-images.githubusercontent.com/38403438/115334548-2e79c800-a1ce-11eb-84f8-e4ddf5d5bc6f.png)
并且maven库只有2.0.1新版本，请问如何使用最新版本

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/autopoi

**Comment by tygithub1** [comment]
问题解决：版本V1.3.1+
在实体中添加方法：isNullObject，实际导入的时候，会根据该方法的返回值决定是否添加数据。

/**
 * 判断该对象是否为空
 * @return
 */
public boolean isNullObject(){
    return this.name == null;
}

**Comment by zhangdaiscott** [comment]
autopoi最新版本是 1.3.6
