### ISSUE TITLE
bug:下拉联动组件，代码生成后还是输入框

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2488]
##### 版本号：
v2.4.3

##### 问题描述：
bug: 下拉联动组件关联查询结果，功能测试没有问题，
但是代码生成后，看到的只是input，没有像功能测试中一样产生级联关系

##### 截图&代码：
生成的代码：
![image](https://user-images.githubusercontent.com/33947373/115489557-eff81200-a28e-11eb-8b62-764e9a907b6c.png)

功能测试：
![image](https://user-images.githubusercontent.com/33947373/115489482-d656ca80-a28e-11eb-87a9-2adfdd688ab6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持此组件生成

**Comment by bestitxq** [comment]
那想实现这种功能应该怎样做呢？

**Comment by earlyEpiphyte** [comment]
> 

同问，得自己实现吗？
