### ISSUE TITLE
页面列表页，如何动态展示对应表数据

### ISSUE THREAD

**Issue by bestitxq** [zhangdaiscott/jeecg-boot#2492]
##### 版本号：
v2.4.3

##### 问题描述：
如下图页面上如何如何动态展示为对应表中字段的名称？ 如  我要通过视频id在页面展示视频名称

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33947373/115524349-9dcfe480-a2c0-11eb-86db-c2edff8ef35e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
字典注解http://doc.jeecg.com/2043929

获取前端自己翻译

**Comment by bestitxq** [comment]
字典注释并不适用，属于另外表的外键。所以说关联别的表id获取内容，是需要自己关联查询后返回吗？

**Comment by bestitxq** [comment]
哦哦 看到了之前没看到关联表的用法，谢谢啦
