### ISSUE TITLE
【菜单管理】首页调换

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2493]
##### 截图&代码：
我想修改下首页的链接，用企业门户做首页，但是提示没权限。
![image](https://user-images.githubusercontent.com/7098009/115527779-f48aed80-a2c3-11eb-86cd-30a184983771.png)
我想问是说只要在菜单管理里面改变首页的菜单地址就可以了么？
另外，首页标签一直在首位，这个首位的链接是写死的么？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
java代码里面写死的，可以自己改造下
