### ISSUE TITLE
JMultiSelectTag 多选组件，下拉框数据较多（上千条），造成卡顿怎么办

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2494]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26954826/115636759-34dc8100-a341-11eb-9dce-e38777037627.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wan84** [comment]
可以增加一些级联关系，把数据量降下来，展示哪么多用户选起来也痛苦啊

**Comment by pwyGouxiong** [comment]
> 可以增加一些级联关系，把数据量降下来，展示哪么多用户选起来也痛苦啊

哎，就是有那么多同级数据，难受啊~，用户是要可以边搜索查询再选的。。。但是默认下就要那么多，那么那么多。。

**Comment by wan84** [comment]
> > 可以增加一些级联关系，把数据量降下来，展示哪么多用户选起来也痛苦啊
> 
> 哎，就是有那么多同级数据，难受啊~，用户是要可以边搜索查询再选的。。。但是默认下就要那么多，那么那么多。。

加载了分页列表，让用户可以批量选择，可以搜索，下拉选有点坑

**Comment by zhangdaiscott** [comment]
自己改造了，可以改成下拉搜索框
