### ISSUE TITLE
如何使用jeecg-boot的jwt和shiro新接入一套商户的登录和权限验证体系

### ISSUE THREAD

**Issue by wan84** [zhangdaiscott/jeecg-boot#2495]
##### 版本号：
2.4.3

##### 问题描述：
我们加入了一套新的商户的用户体系，怎么接入jeecg-boot的jwt和shiro，有没有相关的文档，谢谢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以参考下第三方登录思路，两套系统用户做绑定
