### ISSUE TITLE
docker部署前端启动失败

### ISSUE THREAD

**Issue by chenyuzhuGit** [zhangdaiscott/jeecg-boot#2497]
##### 版本号：
2.3.0

##### 问题描述：
通过npm run build编译代码后，生成
![image](https://user-images.githubusercontent.com/47171610/115675579-4e9db880-a381-11eb-99ab-cf3cba670ec3.png)
然后根据官方提供的Dockerfile，构建image，启动时报：
![image](https://user-images.githubusercontent.com/47171610/115675826-8a388280-a381-11eb-9912-cd58b4e8b4fb.png)，启动失败

##### 截图&代码：

![image](https://user-images.githubusercontent.com/47171610/115675424-24e49180-a381-11eb-8e25-f8b91de68d9f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看错误日志  配置host

**Comment by chenyuzhuGit** [comment]
根据文档要求，搭建后端环境时已配置host，后端可以正常访问。
![image](https://user-images.githubusercontent.com/47171610/115804555-d0d7bc80-a415-11eb-980f-d0eca5a9bde3.png)
但是前端还是报这个错
![image](https://user-images.githubusercontent.com/47171610/115804645-fb297a00-a415-11eb-80cb-5f5c50aee1bd.png)
后将端口号改为127.0.0.1后可以正常启动。但不知道是什么原因造成的。该服务环境使用的是，vmware创建的centos7系统搭建的docker环境。

**Comment by chenyuzhuGit** [comment]
补充上述回复：
![image](https://user-images.githubusercontent.com/47171610/115805080-cd910080-a416-11eb-8a28-efb7dc329643.png)
