### ISSUE TITLE
Online表单功能测试JVXETable和JEditableTable无法切换

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2499]
##### 问题描述：

在 online 表单开发一对多模型时，行编辑组件默认使用 JVXETable，但是列宽没有自动计算，导致 ui 不美观，所以想按开发手册里的方法切换回 JEditableTable，结果找不到 src/components/online/autoform/OnlineFormSwitch.js，无法切换。  
目前有以下几点疑问：

```
* 1.开源版online表单开发目前是否无法切换JVXETable和JEditableTable，如果是，后续会开放切换吗？如果不是，还请告知切换方法。
* 2.后续更新是否考虑online表单JVXETable和JEditableTable选择配置化？可以自由选择使用哪种行编辑组件。
* 3.后续更新可以优化online表单JVXETable行编辑组件的展示效果（自动计算列宽）吗？
```

##### 截图&代码：  
ui不美观：
![image](https://user-images.githubusercontent.com/46367005/115747515-ef16cb80-a3c7-11eb-80d7-65b62484fd34.png)
官方开发手册切换方法：
![image](https://user-images.githubusercontent.com/46367005/115747583-fb9b2400-a3c7-11eb-9e3a-6974004f7c4e.png)
开源版前端工程并无online目录：
![image](https://user-images.githubusercontent.com/46367005/115747975-52a0f900-a3c8-11eb-9edc-777babf17443.png)

**Comment by zhangdaiscott** [comment]
开源版本暂时不支持切换

**Comment by tuikoushui** [comment]
> 开源版本暂时不支持切换

那后续更新可以优化online表单JVXETable行编辑组件的展示效果（自动计算列宽）吗
