### ISSUE TITLE
这个菜单功能有吗

### ISSUE THREAD

**Issue by LeBronn** [zhangdaiscott/jeecg-boot#25]
![无标题](https://user-images.githubusercontent.com/48777418/54735724-c4ebf180-4be2-11e9-86dd-97712654a55d.png)

**Comment by ileadall42** [comment]
有的，不过目前只能生成单表文件，据说下个版本会更新更高级的生成.

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=338140
