### ISSUE TITLE
online表单开发查询配置下拉搜索框，placeholder会出现‘请选择qq’

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2500]
##### 问题描述：
online表单开发==>查询配置==>下拉搜索框，然后该字段查询框的placeholder会出现“请选择qq”的字样。

##### 截图&代码：
查询配置：  
![image](https://user-images.githubusercontent.com/46367005/115749935-300fdf80-a3ca-11eb-973c-c339cae3c47b.png)
  
查询框的placeholder：
![image](https://user-images.githubusercontent.com/46367005/115749623-dc04fb00-a3c9-11eb-9a86-49f75321a6d2.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
