### ISSUE TITLE
JVXETable获取当前行，row参数出现undefined

### ISSUE THREAD

**Issue by HalcyonDaysssss** [zhangdaiscott/jeecg-boot#2501]
columns内容如下：
![image](https://user-images.githubusercontent.com/24239032/115807359-0fbc4100-a41b-11eb-9392-647fd6c370e6.png)
j-vxe-table内容
![image](https://user-images.githubusercontent.com/24239032/115807387-1f3b8a00-a41b-11eb-9355-88d335a7784f.png)
查看当前行结果内容如下：
![image](https://user-images.githubusercontent.com/24239032/115807487-498d4780-a41b-11eb-8989-a2e071fd3ac2.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by HalcyonDaysssss** [comment]
> 收录 jl
一般这样问题是什么原因导致的？

**Comment by sjlei** [comment]
你的那个action为undefined是正常的，因为本来就没有值。
最下面那个 `undefined: undefined` 是一个bug，已经修复，下版本发布
