### ISSUE TITLE
部门管理，新增部门是，部门名称和手机号码的校验有问题

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#2502]
##### 版本号：
2.4.3

##### 问题描述：
部门管理，新增部门是，部门名称和手机号码的校验有问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5564707/115829742-e9f66280-a441-11eb-8e53-75d696269660.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by tygithub1** [comment]
有什么问题
