### ISSUE TITLE
前端query传参问题

### ISSUE THREAD

**Issue by bingo231** [zhangdaiscott/jeecg-boot#2503]
##### [截图&代码：]

![image](https://user-images.githubusercontent.com/24517482/115847450-8fff9800-a455-11eb-8561-b5fb27bfcaef.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by bingo231** [comment]
![image](https://user-images.githubusercontent.com/24517482/115847702-cb9a6200-a455-11eb-8020-e21740886906.png)

新版本说有解决。但用新版本的代码还是出现这个问题

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by bingo231** [comment]
@zhangdaiscott  已解决

**Comment by yanbenrong** [comment]
> @zhangdaiscott 已解决
咋解决得 现在还有这问题呢
