### ISSUE TITLE
未找到online/cgform/head/list对应后端服务

### ISSUE THREAD

**Issue by quanquan-dane** [zhangdaiscott/jeecg-boot#2505]
##### 问题描述：
未找到/online/cgform/head/list?_t=1619170928此地址对应的后端服务，请告知下，多谢！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/6870297/115853033-49ad3780-a45b-11eb-80a2-3958a9776bbd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
肯定自己动代码了

**Comment by quanquan-dane** [comment]
未动代码，数据可以查到，但是对应的接口、对应的代码找不到
