### ISSUE TITLE
org.jeecg.modules.jmreport.api不存在

### ISSUE THREAD

**Issue by wolfsheep** [zhangdaiscott/jeecg-boot#2506]
##### 版本号：
master最新代码：jeecg boot 2.4.3

##### 问题描述：
今天拉取代码后，进行编译提示我：org.jeecg.modules.jmreport.api不存在

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14920103/115950628-f98fad00-a50e-11eb-81c7-d9d8d29d7a3f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
依赖有没下载成功的吧
