### ISSUE TITLE
自定义树控件在代码生成显示问题

### ISSUE THREAD

**Issue by masaiaaaa** [zhangdaiscott/jeecg-boot#2507]
##### 截图&代码：很奇怪的一个地方，这个小bug难道到现在才被发现吗？你们的官方视频里显示online生成的例子，ces_shop_type这个商品分类表建立几个分类，手机鞋子啥的，然后在ces_shop_goods商品表里可以使用这个分类表，用树形选择。online添加之后列表显示是正常的
![image](https://user-images.githubusercontent.com/49604210/115957148-661ca300-a533-11eb-8de7-d6f1d5fffdcb.png)
但是，我把这个商品表生成代码、配置菜单之后，这个商品表的列表商品分类字段显示的是id
![image](https://user-images.githubusercontent.com/49604210/115957243-b6940080-a533-11eb-8ff7-759b38339473.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
