### ISSUE TITLE
按照步骤成功安装完后，http://localhost:3000/页面无法显示

### ISSUE THREAD

**Issue by newmore** [zhangdaiscott/jeecg-boot#2508]
##### 版本号：
2.4.3

##### 问题描述：

yarn run lint执行完毕后
按照步骤成功安装完后，http://localhost:3000/页面无法显示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1541853/115975593-ef73ab80-a51a-11eb-9e12-0b9388067f82.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043874
