### ISSUE TITLE
未找到online/cgform/head/list对应后端服务

### ISSUE THREAD

**Issue by quanquan-dane** [zhangdaiscott/jeecg-boot#2509]
##### 问题描述：
未找到/online/cgform/head/list?_t=1619170928此地址对应的后端服务，请告知下，多谢！未动代码，数据可以查到，但是对应的接口、对应的代码找不到！！！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/6870297/115977150-d6fda280-a5a7-11eb-9a8e-c56b0b985f06.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此部分没有代码

**Comment by quanquan-dane** [comment]
对应的后端接口并未开源：
![image](https://user-images.githubusercontent.com/6870297/115979896-2a2d2080-a5bb-11eb-8b30-b1679f38e57d.png)
