### ISSUE TITLE
 [Vue warn]: Duplicate keys detected: '/reports'. This may cause an update error.

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#251]
##### 版本号：
2.0.1

##### 问题描述：
总是报这个错误 [Vue warn]: Duplicate keys detected: '/reports'. This may cause an update error.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3365218/60416341-2ecb5c80-9c10-11e9-9ffe-417d84edec6e.png)

**Comment by zhangdaiscott** [comment]
怎么重现？

**Comment by galaxist** [comment]
![image](https://user-images.githubusercontent.com/3365218/60420895-5116a780-9c1b-11e9-9bf9-824ef949b54e.png)
![image](https://user-images.githubusercontent.com/3365218/60420945-67246800-9c1b-11e9-9ae4-f4763ec3d641.png)

会不会是我这里有这个包，于是就出问题了。

**Comment by zhangdaiscott** [comment]
新增的？

**Comment by galaxist** [comment]
嗯 我自己加的代码都放在这里面，是不是有冲突？
