### ISSUE TITLE
online在线表单新增字段时，焦点不会自动定位到最新行数据

### ISSUE THREAD

**Issue by ZebinLiu** [zhangdaiscott/jeecg-boot#2511]
##### 问题描述：
online在线表单新增字段时，焦点不会自动定位到最新行数据，需要手动滑动鼠标滑轮，操作很不方便，希望可以改进。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25631464/115991012-e0632b00-a5f8-11eb-8dd8-7103e3b0b067.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，统一修改

**Comment by sjlei** [comment]
已新增功能，下个版本更新
![image](https://user-images.githubusercontent.com/34293221/122220708-2c3c9d00-cee3-11eb-9380-244f9f24c495.png)
