### ISSUE TITLE
2.3版本docker镜像制作的问题

### ISSUE THREAD

**Issue by chenyuzhuGit** [zhangdaiscott/jeecg-boot#2512]
##### 版本号：
2.3

##### 问题描述：
参考官方文档配置前端构建docker镜像时，按照如下配置：
![image](https://user-images.githubusercontent.com/47171610/115995485-0e069f00-a60e-11eb-8948-ed772d31b684.png)
这时在客户端请求后端接口时，是无法请求到的。
后台请求地址为：http://jeecg-boot-system:8080/jeecg-boot
则客户端也应该配置对应的host映射到服务器IP地址，但是在实际生产中，让客户去配置这个不太现实。
请问您有没有更好的方法，来解决这个问题

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没有，要么你知道后台服务域名，直接配置域名地址
