### ISSUE TITLE
用户管理划分部门错误

### ISSUE THREAD

**Issue by GXXiang** [zhangdaiscott/jeecg-boot#2515]
##### 截图&代码： this.$refs.departWindow.add(this.checkedDepartKeys,this.userId);

![微信图片_20210427092103](https://user-images.githubusercontent.com/71313026/116170734-f2001c00-a739-11eb-8afd-a2b08d585d1b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本太老，请参考最新版
