### ISSUE TITLE
请教升级问题

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/jeecg-boot#2516]
##### 版本号：
2.4.0

##### 问题描述：
目前是2.4.0版本，想升级更新到最新版本，是否有注意事项，有没有升级文档说明？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/blob/master/jeecg-boot/db/%E5%A2%9E%E9%87%8FSQL/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.txt
