### ISSUE TITLE
table样式问题

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2517]
##### 版本号：
2.2.1

##### 问题描述：
当表格内所有内容宽度自适应，开启横向滚动，并且最后一列固定在右侧时，倒数第二列出现双线，给倒数第二列固定宽度也没有作用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26954826/116174320-c0d71a00-a740-11eb-999c-b6bdb423eed3.png)
![image](https://user-images.githubusercontent.com/26954826/116174367-d9dfcb00-a740-11eb-953b-16749318135b.png)
![image](https://user-images.githubusercontent.com/26954826/116174455-0693e280-a741-11eb-88a7-06d99904cd2e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看官方文档https://www.antdv.com/docs/vue/introduce-cn/
