### ISSUE TITLE
如何避免生成的代码被覆盖

### ISSUE THREAD

**Issue by chiewm** [zhangdaiscott/jeecg-boot#2518]
##### 版本号：
v2.4.3

##### 问题描述：
由于业务多变，需要多次生成代码，但是会覆盖掉之前修改过的代码，目前只能手动选择覆盖，是否能选择想要生成的代码呢？或者能不能像在线增强那样，另建一个文件来增强业务，从而避免覆盖那些固定的代码。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by qianlei0007** [comment]
多代码会有问题呀。

**Comment by zhangdaiscott** [comment]
生产完代码，后面就手工改了，不要重复生成
