### ISSUE TITLE
分类数据导入方法BUG，当code，A01A100超过A01A99后，无法正确获取pcode。

### ISSUE THREAD

**Issue by cmxpanda** [zhangdaiscott/jeecg-boot#2519]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/21009035/116193452-fa6c4d00-a761-11eb-8cd7-0b7c6b22e03a.png)
if (code.length() > 3) {
                        //TODO 此处有BUG 编码大于三则无正确截取
                        String pCode = sysCategoryExcel.getCode().substring(0, code.length() - 3);
                        log.info("pCode====>", pCode);
                        String pId = sysCategoryService.queryIdByCode(pCode);
                        log.info("pId====>", pId);
                        if (StringUtils.isNotBlank(pId)) {
                            sysCategoryExcel.setPid(pId);
                        }
                    } else {
                        sysCategoryExcel.setPid("0");
                    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
编码自动生成不需要手动修改，当编码为A99的时候，他的下个编码一定是B01，所以不会出现A100的场景

**Comment by cmxpanda** [comment]
您的意思execl导入时不需要填写code编码吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月26日(周三) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangdaiscott/jeecg-boot] 分类数据导入方法BUG，当code，A01A100超过A01A99后，无法正确获取pcode。 (#2519)




 
编码自动生成不需要手动修改，当编码为A99的时候，他的下个编码一定是B01，所以不会出现A100的场景

**Comment by tygithub1** [comment]
可以自定义，需要遵循这个规则，超过两位数字从下个字母开始 如A99的下个编码是B01

**Comment by cmxpanda** [comment]
哦，这样的逻辑，谢谢，回复！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月26日(周三) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangdaiscott/jeecg-boot] 分类数据导入方法BUG，当code，A01A100超过A01A99后，无法正确获取pcode。 (#2519)




 
可以自定义，需要遵循我们定义的这个规则，超过两位数字从下个字母开始 如A99的下个编码是B01
