### ISSUE TITLE
j-editable-table列表中数据字典列如何配合DictSelectUtil.js函数，实现自动显示字典文本

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#252]
##### 版本号：
2.0.1

##### 问题描述：
j-editable-table列表中数据字典列如何配合DictSelectUtil.js函数，实现自动显示字典文本

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=345678

**Comment by gicp** [comment]
a-table用你说的方法可以，但是j-editable-table不行，它并没有dataindex属性
