### ISSUE TITLE
在线online测试是可以上传文件，自动生成的代码不能保存和上传文件

### ISSUE THREAD

**Issue by jwcjf** [zhangdaiscott/jeecg-boot#2522]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18321599/116219321-10880680-a77e-11eb-94a7-8edcc88ee77a.png)

上传报错
操作失败，JSON parse error: Cannot deserialize value of type `byte[]` from String "1619515578719.png": Failed to decode VALUE_STRING as base64 (MIME-NO-LINEFEEDS): Illegal character '_' (code 0x5f) in base64 content; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `byte[]` from String "1619515578719.png": Failed to decode VALUE_STRING as base64 (MIME-NO-LINEFEEDS): Illegal character '_' (code 0x5f) in base64 content at [Source: (PushbackInputStream); line: 1, column: 9] (through reference chain: org.jeecg.modules.srbmp.testonline.entity.Testonline["file"])

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么类型的字段

**Comment by jwcjf** [comment]
> 什么类型的字段
blob
![image](https://user-images.githubusercontent.com/18321599/116367102-8dc48180-a839-11eb-93eb-43a27d930f07.png)

**Comment by jwcjf** [comment]
改成 text  类型就可以了

![image](https://user-images.githubusercontent.com/18321599/116538181-c2a80580-a919-11eb-84b1-c3305ca635bf.png)
