### ISSUE TITLE
2.4.3版本积木报表设计器点击【新建按钮】报错

### ISSUE THREAD

**Issue by zhaoxinjava0904** [zhangdaiscott/jeecg-boot#2523]
##### 版本号：
2.4.3

##### 问题描述：
本地运行开源版本的jeecg-boot 2.4.3版本，代码只修改了数据库链接地址，其它未做改动，在积木报表设计器点击【新建按钮】报错；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33710359/116397301-06870600-a859-11eb-8755-d212301b3c21.png)
![image](https://user-images.githubusercontent.com/33710359/116397331-0edf4100-a859-11eb-91ec-a0273157fdd7.png)
![image](https://user-images.githubusercontent.com/33710359/116397358-156db880-a859-11eb-8f3d-19052a5b47f9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级积木到最新版本

版本JAR(注意配置jeecg私服)
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```

**Comment by zhaoxinjava0904** [comment]
积木报表的jar升级为您发的那个可以了，谢谢！
