### ISSUE TITLE
下载项目中resources中的文件问题

### ISSUE THREAD

**Issue by jingyingqun1** [zhangdaiscott/jeecg-boot#2524]
##### 问题描述：  1.在项目的resources下有excel文件，想下载下来
                                    但获取不到文件。
                               2.同样,手动写了导出xlsx功能，但是点击后导出是txt格式，手动文件后缀后就是自己想要的xlsx文件

##### 截图&代码：

![image](https://user-images.githubusercontent.com/70041058/116485135-11738200-a8bd-11eb-9000-b2aaa9bc2a3d.png)

![image](https://user-images.githubusercontent.com/70041058/116492415-c6fb0100-a8ce-11eb-838a-e1241e558f31.png)
![image](https://user-images.githubusercontent.com/70041058/116492436-d0846900-a8ce-11eb-989a-767af1d3903d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
请详细描述一下你的操作步骤，最好配以截图
