### ISSUE TITLE
【报表设计器】地图使用静态数据无变化

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2528]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/116570822-209a1480-a93d-11eb-9788-c7cbceaedf1a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
点击刷新了吗

**Comment by kasidier** [comment]
> 点击刷新了吗
刷新了，一刷新数据就又变回默认值了

**Comment by zhangdaiscott** [comment]
地图哪有静态数据配置项目，录个视频吧

**Comment by kasidier** [comment]
https://user-images.githubusercontent.com/7098009/117799126-61225800-b284-11eb-8cbe-4e2df73de39b.mp4

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
运行了没有？

**Comment by 1298191366** [comment]
已修复，待新版本发布
