### ISSUE TITLE
j-upload 组件无法接收父组件传值

### ISSUE THREAD

**Issue by NickDaDa** [zhangdaiscott/jeecg-boot#2529]
##### 版本号：
2.4.2

##### 问题描述：
j-upload 组件无法接收父组件传值。
建议把写死的 “true” 替换掉，改为增加props接收父组件传入。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58328460/116657124-7c59b180-a9c0-11eb-9098-b4bf6e3e6cb8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
已更新组件属性，下版本发布
