### ISSUE TITLE
j-editable-table列表中数据字典列如何配合DictSelectUtil.js函数，实现自动显示字典文本

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#253]
版本号：
2.0.1

问题描述：
j-editable-table列表中数据字典列如何配合DictSelectUtil.js函数，实现自动显示字典文本

a-table用你说的方法可以，但是j-editable-table不行，它并没有dataindex属性
截图&代码：

**Comment by zhangdaiscott** [comment]
目前行编辑暂时没有好的解决方案，你先自己编码给字段的属性options赋值吧
![image](https://user-images.githubusercontent.com/3162115/60433888-71089400-9c38-11e9-808c-d69f7ded1c79.png)

**Comment by zhangdaiscott** [comment]
已经支持，下个版本发布
http://jeecg-boot.mydoc.io/?t=345687
![image](https://user-images.githubusercontent.com/3162115/62210847-b3f08f80-b3cf-11e9-9884-12fd4a1d617f.png)

**Comment by zhangdaiscott** [comment]
代码已经上传，请更新代码
