### ISSUE TITLE
表单输入框中，偶尔会出现文本框里面输入不了内容

### ISSUE THREAD

**Issue by 490937333** [zhangdaiscott/jeecg-boot#2530]
##### 问题描述：
表单输入框中，偶尔会出现文本框里面输入不了内容

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
谷歌的问题吧

**Comment by 490937333** [comment]
我怀疑是前端开发模式下编译后的js文件太大导致的加载问题 ，开发模式下一个js 4-50m 特别大
