### ISSUE TITLE
文件上传建议可根据当前业务类型分类文件

### ISSUE THREAD

**Issue by NickDaDa** [zhangdaiscott/jeecg-boot#2531]
##### 版本号：

2.4.2
##### 问题描述：
可编辑表格上传文件，无法根据业务类型归类，建议可根据当前业务类型分类文件（和普通的j-upload一样）。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58328460/116953707-83363c00-acc0-11eb-8130-cc79d50f2317.png)
![image](https://user-images.githubusercontent.com/58328460/116953738-977a3900-acc0-11eb-885d-d474ce603892.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by sjlei** [comment]
已扩展参数，
![image](https://user-images.githubusercontent.com/34293221/118642209-a8bd5c80-b80d-11eb-8334-1504bbea01cb.png)
