### ISSUE TITLE
字典Table不能实时更新

### ISSUE THREAD

**Issue by helloobj** [zhangdaiscott/jeecg-boot#2535]
##### 版本号：
2.4.3

##### 问题描述：
字段配置了字典Table不能实时更新

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/18436353/117236413-35a20680-ae5b-11eb-9aaf-0ccc2052413d.png)

![图片](https://user-images.githubusercontent.com/18436353/117238692-fb873380-ae5f-11eb-83f2-a824a7002425.png)

![图片](https://user-images.githubusercontent.com/18436353/117238742-080b8c00-ae60-11eb-9ed9-be88035ca6a4.png)

![图片](https://user-images.githubusercontent.com/18436353/117240448-638b4900-ae63-11eb-9700-58007b4d812f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
怎么个操作步骤

**Comment by domingoxx** [comment]
同样的问题，今天刚拉的master分支。

**Comment by AndrewZhang1996** [comment]
缓存不一致 [https://github.com/zhangdaiscott/jeecg-boot/issues/2561#issue-890753877](url)

hibernate-re-2.4.3-RC的问题，没办法改，希望能修补一下。

> 怎么个操作步骤

**Comment by claudehotline** [comment]
遇到了同样的问题，只有清除redis缓存才能获取新值

**Comment by zhangdaiscott** [comment]
已收录，正在处理
