### ISSUE TITLE
j-editable-table当alwaysEdit从false变为true，输入框的数据不会同步

### ISSUE THREAD

**Issue by HalcyonDaysssss** [zhangdaiscott/jeecg-boot#2536]
j-editable-table当alwaysEdit从false变为true，输入框的数据不会同步，手动点击输入框数据可以同步，希望可以设置成alwaysEdit变化也可以同步数据

**Comment by zhangdaiscott** [comment]
alwaysEdit属性还没发布呢，你咋用的

**Comment by HalcyonDaysssss** [comment]
![image](https://user-images.githubusercontent.com/24239032/117388218-ee7c4a00-af1c-11eb-8552-32078bf873e0.png)

**Comment by HalcyonDaysssss** [comment]
https://user-images.githubusercontent.com/24239032/117388502-74989080-af1d-11eb-808e-55dc42fbd76a.mp4

**Comment by HalcyonDaysssss** [comment]
顺便请教下当“规格名”相同时，“规格值”相同则显示检验错误提示，有什么优雅的方法吗？
