### ISSUE TITLE
online表单的字段校验规则不能选择“系统校验规则”里面配置的规则

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2537]
##### 版本号：
2.4.3

##### 问题描述：
online表单的字段校验规则好像是不能选择“系统校验规则”里面配置的规则，后续是否能支持？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46367005/117268079-7dd81d80-ae89-11eb-8424-9b75bf72daf9.png)

![image](https://user-images.githubusercontent.com/46367005/117268279-b11aac80-ae89-11eb-88d9-7f5e8af9a9ea.png)

**Comment by zhangdaiscott** [comment]
有这计划
