### ISSUE TITLE
微服务都是在内网环境中，只有网关会暴露公网，因此服务间调用是没必要鉴权的吗

### ISSUE THREAD

**Issue by zhubinsheng** [zhangdaiscott/jeecg-boot#2539]
##### 版本号：

最新
##### 问题描述：
基本上来说，由于各个服务都是在内网环境中，只有网关会暴露公网，因此服务间调用是没必要鉴权的，目前的情况是拦截器会添加原本请求的token，但是如果是定时器中调用的，我目前没有什么好的办法去处理这种情况？我既不想在system中执行定时器，也不想手动生成一个token传递过去。请问各位大佬是否有奇思妙想来解决我的困惑，不甚感激

##### 截图&代码：
public class FeignConfig {

    @Bean
    public RequestInterceptor requestInterceptor() {
        return requestTemplate -> {
            ServletRequestAttributes attributes = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
            if (null != attributes) {
                HttpServletRequest request = attributes.getRequest();
                log.info("Feign request: {}", request.getRequestURI());
                // 将token信息放入header中
                String token = request.getHeader(CommonConstant.X_ACCESS_TOKEN);
                if(token==null){
                    token = request.getParameter("token");
                }
                log.info("Feign request token: {}", token);
                requestTemplate.header(CommonConstant.X_ACCESS_TOKEN, token);
            }else {
                log.info("分布式定时任务执行的");
                requestTemplate.header(CommonConstant.X_ACCESS_TOKEN, "token");
            }
        };
    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
服务之间token机制已经做好了，不需要你做额外的工作

**Comment by zhubinsheng** [comment]
> 服务之间token机制已经做好了，不需要你做额外的工作

首先我是2.4.3版本，据我所知，服务之间是通过http请求的吧，我在实际应用中，是定时任务去请求的，所以甚至说在redis中没有存放任何token。其次不同服务存放在不同服务器中，非内网，这点好像影响不大。
综上，定时任务中想要调用其他服务的api没有携带token；
另外服务之间token机制是将原本的请求加在服务调用的请求头里，除了这个还有其他的内容吗？

**Comment by zhangdaiscott** [comment]
定时任务中想要调用其他服务的api是没有携带token；
你得单独处理

**Comment by zhangdaiscott** [comment]
微服务之间调用免Token方案
http://doc.jeecg.com/2725212

**Comment by zjarlin** [comment]
> 服务之间token机制已经做好了，不需要你做额外的工作

sysCloud gatway nacos 服务连同一个redis,各个业务模块(demo1,demo2)连不同redis,这样可以嘛;服务间的token机制是在哪个类里的,我去研究下
