### ISSUE TITLE
查询为空时，需要加判断，不然拼接sql会报错

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#254]
##### 版本号：
2.0.1

##### 问题描述：
查询为空时，需要加判断，不然拼接sql会报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3365218/60479646-211de180-9cb9-11e9-9ece-1b5ce83632ba.png)
![image](https://user-images.githubusercontent.com/3365218/60479650-27ac5900-9cb9-11e9-9ef2-0179335ca512.png)
![image](https://user-images.githubusercontent.com/3365218/60479660-2da23a00-9cb9-11e9-9577-fd65ba3aa877.png)
这里要加判断是否为空
![image](https://user-images.githubusercontent.com/3365218/60479717-5f1b0580-9cb9-11e9-942f-6e1ac28640ae.png)
```
        Collection<String> anntIds = sysAnnouncementSendService.queryByUserId(userId);
        LambdaQueryWrapper<SysAnnouncement> querySaWrapper = new LambdaQueryWrapper<SysAnnouncement>();
        querySaWrapper.eq(SysAnnouncement::getMsgType, CommonConstant.MSG_TYPE_ALL); // 全部人员
        querySaWrapper.eq(SysAnnouncement::getDelFlag, CommonConstant.DEL_FLAG_0);  // 未删除
        querySaWrapper.eq(SysAnnouncement::getSendStatus, CommonConstant.HAS_SEND); //已发布
        if (!anntIds.isEmpty()) {
            querySaWrapper.notIn(SysAnnouncement::getId, anntIds);
        }
        List<SysAnnouncement> announcements = sysAnnouncementService.list(querySaWrapper);
```

**Comment by zhangdaiscott** [comment]
这块已经改了，下个版本更新上去 3Q
