### ISSUE TITLE
JEditableTable,当 type=popup 时,popup里面的数据排序问题【急求解决方案，感谢！】

### ISSUE THREAD

**Issue by pwyGouxiong** [zhangdaiscott/jeecg-boot#2545]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26954826/117530213-7726e300-b00e-11eb-870e-8ce1bdd2e19f.png)
![image](https://user-images.githubusercontent.com/26954826/117530223-8017b480-b00e-11eb-8bad-c38682098692.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by pwyGouxiong** [comment]
已解决。。方法有点笨，但是能实现：
第一步：给需要加排序的popupCode后面加上?sort=true&column=company_name&order=desc
第二步：JPopupOnlReport.vue里，判断是否包含sort=true，如果包含，则把需要排序的字段拼接到后面。
![image](https://user-images.githubusercontent.com/26954826/117533297-9c235200-b01e-11eb-9ee0-19f35f67e995.png)

在此期待开发团队提供更好的解决办法。

**Comment by sjlei** [comment]
已支持该功能，下版本发布

![image](https://user-images.githubusercontent.com/34293221/119108599-ed860500-ba52-11eb-8456-3f39d75d7d19.png)


![image](https://user-images.githubusercontent.com/34293221/119108547-e101ac80-ba52-11eb-91d3-8367f5295fea.png)
