### ISSUE TITLE
【Online在线表单开发】页面属性的下拉搜索框在功能测试时展示为数字文本框

### ISSUE THREAD

**Issue by quzehu** [zhangdaiscott/jeecg-boot#2549]
##### 版本号：
V2.4.3

##### 问题描述：
使用Online表单开发功能，在页面属性Tab页中，“Integer”的数字类型字段选择下拉搜索框，填入字典编码后，在功能测试时展示的不是下拉搜索框，而是数字文本框。当把数字类型改为字符串类型后，则能显示出下拉搜索框，但是字典编码的读取有误，见如下截图。下拉框没有这个问题，下拉搜索框有。Popup弹窗也有这个问题，当字段类型是Integer数字类型时，就无法正常显示。希望Integer数字类型的字段使用下拉搜索框时，能够正确展示出控件。

##### 截图&代码：
Integer类型字段截图
![image](https://user-images.githubusercontent.com/33826388/117605702-eb869100-b18a-11eb-8aee-58f8e4887267.png)
页面属性截图
![image](https://user-images.githubusercontent.com/33826388/117605671-dc9fde80-b18a-11eb-859f-32f03ecf6091.png)
填入字典截图
![image](https://user-images.githubusercontent.com/33826388/117605769-107b0400-b18b-11eb-9cf5-6a3fd62de8e0.png)
功能测试截图
![image](https://user-images.githubusercontent.com/33826388/117605824-27215b00-b18b-11eb-8b06-fe790a754434.png)

修改为字符串类型后
String类型字段截图
![image](https://user-images.githubusercontent.com/33826388/117605884-49b37400-b18b-11eb-8d52-fed4c20e9a6c.png)

功能测试截图
![image](https://user-images.githubusercontent.com/33826388/117605965-7a93a900-b18b-11eb-901b-ceb868feb661.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
按文档操作：http://doc.jeecg.com/2044072
