### ISSUE TITLE
JVxeTable组件的拖拽排序功能异常

### ISSUE THREAD

**Issue by lixiaolinlala** [zhangdaiscott/jeecg-boot#2551]
##### 版本号：
2.4.2

##### 问题描述：

在使用JVxeTable组件的拖拽排序功能的时候，发现当数据量大于100条时，拖拽排序异常(小于100条记录的时候this.rows.length显示的是table的长度，是正常的)，如下截图第十五条的数据无法向下移动，下面代码this.rows.length显示的是15，可否帮忙解决一下
##### 截图&代码：

  disabledMoveDown() {
        return this.rowIndex === (this.rows.length - 1)
      },
![image](https://user-images.githubusercontent.com/22430553/117752750-ea686900-b249-11eb-8254-659eeddf852b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
问题已修复，下版本更新
