### ISSUE TITLE
【分类字典树】无法设置默认值

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2552]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/117797667-db51dd00-b282-11eb-81ea-c5cf2efe2581.png)
![image](https://user-images.githubusercontent.com/7098009/117797694-e3118180-b282-11eb-9acc-e88d55e25485.png)
![image](https://user-images.githubusercontent.com/7098009/117797712-e99ff900-b282-11eb-8623-e4e008dc7917.png)
![image](https://user-images.githubusercontent.com/7098009/117798255-8793c380-b283-11eb-81e2-072c618abd89.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
先确定树控件存到数据库的是什么再配置  如果id你配置编码肯定无法生效
