### ISSUE TITLE
excel 导入时，小数点后的数据会丢失

### ISSUE THREAD

**Issue by EslSuwen** [zhangdaiscott/jeecg-boot#2555]
##### 版本号：

2.4.3
##### 问题描述：

online表单在线开发生成的功能，excel 导入时，小数点后的数据会丢失

##### 截图&代码：

实体
![image](https://user-images.githubusercontent.com/31917734/117909255-7b077d80-b30c-11eb-977f-3c0f3dae4fe2.png)

excel
![image](https://user-images.githubusercontent.com/31917734/117909309-983c4c00-b30c-11eb-80c2-f07d64ef824c.png)

到插入是就成 V1了
![image](https://user-images.githubusercontent.com/31917734/117909385-ba35ce80-b30c-11eb-811c-613aa6daefb2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
该bug已经修复
