### ISSUE TITLE
代码生成树表haschild存在问题，为什么不在add时就给haschild赋值为0

### ISSUE THREAD

**Issue by zfy220** [zhangdaiscott/jeecg-boot#2558]
##### 版本号：
2021年4月14号的开源版本

##### 问题描述：
代码生成树中，新增时haschild为null，但是添加一个下级后haschild为1，删除这个下级节点haschild就置为0了，会导致树的叶子节点中haschild字段有两种值，为null或者0

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61905108/118064023-ced99b80-b3cc-11eb-939e-d01008f5a5b0.png)

![image](https://user-images.githubusercontent.com/61905108/118064059-e1ec6b80-b3cc-11eb-8770-110d93400802.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
已收录
