### ISSUE TITLE
微服务启动JeecgSystemCloudApplication控制台一直在Init DruidDataSource

### ISSUE THREAD

**Issue by wushengfa233** [zhangdaiscott/jeecg-boot#2560]
##### 版本号：
2.4.3

##### 问题描述：
按照文档要求步骤来的，微服务启动JeecgSystemCloudApplication控制台一直在Init DruidDataSource

##### 截图&代码：
![image](https://user-images.githubusercontent.com/43536040/118079331-98ab1480-b3ea-11eb-858e-7bb590b342e7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Durant-Wen** [comment]
这个问题如何解决？
