### ISSUE TITLE
退出登录时的提示与功能名称不统一

### ISSUE THREAD

**Issue by gongjimin** [zhangdaiscott/jeecg-boot#2562]
##### 版本号：
官方演示系统，我不知道版本号在哪儿看到。

##### 问题描述：
点击“退出登录”时提示“真的要注销登录吗 ?”
“注销”和“退出”没有统一

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by pwyGouxiong** [comment]
UserMenu.vue里面自己改了呗

**Comment by AndrewZhang1996** [comment]
这个改一下就好了
