### ISSUE TITLE
yarn build报错TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by junk123321** [zhangdaiscott/jeecg-boot#2564]
##### 版本号：
yarn 1.22.10
ant-design-vue-jeecg最新版本2.4.3
```
D:\jeecg-boot\ant-design-vue-jeecg>git pull
Already up to date.
```

##### 问题描述：
yarn build报错TypeError: Class extends value undefined is not a constructor or null。yarn serve正常可以使用。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/31426899/118106784-8fcd3980-b410-11eb-9995-9cbf22b961a9.png)

**Comment by zhangdaiscott** [comment]
yarn install
