### ISSUE TITLE
cron表达式解析失败

### ISSUE THREAD

**Issue by cccccccccmmm** [zhangdaiscott/jeecg-boot#2569]
##### 版本号：
2.4.2

##### 问题描述：

cron表达式  具体天数(可多选)  单选时 反解析失败（代码中只考虑多选情况）
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/84298109/118421834-7bc95680-b6f4-11eb-984e-b9532e60100b.png)
![图片](https://user-images.githubusercontent.com/84298109/118421873-96033480-b6f4-11eb-8bb1-1731cdf4911d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本，出新版控件

**Comment by Fliner** [comment]
@zhangdaiscott 您好，我查看了下2.4.5版本的JCron好像没有改，但是更新日志里写了解决该问题

**Comment by zhangdaiscott** [comment]
新版都换组件了
