### ISSUE TITLE
打war包到tomcat下，前端nginx访问，点击登录报ErrorPageFilter错误

### ISSUE THREAD

**Issue by healkerzk** [zhangdaiscott/jeecg-boot#257]
##### 问题描述：
打war包到tomcat下，前端nginx访问，点击登录报ErrorPageFilter错误。
idea启动项目，前端nginx访问正常访问并登录

##### 截图&代码：
nginx配置：
![image](https://user-images.githubusercontent.com/35994418/60499785-b8039180-9ceb-11e9-81ce-35c287ae9235.png)

报错截图：
![image](https://user-images.githubusercontent.com/35994418/60499970-12045700-9cec-11e9-963b-6c5e0ba68b7d.png)

**Comment by zhangdaiscott** [comment]
看着日志没用

**Comment by galaxist** [comment]
springboot项目打成war包，部署到tomcat里，这是多么反人类的部署模式，简直不应该用jeecgboot应该用jeecg。。。

**Comment by zhangdaiscott** [comment]
参考这个文档
http://jeecg-boot.mydoc.io/?t=345683

**Comment by healkerzk** [comment]
是根据 http://jeecg-boot.mydoc.io/?t=345683 这个文档改的，出现了这个ErrorPageFilter的错误
