### ISSUE TITLE
在online开发中，数据库字段备注能否和页面属性的label解耦

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2570]
##### 版本号：
2.4.3

##### 问题描述：
数据库的表设计规范要求（图一），状态位必须备注说明每个值代表含义，但如果状态位的状态值过多就会出现表单label和表格title过长（图二、图三）的情况。
能否在在线开发页面，将页面属性里的字段备注和数据库表的字段备注解耦（图四），让其可以被修改保存，页面显示以页面属性的字段备注为准，使得设计规范和页面显示不冲突，达到最佳结果。

##### 截图&代码：
图一
![image](https://user-images.githubusercontent.com/46367005/118586222-eea60080-b7cc-11eb-9b52-d88e44b63b7c.png)
图二
![image](https://user-images.githubusercontent.com/46367005/118586317-1ac18180-b7cd-11eb-97b3-40e4d26303a0.png)
图三
![image](https://user-images.githubusercontent.com/46367005/118586565-93c0d900-b7cd-11eb-988f-08cbbfcf897e.png)
图四
![image](https://user-images.githubusercontent.com/46367005/118586667-bd7a0000-b7cd-11eb-883e-3c9339db9db8.png)

**Comment by zhangdaiscott** [comment]
目前不支持
