### ISSUE TITLE
dictCode下拉列表 可以使用多条件查询吗

### ISSUE THREAD

**Issue by hyoutom** [zhangdaiscott/jeecg-boot#2574]
##### 版本号：
2.4.3

##### 问题描述：
dictCode下拉列表 可以使用多条件查询吗？ 例如 dictCode="table,a,b,is_del='1' and id='2'"

##### 截图&代码：

![image](https://user-images.githubusercontent.com/51776513/118792068-e1bb0700-b8c9-11eb-9b8a-dfd6d4cc9572.png)

![image](https://user-images.githubusercontent.com/51776513/118792121-ee3f5f80-b8c9-11eb-84b7-239011dc01bd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该可以
