### ISSUE TITLE
excel导入乱码

### ISSUE THREAD

**Issue by yuyu414** [zhangdaiscott/jeecg-boot#2575]
版本号：
2.4.3

问题描述：
excel导入乱码，客户这边使用的有的是office或者wps，还有不同客户的电脑操作系统的编码也不同

##### 截图&代码：
所以导致部分客户的导入导出乱码，我想问一下如何处理，或者源码是如何处理的？不可能让用户统一utf-8或者某种编码

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/autopoi
自己debug改把

**Comment by yuyu414** [comment]
> https://github.com/zhangdaiscott/autopoi
> 自己debug改把

哈哈，我其实是想看看他们怎么设计的，没有的话，还不如我自己封装么
