### ISSUE TITLE
跨域

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2578]
##### 版本号：
2.4.3

##### 问题描述：
Access to XMLHttpRequest at 'http://localhost:9999/jeecg-gateway/sys/randomImage/1621475655064?_t=1621475655' from origin 'http://localhost' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost, http://localhost', but only one is allowed.

但是在后台gateway 的配置文件中把
globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            #allowedHeaders: "*"
把其中的allowedheaders注释掉，又报错不允许跨域了
Access to XMLHttpRequest at 'http://localhost:9999/jeecg-gateway/sys/randomImage/1621475793311?_t=1621475793' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
##### 截图&代码：
![image](https://user-images.githubusercontent.com/11720763/118907333-e75c2f80-b951-11eb-8f94-c4829e9f2a70.png)

![image](https://user-images.githubusercontent.com/11720763/118907298-d8757d00-b951-11eb-8e29-84d21175d688.png)

![image](https://user-images.githubusercontent.com/11720763/118907357-f2af5b00-b951-11eb-885a-90b1bd458049.png)

![image](https://user-images.githubusercontent.com/11720763/118907220-bb40ae80-b951-11eb-95bf-3e5bcc103c27.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
gateway方式跨域已经做了处理，不清楚你怎么用的

**Comment by ly0518** [comment]
gateway是解决了跨域，但是多了一层代理
![image](https://user-images.githubusercontent.com/11720763/118908916-d2cd6680-b954-11eb-8acf-bae25bf78dc6.png)

**Comment by ly0518** [comment]
帮忙解答下  谢谢

**Comment by zhangdaiscott** [comment]
没理解，你是什么场景下遇到跨域问题

**Comment by ly0518** [comment]
前端代码


编译后放置nginx里（未配置跨域）





后台（没有做任何改动）







登录页面









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月20日(星期四) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 跨域 (#2578)





 
没理解，你是什么场景下遇到跨域问题

**Comment by ly0518** [comment]
前端代码
![image](https://user-images.githubusercontent.com/11720763/118924705-0b2e6e00-b970-11eb-89a1-a3d8d854ea75.png)
编译后放置nginx里（未配置跨域）
![image](https://user-images.githubusercontent.com/11720763/118924736-14b7d600-b970-11eb-9d26-1bb8a7af680d.png)
后台（没有做任何改动）
![image](https://user-images.githubusercontent.com/11720763/118924765-1da8a780-b970-11eb-9e4e-f2793f098c23.png)
登录页面
![image](https://user-images.githubusercontent.com/11720763/118924800-28fbd300-b970-11eb-8ade-0818c3fe82d3.png)

**Comment by zhangdaiscott** [comment]
为什么配置这个
![image](https://user-images.githubusercontent.com/3162115/118924897-4fba0980-b970-11eb-9723-25a59f13dd90.png)

**Comment by ly0518** [comment]
![Uploading image.png…]()
去掉后面红框里得这个吗

**Comment by ly0518** [comment]
![image](https://user-images.githubusercontent.com/11720763/118925082-ac1d2900-b970-11eb-93d8-a1b4cace96b8.png)
去掉红框里得吗

**Comment by ly0518** [comment]
能否给解决下
