### ISSUE TITLE
菜单为什么会空白一块，点击看似按钮，但也没有什么反应

### ISSUE THREAD

**Issue by wangchao0899** [zhangdaiscott/jeecg-boot#2579]
##### 版本号：
2.4.3

##### 问题描述：
菜单为什么会空白一块，点击看似按钮，但也没有什么反应，请问如何删除空白

##### 截图&代码：
![Video_2021-05-21_113654](https://user-images.githubusercontent.com/53893157/119078769-6bcdb180-ba29-11eb-816b-1151cbf26e3c.gif)

菜单设置里面也没有空白项目
![image](https://user-images.githubusercontent.com/53893157/119078874-9e77aa00-ba29-11eb-901e-7b568b351326.png)

数据库里面，也没有空白的条目
![image](https://user-images.githubusercontent.com/53893157/119079061-f1e9f800-ba29-11eb-9855-896d10de9474.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你操作后导致的吧，我们本地未重现
