### ISSUE TITLE
JS增强怎么实现点击一个表单的列表页面的自定义按钮弹出另一个表单的新增页面呢？

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2580]
##### 版本号：
2.4.3

##### 问题描述：
我想在员工信息页面选择一条记录点击入职按钮，弹出入职的新增页面，并带一部分值过去，以前用jeecg版本是可以实现的，查看网页源代码可以看到新增的方法，创建新增弹框的方法，但是jeecg-boot版本不会用，也找不到，还有比如我想限制某些状态不能编辑，某些状态不能删除，我可以重写编辑删除方法，掉编辑删除之前加判断条件，在jeecg-boot版本不知道怎么做！大佬！能不能指导下！

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持
