### ISSUE TITLE
Online 表单开发字段设置Popup后无法使用参数

### ISSUE THREAD

**Issue by kevinchuxu** [zhangdaiscott/jeecg-boot#2582]
表单定义Popup数据来源时引用Report报表，目前不支持动态参数。

功能开发中，计划下一版本发布。

**功能设计：**
定义表单字段时，如果引用Popup类型，可以在字典Table名字后面加上参数，静态参数现已支持。

如果使用动态参数，引用字段值写法为${field_name}
![image](https://user-images.githubusercontent.com/5389183/92340715-07aecb80-f0ee-11ea-8ff8-e6f89d2d2d94.png)

**动态参数功能开发：**
1，表单查询、新增数据时，去除动态参数。

2，编辑数据时，根据当前行数据，替换动态参数。
![image](https://user-images.githubusercontent.com/5389183/92340915-9f141e80-f0ee-11ea-9b6e-ae23ba6883bf.png)

_Originally posted by @rickding in https://github.com/zhangdaiscott/jeecg-boot/issues/1666#issuecomment-687972494_

引用上述方法测试无效

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
popup没有在字典table上配置动态参数的功能，online里也不支持popup动态参数的功能，如果是自己写的代码，动态参数的使用请参考文档： http://doc.jeecg.com/2044000

**Comment by tb2888** [comment]
> 表单定义Popup数据来源时引用Report报表，目前不支持动态参数。
> 
> 功能开发中，计划下一版本发布。
> 
> **功能设计：**
> 定义表单字段时，如果引用Popup类型，可以在字典Table名字后面加上参数，静态参数现已支持。
> 
> 如果使用动态参数，引用字段值写法为${field_name}
> ![image](https://user-images.githubusercontent.com/5389183/92340715-07aecb80-f0ee-11ea-8ff8-e6f89d2d2d94.png)
> 
> **动态参数功能开发：**
> 1，表单查询、新增数据时，去除动态参数。
> 
> 2，编辑数据时，根据当前行数据，替换动态参数。
> ![image](https://user-images.githubusercontent.com/5389183/92340915-9f141e80-f0ee-11ea-9b6e-ae23ba6883bf.png)
> 
> _Originally posted by @rickding in [#1666 (comment)](https://github.com/jeecgboot/jeecg-boot/issues/1666#issuecomment-687972494)_
> 
> 引用上述方法测试无效
大佬！这个功能会实现么？

**Comment by tb2888** [comment]
> 收录 ty

大佬，报表动态传参这个功能会实现么？
