### ISSUE TITLE
项目如果是考虑微服务不考虑单体应用，需要怎么改项目结构

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2587]
##### 版本号：
2.4.3

##### 问题描述：
项目如果是考虑微服务不考虑单体应用，需要怎么改项目结构

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11720763/119335972-99338d00-bcbf-11eb-9e33-1fcf02033053.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
删掉即可
![image](https://user-images.githubusercontent.com/3162115/119338956-3643f500-bcc3-11eb-8159-2fefb4c343ad.png)
