### ISSUE TITLE
新版 没有api和biz之分了吗

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2589]
##### 版本号：
2.4.3

##### 问题描述：
新版 没有api和biz之分了吗
我看jeecg-gen都没有了

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？

**Comment by ly0518** [comment]
我看学习视频里有个jeecg-gen的骨架工程，但是github上没有找到呢？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2159148
