### ISSUE TITLE
JS增强根据条件怎么限制不让编辑和删除呢？

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2592]
##### 版本号：

2.4.3
##### 问题描述：
比如说一条数据有草稿、提交状态，我想数据如果是提交状态就不让编辑和删除了，能做到么？用beforeEdit方法抛异常不行，还是会弹框编辑，帮助文档上也没找到方法！

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
下个版本支持。
beforeEdit(row){
	return new Promise((resolve, reject) => {
        console.log('row', row)
      	if(row.name == 'test'){
        	reject('不可编辑test数据');
        }else{
        	resolve();
        }
      })     
}

**Comment by tb2888** [comment]
感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] JS增强根据条件怎么限制不让编辑和删除呢？ (#2592)





 
下个版本支持。

**Comment by tb2888** [comment]
大佬2.4.5版本限制删除之后还是删掉了，link的删除能删，button的批量删除也能删，限制编辑可以用！
下图表单JS增强

点击link删除按钮效果，但是控制台有我写的提示语







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月30日(星期天) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JS增强根据条件怎么限制不让编辑和删除呢？ (#2592)





 
收录 ty

**Comment by zhangdaiscott** [comment]
得2.4.6了，当前版本部分功能未更新

**Comment by tb2888** [comment]
好的！谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JS增强根据条件怎么限制不让编辑和删除呢？ (#2592)





 
得2.4.6了，当前版本部分功能未更新
