### ISSUE TITLE
修改头像modal

### ISSUE THREAD

**Issue by liujuntao1** [zhangdaiscott/jeecg-boot#2593]
##### 问题描述：个人中心-账户设置
修改头像，点击头像弹出modal，右上角X号点击没反应

##### 截图&代码：
![9206ad3b03b8174cc29b84999a2b81c](https://user-images.githubusercontent.com/53896641/119620379-7fb55100-be37-11eb-86e7-4304171dfc71.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下个版本发布
