### ISSUE TITLE
【流程设计】如何设置当前部门主管

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2595]
##### 问题描述：
流程设计中，部门主管如何指定当前所在部门主管？

##### 截图&代码：
流程的部门主管，如何获得当前所在部门的主管？
![image](https://user-images.githubusercontent.com/7098009/119637437-3ae5e600-be48-11eb-9827-ccf47c128911.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有表达式，演示系统让人把表达式删了
