### ISSUE TITLE
JS增强好像没有能控制控件的属性方法，比如表单控制不能点提交按钮，把某个文本框设成只读啥的，还是我没发现

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2596]
##### 版本号：
2.4.3

##### 问题描述：
我是做后端的，所以前端的东西不是很懂！不好意思，如果是有那些方法是我没发现，我想说大佬帮助文档能不能出个比较全面的JS增强方法文档哦？比如说在线表单JS增强中通过that都能做哪些事！像that.handleSubmit();帮助文档里面也没有，是我自己找的！但是找起来有些也看不出是干了些什么

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044100

**Comment by tb2888** [comment]
在线帮助文档里面的内容我看了好多遍了！就介绍了那么几个方法！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 晚上7:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JS增强好像没有能控制控件的属性方法，比如表单控制不能点提交按钮，把某个文本框设成只读啥的，还是我没发现 (#2596)





 
http://doc.jeecg.com/2044100
