### ISSUE TITLE
JEECG 用户角色按钮授权了，还是提示“没有权限，请联系管理员授权”

### ISSUE THREAD

**Issue by jacklinnnn** [zhangdaiscott/jeecg-boot#2597]
##### 截图&代码：
![QQ图片20210527115648](https://user-images.githubusercontent.com/39985297/119763801-ca3fd780-bee2-11eb-9d4f-89921d3d04a7.png)
![QQ图片20210527115656](https://user-images.githubusercontent.com/39985297/119763809-cd3ac800-bee2-11eb-8946-38c8ec63f221.png)
![image](https://user-images.githubusercontent.com/39985297/119763919-0a9f5580-bee3-11eb-8df7-bc0e52c16453.png)

![image](https://user-images.githubusercontent.com/39985297/119763829-d6c43000-bee2-11eb-8071-8eb31a789c9d.png)

按钮已授权，还是提示没有权限！

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
重启了吗，

**Comment by jacklinnnn** [comment]
前端后端都重启过，也重新退出登录了！

**Comment by zcrman** [comment]
我也遇到这个问题了，请问解决了吗？

**Comment by crazyii** [comment]
重启后，退出重新登录还有这个问题的话。 是因为 服务端改了  redis 缓存的 shirokey 的常量名。  在CommonConstant文件里。  
这个key是在不开源那部分代码里设置的。 退出登录的时候 如果改了包名，会清理不掉这个key。 导致shiro那权限无法刷新。
<img width="351" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/11659417/4feddc86-a2d2-48ca-804c-ee279f9e1c7b">
