### ISSUE TITLE
多租户服务端对请求头校验

### ISSUE THREAD

**Issue by numbernumberone** [zhangdaiscott/jeecg-boot#2598]
##### 版本号：
2.4.3
##### 问题描述：
客户端修改 租户id 的话服务端在这里应该做个校验吧。

##### 截图&代码：
        //update-begin-author:taoyan date:20200708 for:多租户用到
        String tenant_id = httpServletRequest.getHeader(CommonConstant.TENANT_ID);
        TenantContext.setTenant(tenant_id);
        //update-end-author:taoyan date:20200708 for:多租户用到
        return super.preHandle(request, response);

![image](https://user-images.githubusercontent.com/17960477/119773555-6245bd00-bef3-11eb-9abe-661cc98a374d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by numbernumberone** [comment]
收录ty 是什么意思啊？

**Comment by tygithub1** [comment]
已修改
