### ISSUE TITLE
创建三级菜单，页面在第三级菜单无法跳转

### ISSUE THREAD

**Issue by WangHuaxin** [zhangdaiscott/jeecg-boot#2599]
##### 版本号：
v2.4.3 

##### 问题描述：
创建三级菜单，页面在第三级菜单无法跳转，第一级和第二级菜单可正常跳转。
如：一级菜单  ->  二级菜单  ->  三级菜单：页面无法跳转

##### 截图&代码：

![image](https://user-images.githubusercontent.com/22535255/119880842-3d872f00-bf5f-11eb-9561-13ed361a05b5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题未复现
