### ISSUE TITLE
无限打开菜单，再回去在左侧菜单栏点一个已经打开的菜单，发现菜单标题和内容不一致，错位了

### ISSUE THREAD

**Issue by chengtg** [zhangdaiscott/jeecg-boot#26]

**Comment by zhangdaiscott** [comment]
来个截图

**Comment by chengtg** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7872&extra=page%3D1 可以看这里面的截图

**Comment by chengtg** [comment]
http://www.jeecg.org/data/attachment/forum/201903/21/215400olasc6ly62p6sd3x.png

**Comment by zhangdaiscott** [comment]
怎么出现的？没重现，麻烦提供下重现步骤

**Comment by zhangdaiscott** [comment]
已经修复，等待新版发布
