### ISSUE TITLE
2.4.2 使用vue-amap问题

### ISSUE THREAD

**Issue by loongw513029** [zhangdaiscott/jeecg-boot#2601]
##### 版本号：
2.4.2

##### 问题描述：
只要使用<el-amap 就出现 未注册components
did you register the component correctly? For recursive components, make sure to provide the "name
##### 截图&代码：

![image](https://user-images.githubusercontent.com/12654938/119926305-b4491a00-bfa9-11eb-9732-4ea7e97c5110.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
vue-amap 你安装了吗
