### ISSUE TITLE
更改包名后，启动system报错

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2602]
##### 版本号：
2.4.3

##### 问题描述：
更改包名后，启动system报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11720763/119936966-93d68b00-bfbc-11eb-9587-6ed08d60d7f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
原有的扫码路径保留

**Comment by ly0518** [comment]
> 原有的扫码路径保留
下面两个地方都加上了，
![image](https://user-images.githubusercontent.com/11720763/119938716-650de400-bfbf-11eb-831a-13e0db23bae0.png)
![image](https://user-images.githubusercontent.com/11720763/119938916-af8f6080-bfbf-11eb-8818-b553baa201a8.png)
![image](https://user-images.githubusercontent.com/11720763/119938968-c0d86d00-bfbf-11eb-92ea-2c524a628fba.png)

**Comment by ly0518** [comment]
> 原有的扫码路径保留
这里也没变
![image](https://user-images.githubusercontent.com/11720763/119939344-4a883a80-bfc0-11eb-8429-448836e885cd.png)

**Comment by CRIOWN** [comment]
你好 请问这个问题解决了吗 能否说一下 我也遇到了相同的问题
