### ISSUE TITLE
扫描不到类

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2603]
##### 版本号：
2.4.3

##### 问题描述：

实在不知道哪里的问题了，pom都看了也没问题，单体应用也是找不到EmptyInterceptor类
##### 截图&代码：

![image](https://user-images.githubusercontent.com/11720763/119946549-54626b80-bfc9-11eb-9ba8-7c359eb087fe.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你要不重写这个类，try catch掉，不清楚你为什么会获取不到报错

**Comment by ly0518** [comment]
try catch 有什么影响吗

**Comment by zhangdaiscott** [comment]
没有
