### ISSUE TITLE
【报表设计器】循环块无法取消

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2606]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/120096254-f6668d00-c15c-11eb-8e27-d778b8cccdbc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改，下个版本发布
