### ISSUE TITLE
前端用户选择单选无法置空的问题

### ISSUE THREAD

**Issue by WDFM** [zhangdaiscott/jeecg-boot#2610]
##### 截图&代码：已经解决，在`JSelectUserByDepModal.vue`中做如图修改
![image](https://user-images.githubusercontent.com/30794779/120138159-87467280-c208-11eb-88c4-e87739efd333.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
