### ISSUE TITLE
【报表设计】获取登录人的登录部门

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2612]
##### 问题描述：在报表设计中如何使用当前登录人的部门

sysOrg
##### 截图&代码：
我想要获取与当前登录人的登录部门相同的人员列表，是否可以使用sysOrgCode?
select * from sys_user where org_code=#{sysOrgCode}
![image](https://user-images.githubusercontent.com/7098009/120170689-cf2ebf00-c233-11eb-9f6e-7a1425280960.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2159712
