### ISSUE TITLE
为什么不能支持多个外键

### ISSUE THREAD

**Issue by chengang2** [zhangdaiscott/jeecg-boot#2613]
##### 版本号：
2.4.3

##### 问题描述：
比如商品，订单关系。那中间表：订单商品表，就应该是有两个外键。good_id, order_id。
这里有两个问题。
1：我只在一张表（订单表） 看到对应的附表。商品表没看到对应的附表。如图1,2,3
2：基于这种多对多的设计，订单商品表里面如何自动展示对应的商品名称，商品价格。我在功能测试中只能对应到具体的商品id。
如图4：

##### 截图&代码：
问题1：
图1：

![image](https://user-images.githubusercontent.com/16473239/120170767-e40b5280-c233-11eb-8454-cdc817fc16a2.png)

图2：
![image](https://user-images.githubusercontent.com/16473239/120170823-f1c0d800-c233-11eb-85b0-be2ba75f5d47.png)

图3：

![image](https://user-images.githubusercontent.com/16473239/120170885-04d3a800-c234-11eb-9b4d-60cb17d66e27.png)

问题2：
图4:

![image](https://user-images.githubusercontent.com/16473239/120171220-64ca4e80-c234-11eb-8a64-02b73f7d7dfa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不支持多个外键，后期优化

归集到https://github.com/zhangdaiscott/jeecg-boot/issues/1312
