### ISSUE TITLE
【报表设计器】图表丢失

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2614]
##### 截图&代码：

https://user-images.githubusercontent.com/7098009/120197670-cbab3000-c253-11eb-9712-0430df3416c5.mp4

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
未重现，请再造个例子

**Comment by kasidier** [comment]
线上404了

![image](https://user-images.githubusercontent.com/7098009/121509033-d1093700-ca18-11eb-8126-843b114c27cd.png)
