### ISSUE TITLE
online 表单开发

### ISSUE THREAD

**Issue by wangzou1995** [zhangdaiscott/jeecg-boot#2616]
##### 版本号：
2.4.3
##### 问题描述：
表同步到数据库 能否同步到自定义的数据库里面，现在默认是同步到jeecg-boot数据库
##### 截图&代码：

![image](https://user-images.githubusercontent.com/42577996/120262567-7bbc7f80-c2cc-11eb-8872-652d336c8aa9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
