### ISSUE TITLE
【菜单权限】

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2617]
##### 问题描述：角色菜单授权和部门的权限控制是什么关系？
比如总共有1,2,3,4,5四个菜单，角色A权限菜单是1,2,3.部门1的权限菜单是1,2,5；部门2的权限菜单是1,3,4.
那一个人被配置了角色A,所属两个部门1和2.
如果这个人登录到部门1 ，会看到哪些菜单？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/120264189-d6a3a600-c2cf-11eb-8067-3c161faa6a96.png)
![image](https://user-images.githubusercontent.com/7098009/120264232-e4592b80-c2cf-11eb-8af0-2293795f9958.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
合集
