### ISSUE TITLE
未找到资源

### ISSUE THREAD

**Issue by ly0518** [zhangdaiscott/jeecg-boot#2623]
##### 版本号：
2.4.3

##### 问题描述：

online表单开发菜单提示【很抱歉，未找到资源】
##### 截图&代码：

![image](https://user-images.githubusercontent.com/11720763/120509766-62feb780-c3fb-11eb-8360-0183c202f839.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己改东西了吧
