### ISSUE TITLE
在线开发功能如何能够配置成模糊查询

### ISSUE THREAD

**Issue by wolfsheep** [zhangdaiscott/jeecg-boot#2624]
##### 版本号：
JeecgBoot2.4.0

##### 问题描述：
在线开发功能如何能够配置成模糊查询，目前创建表之后，自带的查询是全部匹配查询

##### 截图&代码：

![image](https://user-images.githubusercontent.com/14920103/120577611-23fe4f80-c457-11eb-893e-1c05ef977229.png)

![image](https://user-images.githubusercontent.com/14920103/120577712-45f7d200-c457-11eb-9aa9-2d913109e9c3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043941
