### ISSUE TITLE
角色管理，更改了角色的按钮权限，后台的shiro缓存未更新

### ISSUE THREAD

**Issue by 244707133** [zhangdaiscott/jeecg-boot#2627]
##### 问题描述：
角色管理，更改了角色的按钮权限，后台的shiro缓存未更新

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54700030/120602218-676bb480-c47d-11eb-93b3-2b49531cbf48.png)

![image](https://user-images.githubusercontent.com/54700030/120602280-781c2a80-c47d-11eb-8f23-ab97b92de0ca.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？

**Comment by 244707133** [comment]
shiro:cache这个缓存什么情况下更新？

**Comment by 244707133** [comment]
还有我需要更改下shiro cache的命名空间怎么改？authorizationCache后面怎么会多个1呢？

**Comment by 17782798075** [comment]
@zhangdaiscott 这个问题到现在还依然存在，管理员给角色重新分配了权限，缓存并没有及时更新
