### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by wblbird** [zhangdaiscott/jeecg-boot#2629]
##### 问题描述：
删除数据条目的时候，若存在字段是文件图片的，删除操作应该同时删掉对应文件，不然服务器垃圾文件越来越多。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by galaxist** [comment]
这么狂野吗，直接删除图床文件，万一其他地方用到了不是  图裂了 ？

**Comment by wblbird** [comment]
> 这么狂野吗，直接删除图床文件，万一其他地方用到了不是 图裂了 ？

这样看来，确实是需求不一样，功能不一样
