### ISSUE TITLE
动态路由刷新后，页面变空白；

### ISSUE THREAD

**Issue by hzyyy** [zhangdaiscott/jeecg-boot#263]
##### 版本号：
2.0.1

##### 问题描述：
刷新动态路由页面时，页面'加载失败'，页面变空白；但是！其他的动态路由刷新显示正常；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33852158/60639047-71c94200-9e53-11e9-8f62-09f1dc880d42.png)
![image](https://user-images.githubusercontent.com/33852158/60639061-7db50400-9e53-11e9-94c7-6fa395b5cafb.png)

**Comment by hzyyy** [comment]
图片说明：第一张图是通过左侧的菜单能够正常跳转，第二张图是通过左侧的菜单跳转后，刷新当前页面导致问题出现；

**Comment by zhangdaiscott** [comment]
这个页面是自己开发的吧，有什么特殊的地方?
F12看看浏览器报错没有

**Comment by hzyyy** [comment]
没有什么特殊之处，都是一样的。浏览器没有报错；

**Comment by hzyyy** [comment]
通过阅读官方文档，目前已解决，主要是传的id 参数不符合格式官方文档格式，正确的url格式应该是：auto/list/1145510161302011906  。感谢技术人员；
