### ISSUE TITLE
自己创建的填值规则类中用不了redis工具类，注入的值为null

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2630]
##### 版本号：
2.4.3

##### 问题描述：
在service中使用没问题，是不是填值规则类spring创建它时redis工具类还没有被创建？这个能解决么？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55084864/120613887-3db88a80-c489-11eb-88d6-19eff3250078.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这种问题不要提，你的这个coderule都不是在spring容器里面实例化的对象，怎么能这么用

**Comment by tb2888** [comment]
我在类上加了@Component注解也没用！那我要怎么做呢？大佬能指教下么？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 自己创建的填值规则类中用不了redis工具类，注入的值为null (#2630)





 
这种问题不要提，你的这个coderule都不是在spring容器里面实例化的对象，怎么能这么用

**Comment by tb2888** [comment]
加@Service也不行



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 自己创建的填值规则类中用不了redis工具类，注入的值为null (#2630)





 
这种问题不要提，你的这个coderule都不是在spring容器里面实例化的对象，怎么能这么用
