### ISSUE TITLE
2.4.5版本Online在线表单新增（及编辑）界面无法显示组件内容

### ISSUE THREAD

**Issue by suzh76** [zhangdaiscott/jeecg-boot#2631]
##### 版本号：
2.4.5

##### 问题描述：
Online在线表单新增（及编辑）界面无法显示组件内容

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31197280/120732170-72732300-c517-11eb-9765-be0582ebe824.png)

![image](https://user-images.githubusercontent.com/31197280/120732234-874fb680-c517-11eb-9da6-eb840a8a2b1a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
经测试没问题，你是手工升级的？还是跑的最新git版本
![image](https://user-images.githubusercontent.com/3162115/120732725-5b810080-c518-11eb-82e4-14ef98bd1c2f.png)

**Comment by suzh76** [comment]
直接使用最新版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 2.4.5版本Online在线表单新增（及编辑）界面无法显示组件内容 (#2631)





 
经测试没问题，你是手工升级的？还是跑的最新git版本

**Comment by suzh76** [comment]
2.4.3的版本就可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 2.4.5版本Online在线表单新增（及编辑）界面无法显示组件内容 (#2631)





 
经测试没问题，你是手工升级的？还是跑的最新git版本

**Comment by zhangdaiscott** [comment]
1、F12看js是否报错
2、看后台是否报错
3、确认数据库是否最新的

**Comment by suzh76** [comment]
谢谢，我们查一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 2.4.5版本Online在线表单新增（及编辑）界面无法显示组件内容 (#2631)





 
1、F12看js是否报错
 2、看后台是否报错
 3、确认数据库是否最新的

**Comment by suzh76** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 2.4.5版本Online在线表单新增（及编辑）界面无法显示组件内容 (#2631)





 
1、F12看js是否报错
 2、看后台是否报错
 3、确认数据库是否最新的

**Comment by suzh76** [comment]
![Uploading image.png…]()

**Comment by suzh76** [comment]
![image](https://user-images.githubusercontent.com/31197280/120882242-e5a89200-c608-11eb-81e0-a077fbc5c9ee.png)

**Comment by zhangdaiscott** [comment]
其他人无问题，自己确认，有什么特殊的
