### ISSUE TITLE
修改账户名以后，原密码失效

### ISSUE THREAD

**Issue by x522491416** [zhangdaiscott/jeecg-boot#2633]
##### 版本号：
2.4.3

##### 问题描述：
修改账户名以后，原密码失效，导致登陆账号密码错误

passwordUtil 的解密方法存在问题，解密需要的三个参数，一个是密钥，一个是密码，一个是salt, 密码在系统没有存储存的密钥，加密时用的是账户名，导致无法解密。所以在修改账号以后，原密码就会失效
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个操作，请截图

**Comment by x522491416** [comment]
![image](https://user-images.githubusercontent.com/45849273/120793913-138ac980-c56a-11eb-9fcc-40dece683384.png)

**Comment by zhangdaiscott** [comment]
我们不支持修改账号，这是你自己加的逻辑，此类问题请自行修改，不要发issue

**Comment by x522491416** [comment]
![image](https://user-images.githubusercontent.com/45849273/120794523-edb1f480-c56a-11eb-9c32-31cdff0f5aef.png)

**Comment by x522491416** [comment]
懵了

**Comment by x522491416** [comment]
@zhangdaiscott
