### ISSUE TITLE
2..4.5 online-form与文档多出介绍不符

### ISSUE THREAD

**Issue by wan84** [zhangdaiscott/jeecg-boot#2637]
##### 版本号：
2.4.5

##### 问题描述：
online-form这些不是闭源的吗？为什么功能还和文档上的不一致呢？
是不是可以升级一下

## 没有排序字段
![image](https://user-images.githubusercontent.com/4098915/120890958-8793a300-c638-11eb-9e8b-d0e2ca91f2cb.png)
![image](https://user-images.githubusercontent.com/4098915/120890979-a42fdb00-c638-11eb-80bb-742a054a9e1e.png)

## 树形
![image](https://user-images.githubusercontent.com/4098915/120891076-29b38b00-c639-11eb-812d-77e2c58b2b5f.png)
![image](https://user-images.githubusercontent.com/4098915/120891095-39cb6a80-c639-11eb-9b2b-6e62730c1709.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
文档老了，当前功能就是最新的

**Comment by wan84** [comment]
> 文档老了，当前功能就是最新的

有排序功能，还是很有必要的
