### ISSUE TITLE
2.4.5升级后出现后端排序报错

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/jeecg-boot#2639]
##### 版本号：
2.4.5

##### 问题描述：
List页面后端出现创建日期重复排序报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/48822119/120946305-95e3db00-c76e-11eb-8263-759ef4d9a36d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个功能

**Comment by iGuozy** [comment]
就是代码生成器生成出来的页面，打开页面时，后端自带的创建日期排序，重复渲染了两个，导致报错。

**Comment by iGuozy** [comment]
升级前是可以正常打开的，升级后之前生成的页面，打开后端都报这个错。

**Comment by zhangdaiscott** [comment]
描述问题请详细，不然issue会被删除

**Comment by iGuozy** [comment]
![image](https://user-images.githubusercontent.com/48822119/120954280-65f20300-c781-11eb-892e-e24a5f897166.png)
![image](https://user-images.githubusercontent.com/48822119/120954377-a0f43680-c781-11eb-8711-f804d7aef9f7.png)

![image](https://user-images.githubusercontent.com/48822119/120954312-77d3a600-c781-11eb-8ca4-c40620d9d2e3.png)
前端请求数据，创建日期的排序，后端渲染的SQL语句，出现了两次，导致后端报错。

**Comment by zhangdaiscott** [comment]
你的页面是不是自己改了，自己加了多次排序

**Comment by iGuozy** [comment]
页面是有改过，但没加排序，2.4.3的版本没出现这个问题，昨晚升级2.4.5后就出现了。

**Comment by iGuozy** [comment]
![image](https://user-images.githubusercontent.com/48822119/120992214-f6960680-c7b4-11eb-9339-aa089add684b.png)
好像是这个文件升级后的问题，我打印了日志跟踪了一下。发现上图的问题。

**Comment by zhangdaiscott** [comment]
为什么我们的默认代码和例子没问题

**Comment by zhangdaiscott** [comment]
试试
```
if (order.toUpperCase().indexOf(ORDER_TYPE_ASC)>=0) {
				//queryWrapper.orderByAsc(oConvertUtils.camelToUnderline(column));
				String columnStr = oConvertUtils.camelToUnderline(column);
				String[] columnArray = columnStr.split(",");
				queryWrapper.orderByAsc(columnArray);
			} else {
				//queryWrapper.orderByDesc(oConvertUtils.camelToUnderline(column));
				String columnStr = oConvertUtils.camelToUnderline(column);
				String[] columnArray = columnStr.split(",");
				queryWrapper.orderByDesc(columnArray);
			}
```

**Comment by iGuozy** [comment]
这个我下午试过，注释其中一个是可以的。
