### ISSUE TITLE
建议系统字典支持多级联动

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#264]
##### 问题描述：

建议系统字典表sys_dict和sys_dict_item里分别增加parent_code字段,表示父子结构的字典,然后在代码里对JDictSelectTag组件进行扩展,支持级联下拉框,配置父子键的约束,当父change的时候,父对应的子的内容进行清空,当点击子下拉框的时候,获取到父的值然后实时进行查询过滤显示.

**Comment by zhangdaiscott** [comment]
2.0.2版本新增了 分类字典
![image](https://user-images.githubusercontent.com/3162115/60940043-b568f380-a30c-11e9-94e3-4848cc3d427f.png)
