### ISSUE TITLE
online树表单，控件默认值无效

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2641]
##### 版本号：
2.4.3

##### 问题描述：
online树表单，控件默认值无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46367005/120992157-e9791780-c7b4-11eb-984f-d33c430fdff5.png)

![image](https://user-images.githubusercontent.com/46367005/120992224-f8f86080-c7b4-11eb-92e4-8b9312d16ce7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.4.5已解决此问题
