### ISSUE TITLE
把前台页面加入到白名单，访问页面，页面是白页，并且页面的created方法也不触发

### ISSUE THREAD

**Issue by zhusensen** [zhangdaiscott/jeecg-boot#2645]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by sjlei** [comment]
在“菜单管理“里配置的页面，如果要加入到白名单，则需要在 `src/config/router.config.js` 文件里单独配置路由。
因为获取菜单是需要Token的，如果你没有登录就没有Token，没有Token就没有菜单，没有菜单就没有路由，没有路由Vue自然就找不到这个页面，所以你需要手动去文件里配置了路由才能访问到。

![image](https://user-images.githubusercontent.com/34293221/122385821-d0841980-cf9f-11eb-860d-4cf6c7cbd7e5.png)

![image](https://user-images.githubusercontent.com/34293221/122385758-c2ce9400-cf9f-11eb-8425-1510b3cd46f6.png)
