### ISSUE TITLE
从2.4.3更新后online表单开发，js增强使用beforeEdit方法，编辑点击无效，删除beforeEdit即可恢复

### ISSUE THREAD

**Issue by i-Hu** [zhangdaiscott/jeecg-boot#2647]
##### 版本号：
2.4.5

##### 问题描述：
从2.4.3更新后online表单开发，js增强使用beforeEdit方法，编辑点击无效，删除beforeEdit即可恢复

##### 截图&代码：

beforeEdit(row)
{
  if (row.status !== "3"&&row.status !== "5") {
    that.$message.warn('只能处理待收待退状态的信息')
    throw '只能处理待收待退状态的信息'
  }
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本
