### ISSUE TITLE
JSelectUserByDep控件

### ISSUE THREAD

**Issue by 0xCoding** [zhangdaiscott/jeecg-boot#2648]
##### 版本号：
 2.4.2

问题描述：

JSelectUserByDep控件要选择两次才显示在控件中

 截图&代码：
<img width="211" alt="Snipaste_2021-06-10_17-07-19" src="https://user-images.githubusercontent.com/61595017/121498678-38ba8480-ca0f-11eb-97d5-8857e0e75da5.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl
