### ISSUE TITLE
online方式配置数据权限无效

### ISSUE THREAD

**Issue by yxz1025** [zhangdaiscott/jeecg-boot#2649]
##### 版本号：
2.4.3

##### 问题描述：
online方式配置数据权限无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6748654/121511175-f303b900-ca1a-11eb-9e58-214cc226cf70.png)
![image](https://user-images.githubusercontent.com/6748654/121511233-0151d500-ca1b-11eb-9b6c-ba993eb58bb4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
需要给角色赋予数据规则

**Comment by yxz1025** [comment]
> 需要给角色赋予数据规则

![image](https://user-images.githubusercontent.com/6748654/121537849-dffee200-ca36-11eb-893c-0a416db20f0e.png)
我已经配置了 但是不生效

**Comment by xinxingzhao** [comment]
http://doc.jeecg.com/2044045
