### ISSUE TITLE
我的消息后台报错 Parameter 'announcementSendModel' not found. Available parameters are [arg1, arg0, param1, param2]

### ISSUE THREAD

**Issue by xflee09** [zhangdaiscott/jeecg-boot#265]
##### 问题描述：查看我的消息报错
 Parameter 'announcementSendModel' not found. Available parameters are [arg1, arg0, param1, param2]

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35718555/60654546-c59d5080-9e7e-11e9-983d-1659dc0304e7.png)

我是这样解决的：在mapper里面加个参数别名
![image](https://user-images.githubusercontent.com/35718555/60655020-a2bf6c00-9e7f-11e9-9dd3-1071c24ab909.png)

**Comment by zhangdaiscott** [comment]
hao d

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
