### ISSUE TITLE
[报表设计器]x轴名称太长显示不了

### ISSUE THREAD

**Issue by lixiang4543** [zhangdaiscott/jeecg-boot#2652]
##### 版本号：
2.4.5

##### 问题描述：
x轴名称太长显示不了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8317996/121902642-16e83700-cd5a-11eb-8be5-90472c998859.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？

**Comment by lixiang4543** [comment]
右下角 给x轴写的名字太长,展示不全.
![image](https://user-images.githubusercontent.com/8317996/122003573-d7672c80-cde5-11eb-81c6-d6b0643f8a37.png)

**Comment by zhangdaiscott** [comment]
拖的空间大点呢

**Comment by lixiang4543** [comment]
拖动空间和那个字是同步扩大的，也就是说保持这个形状等比缩放，所以放大和缩小都是同样的效果

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/123537077-4c305400-d760-11eb-875b-aace2f73021e.png)

**Comment by lixiang4543** [comment]
http://boot.jeecg.com:8080/jeecg-boot/jmreport/view/570094028250763264
这是在你们平台上配置的一个案例，右边距已经到最大了，还是没显示全，这个图表比较常见的是x轴名称和在x轴下方显示，这样很多种情况都能兼容。

**Comment by zhanghaifei1997** [comment]
![image](https://user-images.githubusercontent.com/57278786/134305570-4cfaea2a-cfbc-41b5-b230-204611325613.png)
这种情况怎么办呀，我想把x轴刻度固定在10个左右，省略一部分，但是设置了v-axis的一些属性都没有效果
