### ISSUE TITLE
jeecg-boot验证码问题

### ISSUE THREAD

**Issue by cai-04** [zhangdaiscott/jeecg-boot#2655]
##### 版本号：
2.4.5

##### 问题描述：
验证码404

##### 截图&代码：
![屏幕截图 2021-06-15 213549](https://user-images.githubusercontent.com/85945709/122064499-c89f6a80-ce23-11eb-9ab1-bf0b7519cbe9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
1、确定后端服务是不是运行了
2、浏览器F12看看，验证码请求的URL地址对不对
