### ISSUE TITLE
postgresql 模式问题

### ISSUE THREAD

**Issue by wang1597538789** [zhangdaiscott/jeecg-boot#2656]
##### 版本号：
v2.4.5

##### 问题描述：
online代码生成导入数据库表功能无法读取postgresql 其他模式的表 只能读取public模式下的表

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32223833/122141573-35485280-ce80-11eb-9fc3-e668d381c85c.png)
已经设置默认模式、且jdbc连接字符串后面也加了?currentSchema=test&stringtype=unspecified
可是online导入数据库表无法读取test模式下的表

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 待测试 sq

**Comment by zhangdaiscott** [comment]
代码生成器依赖升级到
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.3.4</version>
</dependency>
```

配置文件jeecg/jeecg_database.properties增加属性
```
#PostgreSQL模式，多个逗号分隔
schemaName=public,test
```
