### ISSUE TITLE
找不到jeecg-boot-module-demo 2.4.5

### ISSUE THREAD

**Issue by sh3300** [zhangdaiscott/jeecg-boot#2657]
##### 问题描述：
Failure to find org.jeecgframework.boot:jeecg-boot-module-demo:pom:2.4.5 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced
打包的时候报这个错误 找不到2.4.5的包

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11268717/122157850-2d97a680-ce9e-11eb-8627-71dff610659c.png)

**Comment by xinxingzhao** [comment]
在本地的Maven把demo模板install一下就行

**Comment by sh3300** [comment]
> 在本地的Maven把demo模板install一下就行

我install还是报同样的错误哦

**Comment by xinxingzhao** [comment]
> > 在本地的Maven把demo模板install一下就行
> 
> 我install还是报同样的错误哦

你需要把每个子模块都install一下
