### ISSUE TITLE
在线开发生成的代码字典无效

### ISSUE THREAD

**Issue by zhubinsheng** [zhangdaiscott/jeecg-boot#2659]
##### 版本号：
2.4.3（发布日期：20210508）
##### 问题描述：
在线开发配置好字典等功能，在线测试正常。导出代码在本地运行，列表不显示字典项，无报错。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
字典项要重新登录之后才会生效

**Comment by zhubinsheng** [comment]
> 字典项要重新登录之后才会生效
重新登录 清除缓存后也无益
下图一不显示 下图二是在线测试是显示的

![微信截图_20210616143606](https://user-images.githubusercontent.com/44765143/122169727-4d37ca80-ceb0-11eb-8fc6-5f238d723cc6.png)
![微信截图_20210616143640](https://user-images.githubusercontent.com/44765143/122169782-604a9a80-ceb0-11eb-8f8b-d05504511cca.png)

**Comment by zhangdaiscott** [comment]
代码都生成了，自己看下代码，debug不比问快

**Comment by zhubinsheng** [comment]
自动生成的代码无改动，打印看到 dictCode是获取到的，代码如下：
` getSuperFieldList(){
        let fieldList=[];
        fieldList.push({type:'string',value:'regionName',text:'区域代号',dictCode:''})
        fieldList.push({type:'pca',value:'regionPlace',text:'区域（x市x区）'})
        fieldList.push({type:'list_multi',value:'facilities',text:'外部设施，关联sys_dict_item.id,以逗号格式隔开',dictTable:'', dictText:'', dictCode:'facilities'})
        fieldList.push({type:'string',value:'regionWay',text:'地址（x路x号）',dictCode:''})
        fieldList.push({type:'int',value:'regionStatus',text:'状态',dictCode:'awinic_status'})
        fieldList.push({type:'string',value:'note',text:'备注',dictCode:''})
        fieldList.push({type:'int',value:'hotwaterPrice',text:'热水费',dictCode:''})
        fieldList.push({type:'int',value:'electricityPrice',text:'电费',dictCode:''})
        fieldList.push({type:'int',value:'coldwaterPrice',text:'凉水费',dictCode:''})
        this.superFieldList = fieldList
      }`


`columns: [
          {
            title: '#',
            dataIndex: '',
            key:'rowIndex',
            width:60,
            align:"center",
            customRender:function (t,r,index) {
              return parseInt(index)+1;
            }
          },
          {
            title:'区域代号',
            align:"center",
            dataIndex: 'regionName'
          },
          {
            title:'区域（x市x区）',
            align:"center",
            dataIndex: 'regionPlace',
            scopedSlots: {customRender: 'pcaSlot'}
          },
          {
            title:'外部设施，关联sys_dict_item.id,以逗号格式隔开',
            align:"center",
            dataIndex: 'facilities_dictText'
          },
          {
            title:'地址（x路x号）',
            align:"center",
            dataIndex: 'regionWay'
          },
          {
            title:'状态',
            align:"center",
            dataIndex: 'regionStatus_dictText'
          },`

**Comment by zhubinsheng** [comment]
> 代码都生成了，自己看下代码，debug不比问快

真不知道在哪debug，学识尚浅，不知道问题可能出现在哪

**Comment by zhubinsheng** [comment]
但是编辑和新建的表单中都是有的
![微信截图_20210616144555](https://user-images.githubusercontent.com/44765143/122170807-93415e00-ceb1-11eb-873f-4e5fd0d5d548.png)

**Comment by xinxingzhao** [comment]
字典的问题很好解决，在认真查一下，直接改代码也能解决

**Comment by tb2888** [comment]
解决了么？我的也是一样！前端的VUE不怎么懂

**Comment by HatcherZhao** [comment]
> 解决了么？我的也是一样！前端的VUE不怎么懂

找到了，不知道为什么在线生成的实体类属性上没加@Dict，加上列表就好了
