### ISSUE TITLE
j-search-select-tag 封装的loadDict、loadDictItem在后台代码中不存在

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#266]
##### 问题描述：
下拉搜索异步请求后台代码，后台接口不存在；
虽然调用 /sys/dict/getDictItems  微调下这接口能实现效果，但还是上报一下

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/50865430/60702840-98aa7580-9f32-11e9-9702-f1a3bc91fba8.png)
![图片](https://user-images.githubusercontent.com/50865430/60702933-df986b00-9f32-11e9-9762-cec181cf837e.png)
![图片](https://user-images.githubusercontent.com/50865430/60702943-ec1cc380-9f32-11e9-9600-522dab1642f2.png)

**Comment by zhangdaiscott** [comment]
最新版已经发布，请更新
