### ISSUE TITLE
积木报表的主子表在主表没有数据的情况下页面会出错

### ISSUE THREAD

**Issue by xiaoyizeng** [zhangdaiscott/jeecg-boot#2660]
##### 版本号：
jeecgboot 2.4.5

##### 问题描述：
在2.4.5版本的jeecgboot中，积木报表设计这块，关于主子表发现有些问题。
例如要实现这样子的功能：主表是某个部门在某个月的请假汇总，子表是请假的人员详情。主子表参数关联为部门编号跟月份。
如果主表查询的数据结果为空，那么就会报错，java.lang.IndexOutOfBoundsException: Index: 0, Size: 0。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/81517044/122177469-3ac18f00-ceb8-11eb-931e-b7c69d74364a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你如何配置的，数据源怎么用的，详细写一下

**Comment by xiaoyizeng** [comment]
1、以下是表格的数据

2、这个是设计的报表


3、这个是主子表的参数设置


4、这个是汇总的数据
SQL:select att_date,att_depart,count(1)as num from test_attendance group by att_date,att_depart

5、这个是表格的明细
SQL:select * from test_attendance where att_date=${att_date}



6、主表有数据的情况下，页面时正常的

7、主表没有查到数据的时候，就报错了
数据是用了一个日期，但是这个部门并没有这个人员请假的情况。






以上就是我的整个操作流程，这个应该跟数据源没有太大关系，我直接用的mysql也是这样子，其他的数据库也是一样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 积木报表的主子表在主表没有数据的情况下页面会出错 (#2660)





 
你如何配置的，数据源怎么用的，详细写一下

**Comment by xiaoyizeng** [comment]
1、以下是表格的数据
![image](https://user-images.githubusercontent.com/81517044/122193505-20db7880-cec7-11eb-91f3-0243c0bd0ba6.png)
2、这个是设计的报表
![image](https://user-images.githubusercontent.com/81517044/122193552-2a64e080-cec7-11eb-802a-d576034a83b6.png)
3、这个是主子表的参数设置
![image](https://user-images.githubusercontent.com/81517044/122192969-b4f91000-cec6-11eb-8441-f8ee5970413c.png)
4、这个是汇总的数据
SQL:select att_date,att_depart,count(1)as num from test_attendance group by att_date,att_depart
![image](https://user-images.githubusercontent.com/81517044/122193018-bcb8b480-cec6-11eb-9bba-f0ab2cc4a83d.png)
5、这个是表格的明细
SQL:select * from test_attendance where att_date=${att_date}
![image](https://user-images.githubusercontent.com/81517044/122193052-c215ff00-cec6-11eb-8079-79de367fc62e.png)
6、主表有数据的情况下，页面时正常的
![image](https://user-images.githubusercontent.com/81517044/122193092-c8a47680-cec6-11eb-98de-672c34ec98f4.png)
7、主表没有查到数据的时候，就报错了
数据是用了一个日期，但是这个部门并没有这个人员请假的情况。
![image](https://user-images.githubusercontent.com/81517044/122193131-cfcb8480-cec6-11eb-9653-388f67d68d03.png)
![image](https://user-images.githubusercontent.com/81517044/122193138-d3f7a200-cec6-11eb-8b07-5d5cd9a65780.png)


以上就是我的整个操作流程，这个应该跟数据源没有太大关系，我直接用的mysql也是这样子，其他的数据库也是一样的。

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by zhangdaiscott** [comment]
引用这个版本试试
http://jimureport.com/doc/log
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.51-beta</version>
</dependency>
```
