### ISSUE TITLE
shiro的@RequiresPermissions注解不生效

### ISSUE THREAD

**Issue by lyugit** [zhangdaiscott/jeecg-boot#2661]
##### 版本号：
2.4.3

##### 问题描述：
shiro的@RequiresPermissions注解不生效，菜单的按钮配置了权限标识，然后给角色分配了这个按钮的权限，后台代码里接口也配置了注解。
结果：访问接口的时候， 还是没有权限。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25010179/122319447-38f8d980-cf53-11eb-8651-a38e5d888287.png)
![image](https://user-images.githubusercontent.com/25010179/122319495-46ae5f00-cf53-11eb-8549-e647b5363244.png)
![image](https://user-images.githubusercontent.com/25010179/122319606-66458780-cf53-11eb-8d2f-22196cd31a3d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
退出重新登录了？

**Comment by lyugit** [comment]
> 退出重新登录了？
  刚重新登录了，就可以了，， 为啥呀？

**Comment by xinxingzhao** [comment]
> > 退出重新登录了？
> > 刚重新登录了，就可以了，， 为啥呀？

有些数据是登录的时候预加载的
