### ISSUE TITLE
2.4.5，online 文件控件上传带汉字文件报错

### ISSUE THREAD

**Issue by 793292556** [zhangdaiscott/jeecg-boot#2667]
##### 问题描述：

online 文件控件上传带汉字文件报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/66394184/122355932-e6381580-cf84-11eb-88d3-6f33fe301682.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhubinsheng** [comment]
这个问题好改，只是对filename的校验，讲校验去掉或者转义就行

**Comment by zhangdaiscott** [comment]
确定桶的配置正确吗

**Comment by zhangdaiscott** [comment]
收录  测试验证  sq

**Comment by lsqGitHub716** [comment]
你配置的是阿里、还是minio上传？

**Comment by lsqGitHub716** [comment]
经测试，未发现问题
