### ISSUE TITLE
自动生成代码没有添加过滤条件

### ISSUE THREAD

**Issue by zhubinsheng** [zhangdaiscott/jeecg-boot#2668]
##### 版本号：
 2.4.3

##### 问题描述：
自动生成代码没有包含以下功能：
当从数据库表获取字典数据的时候支持写查询条件进行过滤数据

##### 截图&代码：
如下，生成的代码仅查询无检索，这个在自动生成的时候难以加入吗？
`dictCode="region,region_name,region_name "`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
没看懂你的问题，你能截图描述一下吗？

**Comment by zhangdaiscott** [comment]
可以
