### ISSUE TITLE
【报表设计器】怎么使用数值三位分节？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2669]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/122510787-c3ffcf80-d038-11eb-95e1-cc406662d2f3.png)

![image](https://user-images.githubusercontent.com/7098009/122510753-afbbd280-d038-11eb-9de8-b47c39218757.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
你可以通过SQL语句，或者使用API在后台把数据转化好了再返回给报表

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 https://github.com/jeecgboot/JimuReport/issues/138
