### ISSUE TITLE
系统ID的规则疑问

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#267]
##### 版本号：
2.0.2

##### 问题描述：
日志中写道。示例demo主键改成ID_WORKER_STR，后续系统ID规则全部切换为ID_WORKER_STR。目前是有什么业务不支持UUID，导致需要做这样的更改？

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
没有不只支持
