### ISSUE TITLE
微服务2.4.3，接入的rabbitmq，如何确认消息发送成功，和消费成功

### ISSUE THREAD

**Issue by zhusensen** [zhangdaiscott/jeecg-boot#2670]
##### 截图&代码：微服务2.4.3，接入的rabbitmq，如何确认消息发送成功，和消费成功

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看文档和视频

**Comment by zhusensen** [comment]
您好 方便给个资料连接么？我在官网找到的资料只有发送和接收没有 确认结果的介绍。麻烦拉！
















在 2021-06-18 15:23:30，"JEECG开源社区" ***@***.***> 写道：

看文档和视频
