### ISSUE TITLE
online表单数据源配置，数据库类型识别错误

### ISSUE THREAD

**Issue by tuikoushui** [zhangdaiscott/jeecg-boot#2671]
##### 问题描述：
1、数据库类型识别错误：
org.jeecg.config.init.CodeGenerateDbConfig虽然使用的是application.yml的DB配置，但是org.jeecgframework.codegenerate.a.a里却还是使用的jeecg_database.properties里的url来判断数据库类型（图一），导致org.jeecgframework.codegenerate.database.DbReadTableUtil查询数据库所有table时使用的sql与数据库类型不匹配（图二）导致报错。

复现步骤：

1. application.yml里使用oracle数据源
2. jeecg_database.properties使用mysql数据源
3. 在线开发》online表单开发》导入数据库表，即报错 

##### 截图&代码：
图一
![image](https://user-images.githubusercontent.com/46367005/122523509-ac7d1280-d049-11eb-849e-1daf9a48cefe.png)
图二
![image](https://user-images.githubusercontent.com/46367005/122523958-2b724b00-d04a-11eb-88cc-e2325a73fa92.png)

**Comment by zhangdaiscott** [comment]
已解决，升级依赖到这个版本，记得刷新maven
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.3.3</version>
</dependency>
```

**Comment by tuikoushui** [comment]
> 已解决，升级依赖到这个版本，记得刷新maven
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot</groupId>
>   <artifactId>codegenerate</artifactId>
>   <version>1.3.3</version>
> </dependency>
> ```

升级依赖后已解决，谢谢
