### ISSUE TITLE
can not find source of hibernate-re

### ISSUE THREAD

**Issue by BruceKangCN** [zhangdaiscott/jeecg-boot#2673]
##### 版本号：

`2.4.3`

##### 问题描述：

Where is the source code of `org.jeecgframework.boot:hibernate-re`?
I see it is under Apache 2.0 license, and I want to download and costomize it

**Comment by zhangdaiscott** [comment]
不开放

**Comment by BruceKangCN** [comment]
> 不开放

so why do you publish it under Apache 2.0?
if it is published under Apache 2.0, everyone should be able to obtain the source code

![maven_repo](https://user-images.githubusercontent.com/43891241/122549972-ad23a200-d065-11eb-88a4-398de1b284ff.jpg)

**Comment by ygl-rg** [comment]
remove the license if you don't want to share.
