### ISSUE TITLE
Online 报表配置中，报表SQL语句是多行的时候没法全选SQL语句

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/jeecg-boot#2674]
##### 版本号：
2.4.5

##### 问题描述：
Online 报表配置中，报表SQL语句是多行的时候没法全选SQL语句

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/122636161-53c97a80-d11a-11eb-89b4-451caa963f66.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复
