### ISSUE TITLE
popup弹出窗多选问题如何实现回调拆分及不同数据库表的字典内容翻译转换

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#2676]
##### 问题描述：

如何实现popup弹出窗返回多行记录，如我选了两行记录，回调的时候值还是显示在同一行，不会自动拆分成多行记录。

另外请教下表单及列表中如何实现不同数据库的字典翻译，如表单中编码001对应的是取ms sqlserve数据库中的一张表中的商品名称，如何能显示出来这个商品名称，不是在同一个数据库中的。

##### 截图&代码：
![1](https://user-images.githubusercontent.com/54636793/122665622-dade2780-d1da-11eb-97c5-91ce2eb32c97.jpg)

**Comment by zhangdaiscott** [comment]
不支持
