### ISSUE TITLE
导出功能

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#268]
##### 版本号：
2.0.2

##### 问题描述：
导出参数没有传入controller

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3365218/60714012-bd134b80-9f4c-11e9-9ca2-0b7a7cf3ab5a.png)

```
export function downFile(url,paramsStr){
  console.log('parameter', paramsStr)
  return axios({
    url: `${url}?paramsStr=${paramsStr}`,
    method:'get' ,
    responseType: 'blob'
  }
```

**Comment by galaxist** [comment]
```
src\mixins\JeecgListMixin.js
```
```
    handleExportXls(fileName){
      if(!fileName || typeof fileName != "string"){
        fileName = "导出文件"
      }
      
      const paramsStr =  encodeURI(JSON.stringify(this.getQueryParams()));
      if(this.selectedRowKeys && this.selectedRowKeys.length>0){
        paramsStr['selections'] = this.selectedRowKeys.join(",")
      }
      downFile(this.url.exportXlsUrl, paramsStr).then((data)=>{
        if (!data) {
          this.$message.warning("文件下载失败")
          return
        }
        if (typeof window.navigator.msSaveBlob !== 'undefined') {
          window.navigator.msSaveBlob(new Blob([data]), fileName+'.xls')
        }else{
          let url = window.URL.createObjectURL(new Blob([data]))
          let link = document.createElement('a')
          link.style.display = 'none'
          link.href = url
          link.setAttribute('download', fileName+'.xls')
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link); //下载完成移除元素
          window.URL.revokeObjectURL(url); //释放掉blob对象
        }
      })
    },
```

**Comment by lanfen100** [comment]
确实 controller 中           `String paramsStr = request.getParameter("paramsStr"); `  接收到的是  NULL

**Comment by lanfen100** [comment]
> ```
> src\mixins\JeecgListMixin.js
> ```
> 
> ```
>     handleExportXls(fileName){
>       if(!fileName || typeof fileName != "string"){
>         fileName = "导出文件"
>       }
>       
>       const paramsStr =  encodeURI(JSON.stringify(this.getQueryParams()));
>       if(this.selectedRowKeys && this.selectedRowKeys.length>0){
>         paramsStr['selections'] = this.selectedRowKeys.join(",")
>       }
>       downFile(this.url.exportXlsUrl, paramsStr).then((data)=>{
>         if (!data) {
>           this.$message.warning("文件下载失败")
>           return
>         }
>         if (typeof window.navigator.msSaveBlob !== 'undefined') {
>           window.navigator.msSaveBlob(new Blob([data]), fileName+'.xls')
>         }else{
>           let url = window.URL.createObjectURL(new Blob([data]))
>           let link = document.createElement('a')
>           link.style.display = 'none'
>           link.href = url
>           link.setAttribute('download', fileName+'.xls')
>           document.body.appendChild(link)
>           link.click()
>           document.body.removeChild(link); //下载完成移除元素
>           window.URL.revokeObjectURL(url); //释放掉blob对象
>         }
>       })
>     },
> ```
可以先加上 Order order 方法中参数的方式先处理，能接收到
exportXls(Order order,HttpServletRequest request, HttpServletResponse response)

**Comment by zhangdaiscott** [comment]
线上代码支持根据查询条件帅选数据导出啊，你这个改法只是增加选中状态了吧

**Comment by lanfen100** [comment]
> 改法只是增加选中状态了
![image](https://user-images.githubusercontent.com/12097469/62292307-b965dc80-b498-11e9-99e2-e007c9804f9f.png)

![image](https://user-images.githubusercontent.com/12097469/62292359-d4385100-b498-11e9-934c-15148d8f2503.png)


嗯，那就是代码生成的时候contoller 模版不对，接收参数的形式跟demo代码里不一样

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/63660347-99e87800-c7e8-11e9-97fc-80b4a4313d6f.png)
这个代码和你本地的代码不一样？

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
