### ISSUE TITLE
online表单中主从表权限相互影响

### ISSUE THREAD

**Issue by zhangdaiscott** [zhangdaiscott/jeecg-boot#2680]
- 版本号：2.4.0

- 问题描述：
    两个ERP样式的主从表，授权不同，第一个全部权限，第二个部分权限。先点第一功能模块，权限正常，可以显示，但点第二个功能模块后，权限是减少了的权限，但再点第一个模块时，其部分按钮和第二个一样被屏蔽了.

- 截图&代码：

![image](https://user-images.githubusercontent.com/3162115/122735750-e9e3d900-d2b1-11eb-9d92-eccdb036a236.png)
![image](https://user-images.githubusercontent.com/3162115/122735782-f0725080-d2b1-11eb-84b0-bcbb2e7c4042.png)
![image](https://user-images.githubusercontent.com/3162115/122735821-f8ca8b80-d2b1-11eb-98f5-0f944ab16b3e.png)
![image](https://user-images.githubusercontent.com/3162115/122735844-fbc57c00-d2b1-11eb-89ec-1ff60ea93d73.png)
![image](https://user-images.githubusercontent.com/3162115/122735867-ff590300-d2b1-11eb-8b32-ddfca7a06043.png)

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已经修复，见下版本

**Comment by zhangdaiscott** [comment]
手工修改方法
src/views/modules/online/cgform/auto/erp/OnlineCommonList.vue
src/views/modules/online/cgform/auto/OnlCgformTreeList.vue

```
     initButtonSwitch(hideColumns){
        if(hideColumns && hideColumns.length>0){
          Object.keys(this.buttonSwitch).forEach(key=>{
            if(hideColumns.indexOf(key)>=0){
              this.buttonSwitch[key]=false
            }else{
              this.buttonSwitch[key] = true
            }
          })

        }
      },
```
![image](https://user-images.githubusercontent.com/3162115/123886789-ccce9a80-d982-11eb-9518-d5bf8c079294.png)

**Comment by xngyun** [comment]
收到，谢谢！

**Comment by xngyun** [comment]
按回复增加了代码，但权限问题还在，现象依旧 @zhangdaiscott

**Comment by xngyun** [comment]
![微信图片_20210701165721](https://user-images.githubusercontent.com/35642595/124096723-6edaa980-da8d-11eb-8bb8-8df87cb9818c.jpg)
