### ISSUE TITLE
JVXETable 默认新增行数无效，默认新增一行如何获取该行的ID

### ISSUE THREAD

**Issue by missKomorebi** [zhangdaiscott/jeecg-boot#2681]
##### 版本号：
2.4.5

##### 问题描述：
目的描述：
        需要通过接口传值，设置某一列的默认值defaultValue
过程
1. create 调用接口获取值后，设置columns[i].defaultValue 值，搞不定绑定有问题（有个issues也提到动态调整columns）失败了
2.通过点击新增按钮添加行，通过api，this.$refs.xtable.setValue  设值，
   默认插入一行，this.addDefaultRowNum 该参数无效，获取当前table所有数据都length为0
  所以重写add的方法，去除插入默认行数，才达到效果

问题：
       1.有什么其他办法动态设置defaultValue值
       2. 默认添加行数失效如何处理

##### 截图&代码：

![1](https://user-images.githubusercontent.com/49051538/122855190-6f659880-d347-11eb-88fc-9afa1e721d7a.png)
`addAfter(value){
        console.log(value);
        console.log(this.$refs.nspExposedDetails.getTableData());
        console.log(this.$refs.nspExposedDetails.getAll())  ;
      },`
![2](https://user-images.githubusercontent.com/49051538/122855189-6f659880-d347-11eb-8d22-67f105d02359.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by missKomorebi** [comment]
1

**Comment by Benjamin-536** [comment]
老哥这个问题有没有解决，若解决的话，能不能说一下解法过程。。。

**Comment by weiqiLee** [comment]
我也碰到这个问题了,想设置子表为0,结果默认还是出现了一行
