### ISSUE TITLE
minio升级到8.0.3上传失败

### ISSUE THREAD

**Issue by yuxiujuan** [zhangdaiscott/jeecg-boot#2686]
版本号：2.4.0

问题描述：
minio升级到8.0.3，在开发上运行文件上传没问题，运行到生产报错    
{"success":false,"message":"操作失败，Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/multipart/support/StandardMultipartHttpServletRequest","code":500,"result":null,"timestamp":1624428877374}

截图&代码：
![image](https://user-images.githubusercontent.com/8705490/123045696-c9408e00-d42d-11eb-9752-ae3523029f80.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考最新版，已经升了

**Comment by yuxiujuan** [comment]
> 参考最新版，已经升了

您好，我用的2.4.0版本，目前不想做升级，我更新了MinioUtil代码，设置minio 版本8.0.3，请问这个操作失败的问题怎么解决？而且为啥本地上传图片能成功呢
