### ISSUE TITLE
请教高级查询

### ISSUE THREAD

**Issue by missKomorebi** [zhangdaiscott/jeecg-boot#2687]
##### 版本号：
2.4.5

##### 问题描述：
在线开发可以使用子表字段高级查询，利用代码生成后只能使用主表字段查询

文档中没用提到如何改造，请教请教，实在没看懂如何拼接的

##### 截图&代码：

![1](https://user-images.githubusercontent.com/49051538/123059920-d5801780-d43c-11eb-855b-37cf0e66ba25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by guohaichen** [comment]
![image](https://user-images.githubusercontent.com/38747644/123195293-84befc00-d4da-11eb-8304-48bee0f89d15.png)
前端list页面，将主表的fieldList改造成子表的字段就可以了。
