### ISSUE TITLE
建议：Online开发校验字段Tab页中，字段字典Code和字典Text加上放大编辑按钮

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/jeecg-boot#2690]
##### 版本号：
v2.4.5

##### 问题描述：
建议：Online开发校验字段Tab页中，字段字典Code和字典Text加上放大编辑按钮

因为在字段为Popup弹窗的时候，需要回写的字段比较多，这样编辑起来会方便很多，和字典Table的效果一样

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/123181222-74e5ee80-d4bf-11eb-97fc-b4656cdd8ce9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没必要
