### ISSUE TITLE
用户管理编辑，不做修改无法提交，表单提示库中已存在数据，逻辑就是这样的吗

### ISSUE THREAD

**Issue by Mlxa0324** [zhangdaiscott/jeecg-boot#2695]
##### 版本号：
v1.0.0

##### 问题描述：
用户管理编辑，不做修改无法提交，表单提示库中已存在数据，逻辑就是这样的吗

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
唯一判断有一个专门的接口/jeecg-boot/sys/duplicate/check，，判断时机是输入框的值发生变化，所以你没有修改输入框的内容就不会判断值的存在与否，所以正常没有修改值是可以提交的，刚才实验了一下也确实提交了，然后你可以看看代码，用户修改接口是可以提交的

**Comment by Mlxa0324** [comment]
我这块是没办法提交的，不知道是不是谷歌浏览器自动填充的原因。

**Comment by Mlxa0324** [comment]
系统表名被我改了，所以是自己制造的BUG，不好意思哈
