### ISSUE TITLE
生成视图后不能配置外键么？主附表需要配置视图这种情况比较多呀！

### ISSUE THREAD

**Issue by tb2888** [zhangdaiscott/jeecg-boot#2697]
##### 版本号：

2.4.5
##### 问题描述：
附表不能配置外键么？主附表需要配置视图这种情况比较多呀！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55084864/123353303-cd86bb80-d593-11eb-8c44-a01b083bbb18.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
