### ISSUE TITLE
redis集群问题

### ISSUE THREAD

**Issue by a736730489** [zhangdaiscott/jeecg-boot#2698]
##### 版本号：
2.4.3

##### 问题描述：
redis集群配置后，报NOAUTH Authentication required，可能原开发时的集群没有密码，所以导致此bug

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28732971/123391936-1c9e1200-d5cf-11eb-9510-97d824d6911b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by zhangdaiscott** [comment]
最新版本已经改了参考代码

```
@Bean
    public IRedisManager redisManager() {
        log.info("===============(2)创建RedisManager,连接Redis..");
        IRedisManager manager;
        // redis 单机支持，在集群为空，或者集群无机器时候使用 add by jzyadmin@163.com
        if (lettuceConnectionFactory.getClusterConfiguration() == null || lettuceConnectionFactory.getClusterConfiguration().getClusterNodes().isEmpty()) {
            RedisManager redisManager = new RedisManager();
            redisManager.setHost(lettuceConnectionFactory.getHostName());
            redisManager.setPort(lettuceConnectionFactory.getPort());
            redisManager.setDatabase(lettuceConnectionFactory.getDatabase());
            redisManager.setTimeout(0);
            if (!StringUtils.isEmpty(lettuceConnectionFactory.getPassword())) {
                redisManager.setPassword(lettuceConnectionFactory.getPassword());
            }
            manager = redisManager;
        }else{
            // redis集群支持，优先使用集群配置
            RedisClusterManager redisManager = new RedisClusterManager();
            Set<HostAndPort> portSet = new HashSet<>();
            lettuceConnectionFactory.getClusterConfiguration().getClusterNodes().forEach(node -> portSet.add(new HostAndPort(node.getHost() , node.getPort())));
            //update-begin--Author:scott Date:20210531 for：修改集群模式下未设置redis密码的bug issues/I3QNIC
            if (oConvertUtils.isNotEmpty(lettuceConnectionFactory.getPassword())) {
                JedisCluster jedisCluster = new JedisCluster(portSet, 2000, 2000, 5,
                    lettuceConnectionFactory.getPassword(), new GenericObjectPoolConfig());
                redisManager.setPassword(lettuceConnectionFactory.getPassword());
                redisManager.setJedisCluster(jedisCluster);
            } else {
                JedisCluster jedisCluster = new JedisCluster(portSet);
                redisManager.setJedisCluster(jedisCluster);
            }
            //update-end--Author:scott Date:20210531 for：修改集群模式下未设置redis密码的bug issues/I3QNIC
            manager = redisManager;
        }
        return manager;
    }
```

**Comment by a736730489** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月29日(星期二) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] redis集群问题 (#2698)





 
最新版本已经改了参考代码
 @Bean     public IRedisManager redisManager() {         log.info("===============(2)创建RedisManager,连接Redis..");         IRedisManager manager;         // redis 单机支持，在集群为空，或者集群无机器时候使用 add by ***@***.***         if (lettuceConnectionFactory.getClusterConfiguration() == null || lettuceConnectionFactory.getClusterConfiguration().getClusterNodes().isEmpty()) {             RedisManager redisManager = new RedisManager();             redisManager.setHost(lettuceConnectionFactory.getHostName());             redisManager.setPort(lettuceConnectionFactory.getPort());             redisManager.setDatabase(lettuceConnectionFactory.getDatabase());             redisManager.setTimeout(0);             if (!StringUtils.isEmpty(lettuceConnectionFactory.getPassword())) {                 redisManager.setPassword(lettuceConnectionFactory.getPassword());             }             manager = redisManager;         }else{             // redis集群支持，优先使用集群配置             RedisClusterManager redisManager = new RedisClusterManager();             Set<HostAndPort&gt; portSet = new HashSet<&gt;();             lettuceConnectionFactory.getClusterConfiguration().getClusterNodes().forEach(node -&gt; portSet.add(new HostAndPort(node.getHost() , node.getPort())));             //update-begin--Author:scott Date:20210531 for：修改集群模式下未设置redis密码的bug issues/I3QNIC             if (oConvertUtils.isNotEmpty(lettuceConnectionFactory.getPassword())) {                 JedisCluster jedisCluster = new JedisCluster(portSet, 2000, 2000, 5,                     lettuceConnectionFactory.getPassword(), new GenericObjectPoolConfig());                 redisManager.setPassword(lettuceConnectionFactory.getPassword());                 redisManager.setJedisCluster(jedisCluster);             } else {                 JedisCluster jedisCluster = new JedisCluster(portSet);                 redisManager.setJedisCluster(jedisCluster);             }             //update-end--Author:scott Date:20210531 for：修改集群模式下未设置redis密码的bug issues/I3QNIC             manager = redisManager;         }         return manager;     }
