### ISSUE TITLE
login密码未处理

### ISSUE THREAD

**Issue by Hugh126** [zhangdaiscott/jeecg-boot#270]
##### 版本号：
V2.0.2

##### 问题描述：
登陆用户名密码居然是没有处理的。。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13162682/60763081-8bf76000-a09f-11e9-938a-5cc7c142b06c.png)

**Comment by zhangdaiscott** [comment]
你确定你是最新版本?

**Comment by Hugh126** [comment]
> 你确定你是最新版本?

sorry，我前两天刚clone就以为是最新版本了。 我再更新下，谢谢！
  <version>2.0.1</version>
