### ISSUE TITLE
【报表设计器】如何给下钻链接做条件判断

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2701]
##### 问题描述：
我想根据数据不同值进行不同的链接跳转， 比如以数据money为例，我想 money<501跳转到"支出报表"，money>500跳转到“收入报表”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/123395004-4d337b00-d5d2-11eb-8ab0-deb8f69f51f2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持

**Comment by zhangdaiscott** [comment]
暂不支持功能归集  https://github.com/jeecgboot/JimuReport/issues/138
