### ISSUE TITLE
【报表设计器】添加了链接后字体无法改变颜色

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2702]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/123395786-2c1f5a00-d5d3-11eb-9a83-eae1941ef270.png)
![image](https://user-images.githubusercontent.com/7098009/123395932-52dd9080-d5d3-11eb-8847-db45864ceafb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到最新版本看看
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.51-beta</version>
</dependency>
```
http://jimureport.com/doc/log
