### ISSUE TITLE
【online报表设计】报表参数有什么意义？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2703]
##### 问题描述：

在报表设计里的报表参数有什么用？没在说明中找到
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/123505004-3a32b080-d68f-11eb-85e4-943b782e372c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
http://doc.jeecg.com/2044153

这个文档里面有说明
