### ISSUE TITLE
列表页的表格有时候边框线显示不全

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/jeecg-boot#2704]
##### 版本号：
v2.4.5

##### 问题描述：
列表页的表格有时候边框显示不全，放大缩小页面又会回复正常

另外，建议表格加上斑马线（这里应该可以通过修改生成代码的模板实现），这样视觉效果会好很多

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/123506289-fbecbf80-d695-11eb-8fbc-e20bf44508fd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
请描述一下你的操作步骤

**Comment by xinxingzhao** [comment]
> 请描述一下你的操作步骤

刚才又试了一下，无法重现，偶发现象。
