### ISSUE TITLE
【online表单】如何在数据权限里加嵌套关系

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2705]
##### 问题描述：

怎么能在表单的数据规则里使用嵌套查询？
比如每个用户加一个属性（是否学生），
则在课程报表中，如果是学生显示学校类课程，如果不是则显示社会课程
怎么进行设置？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/123517814-a6380780-d6d5-11eb-90c4-5cd696184e32.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
数据权限支持自定义sql
