### ISSUE TITLE
【online报表】怎么在报表中打开某表单的详情页？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2706]
##### 问题描述：
如何给报表项加href,，可以打开某个表单的某一项的详情

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/123518008-aab0f000-d6d6-11eb-931c-c9cc4583ea60.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044087
