### ISSUE TITLE
Online开发列表页不支持模糊搜索

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/jeecg-boot#2707]
##### 版本号：
v2.4.5

##### 问题描述：
Online开发列表页不支持模糊搜索

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/123531126-871c9280-d734-11eb-8955-7040af6daab0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043941

**Comment by xinxingzhao** [comment]
> http://doc.jeecg.com/2043941

Sorry！我搞错了，模糊搜索忘记打开

![image](https://user-images.githubusercontent.com/13712791/123540393-51e26580-d771-11eb-94cf-335f84c59ae9.png)
