### ISSUE TITLE
【online图表】JS增强里点击想带参数跳转怎么设置

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2708]
##### 问题描述：
【online图表】JS增强里点击想带参数跳转怎么设置

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/123531738-a10ca400-d739-11eb-8ba5-2c37e63efd92.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044145
