### ISSUE TITLE
autopoi @ExcelCollection注解如何实现多对多跨行

### ISSUE THREAD

**Issue by ysfcore** [zhangdaiscott/jeecg-boot#2709]
##### 版本号：
2.4.5

##### 问题描述：
autopoi @ExcelCollection注解如何实现多对多跨行

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请详细描述清楚你的需求，图文并茂

**Comment by lsqGitHub716** [comment]
一对多导出实例：http://doc.jeecg.com/2044230
