### ISSUE TITLE
【online报表】合计怎么设定数值格式？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2710]
##### 问题描述：
online 报表中使用合计，怎么能控制不显示小数点后2位？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/123536791-ee4f3c80-d75e-11eb-8f1a-13372b3eb37e.png)

![image](https://user-images.githubusercontent.com/7098009/123536775-e2637a80-d75e-11eb-9a18-fddba8351258.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
