### ISSUE TITLE
【online报表】限定组件样式有什么用？

### ISSUE THREAD

**Issue by kasidier** [zhangdaiscott/jeecg-boot#2711]
##### 问题描述：
配置菜单时，说明文档说要使用固定组件，但是发现使用其他组件也可以，固定组件有什么特殊意义么？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/123540147-1d21de80-d770-11eb-8ca2-ab4f3e8295ee.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
动态组件，可以随便写
