### ISSUE TITLE
less语法加载error

### ISSUE THREAD

**Issue by gqf1995** [zhangdaiscott/jeecg-boot#2718]
##### 问题描述：
less语法加载报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20791771/123617636-0b0c7280-d83a-11eb-8ca2-d7038834b82f.png)

![image](https://user-images.githubusercontent.com/20791771/123617671-13fd4400-d83a-11eb-9573-a7fcc14c52d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你的工具问题吧
