### ISSUE TITLE
2.4.5版本登录admin账号异常。

### ISSUE THREAD

**Issue by ddd123mike** [zhangdaiscott/jeecg-boot#2719]
##### 版本号：

v2.4.5
##### 问题描述：

克隆“12ad80d”提交的版本后，结果环境搭建和数据库配置等等，一直到运行都没有问题。
打开vue发布的页面，登录功能貌似正常，但是登录账号admin后，直接爆【 Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysDepartMapper.queryUserDeparts】异常。

我怀疑是我的那个地方没弄好，于是跳回v2.4.3版本（“1534316”提交的节点），再次运行并登录了账号admin，结果！！！成功了！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7887787/123619465-c84b9a00-d83b-11eb-8c03-b48513782a50.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你是自己合并的代码吧，如果下载代码直接运行不会有问题
