### ISSUE TITLE
Online表单获取值的问题

### ISSUE THREAD

**Issue by jw879** [zhangdaiscott/jeecg-boot#2723]
##### 版本号：
jeecg 2.4.5

##### 问题描述：
请问Online表单开发通过校验字段拿到另一张表的某个字段的时候，怎么同时将另一张表包括该字段的其他值也获取到，新增到现有表中。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
http://doc.jeecg.com/2044073
