### ISSUE TITLE
j-edit-table中select是否支持动态赋值

### ISSUE THREAD

**Issue by liupei1995** [zhangdaiscott/jeecg-boot#274]
##### 问题描述：
想要给j-edit-table的select动态赋值，貌似没有作用

##### 截图&代码：
![QQ截图20190708100230](https://user-images.githubusercontent.com/21356797/60777991-a563df00-a167-11e9-8840-c1618cb9b917.png)

**Comment by zhangdaiscott** [comment]
支持
