### ISSUE TITLE
控制层try catch没有抛出任何的异常，用try{}catch(){}并不能判断是否操作数据库成功吧

### ISSUE THREAD

**Issue by viking-luan** [zhangdaiscott/jeecg-boot#277]
##### 问题描述：
控制层try catch没有抛出任何的异常，用try{}catch(){}并不能判断是否操作数据库成功吧

##### 截图&代码：
![ssssss](https://user-images.githubusercontent.com/52649897/60789246-37341200-a191-11e9-8c39-f3ef8f38b67c.png)

**Comment by zhangdaiscott** [comment]
??

**Comment by viking-luan** [comment]
上面的service调用的结果，不能直接说明已经【修改成功】，因为这个service没有向controller抛出throws任何异常；即使service是throws了异常，实际正确执行了数据操作，也并不代表已经成功的更新了数据库记录，要根据返回值及异常综合判断才算合理！

**Comment by galaxist** [comment]
mybatisplus本身就抹掉了一部分异常，如果没有无用操作update默认可以算成功的。

**Comment by viking-luan** [comment]
非常感谢
