### ISSUE TITLE
initQueryWrapper组装sql查询条件错误

### ISSUE THREAD

**Issue by jarvissdiff** [zhangdaiscott/jeecg-boot#284]

**Comment by zhangdaiscott** [comment]
好的，我们看看

**Comment by tygithub1** [comment]
Sorry, this is not a bug. This is the design. Please read the document. [地址](http://jeecg-boot.mydoc.io/?t=345707)

**Comment by jarvissdiff** [comment]
那现在你们表里的 lt,gt,ne这些会员账号都无法使用和查出来，但是存在数据库啊

**Comment by zhangdaiscott** [comment]
已经解决，请更新代码。
最新规则文档参考：
http://jeecg-boot.mydoc.io/?t=345707
