### ISSUE TITLE
升级2.0.2后，列表页很多子页面存在字符乱码

### ISSUE THREAD

**Issue by fengzie** [zhangdaiscott/jeecg-boot#285]
##### 版本号：
Jeecg Boot: 2.0.2

##### 问题描述：
升级2.0.2后，一下列表页中的子页面存在乱码显示：查询表格， 内联编辑表格，用户列表，角色列表，权限列表，搜索列表（文章），搜索列表（应用）、搜索列表（项目）

个人页->工作台

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34826428/60852558-be819400-a22a-11e9-8737-49a35a73a532.png)

![image](https://user-images.githubusercontent.com/34826428/60852575-d3f6be00-a22a-11e9-96d9-97225becb183.png)

**Comment by zhangdaiscott** [comment]
是不是项目编码不对

**Comment by fengzie** [comment]
> 是不是项目编码不对

有可能是的，查代码，数据源是从jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/demo/mock/json/service.json 里面来的，但数据源里的文字是好的，页面显示就乱了，没有改编码，项目编码在哪调？
![image](https://user-images.githubusercontent.com/34826428/60863276-bd645d00-a252-11e9-8cab-a2ffc98da2f6.png)

![image](https://user-images.githubusercontent.com/34826428/60863294-c9e8b580-a252-11e9-8bc1-29368a621e25.png)

**Comment by fengzie** [comment]
@zhangdaiscott ，很奇怪，这个问题在本地机器上没有，放到了ubuntu的远程测试机上才有

**Comment by zhangdaiscott** [comment]
那你看看吧，ubuntu环境
