### ISSUE TITLE
2.0.2无法启动

### ISSUE THREAD

**Issue by mushroomlb** [zhangdaiscott/jeecg-boot#289]
##### 版本号：
2.0.2
##### 问题描述：
启动包这个错误
##### 截图&代码：
![image](https://user-images.githubusercontent.com/1701771/60957550-6be1ce00-a337-11e9-8240-d42cf9484305.png)

**Comment by zhangdaiscott** [comment]
你改什么了？

**Comment by mushroomlb** [comment]
就把配置文件中的链接字符串改了，其他没动，更新了一次代码还是这样

**Comment by mushroomlb** [comment]
2.0.1版本就能运行，很奇怪

**Comment by zhangdaiscott** [comment]
把你改的截图出来，应该是你改错了

**Comment by galaxist** [comment]
url被你删掉或url改成其他的了

**Comment by mushroomlb** [comment]
![image](https://user-images.githubusercontent.com/1701771/61016275-a7c17580-a3c1-11e9-9256-0a18a28ee720.png)
只改了链接字符串和密码

**Comment by galaxist** [comment]
依赖mysql驱动冲突或被你删了？

**Comment by mushroomlb** [comment]
@galaxist 重新下载什么也不动，顶多报数据库连接错误，现在还没到这一步就报错了，应该是baomidou3.1.2解析多数据库时出现了错误
