### ISSUE TITLE
登录首页点击忘记密码样式乱了

### ISSUE THREAD

**Issue by deanver** [zhangdaiscott/jeecg-boot#290]
##### [截图&代码：]

![image](https://user-images.githubusercontent.com/15809932/60970447-93935f00-a354-11e9-9292-dccc7d9e60d5.png)

**Comment by deanver** [comment]
macos  Chrome浏览器最新版

**Comment by zhangdaiscott** [comment]
发现这个问题了，3Q

**Comment by zhangdaiscott** [comment]
已经修复下个版本发布
