### ISSUE TITLE
无法使用axios

### ISSUE THREAD

**Issue by ws-jdk** [zhangdaiscott/jeecg-boot#291]
##### 截图&代码：
![D )9@Y_734H{MES4B(336NF](https://user-images.githubusercontent.com/52026987/61017519-10125600-a3c6-11e9-82cb-52e655d1fa52.png)
![7C3T)2QO)(`XMILHX_`{DXV](https://user-images.githubusercontent.com/52026987/61017521-10aaec80-a3c6-11e9-985e-84a7293361bc.png)
![~P~NA`1Q3ZQ((Z%4X2@JEO4](https://user-images.githubusercontent.com/52026987/61017523-11dc1980-a3c6-11e9-8536-2d991174dd33.png)

**Comment by zhangdaiscott** [comment]
应该是你环境没配置好

**Comment by ws-jdk** [comment]
我打印this.$axios，显示undefined，不知道怎么解决，没用过这个东西，vue也是刚接触没多久

**Comment by ws-jdk** [comment]
cnpm install --save axios                                               好了
