### ISSUE TITLE
登录only_full_group_by的报错

### ISSUE THREAD

**Issue by 343122875** [zhangdaiscott/jeecg-boot#293]
##### 版本号：
jeecg-boot 2.0.2

##### 问题描述：
前面也有这个的lssues 但是我看和数据库版本没关系啊 这条sql本身就有点问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36358868/61026737-c5ed9c80-a3e6-11e9-993d-b88c86f20b57.png)

**Comment by zhangdaiscott** [comment]
你数据库版本多少，执行下面SQL看看

select count(*) as visit,
        	   count(distinct(ip)) as ip,
        	   DATE_FORMAT(create_time, '%Y-%m-%d') as tian,
        	   DATE_FORMAT(create_time, '%m-%d') as type
         from sys_log 
         where log_type = 1 and create_time >= '2019-07-08' and create_time < '2019-07-11'
         group by tian
         order by tian asc

**Comment by 343122875** [comment]
> 你数据库版本多少，执行下面SQL看看
> 
> select count(*) as visit,
> count(distinct(ip)) as ip,
> DATE_FORMAT(create_time, '%Y-%m-%d') as tian,
> DATE_FORMAT(create_time, '%m-%d') as type
> from sys_log
> where log_type = 1 and create_time >= '2019-07-08' and create_time < '2019-07-11'
> group by tian
> order by tian asc

5.7的 我把tian别名去掉就可以了 group by create_time

**Comment by zhangdaiscott** [comment]
已经处理，并上传git
