### ISSUE TITLE
新增的弹框 做成table切换页面

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#294]
##### 版本号：
2.0

##### 问题描述：

新增的弹框 做成table切换页面
##### 截图&代码：
编写代码
![image](https://user-images.githubusercontent.com/5210084/61026779-f2091d80-a3e6-11e9-9dea-27834039c7be.png)
直接在list页面不起作用
![image](https://user-images.githubusercontent.com/5210084/61025297-dbf95e00-a3e2-11e9-8f74-b3f3a66d33cb.png)

![image](https://user-images.githubusercontent.com/5210084/61025267-c2581680-a3e2-11e9-88eb-8b12bfab69fb.png)

按#160 Issues 答案未解决

**Comment by zhangdaiscott** [comment]
采用路由跳转
this.$router.push({ path: '/online/cgformTreeList/' + rd.id })

**Comment by shaowen** [comment]
> 采用路由跳转
> 这个。$ router.push（{path：'/ online / cgformTreeList'}）

下图代码目录
![image](https://user-images.githubusercontent.com/5210084/61095263-4e227f00-a485-11e9-9fd4-7fd6fd38b536.png)
按路由跳转 配置 点击新增没有反应
![image](https://user-images.githubusercontent.com/5210084/61095278-5f6b8b80-a485-11e9-99bc-c1b0a342092e.png)

**Comment by yanyanpeng** [comment]
同样碰到这个问题
