### ISSUE TITLE
后端服务system打包出现问题

### ISSUE THREAD

**Issue by fjc440** [zhangdaiscott/jeecg-boot#297]
##### 版本号：

2.0.1
##### 问题描述：
system打包的时候找不到common包里面的类，最终导致打包失败

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28079195/61032325-cc364580-a3f3-11e9-86f5-85ceeed5a085.png)
![image](https://user-images.githubusercontent.com/28079195/61032352-dd7f5200-a3f3-11e9-80d1-2a31066c2990.png)

**Comment by zhangdaiscott** [comment]
install  parent

**Comment by fjc440** [comment]
install parent 也会出现一样的错误
![image](https://user-images.githubusercontent.com/28079195/61032844-d573e200-a3f4-11e9-8d79-40e8758e7c5f.png)
