### ISSUE TITLE
线上部署后端服务出现问题

### ISSUE THREAD

**Issue by fjc440** [zhangdaiscott/jeecg-boot#298]
##### 版本号：
2.0.1

##### 问题描述：
线上启动system包后，显示找不到common包里的类，而且本地install parent也会出现问题

##### 截图&代码：
线上问题：
![image](https://user-images.githubusercontent.com/28079195/61033239-a01bc400-a3f5-11e9-81a1-d1a843cf6db5.png)
install parent问题
![image](https://user-images.githubusercontent.com/28079195/61033294-c17cb000-a3f5-11e9-8588-dc4455f800ea.png)

**Comment by zhangdaiscott** [comment]
单独install common

**Comment by fjc440** [comment]
单独install common过了 但是之后再去install system或者parent还是报一样的错误

**Comment by fjc440** [comment]
> 单独install common

单独install common过了 但是之后再去install system或者parent还是报一样的错误

**Comment by fjc440** [comment]
> 单独install common

打包成功了，但是线上的那个问题还是存在，麻烦看一下

**Comment by klniu** [comment]
是不是用错配置文件了，看到你激活的test配置

**Comment by fjc440** [comment]
> 是不是用错配置文件了，看到你激活的test配置

这个并没用，是版本问题，2.0.1问题有bug，但是2.0.2是没有问题的
