### ISSUE TITLE
部门管理选择部门前面的选择框 点击“添加子部门” 提示报错“请选择一条记录”，实际是没选中状态

### ISSUE THREAD

**Issue by xiaguifu** [zhangdaiscott/jeecg-boot#299]
##### 版本号：
2.0.2

##### 截图&代码：
![E3FE2F1A-3B94-4a30-B0D1-827E19420DCE](https://user-images.githubusercontent.com/50070874/61033502-3819ad80-a3f6-11e9-8fc4-4247e7f84e75.png)

**Comment by zhangdaiscott** [comment]
收到，3Q

**Comment by zhangdaiscott** [comment]
目前代码中的checkbox 主要给批量删除用的，添加修改还有右键都是根据点击树节点来操作的
所有针对树操作，请点击树控件
这个问题，我们暂时不做修改
