### ISSUE TITLE
使用ideal启动前端，报错

### ISSUE THREAD

**Issue by cathy0310** [zhangdaiscott/jeecg-boot#30]
npm install执行成功，但是npm run serve报错，报错信息如下：
Syntax Error: SyntaxError: C:\McD-workspace\jeecg-boot-master\ant-design-jeecg-vue\src\utils\axios.js: Export 'instance' is not defined (36:4)

  34 |     VueAxios,
  35 |     // eslint-disable-next-line no-undef
> 36 |     instance as axios
     |     ^
  37 | }

**Comment by zhangdaiscott** [comment]
用yarn
