### ISSUE TITLE
如图报错的话，url应该如何写？

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#302]
##### 版本号：
2.0.2

##### 问题描述：
如图报错的话，url应该如何写？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3365218/61043456-e75f8000-a408-11e9-9c7c-a1f2d99514ae.png)

**Comment by zhangdaiscott** [comment]
新增的菜单配置，截图出来

**Comment by galaxist** [comment]
![image](https://user-images.githubusercontent.com/3365218/61043987-378b1200-a40a-11e9-8263-4ffbaf7900df.png)
![image](https://user-images.githubusercontent.com/3365218/61044013-440f6a80-a40a-11e9-8e62-85d9abc1b5fd.png)

**Comment by zhangdaiscott** [comment]
菜单配置，这能看出什么

**Comment by galaxist** [comment]
![image](https://user-images.githubusercontent.com/3365218/61094713-d3f0fb00-a482-11e9-8062-fc52541cfa4f.png)
是zhide指的这个吗？

**Comment by galaxist** [comment]
@zhangdaiscott 请问我这个是什么问题呀，就直接close了？
