### ISSUE TITLE
增加postgresql数据库脚本

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#304]
##### 截图&代码：
<img width="704" alt="截屏2019-07-1123 55 27" src="https://user-images.githubusercontent.com/9619081/61066016-623f8f80-a437-11e9-8795-68e9e603dec0.png">

**Comment by zhangdaiscott** [comment]
自己用navicat转一份就行

**Comment by bibichuan** [comment]
转出来会报错，org.postgresql.util.PSQLException: ERROR: column "trigger_name" does not exist
