### ISSUE TITLE
企业微信部门管理没有出现同步功能

### ISSUE THREAD

**Issue by 2318348826** [zhangdaiscott/jeecg-boot#3048]
##### 截图&代码：

![1](https://user-images.githubusercontent.com/91167039/134270500-f8d91266-0042-42fc-8bf1-0d9c40aebc67.JPG)

![捕获](https://user-images.githubusercontent.com/91167039/134270502-0008b7a2-8546-46a9-91b3-148fe089c719.JPG)

![2](https://user-images.githubusercontent.com/91167039/134270572-f00c3cca-c580-4abe-a2da-70a8055a86d4.JPG)

![3](https://user-images.githubusercontent.com/91167039/134270793-e919da42-e0b0-4e0f-aa95-078dfd603741.JPG)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by 2318348826** [comment]
太多了所以我把代码贴在了文本里面
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 企业微信部门管理没有出现同步功能 (#3048)





 
没有复现该问题，贴出来 src/views/system/DepartListSync.vue 的代码看看
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2318348826** [comment]
![4](https://user-images.githubusercontent.com/91167039/136637632-14f76611-43a1-4389-a851-8a6a58162b28.JPG)
![5](https://user-images.githubusercontent.com/91167039/136637635-8dcdf35b-66a8-4cf3-8e03-92d53414dfce.JPG)
![1](https://user-images.githubusercontent.com/91167039/136637636-d3fbe7f7-6e81-48ad-b2b6-ef39b038e1f6.JPG)
![2](https://user-images.githubusercontent.com/91167039/136637638-c7d90c14-4ba1-4c40-b551-caafd89da9b9.JPG)
![3](https://user-images.githubusercontent.com/91167039/136637639-a0f65d98-b140-4bb2-b564-0fcffc483451.JPG)
![6](https://user-images.githubusercontent.com/91167039/136637640-d82bfb5e-3791-439b-98e8-99d32155b833.JPG)
![7](https://user-images.githubusercontent.com/91167039/136637641-0d44fcbe-cbdb-4e6a-8894-b7c90499907a.JPG)
![8](https://user-images.githubusercontent.com/91167039/136637642-67410c71-9f86-4d38-8481-927b06d00bb4.JPG)
![9](https://user-images.githubusercontent.com/91167039/136637643-80c87832-7434-4d29-8bf9-88f8222299d0.JPG)
![10](https://user-images.githubusercontent.com/91167039/136637924-ce3579ac-6264-40bf-9f01-e84f37670df4.JPG)
![12](https://user-images.githubusercontent.com/91167039/136637925-c9776095-3787-4a99-8c2b-ad19cde14262.JPG)
![13](https://user-images.githubusercontent.com/91167039/136637923-8822adf7-ac38-4c7c-87b9-afc36b8149fc.JPG)
![14](https://user-images.githubusercontent.com/91167039/136637928-ae9f134b-8258-4a84-ae02-f5068748472f.JPG)
![15](https://user-images.githubusercontent.com/91167039/136637929-03fea86b-a885-45d1-9cc8-2f3d0d643738.JPG)
![16](https://user-images.githubusercontent.com/91167039/136637930-7e90582e-df24-4794-95c3-2e92a9c6e285.JPG)
![17](https://user-images.githubusercontent.com/91167039/136637931-c2cbbc04-35af-4bd7-89b4-ad76f9e9b48c.JPG)
![18](https://user-images.githubusercontent.com/91167039/136637932-ed81959a-cd72-4727-8c22-9058d3da146d.JPG)
![19](https://user-images.githubusercontent.com/91167039/136637934-956d781e-b620-4f63-8b20-a8f2e93ce93b.JPG)
![20](https://user-images.githubusercontent.com/91167039/136637935-1101afdc-ed77-49b9-bc5e-b102b22a1082.JPG)
![23](https://user-images.githubusercontent.com/91167039/136637941-c6b5a954-8354-4084-934c-9d463b820dcc.JPG)
![21](https://user-images.githubusercontent.com/91167039/136637942-af9914ea-f60d-4c6c-a0d1-6d5394207b48.JPG)
![22](https://user-images.githubusercontent.com/91167039/136637945-17eb4bde-4a0d-4dbf-b1fd-650fb386e078.JPG)

这一页的代码没有更改过
