### ISSUE TITLE
关于文档中的业务国际化问题

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#305]
##### 问题描述：
官方文档 描述：通过 vue-i18n 插件来实现全球化的功能，在 src/components/lang/index.js 中引入相应的插件，以及对应的语言js，例如 en-US.js 和 zh-CN.js
可是工程里没有 src/components/lang/index.js 

##### 截图&代码：
<img width="320" alt="WeChatef9fd1bcdd8f87333aef3a60e338676b" src="https://user-images.githubusercontent.com/52776371/61094345-66909a80-a481-11e9-8aa3-158ce72087ea.png">

**Comment by zhangdaiscott** [comment]
我们暂时不考虑改造国际化
你可以参考下面方案，自己改造
33. 国际化改造方案
http://jeecg-boot.mydoc.io/?t=346061

**Comment by he0128** [comment]
看的就这个文档  文档中说得路径没有 没法按照文档来操作 工程里没有“src / components / lang / index.js”文件

**Comment by fly1206** [comment]
http://jeecg-boot.mydoc.io/?t=346061   文档已更新
