### ISSUE TITLE
> 采用路由跳转无反应

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#307]
> 采用路由跳转
> 这个。$ router.push（{path：'/ online / cgformTreeList'}）

下图代码目录
![image](https://user-images.githubusercontent.com/5210084/61095263-4e227f00-a485-11e9-9fd4-7fd6fd38b536.png)
按路由跳转 配置 点击新增没有反应
![image](https://user-images.githubusercontent.com/5210084/61095278-5f6b8b80-a485-11e9-99bc-c1b0a342092e.png)

菜单页面配置
![image](https://user-images.githubusercontent.com/5210084/61095338-a78aae00-a485-11e9-8e03-e42b7c423a2c.png)

_Originally posted by @shaowen in https://github.com/zhangdaiscott/jeecg-boot/issues/294#issuecomment-510707347_

**Comment by zhangdaiscott** [comment]
请提项目本地的问题，自己开发的问题，请多看看基础的书籍
