### ISSUE TITLE
积木报表集成模式，OSS上传支持V4

### ISSUE THREAD

**Issue by Zoe-Zhu** [zhangdaiscott/jeecg-boot#3089]
##### 版本号：
1.3.795

##### 问题描述：
OSS不支持 V4版本的Access, 报Access Denied
##### 截图&代码：
![image](https://user-images.githubusercontent.com/22297885/136487304-7649092f-d29f-4c88-b7ea-ebd058431d85.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
V4版本的Access？？详细说明用法
