### ISSUE TITLE
设计到批量删除的地方：选中一条数据：然后通过表格更多删除功能删除掉该数据，批量删除按钮还存在且可以操作

### ISSUE THREAD

**Issue by xiaguifu** [zhangdaiscott/jeecg-boot#309]
##### 版本号：

2.0.2
##### 问题描述：
设计到批量删除的地方：选中一条数据：然后通过表格更多删除功能删除掉该数据，批量删除按钮还存在且可以操作
建议：操作删除按钮后同时把存储该数据数组对象里面的id同时去掉

##### 截图&代码：

![2C4DF8E4-462E-467c-8861-2D44EFE622FF](https://user-images.githubusercontent.com/50070874/61106563-1e3ca100-a4b0-11e9-8f79-e33196d42883.png)

![FF8217A9-F6F7-43b4-AD6F-EC8C80AD6E83](https://user-images.githubusercontent.com/50070874/61106499-f1888980-a4af-11e9-89b4-6fd64e13b476.png)

**Comment by xiaguifu** [comment]
![25A621F9-821F-4bf9-A8C0-017122F19C88](https://user-images.githubusercontent.com/50070874/61106859-f994f900-a4b0-11e9-8e8a-f332733e3813.png)
我觉得这里加上这段代码就可以了

**Comment by zhangdaiscott** [comment]
好的，我们看看

**Comment by zhangdaiscott** [comment]
已处理并上传git，3Q
