### ISSUE TITLE
表单日期字段未能格式化问题

### ISSUE THREAD

**Issue by bujunwen** [zhangdaiscott/jeecg-boot#3090]
##### 版本号：
2.4.6

##### 问题描述：
表单中包含这个日期字段，新增完成后显示这个时间字段的时候，是以时间戳的方式显示，不是以格式化好的日期方式显示的，这个是要我手动转换吗？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/8176519/136490350-2d4dcafd-7780-418c-9a17-e273bd14b985.png)
![image](https://user-images.githubusercontent.com/8176519/136490377-acd26d04-185f-4c55-a078-c7a0184b11d7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新代码，前段时间有个bug，已经改了
