### ISSUE TITLE
数据规则仅对查询有效，对更新和删除无效

### ISSUE THREAD

**Issue by Rewivy** [zhangdaiscott/jeecg-boot#3095]
##### 截图&代码：
![企业微信截图_16339340339628](https://user-images.githubusercontent.com/48473052/136743490-232ed464-275d-45a3-a824-018d181bc3d3.png)

![企业微信截图_16339341038130](https://user-images.githubusercontent.com/48473052/136743510-e8e5ec4f-f83d-4764-8bd6-28731c6d066a.png)

![企业微信截图_16339341384506](https://user-images.githubusercontent.com/48473052/136743530-49eafc3f-9916-4d5f-8766-119011256076.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
数据权限注主要是隔离数据
