### ISSUE TITLE
一对多示例功能中出现全部删除数据之后，操作按钮消失的问题

### ISSUE THREAD

**Issue by houzepeng** [zhangdaiscott/jeecg-boot#31]
![de909903dabcb6bb9c7e2ecbd23d256](https://user-images.githubusercontent.com/11486789/55124523-6a521880-5141-11e9-8177-823de76225f5.png)

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
新版会提供新的方案

**Comment by houzepeng** [comment]
新版大概什么时候出？谢谢。
