### ISSUE TITLE
积木报表通过api解析online表单报错

### ISSUE THREAD

**Issue by chaungweiRong** [zhangdaiscott/jeecg-boot#3106]
##### 版本号：
jeecgboot版本：2.4.6
##### 问题描述：
积木报表通过api解析online表单报错，online表单存在
报错信息：java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.

##### 截图&代码：
![E9%{J_P}XY3M Y4}_MZJ77X](https://user-images.githubusercontent.com/66629453/137455893-db7307c2-1247-4987-b51e-a39b63bb32b5.png)

api解析URL：{{ domainURL }}/online/cgform/api/data/test_jm_report/queryById?id='${id}'&token='${token}'

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你的jeecgboot是最新版本吗

**Comment by chaungweiRong** [comment]
你好，请问这个问题应该怎么解决？

**Comment by zhangdaiscott** [comment]
请把你的详细配置配置截图说明

**Comment by LancCJ** [comment]
> 

@chaungweiRong  兄弟 你解决了么？如何搞得，都是按照WIKI来的还是这个错误

**Comment by LancCJ** [comment]
哎 升级解决
