### ISSUE TITLE
对接钉钉免密登录，获取人员信息时候返回403

### ISSUE THREAD

**Issue by liwanyin** [zhangdaiscott/jeecg-boot#3117]
##### 版本号：
2.4.6 最新代码

##### 问题描述：
对接钉钉免密登录，已经申请l了通讯录所有的权限，但是获取人员信息时候返回403，请教大佬是否还需要别的配置呢？我用了两个钉钉都不行

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11974866/138031587-d0be5229-2914-4409-989d-572107260431.png)
![image](https://user-images.githubusercontent.com/11974866/138031620-cd365f48-5949-4fa5-afb0-e7b0c892994a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1meng** [comment]
我遇到了相同的问题，按照文档及添加了所需权限后仍然报错。最后在构造钉钉OAuth2登录授权地址的过程中加上prompt参数就可以了，[https://developers.dingtalk.com/document/app/obtain-identity-credentials]里面参数prompt是必须的。
![image](https://user-images.githubusercontent.com/33029682/139781948-5af90789-3a80-4532-a97c-5694fa034608.png)

**Comment by mrdong916** [comment]
> 我遇到了相同的问题，按照文档及添加了所需权限后仍然报错。最后在构造钉钉OAuth2登录授权地址的过程中加上prompt参数就可以了，[https://developers.dingtalk.com/document/app/obtain-identity-credentials]里面参数prompt是必须的。 ![image](https://user-images.githubusercontent.com/33029682/139782025-44c33ff0-887c-4cd5-ab7a-b96c7d899708.png)

再补充一下，钉钉获取用户信息时必须要加上 `prompt=consent`
因为在进行免登陆的时候需要用户手动进行授权一下个人信息，不然就会出现403的问题

还有就是在 企业微信/钉钉 OAuth2登录回调这里有个错误
https://github.com/jeecgboot/jeecg-boot/blob/baefc1338dd03de36384ce7d5846b08041b488d0/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/ThirdLoginController.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L326
重定向的路径固定为了wechat_enterprise，应该修改为 state += "&thirdType=" + source.toLowerCase();

**Comment by yeafel666** [comment]
> 

真的是万分感谢，我在钉钉工作台免密oauth2登录一直报错，看代码还以为是jeewx-api模块1.4.6的问题。 看了您的prompt=consent传值问题直接解决了我的问题。 另外，确实在oauth2回调里确实jeecg-boot的开发者写死了wechat_enterprise,导致我钉钉登录去重定向微信的内容。  再次感谢，希望 @zhangdaiscott 老大能够处理掉这几个bug，jeecg越来越好。
