### ISSUE TITLE
jeecg-boot-module-system>mvn install

### ISSUE THREAD

**Issue by cxs1994** [zhangdaiscott/jeecg-boot#312]
问题描述： The POM for org.jeecgframework.boot:jeecg-boot-base-common:jar:2.0.2 is missing, no dependency information available
Failed to execute goal on project jeecg-boot-module-system: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-module-system:jar:2.0.2: Failure to find org.jeecgframework.boot:jeecg-boot-base-commo
n:jar:2.0.2 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyun has elapsed or updates are forced

**Comment by zhangdaiscott** [comment]
先install  jeecg-boot-base-common
