### ISSUE TITLE
积木报表菜单路由缓存无效

### ISSUE THREAD

**Issue by lijinlang** [zhangdaiscott/jeecg-boot#3125]
##### 问题描述：

配置积木报表的时候，打开方式是内部，在菜单中路由缓存已经勾上了，每次切换的时候还是会重新加载，如何可以不让页面刷新。现在只能选外部打开，还是就是在外部打开的时候，主界面左边功能菜单每次会自动折叠回去，又要重新点开，感觉有点不是很方便。

##### 截图&代码：

![微信图片_20211022142614](https://user-images.githubusercontent.com/54636793/138404372-9716d23f-0f78-4392-823c-0c205d274617.png)

**Comment by zwdgit** [comment]
这两个问题依然存在，目前有解决方案吗？点击3级菜单会自动收到到 2 级菜单这个在哪可以修改啊，找了半天没找到
