### ISSUE TITLE
能否在页面中关闭tab标签页

### ISSUE THREAD

**Issue by liupei1995** [zhangdaiscott/jeecg-boot#314]
##### 问题描述：
能否在页面中操作关闭tab标签页，我看现在好像只能点击tab上面的×才能关闭

**Comment by zhangdaiscott** [comment]
请截图说明

**Comment by liupei1995** [comment]
> 请截图说明
![2019-07-15_155747](https://user-images.githubusercontent.com/21356797/61202164-5eeb2300-a719-11e9-81bf-ad199ca09339.png)
![2019-07-15_155800](https://user-images.githubusercontent.com/21356797/61202191-70ccc600-a719-11e9-8e78-05929ee40687.png)
按钮是编辑代理商页面的，我现在点击提交后，跳到新增代理商页面，但编辑代理商的标签页没有去掉

**Comment by zhouyilong** [comment]
我是将tab标签页绑定的pagelist和linklist移动到store的全局状态中，然后通过修改，达到关闭的效果

**Comment by czh378762** [comment]
layout组件里面有暴露出来provide方法closeCurrent，只需要在页面中inject，就可以直接调用关闭了
![image](https://user-images.githubusercontent.com/23158695/96848276-cc424380-1486-11eb-9f9b-4e35d376de74.png)
