### ISSUE TITLE
用户管理上传修改头像后右上角头像不能实时变化需重新登录后才能显示更换后的头像

### ISSUE THREAD

**Issue by ggunmo** [zhangdaiscott/jeecg-boot#316]
##### 版本号：
2.0.2

##### 问题描述：
用户管理上传修改头像后右上角头像不能实时变化需重新登录后才能显示更换后的头像

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18226120/61204660-64983700-a720-11e9-8be4-3785ba04c92f.png)

**Comment by zhangdaiscott** [comment]
首页刷新下，就可以了
