### ISSUE TITLE
登录时交互出的问题

### ISSUE THREAD

**Issue by deanver** [zhangdaiscott/jeecg-boot#319]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/15809932/61350454-29ba0e80-a89a-11e9-9bd6-290c8df09fc6.png)

**Comment by deanver** [comment]
如果进来的时候什么都不输入，点击登录页会出现登录按钮处于登录状态，交互出问题

**Comment by zhangdaiscott** [comment]
了解，感谢

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
