### ISSUE TITLE
启动jeecg-boot-module-system后台没有online

### ISSUE THREAD

**Issue by liuyang77886** [zhangdaiscott/jeecg-boot#320]
##### 版本号：
2.02

##### 问题描述：
启动jeecg-boot-module-system后台没有online

**Comment by liuyang77886** [comment]
以前的jeecg都有在线表单在线报表等功能

**Comment by liuyang77886** [comment]
2启动jeecg-boot-parent工程   代码生成器运行的是JeecgOneGUI 。 那工程的JeecgApplication。启动起来做什么用的呢，

**Comment by liuyang77886** [comment]
3.jeecg-boot-parent工程里有死循环注入

**Comment by zhangdaiscott** [comment]
死循环？
