### ISSUE TITLE
表单设计器功能设计建议

### ISSUE THREAD

**Issue by tianxia0079** [zhangdaiscott/jeecg-boot#328]
##### 问题描述：

表单设计器作为可视化设计，可以放在online开发中，用户可以可视化设计动态表单.
可以选择可视化设计，或者目前已经实现的非可视化设计

**Comment by tianxia0079** [comment]
现在设计设计规则，先有online表单，再自动生成可视化布局表单，再自定义，这个逻辑也挺好的。

**Comment by zhangdaiscott** [comment]
赞 我们已经这么实现了
