### ISSUE TITLE
菜单管理低分屏错位

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#33]
![image](https://user-images.githubusercontent.com/3365218/55269286-8930e600-52cc-11e9-881c-08fd343d138c.png)

**Comment by galaxist** [comment]
配置项文字多了后错位，在高分屏上显示无问题。

**Comment by zhangdaiscott** [comment]
好的，收录

**Comment by zhangdaiscott** [comment]
已经修复，等待新版发布
