### ISSUE TITLE
在webstrom里 运行yarn install 提示 shell error:not found

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#331]
##### 版本号：
2.0.2

##### 问题描述：

运城yarn install，提示 shell error:not found，但提示的路径用cmd执行yarn -version确认有安装，不知道为什么webstrom没有识别
##### 截图&代码：
![image](https://user-images.githubusercontent.com/3033456/61618029-90766800-ac9e-11e9-9fc7-62f5876b6001.png)

**Comment by zhangdaiscott** [comment]
百度吧，没遇到过
