### ISSUE TITLE
菜单tab页面刷新后保留

### ISSUE THREAD

**Issue by sdf921110** [zhangdaiscott/jeecg-boot#334]
##### 截图&代码：
刷新前：
![image](https://user-images.githubusercontent.com/12679437/61678039-48a22000-ad34-11e9-82b4-f0de67835e27.png)

刷新后：
![image](https://user-images.githubusercontent.com/12679437/61678060-5e174a00-ad34-11e9-9010-5fb456d4d212.png)

**Comment by zhangdaiscott** [comment]
不能
