### ISSUE TITLE
部门管理 - 批量删除BUG

### ISSUE THREAD

**Issue by sdf921110** [zhangdaiscott/jeecg-boot#335]
##### 问题描述：
详情见截图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12679437/61678590-daf6f380-ad35-11e9-9579-8495f51e1459.png)

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangdaiscott** [comment]
已经解决，下个版本会加上提示
