### ISSUE TITLE
druidsql报错，ORA-00904: "TIAN": 标识符无效

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#337]
##### 问题描述：
select count(*) as visit,
        	   count(distinct(ip)) as ip,
        	   DATE_FORMAT(create_time, '%Y-%m-%d') as tian,
        	   DATE_FORMAT(create_time, '%m-%d') as type
         from sys_log 
         where log_type = 1 and create_time >= ? and create_time < ?
         group by tian
         order by tian asc
ORA-00904: "TIAN": 标识符无效

**Comment by zhangdaiscott** [comment]
你更新最新的代码，试试，这块sql写的有点问题

**Comment by tyjohn** [comment]
最新代码也一样，这个sql在oracle下不能执行

**Comment by zhangdaiscott** [comment]
最新的代码，不是这个sql
