### ISSUE TITLE
部门管理 - 批量删除BUG

### ISSUE THREAD

**Issue by sdf921110** [zhangdaiscott/jeecg-boot#338]
##### 问题描述：
详情见截图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12679437/61679202-11357280-ad38-11e9-80c2-543435a409c8.png)
![image](https://user-images.githubusercontent.com/12679437/61679224-1f838e80-ad38-11e9-938b-f62afe66a36d.png)
![image](https://user-images.githubusercontent.com/12679437/61679237-2b6f5080-ad38-11e9-8c0f-219a0f020fd0.png)
![image](https://user-images.githubusercontent.com/12679437/61679245-31653180-ad38-11e9-9221-6fdc2bf70351.png)

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/300

重复的问题，更新代码就可以解决
