### ISSUE TITLE
添加用户无法提交（无法下拉）

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#34]
![image](https://user-images.githubusercontent.com/27263086/55271283-3152a900-52e5-11e9-94a3-711ccd5baf0c.png)
编译没有报错，无法下拉 最后信息无法填写，拉取最新前端代码。

**Comment by zhangdaiscott** [comment]
下拉是什么意思？

**Comment by ileadall42** [comment]
@zhangdaiscott 意思是就是说 无法拉倒提交按钮按提交 红色圈圈的图标也出不来。

**Comment by ileadall42** [comment]
@zhangdaiscott 意思就是说 提交按钮没显示出来 页面无法往下滑

**Comment by galaxist** [comment]
屏幕分辨率问题吧

**Comment by maixiaoge** [comment]
这样修改就可以了！
![image](https://user-images.githubusercontent.com/29217445/55783876-fa00ab00-5ae1-11e9-8bad-f8ca857968e4.png)
