### ISSUE TITLE
pdf预览报错

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#342]
##### 问题描述：
pdf预览 pdf报错 pdf大小1M左右 本地可以打开

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/61687509-25d43380-ad55-11e9-9370-141d63c29325.png)
![image](https://user-images.githubusercontent.com/52776371/61687533-371d4000-ad55-11e9-9049-3616fea5660b.png)
![image](https://user-images.githubusercontent.com/52776371/61687628-7e0b3580-ad55-11e9-9231-b27b5311fc81.png)
![image](https://user-images.githubusercontent.com/52776371/61687704-a5620280-ad55-11e9-81dd-99641b1f1b13.png)
![image](https://user-images.githubusercontent.com/52776371/61687914-1f928700-ad56-11e9-8620-272c28eca964.png)

**Comment by zhangdaiscott** [comment]
参考下常用示例里面的例子
是可以用的
![image](https://user-images.githubusercontent.com/3162115/62030614-08510f00-b218-11e9-8e1e-b64a5fc072b8.png)
![image](https://user-images.githubusercontent.com/3162115/62030598-fff8d400-b217-11e9-9060-08d543ba6a16.png)

**Comment by he0128** [comment]
我参照的就是这个例子 只是把路径改了一下 用的还是咱们框架里的pdf 所以不知道怎么出现这个错误的 一脸的懵




------------------ 原始邮件 ------------------
发件人: "scott"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 下午3:47
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "笑笑云"<wang0128@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] pdf预览报错 (#342)




参考下常用示例里面的例子
 是可以用的

**Comment by zhangdaiscott** [comment]
你这个应该是pdf访问不到了吧，有token控制
加下排除
![image](https://user-images.githubusercontent.com/3162115/62033381-61bc3c80-b21e-11e9-8874-08cb45a194a8.png)
