### ISSUE TITLE
DatePicker 页面显示不全

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#343]
##### 版本号：
2.0.2

##### 问题描述：
DatePicker 页面底部的时候，无法显示确认按钮等

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/61688516-d0e5ec80-ad57-11e9-817b-26cf6539170b.png)

**Comment by zhangdaiscott** [comment]
收到

**Comment by he0128** [comment]
辛苦了


------------------ 原始邮件 ------------------
发件人: "scott"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 下午2:56
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "笑笑云"<wang0128@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] DatePicker 页面显示不全 (#343)




收到

**Comment by zhangdaiscott** [comment]
跟这个https://github.com/zhangdaiscott/jeecg-boot/issues/243重复了，先关闭
