### ISSUE TITLE
table隐藏某一列

### ISSUE THREAD

**Issue by menghuaxiao** [zhangdaiscott/jeecg-boot#344]
##### 问题描述：
table隐藏某一列，需要用到column里面的哪个属性

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40656857/61691606-7f8d2b80-ad5e-11e9-8f85-9dbe8d4fb195.png)
上图是用户管理界面，我想在前台展示的时候隐藏手机号这一列，这一列需要，但是只是不展示给用户。

![image](https://user-images.githubusercontent.com/40656857/61691918-2f629900-ad5f-11e9-9057-9da57b0a2f3f.png)
src/iews/system/UserList.vue文件中，columns里面的column有没有一个属性支持隐藏这一列？类似于hidden: ture之类的，vue中是通过标签v-show实现的，请问这个框架有没有这么一个属性可以去支持？
这个问题主要是考虑到业务中使用联合主键的问题，一个主键的话可以通过<a-table rowKey="id" /a>实现，但是联合主键（2个几以上）需要如何处理，比较主键一般不需要展示到前台的，只是用于返回到前台，放在隐藏域中，后续使用

**Comment by zhangdaiscott** [comment]
文档里面有
http://jeecg-boot.mydoc.io/?t=345992
