### ISSUE TITLE
不支持主键命名

### ISSUE THREAD

**Issue by Hugh126** [zhangdaiscott/jeecg-boot#345]
##### 版本号：
最新

##### 问题描述：
jeecg\code-template\one\java\${bussiPackage}\${entityPackage}\controller\${entityName}Controller.javai
line 106
Service.getById 
这个不支持主键不叫id的啊
##### 截图&代码：
![image](https://user-images.githubusercontent.com/13162682/61696742-74d79400-ad68-11e9-94cc-26a22c50a6d3.png)

**Comment by zhangdaiscott** [comment]
目前是这样，必须是id
