### ISSUE TITLE
JEditor富文本编辑器上传视频，在填写完视频地址并保存后，在富文本编辑框里不能播放该视频

### ISSUE THREAD

**Issue by CindyLiuMin** [zhangdaiscott/jeecg-boot#346]
##### 截图&代码：可在线演示网站里，点击常见案例-常用封装组件 进行查看效果
视频在线地址：https://dev-1259430456.cos.ap-shanghai.myqcloud.com/file/8427e700f64040cca6a0fe0a55a3a243.mp4

**Comment by chengtg** [comment]
一般富文本编辑，上传视频，在富文本框内都不可以点击的，存储的都是src=‘视频地址’，
都必须将文本框的存储的html内容 渲染到html页面才可点击的。
