### ISSUE TITLE
Dependency 'org.jeecgframework.boot:codegenerate:1.0.5' not found

### ISSUE THREAD

**Issue by cathy0310** [zhangdaiscott/jeecg-boot#348]
##### 版本号：
2.0.2

##### 问题描述：
Dependency 'org.jeecgframework.boot:codegenerate:1.0.5' not found

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/?t=345672

**Comment by MoShQing** [comment]
打不开，提示项目未公开
