### ISSUE TITLE
磁盘监控功能bug

### ISSUE THREAD

**Issue by menghuaxiao** [zhangdaiscott/jeecg-boot#351]
##### 版本号：
2.0.1

##### 问题描述：
磁盘监控bug

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40656857/61776320-60a99a80-ae2d-11e9-8a7c-9f25a8cd6eb3.png)

![image](https://user-images.githubusercontent.com/40656857/61776354-6c955c80-ae2d-11e9-9ad3-7690d2332bda.png)

磁盘监控功能，e盘使用率应该是四舍五入后约等于0，但是图片显示有误

**Comment by menghuaxiao** [comment]
版本是2.0.2

**Comment by fly1206** [comment]
修改图片中几处红框标注的内容
![1](https://user-images.githubusercontent.com/23536399/62688618-cab06b00-b9fb-11e9-9fb1-3cc0c89cac07.png)
![2](https://user-images.githubusercontent.com/23536399/62688630-cf751f00-b9fb-11e9-82e0-1ab6a8a6de5a.png)
