### ISSUE TITLE
想问一下，代码能直接发布成手机APP，是否需要改造

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#352]
##### 问题描述：

不是手机用浏览器访问，是直接app发布的话，咋们的代码需要改造吗？

**Comment by zhangdaiscott** [comment]
你可以直接把编译的dist，用hbuilder打成app

**Comment by zhangdaiscott** [comment]
在vue.config.js文件中加入
 baseUrl: './',
不然一直加载，进不到登录页面
![TIM图片20190811162555](https://user-images.githubusercontent.com/3162115/62831592-b5824900-bc54-11e9-9167-1c3b120926e9.png)

**Comment by zhangdaiscott** [comment]
手机端安装配置的教程
https://jeecg.blog.csdn.net/article/details/99293549

**Comment by huahuadeep** [comment]
手机端安装配置的教程https://jeecg.blog.csdn.net/article/details/99293549，
按照这个教程本地搭建登录后会跳转到首页，帮忙看看是不是哪里配置错误？

1. 在vue.config.js文件中加入
`baseUrl: './',`

2. 修改public目录下index.html
`window._CONFIG['domianURL'] = 'http://ip:8080/jeecg-boot';
    window._CONFIG['casPrefixUrl'] = 'http://cas.example.org:8443/cas';
    window._CONFIG['imgDomainURL'] = window._CONFIG['domianURL'] + '/sys/common/view';
    window._CONFIG['pdfDomainURL'] =  window._CONFIG['domianURL'] + '/sys/common/pdf/pdfPreviewIframe';`

3. 修改src/utils/request.js
`const service = axios.create({
  baseURL: 'http://ip:8080/jeecg-boot/', // api base_url
  timeout: 6000 // 请求超时时间
})`
