### ISSUE TITLE
路由带参跳转问题。打开2次

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [zhangdaiscott/jeecg-boot#353]
##### 版本号：
当前最新版本： 1.1.0（发布日期：20190415）

##### 问题描述：
在table页面 最后一列操作列 给一个带参跳转路由的功能。
会打开两次。每次的参数都是拿不到的。

##### 截图&代码：
`<a @click="handleDetailBill()">查看详情</a>`
`      //查看详情
      handleDetailBill () {
        this.$router.push({
          path:'InterfaceRecordLogsDetail',
          query:{
            startDate:moment(this.queryParam.startDate).format("YYYY-MM-DD"),
            endDate:moment(this.queryParam.endDate).format("YYYY-MM-DD")
          }
        })
      },`
![微信截图_20190725182559](https://user-images.githubusercontent.com/20105361/61867423-c408fa80-af09-11e9-8ff9-5b61be63b819.png)
![微信截图_20190725182611](https://user-images.githubusercontent.com/20105361/61867425-c4a19100-af09-11e9-920c-9387cbc3cd04.png)

**Comment by xiaoshuaishuai319** [comment]
TabLayout.vue 文件104行增加：
query:waitRouter.query
即可解决问题

**Comment by King10031** [comment]
能否贴一下代码 我粘贴过来了没有解决这个问题
