### ISSUE TITLE
想问大神一个技术性的问题，思考了好几天不得要领

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#360]
##### 版本号：

2.0.2
##### 问题描述：
在提交表单的时候的handleOk方法里，为什么将修改表单的方法（setFieldsValue）放到校验的方法（validateFields）里不生效，必须拉到外面

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3033456/61992098-50432b00-b08c-11e9-8c75-b49cfb3a4063.png)

**Comment by zhangdaiscott** [comment]
把this 换成that试试

**Comment by tyjohn** [comment]
换成that也不行

**Comment by zhangdaiscott** [comment]
注意 values参数
