### ISSUE TITLE
使用Oracle数据库时出现json转换报错

### ISSUE THREAD

**Issue by jianpingsong** [zhangdaiscott/jeecg-boot#361]
##### 版本号：
2.0.2

##### 问题描述：
Oracle环境下 DictAspect.parseDictText() 异常
**json解析失败Direct self-reference leading to cycle (through reference chain: org.jeecg.modules.message.entity.SysMessage["esContent"]->com.alibaba.druid.proxy.jdbc.NClobProxyImpl["rawNClob"]->oracle.sql.NCLOB["dbaccess"]->oracle.jdbc.driver.T4CConnection["wrapper"])**
##### 菜单链接
http://localhost:3000/modules/message/sysMessageList

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20661941/61993258-905dda00-b09b-11e9-9bcf-9553f178e89b.png)

**Comment by jianpingsong** [comment]
切换成mysql环境是正常的

**Comment by zhangdaiscott** [comment]
应该是大字段 clob类型的问题

**Comment by zhangdaiscott** [comment]
SysMessage的objct类型，改成 String就可以解决这个问题
