### ISSUE TITLE
带参数路由菜单如何配置？

### ISSUE THREAD

**Issue by ycw01** [zhangdaiscott/jeecg-boot#362]
##### 截图&代码：
![Uploading 1.png…]()
![2](https://user-images.githubusercontent.com/32702715/61995833-f0ff0e00-b0bf-11e9-8497-06166a72a746.png)
![3](https://user-images.githubusercontent.com/32702715/61995834-f3616800-b0bf-11e9-8652-a50fb1070fcd.png)

**Comment by ycw01** [comment]
![1](https://user-images.githubusercontent.com/32702715/61995841-05dba180-b0c0-11e9-870c-603effa5f6df.png)

**Comment by zhangdaiscott** [comment]
遇到问题请先看常见问题贴
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
17

**Comment by ycw01** [comment]
> 遇到问题请先看常见问题贴
> http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 17
我的问题还没解决，
这个配置方式我看了，也按这个方式"/online/cgreport/:code"地址配置了。
疑问：这样配置我只定义了存在code这个参数key，那我怎么传参数的value呢？
目的：我想实现的是相同页面及实体，根据不同类型拆分成单独的菜单，显示不同数据。
谢谢技术人员答疑

**Comment by ycw01** [comment]
> 遇到问题请先看常见问题贴
> http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 17

@zhangdaiscott 大佬，麻烦给看下楼上的疑问

**Comment by toblessing** [comment]
> > 遇到问题请先看常见问题贴
> > http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> > 17
> 
> @zhangdaiscott 大佬，麻烦给看下楼上的疑问

楼主有解决这个问题嘛？我也是按照文档配置，然后配置的路由地址就变成根地址了

**Comment by dut3062796s** [comment]
麻烦问下,楼主你的问题处理了么.我也是同样是问题。

**Comment by ycw01** [comment]
> 麻烦问下,楼主你的问题处理了么.我也是同样是问题。
https://github.com/zhangdaiscott/jeecg-boot/issues/362#issuecomment-565917769

**Comment by ycw01** [comment]
> 麻烦问下,楼主你的问题处理了么.我也是同样是问题。
看这里，问题里有配置方法
https://github.com/zhangdaiscott/jeecg-boot/issues/542

**Comment by dut3062796s** [comment]
@ycw01 你好,我有个疑惑是他的路由参数配置.  
1.这种方式：/123/123/:id ，这种方式在菜单路径那边配置了没有效果。只能在router.config.js添加一个路由规则。然后在菜单路径配置  /123/123/:1,这样才能获取到。但是从菜单点击打开后只当前页面,左边的菜单不显示了。
2.按/123/123?id=1这种方式添加菜单路劲，this.$route.query  和 this.$route.params 都获取不到。
你给我的那个好像没太大关系。我进页面的时候 watch 就没走。

**Comment by ycw01** [comment]
1、根据官方文档配置带参数路由菜单
2、配置路由菜单：/demo/demo/:code（注意这里，我需要配置一个隐藏的路由）
3、配置具体菜单a：/demo/demo/:1
4、配置具体菜单b：/demo/demo/:2

**Comment by dut3062796s** [comment]
@ycw01 
你好,添加隐藏路由之后，参数还是没有。
/isbusinessone/ads/:code
/isbusinessone/ads/:1
/isbusinessone/ads/:2

这是我这边加的,第一个是隐藏了的。三个都是 是路由菜单  
麻烦帮忙看看是哪块的问题

**Comment by ycw01** [comment]
> /isbusinessone/ads/:1
> /isbusinessone/ads/:2

/isbusinessone/ads/:1
/isbusinessone/ads/:2
这俩菜单配置“是否路由菜单”为“否”

**Comment by dut3062796s** [comment]
@ycw01 这样的话，点击菜单的时候 404了

**Comment by ycw01** [comment]
> @ycw01 这样的话，点击菜单的时候 404了

/isbusinessone/ads/:code
这个先配置，并且配置成“路由菜单”

**Comment by dut3062796s** [comment]
@ycw01 这个目前配置的是路由菜单。
其他俩个是否
