### ISSUE TITLE
如果表单字段很多，edit方法setfields还有pick吗，哪后面字段一个一个写太长了

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#364]
##### 版本号：

2.0.2
##### 问题描述：

          this.form.setFieldsValue(pick(this.model,字段1，字段2，字段3))
          如果我页面表单有100个字段，那要把100个字段都写出来吗？有没有一个类的方式作为参数替代

**Comment by zhangdaiscott** [comment]
暂时没有

**Comment by tyjohn** [comment]
那要将数据库中查出的数据写入到页面上，目前只能这样？，除非是一行一行的写，每一行一个属性
