### ISSUE TITLE
想问一下<span slot="action" slot-scope="text, record">这一段代码的slot属性是vue中的吗？

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#366]
##### 版本号：

2.0.2
##### 问题描述：
vue中的应该是slot元素，应该不是元素中的slot属性

**Comment by zhangdaiscott** [comment]
是的 插槽概念

**Comment by tyjohn** [comment]
我的意思是vue中的插槽是<slot>元素，咋们代码里是<span slot>是属性，我不太明白咋们这个的原理

**Comment by tyjohn** [comment]
我先好好看看slot，可能是我对插槽的理解还不深入
