### ISSUE TITLE
FormTypes.select中options动态绑定数据问题

### ISSUE THREAD

**Issue by ouyang856** [zhangdaiscott/jeecg-boot#368]
版本号：
2.0.2

问题描述：
在cloums中使用FormTypes.select控件，ｄｅｍｏ中代码ｏｐｔｉｏｎｓ为静态绑定的，现在需要动态从数据库获取值绑定，现已测试使用变量绑定ｏｐｔｉｏｎｓ，但无效

截图&代码：
![image](https://user-images.githubusercontent.com/46732703/62131619-1b460b00-b30e-11e9-8dcc-8f1ae75ecb80.png)
![image](https://user-images.githubusercontent.com/46732703/62131657-27ca6380-b30e-11e9-9c32-526e135a9cab.png)
![image](https://user-images.githubusercontent.com/46732703/62131684-3284f880-b30e-11e9-8431-9b49168172f9.png)

**Comment by sjlei** [comment]
你好，这个时候调用 `this.unitTypeDictOptions` 还未初始化，它的值是 `undefined`，所以无法实现你想要的的效果。

![image](https://user-images.githubusercontent.com/34293221/62203391-aa5e2c00-b3bd-11e9-9a16-f895cc4d5059.png)

**可行的解决方案是：**

1. 初始给 options 赋空数组
![image](https://user-images.githubusercontent.com/34293221/62203767-67e91f00-b3be-11e9-8be3-69b3c48b4ab7.png)

2. 在 `mounted` 生命周期函数中进行赋值
![image](https://user-images.githubusercontent.com/34293221/62203534-f4471200-b3bd-11e9-8df2-a889e492db29.png)

3. 实际运行效果
![image](https://user-images.githubusercontent.com/34293221/62203744-56a01280-b3be-11e9-903b-a87e7af09da2.png)
