### ISSUE TITLE
swagger 访问不了

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#372]
我也是访问 http://localhost:8080/jeecg-boot/swagger-ui.html 一直访问不了，一直弹窗输入用户名密码都不对。
![image](https://user-images.githubusercontent.com/2276718/62283972-4e5eda80-b485-11e9-9c5e-257a879e43d3.png)

从下图 可以看到 /swagger-ui.html 应该是可以匿名访问的
![image](https://user-images.githubusercontent.com/2276718/62284063-7d754c00-b485-11e9-8b1d-499cf08a176b.png)

**Comment by zhangdaiscott** [comment]
username: jeecg
    password: jeecg1314

**Comment by lanfen100** [comment]
> 我也是访问 http://localhost:8080/jeecg-boot/swagger-ui.html 一直访问不了，一直弹窗输入用户名密码都不对。
> ![image](https://user-images.githubusercontent.com/2276718/62283972-4e5eda80-b485-11e9-9c5e-257a879e43d3.png)
> 
> 从下图 可以看到 /swagger-ui.html 应该是可以匿名访问的
> ![image](https://user-images.githubusercontent.com/2276718/62284063-7d754c00-b485-11e9-8b1d-499cf08a176b.png)

application.yml 文件中设置的账户密码

**Comment by liudonghua123** [comment]
哦哦，好的，谢谢，希望可以再文档中说明 :)
