### ISSUE TITLE
a-table列信息多，显示不宽带 ，右边栏位不显示，而且也没有左右滚动条

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#375]
##### 版本号：
2.0.2

##### 问题描述：
a-table列信息多，显示不宽带 ，右边栏位不显示，而且也没有左右滚动条
##### 截图&代码：
![image](https://user-images.githubusercontent.com/31814666/62357197-29ca3780-b545-11e9-9be8-bf19334e6a34.png)

**Comment by gicp** [comment]
![image](https://user-images.githubusercontent.com/31814666/62359479-757ee000-b549-11e9-8213-b69458d0fef1.png)

**Comment by liudonghua123** [comment]
我也是有这个问题，我是通过 自定义显示列 解决，让用户来决定显示那些列（可选项是所有的列，初始显示的列就前几项），参考 

![image](https://user-images.githubusercontent.com/2276718/62377492-7168b780-b575-11e9-8467-c7548b8954ea.png)

**Comment by zhangdaiscott** [comment]
这个看官方文档，自己设置
https://vue.ant.design/docs/vue/introduce-cn/
