### ISSUE TITLE
分类字典页面显示错误

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#377]
##### 问题描述：分类字典页面显示错误
如图，列表显示时，下级节点也逐条显示出来了（显然是多余的）

##### 截图&代码：

![1](https://user-images.githubusercontent.com/9619081/62410428-c5c47380-b617-11e9-8442-e082d3ff9e2d.jpg)

**Comment by zhangdaiscott** [comment]
已重现，感谢

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
