### ISSUE TITLE
j-editable-table 控件中获取行号

### ISSUE THREAD

**Issue by ouyang856** [zhangdaiscott/jeecg-boot#378]
版本号：
2.0.2

问题描述：
在j-editable-table控件中没法直接使用行号，而在a-table中可以直接使用customRender:function (t,r,index) {
              return parseInt(index)+1;
            }
获取行号，需要通过什么方式才能使用customRender方式在j-editable-table中获取行号呢。
截图&代码：
![image](https://user-images.githubusercontent.com/46732703/62410522-49cb2b00-b619-11e9-85a0-cd606205f83a.png)
![image](https://user-images.githubusercontent.com/46732703/62410527-594a7400-b619-11e9-8a67-073dc4804b2e.png)

**Comment by sjlei** [comment]
在下个版本里，你可以 通过下面这种方式来获取当前的行号

### columns 配置

![image](https://user-images.githubusercontent.com/34293221/63318660-cc5a2700-c349-11e9-8916-73c9e96cc489.png)


### 页面对应slot

![image](https://user-images.githubusercontent.com/34293221/63318670-d845e900-c349-11e9-80be-d84660d7ba16.png)
