### ISSUE TITLE
新建公告时指定特定用户翻页错误SelectUserListModal

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#379]
##### 版本号：

2.0.2
##### 问题描述：
SelectUserListModal翻页错误
        param.current = this.ipagination.current;
        param.pageSize = this.ipagination.pageSize;
应该是
        param.pageNo = this.ipagination.current;
        param.pageSize = this.ipagination.pageSize;

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44466941/62424801-86288500-b706-11e9-8752-a30f67cc1dfc.png)

**Comment by fly1206** [comment]
非常感谢  已收录

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布，3Q
