### ISSUE TITLE
在启动JeecgSystemApplication的时候报错

### ISSUE THREAD

**Issue by YDerek** [zhangdaiscott/jeecg-boot#3793]
##### 版本号：
Jeecg  Boot Version: 3.2.0
jdk 1.8
Spring Boot Version: 2.6.6 (v2.6.6)

##### 问题描述：
在启动JeecgSystemApplication的时候报错，我试了把maven库的依赖全部重新下载了也不行，找不到原因。

##### 截图&代码：

<img width="952" alt="513358c192fbbf173546efed92d7795" src="https://user-images.githubusercontent.com/107106899/173552957-013b9fd4-1f61-4a08-874d-ed61a8be0760.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
启动单体类，为什么用到微服务？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2704725
