### ISSUE TITLE
一对多想生成示例中Tab那种样式的，怎么生成。

### ISSUE THREAD

**Issue by yeafel666** [zhangdaiscott/jeecg-boot#380]
##### 版本号：

 2.0.1
##### 问题描述：
想生成示例中一对多Tab那种样式的，我生成出来的是在编辑中控制子表。

##### 截图&代码：
想生成这种样式的一对多，如何操作。
![image](https://user-images.githubusercontent.com/41537806/62425037-2d0e2080-b709-11e9-9528-e21fc67bbff6.png)

**Comment by zhangdaiscott** [comment]
看下文档
http://jeecg-boot.mydoc.io/
![image](https://user-images.githubusercontent.com/3162115/62447214-760cb600-b797-11e9-9321-44f3a5d12007.png)

**Comment by yeafel666** [comment]
感谢，已成功生成。
