### ISSUE TITLE
从前台找后台的链接有什么快捷键等快捷的方式，太麻烦了

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#381]
##### 版本号：

2.0.2
##### 问题描述：
eclipse的后台，感觉从vue前台找后台没有固定的模式，全文搜索太麻烦了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3033456/62437012-0b964e80-b774-11e9-8e42-406559deb5d9.png)

**Comment by zhangdaiscott** [comment]
如果是代码生成的，是有规则，基本都是命名规范的
