### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by morrle** [zhangdaiscott/jeecg-boot#382]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28941145/62436903-af332f00-b773-11e9-92ed-94a8bac7fb8b.png)
![image](https://user-images.githubusercontent.com/28941145/62436921-bfe3a500-b773-11e9-84e9-bccb46fd29a3.png)
![image](https://user-images.githubusercontent.com/28941145/62437094-6039c980-b774-11e9-9c29-ee9e24ed117f.png)

**Comment by fly1206** [comment]
我们尽快处理

**Comment by fly1206** [comment]
已修正  下个版本发布
