### ISSUE TITLE
登录界面显示资源未找到，登录失败是怎么回事？

### ISSUE THREAD

**Issue by Guoguoguo12138** [zhangdaiscott/jeecg-boot#383]
![image](https://user-images.githubusercontent.com/46102403/62454574-2c2bcc00-b7a7-11e9-9e47-7d96e4f6ad3d.png)

**Comment by zhangdaiscott** [comment]
后台没启动

**Comment by Guoguoguo12138** [comment]
> 后台没启动

启动了呀
![image](https://user-images.githubusercontent.com/46102403/62455057-24b8f280-b7a8-11e9-90a2-091117d40cf2.png)

**Comment by JackyAndroid** [comment]
@Guoguoguo12138 请问解决了吗，我这也是相同的问题，通过浏览器访问api可以正常返回，说明server是正常的。但是在前端登录就不行，提示和你的一样
@zhangdaiscott 现在qq群不让进了吗，有没有新的群

**Comment by zhangdaiscott** [comment]
redis启动了吗

**Comment by JackyAndroid** [comment]
@zhangdaiscott 
问题找到了。
request.js中axios实例的baseURL需要的对应baseDomain，而不是baseProject，如下代码。
如果是baseProject请求的域名会变成localhost:3000而不是8080端口。
我这边配置都是按照官方配置，没有多修改其余配置。具体原因作者可以考虑下。
```
//自动设置后台服务 baseURL (也可以手工指定写死项目名字)
let baseDomain = window._CONFIG['domianURL'];
let baseProject = baseDomain.substring(baseDomain.lastIndexOf("/"));
console.log("baseDomain= ",baseDomain)
console.log("baseProject= ",baseProject)

// 创建 axios 实例
const service = axios.create({
  //baseURL: '/jeecg-boot',
  baseURL: baseDomain, // api base_url
  timeout: 9000 // 请求超时时间
})
```

**Comment by mll120110** [comment]
怎么设置多个后台服务呢？目前只能从window._CONFIG['domianURL']这个全局变量改吗？
