### ISSUE TITLE
首页进的是public/index.html? 但是里面没看到加载vue的代码

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#384]
##### 版本号：

2.0.2
##### 问题描述：
是不是有一个外层的代码

**Comment by fly1206** [comment]
入口js 在  main.js

**Comment by tyjohn** [comment]
那main.js是哪个页面引用的？应该有个起始的访问页面了吧？还是直接就执行main.js?

**Comment by lanfen100** [comment]
> 那main.js是哪个页面引用的？应该有个起始的访问页面了吧？还是直接就执行main.js?

  main.js   是入口文件哈   main.js  会通过 new Vue().$mount('#app') 挂载到 index.html 的 <div id="app"></div> 上

**Comment by tyjohn** [comment]
> > 那main.js是哪个页面引用的？应该有个起始的访问页面了吧？还是直接就执行main.js?
> 
> main.js 是入口文件哈 main.js 会通过 new Vue().$mount('#app') 挂载到 index.html 的
> 
> 上

想问一下起始的页面在哪，就浏览器输入http://localhost:3000，系统根据什么机制跳到登陆页或者是main.js

**Comment by lanfen100** [comment]
> > > 那main.js是哪个页面引用的？应该有个起始的访问页面了吧？还是直接就执行main.js?
> > 
> > 
> > main.js 是入口文件哈 main.js 会通过 new Vue().$mount('#app') 挂载到 index.html 的
> > 上
> 
> 想问一下起始的页面在哪，就浏览器输入[http://localhost:3000，系统根据什么机制跳到登陆页或者是main.js](http://localhost:3000%EF%BC%8C%E7%B3%BB%E7%BB%9F%E6%A0%B9%E6%8D%AE%E4%BB%80%E4%B9%88%E6%9C%BA%E5%88%B6%E8%B7%B3%E5%88%B0%E7%99%BB%E9%99%86%E9%A1%B5%E6%88%96%E8%80%85%E6%98%AFmain.js)

看这个 官方最近刚刚调整过的
https://github.com/zhangdaiscott/jeecg-boot/commit/29d77c89dfdbec1475ad0f6452ff720f09f17815
