### ISSUE TITLE
自建模块中定义的接口启动之后访问自定义的接口出现404

### ISSUE THREAD

**Issue by techeaven** [zhangdaiscott/jeecg-boot#385]
##### 版本号：
2.0.2

##### 问题描述：
* 自定义了一个module 
* 已在system的pom文件中引入该模块
* parent对应的pom文件中也添加该模块名
* 根据数据库表使用代码生成器生成了接口
问题：
使用postman并带上token值访问接口返回404 截图如下：
##### 截图&代码：
![image](https://user-images.githubusercontent.com/44140173/62457795-140b7b00-b7ae-11e9-9fe0-f51896a7db2e.png)
使用postman测试的结果如下：
![image](https://user-images.githubusercontent.com/44140173/62457851-369d9400-b7ae-11e9-882e-d7e5e7f2dbf6.png)

还请大佬指引一下是不是和我的模块命名有关系或者是我遗漏了什么步骤？？

**Comment by zhangdaiscott** [comment]
你这路径在扫描范围内吗

**Comment by techeaven** [comment]
请问扫描范围的路劲有什么特点？或者我可以在哪找到这部分资料

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
91
