### ISSUE TITLE
eclipse manven打包报错

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#386]
##### 版本号：
2.0.2

##### 问题描述：

Failed to execute goal on project jeecg-boot-module-system: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-module-system:jar:2.0.2: The following artifacts could not be resolved: org.jeecgframework.boot:jeecg-boot-base-common:jar:2.0.2, org.jeecgframework.boot:jeecg-boot-module-worksheet:jar:2.0.2: Failure to find org.jeecgframework.boot:jeecg-boot-base-common:jar:2.0.2 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyun has elapsed or updates are forced -> [Help 1]

我是在system下打的包，这个是什么问题？

**Comment by zhangdaiscott** [comment]
先install parent
