### ISSUE TITLE
nginx配置了servername后，无法访问

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#388]
##### 版本号：
2.02.

##### 问题描述：
127.0.0.1和localhost没问题，但是servername配置了域名后，不能访问

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3033456/62522491-64ddab00-b864-11e9-9996-0bdc6b608124.png)

**Comment by lanfen100** [comment]
> ##### 版本号：
> 2.02.
> 
> ##### 问题描述：
> 127.0.0.1和localhost没问题，但是servername配置了域名后，不能访问
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/3033456/62522491-64ddab00-b864-11e9-9996-0bdc6b608124.png)

你是在本次环境使用了自己定义的一个域名吧
在 hosts 文件中 将你的域名地址指向 127.0.0.1 就行了 
C:Windows\System32\drivers\etc\hosts最后增加 
127.0.0.1 worksheet.qiaoqi1983.com

**Comment by zhangdaiscott** [comment]
http://jeecg-boot.mydoc.io/
JAR部署方案
