### ISSUE TITLE
token大bug，用户登录第一次生成token，即使刷新，也不会带新的请求token，来请求，

### ISSUE THREAD

**Issue by brade080710** [zhangdaiscott/jeecg-boot#389]
##### 截图&代码：if (!JwtUtil.verify(token, userName, passWord)) {
				String newAuthorization = JwtUtil.sign(userName,  passWord);
				redisUtil.set(CommonConstant.PREFIX_USER_TOKEN + token, newAuthorization);
				// 设置超时时间
				redisUtil.expire(CommonConstant.PREFIX_USER_TOKEN + token, JwtUtil.EXPIRE_TIME / 1000);
如图代码，虽然刷新，但是没做token处理，并返回给前端

**Comment by zhangdaiscott** [comment]
你指的是这块的代码吗？这个已经修复了
![image](https://user-images.githubusercontent.com/3162115/62833390-a01b1800-bc70-11e9-8250-e382324fd802.png)
