### ISSUE TITLE
前端路由跳转时query参数丢失

### ISSUE THREAD

**Issue by dongqiusheng** [zhangdaiscott/jeecg-boot#39]
在页面中使用this.$router.push({ path: '/yl/LandMassManager', query: { id } })，在另一个页面接收，发现参数没传过去。打断点发现permission.js中router.beforeEach会进两次，第一次有参数，就二次没有。想问一下为什么会进两次啊

**Comment by dongqiusheng** [comment]
已找到问题，TabLayout.vue文件中
![image](https://user-images.githubusercontent.com/22701497/55457126-88c18380-561b-11e9-9a6c-2fab03dd60c2.png)
没有传入query

**Comment by zhangdaiscott** [comment]
好的，感谢

**Comment by zhangdaiscott** [comment]
具体怎么改？

**Comment by dongqiusheng** [comment]
![image](https://user-images.githubusercontent.com/22701497/56103408-378f8900-5f65-11e9-8bf9-d9f4aaef6419.png)

**Comment by zhangdaiscott** [comment]
非常感谢

**Comment by xiaoshuaishuai319** [comment]
@dongqiusheng 打开两次怎么解决的？

**Comment by xiaoshuaishuai319** [comment]
query:waitRouter.query 竟然加上这个就不存在两次了。
