### ISSUE TITLE
短信验证码，直接放result返回前端了

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#391]
##### 版本号：
2.0.2

##### 问题描述：
发短信验证码接口，验证码直接放了result返回前端了。。。。。。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44466941/62553256-96289c00-b8a1-11e9-935a-057eb48889a2.png)

**Comment by zhangdaiscott** [comment]
没明白你的意思
？？？

**Comment by zhanjunfeng** [comment]
短信验证码怎么能放了结果返回给前端呢？？？我不用看手机，在浏览器里直接看到验证码了，这样的验证码还有什么意义？

**Comment by zhangdaiscott** [comment]
明白了，3Q

**Comment by zhangdaiscott** [comment]
已经处理，下个发布
