### ISSUE TITLE
国际问题：不显示国际化的内容

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#392]
##### 版本号：
2.0.2

##### 问题描述：
不显示国际化的内容
预想： 在登录页面显示 ‘中文’
结果：在登录页面上显示‘lang’
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/62587523-01e82480-b8f5-11e9-8346-0e3f3029b498.png)
![image](https://user-images.githubusercontent.com/52776371/62587564-23e1a700-b8f5-11e9-8fe4-a520ccd965e8.png)
![image](https://user-images.githubusercontent.com/52776371/62587583-365be080-b8f5-11e9-9d8e-cb622760ae14.png)
![image](https://user-images.githubusercontent.com/52776371/62587639-6f945080-b8f5-11e9-8897-3f44f5b23fbe.png)
![image](https://user-images.githubusercontent.com/52776371/62587693-abc7b100-b8f5-11e9-833f-ce30922f7dc3.png)

**Comment by zhangdaiscott** [comment]
默认不支持国际化，需要按照文档手工改造
http://jeecg-boot.mydoc.io/?t=346061
