### ISSUE TITLE
linux服务器导入xls功能失败，

### ISSUE THREAD

**Issue by xuechaoch** [zhangdaiscott/jeecg-boot#393]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/50430358/62587898-6e175800-b8f6-11e9-817f-2fc80f4303fa.png)
![图片](https://user-images.githubusercontent.com/50430358/62587910-740d3900-b8f6-11e9-9fa0-686a203288f2.png)

经过测试是下面这行代码的原因：
`ExcelImportUtil.importExcel(inputStream, RMPPage.class, params);`
这行代码会抛出异常。

**Comment by zhangdaiscott** [comment]
下载autopoi源码，加点日志 手工跟吧，我们没遇到过这个问题
https://github.com/zhangdaiscott/autopoi
