### ISSUE TITLE
前端a-input-number标签的BUG

### ISSUE THREAD

**Issue by alibababa888** [zhangdaiscott/jeecg-boot#394]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/53844772/62589078-aa4cb780-b8fa-11e9-9ba8-b849acf42813.png)
![image](https://user-images.githubusercontent.com/53844772/62589094-b769a680-b8fa-11e9-91be-a5c777acdf7d.png)
![image](https://user-images.githubusercontent.com/53844772/62589136-dd8f4680-b8fa-11e9-9721-6aa7e746dc23.png)
以上是原始代码，并未有初始值，需要改成以下形式。
![image](https://user-images.githubusercontent.com/53844772/62589106-bf294b00-b8fa-11e9-92b7-98fb2aa635e3.png)

**Comment by fly1206** [comment]
非常感谢  已收录

**Comment by zhangdaiscott** [comment]
已经发布了，请更新代码
