### ISSUE TITLE
关于 jeecg-BOOT

### ISSUE THREAD

**Issue by shixingyu42** [zhangdaiscott/jeecg-boot#395]
##### 版本号：
2.0.1

##### 问题描述：
代码生成器生成的 SQL 文不能 满足需求，
直接解析 xml 上的 SQL 速度很慢，页面加载一直报  超时，有什么地方能够优化 前台渲染速度

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53848050/62593782-a2950f00-b90a-11e9-85c7-7afadca0bc55.png)

**Comment by zhangdaiscott** [comment]
多大的数据量？ 具体情况详细说明
自己做过SQL优化吗

**Comment by shixingyu42** [comment]
数据量不大，就只有5000多条记录，SQL文 只有 1秒，但前台加载  6秒以上

**Comment by zhangdaiscott** [comment]
那你得具体看下写的代码了，我们这边10万级数据也很快
