### ISSUE TITLE
开发环境运行正常，将后端以WAR部署到本机tomcat，运行tomact就出错，见截图

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#397]
##### 版本号：
2.0.2

##### 问题描述：
开发环境运行正常，将后端以WAR部署到本机tomcat，运行tomact就出错，见截图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31814666/62605173-1b589300-b92c-11e9-8b28-57e542e6b127.png)

**Comment by gicp** [comment]
![image](https://user-images.githubusercontent.com/31814666/62605326-712d3b00-b92c-11e9-8845-9b6fac61a4b5.png)

**Comment by zhangdaiscott** [comment]
看这个文档
http://jeecg-boot.mydoc.io/?t=345683
