### ISSUE TITLE
发短信的方法sendSms设置了参数templateCode，代码里又写死了

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#398]
##### 版本号：
2.0.2

##### 问题描述：
DySmsHelper中的sendSms方法设置了templateCode参数，但在代码里又写死了，算是个小问题吧

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44466941/62623771-3939ee00-b954-11e9-9017-5e160753d184.png)

**Comment by fly1206** [comment]
非常感謝，已收录

**Comment by fly1206** [comment]
已重构  下个版本发布
