### ISSUE TITLE
代码生成主键能支持自增ID

### ISSUE THREAD

**Issue by theodo123** [zhangdaiscott/jeecg-boot#4]
//表主键策略（目前只支持UUID）
  table.setPrimaryKeyPolicy("uuid");
代码生成主键能支持自增ID就好了，这个都应该有需求吧。@TableId(value = "id", type = IdType.AUTO)

**Comment by zhangdaiscott** [comment]
可以自己改，我们暂时目前支持UUID，方便数据库迁移
