### ISSUE TITLE
j-editable-table 细节问题

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#401]
##### 问题描述：
j-editable-table表格

渲染的下拉框列表 或者多选框 ，无法禁用；
可否增加列禁用功能； 目前只支持行禁用。

或者增加字典翻译功能  属性 ：customRender  

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50865430/62686737-dc900f00-b9f7-11e9-9b98-6d5b6967f12c.png)

**Comment by sjlei** [comment]
列禁用功能已经添加；字典翻译也已经集成在组件里了。以上修改均在下个版本中发布。
