### ISSUE TITLE
ie11兼容问题

### ISSUE THREAD

**Issue by jiahaifeng001** [zhangdaiscott/jeecg-boot#402]
##### 版本号：
4.0

##### 问题描述：
业务申请 -->新增  出差天数出现NAN

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30522255/62688289-24646580-b9fb-11e9-990d-a97b5d470ec1.png)

**Comment by jiahaifeng001** [comment]
表单设计打不开

**Comment by zhangdaiscott** [comment]
你是说IE下，表单设计器打不开吗？
