### ISSUE TITLE
jeecg-boot 能做域验证吗？

### ISSUE THREAD

**Issue by shixingyu42** [zhangdaiscott/jeecg-boot#403]
##### 版本号：
2.0.1

##### 问题描述：

jeecg-boot 能做域验证吗？

**Comment by zhangdaiscott** [comment]
描述的过于简单

**Comment by shixingyu42** [comment]
这个项目 要 域验证的话，是通过 spring-boot + shiro   还是单纯 用 spring-boot 可以
