### ISSUE TITLE
j-editor表单提交时取不到值

### ISSUE THREAD

**Issue by zhichengbohui** [zhangdaiscott/jeecg-boot#407]
##### 截图&代码：
表单代码
`<a-form-item
              :labelCol="labelCol"
              :wrapperCol="wrapperCol"
              label="合同">
              <j-editor  v-decorator="['contract', {}]"
                         name="contract"/>
            </a-form-item>`
引入
`import JEditor from '@/components/jeecg/JEditor'`

`components: {
       JEditor,
      JSearchSelectTag,
    },`
表单赋值
` this.form.setFieldsValue(pick(this.model,  'contract', ))`
表单取值
`/** 整理成formData */
      classifyIntoFormData(allValues) {
        let main = Object.assign(this.model, allValues.formValue)
        console.log("表单参数："+this.main);
        //时间格式化
        main.reserveDate = main.reserveDate ? main.reserveDate.format() : null;
        main.dueDate = main.dueDate ? main.dueDate.format() : null;
        return {
          ...main, // 展开
          wmsReserveDetailedList: allValues.tablesValue[0].values,
        }
      }`

![QQ图片20190809104616](https://user-images.githubusercontent.com/40782576/62750496-f468a100-ba92-11e9-8c7d-956a3827c832.png)
![1](https://user-images.githubusercontent.com/40782576/62769482-ab810e80-bacb-11e9-9666-0c7fa3d1a25f.png)
![2](https://user-images.githubusercontent.com/40782576/62769483-ab810e80-bacb-11e9-8f9a-b7416351695f.png)
![3](https://user-images.githubusercontent.com/40782576/62769486-ab810e80-bacb-11e9-9cbf-f221cfdf3f6a.png)

**Comment by zhichengbohui** [comment]
前段代码是这样的
<j-editor  v-decorator="['contract', {}]"
                         name="contract" />

**Comment by zhichengbohui** [comment]
前端代码是这样的
```
<j-editor  v-decorator="['contract', {}]"
                         name="contract"
              />
```

**Comment by zhangdaiscott** [comment]
代码量有点少，无法判断

**Comment by xinzhexingzhe** [comment]
我这边，对这个组件进行测试了。没有发现你所说的问题。
 <j-editor v-decorator="[ 'msgContent', {} ]"  triggerChange></j-editor>  你可以在组件上加上“triggerChange” 试试

**Comment by xinzhexingzhe** [comment]
<j-editor v-decorator="[ 'msgContent', {} ]"  triggerChange></j-editor>

**Comment by xinzhexingzhe** [comment]
“<j-editor v-decorator="[ 'msgContent', {} ]"  triggerChange></j-editor>”
