### ISSUE TITLE
SecurityUtils.getSubject().getPrincipal() 为null

### ISSUE THREAD

**Issue by xuechaoch** [zhangdaiscott/jeecg-boot#408]
##### 问题描述：项目中获取不到登录用户信息，
使用SecurityUtils.getSubject().getPrincipal()  获取时为null,     

但是在退出登陆的controller里面SecurityUtils.getSubject().getPrincipal() 又不为null.
我现在需要在业务代码中获取到登陆用户信息，请问该 怎样解决

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/50430358/62750902-44943300-ba94-11e9-8bce-7455b202f06f.png)

**Comment by zhangdaiscott** [comment]
退出请求，排除了shiro拦截器了。
不在拦截器控制范围的请求，通过这个方法是获取不到用户信息的。

**Comment by xuechaoch** [comment]
您好，那么请问我现在怎样能获取到当前登录用户

**Comment by xuechaoch** [comment]
> 
> 
> 退出请求，排除了shiro拦截器了。
> 不在拦截器控制范围的请求，通过这个方法是获取不到用户信息的。

您好，那请问 我应该怎样解决，可以说下具体操作吗，我在shiro的配置文件里面也不知道怎样配置

**Comment by xuechaoch** [comment]
> 
> 
> > 退出请求，排除了shiro拦截器了。
> > 不在拦截器控制范围的请求，通过这个方法是获取不到用户信息的。
> 
> 您好，那请问 我应该怎样解决，可以说下具体操作吗，我在shiro的配置文件里面也不知道怎样配置

谢谢了，，我搞定了，

**Comment by zhangdaiscott** [comment]
6.1 通过token获取用户信息方法
   说明： 如果你的请求排除了shiro拦截器，通过6的方式获取不到用户信息，这个时候可以通过token解析获取用户名，通过用户账号查询数据库，获取用户信息。
`org.jeecg.common.system.util.JwtUtil.getUsername(token)`

http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&page=1&extra=#pid21237
