### ISSUE TITLE
关于JTreeSelect，dict希望增加过滤参数

### ISSUE THREAD

**Issue by rubywu** [zhangdaiscott/jeecg-boot#409]
##### 截图&代码：

` <j-tree-select
            style="width: 300px"
            placeholder="请选择上级分类"
            v-decorator="['parentId', {}]"
            dict="pms_product_category,name,id,del_flag=0"
            pidField="parent_id"
          ></j-tree-select>`

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
http://jeecg-boot.mydoc.io/?t=345967
