### ISSUE TITLE
linux环境下mysql区分大小写，但是qrtz_locks表名小写，后台启动报错

### ISSUE THREAD

**Issue by yuxishua** [zhangdaiscott/jeecg-boot#41]
![image](https://user-images.githubusercontent.com/7563822/55771620-63b98e80-5abb-11e9-8691-7a02065532ad.png)
从windows把数据库转移到linux服务器上后，把项目里的数据库连接改成服务器上的地址后，启动时，报错。

**Comment by zhangdaiscott** [comment]
把数据库设置不区分大小写

**Comment by bobolau** [comment]
同样问题，建议SQL语句中修改qrtz相关的表名为大写来处理更好。
SQL参见文件
https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql
