### ISSUE TITLE
能开发一套不用UI框架，只是基于VUE+Springboot的框架系统吗?

### ISSUE THREAD

**Issue by tyjohn** [zhangdaiscott/jeecg-boot#410]
##### 问题描述：

我们许多系统都是按照客户的样式需求美工做好的html+css文件，要切到UI框架肯定不现实，想问问大神能不能整一套前端就是基于VUE的框架系统

**Comment by zhangdaiscott** [comment]
我们不会做这个事情，你们可以把UI重写，不用默认的UI框架。

**Comment by tyjohn** [comment]
谢谢大神
