### ISSUE TITLE
数据权限使用问题

### ISSUE THREAD

**Issue by fatemimipang** [zhangdaiscott/jeecg-boot#412]
##### 版本号：
2.01

##### 问题描述：
数据权限问题

##### 截图&代码：
如果部门属于技术的录入了一条信息,我只想技术自己看到,并且B部门主管能看到技术和行政的,B部门的能看到B部门下所有的,这种怎么配置数据权限.我尝试着配了一下,查询自己部门,和大于等于自己部门等,查询出来的有问题 
![image](https://user-images.githubusercontent.com/51980977/62771985-05380780-bad1-11e9-84b3-da55c9ee3071.png)

**Comment by fatemimipang** [comment]
好像like可以,
修改了部门要重新登录才生效,建议修改时重置缓存.

**Comment by zhangdaiscott** [comment]
是的，只能通过机构编码采用like规则匹配

**Comment by zhangdaiscott** [comment]
你说的修改了部门，指的是修改用户的部门吗？
这个需要退出重新登录的或者刷新首页
