### ISSUE TITLE
新生成的list页面，总是会有面包屑，偶尔又没有，好像跟数据有关？

### ISSUE THREAD

**Issue by David136** [zhangdaiscott/jeecg-boot#413]
##### 版本号：

2.0.2
##### 截图&代码：
![aaaaa](https://user-images.githubusercontent.com/16862623/62820233-e0589880-bb93-11e9-813b-a3f0d363f608.png)

**Comment by zhangdaiscott** [comment]
这跟你配置菜单的上一级的前端组件配置有关
![image](https://user-images.githubusercontent.com/3162115/62820937-bb1d5780-bb9e-11e9-9dbe-e4a2bb2e7016.png)

**Comment by keith-ch** [comment]
@zhangdaiscott 大佬，我也碰到这个问题，能说的更明白一些吗？
上一级菜单怎么样配置可以去掉面包屑？
前端组件不配置成layouts/RouteView的话，那配置成什么呢？
多谢多谢！
