### ISSUE TITLE
页面列表查询字段是string,都是模糊查询

### ISSUE THREAD

**Issue by chengtg** [zhangdaiscott/jeecg-boot#414]
版本号：2.0.2
问题描述：查询器中针对查询字段对应的java类型为String，全默认设置了模糊查询
截图&代码：
![image](https://user-images.githubusercontent.com/13086930/62829160-23fde180-bc2a-11e9-88ec-f64dab089664.png)

产生问题影响：在查询列表的时候，如查询控件是数据字典或者下拉树，查询最终条件都拼接成like，结果肯定是错误
![image](https://user-images.githubusercontent.com/13086930/62829274-9c65a200-bc2c-11e9-879a-951d2d7335a6.png)

![image](https://user-images.githubusercontent.com/13086930/62829271-92dc3a00-bc2c-11e9-84d8-152e91a54602.png)

解决方案：
    1.修改去掉查询器的string类型字段默认模糊查询，同时后台业务逻辑处理，如查询列表的时候，添加map，map中设置要模糊查询的字段，如{'name','like'},然后再修改接受的entity参数，修改为name的value为‘*‘+ctg+’*’
   2.封装a-input插件，组成一个模糊查询插件，这个插件最终目的是将input值，变为*input值*传递给后台

**Comment by fly1206** [comment]
非常感谢  已收录

**Comment by zhangdaiscott** [comment]
已经修复，
新版会提供一个模糊查询组件 ： src/components/jeecg/JInput.vue
