### ISSUE TITLE
定时任务

### ISSUE THREAD

**Issue by zhl19911203** [zhangdaiscott/jeecg-boot#415]
##### 版本号：
2.0.2

##### 问题描述：
本地有几个应用连着同一个数据库，并且同时启动了好几个定时任务，这样启动之后一会自己就停止了，不稳定，并且只能起来一个或者几个，不能全部正常运行，qrtz_triggers表的TRIGGER_STATE字段显示为ERROR

**Comment by zhangdaiscott** [comment]
你应该只留一个应用跑定时任务，其他的不开启定时任务。
因为目前定时任务不是分布式的
