### ISSUE TITLE
service层使用cachable

### ISSUE THREAD

**Issue by futurOR** [zhangdaiscott/jeecg-boot#419]
##### 版本号：
2.0.0

##### 问题描述：
试图通过service层添加redis缓存时，尝试使用wrapper.getSqlSegment，发现似乎是用了Spel表达式：
object_code LIKE #{ew.paramNameValuePairs.MPGENVAL1} ORDER BY create_time DESC , object_code ASC
这个like后的值无法作为查询条件判断，无法做redis中的key，是否有其他选项能够作为key？
##### 截图&代码：
![image](https://user-images.githubusercontent.com/10953765/62872775-c1ebcc00-bd50-11e9-9ab9-dc7359129ca8.png)

**Comment by fly1206** [comment]
建议把这个方法实现写到mapper类里面  然后在service方法里面另外封装方法对象参数  调用mapper类里的方法  然后在该service方法上增加缓存注解

**Comment by futurOR** [comment]
理解了，也是一种不错的方案！不过我已经写了一种了.....勉强可以用
新增一个keyGenerator
把sqlSegment+namedValuePair一同写入key，同时带上Ipage信息，否则排序也会出问题
`@Bean
	public static KeyGenerator wrapperKeyGenerator() {
		return new KeyGenerator() {
			@Override
			public Object generate(Object target, Method method, Object... params) {
				StringBuffer sb = new StringBuffer();
				for (Object obj : params) {
					if (obj instanceof QueryWrapper){
						QueryWrapper queryWrapper = (QueryWrapper) obj;
						String sql = queryWrapper.getSqlSegment();
						Map<String,Object> pairs = queryWrapper.getParamNameValuePairs();
						sb.append("sql:");
						sb.append(sql);
						sb.append("-");
						sb.append("params:");
						sb.append(pairs.toString());
					}
					else if (obj instanceof IPage){
						IPage page = (IPage) obj;
						long current = page.getCurrent();
						long size = page.getSize();
						sb.append("currentPage:");
						sb.append(current);
						sb.append("pageSize:");
						sb.append(size);
						sb.append("-");
					}
				}
				return sb.toString();
			}
		};
	}`
![image](https://user-images.githubusercontent.com/10953765/63006913-338f5b80-beb2-11e9-97c0-17e1375b040f.png)

**Comment by fly1206** [comment]
嗯嗯  都可以  在不改造原有方法上可以这么处理
