### ISSUE TITLE
edge浏览器

### ISSUE THREAD

**Issue by SenbeiSAMA** [zhangdaiscott/jeecg-boot#420]

**Comment by zhangdaiscott** [comment]
那个功能？ 请详细说明

**Comment by SenbeiSAMA** [comment]
> 那个功能？ 请详细说明
我们加截图整理了一个文档，方便的话请您看一下吧。
[github.docx](https://github.com/zhangdaiscott/jeecg-boot/files/3495429/github.docx)

**Comment by SenbeiSAMA** [comment]
> 那个功能？ 请详细说明

您好，我们放Edge兼容后打成jar包部署到服务器后访问，Edge却兼容了，除了按F12会拒绝访问外，没有以上问题了，看来是开发环境的问题大概。感谢您的作品。

**Comment by zhangdaiscott** [comment]
ok
