### ISSUE TITLE
checkbox 取行号

### ISSUE THREAD

**Issue by shixingyu42** [zhangdaiscott/jeecg-boot#421]
##### 版本号：
2.0.1

##### 问题描述：
有什么方法可以不通过id后台获取，而是通过checkbox直接获取当前元选中行的记录

或者说  selectedRowKeys  如何取到 当前 行号（不走后台）

**Comment by shixingyu42** [comment]
使用 j-editable-table 的时候需要 批量更新，因为 j-editable-table 改完 是 不跟后台交互的，没有存到数据库，现在就是想  把修改后的内容，批量存到数据库

**Comment by tcfly** [comment]
@shixingyu42 常见案例-->JEditableTable 示例,代码里也有readme

**Comment by shixingyu42** [comment]
@tcfly 代码里的readme我看过了，他取得 rowids 都是  id值啊，我现在要取的 是 行号(index) 啊

**Comment by shixingyu42** [comment]
只能取 id 然后遍历 data，行号 不存在
