### ISSUE TITLE
系统管理-用户管理，编辑用户资料bug

### ISSUE THREAD

**Issue by haojing8312** [zhangdaiscott/jeecg-boot#422]
##### 版本号：
2.0.2

##### 问题描述：
号码为*的用户删除以后（逻辑删除），重复校验接口并未剔除该用户，无法新增编辑相同号码用户。

**Comment by fly1206** [comment]
一般不建议删除 系统可能存在相关联的历史数据    建议禁用或冻结用户   用户名称一旦入库  不允许重复

**Comment by zhangdaiscott** [comment]
可以按照自己的项目需求，把逻辑删除改成真实删除。
我们没办法照顾全部的场景
