### ISSUE TITLE
jeecg-boot的代码生成器，怎么生成不是驼峰标识的实体

### ISSUE THREAD

**Issue by sotier** [zhangdaiscott/jeecg-boot#424]
请问大佬：

jeecg-boot的代码生成器，怎么生成不是驼峰标识的实体

在哪里配置

**Comment by zhangdaiscott** [comment]
请截图

**Comment by sotier** [comment]
请问大佬：

jeecg-boot的代码生成器，怎么生成不是驼峰标识的实体

在哪里配置
-------

我的意思是，比如字段名是user_name现在代码生成器生成的实体是:
private String userName;

能不能生成和数据字段名一样的实体属性名，如下：
private String user_name;

**Comment by zhangdaiscott** [comment]
这样不专业，正常编码都是驼峰写法
