### ISSUE TITLE
前端a-select标签使用有问题，模糊搜索不对

### ISSUE THREAD

**Issue by alibababa888** [zhangdaiscott/jeecg-boot#425]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/53844772/63138799-60588580-c00e-11e9-9bfa-703f1fbec227.png)
![image](https://user-images.githubusercontent.com/53844772/63138810-69495700-c00e-11e9-8735-ee402e2c96eb.png)
根据名称模糊搜索没有任何结果
![image](https://user-images.githubusercontent.com/53844772/63138829-7c5c2700-c00e-11e9-99dc-fdddca6b600e.png)
反而能够根据id能够模糊搜索。
解决方案:需要增加配置
![image](https://user-images.githubusercontent.com/53844772/63138889-ad3c5c00-c00e-11e9-89ae-6bfc24fdd4cf.png)

**Comment by fly1206** [comment]
非常感谢   已收录

**Comment by zhangdaiscott** [comment]
已经发布
