### ISSUE TITLE
微服务开发下建议在jeecg.yaml中增加projectpath参数

### ISSUE THREAD

**Issue by reltian** [zhangdaiscott/jeecg-boot#4251]
##### 问题描述：
否则会在jar包的目录下自动生成E:\workspace\jeecg-boot目录，这个在Linux环境里会报错。
或者在Online表单开发中，增加一个默认生成路径的设置。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28427965/202656974-c91c92a7-ea06-48e9-ab94-37e593ef8538.png)

![image](https://user-images.githubusercontent.com/28427965/202657102-fde73a03-9d02-4e65-b5d2-35c101ca5535.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jeecg-module-system/jeecg-system-start\jeecg\jeecg_config.properties

修改这个，不支持你说的哪个文件

**Comment by reltian** [comment]
我觉得能在系统里配置的尽量不用配置文件，用配置文件的尽量在一个文件里解决，大概有点完美主义。
