### ISSUE TITLE
excel导入，要本地开发环境正常，但是部署到服务器后运行就出错

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#427]
##### 版本号：
2.0.2

##### 问题描述：
excel导入，要本地开发环境正常，但是部署到服务器后运行就出错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31814666/63150142-9f9bcc00-c038-11e9-913c-e57d8b0ecb7c.png)

**Comment by gicp** [comment]
刚才我去服务器上执行导入就可以成功。
由此问题描述改为：excle导入功能为何只能在nginx服务器本机才能成功？

**Comment by zhangdaiscott** [comment]
有错误日志吗

**Comment by gicp** [comment]
![image](https://user-images.githubusercontent.com/31814666/63236381-0e169f00-c270-11e9-8c39-59e112c4fa4b.png)

**Comment by zhangdaiscott** [comment]
你确认你nginx配置的对吗，这是本地应用，不是另外的服务器吧

![image](https://user-images.githubusercontent.com/3162115/63408813-6ee5d900-c422-11e9-9749-80127f0aeab0.png)
