### ISSUE TITLE
希望菜单能配置外链，直接弹出新页面而不是嵌入iframe

### ISSUE THREAD

**Issue by chengyu2333** [zhangdaiscott/jeecg-boot#428]

**Comment by fly1206** [comment]
弹出的话  就不在当前系统里面了   直接浏览器新开窗口了   如果你们需要 可以修改src/components/layouts/IframePageView.vue 这个页面

**Comment by chengyu2333** [comment]
修改后可以弹了，但会打开个空白tab，如何将这个tab关闭呢？

**Comment by zhangdaiscott** [comment]
此问题已经修复，下个版本发布
