### ISSUE TITLE
updateBatchById 批量更新失败

### ISSUE THREAD

**Issue by yuxishua** [zhangdaiscott/jeecg-boot#43]
![image](https://user-images.githubusercontent.com/7563822/55927093-5ed51600-5c46-11e9-8ba2-199c51914be8.png)
构造了一个List<Product> listProduct ,然后调用productService.updateBatchById(listProduct ),就报这个错，
问题原因是：com.baomidou.mybatisplus.extension.service.impl.ServiceImpl 243行中，构建参数param时， 只构建了一个key=et 的元素，应该还有一个key = param1的元素，可惜代码没有，不知道问题出在哪？

**Comment by zhangdaiscott** [comment]
这个底层用mybatis plus
