### ISSUE TITLE
多标签页模式bug

### ISSUE THREAD

**Issue by jasonto87** [zhangdaiscott/jeecg-boot#430]
在多标签页模式下，打开任意超过三个页面，再回到主页的时候，页面上图表消失，变为空白。

**Comment by tcfly** [comment]
@jasonto87  能说明下怎么复现么(开发环境,浏览器等)

**Comment by jasonto87** [comment]
@tcfly 在页面上选择“多标签页模式”，然后再依次新点击打开任意两个或多个新标签页，此时再点击”首页”标签页，就发现之前可以显示的图表变成一片空白，浏览器刷新后可正常显示。   此问题仅出现在“首页”标签页，其他新打开的标签页切换的时候感觉会自动刷新，所以没这个问题。  使用浏览器是chrome76.0，在firefox和IE下均存在这个问题，应该与浏览器无关

**Comment by tcfly** [comment]
@jasonto87 [看下这个issue](https://github.com/viserjs/viser/issues/55)

**Comment by tcfly** [comment]
@jasonto87 [这个issue可以暂时给出解决方案](https://github.com/viserjs/viser/issues/275),TabLayout组件,加个页签回调函数,触发一下resize事件

**Comment by tcfly** [comment]
其实ant-design 官方不推荐使用多页签

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
