### ISSUE TITLE
24小时制问题

### ISSUE THREAD

**Issue by ylz201** [zhangdaiscott/jeecg-boot#434]
##### 版本号：
2

##### 问题描述：
			默认是12小时制，导致数据时间错乱
 

##### 截图&代码：
		QueryGenerator 49行	time = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

应该是			time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

**Comment by zhangdaiscott** [comment]
3Q，已修复，下个版本发布！
