### ISSUE TITLE
代码生成器无法生成文件

### ISSUE THREAD

**Issue by neelee** [zhangdaiscott/jeecg-boot#435]
##### 版本号：
2.0.1

##### 问题描述：
代码生成器好像都运转正常，但是无法根据配置生成文件

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2560440/63335283-aba4c800-c36f-11e9-8eba-6cf111297b20.png)

**Comment by zhangdaiscott** [comment]
什么配置文件？

**Comment by neelee** [comment]
> 什么配置文件？

1、 jeecg-boot-module-system/src/main/resources/jeecg/jeecg_config.properties  按照相应的文档介绍配置的
2、最主要的是无法根据代码生成器生成文件

**Comment by zhangdaiscott** [comment]
你代码生成的路径对吗，后台没报错说明生成成功 了

**Comment by neelee** [comment]
> 你代码生成的路径对吗，后台没报错说明生成成功 了
您看我的配置文件是否正确
![image](https://user-images.githubusercontent.com/2560440/63416933-fa676600-c432-11e9-9b8b-1815bcda79a9.png)

**Comment by neelee** [comment]
> 你代码生成的路径对吗，后台没报错说明生成成功 了

目前是没有找到生成的文件在哪

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/63417933-cd1bb780-c434-11e9-8636-a189b2561323.png)

这个里面没有？

**Comment by zhangdaiscott** [comment]
你去QQ群交流284271917吧，这个应该是用法不对

**Comment by hairongxiaohao** [comment]
我也是这个问题,楼主解决了吗

**Comment by neelee** [comment]
> 我也是这个问题,楼主解决了吗

解决了，升级到2.0.2就可以了，我一直用的是2.0.1估计有bug
