### ISSUE TITLE
>Token失效，请重新登录!

### ISSUE THREAD

**Issue by littlecheng** [zhangdaiscott/jeecg-boot#4364]
> 
这个不算是部署问题，我自己写了个后台，部署到服务器上，小程序就能访问服务器接口；而用jeecg代码部署，小程序访问就是401.

_Originally posted by @littlecheng in https://github.com/jeecgboot/jeecg-boot/issues/4352#issuecomment-1336654194_

**Comment by zhangdaiscott** [comment]
不清楚你具体如何配置，没办法帮你

**Comment by littlecheng** [comment]
你们程序有bug把，我在ShrioConfig加了过滤接口根本不起作用。在配置文件里加了过滤接口才起作用。终于不再401了。
jeecg:
  shiro:
    excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**,/api/v1/nx/plan/**&nbsp;


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] &gt;Token失效，请重新登录! (Issue #4364)





 
不清楚你具体如何配置，没办法帮你

**Comment by zhangdaiscott** [comment]
你加的对吗

**Comment by 1369521908** [comment]
可以参考下解决方法
https://github.com/jeecgboot/jeecg-boot/issues/4786
