### ISSUE TITLE
a-select 手动赋值选中问题

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#438]
##### 版本号：
2.0.2

##### 问题描述：
查询条件 a-select 标签中 通过v-model 绑定 queryParam.provId 值时， 在代码中手动改变 queryParam.provId=‘’ 值后， 再去选则其他下拉值时，下拉框值未改变； 但点击查询后 选中的值才会显示在select中

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/50865430/63409220-50cca880-c423-11e9-94df-fac96ab99131.png)
![图片](https://user-images.githubusercontent.com/50865430/63409305-7bb6fc80-c423-11e9-875a-599103a0a2e5.png)

**Comment by fly1206** [comment]
您好，没有重现该问题，可以参考【常用示例--内嵌table】查询条件中a-select的使用
