### ISSUE TITLE
代码生成器table.setTableName，表名小写，会查询不到数据

### ISSUE THREAD

**Issue by leemoncn** [zhangdaiscott/jeecg-boot#44]
table.setTableName的表名是小写，但是在DbReadTableUtil里面，查询information_schema表的时候，拼接的where table_name =会自动转成大写，导致找不到数据

**Comment by leemoncn** [comment]
会提示  该表不存在或者表中没有字段

**Comment by zhangdaiscott** [comment]
把mysql设置成不区分大小写
