### ISSUE TITLE
列表页高级查询建议增加下拉选择的查询

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#441]

**Comment by wjxjasin** [comment]
![image](https://user-images.githubusercontent.com/49051702/63422848-bcbc0a80-c43d-11e9-938f-b40030015bc5.png)

**Comment by wjxjasin** [comment]
![image](https://user-images.githubusercontent.com/49051702/63423054-16bcd000-c43e-11e9-9424-cdd0d4d08824.png)
唯独缺少下拉框的高级查询

**Comment by zhangdaiscott** [comment]
下拉取值，从那取呢？ 字典吗

**Comment by wjxjasin** [comment]
对



------------------ 原始邮件 ------------------
发件人: "JEECG开源社区"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 上午10:15
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>; 
抄送: "jasin"<wjxjasin@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeecg-boot] 列表页高级查询建议增加下拉选择的查询 (#441)




下拉取值，从那取呢？ 字典吗

**Comment by zhangdaiscott** [comment]
好的，我们看看

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
