### ISSUE TITLE
autopoi-web 导入图片字段时无法指定保存路径

### ISSUE THREAD

**Issue by cdsuifeng** [zhangdaiscott/jeecg-boot#4415]
##### 版本号：
3.1.0
autopoi-web : 1.3.9
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
@excel 导入图片时，指定savePath 参数无效，始终都是  import 路径。切换autopoi-web版本1.4.5 也无效。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23712951/207565030-6a08ec8c-751e-4218-8001-d3c7ab7f2471.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
