### ISSUE TITLE
主子表分开维护，生成的代码子表的分页每次查询都是全部，怎么样改成后台真是分页？

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#442]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/42332606/63479933-a0ae7c80-c4c2-11e9-83a6-7c46a91a00f9.png)

**Comment by zhangdaiscott** [comment]
页面用的是哪个模板？ 子表没有分页吗

**Comment by RhineDream** [comment]
> 页面用的是哪个模板？ 子表没有分页吗

主子表分开维护的模板，应该是one2
![image](https://user-images.githubusercontent.com/42332606/63671137-535b4380-c811-11e9-8757-59989cedf186.png)
，jeecg前台是做了分页，但是每次点击下一页，都是根据主表id查询所有的子表相关数据。应该就是后台没处理，只在前台处理的

**Comment by zhangdaiscott** [comment]
发现了，我们尽快修复

**Comment by zhangdaiscott** [comment]
问题修复了，下个版本发布

**Comment by RhineDream** [comment]
> 问题修复了，下个版本发布
您好，下个版本啥时候发布呢？因为我们的项目一直在开发，这一块问题也是想尽快解决的
