### ISSUE TITLE
主子表分开维护，主表字典@DICT可以用，子表字段@DICT不生效，这个是不是bug？

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#443]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/42332606/63480098-377b3900-c4c3-11e9-952c-f86d88429969.png)
主表
![image](https://user-images.githubusercontent.com/42332606/63480118-482baf00-c4c3-11e9-866e-97d6494de2c3.png)
子表
![image](https://user-images.githubusercontent.com/42332606/63480124-511c8080-c4c3-11e9-8ddb-1b038c4e830a.png)
代码完全一样，就是不生效，子表接口返回的都没有_dictText字段
字典表的值都不能用

**Comment by RhineDream** [comment]
我对@dict进行改造以后可以实现子表的字典值转换了，修改是这样的
![image](https://user-images.githubusercontent.com/42332606/63481937-904dd000-c4c9-11e9-92ab-0b89355d56dd.png)
但是能不能用一个更优雅的方式实现呢？建议比如做成一个注解？在需要转换的方法上，加上注解

**Comment by fly1206** [comment]
有两种方案
第一种方案实体中使用注解的，
可以修改controller的返回值，返回Result<IPage<?>>  对象 例如下面的方法
`
/**
     * 通过id查询
     *
     * @param mainId
     * @return
     */
    @GetMapping(value = "/listOrderCustomerByMainId")
    public Result<IPage<JeecgOrderCustomer>> queryOrderCustomerListByMainId(@RequestParam(name = "mainId", required = false) String mainId) {
        Result<IPage<JeecgOrderCustomer>> result = new Result<IPage<JeecgOrderCustomer>>();
        // TODO
        IPage<JeecgOrderCustomer> pageList = new Page<JeecgOrderCustomer>();
        List<JeecgOrderCustomer> jeecgOrderCustomerList = null;
        if (mainId != null) {
            jeecgOrderCustomerList = jeecgOrderCustomerService.selectCustomersByMainId(mainId);
            pageList.setRecords(jeecgOrderCustomerList);
            result.setResult(pageList);
            result.setSuccess(true);
            return result;
        } else {
			return null;
		}
    }
`

然后前端更改

`
this.dataSource = res.result.records;
`

字段修改
`
dataIndex: 'sex_dictText'
`

**Comment by fly1206** [comment]
第二种方案，实体中不使用注解的，再前端处理字段字段
# JDictSelectUtil.js 列表字典函数用法
----

- 第一步: 引入依赖方法
```html
       import {initDictOptions, filterDictText} from '@/components/dict/JDictSelectUtil'
```

- 第二步: 在created()初始化方法执行字典配置方法
```html
      //初始化字典配置
      this.initDictConfig();
```
      
- 第三步: 实现initDictConfig方法，加载列表所需要的字典(列表上有多个字典项，就执行多次initDictOptions方法)
      
```html
      initDictConfig() {
        //初始化字典 - 性别
        initDictOptions('sex').then((res) => {
          if (res.success) {
            this.sexDictOptions = res.result;
          }
        });
      },
```
      
- 第四步: 实现字段的customRender方法
```html
     customRender: (text, record, index) => {
       //字典值替换通用方法
       return filterDictText(this.sexDictOptions, text);
     }
```

**Comment by RhineDream** [comment]
> 第二种方案，实体中不使用注解的，再前端处理字段字段
> 
> # JDictSelectUtil.js 列表字典函数用法
> * 第一步: 引入依赖方法
> 
> ```
>        import {initDictOptions, filterDictText} from '@/components/dict/JDictSelectUtil'
> ```
> 
> * 第二步: 在created()初始化方法执行字典配置方法
> 
> ```
>       //初始化字典配置
>       this.initDictConfig();
> ```
> 
> * 第三步: 实现initDictConfig方法，加载列表所需要的字典(列表上有多个字典项，就执行多次initDictOptions方法)
> 
> ```
>       initDictConfig() {
>         //初始化字典 - 性别
>         initDictOptions('sex').then((res) => {
>           if (res.success) {
>             this.sexDictOptions = res.result;
>           }
>         });
>       },
> ```
> 
> * 第四步: 实现字段的customRender方法
> 
> ```
>      customRender: (text, record, index) => {
>        //字典值替换通用方法
>        return filterDictText(this.sexDictOptions, text);
>      }
> ```

收到，万分感谢
