### ISSUE TITLE
条件搜索，要搜的字段在关联的两张表里都有，这时候数据库会报错，如何处理？

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#444]
##### 截图&代码：
前台页面
![image](https://user-images.githubusercontent.com/42332606/63483647-abbbd980-c4cf-11e9-882c-62ab072fd44c.png)
controller
![image](https://user-images.githubusercontent.com/42332606/63483671-c5f5b780-c4cf-11e9-9b6e-bfa550595db5.png)
service
![image](https://user-images.githubusercontent.com/42332606/63483681-d0b04c80-c4cf-11e9-81d1-e8f4f920dabe.png)
service实现类
![image](https://user-images.githubusercontent.com/42332606/63483697-ddcd3b80-c4cf-11e9-8649-74e23212e54e.png)
dao
![image](https://user-images.githubusercontent.com/42332606/63483712-e6be0d00-c4cf-11e9-98bb-50fa3b1fe40a.png)
xml
![image](https://user-images.githubusercontent.com/42332606/63483832-36043d80-c4d0-11e9-9a00-d9bdb8c6cd0f.png)

就是想让这个条件查询可以使用，求助大佬，困扰好几天了

**Comment by zhang0001** [comment]
可以改写 QueryGenerator ，拼装条件的时候加上表名

**Comment by tygithub1** [comment]
了解！后期改造

**Comment by fly1206** [comment]
QueryGenerator  可以使用  apply 拼接sql实现, 
参照官方使用说明https://mp.baomidou.com/guide/wrapper.html#apply
