### ISSUE TITLE
生产环境如下：nginx和tomcat在同一台电脑,此台电脑有内网IP和外网IP； 问题如下：无论内网IP或外网IP，程序都能正常运行，但有一点：导入功能在内网IP正常，但在 外网IP下就是不行，出错如下

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#449]
##### 版本号：
2.0.2

##### 问题描述
生产环境如下：nginx和tomcat在同一台电脑,此台电脑有内网IP和外网IP；
问题如下：无论内网IP或外网IP，程序都能正常运行，但有一点：导入功能在内网IP正常，但在
外网IP下就是不行，出错如下：

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31814666/63678876-b43f4780-c822-11e9-9044-bc14c5e0a85b.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/63680187-a9d27d00-c825-11e9-8fc7-62e160c2f9a7.png)
外网访问端口开了吗

**Comment by gicp** [comment]
开了，外网正常运行，唯有每个窗口的导入功能不行

**Comment by zhangdaiscott** [comment]
就没进入后台？

**Comment by gicp** [comment]
nginx和tomcat在同一台电脑，下面是nginx配置，指向这台电脑内部IP:172.16.100.15,你看看配置有没有问题。
![image](https://user-images.githubusercontent.com/31814666/63698376-4bbb8f00-c851-11e9-8ce5-ac55d5328e25.png)

![image](https://user-images.githubusercontent.com/31814666/63698282-2169d180-c851-11e9-8de2-29c341ea1e7d.png)

**Comment by gicp** [comment]
有没有解决方法啊？

**Comment by zhangdaiscott** [comment]
访问你这个地址，不通
![image](https://user-images.githubusercontent.com/3162115/63784227-ea62f100-c920-11e9-9367-8f778b154605.png)

**Comment by klniu** [comment]
这种情况是因为window._CONFIG['domianURL']设置成内网原因吧，我建议你在导入时，动态把window._CONFIG['domianURL']根据用户访问的网站替换成相应的内网或外网地址
