### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by z469441432** [zhangdaiscott/jeecg-boot#45]
"C:\Program Files\Java\jdk1.8.0_161\bin\java" "-javaagent:E:\IntelliJ IDEA 2017.3.2\lib\idea_rt.jar=59010:E:\IntelliJ IDEA 2017.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_161\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_161\jre\lib\rt.jar;G:\jeecg-boot-master\jeecg-boot\target\classes;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-web\2.0.3.RELEASE\spring-boot-starter-web-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter\2.0.3.RELEASE\spring-boot-starter-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot\2.0.3.RELEASE\spring-boot-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-logging\2.0.3.RELEASE\spring-boot-starter-logging-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;E:\maven\MavenRepository\maven_jar\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;E:\maven\MavenRepository\maven_jar\org\apache\logging\log4j\log4j-to-slf4j\2.10.0\log4j-to-slf4j-2.10.0.jar;E:\maven\MavenRepository\maven_jar\org\apache\logging\log4j\log4j-api\2.10.0\log4j-api-2.10.0.jar;E:\maven\MavenRepository\maven_jar\org\slf4j\jul-to-slf4j\1.7.25\jul-to-slf4j-1.7.25.jar;E:\maven\MavenRepository\maven_jar\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;E:\maven\MavenRepository\maven_jar\org\yaml\snakeyaml\1.19\snakeyaml-1.19.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-json\2.0.3.RELEASE\spring-boot-starter-json-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.9.6\jackson-datatype-jdk8-2.9.6.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.9.6\jackson-datatype-jsr310-2.9.6.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.6\jackson-module-parameter-names-2.9.6.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-tomcat\2.0.3.RELEASE\spring-boot-starter-tomcat-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\apache\tomcat\embed\tomcat-embed-core\8.5.31\tomcat-embed-core-8.5.31.jar;E:\maven\MavenRepository\maven_jar\org\apache\tomcat\embed\tomcat-embed-el\8.5.31\tomcat-embed-el-8.5.31.jar;E:\maven\MavenRepository\maven_jar\org\apache\tomcat\embed\tomcat-embed-websocket\8.5.31\tomcat-embed-websocket-8.5.31.jar;E:\maven\MavenRepository\maven_jar\org\hibernate\validator\hibernate-validator\6.0.10.Final\hibernate-validator-6.0.10.Final.jar;E:\maven\MavenRepository\maven_jar\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-web\5.0.7.RELEASE\spring-web-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-beans\5.0.7.RELEASE\spring-beans-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-webmvc\5.0.7.RELEASE\spring-webmvc-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-expression\5.0.7.RELEASE\spring-expression-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-mail\2.0.3.RELEASE\spring-boot-starter-mail-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-context\5.0.7.RELEASE\spring-context-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-context-support\5.0.7.RELEASE\spring-context-support-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\com\sun\mail\javax.mail\1.6.1\javax.mail-1.6.1.jar;E:\maven\MavenRepository\maven_jar\javax\activation\activation\1.1\activation-1.1.jar;E:\maven\MavenRepository\maven_jar\net\bytebuddy\byte-buddy\1.7.11\byte-buddy-1.7.11.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-core\5.0.7.RELEASE\spring-core-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-jcl\5.0.7.RELEASE\spring-jcl-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-aop\2.0.3.RELEASE\spring-boot-starter-aop-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-aop\5.0.7.RELEASE\spring-aop-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\aspectj\aspectjweaver\1.8.13\aspectjweaver-1.8.13.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-actuator\2.0.3.RELEASE\spring-boot-starter-actuator-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-actuator-autoconfigure\2.0.3.RELEASE\spring-boot-actuator-autoconfigure-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-actuator\2.0.3.RELEASE\spring-boot-actuator-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\io\micrometer\micrometer-core\1.0.5\micrometer-core-1.0.5.jar;E:\maven\MavenRepository\maven_jar\org\hdrhistogram\HdrHistogram\2.1.10\HdrHistogram-2.1.10.jar;E:\maven\MavenRepository\maven_jar\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;E:\maven\MavenRepository\maven_jar\commons-io\commons-io\2.6\commons-io-2.6.jar;E:\maven\MavenRepository\maven_jar\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-freemarker\2.0.3.RELEASE\spring-boot-starter-freemarker-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\freemarker\freemarker\2.3.28\freemarker-2.3.28.jar;E:\maven\MavenRepository\maven_jar\org\projectlombok\lombok\1.16.22\lombok-1.16.22.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus-boot-starter\3.0.6\mybatis-plus-boot-starter-3.0.6.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus\3.0.6\mybatis-plus-3.0.6.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus-extension\3.0.6\mybatis-plus-extension-3.0.6.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus-core\3.0.6\mybatis-plus-core-3.0.6.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus-annotation\3.0.6\mybatis-plus-annotation-3.0.6.jar;E:\maven\MavenRepository\maven_jar\com\github\jsqlparser\jsqlparser\1.2\jsqlparser-1.2.jar;E:\maven\MavenRepository\maven_jar\org\mybatis\mybatis-spring\1.3.2\mybatis-spring-1.3.2.jar;E:\maven\MavenRepository\maven_jar\org\mybatis\mybatis\3.4.6\mybatis-3.4.6.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\mybatis-plus-generator\3.0.6\mybatis-plus-generator-3.0.6.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-autoconfigure\2.0.3.RELEASE\spring-boot-autoconfigure-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-jdbc\2.0.3.RELEASE\spring-boot-starter-jdbc-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\com\zaxxer\HikariCP\2.7.9\HikariCP-2.7.9.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-jdbc\5.0.7.RELEASE\spring-jdbc-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-configuration-processor\2.0.3.RELEASE\spring-boot-configuration-processor-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\com\alibaba\druid-spring-boot-starter\1.1.10\druid-spring-boot-starter-1.1.10.jar;E:\maven\MavenRepository\maven_jar\com\alibaba\druid\1.1.10\druid-1.1.10.jar;E:\maven\MavenRepository\maven_jar\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;E:\maven\MavenRepository\maven_jar\com\baomidou\dynamic-datasource-spring-boot-starter\2.5.0\dynamic-datasource-spring-boot-starter-2.5.0.jar;E:\maven\MavenRepository\maven_jar\com\alibaba\fastjson\1.2.35\fastjson-1.2.35.jar;E:\maven\MavenRepository\maven_jar\mysql\mysql-connector-java\5.1.46\mysql-connector-java-5.1.46.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-quartz\2.0.3.RELEASE\spring-boot-starter-quartz-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-tx\5.0.7.RELEASE\spring-tx-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\quartz-scheduler\quartz\2.3.0\quartz-2.3.0.jar;E:\maven\MavenRepository\maven_jar\com\mchange\mchange-commons-java\0.2.11\mchange-commons-java-0.2.11.jar;E:\maven\MavenRepository\maven_jar\com\auth0\java-jwt\3.4.1\java-jwt-3.4.1.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\core\jackson-databind\2.9.6\jackson-databind-2.9.6.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\jackson\core\jackson-core\2.9.6\jackson-core-2.9.6.jar;E:\maven\MavenRepository\maven_jar\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-spring-boot-starter\1.4.0-RC2\shiro-spring-boot-starter-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-spring\1.4.0-RC2\shiro-spring-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-core\1.4.0-RC2\shiro-core-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-lang\1.4.0-RC2\shiro-lang-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-cache\1.4.0-RC2\shiro-cache-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-crypto-hash\1.4.0-RC2\shiro-crypto-hash-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-crypto-core\1.4.0-RC2\shiro-crypto-core-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-crypto-cipher\1.4.0-RC2\shiro-crypto-cipher-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-config-core\1.4.0-RC2\shiro-config-core-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-config-ogdl\1.4.0-RC2\shiro-config-ogdl-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar;E:\maven\MavenRepository\maven_jar\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-event\1.4.0-RC2\shiro-event-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\org\apache\shiro\shiro-web\1.4.0-RC2\shiro-web-1.4.0-RC2.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-swagger2\2.9.2\springfox-swagger2-2.9.2.jar;E:\maven\MavenRepository\maven_jar\io\swagger\swagger-annotations\1.5.20\swagger-annotations-1.5.20.jar;E:\maven\MavenRepository\maven_jar\io\swagger\swagger-models\1.5.20\swagger-models-1.5.20.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-spi\2.9.2\springfox-spi-2.9.2.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-core\2.9.2\springfox-core-2.9.2.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-schema\2.9.2\springfox-schema-2.9.2.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-swagger-common\2.9.2\springfox-swagger-common-2.9.2.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-spring-web\2.9.2\springfox-spring-web-2.9.2.jar;E:\maven\MavenRepository\maven_jar\com\google\guava\guava\20.0\guava-20.0.jar;E:\maven\MavenRepository\maven_jar\com\fasterxml\classmate\1.3.4\classmate-1.3.4.jar;E:\maven\MavenRepository\maven_jar\org\springframework\plugin\spring-plugin-core\1.2.0.RELEASE\spring-plugin-core-1.2.0.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\plugin\spring-plugin-metadata\1.2.0.RELEASE\spring-plugin-metadata-1.2.0.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\mapstruct\mapstruct\1.2.0.Final\mapstruct-1.2.0.Final.jar;E:\maven\MavenRepository\maven_jar\io\springfox\springfox-swagger-ui\2.9.2\springfox-swagger-ui-2.9.2.jar;E:\maven\MavenRepository\maven_jar\org\springframework\boot\spring-boot-starter-data-redis\2.0.3.RELEASE\spring-boot-starter-data-redis-2.0.3.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\data\spring-data-redis\2.0.8.RELEASE\spring-data-redis-2.0.8.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\data\spring-data-keyvalue\2.0.8.RELEASE\spring-data-keyvalue-2.0.8.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\data\spring-data-commons\2.0.8.RELEASE\spring-data-commons-2.0.8.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\springframework\spring-oxm\5.0.7.RELEASE\spring-oxm-5.0.7.RELEASE.jar;E:\maven\MavenRepository\maven_jar\io\lettuce\lettuce-core\5.0.4.RELEASE\lettuce-core-5.0.4.RELEASE.jar;E:\maven\MavenRepository\maven_jar\io\projectreactor\reactor-core\3.1.8.RELEASE\reactor-core-3.1.8.RELEASE.jar;E:\maven\MavenRepository\maven_jar\org\reactivestreams\reactive-streams\1.0.2\reactive-streams-1.0.2.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-common\4.1.25.Final\netty-common-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-transport\4.1.25.Final\netty-transport-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-buffer\4.1.25.Final\netty-buffer-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-resolver\4.1.25.Final\netty-resolver-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-handler\4.1.25.Final\netty-handler-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\io\netty\netty-codec\4.1.25.Final\netty-codec-4.1.25.Final.jar;E:\maven\MavenRepository\maven_jar\org\apache\commons\commons-pool2\2.5.0\commons-pool2-2.5.0.jar;E:\maven\MavenRepository\maven_jar\org\jeecgframework\boot\codegenerate\1.0.2\codegenerate-1.0.2.jar;E:\maven\MavenRepository\maven_jar\org\postgresql\postgresql\42.2.2\postgresql-42.2.2.jar;E:\maven\MavenRepository\maven_jar\org\jeecgframework\autopoi-web\1.0.1\autopoi-web-1.0.1.jar;E:\maven\MavenRepository\maven_jar\org\jeecgframework\autopoi\1.0.1\autopoi-1.0.1.jar;E:\maven\MavenRepository\maven_jar\org\apache\poi\poi\3.9\poi-3.9.jar;E:\maven\MavenRepository\maven_jar\org\apache\poi\poi-ooxml\3.9\poi-ooxml-3.9.jar;E:\maven\MavenRepository\maven_jar\org\apache\poi\poi-ooxml-schemas\3.9\poi-ooxml-schemas-3.9.jar;E:\maven\MavenRepository\maven_jar\org\apache\xmlbeans\xmlbeans\2.3.0\xmlbeans-2.3.0.jar;E:\maven\MavenRepository\maven_jar\stax\stax-api\1.0.1\stax-api-1.0.1.jar;E:\maven\MavenRepository\maven_jar\xerces\xercesImpl\2.9.1\xercesImpl-2.9.1.jar;E:\maven\MavenRepository\maven_jar\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;E:\maven\MavenRepository\maven_jar\org\apache\poi\poi-scratchpad\3.9\poi-scratchpad-3.9.jar;E:\maven\MavenRepository\maven_jar\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;E:\maven\MavenRepository\maven_jar\org\hibernate\hibernate-core\4.1.0.Final\hibernate-core-4.1.0.Final.jar;E:\maven\MavenRepository\maven_jar\antlr\antlr\2.7.7\antlr-2.7.7.jar;E:\maven\MavenRepository\maven_jar\org\jboss\spec\javax\transaction\jboss-transaction-api_1.1_spec\1.0.0.Final\jboss-transaction-api_1.1_spec-1.0.0.Final.jar;E:\maven\MavenRepository\maven_jar\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;E:\maven\MavenRepository\maven_jar\org\hibernate\javax\persistence\hibernate-jpa-2.0-api\1.0.1.Final\hibernate-jpa-2.0-api-1.0.1.Final.jar;E:\maven\MavenRepository\maven_jar\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;E:\maven\MavenRepository\maven_jar\org\javassist\javassist\3.15.0-GA\javassist-3.15.0-GA.jar;E:\maven\MavenRepository\maven_jar\org\hibernate\common\hibernate-commons-annotations\4.0.1.Final\hibernate-commons-annotations-4.0.1.Final.jar" org.jeecg.JeecgOneGUI
11:46:43.587 [AWT-EventQueue-0] DEBUG org.jeecgframework.codegenerate.database.DbReadTableUtil - 数据库驱动: com.mysql.jdbc.Driver
Mon Apr 15 11:46:43 CST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jeecgframework.codegenerate.database.DbReadTableUtil.c(DbReadTableUtil.java:391)
	at org.jeecgframework.codegenerate.window.CodeWindow$1.actionPerformed(CodeWindow.java:178)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Process finished with exit code 0

以上是配置的全部内容，配置文件除了密码我全部都没动

请问这是怎么回事。

数据库已经初始化过了，有数据。

application.yml我直接把application-dev.yml复制过来,然后改了spring-datasource-datasource-master下的数据库密码password.

**Comment by ileadall42** [comment]
@z469441432 数据库启动了吗?1.1版本的话 选对activate的那个数据库密码来修改了吗？

**Comment by z469441432** [comment]
> activate

数据库一直没停，里面还有其他项目要用的库呢啊。
activate的数据库密码是什么意思呢，我没注意

**Comment by galaxist** [comment]
你这是数据库root的远程访问权限没给吧

**Comment by z469441432** [comment]
本地的数据库





> 你这是数据库root的远程访问权限没给吧
我这个数据库用了两年了，本地访问局域网访问都没有问题的啊。
我很奇怪到底为什么会出这个错误。我觉得可能是配置，是不是我本地的配置需要改改？
哦，对了，我用的是intellij，不是eclipse

**Comment by galaxist** [comment]
其他项目也是用的和你用的账号和实例一样吗，数据库账号，ip（内外网有区分），具体实例都不一样的。

**Comment by zhangdaiscott** [comment]
账号密码错误
