### ISSUE TITLE
非admin账号，登录后查看更多通知，个人中心，账号设置等，都打不开，测试多个账号都有问题，google控制台有报错

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#451]
##### 版本号：
2.1.0

##### 问题描述：
今天升级代码之后，非admin账号，登录后查看更多通知，个人中心，账号设置等，都打不开，测试多个账号都有问题，google控制台有报错。（后测试，不知道怎么得有时候就能点进去，刷新之后就不行）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42332606/63680849-1ef28200-c827-11e9-8b96-41605f027ed6.png)
![image](https://user-images.githubusercontent.com/42332606/63680878-2a45ad80-c827-11e9-95f5-9dc2fb3da46b.png)
![image](https://user-images.githubusercontent.com/42332606/63680888-303b8e80-c827-11e9-9fcb-47300bf513f6.png)
本人是java开发，不擅长前端，不知道这个是不是前端的bug，希望能解惑，万分感谢

**Comment by zhangdaiscott** [comment]
admin 可以？

**Comment by RhineDream** [comment]
> admin 可以？

我这边测试确实admin可以，子账号不行

**Comment by zhangdaiscott** [comment]
好的，我们测测

**Comment by zfmmp** [comment]
测试完成没有问题

**Comment by RhineDream** [comment]
> 测试完成没有问题

非常感谢，已经解决了，我以为这个不是菜单，没有配置菜单权限，建议把这个写道文档里，不然不说还真不知道是这个原因导致的。之前以为是公共模块，不需要配置权限。
