### ISSUE TITLE
chart x 轴数据显示不全

### ISSUE THREAD

**Issue by brade080710** [zhangdaiscott/jeecg-boot#452]
[#####](url) 版本号：
2.0.2

##### 问题描述：
chart x 轴显示不全

##### 截图&代码：

![image](https://raw.githubusercontent.com/brade080710/jwtdemo/master/QQ%E6%88%AA%E5%9B%BE20190826172121.png)

**Comment by zhangdaiscott** [comment]
这是哪个功能？

**Comment by brade080710** [comment]
首页的组件线性图，最下面那个，统计登录用户的，数据多了，最后一个x轴显示不全，麻烦能不能提供一下，文档

**Comment by zhangdaiscott** [comment]
报表UI组件：viser-vue
https://viserjs.github.io/demo.html#/viser/bar/basic-bar

**Comment by kangshifu1** [comment]
<template>
  <div>
    <v-chart :forceFit="true" :height="height" :data="data" :scale="scale" :padding="padding">
      <v-tooltip />
      <v-axis />
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>
  </div>
</template>

<script>
const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
    { year: '19910', value: 3 },
  { year: '19920', value: 4 },
  { year: '19930', value: 3.5 },
  { year: '19940', value: 5 },
  { year: '19950', value: 4.9 },
{ year: '19921', value: 4 },
  { year: '19931', value: 3.5 },
  { year: '19941', value: 5 },
  { year: '19951', value: 4.9 },

  { year: '1996000000', value: 6 } 
];

const scale = [{
  dataKey: 'value',
  min: 0,
},{
  dataKey: 'year',
  min: 0,
  max: 1,
}];

export default {
  data() {
    return {
      data,
      scale,
      height: 400,padding: [20, 'auto', 300, 'auto']
    };
  }
};
</script>

**Comment by kangshifu1** [comment]
`<v-chart :forceFit="true" :height="height" :data="data" :scale="scale" :padding="padding">
      <v-tooltip />
      <v-axis />
      <v-line position="year*value" />
      <v-point position="year*value" shape="circle" />
    </v-chart>`

**Comment by kangshifu1** [comment]
设置padding 可进行padding的大小 进行设置

**Comment by kangshifu1** [comment]
https://blog.csdn.net/sinat_19528249/article/details/100436288

**Comment by brade080710** [comment]
确实可以解决，非常感谢
