### ISSUE TITLE
后台代码，部署到k8s+docker环境，一直报token异常，但是可正常使用，不知道怎么处理...

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#453]
##### 版本号：
2.1.0

##### 问题描述：
如题，后台代码，部署到k8s+docker环境，一直报token异常，但是可正常使用，不知道怎么处理...最新版说解决了这个问题，本地测试没有这个问题，部署到服务器之后有

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42332606/63681078-97594300-c827-11e9-9426-c18d09869052.png)

**Comment by zhangdaiscott** [comment]
清空浏览器缓存，原来首页有个定时任务一直刷请求，超时就会出现这个问题

**Comment by RhineDream** [comment]
> 清空浏览器缓存，原来首页有个定时任务一直刷请求，超时就会出现这个问题

清空了也不行，感觉跟前台没有关系，我把浏览器都关了还是会报这样的错，定时大概十来八秒就会抛一次异常，
![image](https://user-images.githubusercontent.com/42332606/63733030-776a6380-c8a9-11e9-99c5-c5bd84d914c5.png)
![image](https://user-images.githubusercontent.com/42332606/63733039-80f3cb80-c8a9-11e9-9021-e0848aaa538d.png)
![image](https://user-images.githubusercontent.com/42332606/63733041-8224f880-c8a9-11e9-8068-837e183c712c.png)
发现每次报的身份ip地址不一样，这个地址段应该是k8s的地址段
![image](https://user-images.githubusercontent.com/42332606/63733106-b4cef100-c8a9-11e9-9500-ca84585bfe51.png)

**Comment by RhineDream** [comment]
> 清空浏览器缓存，原来首页有个定时任务一直刷请求，超时就会出现这个问题

我怀疑是不是跟k8s的机制有关系？但是具体什么原因还真是想不明白

**Comment by zhangdaiscott** [comment]
有定时任务吗

**Comment by RhineDream** [comment]
> 有定时任务吗

没有，还没有自己写过定时任务

**Comment by zhangdaiscott** [comment]
是不是通过ngnix负载的，监控下nginx有没有请求，把所有访问口都关掉，看看后台还提示没有

**Comment by RhineDream** [comment]
> 是不是通过ngnix负载的，监控下nginx有没有请求，把所有访问口都关掉，看看后台还提示没有

确实有请求，见下图
![image](https://user-images.githubusercontent.com/42332606/63734792-3f1a5380-c8b0-11e9-95ae-de51344262bf.png)

代码搜索如下
![image](https://user-images.githubusercontent.com/42332606/63734808-4b061580-c8b0-11e9-8f7f-8922ea11496b.png)

但是浏览器都处于关闭状态，他是怎么发起这个定时请求的呢？
我应该怎么把这个请求停掉？

**Comment by RhineDream** [comment]
> 是不是通过ngnix负载的，监控下nginx有没有请求，把所有访问口都关掉，看看后台还提示没有

而且停掉之后，对系统其他功能有没有影响？

**Comment by zhangdaiscott** [comment]
你的版本应该是2.1.0 之前的。新版已经裁成websocket推送消息，原来逻辑是在页面加了一个js定时任务，去刷新获取后台公告信息。
可以参考最新版改造

**Comment by RhineDream** [comment]
> 你的版本应该是2.1.0 之前的。新版已经裁成websocket推送消息，原来逻辑是在页面加了一个js定时任务，去刷新获取后台公告信息。
> 可以参考最新版改造

![image](https://user-images.githubusercontent.com/42332606/63741724-c7a4ee00-c8c8-11e9-889f-15f662486455.png)
![image](https://user-images.githubusercontent.com/42332606/63741752-dd1a1800-c8c8-11e9-89ae-136c63df9121.png)

我仔细对比了一下，我的应该是最新版版的，我这里还有websocket呢

![image](https://user-images.githubusercontent.com/42332606/63741886-63cef500-c8c9-11e9-85c8-a655939616a8.png)
感觉这都挺正常的

是不是把那个定时任务注掉就好了？
