### ISSUE TITLE
Online表单开发的从数据库导入表单功能只能支持数据库名jeecg-boot

### ISSUE THREAD

**Issue by hiyaojie** [zhangdaiscott/jeecg-boot#454]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/14881927/63682978-c5408680-c82b-11e9-9ab4-13baf2ad0462.png)

**Comment by zhangdaiscott** [comment]
修改代码生成器的数据库配置
   配置文件: jeecg-boot-module-system/src/main/resources/jeecg/jeecg_database.propertie
http://jeecg-boot.mydoc.io/?t=345685
