### ISSUE TITLE
浏览器页面正常打开，过一会websocket会自动断开，断开时，发送通知公告无法推送

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#457]
##### 版本号：
2.1.0

##### 问题描述：
浏览器页面正常打开，过一会websocket会自动断开，断开时，发送通知公告无法推送
刷新两个浏览器，当控制台输出两个都连接上时，才能推送公告成功

期望：用户处于登录状态，websocket能一直连接，不然公告推送意义不大
##### 截图&代码：
![image](https://user-images.githubusercontent.com/42332606/63734036-4429d380-c8ad-11e9-9452-3333cc940328.png)

**Comment by RhineDream** [comment]
已解决，因为nginx代理的问题，一分钟自动断开websocket连接，加长时间，加了心跳包功能。。。

**Comment by zhangdaiscott** [comment]
好

**Comment by CharlieJ0hn** [comment]
@RhineDream 您好，能把您开启心跳的代码和nginx配置给我看看吗？我这里去掉readtime还是断开，无法开启心跳。
