### ISSUE TITLE
建议：nginx配置增加以下配置以支持websocket

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#458]
##### 版本号：
2.1.0

##### 问题描述：
nginx配置增加以下配置以支持websocket，不配置该项，websocketlian连接报404

proxy_set_header        Upgrade $http_upgrade;
proxy_set_header        Connection "upgrade";

##### 截图&代码：

![image](https://user-images.githubusercontent.com/42332606/63734654-b26f9580-c8af-11e9-866a-890d1efa91ea.png)

**Comment by zhangdaiscott** [comment]
3Q

**Comment by zhangdaiscott** [comment]
验证了下，我们演示系统没加这个也可以用啊

**Comment by warrenwuz** [comment]
感谢
