### ISSUE TITLE
热部署

### ISSUE THREAD

**Issue by yuewanzhe** [zhangdaiscott/jeecg-boot#459]
##### 版本号：
2.1.0

##### 问题描述：
开启热部署启动项目会报错，关闭热部署启动就不会报错。

##### 截图&代码：
![微信截图_20190827102523](https://user-images.githubusercontent.com/52185088/63736265-147ec980-c8b5-11e9-8679-3fc3df5e3064.png)

**Comment by zhangdaiscott** [comment]
建议用 JRebel

**Comment by yuewanzhe** [comment]
我用的eclipse

**Comment by ycw01** [comment]
idea也报错

**Comment by whyduzhuo** [comment]
> 建议用 JRebel

用不起
