### ISSUE TITLE
多模块中如何使用system中的实体类

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#460]
##### 版本号：
v2.0.2

##### 问题描述：
根据常见问题中的解答自己写了一个子模块，但是子模块禁止引用system的实体。请问我该如何使用system的实体呢？我之前见过的方法是把所有的实体都当作一个模块来使用。这样所有的模块都可以共用实体。

**Comment by zhangdaiscott** [comment]
尽量不要用，可以自定义一个DTO
