### ISSUE TITLE
swagger2 打开doc.html或swagger-ui.html异常问题

### ISSUE THREAD

**Issue by wrs645776258** [zhangdaiscott/jeecg-boot#461]
##### 版本号：

2.0.2
##### 问题描述：
打开doc.html或swagger-ui.html异常问题

##### 截图&代码：
i.s.m.parameters.AbstractSerializableParameter:421 - Illegal DefaultValue null for parameter type integer
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412)

**Comment by wrs645776258** [comment]
上面问题是因为@ApiModel注解的实体类存在Integer或long类型等等，没有默认值问题。导致转换时报错。
解决方法1：
在字段上的@ApiModelProperty(value = "主键ID",example = "1")加example 属性。
解决方法2：
增加依赖包。
原依赖包始1.5.20，是引入springfox-swagger2默认引入的。
现在手动引入
<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.5.21</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-models</artifactId>
			<version>1.5.21</version>
		</dependency>

**Comment by zhangdaiscott** [comment]
升级最新版就好了
