### ISSUE TITLE
编译主题颜色已生效，但是hai还在一直转圈，显示主题正在编译，不是一个人有这个问题..

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#463]
##### 版本号：
2.1.0

##### 问题描述：
貌似蓝色主题可以，其他的dou都会转圈

![image](https://user-images.githubusercontent.com/42332606/63744432-e8257600-c8d1-11e9-8f27-1a83395f7ae5.png)

**Comment by zhangdaiscott** [comment]
我测试可以啊

**Comment by RhineDream** [comment]
> 我测试可以啊

给你个我的测试地址http://61.135.192.77:10001 
admin    123456
切换完颜色之后如果不转圈，f5刷新一下试试？
我本地和服务器都转圈
![image](https://user-images.githubusercontent.com/42332606/63755705-b4eee100-c8e9-11e9-9c2a-bb17532efb31.png)

**Comment by zhangdaiscott** [comment]
你的版本也没问题，清空浏览器缓存试试
![image](https://user-images.githubusercontent.com/3162115/63757284-5d9e4000-c8ec-11e9-98ee-b84f66d4f3cb.png)

**Comment by zhangdaiscott** [comment]
发现问题了，我们看看

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布

**Comment by zgz1227** [comment]
> 已经解决，下个版本发布

请问是什么问题？我们自己应该怎么解决？

**Comment by he0128** [comment]
> 已经解决，下个版本发布

下个版本 什么时候发布？
