### ISSUE TITLE
postgres数据库下测试在线表单报错

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#464]
##### 截图&代码：
1、选主表，选功能测试
<img width="974" alt="截屏2019-08-2714 10 33" src="https://user-images.githubusercontent.com/9619081/63745431-bf52b000-c8d4-11e9-8c34-b98f949e4538.png">
2、添加-点确定提交后报错（无源码，无法定位问题产生原因）
<img width="1254" alt="截屏2019-08-2714 14 25" src="https://user-images.githubusercontent.com/9619081/63745561-15bfee80-c8d5-11e9-8786-e61e83d0e34d.png">
错误如下：
### Cause: org.postgresql.util.PSQLException: ERROR: column "create_time" is of type timestamp without time zone but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：133
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "create_time" is of type timestamp without time zone but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：133

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
