### ISSUE TITLE
2.1版本在线表单开发提示找不到资源

### ISSUE THREAD

**Issue by 343122875** [zhangdaiscott/jeecg-boot#467]
##### 版本号：
2.1

##### 问题描述：
点击自定义按钮后提示“很抱歉，资源未找到!”
点开network发现项目名为jeecg-boot，index.html和vue.config.js中已经指定自己的项目名了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36358868/63824300-347fbd00-c989-11e9-9865-2c21b4fbd7f6.png)
![image](https://user-images.githubusercontent.com/36358868/63824286-29c52800-c989-11e9-9085-522bd73c99c6.png)
![image](https://user-images.githubusercontent.com/36358868/63824340-5b3df380-c989-11e9-98a2-8b716e6774de.png)

**Comment by zhangdaiscott** [comment]
改过项目名字的话，说明你改全

**Comment by 343122875** [comment]
//图片预览请求地址
 window._CONFIG['domianURL'] = 'http://localhost:8080/jeecg-boot';
 window._CONFIG['imgDomainURL'] = 'http://localhost:8080/jeecg-boot/sys/common/view';

// 创建 axios 实例
const service = axios.create({
  baseURL: '/jeecg-boot/', // api base_url
  timeout: 6000 // 请求超时时间
})

这2个地方我都改了呀 还有哪里需要改吗？

**Comment by 343122875** [comment]
> 改过项目名字的话，说明你改全

//图片预览请求地址
window._CONFIG['domianURL'] = 'http://localhost:8080/jeecg-boot';
window._CONFIG['imgDomainURL'] = 'http://localhost:8080/jeecg-boot/sys/common/view';

// 创建 axios 实例
const service = axios.create({
baseURL: '/jeecg-boot/', // api base_url
timeout: 6000 // 请求超时时间
})

这2个地方我都改了呀 还有哪里需要改吗？

**Comment by zhangdaiscott** [comment]
你截图的代码，看样子不是2.1版本
最新版是
https://github.com/zhangdaiscott/jeecg-boot/blob/master/ant-design-vue-jeecg/public/index.html

**Comment by 343122875** [comment]
> 你截图的代码，看样子不是2.1版本
> 最新版是
> https://github.com/zhangdaiscott/jeecg-boot/blob/master/ant-design-vue-jeecg/public/index.html

![image](https://user-images.githubusercontent.com/36358868/63869649-0f239b00-c9eb-11e9-9c2e-d8176800f633.png)
是最新的 我上面发的是你们官方开发手册上的 我的意思是index.html和vue.config.js前端两个需要改的地方都改了已经

**Comment by zhangdaiscott** [comment]
请缓存试试吧

**Comment by 343122875** [comment]
> 请缓存试试吧

换了浏览器也还是一样 而且全局搜了前端的代码 一直找不到jeecg-boot了

**Comment by zhangdaiscott** [comment]
只能手工修改node_modules下@jeecg/antd-onine下的js
搜jeecg-boot 手工修改成你自己的项目名字

**Comment by supine-win** [comment]
2.4.3中是否还是写死的

**Comment by zhangdaiscott** [comment]
新版不是

**Comment by ly0518** [comment]
![image](https://user-images.githubusercontent.com/11720763/120592722-e73f5200-c470-11eb-83cd-19a48da65acf.png)

**Comment by zhenghaifei593** [comment]
最新版的改了antd-online-mini的项目名称，还是找不到资源
