### ISSUE TITLE
JPopup组件无法在自定义页使用，咨询使用教程

### ISSUE THREAD

**Issue by leekent** [zhangdaiscott/jeecg-boot#468]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/33902969/63830013-9e09c680-c99d-11e9-89b4-846297c73e31.png)

![image](https://user-images.githubusercontent.com/33902969/63830052-b8dc3b00-c99d-11e9-89ca-3d8d0acbad5f.png)

**Comment by leekent** [comment]
![Uploading image.png…]()
尝试了两个组件，都无法使用， online生成代码后的vue文件是从jeecgbiz引入JPopup， 同样无法使用

**Comment by leekent** [comment]
![image](https://user-images.githubusercontent.com/33902969/63830644-3fdde300-c99f-11e9-9e65-d6086c1ec4c6.png)
尝试了两个组件，都无法使用， online生成代码后的vue文件是从jeecgbiz引入JPopup， 同样无法使用

**Comment by zhangdaiscott** [comment]
这块功能尚未开放

**Comment by leekent** [comment]
> 这块功能尚未开放

好的， 是否就意味着online生成代码后无法使用？

**Comment by zhangdaiscott** [comment]
popup组件这块目前是无法使用

**Comment by he0128** [comment]
JPopup组件 有开放的计划吗？
