### ISSUE TITLE
online 表单开发提示很抱歉资源未找到

### ISSUE THREAD

**Issue by Airoyee** [zhangdaiscott/jeecg-boot#470]
##### 问题描述：

online 表单开发配置好路径后，提示很抱歉资源未找到

##### 截图&代码：

在线表单生成路径
![image](https://user-images.githubusercontent.com/12388669/63838053-30ff2c80-c9af-11e9-80fa-d858c5e12e1e.png)

在菜单里面这么配置
![image](https://user-images.githubusercontent.com/12388669/63837932-ff866100-c9ae-11e9-927b-e236cd058842.png)

访问生成的菜单提示“很抱歉资源未找到”

![image](https://user-images.githubusercontent.com/12388669/63838098-4aa07400-c9af-11e9-8d3d-9143bd8b2c37.png)

期待大佬回复

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/63841200-f26c7080-c9b4-11e9-8b01-027233f89660.png)

改成非路由菜单

**Comment by Airoyee** [comment]
@zhangdaiscott 感谢大佬，太棒了这个功能

**Comment by haijie3505** [comment]
1、测试环境使用online在线开发没有生成代码，如何快速部署到生产环境
2、测试环境使用online在线开发生成代码，如何快速部署到生产环境

**Comment by zhangdaiscott** [comment]
其他角色用户，访问online菜单 提示404问题
https://github.com/zhangdaiscott/jeecg-boot/issues/744
