### ISSUE TITLE
请求URL路径权限问题

### ISSUE THREAD

**Issue by NoSuchBean** [zhangdaiscott/jeecg-boot#471]
##### 版本号：
V2.0.1

##### 问题描述：
我们领导不想要@RequiresPermissions("user:adduser")这样的方式来控制权限,请问项目中还有没有通过其他方法来实现请求URL的permission控制?比如,A账号没有某个菜单权限的时候,禁止A账号通过postman等方式请求该菜单权限路径;
我看到相比较于V1.0, V2.0版本升级时,ShiroConfig类中把filterMap.put("resourceCheckFilter", new ResourceCheckFilter()); 这行代码给去掉了,看着感觉像是这个类实现了URL的权限控制,但是又找不到是在哪里使用到它,在它的方法里面打断点,普通操作也没有进入该断点;

##### 截图&代码：
ShiroConfig.java
		// 添加自己的过滤器并且取名为jwt
		Map<String, Filter> filterMap = new HashMap<String, Filter>(1);
		filterMap.put("jwt", new JwtFilter());
		filterMap.put("resourceCheckFilter", new ResourceCheckFilter());
		shiroFilterFactoryBean.setFilters(filterMap);
		// <!-- 过滤链定义，从上向下顺序执行，一般将/**放在最为下边
		filterChainDefinitionMap.put("/**", "jwt");
		//filterChainDefinitionMap.put("/**", "resourceCheckFilter");

**Comment by zhangdaiscott** [comment]
可以自己改造

**Comment by UPMuling** [comment]
哥们，遇到同样的问题。你们有改造了吗？
