### ISSUE TITLE
个人中心的个人设置（比如昵称等）无法修改

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#472]
##### 问题描述：
个人中心的个人设置（比如昵称等）无法修改, 提交后无响应（没调后台接口）

##### 截图&代码：
<img width="949" alt="截屏2019-08-2817 07 27" src="https://user-images.githubusercontent.com/9619081/63842287-e4b7ea80-c9b6-11e9-8ed8-3a57481f160f.png">

**Comment by zhangdaiscott** [comment]
这是模板未实现，需要自己实现

**Comment by liaoyongxiong** [comment]
好的
