### ISSUE TITLE
在线表单开发

### ISSUE THREAD

**Issue by mrlonely1986** [zhangdaiscott/jeecg-boot#473]
##### 问题描述：新建单表表单，点击测试功能报错
![image](https://user-images.githubusercontent.com/7775292/63842956-2dbc6e80-c9b8-11e9-9d07-49af119281a9.png)

##### 截图&代码：
数据库查询失败nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM ( SELECT ,id FROM testchen where 1=1 ORDER BY create_time desc ) TOTAL ### The error may exist in URL [jar:file:/Users/chendan/.m2/repository/org/jeecgframework/boot/online-form/1.0.2/online-form-1.0.2.jar!/org/jeecg/modules/online/cgform/mapper/xml/OnlCgformFieldMapper.xml] ### The error may involve org.jeecg.modules.online.cgform.mapper.OnlCgformFieldMapper.selectPageBySql ### The error occurred while executing a query ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(1) FROM ( SELECT ,id FROM testchen where 1=1 ORDER BY create_time desc ) TOTAL

**Comment by zhangdaiscott** [comment]
怎么重现？

**Comment by mrlonely1986** [comment]
执行count的 时候  l : SELECT COUNT(1) FROM ( SELECT ,id FROM testchen where 1=1 ORDER BY create_time desc ) TOTAL  id前面 多了一个 , 号

**Comment by mrlonely1986** [comment]
![image](https://user-images.githubusercontent.com/7775292/63844526-f8655000-c9ba-11e9-98c3-b33d464251aa.png)

**Comment by mrlonely1986** [comment]
我看了是主键排序错了，估计是这个引起的

**Comment by zhangdaiscott** [comment]
你是什么数据库，有什么特殊的？？
我们测试是没问题的

**Comment by mrlonely1986** [comment]
mysql 5.7  我觉得和数据库应该没关系 是生成 count 语句的时候出问题了，

**Comment by mrlonely1986** [comment]
id 前面 会多生成 一个 ,号

**Comment by zhangdaiscott** [comment]
请出重现步骤，我们无法重现

**Comment by zhangdaiscott** [comment]
你是不是把所有字段都隐藏了？
