### ISSUE TITLE
Online表单在线开发主附表代码生成BUG

### ISSUE THREAD

**Issue by enay1986** [zhangdaiscott/jeecg-boot#475]
##### 问题描述：
Online表单在线开发模块，单表生成代码没有问题，主附表在选中主表生成代码时，打开的页面为空白且无法关闭。

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/54653176/63904781-bed92700-ca44-11e9-9930-a3df21825044.png)
![图片](https://user-images.githubusercontent.com/54653176/63904790-c4cf0800-ca44-11e9-9f8b-07e3af7608cd.png)

**Comment by zhangdaiscott** [comment]
有更详细的错吗，主表代码生成我们测试过没有问题

**Comment by enay1986** [comment]
后台没有报错，前端有如下错误:
[Vue warn]: Error in render: "TypeError: t is null"

found in

---> <CodeGenerator>
       <ACard>
         <OnlCgformHeadList> at src/views/modules/online/cgform/OnlCgformHeadList.vue
           <RouteView> at src/components/layouts/RouteView.vue
             <Anonymous>
               <ALayoutContent>
                 <Anonymous>
                   <ALayout>
                     <Anonymous>
                       <ALayout>
                         <GlobalLayout> at src/components/page/GlobalLayout.vue
                           <TabLayout> at src/components/layouts/TabLayout.vue
                             <ALocaleProvider>
                               <App> at src/App.vue
                                 <Root> vue.runtime.esm.js:619
TypeError: "t is null"
    node_modules OnlineForm.umd.min.js:43
    renderList VueJS
    node_modules OnlineForm.umd.min.js:43
    VueJS 7
    run es6.promise.js:75
    notify es6.promise.js:92
    flush 
![图片](https://user-images.githubusercontent.com/54653176/63905912-64da6080-ca48-11e9-8037-167d3d402229.png)
![图片](https://user-images.githubusercontent.com/54653176/63905942-77549a00-ca48-11e9-81e0-665478354df1.png)
![图片](https://user-images.githubusercontent.com/54653176/63905964-863b4c80-ca48-11e9-91f2-4ac0d461edfa.png)

**Comment by zhangdaiscott** [comment]
你是打开生成界面报错吗？
我们这边无论是打开界面和生成代码，一对多都无问题，你再确认下你的环境有什么特殊的吧
