### ISSUE TITLE
全局异常处理与控制器的try catch 

### ISSUE THREAD

**Issue by luoyunchong** [zhangdaiscott/jeecg-boot#476]
##### 问题描述：
既然在代码中已经有了JeecgBootExceptionHandler的全局异常处理，那么在SysUserController中依然包含了大量的try catch Exception的异常拦截，二个代码是否重复使用，在SysUserController中的这些try catch大多数应该是可以删除的。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18613266/63905257-4a9f8300-ca46-11e9-856e-ed1ad479da4f.png)

![image](https://user-images.githubusercontent.com/18613266/63905179-01e7ca00-ca46-11e9-9cc2-2517b5b30f1a.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
代码生成器和部分功能已经改造完成，下个版本发布
