### ISSUE TITLE
在线表单开发生成代码失败

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#479]
##### 问题描述：
在线表单开发生成代码失败

##### 截图&代码：
1、选取test_order_main，点击代码生成
<img width="1005" alt="截屏2019-08-2915 16 35" src="https://user-images.githubusercontent.com/9619081/63919034-7df70780-ca70-11e9-86e4-c85cf8fbd7e7.png">

2、抛出异常，无法生成代码：
2019-08-29 15:13:54.810 [http-nio-8080-exec-2] INFO  org.jeecgframework.codegenerate.generate.a.a:34 - ----templatePath-----------------/jeecg/code-template-online/onetomany
java.io.FileNotFoundException: file:/Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/target/jeecg-boot-module-system-2.1.0.jar!/BOOT-INF/classes!/jeecg/code-template-online/onetomany does not exist.
        at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:122)
        at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:119)
        at java.security.AccessController.doPrivileged(Native Method)
        at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:119)

查看target的打包目录，实际上看到classes!/jeecg/code-template-online/onetomany 文件是存在的
<img width="471" alt="截屏2019-08-2915 19 18" src="https://user-images.githubusercontent.com/9619081/63918980-63bd2980-ca70-11e9-8099-9b6d169dfb60.png">

**Comment by zhangdaiscott** [comment]
你用的什么开发工具

**Comment by liaoyongxiong** [comment]
开发工具是idea
<img width="629" alt="截屏2019-08-2916 22 40" src="https://user-images.githubusercontent.com/9619081/63923492-3e80e900-ca79-11e9-8d53-c43c0b50ae73.png">


我是在命令行下用 mvn package打包的:

liaoyongxiong@liaoyongxiongdeMacBook-Pro jeecg-boot % mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] jeecg-boot-parent                                                  [pom]
[INFO] jeecg-boot-base-common                                             [jar]
[INFO] jeecg-boot-module-system                                           [jar]
[INFO] 
[INFO] -------------< org.jeecgframework.boot:jeecg-boot-parent >--------------
[INFO] Building jeecg-boot-parent 2.1.0                                   [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] -----------< org.jeecgframework.boot:jeecg-boot-base-common >-----------
[INFO] Building jeecg-boot-base-common 2.1.0                              [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ jeecg-boot-base-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/src/main/resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ jeecg-boot-base-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 59 source files to /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/target/classes
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/src/main/java/org/jeecg/common/system/query/QueryGenerator.java: 某些输入文件使用了未经检查或不安全的操作。
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/src/main/java/org/jeecg/common/system/query/QueryGenerator.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ jeecg-boot-base-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ jeecg-boot-base-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ jeecg-boot-base-common ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ jeecg-boot-base-common ---
[INFO] Building jar: /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-base-common/target/jeecg-boot-base-common-2.1.0.jar
[INFO] 
[INFO] ----------< org.jeecgframework.boot:jeecg-boot-module-system >----------
[INFO] Building jeecg-boot-module-system 2.1.0                            [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ jeecg-boot-module-system ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 353 resources
[INFO] Copying 43 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ jeecg-boot-module-system ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 188 source files to /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/target/classes
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/SysDictController.java: 某些输入文件使用或覆盖了已过时的 API。
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/controller/SysDictController.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/cas/controller/CasClientController.java: 某些输入文件使用了未经检查或不安全的操作。
[INFO] /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/cas/controller/CasClientController.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ jeecg-boot-module-system ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ jeecg-boot-module-system ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ jeecg-boot-module-system ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ jeecg-boot-module-system ---
[INFO] Building jar: /Users/liaoyongxiong/iovs/jeecg-boot/jeecg-boot-module-system/target/jeecg-boot-module-system-2.1.0.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.1.3.RELEASE:repackage (repackage) @ jeecg-boot-module-system ---
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jeecg-boot-parent 2.1.0:
[INFO] 
[INFO] jeecg-boot-parent .................................. SUCCESS [  0.004 s]
[INFO] jeecg-boot-base-common ............................. SUCCESS [  7.715 s]
[INFO] jeecg-boot-module-system ........................... SUCCESS [ 14.770 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.987 s
[INFO] Finished at: 2019-08-29T16:23:56+08:00
[INFO] ------------------------------------------------------------------------

**Comment by zhangdaiscott** [comment]
是什么数据库？ 详细说明环境

**Comment by zhangdaiscott** [comment]
我们也用IDEA没问题的

**Comment by kangshifu1** [comment]
没发现问题啊

**Comment by liaoyongxiong** [comment]
还是搞不定这个问题，麻烦看看是不是这个原因导致：
https://stackoverflow.com/questions/43065117/java-io-filenotfoundexception-boot-inf-classes-templates

**Comment by anson88616425** [comment]
这个问题你解决了吗

**Comment by anson88616425** [comment]
我也遇到这个问题

**Comment by afeidexiaolulu** [comment]
问题解决了吗，，我也遇到这个问题。

**Comment by zhangdaiscott** [comment]
下个版本
