### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zichenly** [zhangdaiscott/jeecg-boot#48]
![ss](https://user-images.githubusercontent.com/19464001/56114757-56594400-5f94-11e9-9a5d-0accdd83a6f2.png)

**Comment by zichenly** [comment]
今天刚更新，一进来就是404

**Comment by yuxishua** [comment]
数据库表也更新，就好了

**Comment by zichenly** [comment]
> 数据库表也更新，就好了
完美解决
