### ISSUE TITLE
Online表单功能测试缺陷

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#481]
##### 问题描述：
Online表单功能测试时，添加记录后，更多-详情页弹出详情页字段值为空（编辑页也存在）

##### 截图&代码：
1、进入test_order_main 功能测试页，添加一条记录
<img width="1003" alt="截屏2019-08-2916 48 46" src="https://user-images.githubusercontent.com/9619081/63926822-14cac080-ca7f-11e9-8626-4624e67577c4.png">
2、更多-》详情，详情页显示，但字段值没有（关闭后接着点编辑，弹出的界面也类似，没有字段值显示）
<img width="1234" alt="截屏2019-08-2916 49 24" src="https://user-images.githubusercontent.com/9619081/63926960-5a878900-ca7f-11e9-9dad-018f83e1b3fb.png">
<img width="1208" alt="截屏2019-08-2916 52 53" src="https://user-images.githubusercontent.com/9619081/63926995-6c692c00-ca7f-11e9-8747-b3c894aa6615.png">

**Comment by zhangdaiscott** [comment]
什么数据库

**Comment by liaoyongxiong** [comment]
postgresql 11

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
