### ISSUE TITLE
Online表单开发：postgresql数据环境下普通同步方式同步数据库失败

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#482]
##### 问题描述：
Online表单开发，数据库为postgresql 11
编辑表单后，同步数据库，选择普通方式同步。同步失败。

##### 截图&代码：
1、选择普通同步
<img width="496" alt="截屏2019-08-2917 19 34" src="https://user-images.githubusercontent.com/9619081/63928144-ab987c80-ca81-11e9-8cda-4a80b77e23ed.png">
2、从日志输出看，应该是日期类型没有对数据进行兼容，生成的alter语句日期、时间类型为datetime（postgresql的日期类型为timestamp）
 alter table  test_order_main   ALTER  COLUMN   create_time  type datetime ;

建议全面检查下Online表单的代码，对日期类型的处理上做到数据库兼容。

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
