### ISSUE TITLE
online  字段在页面选择”必填项“时 代码中无法生成必填项验证

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#483]
##### 版本号：
2.1.0

##### 问题描述：
online  字段在页面选择”必填项“时 代码中无法生成必填项验证

补充：其他验证也无法生成验证代码
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/63933647-3ed6af80-ca8c-11e9-915a-be5bdade9ca4.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经修复下个版本发布
