### ISSUE TITLE
打包的APP如何调用手机摄像头等硬件

### ISSUE THREAD

**Issue by capricornstone** [zhangdaiscott/jeecg-boot#488]
##### 版本号：
2.1

##### 问题描述：
按照官方文档用HBuilderX 打包APP成功了，运行良好，请问，如果想调用手机摄像头等硬件应该如何处理，能否提供示例代码。

**Comment by zhangdaiscott** [comment]
这么我们暂时没用到，你们先研究看看，给大家分享下
