### ISSUE TITLE
部门管理，如何设置让创建者只能看到自己创建的部门

### ISSUE THREAD

**Issue by zhaohuaxiaoy** [zhangdaiscott/jeecg-boot#497]
##### 版本号：
2.0.2

##### 问题描述：
使用数据权限去控制，无法实现仅看自己创建的部门。

##### 截图&代码：
添加了数据权限
![185F19CE-697D-4A74-BDFA-A846FD11E080](https://user-images.githubusercontent.com/13568008/64066424-efd77880-cc4b-11e9-86f7-b9467269b2fb.png)
![34F09F15-E2BB-4987-9BBC-61256199180F](https://user-images.githubusercontent.com/13568008/64066425-f5cd5980-cc4b-11e9-99a9-c9a1f599e781.png)
![C968BF45-6D1E-448A-B3D4-FF343DB52D7E](https://user-images.githubusercontent.com/13568008/64066426-f960e080-cc4b-11e9-9620-e58f62fb8bb9.png)

**Comment by zhangdaiscott** [comment]
这块查询没使用查询过滤器，你缓存查询过滤器实现查询就可以
QueryWrapper<SysUser> queryWrapper = QueryGenerator.initQueryWrapper(user, req.getParameterMap());

![image](https://user-images.githubusercontent.com/3162115/64074936-514b2600-cce4-11e9-813d-d1f0d7d3f6a8.png)

**Comment by ZevenFang** [comment]
```java
	@RequestMapping(value = "/queryTreeList", method = RequestMethod.GET)
	public Result<List<SysDepartTreeModel>> queryTreeList() {
		LoginUser user = (LoginUser) SecurityUtils.getSubject().getPrincipal();
		if (!user.getUsername().equals("admin")) // 非管理员只能查看自己的部门
			return this.queryMyDeptTreeList();
		Result<List<SysDepartTreeModel>> result = new Result<>();
		try {
			// 从内存中读取
//			List<SysDepartTreeModel> list =FindsDepartsChildrenUtil.getSysDepartTreeList();
//			if (CollectionUtils.isEmpty(list)) {
//				list = sysDepartService.queryTreeList();
//			}
			List<SysDepartTreeModel> list = sysDepartService.queryTreeList();
			result.setResult(list);
			result.setSuccess(true);
		} catch (Exception e) {
			log.error(e.getMessage(),e);
		}
		return result;
	}
```
