### ISSUE TITLE
Online在线表单配置菜单问题

### ISSUE THREAD

**Issue by leekent** [zhangdaiscott/jeecg-boot#499]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/33902969/64074962-a71fce00-cce4-11e9-961f-af5de68d3be0.png)

**Comment by leekent** [comment]
应该怎么配置才能放到如系统管理菜单目录下， 并可以正常访问呢？　主要请求后台获取字段相关配置信息获取不到ｃｏｄｅ参数　　感谢解答！

**Comment by zhangdaiscott** [comment]
菜单路由类型设置为“否”
![image](https://user-images.githubusercontent.com/3162115/64075059-e1d63600-cce5-11e9-8a0c-f633bac0f252.png)
