### ISSUE TITLE
代码生成的导出功能无法获取到登录账号信息

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#50]
![image](https://user-images.githubusercontent.com/3365218/56181125-c3291880-603e-11e9-8dda-3bd33831ba3f.png)
加上后为空。
![image](https://user-images.githubusercontent.com/3365218/56181148-dd62f680-603e-11e9-941d-c505dc5b4f21.png)

屏蔽过滤后报服务器500错误

![image](https://user-images.githubusercontent.com/3365218/56181112-b7d5ed00-603e-11e9-9e91-c7612b3e5b8e.png)
![image](https://user-images.githubusercontent.com/3365218/56181211-126f4900-603f-11e9-95ab-4c581fede5d6.png)

**Comment by zhangdaiscott** [comment]
导入导出这块得单独处理，因为排除的shirio控制

**Comment by galaxist** [comment]
这个不是shiro的方法吗，怎么单独处理呢？因为导出我们要监控什么人导出什么数据，这个很重要的。

**Comment by zhangdaiscott** [comment]
别着急，我们尽快处理

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
