### ISSUE TITLE
在线生成表单包名问题。

### ISSUE THREAD

**Issue by allenchenx** [zhangdaiscott/jeecg-boot#500]
##### 问题描述：
更改项目包名后，在线表单就无法正常使用了。比如把system的包名由org.jeecg改成org.xxxx。在线表单开发就无法访问了。。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35280372/64077659-0a215d00-cd05-11e9-943f-6dd0225241ad.png)

**Comment by allenchenx** [comment]
vue 里面引用的@jeecg/antd-onine 源码里面的baseURL:jeecg-boot 改了，首先排除访问根路径的问题

**Comment by zhangdaiscott** [comment]
扫描路径org.jeecg 得保留
