### ISSUE TITLE
导出隐藏列 代码里缺少isColumnHidden这个字段 是版本问题吗？

### ISSUE THREAD

**Issue by 1158119024** [zhangdaiscott/jeecg-boot#502]
##### 问题描述：
代码里缺少isColumnHidden这个字段 是版本问题吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40381114/64102739-296ec780-cda3-11e9-9a31-b906f4c43f90.png)
![image](https://user-images.githubusercontent.com/40381114/64102797-43100f00-cda3-11e9-92d5-441471c5a9db.png)

**Comment by zhangdaiscott** [comment]
没有这个属性，需要自己扩展

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/autopoi

**Comment by 1158119024** [comment]
好的，谢谢
