### ISSUE TITLE
生成的代码，导出功能，带不上条件....看到请求上有，但是后台没有接收到，不知道是不是bug

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#503]
##### 版本号：
2.1.0

##### 问题描述：
单表生成，导出功能，条件带不上，不知道怎么添加自定义条件

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42332606/64141119-85842b00-ce39-11e9-948f-85f84f03fae8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by RhineDream** [comment]
自己写了一个方法，然后在自己的方法里调用导出，导出也是重新写，
![image](https://user-images.githubusercontent.com/42332606/64142072-1577a400-ce3d-11e9-8c4a-7e71ed20e1ba.png)

直接用标号2代码不行。2方法里也添加了1的参数，最后使用如下写法
![image](https://user-images.githubusercontent.com/42332606/64142248-cbdb8900-ce3d-11e9-8b9f-6a88dbaccbee.png)

感觉是赋值附不上
![image](https://user-images.githubusercontent.com/42332606/64142294-fcbbbe00-ce3d-11e9-86f2-994489b358c9.png)

增加了如下方法

handleExportXls3(fileName){
      this.$message.loading('正在导出,请勿多次点击,请耐心等待...',10)
      if(!fileName || typeof fileName != "string"){
        fileName = "导出文件"
      }
      // eslint-disable-next-line
      debugger
      let param = this.queryParam;
      // if(this.table.selectedRowKeys && this.table.selectedRowKeys.length>0){
      //   param['selections'] = this.table.selectedRowKeys.join(",")
      // }
      if(this.selectedRowKeys && this.selectedRowKeys.length>0){
        param['selections'] = this.selectedRowKeys.join(",")
      }
      console.log("导出参数",param)
      let paramsString = JSON.stringify(filterObj(param));
      
      downFile(this.url.exportXlsUrl,{paramsStr:paramsString}).then((data)=>{
        if (!data) {
          this.$message.warning("文件下载失败")
          return
        }
        if (typeof window.navigator.msSaveBlob !== 'undefined') {
          window.navigator.msSaveBlob(new Blob([data]), fileName+'.xls')
        }else{
          let url = window.URL.createObjectURL(new Blob([data]))
          let link = document.createElement('a')
          link.style.display = 'none'
          link.href = url
          link.setAttribute('download', fileName+'.xls')
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link); //下载完成移除元素
          window.URL.revokeObjectURL(url); //释放掉blob对象
          this.$message.success('下载完成!', 3)
        }
      })
    },

这样是可以用了，但是感觉不够优雅，希望官方能有解决方案

**Comment by tygithub1** [comment]
sorry,your code is out of date！

**Comment by zhangdaiscott** [comment]
GUI的代码生成器模板，的确没有生成对应的逻辑，我们已经修复，下个版本发布
