### ISSUE TITLE
常见案例-一对多table示例-机票信息-新增和编辑里的选择日期后没有在日期框里显示

### ISSUE THREAD

**Issue by li0801** [zhangdaiscott/jeecg-boot#505]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/54701180/64154960-7666a280-ce64-11e9-9b41-7fe3f2cc0b73.png)
选择后：没显示日期
![image](https://user-images.githubusercontent.com/54701180/64154996-8d0cf980-ce64-11e9-8d7f-a0bd5ad4e267.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by fly1206** [comment]
改成如下：
<j-date :trigger-change="true"  v-decorator="['tickectDate',{rules:[{ required: true,message: '请输入航班号!'}]}]"></j-date>

**Comment by fly1206** [comment]
修改成：
`
<j-date :trigger-change="true"  v-decorator="['tickectDate',{rules:[{ required: true,message: '请输入航班号!'}]}]"></j-date>
`

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
