### ISSUE TITLE
redis配置存在问题，登录会提示成功，但是跳转前又提示登录过期

### ISSUE THREAD

**Issue by MrQiaoLei** [zhangdaiscott/jeecg-boot#506]
##### 版本号：

jeecg-boot
##### 问题描述：

redis存在问题的情况下，登录提示成功！弹出欢迎回来提示框，但跳转前就会提示登录过期，重新登录
##### 截图&代码：

![image](https://user-images.githubusercontent.com/17661940/64166702-36121f00-ce7a-11e9-8ae6-d074dee1e189.png)

![image](https://user-images.githubusercontent.com/17661940/64166793-6954ae00-ce7a-11e9-9638-4f2791b1a45d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
reids必须配置成功
