### ISSUE TITLE
极简部署方案问题

### ISSUE THREAD

**Issue by liuguochao182311** [zhangdaiscott/jeecg-boot#507]
##### 问题描述：
使用极简部署方案打成jar部署之后，在页面访问的时候，如果直接在浏览器输入http://localhost:8081/isystem/user，就访问不了，出现
![image](https://user-images.githubusercontent.com/41249899/64246169-e6495b80-cf3e-11e9-8f6a-82c906028388.png)
，这个怎么解决呢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
说明你没改路由规则
![image](https://user-images.githubusercontent.com/3162115/64249034-50fd9580-cf45-11e9-97b5-2c0056f56384.png)
