### ISSUE TITLE
online开发功能控件缺失 上传组件bug

### ISSUE THREAD

**Issue by leekent** [zhangdaiscott/jeecg-boot#508]
##### 问题描述：1 decimall类型字段没有对应的number控件
2 上传组件上传pdf文件后无法预览打开， jpg格式文件没问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33902969/64303454-d0797c00-cfba-11e9-9c31-ca51260b5d46.png)
![image](https://user-images.githubusercontent.com/33902969/64303471-eab35a00-cfba-11e9-9d74-af4ff4112765.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/64306008-e93a5f80-cfc3-11e9-8936-cfab87cb9dfc.png)

**Comment by leekent** [comment]
数据库字段类型原本就是是 BigDecimal  ， 导入后页面属性设置控件时只有文本框可选， 后台生成feild表中的字段类型为string， 手动改为BigDecimal后恢复正常

**Comment by zhangdaiscott** [comment]
你的意思是导入的时候 BigDecimal 类型识别为 string是吗？
请问你是什么数据库

**Comment by zhangdaiscott** [comment]
经过测试online导入字段类型和代码生成的字段类型都没有问题，此问题关闭

online导入截图
![image](https://user-images.githubusercontent.com/3162115/64503071-ef9a4580-d2fb-11e9-89f1-2b329c171851.png)


生成代码截图

![image](https://user-images.githubusercontent.com/3162115/64503081-f7f28080-d2fb-11e9-9f44-f16f59e98dd7.png)
