### ISSUE TITLE
页面表单权限中的显示隐藏控制无法控制api是否被使用

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#509]
##### 版本号：
2.1.0

##### 问题描述：
页面表单权限中使用`v-has`的显示隐藏控制，只能控制前端是否显示，不能从根源上控制是否可以使用的权限，例如开发者工具中获取到token之后，可以直接curl或者postman构造请求去访问被隐藏的api接口。

##### 截图&代码：
无

**Comment by liudonghua123** [comment]
查看文档，可以配合 [JAVA访问权限控制](http://jeecg-boot.mydoc.io/?t=345723) 来解决，谢谢！

**Comment by liudonghua123** [comment]
有个小建议，可以约定例如 user 或者 user:* 包括 所有例如 user:edit, user:add, user:delete 等权限，并且默认生成的代码中都添加上 @RequiresPermissions("user:xxx") ,然后在前端页面默认添加上 user或user:* 的权限，这样前端配置就方便灵活点，不需要修改代码。

**Comment by zhangdaiscott** [comment]
默认生成权限代码是可以，但同时要是必须授权才能使用。
可以做，但是这样增加了使用者的成本，很多人不会用反而会问很多问题。
不如现在这样，需要自己加

**Comment by zhangdaiscott** [comment]
代码自动生成权限注解和权限指令的坏处
1. 需要同时生成对应的权限升级SQL
2. 需要手工授权才能访问（不授权访问不了）
3. 增加了授权配置（如果项目要求严格默认大部分功能都需要颗粒化控制，是可以的；如果项目权限要求不高，反而增加了项目开发成本）

所以此方案可以视情况而定，如果权限要求高，可以改代码生成器模板，直接实现权限代码的生成。
