### ISSUE TITLE
代码生成器 sqlserver 注释中文乱码

### ISSUE THREAD

**Issue by zhang0001** [zhangdaiscott/jeecg-boot#510]
##### 截图&代码：生成的entity  comment 中文为乱码
看到了查comment 的sql 

`select distinct cast(a.name as varchar(50)) column_name,  cast(b.name as varchar(50)) data_type,  cast(e.value as VARCHAR(200)) comment,  cast(ColumnProperty(a.object_id,a.Name,'''Precision''') as int) num_precision,  cast(ColumnProperty(a.object_id,a.Name,'''Scale''') as int) num_scale,  a.max_length,  (case when a.is_nullable=1 then '''y''' else '''n''' end) nullable,column_id   from sys.columns a left join sys.types b on a.user_type_id=b.user_type_id left join (select top 1 * from sys.objects where type = '''U''' and name ={0}  order by name) c on a.object_id=c.object_id left join sys.extended_properties e on e.major_id=c.object_id and e.minor_id=a.column_id and e.class=1 where c.name={0} order by a.column_id `

cast(e.value as VARCHAR(200)) comment 这边会出现中文乱码，改成cast(e.value as NVARCHAR(200)) comment  后正常，当然可能是数据库字符集等问题，这边对sql server 也不是太了解，目前仅发现这样能解决问题。
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在问题，你的方案好用，感谢。
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.0.6</version>
</dependency>
