### ISSUE TITLE
隔段时间未登录，一直显示登录超时

### ISSUE THREAD

**Issue by treebearye** [zhangdaiscott/jeecg-boot#511]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32627101/64327472-536ff600-cffe-11e9-8d79-74c14c5776f7.png)

![image](https://user-images.githubusercontent.com/32627101/64327607-95993780-cffe-11e9-80e8-e837a1dda7c3.png)

**Comment by zhangdaiscott** [comment]
直接访问后台接口，好使吗？
先确认下是否是后台挂了

**Comment by zhangdaiscott** [comment]
遇到类似问题，看看数据库连接池和druid是不是小了，设置大点
