### ISSUE TITLE
为什么没有高级查询了

### ISSUE THREAD

**Issue by main-key** [zhangdaiscott/jeecg-boot#5118]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
3

##### 问题描述：
为什么没有高级查询了

**Comment by zhangdaiscott** [comment]
有

**Comment by main-key** [comment]
生成页面的时候我没有选择查询字段，然后在页面上没找到，是有什么权限吗

**Comment by zhangdaiscott** [comment]
生成默认没生成高级查询，可以手工加上这个逻辑

**Comment by main-key** [comment]
这个功能挺不错的，为什么不默认加上呢，是不是有什么安全BUG啥的
