### ISSUE TITLE
【系统通知】发送指定对象只能在一个分页里面，不能叠加

### ISSUE THREAD

**Issue by kangshifu1** [zhangdaiscott/jeecg-boot#513]
##### 版本号：
2.0.1

##### 问题描述：
期望可以在多个分页的里面查看 并选择数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12906159/64340964-ee29fe00-d019-11e9-9e68-ee7f65a1809c.png)
![image](https://user-images.githubusercontent.com/12906159/64340980-fb46ed00-d019-11e9-987f-763306766fb0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
了解，后面会修改，增加参数，允许自定义配置，是否在翻页的时候，保存前一页选中的数据

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
