### ISSUE TITLE
【常用案例】一对多edittable 编辑数据 新增机票后 提示成功但是并没有保存进去

### ISSUE THREAD

**Issue by kangshifu1** [zhangdaiscott/jeecg-boot#514]
##### 版本号：
2.0.1

##### 问题描述：
一对多edittable 编辑数据 新增机票后 提示成功但是并没有保存进去

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12906159/64341397-d56e1800-d01a-11e9-83d7-cd4c6bbd6099.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by kangshifu1** [comment]
![image](https://user-images.githubusercontent.com/12906159/64341483-064e4d00-d01b-11e9-8cce-c0cc94305527.png)
![image](https://user-images.githubusercontent.com/12906159/64341496-0ea68800-d01b-11e9-8d1e-f9167fb7d0d6.png)
{createBy: "admin", ctype: "2", orderMoney: 1231, createTime: "2019-09-05 20:18:36", updateBy: "admin",…}
content: "23123"
createBy: "admin"
createTime: "2019-09-05 20:18:36"
ctype: "2"
id: "1169585622828134402"
jeecgOrderCustomerList: [,…]
jeecgOrderTicketList: []
orderCode: "12312"
orderDate: "2019-09-05 20:18:31"
orderMoney: 1231
updateBy: "admin"
updateTime: "2019-09-05 20:20:04"

**Comment by zhangdaiscott** [comment]
重复问题，关闭这个
https://github.com/zhangdaiscott/jeecg-boot/issues/505
