### ISSUE TITLE
更新指定字段时报错

### ISSUE THREAD

**Issue by guangshuowang** [zhangdaiscott/jeecg-boot#516]
##### 版本号：
2.0.2，2019年8月23日下载的master源码

##### 问题描述：
在service层调用update(updatewraper)，或者mapper.update(null,updatewraper)方法的时候会报空指针异常，亲测这不是mybatis-plus的问题，相同场景单独测试项目已模拟mybatis-plus（3.1.2和3.2.0版本）update api正常

##### 截图&代码：
![1](https://user-images.githubusercontent.com/17266306/64423249-9dc5a580-d0d8-11e9-83be-c22f61d3524c.jpg)
![2](https://user-images.githubusercontent.com/17266306/64423285-bafa7400-d0d8-11e9-8b6d-c80877fb906a.png)

第二张图中的方法进去参数是null，直接报空指针
boolean update = demoService.update(Wrappers.<Demo>lambdaUpdate()
				.set(Demo::getAge, 1)
				.eq(Demo::getId, "7"));
		Assert.isTrue(update, "更新失败");
		int res = demoMapper.update(null, Wrappers.<Demo>lambdaUpdate()
				.set(Demo::getAge, 1)
				.eq(Demo::getId, "7"));
		Assert.isTrue(res == 1, "更新失败");

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by guangshuowang** [comment]
这个问题怎么这么久了也没回复呢

**Comment by eternityzhang** [comment]
![image](https://user-images.githubusercontent.com/31660451/66380388-e7f8ba00-e9e9-11e9-949a-f2f144fcc4b1.png)
![image](https://user-images.githubusercontent.com/31660451/66380506-3017dc80-e9ea-11e9-91ef-bc014b029bf5.png)

我也遇到你说的这个问题了,打了下断点,是项目中MybatisInterceptor拦截器的问题.
因为你第一个参数为null,他取得就是第一个参数,所以空指针了,我也正在找解决方法呢.

还有一个问题就是,在xml中手写批量更新的时候,updateBy和updateTime都没有更新

**Comment by eternityzhang** [comment]
貌似他这个方法中更新这块代码是专门针对mybatis plus封装的更新方法写的,
普通手写xml的更新实现不了注入更新时间和更新人,
在第一个参数为null的时候就报错了,
companyService.updateBatch(null, null,"test1","test2");
上面的就报错,因为parameter为null了
取巧的方法,就是parameter为null时直接跳过注入过程,继续执行,
这样暂时解决了报错的问题,但是实现不了updateBy和updateTime注入了
![image](https://user-images.githubusercontent.com/31660451/66383228-378db480-e9ef-11e9-95a5-64b03e81783e.png)

**Comment by zhangdaiscott** [comment]
新版已经发布修复，感谢
