### ISSUE TITLE
Online表单“详情”和“编辑”按钮交替点击时，输入框内没有值

### ISSUE THREAD

**Issue by HanSunyi** [zhangdaiscott/jeecg-boot#519]
##### 版本号：
jeecg boot 2.0.1
##### 问题描述：
重现步骤：
1、配置一个类型为“单表类型”的“普通表单”的在线表单到菜单中，并给用户配置该菜单的权限
2、创建一条数据，并选中
3、点击一次“编辑”（首次显示正常）
4、点击详情（此次输入框内无数据）
5、重复步骤3、4，输入框内一直无数据
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/16067355/64471008-83460780-d17e-11e9-857e-23799596b538.png)
![图片](https://user-images.githubusercontent.com/16067355/64471025-9fe23f80-d17e-11e9-82c2-2af4802f2e96.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题发现了，下个版本会修复
