### ISSUE TITLE
定时任务有bug 

### ISSUE THREAD

**Issue by DexSinis** [zhangdaiscott/jeecg-boot#520]
##### 问题描述：
定时任务跑着跑着 就不跑了，看表是出了问题之后就不会再跑下一次

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14175683/64472159-ad062b00-d18c-11e9-85e0-6da09f3527d7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lu172195219** [comment]
定时任务的 问题。  设置corn表达式 每1分钟执行一次，实际执行是2分钟执行一次。

**Comment by lu172195219** [comment]
带参数的定时任务，会因为不知名的原因（没有报错信息）中断，中断后接下去不再执行

**Comment by DexSinis** [comment]
是的，我换了一种写法，就不会出现这种情况了 我感觉是你集成这个定时框架哪里出现了问题

**Comment by zhangdaiscott** [comment]
换个写法？

**Comment by lu172195219** [comment]
请问你说的换个写法是什么意思，是java代码 还是 corn表达式

**Comment by zhangdaiscott** [comment]
这个问题是指corn表达式有问题吗？

**Comment by lu172195219** [comment]
应该不是corn表达式的原因，corn表达式是通过页面工具生成的。  之前也都用过，不会错的。

**Comment by lu172195219** [comment]
带参数会中断的问题，有时候碰到有时候又好，至今搞不懂原因。

**Comment by zhangdaiscott** [comment]
@DexSinis 说换个写法就好了？ 是怎么个写法

**Comment by DexSinis** [comment]
@zhangdaiscott 参考
https://github.com/lanjerry/quartz-demo

**Comment by DexSinis** [comment]
@lu172195219 有计划做springcloud版本么

**Comment by lu172195219** [comment]
> @lu172195219 有计划做springcloud版本么

暂时还没这个需求。

**Comment by DexSinis** [comment]
埋点监控 有考虑模块有考虑完善么

**Comment by yangzhiwei666** [comment]
我新增无参的定时任务可以跑，一旦重启系统就改写了sql里的字段，导致不跑了，请问有什么解决方案

**Comment by zhangdaiscott** [comment]
有异常吗？ 或者报错信息，我们这边没遇到过

**Comment by 1001Hyb** [comment]
一样的问题  立即执行 单次没有问题， 定时执行几次就不跑了，应该是线程阻塞了，execute方法没有被定时调用。有大佬解决了请分享一下，我的jeecg的版本是2.4.6

**Comment by niezixu** [comment]
> 一样的问题 立即执行 单次没有问题， 定时执行几次就不跑了，应该是线程阻塞了，execute方法没有被定时调用。有大佬解决了请分享一下，我的jeecg的版本是2.4.6

我也是遇到同样的问题，看样子是没人解决咯？
