### ISSUE TITLE
角色配置数据权限的问题

### ISSUE THREAD

**Issue by guangshuowang** [zhangdaiscott/jeecg-boot#521]
##### 版本号：
2.0.2

##### 问题描述：
进入角色授权，选择有数据权限的菜单进行数据权限设置，第一次点击菜单，会正常出现当前菜单下配置的数据权限，第二次点击就会显示无配置信息，这个时候后台日志显示传过去的权限id是undefined，这两种情况是交替出现的

##### 截图&代码：
![0](https://user-images.githubusercontent.com/17266306/64474390-0bd89e00-d1a7-11e9-8fa4-3bc14a79a8ae.png)
![1](https://user-images.githubusercontent.com/17266306/64474392-0da26180-d1a7-11e9-9d45-d4341b68e10c.png)
![2](https://user-images.githubusercontent.com/17266306/64474413-404c5a00-d1a7-11e9-89cc-10f76dd45364.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经重现，感谢

**Comment by zhangdaiscott** [comment]
解决，下个版本发布
