### ISSUE TITLE
代码生成器

### ISSUE THREAD

**Issue by zzs583520** [zhangdaiscott/jeecg-boot#522]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/20652767/64511703-701a6f80-d317-11e9-9637-ba7895aef6b7.png)
![image](https://user-images.githubusercontent.com/20652767/64511750-86283000-d317-11e9-8f45-9b2f650d6921.png)
我保证我的数据库中存在这个表

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
数据库是否区分大小写？
远程是否能链接成功？

**Comment by zzs583520** [comment]
数据库是不区分大小写的，我能肯定配置的地址是可以链接上的。但是不确定当前的代码生成器是否对接成功

**Comment by zhangdaiscott** [comment]
换my5.7远程的时候，看看是不是mysql 8的问题

**Comment by zzs583520** [comment]
我本地装了一个5.7的数据库，但是还是找不到表
