### ISSUE TITLE
所有模块的部门列表都打不开，显示资源未找到

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#523]
##### 版本号：
2.1.0

##### 问题描述：
不管是用户列表里的部门选择弹窗，还是我的部门，都无法显示部门列表，system包前后台我都没改过

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49867691/64513007-30a15280-d31a-11e9-8fcf-7ba57e29107e.png)
![image](https://user-images.githubusercontent.com/49867691/64513040-46af1300-d31a-11e9-9807-fb165700ed11.png)
![image](https://user-images.githubusercontent.com/49867691/64513067-54fd2f00-d31a-11e9-9016-eebc0fca21e5.png)
![image](https://user-images.githubusercontent.com/49867691/64513142-73632a80-d31a-11e9-8a51-67bfeb59d6f3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
改项目名字了？
https://jeecg-boot.mydoc.io/?t=345683
![image](https://user-images.githubusercontent.com/3162115/64515760-c68bac00-d31f-11e9-9917-47e82fcbddbc.png)

**Comment by dskl1** [comment]
没改过，和上面的一样
