### ISSUE TITLE
登录页面，自动登录选项点击报错

### ISSUE THREAD

**Issue by wangkaiChen1118** [zhangdaiscott/jeecg-boot#525]
##### 版本号：
2.1.0

##### 问题描述：
登录页面，点击自动登录时，控制台报错
[Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event 
##### 截图&代码：
![image](https://user-images.githubusercontent.com/51146877/64593963-ab817080-d3e1-11e9-931c-f417491e84d1.png)
代码中
![image](https://user-images.githubusercontent.com/51146877/64594043-ce138980-d3e1-11e9-8577-6fa7020432d5.png)
此处提供的就是一个 布尔值
![image](https://user-images.githubusercontent.com/51146877/64594099-e84d6780-d3e1-11e9-992b-290322be7b6f.png)
不明白为什么，得到的是一个 event ，事件对象？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wangkaiChen1118** [comment]
> ##### 版本号：
> 2.1.0
> 
> ##### 问题描述：
> 登录页面，点击自动登录时，控制台报错
> [Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/51146877/64593963-ab817080-d3e1-11e9-931c-f417491e84d1.png)
> 代码中
> ![image](https://user-images.githubusercontent.com/51146877/64594043-ce138980-d3e1-11e9-8577-6fa7020432d5.png)
> 此处提供的就是一个 布尔值
> ![image](https://user-images.githubusercontent.com/51146877/64594099-e84d6780-d3e1-11e9-992b-290322be7b6f.png)
> 不明白为什么，得到的是一个 event ，事件对象？
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
演示系统没有报错
![image](https://user-images.githubusercontent.com/3162115/64594564-dae4ad00-d3e2-11e9-9348-2b3c56ea7cb8.png)

**Comment by wangkaiChen1118** [comment]
你的演示系统，在线的控制台打印都取消掉了吧？？




------------------ 原始邮件 ------------------
发件人: "JEECG开源社区"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 下午3:51
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>; 
抄送: "Chenwangkai"<1143410797@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeecg-boot] 登录页面，自动登录选项点击报错 (#525)




演示系统没有报错

**Comment by chenshouzuo** [comment]
> 你的演示系统，在线的控制台打印都取消掉了吧？？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "JEECG开源社区"<notifications@github.com>; 发送时间: 2019年9月10日(星期二) 下午3:51 收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>; 抄送: "Chenwangkai"<1143410797@qq.com>; "State change"<state_change@noreply.github.com>; 主题: Re: [zhangdaiscott/jeecg-boot] 登录页面，自动登录选项点击报错 (#525) 演示系统没有报错 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

我也遇到相同的问题，请问你是如何解决的？

**Comment by wangkaiChen1118** [comment]
> > 你的演示系统，在线的控制台打印都取消掉了吧？？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "JEECG开源社区"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年9月10日(星期二) 下午3:51 收件人: "zhangdaiscott/jeecg-boot"[jeecg-boot@noreply.github.com](mailto:jeecg-boot@noreply.github.com); 抄送: "Chenwangkai"[1143410797@qq.com](mailto:1143410797@qq.com); "State change"[state_change@noreply.github.com](mailto:state_change@noreply.github.com); 主题: Re: [zhangdaiscott/jeecg-boot] 登录页面，自动登录选项点击报错 (#525) 演示系统没有报错 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 我也遇到相同的问题，请问你是如何解决的？



> > 你的演示系统，在线的控制台打印都取消掉了吧？？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "JEECG开源社区"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年9月10日(星期二) 下午3:51 收件人: "zhangdaiscott/jeecg-boot"[jeecg-boot@noreply.github.com](mailto:jeecg-boot@noreply.github.com); 抄送: "Chenwangkai"[1143410797@qq.com](mailto:1143410797@qq.com); "State change"[state_change@noreply.github.com](mailto:state_change@noreply.github.com); 主题: Re: [zhangdaiscott/jeecg-boot] 登录页面，自动登录选项点击报错 (#525) 演示系统没有报错 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 我也遇到相同的问题，请问你是如何解决的？



> > 你的演示系统，在线的控制台打印都取消掉了吧？？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "JEECG开源社区"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年9月10日(星期二) 下午3:51 收件人: "zhangdaiscott/jeecg-boot"[jeecg-boot@noreply.github.com](mailto:jeecg-boot@noreply.github.com); 抄送: "Chenwangkai"[1143410797@qq.com](mailto:1143410797@qq.com); "State change"[state_change@noreply.github.com](mailto:state_change@noreply.github.com); 主题: Re: [zhangdaiscott/jeecg-boot] 登录页面，自动登录选项点击报错 (#525) 演示系统没有报错 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 我也遇到相同的问题，请问你是如何解决的？

我就直接把这个自动登录模块给干掉了，解决不了
