### ISSUE TITLE
部署到linux服务器之后，在已登录的情况下，直接访问登陆界面，显示404

### ISSUE THREAD

**Issue by PinkMango** [zhangdaiscott/jeecg-boot#526]
##### 版本号：
2.0.2

##### 问题描述：
部署到linux服务器之后，在已登录的情况下，直接访问登陆界面http://xxx/user/login，显示404

##### 截图&代码：

![image](https://user-images.githubusercontent.com/29477082/64662130-ea630500-d479-11e9-9d2f-3d05699f7004.png)

![image](https://user-images.githubusercontent.com/29477082/64662194-18e0e000-d47a-11e9-9344-8c89002448c3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://jeecg-boot.mydoc.io/?t=345682

**Comment by PinkMango** [comment]
是按照文档配置的....
