### ISSUE TITLE
war方式部署tomcat报错

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#527]
##### 版本号：

2.1.0
##### 问题描述：
war包解包出错，完全按照技术文档做的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49867691/64678112-83f6da80-d4ab-11e9-83dc-d66d11f2a892.png)
![image](https://user-images.githubusercontent.com/49867691/64678133-8ce7ac00-d4ab-11e9-8e62-deae633ba66f.png)
![image](https://user-images.githubusercontent.com/49867691/64678147-93762380-d4ab-11e9-9466-78fbd37775d8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
tomcat几？

**Comment by dskl1** [comment]
8

**Comment by zhangdaiscott** [comment]
按照这个文档不会有问题，测试过
http://doc.jeecg.com/1273923
