### ISSUE TITLE
数据权限问题

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#528]
##### 版本号：
2.1.0

##### 问题描述：
同一个URL 设置两种不同权限，分别给不同角色使用，
权限过滤只根据 URL 查询数据库 未判断角色是否拥有，导致查询出两条权限，程序抛出异常

##### 截图&代码：

![image](https://user-images.githubusercontent.com/50865430/64747837-d0412980-d542-11e9-82ca-f0f4ec7b7b7f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
已经改造，下个版本发布

**Comment by Nicky213Zhang** [comment]
@zhangdaiscott 请问下个版本什么时候能发呀，我们已经用在生产环境了，数据权限的问题困扰好几天了，请帮帮忙

**Comment by zhangdaiscott** [comment]
不改也可以，其实是你的用法不对，同一个请求不应该配置多个菜单。
你应该针对不同的角色，授权不同的数据权限规则
