### ISSUE TITLE
权限配置bug

### ISSUE THREAD

**Issue by Sellenite** [zhangdaiscott/jeecg-boot#529]
##### 版本号：

当前最新版本： 2.1.0（发布日期：20190826）

##### 问题描述：

使用角色权限配置时，在父子没有关联的前提下，点击一级菜单，这时候再点击父子关联选项，菜单自动关联后，点击保存，这时候实际保存的选项只有关联前的一级菜单id，自动关联的菜单没有加进去

##### 截图&代码：

前端代码，这个可能是antd的tree组件的固有问题，看可否能通过其他方式修复

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述太抽象，请截图或者录个视频

**Comment by Sellenite** [comment]
> 描述太抽象，请截图或者录个视频

##### 操作方式：
![test3](https://user-images.githubusercontent.com/23151382/65308978-c2804980-dbbd-11e9-82fe-2bbf57eb4074.gif)

实际只有两个权限id，勾选了关联后，上传的id其实还是之前那两个，然后会带有以下问题：

如果默认是关联的话，返回的是一级菜单的id权限和其中一个二级菜单的权限，但在菜单里会显示全部都勾选了，让人以为自己有全部权限，实际并不是

![test4](https://user-images.githubusercontent.com/23151382/65309392-944f3980-dbbe-11e9-942b-4e4eb94023a5.gif)

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
此问题已经修复，请更新最新代码
