### ISSUE TITLE
数据权限通过SYS_ORG_CODE控制需要自己在添加数据的时候赋值吗

### ISSUE THREAD

**Issue by sunguangsheng** [zhangdaiscott/jeecg-boot#53]
想要数据权限通过SYS_ORG_CODE控制需要自己在添加数据的时候给SYS_ORG_CODE赋值吗

**Comment by zhangdaiscott** [comment]
不需要，需要给表加上对应字段

**Comment by sunguangsheng** [comment]
我在表中加了字段但是不会自动赋值，我看了一下代码，应该是在mybatis拦截器中没有给赋值吧，我改改这个拦截器应该就行了吧

**Comment by zhangdaiscott** [comment]
麻烦详细发出你的配置，默认会自动注入的

**Comment by xwsg** [comment]
我给表加上sys_org_code 字段后，添加数据时并没有自动注入，麻烦确认一下

**Comment by zhangdaiscott** [comment]
这个逻辑还没写

**Comment by zhangdaiscott** [comment]
已经解决下个版本发布
