### ISSUE TITLE
vue.config.js 中配置覆盖默认主题颜色不完整

### ISSUE THREAD

**Issue by wangkaiChen1118** [zhangdaiscott/jeecg-boot#530]
##### 版本号：
2.1.0

##### 问题描述：
在vue.config.js 中更改默认主题颜色为 pink
![image](https://user-images.githubusercontent.com/51146877/64762711-3d6bb380-d571-11e9-8c88-fc725e5d5c5f.png)
重启项目后，发现左侧菜单栏，按钮和其他一些 ant-design-vue 的主题色的确覆盖为了pink，
但是导航栏的背景色还是浅蓝色，
请问是需要单独覆盖吗？？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/51146877/64762995-b408b100-d571-11e9-9b67-82103bb6d3c2.png)
![image](https://user-images.githubusercontent.com/51146877/64763040-c84cae00-d571-11e9-9e88-9a9e132c1fd3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
目前这一块似乎是固定的，没有与主题，less变量关联，而且目前这里使用的是sass，可行的方式是需要把组件中的sass转换到less（我在网上找了一下，less转sass在线的工具有，sass转less的较少，https://csspre.com/convert/ ，这块大概只能靠人工转换），因为vue-antd, vue-antd-pro主要是用的都是less而不是sass，这两个之间的变量应该是不能共用的，然后在需要与主题关联的地方使用less中定义的相关变量。
![image](https://user-images.githubusercontent.com/2276718/65828300-efbead00-e2cb-11e9-96d4-58f0bf231772.png)
![image](https://user-images.githubusercontent.com/2276718/65828365-b3d81780-e2cc-11e9-83fc-19f79031f770.png)


其他参考资料：
https://vue.ant.design/docs/vue/customize-theme-cn/
https://pro.loacg.com/docs/theme

**Comment by liudonghua123** [comment]
刚才上面写的sass，scss有点混乱，捋一捋 

https://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass

![image](https://user-images.githubusercontent.com/2276718/65828571-d4a16c80-e2ce-11e9-8de8-67de11b31c02.png)

**Comment by liudonghua123** [comment]
刚才看了一下，从 sass（不是scss）转换到 less 其实很方便，看一会 http://lesscss.org/ 这个就搞定了

![image](https://user-images.githubusercontent.com/2276718/65828733-7ecdc400-e2d0-11e9-9ddf-24710f8725f3.png)
