### ISSUE TITLE
数据权限问题，请求作者帮忙

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#532]
##### 版本号：
当前最新版本： 2.1.0（发布日期：20190826）

##### 问题描述：
系统部门管理模块无法添加数据权限问题，@PermissionData(pageComponent="system/DepartList")无效，发现问题为：

##### 截图&代码：
![1](https://user-images.githubusercontent.com/25654842/64773884-b83ec980-d585-11e9-829d-0c8aa3086749.png)
![2](https://user-images.githubusercontent.com/25654842/64773984-ef14df80-d585-11e9-82bb-ecdfa5dd95a0.png)
![3](https://user-images.githubusercontent.com/25654842/64773997-f20fd000-d585-11e9-978f-9c8fca12cd92.png)
问题：没有走mybatis-plus查询条件的就没办法动态加入数据权限范围的sql，请问有办法可以解决吗

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题已经处理，新版发布
