### ISSUE TITLE
JTreeSelect能否支持多选

### ISSUE THREAD

**Issue by jiangkun1151** [zhangdaiscott/jeecg-boot#533]
##### 版本号：
2.1.0

##### 问题描述：
目前JTreeSelect文档中没有复选框的属性，只能单选，这个能否改造成多选的下拉树
或者能否指导下如何在JTreeSelect中改造？

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持，拓展一个多选属性就可以 multiple
https://vue.ant.design/components/tree-select-cn/

**Comment by zhangdaiscott** [comment]
已经改造完成，下个版本发布
