### ISSUE TITLE
打包后的js文件太大了

### ISSUE THREAD

**Issue by vicviz** [zhangdaiscott/jeecg-boot#535]
##### 问题描述：
js全下载，调试版本50M,编译版本开gzip 7M, 手机打开太卡了,PC也很卡，请问有什么办法减文件大小吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2442699/64902054-15946100-d6d3-11e9-944a-e4d768f81a7c.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/64902519-b63a4f00-d6da-11e9-8db0-918662ad7f52.png)


没你说的那么大，部署的时候开启gzip压缩很快

**Comment by zhangdaiscott** [comment]
五、nginx 开启压缩，提高首页访问效率
https://github.com/zhangdaiscott/jeecg-boot/issues/88

**Comment by xiuxiuyifan** [comment]
您找到好的方法了吗？？？

**Comment by zhangdaiscott** [comment]
参考下
https://www.toutiao.com/a6748197625532514828/?timestamp=1571456800&app=news_article_lite&group_id=6748197625532514828&req_id=2019101911463901001404703126A26BF8
https://www.cnblogs.com/wangtaolearning/p/11234645.html
