### ISSUE TITLE
2.1版本开源版前台调整的online模块打包JS中项目名

### ISSUE THREAD

**Issue by gjl0924** [zhangdaiscott/jeecg-boot#536]
##### 问题描述：
2.1版本开源版前台调整的online模块打包JS中项目名，提示资源未找到。后台java如何调整。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44
