### ISSUE TITLE
在进行角色菜单授权时提示没有权限

### ISSUE THREAD

**Issue by snkever** [zhangdaiscott/jeecg-boot#5369]
##### 版本号：

3.5.4
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在进行角色菜单授权时提示没有权限

##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/7539c703-cee9-40ae-83d7-d67fc9a0a539)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的数据库是用的那个脚本？

**Comment by snkever** [comment]
数据库也升级到了3.5.5
