### ISSUE TITLE
jeecg-boot版本online表单在线开发功能，在修改前后台上下文之后，页面打开之后提示资源未找到

### ISSUE THREAD

**Issue by gjl0924** [zhangdaiscott/jeecg-boot#538]
##### 版本号：
2.1

##### 问题描述：
jeecg-boot版本online表单在线开发功能，在修改前后台上下文之后，页面打开之后提示资源未找到

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34853851/64933923-04d21f80-d87a-11e9-806f-bfd2f7c3cbf9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1

44
