### ISSUE TITLE
war包部署tomcat报错

### ISSUE THREAD

**Issue by dskl1** [zhangdaiscott/jeecg-boot#539]
##### 版本号：

2.1
##### 问题描述：
同样的配置，我试了2.0.1和2.0.2，tomcat都部署正常，2.1就报错，是2.1新增了什么，某些地方我没修改吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49867691/64939991-5cca4f80-d895-11e9-93dd-46bd285d5c69.png)
![image](https://user-images.githubusercontent.com/49867691/64940062-99964680-d895-11e9-8bae-32589039ea15.png)
![image](https://user-images.githubusercontent.com/49867691/64940078-a3b84500-d895-11e9-980c-b5e14fe26ea6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
加了websocket，你是tomcat几支持websocket吗

**Comment by dskl1** [comment]
tomcat8,需要特别设置什么吗

**Comment by zhangdaiscott** [comment]
按道理是不需要，我这边没遇到过，你百度看看

**Comment by dskl1** [comment]
我的tomcat端口号用的8089，和这个用关系吗

**Comment by dskl1** [comment]
https://blog.csdn.net/qq_18649209/article/details/79529434
按照上面的做就正常了

**Comment by zhangdaiscott** [comment]
好的
