### ISSUE TITLE
关于页面回来切换再切回原页面后清除界面内容的问题：（客户反馈此问题严重影响交互，用户体验）。

### ISSUE THREAD

**Issue by judgerzhang** [zhangdaiscott/jeecg-boot#540]
##### 版本号：
前端，所有版本
##### 问题描述：        
        现在打开多个菜单，当切换到其他菜单后，再切回来原来界面上的数据全部被初始清空（这样对用户来说非常痛苦），建议修改菜单加载（优化），新的已经存在的直接切换而无需重新加载。
        谢谢 团队的努力。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个是考虑到业务操作数据已经变了，你再次访问不需要重新加载页面，不然出现数据混乱问题。
如果觉得这个不好，可以自己改，加上路由缓存，系统性能还会更快

**Comment by rjliulei** [comment]
在线表单生成的页面如何配置路由缓存？
