### ISSUE TITLE
表单生成bug

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#541]
##### 版本号：
2.1.0

##### 问题描述：
导入表单配置，选择页表和form页显示字段，无论怎么选，生成的代码都是全部，选择抽屉也无效，始终是弹窗

##### 截图&代码：
![1](https://user-images.githubusercontent.com/25654842/65008427-e896b700-d93b-11e9-9dcb-9b5030124935.png)
![2](https://user-images.githubusercontent.com/25654842/65008440-f5b3a600-d93b-11e9-87c9-53289560ea52.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Nicky213Zhang** [comment]
补充：生成的modal页，字典对象也有问题
![3](https://user-images.githubusercontent.com/25654842/65009076-09600c00-d93e-11e9-8767-e1d2e724f52b.png)
dictCode=""会多出俩个逗号，导致解析不了字典

**Comment by zhangdaiscott** [comment]
还没实现

**Comment by zhangdaiscott** [comment]
暂时关闭，争取尽快升级代码生成器【专项工作】
