### ISSUE TITLE
单选框DictSelectTag 标签无法触发事件

### ISSUE THREAD

**Issue by jiangkun1151** [zhangdaiscott/jeecg-boot#543]
##### 版本号：
2.1.0

##### 问题描述：
封装的<j-dict-select-tag 或 <DictSelectTag单选框 无法触发@change 、@select等事件，我需要选项做其他数据的绑定用DictSelectTag无法触发，多选框或 <a-select 标签是可以触发的，请问还有什么方式可以帮忙解决

##### 截图&代码：
<j-dict-select-tag  v-model="queryParam.sex" placeholder="请输入用户性别"
                  dictCode="sex"/>
或
<DictSelectTag  v-model="queryParam.sex" placeholder="请输入用户性别" dictCode="sex" @change="handlechange"/>

    methods: {
      handleChange(e){
      console.log("-----"+e);       
   }
}
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
加上属性
:triggerChange="true"

http://doc.jeecg.com/1273909
