### ISSUE TITLE
代码生成器，表xxx在库中不存在

### ISSUE THREAD

**Issue by sleeeeeeepa** [zhangdaiscott/jeecg-boot#544]
##### 问题描述：
使用代码生成器提示 表 [ xxx] 在数据库中，不存在 ！请确认数据源配置是否配置正确、表名是否填写正确~ 
代码生成器的jeecg_database.properties 已经和application-dev.yml 中数据库配置一样，而项目可以正常使用说明数据库配置正常，表也选用项目导入的表依然不行

##### 问题截图：
![输入图片说明](https://images.gitee.com/uploads/images/2019/0917/182707_8060d353_1249808.png "屏幕截图.png")

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
数据库名配置了吗
![image](https://user-images.githubusercontent.com/3162115/65056623-c769b100-d9a3-11e9-9abc-1a5222904415.png)

**Comment by zhangdaiscott** [comment]
如何没有新问题反馈，此问题先关闭了

**Comment by sleeeeeeepa** [comment]
配置了  ， 也是不行 数据库是docker里的5.7



------------------ 原始邮件 ------------------
发件人: "JEECG开源社区"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 晚上11:35
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "...."<631617479@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] 代码生成器，表xxx在库中不存在 (#544)




数据库名配置了吗

**Comment by zhangdaiscott** [comment]
把你的配置和环境，详细贴出来
