### ISSUE TITLE
CAS集成问题

### ISSUE THREAD

**Issue by jiawenzhe** [zhangdaiscott/jeecg-boot#545]
##### 版本号：
2.0

##### 问题描述：
集成CAS以后，通过cas输入账号密码，登录成功后跳转，前端登录网页控制台提示Token已失效，请重新登录，然后一直加载登录动画

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/30572750/65096293-0412c800-d9f7-11e9-90a8-7a739699299f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请按照文档
http://doc.jeecg.com/1273851

**Comment by jiawenzhe** [comment]
就是按照文档的方式，对代码进行集成的但是，出现了上述问题

**Comment by liuhaonan0422** [comment]
大佬请问这个问题解决了吗，我这边遇到了一模一样的问题按照官网文档配置的
