### ISSUE TITLE
更改defaultSettings 的primaryColor 后出现异常

### ISSUE THREAD

**Issue by zgwangweijian** [zhangdaiscott/jeecg-boot#551]
##### 问题描述：
更改defaultSettings 的primaryColor 后出现异常，
页面一直提示正在编译主题，不消失，
控制台报错 window.less.modifyVars is not a function

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此bug已经解决，新版会修复

**Comment by ycw01** [comment]
> 此错误已经解决，新版会修复

大佬，怎么解决？
