### ISSUE TITLE
JEditableTable setValues 设置某行值无效

### ISSUE THREAD

**Issue by hzyyy** [zhangdaiscott/jeecg-boot#552]
##### 版本号：
v2.0

##### 问题描述：
使用JEditableTable setValues 主动设置表格中某行某列的值无效；视图不更新；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33852158/65219363-fdfe1380-daea-11e9-8a22-143399173d23.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by hzyyy** [comment]
补充：
this.$refs.invoiceLine.getAll(true).then( all => console.log(all) )
打印数据，指定行lineAmount 成功赋值9999999；因此认为，数据源更新了，但是视图没更新；

**Comment by zhangdaiscott** [comment]
你的版本太老了，你升级2.1试试

**Comment by hzyyy** [comment]
> 你的版本太老了，你升级2.1试试

如果针对于JEditableTable 的升级，需要升级哪些文件呢；因为项目即将上线了，因此不想改动太多；

**Comment by zhangdaiscott** [comment]
ant-design-jeecg-vue\src\components\jeecg\JEditableTable.vue

**Comment by hzyyy** [comment]
升级了此文件，依然视图不刷新。

**Comment by zhangdaiscott** [comment]
替换这个附件试试

**Comment by hzyyy** [comment]
好的，谢谢

**Comment by shanggushenlong** [comment]
@hzyyy 你好，打扰一下，向你请教一下，这个 JEditableTable 这个是否是由代码生成器生成的，如果是的话，请问是那一套代码模板？？

**Comment by hzyyy** [comment]
嗨； JEditableTable 这个文件是属于配置文件；我猜你应该用过jeecg 的第一版本。这个版本和第一版本很不一样；你在JEditableTable 里配置的代码，是不会生成新的文件的，只会将配置数据以json 的数据保存到数据库；前端拿到相对应的配置数据，动态生成表格。

**Comment by shanggushenlong** [comment]
你好，打扰你了，抱歉，我没有太懂你的意思，jeecg我还没有用过，我直接用的就是jeecgboot版本的，由于我用过代码生成器生成过代码，所以想问你关于这个组件的使用方法，你的意思是说，这个组件是不会根据数据库中的表来生成页面的？？而且这个也不是代码生成器生成的，我如果想要写页面的话，就必须自己手动写入这个组件？？是这个意思吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hzyyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午4:29
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JEditableTable setValues 设置某行值无效 (#552)




嗨；  JEditableTable 这个文件是属于配置文件；我猜你应该用过jeecg 的第一版本。这个版本和第一版本很不一样；你在JEditableTable 里配置的代码，是不会生成新的文件的，只会将配置数据以json 的数据保存到数据库；前端拿到相对应的配置数据，动态生成表格。

**Comment by hzyyy** [comment]
jeecg-boot 即时jeecg；jeecg的表单配置是不会自动生成页面文件的；都只会使用一个由jeecg提供的通用的.vue 文件。

**Comment by shanggushenlong** [comment]
呃，我还是没有太懂，那如果我现在像用这种效果的话，该怎么引入呢？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hzyyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午4:48
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JEditableTable setValues 设置某行值无效 (#552)




jeecg-boot 即时jeecg；jeecg的表单配置是不会自动生成页面文件的；都只会使用一个由jeecg提供的通用的.vue 文件。

**Comment by hzyyy** [comment]
唔；我们公司这边对这个表单配置的代码进行了大规模的改动；我这边很难跟你讲清楚了。
我司当前的操作流程是：
  在表单配置页面当中，新建一个表单配置；
  这时，后端就会去处理这块的逻辑，将新建的表单会自动生成一个路径；新生成的路径将会在菜单管理中可以看到了。
  关于文件路径这一块，jeecg 提供的官网文档也有详细介绍，可以在jeecg 官方案例中找到菜单管理，进行了解；入门最好熟读文档 。
  后端生成的一个路径，经过jeecg 提供的前端代码解析后，会生成一个动态路由，前端根据路由进行跳转并解析页面。
  说真的，这个jeecg 项目想要了解其运作原理，是比较痛苦的，并且坑点也比较多；但是也有优秀的地方，比如菜单配置，以及菜单按钮权限配置。
  以及；除了jeecg 提供的表单配置页面之外，其余的地方，极度不推荐使用jeecg 封装的表格组件，坑点很多。可使用vand 提供的表格控件，毕竟jeecg 也是封装vantd 的。

**Comment by shanggushenlong** [comment]
好的好的，谢谢指教


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hzyyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午5:49
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] JEditableTable setValues 设置某行值无效 (#552)




唔；我们公司这边对这个表单配置的代码进行了大规模的改动；我这边很难跟你讲清楚了。
 我司当前的操作流程是：
 在表单配置页面当中，新建一个表单配置；
 这时，后端就会去处理这块的逻辑，将新建的表单会自动生成一个路径；新生成的路径将会在菜单管理中可以看到了。
 关于文件路径这一块，jeecg 提供的官网文档也有详细介绍，可以在jeecg 官方案例中找到菜单管理，进行了解；入门最好熟读文档 。
 后端生成的一个路径，经过jeecg 提供的前端代码解析后，会生成一个动态路由，前端根据路由进行跳转并解析页面。
 说真的，这个jeecg 项目想要了解其运作原理，是比较痛苦的，并且坑点也比较多；但是也有优秀的地方，比如菜单配置，以及菜单按钮权限配置。
 以及；除了jeecg 提供的表单配置页面之外，其余的地方，极度不推荐使用jeecg 封装的表格组件，坑点很多。可使用vand 提供的表格控件，毕竟jeecg 也是封装vantd 的。
