### ISSUE TITLE
online数据库导入后再编辑的表名问题

### ISSUE THREAD

**Issue by ford-ren** [zhangdaiscott/jeecg-boot#553]
##### 截图&代码：
![编辑异常](https://user-images.githubusercontent.com/41729574/65220796-24717e00-daee-11e9-9166-65311460af87.png)
![源码位置](https://user-images.githubusercontent.com/41729574/65220803-29cec880-daee-11e9-9c1b-a87dbd487cd0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你们这个命名很不规范，我们不能支持

**Comment by ford-ren** [comment]
谢谢
