### ISSUE TITLE
online从数据库导入表单，导入的表单字段长度为0

### ISSUE THREAD

**Issue by ford-ren** [zhangdaiscott/jeecg-boot#554]
##### 版本号：
2.1.0

##### 问题描述：
使用online表单开发的从数据库导入表单，导入表单的所有字段的长度都为0。数据库为postgresql数据库。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41729574/65226367-4e7c6d80-daf9-11e9-9dae-fcea8e4474d0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，我们确认下

**Comment by zhangdaiscott** [comment]
升级代码生成器

<dependency>
<groupId>org.jeecgframework.boot</groupId>
<artifactId>codegenerate</artifactId>
<version>1.0.7</version>
</dependency>
