### ISSUE TITLE
online表单功能，从数据库导入时把数据库本身的配置表、内置表都查出来了

### ISSUE THREAD

**Issue by F-T-Jen** [zhangdaiscott/jeecg-boot#555]
##### 版本号：
2.1.0

##### 问题描述：
online表单功能，从数据库导入时把数据库本身的配置表、内置表都查出来了.这样很容把数据库搞出问题啊。数据库为PostgreSql，框架很多地方对postgres不兼容。如postgresql对大小写不敏感，而有些数据表的字段为大写，查询时会提示字段不存在（如qrtz_的表）。希望改进。

##### 截图&代码：
![数据库表1](https://user-images.githubusercontent.com/41729574/65233337-3c083100-db05-11e9-8e88-f1dce7c9fd01.png)
![数据库表2](https://user-images.githubusercontent.com/41729574/65233343-3e6a8b00-db05-11e9-9ad0-2bc75977cae7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级代码生成器

`
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.0.7</version>
</dependency>`
