### ISSUE TITLE
online表单从数据导入后text类型转换错误

### ISSUE THREAD

**Issue by F-T-Jen** [zhangdaiscott/jeecg-boot#557]
##### 版本号：
2.1.0

##### 问题描述：
postgresql数据库环境下：online表单的“从数据库导入表单”功能，导入的表字段类型为text类型，导出后显示类型为string，且长度为0。测试mysql数据库的text类型是正确的，长度为65535

##### 截图&代码：

![image](https://user-images.githubusercontent.com/41729574/65291873-b5e0fe80-db87-11e9-8a53-c36f00fc6dbd.png)
![image](https://user-images.githubusercontent.com/41729574/65291899-d90bae00-db87-11e9-9e45-520b7e2ee61b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by F-T-Jen** [comment]
postgresql真是够了

**Comment by F-T-Jen** [comment]
框架对PostgreSql数据库不友好，很多地方兼容都有问题，忘早日修复，忘项目越来越完善

**Comment by galaxist** [comment]
忘记了就算了吧

**Comment by zhangdaiscott** [comment]
此问题已经修复，下个版本发布

**Comment by F-T-Jen** [comment]
> 忘记了就算了吧

要等到下个版本T_T
