### ISSUE TITLE
代码生成器行字段数目设置不生效

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#558]
##### 问题描述：
使用代码生成器时，设置行字段数目为3（表单一行布局三个字段），但生成的代码中，还是一行一个字段，设置未生效。

##### 截图&代码：

![截屏2019-09-2012 53 01](https://user-images.githubusercontent.com/9619081/65300474-2860d700-dba6-11e9-9653-5c5fd143ea9b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前还不支持

**Comment by zhangdaiscott** [comment]
暂时关闭，争取尽快升级代码生成器【专项工作】
