### ISSUE TITLE
Online在线功能ERP主题，从表记录被误删除

### ISSUE THREAD

**Issue by HolaFish** [zhangdaiscott/jeecg-boot#5591]
##### 问题描述：
Online在线功能，主表为ERP主题模板
问题：当**修改**一条主表记录后，该记录关联的**从表记录**会被删除

**Comment by zhangdaiscott** [comment]
有演示吗

**Comment by HolaFish** [comment]
已系统自带的订单表和订单明细表为例：
1. 将订单主表改为ERP模板
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/f75f5ba1-6926-4ad0-8b8a-a2785f4d6e07)
2. 选中一条订单记录，此时该条记录的订单产品明细和订单客户是有关联数据的
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/e058ba72-5f18-4add-8ba9-6802db3af157)
3. 修改选中订单记录的任意字段并保存，此时该记录关联的订单产品明细和订单客户记录被清空了(DB中的记录被清空）
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/bd3a9008-74b8-4969-b0ca-ff6a89f8a540)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布

**Comment by lzk97224** [comment]
这个目前有什么临时解决方案吗
