### ISSUE TITLE
codegenerate-1.0.2.jar 下载不下来

### ISSUE THREAD

**Issue by happy1990ts** [zhangdaiscott/jeecg-boot#56]
按照官方的maven设置也不行

**Comment by zhangdaiscott** [comment]
你应该配置其他私服了，把其他的私服注释掉

**Comment by happy1990ts** [comment]
我试过两遍，第一遍确实有其他私服，maven一波下载后，唯独 codegenerate-1.0.2.jar 缺失，然后我清除了本地仓库所有 *.lastUpdated 文件后，把setting.xml中的其他<mirror>全部注释掉，只保留Jeecg-Boot 技术文档提供的阿里云镜像，一波下载后，还是唯独缺失 codegenerate-1.0.2.jar
