### ISSUE TITLE
本地登陆一直显示进度条

### ISSUE THREAD

**Issue by xlsking** [zhangdaiscott/jeecg-boot#560]
##### 版本号：
2.0
##### 问题描述：
本地登陆后，提示登陆成功，但没有跳转到首页，还一直停留在登录页面，并且后台日志有登录退出。

##### 截图&代码：
登录页的首页top进度条一直停留在这个位置。
![image](https://user-images.githubusercontent.com/23182004/65305123-f73bd300-dbb4-11e9-9a3a-42b4c4735b78.png)
确定按钮一直在转圈圈
![image](https://user-images.githubusercontent.com/23182004/65305151-091d7600-dbb5-11e9-8748-f88ee54b3693.png)

请jeecg-boot 技术人员给予技术支持，给予解答，应该什么原因导致，如何处理？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你后台交互有问题
