### ISSUE TITLE
前端的静态资源过重，建议优化异步加载

### ISSUE THREAD

**Issue by htank-wang** [zhangdaiscott/jeecg-boot#561]
##### 版本号：
2.1.0

##### 问题描述：
静态资源文件过大，建议从两个方向优化：

1.  插件过多，过大。仅@jeecg/antd-onine源文件就有近3M
2. 组件 "resolve => require(['@/' + component+'.vue'], resolve)"这样的加载方式，会导致构建时将项目内所有组件及所依赖的插件构建在一起，建议优化为异步按需加载。

ps:动态路由很好很赞

##### 截图&代码：

![image](https://user-images.githubusercontent.com/17918845/65310224-6ec32f80-dbc0-11e9-8844-991cbef70d52.png)

**Comment by xiuxiuyifan** [comment]
开发环境下面，app.js 文件加载有20几M咋回事？能解决吗？？？

**Comment by htank-wang** [comment]
插件太多，你可以先删掉一部分试试。或者换成cdn引入。

**Comment by xiuxiuyifan** [comment]
你现在开发环境下面也这样吗？？，还有你说的这个问题打包之后的文件也大，你是怎么解决的？？？

**Comment by zhangdaiscott** [comment]
app.js  只有4k
你的环境有问题
![image](https://user-images.githubusercontent.com/3162115/65402186-74f31f00-ddff-11e9-8460-2b521a934492.png)

**Comment by xiuxiuyifan** [comment]
![image](https://user-images.githubusercontent.com/27720360/65402605-124f5280-de02-11e9-9ff5-28746b1da9ec.png)
我的app.js 文件这么大，在开发环境下面，不知道咋回事

**Comment by xiuxiuyifan** [comment]
![image](https://user-images.githubusercontent.com/27720360/65403365-e1711c80-de05-11e9-8886-769cce8086ee.png)
这个是我刚才刚从线上拉下来的代码

**Comment by xiuxiuyifan** [comment]
自己改异步是写成import 的方式吗?

**Comment by htank-wang** [comment]
改异步会比较麻烦，你还是根据自己的业务曾删插件吧。
比如：antd-onine（在线表单编辑近3M）viser-vue（图表，实际业务可能只要几个图表组件，也有好几M）等等。

**Comment by xiuxiuyifan** [comment]
好的就看 package.json下面的包自己不要的都删了，对吗？

**Comment by zhangdaiscott** [comment]
其实不影响，正式发布，开启Gzip压缩，很快

**Comment by xiuxiuyifan** [comment]
开发的时候很难受，正式发布我用webpack打了gzip的包，是没啥影响

**Comment by htank-wang** [comment]
肯定有影响，只是你们的业务对页面加载速度要求不高。所以我提的建议是优化。

**Comment by xiuxiuyifan** [comment]
好的，那我有时间把没用的删了
