### ISSUE TITLE
http://localhost:3000/jeecg-boot/online/cgform/head/queryTables/ 404 (Not Found)

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#562]
##### 版本号：
2.1.0

##### 问题描述：
我按照文档修改了极简部署的方式，访问 `Online表单开发` 里面的 `从数据库导入表单` ，console上报 `http://localhost:3000/jeecg-boot/online/cgform/head/queryTables/ 404 (Not Found)` 这个错误，经分析可能是 @jeecg/antd-onine 包里面的请求路径处理的有问题，我在 console上可以看到 `_CONFIG` 的值是正确的 `{domianURL: "http://localhost:8080", casPrefixUrl: "http://cas.example.org:8443/cas", imgDomainURL: "http://localhost:8080/sys/common/view", pdfDomainURL: "http://localhost:8080/sys/common/pdf/pdfPreviewIframe"}`

正常的请求路径应该是 \``${_CONFIG.domianURL}/online/cgform/head/queryTables/`\`，不会硬编码有 `jeecg-boot`

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2276718/65373293-15392e80-dcae-11e9-8696-a58c38c1fe7b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/65383797-fa69c700-dd4c-11e9-9e25-5b36884a921d.png)

我之前就参考了这几项设置

后端
![image](https://user-images.githubusercontent.com/2276718/65383815-2edd8300-dd4d-11e9-8798-1ffaa30bed76.png)

前端
![image](https://user-images.githubusercontent.com/2276718/65383839-6fd59780-dd4d-11e9-8222-af4b70ba6c7e.png)
![image](https://user-images.githubusercontent.com/2276718/65383843-7fed7700-dd4d-11e9-95b7-8e9a46589b6d.png)
![image](https://user-images.githubusercontent.com/2276718/65383854-9562a100-dd4d-11e9-92a6-6dbd23b8a4c4.png)

`ant-design-jeecg-vue/vue.config.js` 我没有做修改，我做了修改以后还是相同的问题

![image](https://user-images.githubusercontent.com/2276718/65383918-48cb9580-dd4e-11e9-9638-12d3361aaf1a.png)


![image](https://user-images.githubusercontent.com/2276718/65383915-3cdfd380-dd4e-11e9-90b0-ab97b7543239.png)

其他请求都是正常的，目前暂时只发现这一个请求是404
