### ISSUE TITLE
online 表单开发接口报错，无此接口

### ISSUE THREAD

**Issue by dreamGitCJB** [zhangdaiscott/jeecg-boot#563]
##### 截图&代码：
![7FFED0EC201BF393AA968A6C4FBE3E91](https://user-images.githubusercontent.com/22078662/65406192-60b81d80-de11-11e9-80cd-1f2e34b7eaad.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
修改项目的话参考
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44

**Comment by zhangdaiscott** [comment]
online必须保留jeecg默认的路径扫描地址

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
91
