### ISSUE TITLE
online/cgform/** 接口405

### ISSUE THREAD

**Issue by dreamGitCJB** [zhangdaiscott/jeecg-boot#566]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/22078662/65407517-5bf56880-de15-11e9-8a7a-cbf029f7e4e0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请不要发重复的问题
https://github.com/zhangdaiscott/jeecg-boot/issues/563

**Comment by dreamGitCJB** [comment]
> 请不要发重复的问题
> #563

没有解决我的问题啊

**Comment by wowgmq** [comment]
同样的问题，请问有办法解决吗

**Comment by wkeyword** [comment]
我这边也遇到这个问题，但是看了563没能解决问题。应该是题主改了包路径导致的吧？

**Comment by Tyebile** [comment]
> > 请不要发重复的问题
> > #563
> 
> 没有解决我的问题啊

online/cgform/**  这个类型的接口后台在哪找到了么？
