### ISSUE TITLE
树demo页面去哪了？访问不了？

### ISSUE THREAD

**Issue by skfiy** [zhangdaiscott/jeecg-boot#568]
##### 问题描述：
您好,请问，演示地址里的树DEMO访问不了，下载后的项目里也没有树demo导航栏，树demo去哪了？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23720918/65497801-6c791200-deed-11e9-9042-81985002b6c3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个菜单没有对应的页面，应该是配置错了，删掉就行

**Comment by skfiy** [comment]
那有没有全部树的demo页面？

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/65562241-346ae100-df78-11e9-9481-4064d6d1fc85.png)
![image](https://user-images.githubusercontent.com/3162115/65562249-3c2a8580-df78-11e9-84f2-1fd9e46fa4c2.png)

**Comment by skfiy** [comment]
哦，谢了
