### ISSUE TITLE
swagger-ui测试接口authorize后，header里依然没有带上token

### ISSUE THREAD

**Issue by hiyaojie** [zhangdaiscott/jeecg-boot#575]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/14881927/65650282-c50af500-e03c-11e9-9b37-7eb4af17862f.png)
![image](https://user-images.githubusercontent.com/14881927/65650294-d227e400-e03c-11e9-80e5-d975d5f2cb54.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
获取token在这设置没有问题
![image](https://user-images.githubusercontent.com/3162115/65677754-bf390200-e084-11e9-8a5f-3e920b61e74b.png)
