### ISSUE TITLE
druid will not be managed by Spring

### ISSUE THREAD

**Issue by sjz229812913** [zhangdaiscott/jeecg-boot#576]
##### 版本号：
2.1.0

##### 问题描述：
这里的事务管理 是正确的吗？
was  not registered for synchronization because synchronization is not active
will not be managed by Spring
##### 截图&代码：
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@69566ff0] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@214a8ab4] will not be managed by Spring
==>  Preparing: select * from sys_depart where id IN ( select dep_id from sys_user_depart where user_id = ? ) 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
这个问题是怎么重现的，请提供详细的重现步骤，有demo更容易分析，我看了一下这个错误信息，根据你提供的信息不好判断是哪可能有问题

我找了一下这个错误信息相关资料，或许可以参考：
https://www.javazhiyin.com/25020.html
https://blog.csdn.net/qq_20867981/article/details/79713538
https://blog.csdn.net/qq_26878363/article/details/89888693

**Comment by zhangdaiscott** [comment]
Preparing: select * from sys_depart where id IN ( select dep_id from sys_user_depart where user_id = ? )

这个SQL是查询操作，不需要事务，没关系。
你测试下加@Transaction注解，不提示这个就没有问题。

**Comment by zhangdaiscott** [comment]
这个博客说的很明白
https://blog.csdn.net/Dongguabai/article/details/82057363
