### ISSUE TITLE
导出excle标题如何做成国际化

### ISSUE THREAD

**Issue by awayzhou** [zhangdaiscott/jeecg-boot#577]
##### 问题描述：
导出excle的时候，@Excel(name = "模板CODE", width = 15)  这个注解的name可以做成国际化吗？根据不同的语言版本，展示不同的标题语言

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
得自己扩展了
