### ISSUE TITLE
一对多的表单中，子表单里面的列是否支持隐藏

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#578]
##### 问题描述：
截图部分是否支持列的隐藏。有这样一个需求：根据上面选择的类型，我们需要使下面的列隐藏或显示列。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49051702/65671947-c4914f00-e07a-11e9-8e83-16c9571ad765.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1276924
