### ISSUE TITLE
关于对代码生成器maven依赖的生无可恋

### ISSUE THREAD

**Issue by happy1990ts** [zhangdaiscott/jeecg-boot#58]
- ### 1.本地 setting.xml 的<mirror>配置如下：
![TIM截图20190418174708](https://user-images.githubusercontent.com/14025415/56352737-6c6c3c00-6202-11e9-921e-e94f74a335fd.jpg)
- ### 2.idea中maven更新后......
![TIM截图20190418174527](https://user-images.githubusercontent.com/14025415/56352807-91f94580-6202-11e9-9fa2-3ed71451ed57.jpg)
- ### 3.本地maven仓库中的文件：
![TIM截图20190418175250](https://user-images.githubusercontent.com/14025415/56352924-d4bb1d80-6202-11e9-9c05-1c340cb145dd.jpg)
_**试了很多遍了，生无可恋**_

**Comment by zhangdaiscott** [comment]
你本地是不是配置了别的镜像？

**Comment by happy1990ts** [comment]
你看我setting.xml里的<mirrors>标签对里只有一个<mirror>标签啊，说明我只配了一个仓库
