### ISSUE TITLE
关于v2.1.0版本代码生成器postgresql不同schema里各有几个同一表名的表不能选定生成的问题

### ISSUE THREAD

**Issue by Royyu1215** [zhangdaiscott/jeecg-boot#580]
##### 版本号：
v2.1.0

##### 问题描述：

v2.1.0版本代码生成器postgresql不同schema里各有几个同一表名的表不能选定哪个schema里面的表生成,生成的是查询表名出来后排序第一个的表.看了生成器源码应该是sql查询:select distinct c. relname as table_name from pg_class c 把所有表名当成唯一了.所以不能选定在哪个schema里面进行生成
##### 截图&代码：

DbReadTableUtil.class  69行

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
麻烦截图看下

**Comment by Royyu1215** [comment]
![test](https://user-images.githubusercontent.com/31911898/65829329-028aaf00-e2d7-11e9-8271-023430061a00.jpg)
这是从数据库里查询的同一个名字有三个表

![asdfa](https://user-images.githubusercontent.com/31911898/65829345-29e17c00-e2d7-11e9-8815-bf6bd5091fbe.jpg)
能生成排第一的表

![asdf](https://user-images.githubusercontent.com/31911898/65829348-3239b700-e2d7-11e9-825c-797a8b9cf116.jpg)
不能选定具体schema的表

**Comment by zhangdaiscott** [comment]
jeecg/jeecg_database.properties
画红框的参数就是配置那个数据库

![image](https://user-images.githubusercontent.com/3162115/66177793-7e00ad80-e695-11e9-82d1-8398f898d23a.png)

**Comment by Royyu1215** [comment]
已尝试多次.并不行...

**Comment by Royyu1215** [comment]
我再试试.找到原因再反馈.感谢大佬
