### ISSUE TITLE
resources下excel文件损坏问题

### ISSUE THREAD

**Issue by ycw01** [zhangdaiscott/jeecg-boot#582]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/32702715/65751574-8e68d380-e13d-11e9-850e-990557cd4f92.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ycw01** [comment]
问题原因：
<resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
maven 使用了filter，其其原理是处理文本文件，并将其替换变量，对于二进制文件有问题，导致excel文件损坏。
解决方案：
1、改变文件路径，不放在resources下
2、更改配置如下， **更改后务必maven claen**
 <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                    <include>**/*.xml</include>
                    <include>**/*.tld</include>
                    <include>**/*.doc</include>
                </includes>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.xlsx</include>
                    <include>**/*.xls</include>
                </includes>
                <excludes>
                    <exclude>**/*.yml</exclude>
                    <exclude>**/*.xml</exclude>
                    <exclude>**/*.tld</exclude>
                    <exclude>**/*.doc</exclude>
                </excludes>
                <filtering>false</filtering>
            </resource>

**Comment by zhangdaiscott** [comment]
非常感谢
