### ISSUE TITLE
分页查询方法当pageSize大于500的时候只能查询500条数据

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#583]
##### 问题描述：
使用分页查询方法的时候，当pageSize大于500的时候只能查询500条数据，查看sql变成了LIMIT 0,500 ，实际想查询出1000条左右的数据。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49051702/65762861-997b2e00-e154-11e9-8fe0-5dbc03109977.png)
![image](https://user-images.githubusercontent.com/49051702/65762896-ad269480-e154-11e9-908a-a13a022a976f.png)
![image](https://user-images.githubusercontent.com/49051702/65762916-bd3e7400-e154-11e9-928e-3ccadb911ce7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
查看源码，这个配置是`mybatis-plus`中`PaginationInterceptor`默认设置的
![image](https://user-images.githubusercontent.com/2276718/65827300-60150080-e2c3-11e9-8b43-3b87ba5bf066.png)
可以通过`MybatisPlusConfig`中如下设置设置为更大的`limit`或者取消
![image](https://user-images.githubusercontent.com/2276718/65827325-b08c5e00-e2c3-11e9-8c9a-2e116412bc53.png)

**Comment by wjxjasin** [comment]
谢谢
