### ISSUE TITLE
online表单字段校验 唯一校验 问题

### ISSUE THREAD

**Issue by mindreading** [zhangdaiscott/jeecg-boot#585]
##### 截图&代码：
<img width="715" alt="WeChat3ee265819b9aeeb5796842da7ff8646f" src="https://user-images.githubusercontent.com/12807738/65812253-15c64d80-e1f7-11e9-8636-ab8d191a8816.png">
<img width="324" alt="WeChat16b46e9deea6fec90e7ba1d846d1f768" src="https://user-images.githubusercontent.com/12807738/65812255-1b239800-e1f7-11e9-9aaf-1c13c5383c7c.png">

**Comment by liudonghua123** [comment]
我这边也是类似的情况，从控制台上看到有从OnlineForm上报的错，看上去有点像是需要需要增强JS来自定义提供这个方法，又或者可能是OnlineForm的一个bug。

在线开发生产的代码中没看到这个校验规则相关代码。

![image](https://user-images.githubusercontent.com/2276718/65829673-564ac780-e2da-11e9-8b43-0422d186488d.png)

**Comment by zhangdaiscott** [comment]
现在不支持唯一校验，请去掉配置

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
