### ISSUE TITLE
linux系统下,在线开发表单，数据导入问题

### ISSUE THREAD

**Issue by stsdzjh** [zhangdaiscott/jeecg-boot#589]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/35788848/65829647-18e63a00-e2da-11e9-95ff-7a69dfd2f01b.png)

**Comment by liudonghua123** [comment]
这种问题没有错误日志，可以尝试着把日志输出的级别设置宽一点例如debug；
另外我有几次也是因为长时间不操作就登录超时了，不知道你是不是也是类似的问题，把超时时间设长一点再试试呢？

**Comment by stsdzjh** [comment]
> 这种问题没有错误日志，可以尝试着把日志输出的级别设置宽一点例如debug；
> 另外我有几次也是因为长时间不操作就登录超时了，不知道你是不是也是类似的问题，把超时时间设长一点再试试呢？

应该不是超时的问题，系统是立马就返回登录过期，根本就没有等待的过程

**Comment by liudonghua123** [comment]
@stsdzjh 没有日志信息，有点难分析，我这边也不好重现，是不是可以设置断点，或者在关键的环节上添加日志输出，看看是运行到哪，可能是在哪出错。

**Comment by stsdzjh** [comment]
> @stsdzjh 没有日志信息，有点难分析，我这边也不好重现，是不是可以设置断点，或者在关键的环节上添加日志输出，看看是运行到哪，可能是在哪出错。

我从前台打印日志，请求的地址是http://127.0.0.1:8080/jeecg-boot/online/cgform/api/importXls/90e0f26e07bd455ba898e8d9e2e39975
在后台的代码里，就没有对应的请求路径的实现，所以，也没找到可以设置断点的地方，这个请求路径，是不是在其他依赖的jar包中实现了？

**Comment by liudonghua123** [comment]
`http://127.0.0.1:8080/jeecg-boot/online/` 这个网址确实是另一个Jar包里面实现的
```
		<!--  online form-->
		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>online-form</artifactId>
			<version>1.0.2</version>
		</dependency>
```

你只在Linux上部署的在线开发中有这个问题么？

**Comment by stsdzjh** [comment]
> `http://127.0.0.1:8080/jeecg-boot/online/` 这个网址确实是另一个Jar包里面实现的
> 
> ```
> 		
> 		<dependency>
> 			<groupId>org.jeecgframework.boot</groupId>
> 			<artifactId>online-form</artifactId>
> 			<version>1.0.2</version>
> 		</dependency>
> ```
> 
> 你只在Linux上部署的在线开发中有这个问题么？

是的，在win+myeclipse开发环境下，调试是没有问题的，可以正常导入，也不报错，就是打jar包后，部署到linux环境，才出现这个问题，jeecg-boot/online/cgform/api  这个路径我用jd-gui在online-form里也没有找到

**Comment by zhangdaiscott** [comment]
你是不是改项目名字了？
参考
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44

**Comment by stsdzjh** [comment]
> 你是不是改项目名字了？
> 参考
> http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
> 44

项目名字没有改过，都是默认的
![image](https://user-images.githubusercontent.com/35788848/65843112-7b831880-e362-11e9-81bd-0348f508b917.png)

**Comment by liudonghua123** [comment]
> @stsdzjh jeecg-boot/online/cgform/api 这个路径我用jd-gui在online-form里也没有找到

我是这样看到的，这个没有开源，只能看到混淆后的代码，方法签名和实现似乎有点不像，可能是运行时动态修改字节码的吧

你说的这个问题确实有点难重现，不好分析 

![image](https://user-images.githubusercontent.com/2276718/65843875-7a53ea80-e366-11e9-998c-05be65c30a3d.png)

**Comment by stsdzjh** [comment]
@liudonghua123 @zhangdaiscott 
不好意思，犯了个低级错误，把前台的地址改为公网地址就可以了，原来是127.0.0.1
![image](https://user-images.githubusercontent.com/35788848/65846051-1124a500-e36f-11e9-8a78-017dadbdf5af.png)
问题已解决，感谢各位大佬协助！
