### ISSUE TITLE
jeecg-boot2.0.2版本添加自己业务逻辑页面之后,vue页面跳转过渡不正常

### ISSUE THREAD

**Issue by eternityzhang** [zhangdaiscott/jeecg-boot#590]
### 问题描述：
正常的添加业务逻辑及页面,但是不知道哪个地方产生冲突或者怎么的,会导致下面图片的问题.
### 截图&代码：
从这个页面开始跳转:
![image](https://user-images.githubusercontent.com/31660451/65829453-4af69c80-e2d8-11e9-8016-6d91c172180a.png)

跳转到这个页面
![image](https://user-images.githubusercontent.com/31660451/65829454-59dd4f00-e2d8-11e9-9518-e3548a902986.png)

跳转过程中:

![image](https://user-images.githubusercontent.com/31660451/65829574-7fb72380-e2d9-11e9-9ac3-9b667c7fdc2d.png)

**Comment by zhangdaiscott** [comment]
自己写的代码，请不要发issue，因为我们没有代码，没有办法判断

**Comment by Nicky213Zhang** [comment]
这个问题我也碰到过，应该是vue的一种现象，当一级菜单为路由菜单（不知道说的对不对哈）跳转具体页面时，切换页面会从当前页面底部升起，仍可看到当前页面，短暂的时间俩个页面同时出现在页面上。试过一级菜单没有具体页面，由二级菜单跳转就不会出现这个现象。当然，这些都不影响数据结果。

**Comment by eternityzhang** [comment]
> 这个问题我也碰到过，应该是vue的一种现象，当一级菜单为路由菜单（不知道说的对不对哈）跳转具体页面时，切换页面会从当前页面底部升起，仍可看到当前页面，短暂的时间俩个页面同时出现在页面上。试过一级菜单没有具体页面，由二级菜单跳转就不会出现这个现象。当然，这些都不影响数据结果。

好的,谢谢,我再研究研究,实在不行,整体转换一下将跳转链接放到二级菜单里面

**Comment by Nicky213Zhang** [comment]
> > 这个问题我也碰到过，应该是vue的一种现象，当一级菜单为路由菜单（不知道说的对不对哈）跳转具体页面时，切换页面会从当前页面底部升起，仍可看到当前页面，短暂的时间俩个页面同时出现在页面上。试过一级菜单没有具体页面，由二级菜单跳转就不会出现这个现象。当然，这些都不影响数据结果。
> 
> 好的,谢谢,我再研究研究,实在不行,整体转换一下将跳转链接放到二级菜单里面

找到一个简单的处理方式，
![微信图片_20190929180427](https://user-images.githubusercontent.com/25654842/65830643-d0337e80-e2e3-11e9-84ba-a5a6a72270e3.png)
前后加上这个div，是参考的首页。发现还不错，比之前好很多，具体实现还不清楚

**Comment by eternityzhang** [comment]
> > > 这个问题我也碰到过，应该是vue的一种现象，当一级菜单为路由菜单（不知道说的对不对哈）跳转具体页面时，切换页面会从当前页面底部升起，仍可看到当前页面，短暂的时间俩个页面同时出现在页面上。试过一级菜单没有具体页面，由二级菜单跳转就不会出现这个现象。当然，这些都不影响数据结果。
> > 
> > 
> > 好的,谢谢,我再研究研究,实在不行,整体转换一下将跳转链接放到二级菜单里面
> 
> 找到一个简单的处理方式，
> ![微信图片_20190929180427](https://user-images.githubusercontent.com/25654842/65830643-d0337e80-e2e3-11e9-84ba-a5a6a72270e3.png)
> 前后加上这个div，是参考的首页。发现还不错，比之前好很多，具体实现还不清楚

我测试了下,template下的第一层(也就是你图中代码的位置)加上一层div确实有效果,我突然想起来之前看的一个教程中,现在版本的vue貌似就是需要有一个父容器一般是div包起来下面的代码.
