### ISSUE TITLE
一对多JEditable a-select组件的问题

### ISSUE THREAD

**Issue by FENGDEJUN** [zhangdaiscott/jeecg-boot#591]
##### 问题描述：
如下图，输入框被遮住
希望解决成如下3者之一
1、要么输入2个检索的字符才出列表
2、要么下拉框的内容右移  一些
3、 要么全部向上拉，不要挡住输入框

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14088300/65829735-fc96cd00-e2da-11e9-9e49-22e366c7c894.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by FENGDEJUN** [comment]
版本号：2.0.2

**Comment by zhangdaiscott** [comment]
2.1版本已经解决了这个问题，请更新

**Comment by FENGDEJUN** [comment]
@zhangdaiscott 没有看到2.1版本

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot

**Comment by FENGDEJUN** [comment]
> https://github.com/zhangdaiscott/jeecg-boot

实现的效果非常赞
响应非常及时
相信会获得更多用户的认同

感谢
