### ISSUE TITLE
window.less.modifyVars is not a function     at eval

### ISSUE THREAD

**Issue by gemini0524** [zhangdaiscott/jeecg-boot#592]
##### 版本号：
2.1

##### 问题描述：
系统设置，换风格和主题色后，重新刷新，一直出现正在编译主题！

##### 截图&代码：

<img width="942" alt="展示" src="https://user-images.githubusercontent.com/3241234/65831475-6f5c7400-e2ec-11e9-95d2-9c0c6610c638.png">
<img width="601" alt="WX20190929-190059@2x" src="https://user-images.githubusercontent.com/3241234/65831477-72576480-e2ec-11e9-9c6b-0992954bfd13.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
我查看源代码，应该是 less.js 还没加载好，然后就开始编译主题，所以报错，相关代码如下

![image](https://user-images.githubusercontent.com/2276718/65833958-bc4e4380-e308-11e9-853a-27666128d233.png)

![image](https://user-images.githubusercontent.com/2276718/65833993-10f1be80-e309-11e9-8f9c-7613382d3d50.png)

首次加载时 less.js 还没有加载完成，里面是没有 modifyVars 函数的，这里的判断也有点问题，所以就进入到下面直接使用了，所以报错了。

**Comment by liudonghua123** [comment]
这个问题和 https://github.com/zhangdaiscott/jeecg-boot/issues/530 是相关的，在 https://github.com/zhangdaiscott/jeecg-boot/pull/587 中我一并解决了

**Comment by zhangdaiscott** [comment]
此问题已经处理，下个版本会发布
