### ISSUE TITLE
V2.1.0没有适配ie9和ie10吗

### ISSUE THREAD

**Issue by yemingxingkong** [zhangdaiscott/jeecg-boot#593]
##### 版本号：
V2.1.0

##### 问题描述：
没有去适配ie9和ie10吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33214698/65849678-1dfcc500-e37e-11e9-8516-a1ce006be777.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持的，官方建议IE11+
