### ISSUE TITLE
一对多 页面属性不起作用 如图片 附件 属性

### ISSUE THREAD

**Issue by yangyangs2537** [zhangdaiscott/jeecg-boot#598]
##### 版本号：
当前最新版本： 2.1.0（发布日期：20190826）

##### 问题描述：
一对多 页面属性不起作用 如图片 附件 属性

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46039330/66309521-70b91c80-e93c-11e9-9dcc-c12883020c3a.png)
![image](https://user-images.githubusercontent.com/46039330/66309557-86c6dd00-e93c-11e9-9ee6-69f21938e71e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
新版已经发布，请更新代码测试
