### ISSUE TITLE
页面属性没有 分类字典树控件

### ISSUE THREAD

**Issue by yangyangs2537** [zhangdaiscott/jeecg-boot#599]
##### 版本号：

当前最新版本： 2.1.0（发布日期：20190826）
##### 问题描述：
分类字典树控件 还没及时更新

##### 截图&代码：

![image](https://user-images.githubusercontent.com/46039330/66322340-8f2b1200-e954-11e9-8b2a-9df9484aade2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本发布
