### ISSUE TITLE
没找到springboot版的jeecg-boot代码生成器

### ISSUE THREAD

**Issue by gzzlovezyx** [zhangdaiscott/jeecg-boot#6]
<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>codegenerate</artifactId>
			<version>1.0.0</version>
		</dependency>

**Comment by zhangdaiscott** [comment]
你应该是配置了镜像，参考一下链接，进行jeecg的镜像设置
http://jeecg-boot.mydoc.io/?t=342603

**Comment by zhangdaiscott** [comment]
<mirrors>
       <mirror>
            <id>nexus-aliyun</id>
            <mirrorOf>*,!jeecg,!jeecg-snapshots</mirrorOf>
            <name>Nexus aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror> 
 </mirrors>

**Comment by gzzlovezyx** [comment]
改完之后就可以了，谢谢，那就是codegenerate是不开源的对吧？
