### ISSUE TITLE
生成的表单，如果某一列数据为null ,后面列的数据都会往前移

### ISSUE THREAD

**Issue by hiyaojie** [zhangdaiscott/jeecg-boot#60]
生成的表单，如果某一列数据为null ,后面列的数据都会往前移，效果如下：

![image](https://user-images.githubusercontent.com/14881927/56428649-b9c7d680-62f2-11e9-8985-1062e53b635c.png)

**Comment by zhangdaiscott** [comment]
数据列为空是什么意思？

**Comment by hiyaojie** [comment]
就是这一行数据，问题描述和答案字段为null ,前端把操作那一栏的数据渲染到了问题描述那一栏；

**Comment by zhangdaiscott** [comment]
不会啊，数据为空不是很正常吗
