### ISSUE TITLE
context-path修改后，online表单开发对应的接口提示404，其他接口可以正常访问。

### ISSUE THREAD

**Issue by fuqiangma** [zhangdaiscott/jeecg-boot#605]
##### 问题描述：
context-path修改后，online表单开发对应的接口提示404，其他接口可以正常访问。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38602522/66471106-5c505d80-eabd-11e9-8ada-10fb64c13faa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看下常见问题贴
44
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
