### ISSUE TITLE
单体项目连接远程数据库报错没有表

### ISSUE THREAD

**Issue by xiaocheng121380** [zhangdaiscott/jeecg-boot#6074]
##### 截图&代码：
![368d0633db3d45007211b7a79873c2f](https://github.com/jeecgboot/jeecg-boot/assets/73933122/08742d9d-0dac-42eb-af4b-d8c2fb6f4133)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by chenhengeng** [comment]
应该是设置mysql不区分数据库大小写吧
