### ISSUE TITLE
ant-design-vue的控件a-tooltip在平台内使用ie11打开，鼠标移动后出现闪动

### ISSUE THREAD

**Issue by zhouyilong** [zhangdaiscott/jeecg-boot#608]
##### 截图&代码：如下

![Video_2019-10-10_113306](https://user-images.githubusercontent.com/9840580/66537423-f9110a80-eb52-11e9-881f-93beec5a4e33.gif)

**Comment by zhouyilong** [comment]
另外补充，发现在IE11下，所有的下拉框组件、日期组件等弹出式的，都存在闪两下的情况。官方的我测试过，也同样存在这个问题。

**Comment by sjlei** [comment]
IE版本号：

![image](https://user-images.githubusercontent.com/34293221/68354373-2697a680-0147-11ea-9f03-024bdb099468.png)

经测试，并没有发现 `a-tooltip` 闪动的问题

![代码演示To](https://user-images.githubusercontent.com/34293221/68354706-0b796680-0148-11ea-9e3f-7c194e1b9631.gif)

下拉框组件闪烁的问题官方文档也有，只要是下拉选项过长，出现滚动条的都会闪烁，这应该是IE的缺陷，目前只能等antd-vue官方解决。

![代码演示To1](https://user-images.githubusercontent.com/34293221/68354874-8e9abc80-0148-11ea-9ca0-9d0afa36285b.gif)
