### ISSUE TITLE
文档中的JEditableTable 的 示例五自定义函数校验不起作用

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#609]
##### 问题描述：
JEditableTable 的 示例五自定义函数校验不起作用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49051702/66566560-d6edab80-eb97-11e9-9a23-1bd618203eba.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by hzyyy** [comment]
我刚刚也遇到了，正想提issues 的。如果你解决了，请回复我，谢谢

**Comment by hzyyy** [comment]
> 我刚刚也遇到了，正想提问题的。如果你解决了，请回复我，谢谢

更新JEditableTable.vue 文件到最新就ok 了

**Comment by hzyyy** [comment]
JEditableTable.vue 文件更新至1.5.0 版本即可

**Comment by wjxjasin** [comment]
1.5.0 版本是哪个，我现在用的是2.0.1的版本的






------------------ 原始邮件 ------------------
发件人: "hzyyy"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午3:11
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>; 
抄送: "jasin"<wjxjasin@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeecg-boot] 文档中的JEditableTable 的 示例五自定义函数校验不起作用 (#609)




JEditableTable.vue 文件更新至1.5.0 版本即可

**Comment by hzyyy** [comment]
[
[JEditableTable.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3716132/JEditableTable.zip)
](url)

**Comment by hzyyy** [comment]
[JEditableTable.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3716134/JEditableTable.zip)

**Comment by zhangdaiscott** [comment]
升级2.1的代码试试

**Comment by isfang158** [comment]
![image](https://user-images.githubusercontent.com/50865430/67008343-e337b280-f11b-11e9-975e-38ded3be7b0c.png)
一样  没反应    最新 2.1.0版本

**Comment by wjxjasin** [comment]
你应该再提一个issue------------------ 原始邮件 ------------------
发件人: "isfang158"<notifications@github.com>
发送时间: 2019年10月17日(星期四) 晚上8:24
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "wjxjasin"<wjxjasin@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] 文档中的JEditableTable 的 示例五自定义函数校验不起作用 (#609)




 一样  没反应    最新 2.1.0版本
 
&mdash;

**Comment by sjlei** [comment]
你好，经测试，示例五中的自定义函数校验我这里是没问题的，可以正常使用。你用的版本是多少？或者将你那个版本的`JEditableTable.vue`源文件和你的使用方式发上来我看看，再测试一下。

**Comment by wjxjasin** [comment]
嗯，谢谢，我在最新版本中找到了示例5改动的代码，已经集成进去了，我用的版本是2.0.1



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "牧星长"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 晚上8:09
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "jasin"<wjxjasin@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 文档中的JEditableTable 的 示例五自定义函数校验不起作用 (#609)




你好，经测试，示例五中的自定义函数校验我这里是没问题的，可以正常使用。你用的版本是多少？或者将你那个版本的JEditableTable.vue源文件和你的使用方式发上来我看看，再测试一下。
