### ISSUE TITLE
建议在消息模板管理的邮箱类型集成富文本编辑框

### ISSUE THREAD

**Issue by ileadall42** [zhangdaiscott/jeecg-boot#61]
![image](https://user-images.githubusercontent.com/27263086/56450014-f1b33600-6353-11e9-8e4f-238c8ca75b6e.png)

**集成富文本编辑框** 让邮件内容更有生命力~**

**Comment by zhangdaiscott** [comment]
好的

**Comment by ileadall42** [comment]
![71556023414_.pic_hd](http://wx2.sinaimg.cn/large/006qhU4Vgy1g2curqe0mbj327w16ugtn.jpg)
感觉系统通告，发送全体消息的时候或者在首页展示通告的时候，有样式富文本编辑也是挺好的~

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
