### ISSUE TITLE
部门管理数据显示问题，请作者帮忙

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#610]
##### 版本号：
2.1.0

##### 问题描述：
部门管理在配置数据权限范围后，如登录者非一级机构用户，并且权限为所在部门及以下时，看不到所在部门及以下的数据，原因为，在生成树结构时，只有没有父级id的会添加到treelist，故而如果登录者数据范围是从第二级开始的，则看不到树结构。
还望作者能帮忙解答一下，能力有限，不是很敢动这部分代码

##### 截图&代码：
![微信图片_20191011145222](https://user-images.githubusercontent.com/25654842/66630899-ac532f80-ec37-11e9-97c3-3818b851a7f7.png)
![3](https://user-images.githubusercontent.com/25654842/66630959-c55be080-ec37-11e9-8508-968a43a9dabb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
部门管理是系统管理用的全局管理；
如果你想不同人看到的是，自己的部门，可以用“我的部门”这个功能，此功能已经有了
![image](https://user-images.githubusercontent.com/3162115/74910163-d5a97680-53f4-11ea-906a-cffb9d35e587.png)
