### ISSUE TITLE
在线生成 没有 api-注解  非在线生成有 还有抽屉风格没有效果

### ISSUE THREAD

**Issue by yangyangs2537** [zhangdaiscott/jeecg-boot#611]
##### 版本号：
当前最新版本： 2.1.0（发布日期：20190826）

##### 问题描述：
在线生成 没有 api-注解  非在线生成有
 还有抽屉风格没有效果 ，页面大小对话框伸缩没有
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
生成的代码默认会有一个抽屉风格的页面，需要手工改下
__Style#Drawer.vue
把这个后缀去掉就是抽屉风格

![image](https://user-images.githubusercontent.com/3162115/66635580-17a1ff00-ec42-11e9-93fb-f2fa9419bb89.png)

**Comment by yangyangs2537** [comment]
------------------



卢培洋
科而勒


 联系我









 
 我选择抽屉风格 并没有 生成 就只有一个UserDataSetModal.vue  是抽屉风格


------------------ 原始邮件 ------------------
发件人: "JEECG开源社区"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午4:15
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "S2T25卢培洋"<1055448724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] 在线生成 没有 api-注解  非在线生成有 还有抽屉风格没有效果 (#611)




生成的代码默认会有一个抽屉风格的页面，需要手工改下
 __Style#Drawer.vue
 把这个后缀去掉就是抽屉风格

**Comment by zhangdaiscott** [comment]
我们确认下

**Comment by zhangdaiscott** [comment]
确认online单表生成有抽屉风格
![image](https://user-images.githubusercontent.com/3162115/67160600-29dc1580-f385-11e9-972f-b8f127c53a53.png)
