### ISSUE TITLE
当只有一个二级菜单页面时，关闭页面再打开，不刷新页面

### ISSUE THREAD

**Issue by JohnShen1994** [zhangdaiscott/jeecg-boot#612]
##### 版本号：
master

##### 问题描述：
如下图1，2所示，当我只打开系统管理的一个子菜单如“用户管理”页面时，我把“用户管理”页面关闭了再打开页面，页面是不会刷新的。

奇怪的是，当我打开系统管理的二个或二个以上的子菜单，却能刷新。

##### 截图&代码：
图1：
![image](https://user-images.githubusercontent.com/16118074/66639443-6acb8000-ec49-11e9-8855-ff6b70268cfb.png)

再次打开“用户管理”页面，这个勾还存在
![image](https://user-images.githubusercontent.com/16118074/66639541-95b5d400-ec49-11e9-84bd-f040a69944f4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/68079687-533a7e00-fe28-11e9-88e2-1c85dfed72f9.png)

这是 vue 里面 keep-alive 的正常工作方式，可以参考
https://cn.vuejs.org/v2/api/index.html#keep-alive
https://cn.vuejs.org/v2/api/#activated
https://my.oschina.net/lixiaoyan/blog/1920406
https://stackoverflow.com/questions/48501978/how-to-use-keep-alive-in-vuejs
