### ISSUE TITLE
online 在线生成一对多问题bug

### ISSUE THREAD

**Issue by yangyangs2537** [zhangdaiscott/jeecg-boot#613]
##### 版本号：
当前最新版本： 2.1.0（发布日期：20190826）

##### 问题描述：

online 在线生成一对多问题bug 第一次子子表序号为空，可以生成，后面再追加也可，但第一次初建就给序号就不会代码生成  报null 错误 页面卡死 
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
序号都设置上值就解决了这个问题
