### ISSUE TITLE
docker JAR分离大包部署

### ISSUE THREAD

**Issue by caigaolin** [zhangdaiscott/jeecg-boot#6196]
##### 版本号：
3.6.2
##### 问题描述：
docker分离式部署，jar单独放到lib文件夹下，启动报错，服务器是linux

##### 截图&代码：
分离大包方式，源码情况
<img width="1512" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/46164794/733c419a-377e-48ee-a2cc-67742faae0f3">

部署文件夹
<img width="581" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/46164794/b25dbcb0-b6c0-48bd-8b5d-2179bf1a8247">
启动报错
<img width="1290" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/46164794/6c5b4832-d202-44e3-ba88-790aa76c8395">

<img width="1290" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/46164794/e4a8a023-05f7-445c-8dff-1d03bacfc151">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
现在的swagger用的不是openapi，这是你们自己改的？

**Comment by caigaolin** [comment]
您好，没有进引入依赖这个是版本自带的

**Comment by zhangdaiscott** [comment]
分支： master？还是springboot3?
前端版本: vue3版？还是 vue2版？

**Comment by caigaolin** [comment]
分支是3.6.2

**Comment by zhangdaiscott** [comment]
cr 测试

**Comment by caigaolin** [comment]
上图项目依赖的包大部分都在lib文件下下，base-upms-biz-test.jar里面只有几个项目核心的依赖包，而且很下，每次只需上传这个jar就可以，启动时采用：执行run.sh就可以，只要依赖包不升级版本lib就不用替换。采用这种分离时部署，减少主jar包过大。咱们提供的有window版本的，但是docker部署的没有，咱们提供的单体框架，我尝试这种形式不行。还请指导完善。







--

业精于勤，荒于嬉，行成于思，毁于随。




在 2024-05-14 14:13:11，"EightMonth" ***@***.***> 写道：

docker部署方案请参考官方文档:https://help.jeecg.com/java/setup/dockerset/soft.html
官方文档中，并未提供分离大包部署方案，麻烦说明如何做的分离大包部署方案，以便于后续提供支持
