### ISSUE TITLE
增加JEditableTable组件的一些小功能,可能会用到

### ISSUE THREAD

**Issue by Loren1999** [zhangdaiscott/jeecg-boot#621]
##### 问题描述：
JEditableTable组件的一些小功能,可能会用到

##### 截图&代码：
1.    allowInput属性可以创建新的选项,有时不希望用户可以创建 (避免错误),可以添加一个allowSearch属性仅用来筛选
代码位于/src/components/jeecg/JEditableTable.vue的buildProps方法中,可在第1548行增加如下
`// 判断select是否允许查询
        if (col.type === FormTypes.select && col.allowSearch === true) {
          props['showSearch'] = true
          props['optionFilterProp'] = 'children'
          props['filterOption'] = (input, option) => {
            return option.componentOptions.children[0].text.toLowerCase().indexOf(input.toLowerCase()) >= 0
          }
        }`
使用方式:
增加allowSearch属性即可
![image](https://user-images.githubusercontent.com/20633409/66717014-01916b80-ee07-11e9-802c-bf2a410bfe1d.png)

2.    使用select组件时,有时需要禁用一些选项,可以增加一个禁用选项的功能
![image](https://user-images.githubusercontent.com/20633409/66717108-fb4fbf00-ee07-11e9-948b-991235af05eb.png)
使用方式:
![image](https://user-images.githubusercontent.com/20633409/66717139-52ee2a80-ee08-11e9-9516-7964541b49f5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
你好，以下两个功能均已在新版本中实现，请耐心等待新版本的发布。

![image](https://user-images.githubusercontent.com/34293221/68291427-d37d0f80-00c4-11ea-854e-e31138babe1b.png)

![image](https://user-images.githubusercontent.com/20633409/66717139-52ee2a80-ee08-11e9-9516-7964541b49f5.png)
