### ISSUE TITLE
Online表单开发-单表类型-同步数据库失败-sqlserver库

### ISSUE THREAD

**Issue by henleygao** [zhangdaiscott/jeecg-boot#629]
##### 问题描述：
Online表单开发-单表类型-同步数据库失败-sql server库

##### 截图&代码：
ERROR org.jeecg.modules.online.cgform.a.a:545 - OnlCgformApiController.doDbSynch()发生异常：null

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
数据库兼容问题已经修复，下个版本会修复这个问题
