### ISSUE TITLE
表单验证下滑的时候验证会变正常 

### ISSUE THREAD

**Issue by SoYoungHu** [zhangdaiscott/jeecg-boot#630]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/48267058/66806526-55f93000-ef5a-11e9-8b3d-ffc415214196.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请用2.1 试试

**Comment by SoYoungHu** [comment]
> 请用2.1 试试

也不可以哦  你们官网JEditableTable实例表单验证也有这个问题
