### ISSUE TITLE
如何去掉jeecg-boot中的shiro

### ISSUE THREAD

**Issue by lrzj** [zhangdaiscott/jeecg-boot#631]
##### 版本号：
jeecgboot2.0

##### 问题描述：
由于项目需要，想把shiro从项目中去掉

##### 截图&代码：
![image](https://user-images.githubusercontent.com/56569172/66820681-c06a9a00-ef73-11e9-8a6f-49b3952c8017.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此问题不要再发了，自己重构即可
