### ISSUE TITLE
对象复制问题 BeanUtils建议更换成MapStruct

### ISSUE THREAD

**Issue by archorfight** [zhangdaiscott/jeecg-boot#632]
##### 版本号：
2.0.2

##### 问题描述：
BeanUtils 复制对象 效率差，还有深拷贝的问题。  建议换成 MapStruct 
http://www.kailing.pub/MapStruct1.3/index.html#_apache_maven

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
感觉MapStruct 用起来比较繁琐啊
