### ISSUE TITLE
JEditor 组件的视频预览功能

### ISSUE THREAD

**Issue by wangkaiChen1118** [zhangdaiscott/jeecg-boot#634]
##### 版本号：
2.1.0

##### 问题描述：
富文本编辑器中，把视频地址写进去，然后保存，视频不能预览吗；

##### 截图&代码：

富文本编辑器中，把视频地址写进去，然后保存，视频不能预览吗；
![image](https://user-images.githubusercontent.com/51146877/66987942-444b9000-f0f4-11e9-8264-f13da9f70144.png)
![image](https://user-images.githubusercontent.com/51146877/66988049-79f07900-f0f4-11e9-8b02-ea0389e92c27.png)

或者第二种，内嵌一个 video 标签，然后保存，视频还是不能预览
![image](https://user-images.githubusercontent.com/51146877/66988150-9ee4ec00-f0f4-11e9-9538-69a1a9ee13d0.png)
![image](https://user-images.githubusercontent.com/51146877/66988239-c3d95f00-f0f4-11e9-9d46-df7689746089.png)

以下是我单独放一个  video 标签的内容，用 p 标签包裹起来，模拟富文本编辑器的内容，
虽然用 p 标签包裹了 video 标签，还是可以正常显示这个视频的
![image](https://user-images.githubusercontent.com/51146877/66988367-000cbf80-f0f5-11e9-9c3b-50b4d50ddaf6.png)
![image](https://user-images.githubusercontent.com/51146877/66988405-0ac75480-f0f5-11e9-82f6-01e1d73bd3ab.png)

请问这个 JEditor 组件，可以实现视频预览吗？ 是我的操作有问题吗？
感谢！！！

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没实现视频功能

**Comment by liudonghua123** [comment]
由于富文本编辑器使用的是tinymce (https://github.com/tinymce/tinymce/issues?utf8=%E2%9C%93&q=video+preview)，这个特性我查了属于高级付费的，不过如果能力强，也可以自己实现类似的功能

![image](https://user-images.githubusercontent.com/2276718/67735358-d5006500-fa3e-11e9-8881-9b53a1b41b3d.png)

![image](https://user-images.githubusercontent.com/2276718/67735309-b39f7900-fa3e-11e9-9b11-158809e651a7.png)

**Comment by wangkaiChen1118** [comment]
感谢------------------ 原始邮件 ------------------
发件人: "liudonghua"<notifications@github.com>
发送时间: 2019年10月29日(星期二) 中午11:27
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "wangkaiChen1118"<1143410797@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] JEditor 组件的视频预览功能 (#634)



由于富文本编辑器使用的是tinymce (https://github.com/tinymce/tinymce/issues?utf8=%E2%9C%93&q=video+preview)，这个特性我查了属于高级付费的，不过如果能力强，也可以自己实现类似的功能
 

 

 
&mdash;
