### ISSUE TITLE
在线开发模块中postgre数据库连接关键字拼写错误

### ISSUE THREAD

**Issue by jasonleo0314** [zhangdaiscott/jeecg-boot#635]
##### 版本号：
2.1.0

##### 问题描述：

在线开发模块中，点击按钮“从数据库导入表单”应当读取数据库中的表。当设置在线开发数据库为postgre时，点击按钮报错，提示未找到变量“diver_name”的值。经试验，将jeecg_database文件中postgre数据库连接配置项driver_name=org.postgresql.Driver改为diver_name=org.postgresql.Driver即可成功读取数据库。
这说明，在线开发模块中存在bug，误将 driver 拼写为diver导致，请修改。

##### 截图&代码：

![捕获](https://user-images.githubusercontent.com/10685079/66991767-4b29d100-f0fb-11e9-9cfd-da6d9fc0881d.PNG)

**Comment by zhangdaiscott** [comment]
收录，感谢

**Comment by zhangdaiscott** [comment]
短期先不改了，不然会影响老代码的使用
