### ISSUE TITLE
一对多的poi导出时如何屏蔽每张表不想导出的字段

### ISSUE THREAD

**Issue by gogowrong** [zhangdaiscott/jeecg-boot#637]
##### 截图&代码：下面是代码生成器生成的导出功能的实现代码，pageList已经包含了从数据库查询到的数据（多张表的数据），导出时默认会导出所有字段，可是每张表都有些字段我不想导出来，该怎么办。
@RequestMapping(value = "/exportXls")
  public ModelAndView exportXls(HttpServletRequest request, HttpServletResponse response,MallOrderProduct OrderProduct) {
      // Step.1 组装查询条件
      QueryWrapper<MallOrderProduct> queryWrapper = null;
      try {
          String paramsStr = request.getParameter("paramsStr");
          //paramsStr always be null  所以我重新给queryWrapper赋值
          if (oConvertUtils.isNotEmpty(paramsStr)) {
              String deString = URLDecoder.decode(paramsStr, "UTF-8");
              MallOrderProduct mallOrderProduct = JSON.parseObject(deString, MallOrderProduct.class);
              queryWrapper = QueryGenerator.initQueryWrapper(mallOrderProduct, request.getParameterMap());
          }
      } catch (UnsupportedEncodingException e) {
          e.printStackTrace();
      }
      queryWrapper = QueryGenerator.initQueryWrapper(OrderProduct, request.getParameterMap());

      //Step.2 AutoPoi 导出Excel
      ModelAndView mv = new ModelAndView(new JeecgEntityExcelView());
      List<MallOrderProductPage> pageList = new ArrayList<MallOrderProductPage>();
      List<MallOrderProduct> mallOrderProductList = mallOrderProductService.list(queryWrapper);
      for (MallOrderProduct mallOrderProduct : mallOrderProductList) {
          MallOrderProductPage vo = new MallOrderProductPage();
          BeanUtils.copyProperties(mallOrderProduct, vo);
          List<MallProduct> mallProductList = mallProductService.selectByMainId(String.valueOf(mallOrderProduct.getProductId()));
          vo.setMallProductList(mallProductList);
          List<MallUser> mallUserList = mallUserService.selectByMainId(String.valueOf(mallOrderProduct.getUserId()));
          vo.setMallUserList(mallUserList);
          pageList.add(vo);
      }
      //导出文件名称
      mv.addObject(NormalExcelConstants.FILE_NAME, "购买清单列表");
      mv.addObject(NormalExcelConstants.CLASS, MallOrderProductPage.class);
      mv.addObject(NormalExcelConstants.PARAMS, new ExportParams("购买清单列表数据", "备注信息", "导出信息"));
      mv.addObject(NormalExcelConstants.DATA_LIST, pageList);
      return mv;
  }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/607
