### ISSUE TITLE
页面渲染数据效率过慢

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#638]
##### 版本号：
2.1.0

##### 问题描述：
前端页面添加了许多 按钮权限 状态判断；
加载500行数据时  时间长达1分多钟，下面是录屏

##### 截图&代码：
页面通过 v-has 加数据状态判断权限
![image](https://user-images.githubusercontent.com/50865430/67064208-34878680-f19c-11e9-988b-c18f9e179e84.png)

![QQ截图20191018112426](https://user-images.githubusercontent.com/50865430/67064314-a9f35700-f19c-11e9-8848-d06d01bc7cbf.png)

![QQ截图20191017112445](https://user-images.githubusercontent.com/50865430/67064320-afe93800-f19c-11e9-9ff7-88a37c218938.png)

录屏：打包
[20191018_113537.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3742222/20191018_113537.zip)

**Comment by isfang158** [comment]
图片放错了一张


![123 (2)](https://user-images.githubusercontent.com/50865430/67064462-3736ab80-f19d-11e9-8aef-b284ccdd15e4.png)

**Comment by zhangdaiscott** [comment]
src/utils/hasPermission.js
这页面里面的console.log 注释掉试试

**Comment by zhangdaiscott** [comment]
console.time用于计算js代码执行耗时
https://www.cnblogs.com/mei123/p/8548820.html
