### ISSUE TITLE
  SpringBoot+Mybatis+AntDesign 适合做ERP系统不 技术咨询

### ISSUE THREAD

**Issue by shaowen** [zhangdaiscott/jeecg-boot#64]
SpringBoot+Mybatis+AntDesign 适合做ERP系统不，
1、 主要是页面数据比较多， 以前系统用的是extjs .
2、AntDesign 是做页面比较密集，样式好调整吗  如图1 这样的紧凑感 谢谢

如图1
![image](https://user-images.githubusercontent.com/5210084/56489121-3933f080-6513-11e9-92e5-f058782ba4af.png)

**Comment by zhangdaiscott** [comment]
适合

**Comment by shaowen** [comment]
sql server数据库有注意事项 谢谢 兼容吗

**Comment by shaowen** [comment]
> 适合

你好 sql server数据库有注意事项 谢谢 兼容吗
