### ISSUE TITLE
登陆返回前端的数据有密码和盐

### ISSUE THREAD

**Issue by klniu** [zhangdaiscott/jeecg-boot#643]
##### 版本号：
2.1.1

##### 问题描述：
登陆返回前端的数据有密码和盐，不安全

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1018698/67180663-d8776900-f40c-11e9-868e-91066e0c2bfe.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by cjy37** [comment]
+1  这个我昨天也发现了，不安全。。。

**Comment by zhangdaiscott** [comment]
已处理，非常感谢
