### ISSUE TITLE
pom文件jar包引入

### ISSUE THREAD

**Issue by menghuaxiao** [zhangdaiscott/jeecg-boot#648]
##### 版本号：
2.1.1

##### 问题描述：
现在pom中引入的是jeecg的私服，内网是无法访问互联网的，jar包在开发机中都存在，内网开发中，pom无法从私服下载，引入该如何写？

##### 截图&代码：

![TIM图片20191021142033](https://user-images.githubusercontent.com/40656857/67193174-7415d300-f427-11e9-86f2-5c48abb3b458.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
通过网络下载jar，再通过maven命令，手工安装到本地
