### ISSUE TITLE
2.1.1版online开发无法读取postgre数据库且不报错

### ISSUE THREAD

**Issue by jasonleo0314** [zhangdaiscott/jeecg-boot#649]
##### 版本号：
2.1.1

##### 问题描述：
2.1.0版本中原样配置就可以读取全部pg数据表，2.1.1版本无法读取且不报错。在页面“online开发”中点击按钮“数据库导入表单”，读取结果为空表。后端控制台没有报错，application-dev文件中三个数据源连接配置正确，jeecg_database\.properties文件中只开启了华为云并且配置正确。

##### 截图&代码：
在页面“online开发”中点击按钮“数据库导入表单
![在页面“online开发”中点击按钮“数据库导入表单”](https://user-images.githubusercontent.com/10685079/67200220-c2ca6980-f435-11e9-9e08-d21f256169d1.PNG)
读取结果为空表
![读取结果为空表](https://user-images.githubusercontent.com/10685079/67200221-c2ca6980-f435-11e9-98d7-af970df98ab9.PNG)
后端控制台没有报错
![后端控制台没有报错](https://user-images.githubusercontent.com/10685079/67200223-c3630000-f435-11e9-89da-4965b0a44816.PNG)
三个数据源连接配置正确
![三个数据源连接配置正确](https://user-images.githubusercontent.com/10685079/67200224-c3630000-f435-11e9-9a8e-8828def259ef.PNG)
jeecg_database properties文件中只开启了华为云并且配置正确
![jeecg_database properties文件中只开启了华为云并且配置正确](https://user-images.githubusercontent.com/10685079/67200225-c3fb9680-f435-11e9-9ef0-64fdf80fa5a1.PNG)
文档中这个配置也做了
![文档中这个配置也做了](https://user-images.githubusercontent.com/10685079/67201214-5dc44300-f438-11e9-9eec-506b1e787944.PNG)
引入了驱动包
![引入了驱动包](https://user-images.githubusercontent.com/10685079/67201775-9c0e3200-f439-11e9-8ca0-5c22d533fd49.PNG)
数据库连接测试成功
![数据库连接测试成功](https://user-images.githubusercontent.com/10685079/67200460-6ca9f600-f436-11e9-8e7a-9f06c385dca1.PNG)
数据库内容
![数据库内容](https://user-images.githubusercontent.com/10685079/67200461-6d428c80-f436-11e9-8e40-0279522a708c.PNG)

求助，挺急的，领导要求尽快上线，就我一个研发，做好也不给钱，公益项目。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/67201738-7bde7300-f439-11e9-922d-3ef75786af44.png)

不应该啊，这个能联通吗

**Comment by jasonleo0314** [comment]
能连通

**Comment by zhangdaiscott** [comment]
我们现在用的是 postgres9.6
你是多少版本

**Comment by jasonleo0314** [comment]
那我换个版本先试一下，谢了！

**Comment by jasonleo0314** [comment]
更换了数据库至postgres9.6，还是一样的情况，读不出来且无报错

**Comment by jasonleo0314** [comment]
我退回到2.1.0版本再次尝试，结果可以正常读取pg数据库，可推断此问题为新bug。
![2 1 0版本可以接通](https://user-images.githubusercontent.com/10685079/67208464-2a89b000-f448-11e9-9938-ae1b604c8dfc.PNG)

**Comment by zhangdaiscott** [comment]
好，明天我们测下

**Comment by zhangdaiscott** [comment]
这边测试没有任何问题
![image](https://user-images.githubusercontent.com/3162115/67254308-ef6e9780-f4ae-11e9-8fa9-b7c69cd00be8.png)



![image](https://user-images.githubusercontent.com/3162115/67254296-dfef4e80-f4ae-11e9-9ea6-b67ab0775efe.png)
