### ISSUE TITLE
代码规范和代码质量

### ISSUE THREAD

**Issue by igitee** [zhangdaiscott/jeecg-boot#65]
感慨一声，Jeecg-boot的代码质量和代码规范，比Jeecg差了不少！！！

**Comment by zhangdaiscott** [comment]
请具体说明下，具体哪些地方

**Comment by igitee** [comment]
随手找一处
![image](https://user-images.githubusercontent.com/9738358/56495075-13b0e200-6527-11e9-93bd-a4b53309711a.png)

**Comment by igitee** [comment]
Jeecg就没有这么随意的编码

**Comment by igitee** [comment]
Jeecg就没有这么随意的编码

**Comment by igitee** [comment]
Jeecg就没有这么随意的编码，绝对没有黑的意思，从Jeecg就关注，个人很喜欢的项目！！！

**Comment by zhangdaiscott** [comment]
这个是故意的，原来加了注解，开源给批量替换了，没调格式

**Comment by zhangdaiscott** [comment]
已经修复
