### ISSUE TITLE
关于分类字典编码自动生成

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#650]
##### 问题描述：2。1.1版本中，分类字典的类型编码改成了自动生成，对此，有两个疑问：
1、对于2.1.1以前的版本，数据库中已经存在的数据，类型编码是手工指定的，升级到2.1.1版本后，是否还可以保留原有的编码（因为之前自己指定的编码，在应用中有特定的含义并进行了处理）
2、关于类型编码自动生成，建议不要一刀切，最好创建时，自动生成建议值，用户在界面上可以修改调整，类型编码在具体的应用中会有特定的含义，不建议由平台来固定一种格式。

##### 截图&代码：

<img width="997" alt="截屏2019-10-2208 14 56" src="https://user-images.githubusercontent.com/9619081/67252095-0bb90700-f4a4-11e9-85cc-9ce1c4d80846.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
老数据，可能得删掉，不然编码生成会有问题

**Comment by liaoyongxiong** [comment]
这个很致命呀。我系统里用分类字典构建了中国行政区域树，其中编码字段保存的是行政区域代码。其实，2.1.0的实现是很好用的。

**Comment by zhangdaiscott** [comment]
可以自己改造，原先的模式保证不了编码的上下级，容易出问题

**Comment by shanggushenlong** [comment]
@liaoyongxiong 你好，向你请教一下，怎么分类字典在页面无法创建啊？？

**Comment by zhangdaiscott** [comment]
已经重构，采用系统的规则.
后期可以根据自己的要求比较方便的重构
![image](https://user-images.githubusercontent.com/3162115/70859281-18aa2200-1f4c-11ea-88f9-8275feda2576.png)
