### ISSUE TITLE
系统通告新增公告bug

### ISSUE THREAD

**Issue by 184005306** [zhangdaiscott/jeecg-boot#651]
##### 版本号：
2.1.1

##### 问题描述：
系统公告新增时，内容：富文本插件点击。。。more意思是更多，然后关闭，上传图片不消失

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45930339/67253609-1c20b000-f4ab-11e9-90f0-6b0cc1fd828c.png)

![image](https://user-images.githubusercontent.com/45930339/67253612-25aa1800-f4ab-11e9-90b5-f14a5c614ec3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确认存在问题，我们会尽快修复

**Comment by liudonghua123** [comment]
有点奇怪，我这边 tinymce 显示的一直是如下
![image](https://user-images.githubusercontent.com/2276718/67552918-9c127880-f73e-11e9-9abc-d3f6956bc602.png)

暂时重现不了，我再看看

**Comment by liudonghua123** [comment]
这个问题和tinymce的toolbar_drawer设置有关，如果是floating的时候，会有这个bug，详细信息可参考 https://github.com/tinymce/tinymce/issues/5100， 目前最简单的方式是设置toolbar_drawer为sliding或者false，相应效果如下
sliding效果：(点击more不是弹窗，而是在下面一行显示)
![image](https://user-images.githubusercontent.com/2276718/67627796-db071200-f895-11e9-9731-3e4745a65904.png)
false效果：（没有more，直接显示）
![image](https://user-images.githubusercontent.com/2276718/67627809-fc67fe00-f895-11e9-9ce9-7f1d80f199a8.png)

修改的代码位置是
![image](https://user-images.githubusercontent.com/2276718/67627793-cdea2300-f895-11e9-8a31-51084ead953f.png)

**Comment by liudonghua123** [comment]
详细配置 请参考 https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_drawer

**Comment by zhangdaiscott** [comment]
此问题已处理，下个版本发布
