### ISSUE TITLE
数据规则配置 更改用户部门信息后不生效

### ISSUE THREAD

**Issue by kingshan** [zhangdaiscott/jeecg-boot#653]
##### 版本号：

2.1.1
##### 问题描述：
1在数据规则配置中增加规则值为#{sys_org_code}的配置，规则生效。
2在用户管理中  更改admin的部门信息
3数据规则中获取的sysOrgCode 还是之前的

编辑用户部门会被拦截器注入当前操作用户的sysOrgCode
数据规则中切面代码中的sysBaseAPI.getUserByName(username)会取出来数据库中的对该记录操作用户的sysOrgCode 并缓存，缓存失效前，除非手动切换一下部门，orgCode都是操作用户的orgCode

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12539881/67255197-76be0a00-f4b3-11e9-8fe7-d4092a67edde.png)

![image](https://user-images.githubusercontent.com/12539881/67255310-f4821580-f4b3-11e9-9da1-3b71b3dd7d3c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没完全明白，你的意思是切换用户部门未生效？
新增数据，还是原来登录选择的部门code?
