### ISSUE TITLE
websock分布式的解决方案

### ISSUE THREAD

**Issue by Hachiko-JQ** [zhangdaiscott/jeecg-boot#654]
##### 版本号：
2.1.0

##### 问题描述：
websock在分布式的情况下 session问题无法正常推送到用户 希望能出一个集群的方案

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by kingshan** [comment]
把Websocket服务单独拿出来应该就可以的吧

**Comment by 343122875** [comment]
> 把Websocket服务单独拿出来应该就可以的吧

这样可以是可以的 我现在是把ng转发做了一层判断 理论上是一样的 但是能有集群方案就更好了

**Comment by zhangdaiscott** [comment]
rabbitmq+websocket(SpringBoot版)实现分布式消息推送
    https://www.cnblogs.com/ycnp/p/11990324.html
