### ISSUE TITLE
online表单开发自定义按钮无效

### ISSUE THREAD

**Issue by hellozjf** [zhangdaiscott/jeecg-boot#657]
##### 版本号：

Jeecg-Boot 2.1.1

##### 问题描述：

我按照文档：[http://doc.jeecg.com/1276931](http://doc.jeecg.com/1276931)进行操作

操作完之后，我点击功能测试按钮能够看到按钮确实被加进来了，见图1

然后我使用代码生成，却发现生成出来的vue代码中并没有相应的按钮，见图2

online表单开发自定义按钮这个功能目前是不是还没有开放出来？

##### 截图&代码：

![](https://aliyun.hellozjf.com:7004/uploads/2019/10/22/{01484EDF-3D4D-4FAF-8CC9-4E60F96DD091}_20191022163629.jpg)

![](https://aliyun.hellozjf.com:7004/uploads/2019/10/22/%7B02BEFD49-F18C-47CF-8C45-52E14EC0A9E8%7D_20191022164219.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前还不支持生成，只支持在线
