### ISSUE TITLE
引用activiti-spring-boot-starter-basic  5.23.0报错

### ISSUE THREAD

**Issue by sistit** [zhangdaiscott/jeecg-boot#658]
##### 版本号：
以1.1.0为例，但其他版本也存在问题

##### 问题描述：
引用activiti-spring-boot-starter-basic 5.23.0报错

##### 截图&代码：
启动时提示 Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzJobController': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.scheduling.quartz.SchedulerFactoryBean]: Factory method 'quartzScheduler' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionManager' defined in class path resource [org/activiti/spring/boot/JpaProcessEngineAutoConfiguration$JpaConfiguration.class]: Unsatisfied dependency expressed through method 'transactionManager' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.persistence.EntityManagerFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2019-10-23 09:14:07.527 [main] INFO  org.apache.catalina.core.StandardService:180 - Stopping service [Tomcat]

仅添加引用，以及在Application里修改@SpringBootApplication(exclude= SecurityAutoConfiguration.class)

**Comment by zhangdaiscott** [comment]
抱歉，自己集成产生的问题，请不要在这里提。
