### ISSUE TITLE
如何拦截用户在浏览器的地址栏键入除登录页，首页地址以外的地址，如果不是这两个地址就跳 登录页（用户未登录）或者首页（用户已登录）

### ISSUE THREAD

**Issue by z657622611** [zhangdaiscott/jeecg-boot#659]
##### 版本号：
2.1

##### 问题描述：
普通用户 
       在地址栏 输入 除了登录页地址 或者 首页地址外的其他地址都进行拦截，跳转 登录页（用户未登录）或者首页（用户已登录）

管理员 
      则是跳转 登录页 或者 后台页

##### 截图&代码：
![image](https://user-images.githubusercontent.com/56903118/67351812-f6fe7100-f580-11e9-92bc-6d7c88ca7cc3.png)
此处地址栏 如果键入其他的地址(如：localhost:3000/exam/list)  需要进行拦截  并跳回这个页面

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你可以改造路由拦截器 vue router 实现

src/permission.js:14
