### ISSUE TITLE
如何打开一个新的菜单Tab页

### ISSUE THREAD

**Issue by Huang-ChenGang** [zhangdaiscott/jeecg-boot#660]
##### 版本号：
vue-antd-jeecg  2.0.2

##### 问题描述：
现在是点击菜单列表中的菜单项打开一个新的tab页，如何通过点击某个页面的按钮打开一个新的tab页，具体方法是什么？
然后看你们官网的演示版里有这个功能，但是下载下来的源码就没有。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35560581/67353405-113a4e00-f585-11e9-9c84-aa998c7f7daa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
viewMore(type){
        this.$router.push({
          path: '/process/BpmAutoDesformApplyMore',
          query: {
            procType: type
          }
        })
      },

**Comment by Huang-ChenGang** [comment]
关闭一个Tab页呢？也是通过页面上点击按钮进行操作。

**Comment by Huang-ChenGang** [comment]
你怎么能把issure关闭呢？我都还没确认。
