### ISSUE TITLE
登录页面选择是否自动登录时报错

### ISSUE THREAD

**Issue by chenshouzuo** [zhangdaiscott/jeecg-boot#661]
##### 问题描述：
选择是否自动登录时控制台打印：[Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么浏览器，我这边用谷歌，没报错

**Comment by chenshouzuo** [comment]
我用的也是谷歌，我从github上重新把项目拉下来 什么都没改的情况下 还是这个提示 奇怪





------------------ 原始邮件 ------------------
发件人: "JEECG开源社区"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午2:02
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>;
抄送: "陈守佐"<786869938@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhangdaiscott/jeecg-boot] 登录页面选择是否自动登录时报错 (#661)




什么浏览器，我这边用谷歌，没报错

**Comment by zhangdaiscott** [comment]
截图看看

**Comment by liudonghua123** [comment]
@chenshouzuo [Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event 根据错误信息感觉是checked的属性值问题，可以详细看看错误堆栈是哪里出错，设断点，看看为什么出错

**Comment by chenshouzuo** [comment]
@zhangdaiscott  项目组其他人也有这个问题
<img width="960" alt="1" src="https://user-images.githubusercontent.com/13414622/67741512-58788100-fa54-11e9-82a4-69fbde596dec.png">
<img width="523" alt="2" src="https://user-images.githubusercontent.com/13414622/67741514-59111780-fa54-11e9-8864-4ebdeb79ebfb.png">
<img width="507" alt="3" src="https://user-images.githubusercontent.com/13414622/67741515-59111780-fa54-11e9-95ae-2dc678db7907.png">
<img width="344" alt="4" src="https://user-images.githubusercontent.com/13414622/67741516-59a9ae00-fa54-11e9-9f64-04735c379dd5.png">

**Comment by liudonghua123** [comment]
这个问题的重现步骤是，登陆界面上改变自动登陆的复选框的值，原因是这个a-checkbox使用了v-model的双向数据绑定，其内部的callback会被调用两次，第一次的值是一个event对象，第二次的值是正确的
![image](https://user-images.githubusercontent.com/2276718/67745965-7350f280-fa60-11e9-9ad6-cdcf0ea6b498.png)

![image](https://user-images.githubusercontent.com/2276718/67745986-7fd54b00-fa60-11e9-8046-a7fc7c83a40d.png)

查看antd vue的相关文档，其不建议在antd的组件中使用v-model，最好也不好混用。

https://www.antdv.com/docs/vue/faq-cn/
![image](https://user-images.githubusercontent.com/2276718/67746088-b6ab6100-fa60-11e9-8950-f6b04c0c81be.png)

把 v-model 的使用方式改成和此页面其他组件相同的 v-decorator 方式即可解决问题，详细原因还没有去分析，可能是 antd 封装的组件对于 v-model 的支持有bug或者是上下文环境中的其他组件的事件对其影响（事件捕获、冒泡）

**Comment by liudonghua123** [comment]
这个问题我已在 https://github.com/vueComponent/ant-design-vue 中提交相关issue https://github.com/vueComponent/ant-design-vue/issues/1356

**Comment by chenshouzuo** [comment]
@liudonghua123  @zhangdaiscott 感谢大佬们 愿jeecg越来越强大
