### ISSUE TITLE
代码生成器字段排序

### ISSUE THREAD

**Issue by offves** [zhangdaiscott/jeecg-boot#662]
##### 版本号：
2.1.1

##### 问题描述：
希望代码生成器表字段加上排序, 每次生成后都要手动调整, 比较麻烦

##### 截图&代码：
org.jeecgframework.codegenerate.database.DbReadTableUtil

![image](https://user-images.githubusercontent.com/37245610/67356732-b48f6100-f58d-11e9-8a0c-25f16b461a71.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的
