### ISSUE TITLE
切换部门当前用户信息未更新

### ISSUE THREAD

**Issue by klniu** [zhangdaiscott/jeecg-boot#663]
##### 版本号：
2.1.1

##### 问题描述：
用户在界面点击切换部门后，后台将用户的数据库信息内的org_code更新了，但因为redis里缓存没有更新，因此造成
```java
 (LoginUser)SecurityUtils.getSubject().getPrincipal();
```
获取的仍是过期的信息，而且用户即使退出也无效，建议在更换部门时清除当前用户的信息缓存
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
了解，非常感谢

**Comment by liudonghua123** [comment]
我是这样修改的解决这个问题
1. 切换部门后，清除相关缓存
![image](https://user-images.githubusercontent.com/2276718/67628292-b31bac80-f89d-11e9-8edd-c75895a2acad.png)

2. 用户退出，清楚相关缓存
![image](https://user-images.githubusercontent.com/2276718/67628295-caf33080-f89d-11e9-9ad2-7051aadedd59.png)

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
