### ISSUE TITLE
自己写的列表查询方法，为什么字典配置没效果呢，而系统默认的的列表查询方法就是正常的，区别在哪，有没有解决办法，求大佬指教

### ISSUE THREAD

**Issue by li0801** [zhangdaiscott/jeecg-boot#668]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by zhangdaiscott** [comment]
截图你的代码，看下
初步怀疑是返回的实体类型不对
参考
https://gitee.com/jeecg/jeecg-boot/issues/I126XA
