### ISSUE TITLE
动态路由的带参

### ISSUE THREAD

**Issue by yogwang** [zhangdaiscott/jeecg-boot#669]
##### 版本号：
version:2.1.0（发布日期：20190826）

##### 问题描述：

在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`  
点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`  就可以。
在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id` 

##### 截图&代码：

![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`  
![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)

##### 附
vue@^2.6.10
@vue/cli@^3.8.0
vue-router@^3.0.1

#### 2019年10月25日更新，
使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。

👉 修改 : 菜单管理中，最后不添加 `/:id` ,
使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。

**Comment by zhangdaiscott** [comment]
jeecgboot 针对组件的名字做了规则处理，所以默认不是UserInfo

org.jeecg.modules.system.controller.SysPermissionController#getPermissionJsonObject
自定义name规则
![image](https://user-images.githubusercontent.com/3162115/67630905-8bdad480-f8c9-11e9-867d-d12d590929a0.png)



如果你需要自定义组件名，可以手工改下数据库字段
![image](https://user-images.githubusercontent.com/3162115/67630904-7665aa80-f8c9-11e9-9e42-fbd8fca61df3.png)

**Comment by wangkaiChen1118** [comment]
> ##### 版本号：
> version:2.1.0（发布日期：20190826）
> 
> ##### 问题描述：
> 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> 
> ##### 截图&代码：
> ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> 
> ##### 附
> vue@^2.6.10
> @vue/cli@^3.8.0
> vue-router@^3.0.1
> 
> #### 2019年10月25日更新，
> 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> 
> 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。

请问这个动态生成的路由名称，如果想要生成的 路由的name 后边不带 @参数 , 这个需要后端来修改吗？

**Comment by yogwang** [comment]
> > ##### 版本号：
> > version:2.1.0（发布日期：20190826）
> > ##### 问题描述：
> > 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> > 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> > 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> > ##### 截图&代码：
> > ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> > 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> > ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> > ##### 附
> > vue@^2.6.10
> > @vue/cli@^3.8.0
> > vue-router@^3.0.1
> > #### 2019年10月25日更新，
> > 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> > 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> > 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。
> 
> 请问这个动态生成的路由名称，如果想要生成的 路由的name 后边不带 @参数 , 这个需要后端来修改吗？

上边的回复里说了呀。

**Comment by wangkaiChen1118** [comment]
> ##### 版本号：
> version:2.1.0（发布日期：20190826）
> 
> ##### 问题描述：
> 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> 
> ##### 截图&代码：
> ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> 
> ##### 附
> vue@^2.6.10
> @vue/cli@^3.8.0
> vue-router@^3.0.1
> 
> #### 2019年10月25日更新，
> 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> 
> 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。


> > > ##### 版本号：
> > > version:2.1.0（发布日期：20190826）
> > > ##### 问题描述：
> > > 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> > > 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > > 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> > > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> > > 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> > > ##### 截图&代码：
> > > ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> > > 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > > ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> > > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> > > ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> > > ##### 附
> > > vue@^2.6.10
> > > @vue/cli@^3.8.0
> > > vue-router@^3.0.1
> > > #### 2019年10月25日更新，
> > > 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> > > 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> > > 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。
> > 
> > 
> > 请问这个动态生成的路由名称，如果想要生成的 路由的name 后边不带 @参数 , 这个需要后端来修改吗？
> 
> 上边的回复里说了呀。

这样设置是不会创建一个新标签来，但是此时相当于 params 传参，如果用户手动刷新页面，就会导致参数丢失

**Comment by yogwang** [comment]
> > ##### 版本号：
> > version:2.1.0（发布日期：20190826）
> > ##### 问题描述：
> > 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> > 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> > 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> > ##### 截图&代码：
> > ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> > 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> > ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> > ##### 附
> > vue@^2.6.10
> > @vue/cli@^3.8.0
> > vue-router@^3.0.1
> > #### 2019年10月25日更新，
> > 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> > 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> > 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。
> 
> > > > ##### 版本号：
> > > > version:2.1.0（发布日期：20190826）
> > > > ##### 问题描述：
> > > > 在菜单管理中如技术文档里边所说，填写 `/UserInfo/:id` ，
> > > > 并在页面中使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > > > 点击按钮跳转会到 `/` ，并不会跳转到 `/UserInfo/123456` ，提示 `[vue-router] Route with name 'UserInfo' does not exist` 。
> > > > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>` 就可以。
> > > > 在Vue DevTools中检查发现，`UserInfo` 对应的是 Name 是 `UserInfo-@id`
> > > > ##### 截图&代码：
> > > > ![2](https://user-images.githubusercontent.com/51895542/67458012-b62d5780-f667-11e9-86d0-e01ef2f1703e.jpg)
> > > > 使用 `<router-link :to="{name:'UserInfo', params: {id:id}}">查看</router-link>`
> > > > ![3](https://user-images.githubusercontent.com/51895542/67458015-b6c5ee00-f667-11e9-9556-315945c7822e.jpg)
> > > > 使用 `<router-link :to="'UserInfo/'+id" />查看</router-link>`
> > > > ![4](https://user-images.githubusercontent.com/51895542/67458016-b75e8480-f667-11e9-9268-9dd6bbc8d0c1.jpg)
> > > > ##### 附
> > > > vue@^2.6.10
> > > > @vue/cli@^3.8.0
> > > > vue-router@^3.0.1
> > > > #### 2019年10月25日更新，
> > > > 使用 `:to="'UserInfo/'+id"` 点击多个查看用户后，会创建多个用户资料标签，并且没有激活的方法，来重新获取用户 ID。
> > > > 👉 修改 : 菜单管理中，最后不添加 `/:id` ,
> > > > 使用 `:to="{name:'UserInfo', params: {id:id}}"` 直接传参开的标签可以获得 ID，之后也不会再创建一个新标签。
> > > 
> > > 
> > > 请问这个动态生成的路由名称，如果想要生成的 路由的name 后边不带 @参数 , 这个需要后端来修改吗？
> > 
> > 
> > 上边的回复里说了呀。
> 
> 这样设置是不会创建一个新标签来，但是此时相当于 params 传参，如果用户手动刷新页面，就会导致参数丢失

如果按照他们的方法改写过控制器，就不会丢失参数了。打开在同一个标签页。

**Comment by yangfuhua2009** [comment]
控制器怎么改写,才不会在刷新页面时丢失params参数

**Comment by yogwang** [comment]
@yangfuhua2009 
org.jeecg.modules.system.controller.SysPermissionController#getPermissionJsonObject
自定义name规则

[前端笔记](https://yogwang.site/2019/jeecg-boot-devDiary03/)

**Comment by yangfuhua2009** [comment]
你好,我是用的官方的自定路由规则, this.$router.push({name:'knowledge-CmsArticlechapterList',params:{articleid:id}}); 这样可以正常跳转,只是在f5刷新页面时会丢失params 怎么解决.
特别感谢!!

**Comment by yogwang** [comment]
> 你好,我是用的官方的自定路由规则, this.$router.push({name:'knowledge-CmsArticlechapterList',params:{articleid:id}}); 这样可以正常跳转,只是在f5刷新页面时会丢失params 怎么解决.
> 特别感谢!!

添加菜单的同时增加参数就好了。
例子：
需求查看从文章列表点击文章跳转到文章详情页面
那么在添加菜单路径的时候就是 `/article/detail/:id` 后边的 `:id` 就是你的动态参数名
可以查看 Vue-router 的[官方文档](https://router.vuejs.org/zh/guide/essentials/dynamic-matching.html)，也可以查看我[之前回复](https://github.com/zhangdaiscott/jeecg-boot/issues/669#issuecomment-637899796)的笔记链接。

**Comment by yangfuhua2009** [comment]
![2](https://user-images.githubusercontent.com/15136732/83587704-4890c480-a582-11ea-8544-47d54b955662.png)
看官方回复说 菜单是不加参数的啊
我这边加了参数后就打不开页面了.
我目前用的jeecgboot 2.2 你当时用的2.1会不会有区别

**Comment by yogwang** [comment]
@yangfuhua2009  😂这个是我的开发笔记....
如果不加 `:id` 的话，你可以考虑用 `query` 来传参，如果要用 `params` 就要加上 `:id`，同时路由名称就会被改变，但是你用 `path` 应该没问题。

**Comment by yangfuhua2009** [comment]
真的是已经折腾昨天一天了.用query会打开多个标签页,所以已经放弃了,只能用params,
用params时 菜单路由加:id时,怎么都跳转不成功,
看你文档写的是用这样的方式可以跳转成功.
 <router-link :to="'cmsarticlechapterlist/123'">查看</router-link>

**Comment by yogwang** [comment]
@yangfuhua2009  你在添加菜单的时候增加 `:id` 的参数，但是在跳转操作的的时候就不用加 `:id` 了，
比如我文档里边的例子来说
在添加菜单的时候，菜单路径为 `/UserInfo/:id` ，提交之后它的路由名称就会变成 `Userinfo-@id`;
但是你在跳转的时候就是下边三种情况
1. `this.$router.push({name:"UserInfo-@id:", params: {id:id}})` 使用 `name` 路由
2. `this.$router.push({path:"/UserInfo",query:{id:id}})` 使用 `path` 路由1
3. `this.$router.push({path:"/UserInfo/"+id})` 使用 `path` 路由2

**Comment by yangfuhua2009** [comment]
通过参数可以跳转了,这是地址http://localhost:3000/knowledge/CmsArticlechapterList/39066bbd0e23fba15b3e2674a543247f
这样有个问题是多个标签页打开的,可以控件到单个标签页打开吗

**Comment by yogwang** [comment]
@yangfuhua2009 我记得之前是可以了，后来就没注意的了。

**Comment by King10031** [comment]
> 通过参数可以跳转了,这是地址http://localhost:3000/knowledge/CmsArticlechapterList/39066bbd0e23fba15b3e2674a543247f
> 这样有个问题是多个标签页打开的,可以控件到单个标签页打开吗

问题解决了吗 ？

**Comment by King10031** [comment]
我也是会最终 通过 query会打开两个压面

**Comment by yogwang** [comment]
> 我也是会最终 通过 query会打开两个页面

可以试试用固定的path，然后不增加动态参数然后用params来传参看看，我现在是魔改的Layout没有tabs了。

**Comment by King10031** [comment]
老哥 麻烦看一下我的帖子
https://github.com/jeecgboot/jeecg-boot/issues/2888
