### ISSUE TITLE
@Cacheable不生效问题

### ISSUE THREAD

**Issue by zhangshengbiao** [zhangdaiscott/jeecg-boot#67]
JeecgDemoController中提供的@Cacheable经过测试缓存生效，
但是比如我在SysPermissionController类中增加action如下：
@RequestMapping(value = "/test",method = RequestMethod.GET)
public void test(){
	sysPermissionService.queryPermissionUrlWithStar();
}
serviceimpl实现类中实现如下：
@Override
@Cacheable(value = "permission")
public List<String> queryPermissionUrlWithStar() {
	System.out.println("#######################");
	return this.baseMapper.queryPermissionUrlWithStar();
}

缓存并没有生效，每次都会走queryPermissionUrlWithStar方法。
输出：
#######################
#######################
#######################

**Comment by zhangdaiscott** [comment]
昨天提交了几个代码，你更新试试

**Comment by zhangshengbiao** [comment]
是和shiro集成的问题，把出现在shiroconfig里的bean加上lazy注解就行

**Comment by zhangdaiscott** [comment]
en ，是自己加入新的引入了吧
