### ISSUE TITLE
拉取代码很容易超时

### ISSUE THREAD

**Issue by ydcun** [zhangdaiscott/jeecg-boot#674]
##### 问题描述：
拉取代码很容易超时
##### 截图&代码：

![image](https://user-images.githubusercontent.com/4220967/67629088-2fb58780-f8ac-11e9-8557-2a0bde418f63.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecg-boot
