### ISSUE TITLE
首页无法显示

### ISSUE THREAD

**Issue by zgwangweijian** [zhangdaiscott/jeecg-boot#676]
##### 问题描述：
多页签模式下，开启除首页外的其他页签，然后刷新页面，再次点击首页页签选项卡，无法显示首页

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zgwangweijian** [comment]
再次点击首页（页签选项卡，非左侧菜单），无法显示首页

**Comment by zhangdaiscott** [comment]
请截图
