### ISSUE TITLE
没有看到Activiti的模块和页面

### ISSUE THREAD

**Issue by langchenfujian** [zhangdaiscott/jeecg-boot#677]
##### 版本号：
JeecgBoot 2.1.1

##### 问题描述：
这个版本有没有集成Activiti工作流？ 启动后，在浏览器页面没有找到相关工作流的页面。谢谢查看这个问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6021027/67631427-59cd7080-f8d1-11e9-881c-72d79bcf44cd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
工作流模块不开源
