### ISSUE TITLE
菜单里只有首页一栏

### ISSUE THREAD

**Issue by MarsCircle** [zhangdaiscott/jeecg-boot#681]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/45489550/67701935-cfc5fa80-f9eb-11e9-980f-a8fc680400e0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Youpengac** [comment]
使用admin账户登录下，给jeecg用户对应的角色进行授权，勾选指定的菜单，再用jeecg账户登录时试试

**Comment by MarsCircle** [comment]
他提示我admin用户不存在，请问在哪里设置admin账号呢

**Comment by liudonghua123** [comment]
可能是数据库里面没有这个用户，你看一下 `sys_user` 这个表数据，实在不行，删掉这个数据库，重新导入
