### ISSUE TITLE
上传组件存在问题

### ISSUE THREAD

**Issue by isfang158** [zhangdaiscott/jeecg-boot#682]
##### 版本号：
2.1.1

##### 问题描述：
beforeUpload 中 返回false ，上传组件还是会显示当前上传文件的名称；如下图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50865430/67728203-4d5b2c00-fa27-11e9-97da-938bb7e1c8e1.png)

![image](https://user-images.githubusercontent.com/50865430/67728268-957a4e80-fa27-11e9-851c-b3d5e993d159.png)
![image](https://user-images.githubusercontent.com/50865430/67728281-a62ac480-fa27-11e9-93d8-ba5a2e079e86.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
这个其实不属于这个项目了，a-upload 组件是 antd 的 vue 版本中的上传组件，请详细参考 https://vue.ant.design/components/upload-cn/#components-upload-demo-upload-manually 中的使用说明文档，如果不符合预期，可以在 https://github.com/vueComponent/ant-design-vue 中提交详细issue
