### ISSUE TITLE
前端非根目录部署

### ISSUE THREAD

**Issue by 284658474** [zhangdaiscott/jeecg-boot#684]
##### 版本号：
2.1.0

##### 问题描述：
1、前端打包修改dist文件夹，因Nginx部署多个，对前端不是很熟悉，请指点一下
2、因根据文档只能根目录访问部署没有问题，请问非根目录怎么部署

##### 截图&代码：

![image](https://user-images.githubusercontent.com/35591968/67733168-7e902800-fa38-11e9-841f-53b3f446a281.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
@284658474 这个比较简单，可以搜索看一下文档
![image](https://user-images.githubusercontent.com/2276718/67734356-d67c5e00-fa3b-11e9-8ab1-55eedc070afd.png)

**Comment by 284658474** [comment]
> @ 284658474这个比较简单，可以搜索看一下文档
> ![图片](https://user-images.githubusercontent.com/2276718/67734356-d67c5e00-fa3b-11e9-8ab1-55eedc070afd.png)
我说的是前端

**Comment by liudonghua123** [comment]
这个文档里面有说明啊
![image](https://user-images.githubusercontent.com/2276718/67734925-6c64b880-fa3d-11e9-8123-eae064e3dad9.png)
你没看到？？？

**Comment by 284658474** [comment]
根据文档部署没有问题，build出来dist 文件夹放到nginx 就行了，我的上面说的意思，如何部署多个前端页面，因为bulid都是dist文件

**Comment by liudonghua123** [comment]
你说的是nginx的部署配置文件问题了，每个人的情况不同，应该根据自己的实际业务情况，参考nginx的配置使用文档来配置和调试

**Comment by Nicky213Zhang** [comment]
root 后面直接配置你想要放的物理路径即可，譬如/usr/local/xx/index.html

**Comment by Tech--man** [comment]
@284658474 这位同学的问题没人解答吗

**Comment by liudonghua123** [comment]
@Tech--man 上面已经说的很清楚了啊
