### ISSUE TITLE
富文本组件使用方法

### ISSUE THREAD

**Issue by yogwang** [zhangdaiscott/jeecg-boot#685]
##### 版本号：
2.1.0（发布日期：20190826）

##### 问题描述：
开发文档里边没有富文本组件使用方法，按关键词搜索也没有找到，
官方[视频教程](https://www.bilibili.com/video/av62841643/?p=8)里边的老师也没有找到（av62841643，P8：17:50），
直接去 `components/jeecg` 下找的。

有没有详细说明的文档？

##### 截图&代码：
![Snipaste_2019-10-29_10-45-18](https://user-images.githubusercontent.com/51895542/67733451-5b19ad00-fa39-11e9-9192-5f8122b68b15.jpg)
![Snipaste_2019-10-29_10-47-11](https://user-images.githubusercontent.com/51895542/67733507-869c9780-fa39-11e9-9ef9-ab59f60eb3a5.jpg)
![Snipaste_2019-10-29_10-47-30](https://user-images.githubusercontent.com/51895542/67733508-869c9780-fa39-11e9-85a3-8754fb8d9038.jpg)

**Comment by liudonghua123** [comment]
@yogwang  这个富文本组件本质是 TinyMCE (https://github.com/tinymce/tinymce)， 在vue项目中使用的封装库 https://github.com/tinymce/tinymce-vue ，详细信息可以参考 tinymce 的相关内容即可，其实本身没有多少较难使用的地方，稍微难一点的可能是集成文件上传、文件在线预览管理这块。
