### ISSUE TITLE
MybatisInterceptor不更新updateBy,updateTime问题

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#686]
##### 版本号：
2.1.1

##### 问题描述：
MybatisInterceptor这个拦截器在更新表的update_by和update_time字段的时候加了个原字段值必须为空的判断，导致所有的数据只在第一次修改的时候记录下了修改者和修改时间，之后的所有修改这两个字段都不再做更新。update_by和update_time应该是每次update的时候都要更新的，和原来有没有值没有关系。

另外建议在create的时候，update_by和update_time是不是可以考虑填和create_by，create_time一样的值，空值在有些需要以update_time排序的情况下比较麻烦。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44466941/67739397-4c3cf580-fa4d-11e9-91f1-af21c8b8b74d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Nicky213Zhang** [comment]
> ##### 版本号：
> 2.1.1
> 
> ##### 问题描述：
> MybatisInterceptor这个拦截器在更新表的update_by和update_time字段的时候加了个原字段值必须为空的判断，导致所有的数据只在第一次修改的时候记录下了修改者和修改时间，之后的所有修改这两个字段都不再做更新。update_by和update_time应该是每次update的时候都要更新的，和原来有没有值没有关系。
> 
> 另外建议在create的时候，update_by和update_time是不是可以考虑填和create_by，create_time一样的值，空值在有些需要以update_time排序的情况下比较麻烦。
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/44466941/67739397-4c3cf580-fa4d-11e9-91f1-af21c8b8b74d.png)
> 
> 友情提示： 未按格式要求发帖，会直接删掉。



> ##### 版本号：
> 2.1.1
> 
> ##### 问题描述：
> MybatisInterceptor这个拦截器在更新表的update_by和update_time字段的时候加了个原字段值必须为空的判断，导致所有的数据只在第一次修改的时候记录下了修改者和修改时间，之后的所有修改这两个字段都不再做更新。update_by和update_time应该是每次update的时候都要更新的，和原来有没有值没有关系。
> 
> 另外建议在create的时候，update_by和update_time是不是可以考虑填和create_by，create_time一样的值，空值在有些需要以update_time排序的情况下比较麻烦。
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/44466941/67739397-4c3cf580-fa4d-11e9-91f1-af21c8b8b74d.png)
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

同样碰到这个问题，感谢！顺便问一下，我们是不是可以自行调整这边代码

**Comment by liudonghua123** [comment]
> ##### 版本号：
> 2.1.1
> 
> ##### 问题描述：
> MybatisInterceptor这个拦截器在更新表的update_by和update_time字段的时候加了个原字段值必须为空的判断，导致所有的数据只在第一次修改的时候记录下了修改者和修改时间，之后的所有修改这两个字段都不再做更新。update_by和update_time应该是每次update的时候都要更新的，和原来有没有值没有关系。
> 
> 另外建议在create的时候，update_by和update_time是不是可以考虑填和create_by，create_time一样的值，空值在有些需要以update_time排序的情况下比较麻烦。
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/44466941/67739397-4c3cf580-fa4d-11e9-91f1-af21c8b8b74d.png)
> 
> 友情提示： 未按格式要求发帖，会直接删掉。

有道理 😃

**Comment by zhanjunfeng** [comment]
当然可以自行调整，判断去掉就可以了

**Comment by zhangdaiscott** [comment]
已经处理，下个版本发布
