### ISSUE TITLE
如何监听 v-decorator里面的属性值的改变？

### ISSUE THREAD

**Issue by yangyangs2537** [zhangdaiscott/jeecg-boot#688]
##### 版本号：

1025.2.10
##### 问题描述：
如何监听 v-decorator里面的属性值的改变？
##### 截图&代码：

 <a-form-item label="用户选择v-decorator" style="width: 500px">
      <j-select-multi-user v-decorator="['users']"/>
      {{ getFormFieldValue('users') }}
    </a-form-item>

 watch: {
users？？？？？？？？？？？？？？？？？
 }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
可以在 v-decorator 的 option 中设置 onChange
可参考
https://github.com/react-component/form#usage
https://www.antdv.com/components/form-cn/#this.form.getFieldDecorator(id,-options)-%E5%92%8C-v-decorator=%22[id,-options]%22
