### ISSUE TITLE
前端小细节

### ISSUE THREAD

**Issue by a63149300** [zhangdaiscott/jeecg-boot#690]
##### 问题描述：
大佬您好，本人是枚前端，看了项目感觉很感兴趣，所以看了下前端页面，有几个小细节不知道提得是否合适：
1、项目对src下面的代码没有做eslint   2、代码出现比较多了!=  ==，并没有用严谨的 !== ===  3、ant并没有启用组件按需加载
最后真心希望项目越做越好，关注越来越多，谢谢开源

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
非常感谢，如果可以指出具体修改地方就更好了
