### ISSUE TITLE
菜单管理添加了之后，菜单栏还是没有

### ISSUE THREAD

**Issue by MarsCircle** [zhangdaiscott/jeecg-boot#691]
##### 截图&代码：
![YZ5`8{(K9QGV{LV@1)X}4EW](https://user-images.githubusercontent.com/45489550/67827042-95eb1600-fb09-11e9-997c-fc99df42af0b.png)
![3O@5V7RPL6HN~T_MH(RL3C3](https://user-images.githubusercontent.com/45489550/67827044-97b4d980-fb09-11e9-81e7-8bc89bf0ebdb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
角色授权了吗

**Comment by MarsCircle** [comment]
好的 谢谢，解决了
