### ISSUE TITLE
Tab页如何通过代码关闭

### ISSUE THREAD

**Issue by Huang-ChenGang** [zhangdaiscott/jeecg-boot#692]
##### 版本号：
vue-antd-jeecg 2.0.2

##### 问题描述：
现在是点击菜单列表中的菜单项打开一个新的tab页，如何通过点击某个页面的按钮关闭这个tab页，具体方法是什么？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35560581/67836688-39e3ba00-fb28-11e9-9b80-b4df6fb1bcc4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
这个不难，可以参考 https://www.antdv.com/components/tabs-cn/ 看看，其实就是通过修改数据动态渲染 `a-tab-pane`

![image](https://user-images.githubusercontent.com/2276718/68028920-fc7e5880-fcf0-11e9-9ead-86bda21890f4.png)

**Comment by sjlei** [comment]
通过点击按钮新开一个tab页面，可以通过下面这种方式实现：

``` js
this.$router.push({ path: string })
```

示例：

``` js
this.$router.push({ path: "/jeecg/helloworld" })
```

但是如果想要通过点击按钮关闭某个Tab页面，不好做，比较难实现。

**Comment by zypy333** [comment]
偷懒没搜到解决方案，还是自己搞出来了，留给后面要用的人

`const route = useRoute();
 const router = useRouter();
 const tabStore = useMultipleTabStore();

tabStore.closeTabByKey(route.fullPath, router);`
