### ISSUE TITLE
时间范围查询问题

### ISSUE THREAD

**Issue by DeanXW** [zhangdaiscott/jeecg-boot#693]
##### 版本号：

自己使用2.0.2出现这个问题  在jeecg-boot 在线演示版本也发现这个问题
##### 问题描述：
使用范围查询时均无法返回正确的数据，直接一条数据也没有，解决办法是直接使用时间字符串进行范围查询，不用将字符串转化为Date类进行范围查询
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18533634/67838260-dd829980-fb2b-11e9-896b-1a63c2e1f608.png)

![image](https://user-images.githubusercontent.com/18533634/67838327-060a9380-fb2c-11e9-9b16-7f539d789fa8.png)
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by DeanXW** [comment]
test error

**Comment by hjhcos** [comment]
这个逻辑是错误的 在源码里面 是通过在字段的尾部加上_begin和_end来设置区间的
![66ef8d5d3e5a387c78e844265d47459](https://github.com/jeecgboot/jeecg-boot/assets/54499588/159c31b0-2c02-4243-9b0e-0d6baa0df636)

**Comment by hjhcos** [comment]
如果按照你得方法那么后台实体类里面字段不定义为Date是定义为String，那么使用QueryGenerator.initQueryWrapper来拼接的sql语句就是eq 不是 ge 或 le

**Comment by hjhcos** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/a114f30f-c957-48e8-81b2-75b3e681261b)
解决方法是这里加个类型判断  如果是日期或数字就是数组的形式，ge第一个数组是_begin，le第二个数组是_end，如果是字符串，那么就需要前端在传参数时在字段加上_begin和_end，查询条件应该为in

**Comment by hjhcos** [comment]
我这边尝试了修改 doIntervalQuery 这个方法发现是不可行的，还是通过前端加后缀方便些，具体修改方案如下：
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/a08b3afa-791d-4996-b93c-5960322f61a3)
因为字段会被赋值，而又无法深入对字段的赋值进行清空，就会出现eq和区间查询同时存在。

**Comment by hjhcos** [comment]
因此最好的办法还是前端加后缀，区间 _begin和_end，in _MultiString
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/43b6d610-e109-4870-859a-460e2a0308d2)
