### ISSUE TITLE
postgresql 驱动 配置不正确  groupId 应该是 org.postgresql

### ISSUE THREAD

**Issue by walnut-tom** [zhangdaiscott/jeecg-boot#694]
##### 问题描述：
postgresql 驱动 配置不正确  groupId 应该是 org.postgresql
```
<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <version>42.2.6</version>
</dependency>

```
##### 截图&代码：

```
<!-- postgresql驱动 -->
        <dependency>
            <groupId>postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.5</version>
            <scope>runtime</scope>
        </dependency>

```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
确实是这样的

https://mvnrepository.com/artifact/postgresql/postgresql
![image](https://user-images.githubusercontent.com/2276718/68072267-dd4dfc80-fdbe-11e9-96c4-486d83e2658e.png)

https://mvnrepository.com/artifact/org.postgresql/postgresql
![image](https://user-images.githubusercontent.com/2276718/68072272-f0f96300-fdbe-11e9-810b-0ade7188188c.png)

**Comment by zhangdaiscott** [comment]
已修复下个版本发布
