### ISSUE TITLE
代码生成器生成的后台 mapper和service都是空的，请问这个正常吗？

### ISSUE THREAD

**Issue by MarsCircle** [zhangdaiscott/jeecg-boot#696]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/45489550/67877727-18f58600-fb75-11e9-9c0f-e192a7b62efd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没问题
