### ISSUE TITLE
职务查询时出现错误-sys_position表

### ISSUE THREAD

**Issue by lllcr** [zhangdaiscott/jeecg-boot#697]
##### 问题描述：
在用户管理中 --操作栏-更多-详情
职务一栏查询不到数据，后台报错
sql 直接拿出来也不能查询，原因是有个字段疑似 mysql 关键字段 ，加上单引号就可以了。

但不知道系统中怎么解决这个问题！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34624646/67911064-12d8c700-fbc0-11e9-8a9f-4c1a41d1a07f.png)

![image](https://user-images.githubusercontent.com/34624646/67911160-8549a700-fbc0-11e9-9dbe-691d3f147c48.png)
![image](https://user-images.githubusercontent.com/34624646/67911272-e7a2a780-fbc0-11e9-96c7-e869e2176f4d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，我们看看

**Comment by guozhanxian** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/1329731/68527718-294ff280-0325-11ea-8ab5-60d7b05ad467.png">
我是MySQL5.7.18是没有问题的。看上去好像是MySQL版本的问题。可能是MySQL8里rank是关键字。

**Comment by liudonghua123** [comment]
rank 确实是 MySQL8 的关键字
有两种方式可以解决
1. 生成的sql的字段名需要使用`rank`来标识
2. 修改rank字段名为其他字段名
![image](https://user-images.githubusercontent.com/2276718/69016865-8a3e9100-09dd-11ea-8082-82a2089c4b50.png)

**Comment by lllcr** [comment]
谢谢

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/69017295-038bb300-09e1-11ea-9c6d-9ae413e544cd.png)
按照上面的文档这样修改应该就可以了，相比修改字段名称，这种方式应该是最快的
![image](https://user-images.githubusercontent.com/2276718/69017318-25853580-09e1-11ea-92eb-4dbe557e759f.png)

详细3.x删除关键字自动转义功能的讨论可参考
https://github.com/baomidou/mybatis-plus/issues/399

**Comment by lllcr** [comment]
文档更新了？

**Comment by liudonghua123** [comment]
@llcr 没有更新，我上面的文档是 mybatis plus 的文档，他的更新了，对于自己的业务逻辑代码，我们可以修改代码生成模板，所有字段都添加上 ``@TableField("`fieldName`")``，这样就可以了。
框架层面的代码就需要手动修改了

**Comment by zhangdaiscott** [comment]
已经修改下个版本发布
