### ISSUE TITLE
使用代码生成器之后的生成的菜单，点击新增的时候发生了这样的报错

### ISSUE THREAD

**Issue by MarsCircle** [zhangdaiscott/jeecg-boot#698]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/45489550/67927129-cc509000-fbf2-11e9-8ddb-6e0b87aa1afa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己排查错误吧，应该只字段不匹配

**Comment by yanyapeng123** [comment]
0
