### ISSUE TITLE
websocket 无法被代理

### ISSUE THREAD

**Issue by wrs645776258** [zhangdaiscott/jeecg-boot#699]
##### 版本号：
2.1.0

##### 问题描述
我的前端是使用域名发布的，后端是使用的本机地址，websocket无法被nginx代理访问
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wrs645776258** [comment]
![image](https://user-images.githubusercontent.com/28645200/67997527-6d8d2400-fc8f-11e9-9f1b-f921d5be4306.png)

**Comment by wrs645776258** [comment]
还有大家需要注意的地方在项目的index.html页面 
![image](https://user-images.githubusercontent.com/28645200/67997613-cb217080-fc8f-11e9-8d72-5dcf68e07208.png)

**Comment by chenshouzuo** [comment]
3Q，绕了半天，看了最下面的图，绕出来了！（如果按照最下面那张写死的话，内网环境下会出错。）

**Comment by liudonghua123** [comment]
嗯，`websocket`的`nginx` `proxy_pass` 代理处必须要添加这两个配置
```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```
这两个配置即使不是`ws`的代理也是安全的（参考 https://github.com/jwilder/nginx-proxy 的实现 ）

`window._CONFIG` 这里的配置我是这样写的，可以本地调试+生产环境部署
```
    <script>
      window._CONFIG = {}
      window._CONFIG['domianURL'] =
        'http://' + (document.location.hostname === 'localhost' ? 'localhost:8080' : document.location.host)
      window._CONFIG['casPrefixUrl'] = 'http://cas.example.org:8443/cas'
      window._CONFIG['imgDomainURL'] = window._CONFIG['domianURL'] + '/sys/common/view'
      window._CONFIG['pdfDomainURL'] = window._CONFIG['domianURL'] + '/sys/common/pdf/pdfPreviewIframe'
    </script>
```

**Comment by wrs645776258** [comment]
> 3Q，绕了半天，看了最下面的图，绕出来了！（如果按照最下面那张写死的话，内网环境下会出错。）

可以参考下面的写法

**Comment by wrs645776258** [comment]
> 嗯，`websocket`的`nginx` `proxy_pass` 代理处必须要添加这两个配置
> 
> ```
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
> ```
> 
> 这两个配置即使不是`ws`的代理也是安全的（参考 https://github.com/jwilder/nginx-proxy 的实现 ）
> 
> `window._CONFIG` 这里的配置我是这样写的，可以本地调试+生产环境部署
> 
> ```
>     <script>
>       window._CONFIG = {}
>       window._CONFIG['domianURL'] =
>         'http://' + (document.location.hostname === 'localhost' ? 'localhost:8080' : document.location.host)
>       window._CONFIG['casPrefixUrl'] = 'http://cas.example.org:8443/cas'
>       window._CONFIG['imgDomainURL'] = window._CONFIG['domianURL'] + '/sys/common/view'
>       window._CONFIG['pdfDomainURL'] = window._CONFIG['domianURL'] + '/sys/common/pdf/pdfPreviewIframe'
>     </script>
> ```

这种写法不错，解决内外网冲突问题

**Comment by wrs645776258** [comment]
上面的写法不错，解决了，重复修改地址的问题

**Comment by shanggushenlong** [comment]
请教下大家，项目现在websocket总是向后台发请求，而且总是报错
，这是什么情况呢？什么原因导致的，我百度了很多，感觉都不行
![image](https://user-images.githubusercontent.com/20007857/70505206-63015c80-1b62-11ea-853b-94bbd17c03c5.png)

**Comment by shanggushenlong** [comment]
总是报错如下：
WebSocket connection to 'ws://127.0.0.1:8080/bronze-cps/websocket/e9ca23d68d884d4ebb19d07889727dae' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by zhangdaiscott** [comment]
应该是你后台断过

**Comment by shanggushenlong** [comment]
好的，谢谢

**Comment by Caisen1988** [comment]
@shanggushenlong 您好，请问你是如何解决的

**Comment by zhangdaiscott** [comment]
```
  location /jeecg-boot {
            proxy_pass http://szy-fx;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Via "nginx";

            # 要支持websocket得这么写，不然CentOS上可能失败
            # proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
```

**Comment by Caisen1988** [comment]
@zhangdaiscott 您好，请问http://szy-fx;指向的是8080端口吗

**Comment by NewOrForever** [comment]
.env 环境配置文件中我是这么配置的
`VUE_APP_API_BASE_URL=/api` 

initWebSocket 方法中我这样改的，重新组装
这样就可以在测试和生产环境中试用了
```
var url = "";
if (window._CONFIG['domianURL'].indexOf('https://') !== -1 || window._CONFIG['domianURL'].indexOf('http://') !== -1) {
  url = window._CONFIG['domianURL'].replace("https://", "wss://").replace("http://", "ws://") + "/websocket/" + userId;
} else {
  var protocol = window.location.protocol;
  var host = window.location.host;
  url = protocol + "//" + host + window._CONFIG['domianURL'] + "/websocket/" + userId;
  url = url.replace("https://", "wss://").replace("http://", "ws://");
}
```

**Comment by liubaolong123** [comment]
我在本地跑的，也遇到了同样的错误
