### ISSUE TITLE
查询用户拥有的菜单权限和按钮权限 有漏洞

### ISSUE THREAD

**Issue by ares007** [zhangdaiscott/jeecg-boot#70]
main/java/org/jeecg/modules/system/controller/SysPermissionController.java
在queryByUser里，前端如果修改username的值，可以获取其它用户的菜单权限。
建议用getUserNameByToken获取username

**Comment by zhangdaiscott** [comment]
ok

**Comment by zhangdaiscott** [comment]
已经修复下个版本发布
