### ISSUE TITLE
table中如何展示图片

### ISSUE THREAD

**Issue by Huang-ChenGang** [zhangdaiscott/jeecg-boot#700]
##### 版本号：
vue-antd-jeecg 2.0.2

##### 问题描述：
table中如何展示图片，就是标签a-table中，如何展示图片。下边是我自己写的代码，没有效果

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35560581/67958908-e6aa5e00-fc32-11e9-83da-c0c26afc375a.png)

`columns: [
    {
            title: '图片',
            align: "center",
            width: 100,
            dataIndex: '',
            key: 'headImgUrl',
            render: (o, row) => (
              <span><img src={o.headImgUrl} alt="" style={{width:'50px',height:'50px'}}/></span>
            )
      }
]`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考用户管理的头像功能
