### ISSUE TITLE
如何分页进行合计呢？

### ISSUE THREAD

**Issue by tb19901109** [zhangdaiscott/jeecg-boot#701]
##### 问题描述：

目前，只有在不分页情况下进行合计，当分页情况下有两种方案均存在问题，1比如单页显示是10条，合计为第11列，就被隐藏掉。2当每页显示10条时，后台返回9条在拼上一条合计，可以显示正常，但是页面上只有9条数据加上一条合计。
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己在后台实现合计，作为最后一行数据展示

**Comment by yanyapeng123** [comment]
> ##### 版本号：
> ##### 问题描述：
> 目前，只有在不分页情况下进行合计，当分页情况下有两种方案均存在问题，1比如单页显示是10条，合计为第11列，就被隐藏掉。2当每页显示10条时，后台返回9条在拼上一条合计，可以显示正常，但是页面上只有9条数据加上一条合计。
> 
> ##### 截图&代码：
> 友情提示： 未按格式要求发帖，会直接删掉。

你现在这个功能实现了吗，如何做呢？
