### ISSUE TITLE
在线开发，代码生成功能生成的vue页面，数据的校验失效

### ISSUE THREAD

**Issue by chinazml** [zhangdaiscott/jeecg-boot#702]
##### 问题描述：在线开发，代码生成功能生成的vue页面，数据的校验失效（包括唯一性校验、输入长度、数字校验、小数校验等，见截图），同样的功能在在线功能测试的时候有效。
还有选中三列分布，生成的vue是不分列的。

##### 截图&代码：
![微信截图_20191101155323](https://user-images.githubusercontent.com/56468753/68010911-da6ce200-fcc0-11e9-8264-6946c2ed8810.png)
![QQ截图20191101155725](https://user-images.githubusercontent.com/56468753/68010926-e062c300-fcc0-11e9-8123-672a15de1c79.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
代码生成不支持三列模板，校验的话我们看下

**Comment by sjlei** [comment]
Online代码生成器校验这一块已经补全了，支持所有可选的验证规则，将在下个版本更新，敬请期待
