### ISSUE TITLE
JEditableTable能否将字段隐藏

### ISSUE THREAD

**Issue by wjxjasin** [zhangdaiscott/jeecg-boot#703]
##### 问题描述：
JEditableTable的特点是编辑数据的时候先删除旧数据，再重新添加，但是如果JEditableTable没有将该字段显示的话，修改保存的时候，就会将该字段的值置空，导致数据出现异常。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49051702/68012113-1d7c8480-fcc4-11e9-8c5a-c520451e57f2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
@wjxjasin `JEditableTable`中如果不想显示的字段在columns中删掉就行，但是会出现你所说的提交表单的时候这个字段是空的，这时候就需要自行在提交表单之前处理了

**Comment by wjxjasin** [comment]
谢谢！交给后台确实解决很多问题



------------------ 原始邮件 ------------------
发件人: "liudonghua"<notifications@github.com>; 
发送时间: 2019年11月1日(星期五) 晚上9:23
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com>; 
抄送: "jasin"<wjxjasin@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zhangdaiscott/jeecg-boot] JEditableTable能否将字段隐藏 (#703)




@wjxjasin JEditableTable中如果不想显示的字段在columns中删掉就行，但是会出现你所说的提交表单的时候这个字段是空的，这时候就需要自行在提交表单之前处理了

**Comment by sjlei** [comment]
你好，当前版本的JEditableTable组件支持隐藏列功能，实现方式参考：
![image](https://user-images.githubusercontent.com/34293221/68289326-df66d280-00c0-11ea-9ad1-e8c3182e9869.png)

但是有个小BUG，所以尚未公开，具体表现为：当dataSource是静态数据的时候，配置成隐藏列会有问题，异步查询出来的数据是没问题的。

这个问题已在新版本中修复，请耐心等待新版本的发布。
