### ISSUE TITLE
online 开发根路径问题

### ISSUE THREAD

**Issue by lanfen100** [zhangdaiscott/jeecg-boot#704]
##### 问题描述：
前后台项目修改 项目根路径，context-path 为 xxx 后，前端 online 开发时候，请求跟路径仍为 /jeecg-boot 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12097469/68101574-3e81e700-ff09-11e9-8691-225e7acf6b00.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44
