### ISSUE TITLE
a-table 怎么设置默认展开行或者全部展开

### ISSUE THREAD

**Issue by skfiy** [zhangdaiscott/jeecg-boot#706]
##### 版本号：
vue-antd-jeecg 2.0.2

##### 问题描述：
a-table 怎么设置默认展开行或者全部展开？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23720918/68180889-612b0300-ffd0-11e9-92ed-6d2eb8d5504e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://www.antdv.com/components/table-cn/
![image](https://user-images.githubusercontent.com/3162115/68362648-f78f2e00-0162-11ea-9b7d-c29012a64c4a.png)
