### ISSUE TITLE
角色功能列表不能查看和修改关联的用户，必须去用户列表才能修改所属的角色。不方便

### ISSUE THREAD

**Issue by heidongzai** [zhangdaiscott/jeecg-boot#707]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/19759686/68188839-064fd680-ffe5-11e9-8344-5741d6faf6c3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by guozhanxian** [comment]
在用户多的系统里，这个功能意义不大。从很多用户中查找你要操作的用户也是不方便。

**Comment by zhangdaiscott** [comment]
此功能已经实现，下个版本发布
