### ISSUE TITLE
支持哪些浏览器

### ISSUE THREAD

**Issue by 13917189872** [zhangdaiscott/jeecg-boot#709]
##### 版本号：
2.1.1

##### 问题描述：
当前2.1.1版本，支持哪些浏览器，浏览器最低版本是多少，貌似只支持IE11+，IE10以下不能正常使用，希望老师给个回复，谢谢。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/15811523/68353954-0adfd080-0146-11ea-836a-2f2c752fa41f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
IE11+
