### ISSUE TITLE
关于系统router扩展的问题，和思路

### ISSUE THREAD

**Issue by xiuxiuyifan** [zhangdaiscott/jeecg-boot#713]
##### 截图&代码：

 
![image](https://user-images.githubusercontent.com/27720360/68394796-7313ce00-01a9-11ea-8388-9453c700db5d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考，通过机构选择人组件
![image](https://user-images.githubusercontent.com/3162115/68523720-f2afb300-02f7-11ea-9a20-0a1318952ea4.png)

![image](https://user-images.githubusercontent.com/3162115/68523719-ecb9d200-02f7-11ea-9c92-c607711e3a4a.png)

**Comment by xiuxiuyifan** [comment]
好的我试试，谢谢哈
