### ISSUE TITLE
j-dict-select-tag 表单编辑回显失败

### ISSUE THREAD

**Issue by yangting793** [zhangdaiscott/jeecg-boot#715]
##### 版本号：
j-dict-select-tag 表单编辑回显中文

##### 问题描述：
j-dict-select-tag 读取数据字典数据，表单编辑下拉框应该默认显示成中文。现在编辑回显是显示的数据表中的status，而不是中文。想要的效果是，编辑是默认显示成数据字典的 item_text 数据字典项文本

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/56527567/68482803-4927dd80-0275-11ea-8eb8-2ea1c0c09a85.png)
![图片](https://user-images.githubusercontent.com/56527567/68482829-580e9000-0275-11ea-9bb8-42864a30812f.png)
![图片](https://user-images.githubusercontent.com/56527567/68482906-7b393f80-0275-11ea-84f7-77023fd092cf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
@yangting793 是不是数据字典里的 `finish_status` 配置的有问题
可以在仔细看看 以下文档
http://doc.jeecg.com/1273909
http://doc.jeecg.com/1273880

**Comment by yangzhiwei666** [comment]
@yangting793 我也出现了这样的问题，请问解决了没？

**Comment by yangting793** [comment]
@yangzhiwei666 已经解决，你仔细看一下数据字典的类型与业务标准字段类型是否一致。
![图片](https://user-images.githubusercontent.com/56527567/68556443-3ed03400-046d-11ea-9cc0-a339062ccbd0.png)

**Comment by liudonghua123** [comment]
@yangting793 @yangzhiwei666 你们提供更多信息，例如 数据字典里面的配置项，这样才方便分析问题原因

**Comment by liudonghua123** [comment]
@yangting793 @yangzhiwei666 你们提供更多信息，例如 数据字典里面的配置项，这样才方便分析问题原因

**Comment by yangting793** [comment]
@liudonghua123 已经解决。

**Comment by yangting793** [comment]
@liudonghua123 谢谢啦。

**Comment by yangzhiwei666** [comment]
@yangting793 
![image](https://user-images.githubusercontent.com/32032126/68556647-15fc6e80-046e-11ea-8b8b-ce4de8df9ce2.png)
![image](https://user-images.githubusercontent.com/32032126/68556669-2ad90200-046e-11ea-91a6-e6f7d1611a1a.png)
![image](https://user-images.githubusercontent.com/32032126/68556689-3e846880-046e-11ea-9ec0-b45b4e11d618.png)
我已经吧pick放到外面了，还是没有翻译过来

**Comment by yangzhiwei666** [comment]
@yangting793 已找到问题，是因为我字段是Integer类型，回填没对应
