### ISSUE TITLE
[Bug]代码生成器检查数据表是否存在（For Linux and Mac）

### ISSUE THREAD

**Issue by violetice** [zhangdaiscott/jeecg-boot#716]
##### 版本号：
2.1.1（发布日期：20191021）

##### 问题描述：
开发的时候生成代码都是java同学搞得，他的 MySQL 用的 Windows 版本，**不区分大小写**。 
现在是 Linux 测试环境，因为数据库有点改动，需要重新生成一下代码。`jeecg_database.properties`也是连的 Linux 上的 MySQL 了。

我检查代码发现这里居然把表名转换成大写了？！出于什么原因要转换成大写呢？

codegenerate-1.0.7.jar
```java
package org.jeecgframework.codegenerate.database;
...
public static boolean c(String var0) {
    ...
    if (org.jeecgframework.codegenerate.a.a.a.equals("mysql")) {
        var2 = "select column_name,data_type,column_comment,0,0 from information_schema.columns where table_name = '" + var0.toUpperCase() + "' and table_schema = '" + org.jeecgframework.codegenerate.a.a.f + "'";
    }
    ...
}
```

这里的`var0`不能使用`toUpperCase()`，对 Linux 和 Mac 很不友好。
因为大写表名也有用处，所以不能把数据库设置成不区分大小写。
我现在是先把大写表名改成别的名字，再把小写表名该大写，生成了代码之后再改回去。好累。。。

##### 问题截图：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已修复
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.0.8</version>
</dependency>
