### ISSUE TITLE
spring boot 配置开启压缩问题

### ISSUE THREAD

**Issue by wrs645776258** [zhangdaiscott/jeecg-boot#718]
##### 版本号：
2.1.0

##### 问题描述：
spring boot 配置开启压缩，配置错误
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28645200/68558096-ffa4e180-0472-11ea-8e75-0cac32a7b5ab.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wrs645776258** [comment]
应该改为：
![image](https://user-images.githubusercontent.com/28645200/68558167-3ed33280-0473-11ea-865f-91c898a6f208.png)

**Comment by zhangdaiscott** [comment]
好

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
