### ISSUE TITLE
页面问题

### ISSUE THREAD

**Issue by igitee** [zhangdaiscott/jeecg-boot#72]
如图
![image](https://user-images.githubusercontent.com/9738358/56677014-262b4700-66f2-11e9-953c-af0ae9aa8350.png)
提示信息被覆盖

**Comment by zhangdaiscott** [comment]
你的版本是多少，老版有这个问题，新版1.1应该没了

**Comment by igitee** [comment]
![image](https://user-images.githubusercontent.com/9738358/56779286-da20f500-680c-11e9-8e48-2a51df0880e1.png)
额，官方演示版，谷歌浏览器版本
![image](https://user-images.githubusercontent.com/9738358/56779316-0b99c080-680d-11e9-9c66-f908d39cd539.png)

**Comment by igitee** [comment]
本地浏览器缓存问题，谢谢解答
