### ISSUE TITLE
项目存在相同包名和类名

### ISSUE THREAD

**Issue by wrs645776258** [zhangdaiscott/jeecg-boot#722]
##### 版本号：
2.1.1

##### 问题描述：
此类SysPermissionDataRule 在
jeecg-boot-base-common和 jeecg-boot-module-system项目中都有，而且包名一致，这个可能是你们项目在写后续通用类，为了不去做之前使用地址的修改（可能有其它原因，请告知），而创建，这样不是很合理吧。后续进行修改要同时修改两处，如果我只修改jeecg-boot-base-common，而不修改jeecg-boot-module-system下的（加一个属性），调用相关方法是会出错的，因为jvm对同包同类名只会加载第一个。
 而且，出现同包名同类名，也属于一种错误设计吧。建议后续对包名做一些优化，避免出现这种问题。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确存在不规范写法，后期考虑改进

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
