### ISSUE TITLE
Online表单开发代码生成BUG

### ISSUE THREAD

**Issue by Jaxzzxml** [zhangdaiscott/jeecg-boot#723]
##### 问题描述：
数据库表结构为主表A，附表A1（一对一），附表A2（一对多），附表A3（一对多）。自动生成的代码放到项目上后 “添加” 和 ”修改” 功能前端报错。原因是自动生成的存储附表值的数组下标为1,2，而正确的下标应该为0,1

##### 截图&代码：
classifyIntoFormData(allValues) {
        let main = Object.assign(this.model, allValues.formValue)

        return {
          ...main, // 展开
          A1: this.$refs.projectSummaryForm.getFormData(),
          A2: allValues.tablesValue[1].values,//此处应该为0
          A3: allValues.tablesValue[2].values,//此处应该为1
        }
      },

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by cjy37** [comment]
mark

**Comment by zhangdaiscott** [comment]
你是什么版本？ 为什么我生成的是对的呢
