### ISSUE TITLE
不管用哪个用户登陆 create_by 插入的都是 jeecg

### ISSUE THREAD

**Issue by zn123** [zhangdaiscott/jeecg-boot#726]
##### 版本号：

2.1.1
##### 问题描述：
不管用哪个用户登陆 create_by 插入的都是 jeecg
sys_org_code 注入失败

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
跟代码看看
org.jeecg.config.mybatis.MybatisInterceptor

**Comment by zn123** [comment]
解决了，调试的时候把 这个路径的登陆要求 设成了 anon 了，系统默认填了jeecg
