### ISSUE TITLE
前端项目打包时排除部分组件该如何配置

### ISSUE THREAD

**Issue by cjalchange** [zhangdaiscott/jeecg-boot#728]
##### 版本号：
2.1.1

##### 问题描述：
为了减少线上项目js文件的大小，我打算将线上不需要的组件在打包时排除掉，比如“Online表单配置”模块，这个只需要在开发时使用，上线后是不使用的。这种情况下我应该如何配置呢？

**Comment by zhangdaiscott** [comment]
手工删掉
