### ISSUE TITLE
前端defaultSettings配置关闭多页签模式无效

### ISSUE THREAD

**Issue by kingshan** [zhangdaiscott/jeecg-boot#730]
##### 版本号：
2.1.1

##### 问题描述：
修改前端工程的  defaultSettings.js中的multipage: false, //默认多页签模式 无效
查看main.js  存值得时候没有从js里取

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12539881/68931225-12991800-07cb-11ea-9187-bfa90398e25b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
嗯，确实是，这里如果`localstorage`里面没有`multipage`相关设置，就是用默认的`true`，而不会类似于上面的从`config`中获取默认值，如果需要从`defaultSettings`中使用默认的`multipage`，只需要把`true`改成`config.multipage`即可，然后清空`localstorage`，刷新网页就可以生效了
修改如下
![image](https://user-images.githubusercontent.com/2276718/69018238-5451da80-09e6-11ea-9bde-c15e44acee42.png)

这里暂时不清楚为什么要这么写，可能的原因是希望默认就是用`multipage`，这样方便后台管理，其实这里应该就在`defaultSettings.js`中设置`multipage: true`, `main.js` 中像上面一样默认使用`config.multipage`这样会比较优雅一点。

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布

**Comment by Nicky213Zhang** [comment]
> 已经修复，下个版本发布

您好，对这个设置多页签的问题有俩个疑问，1：新版本修复该bug的地方，是否只需要修改main.js；2：每次切换都需要清空缓存，这对线上项目实施起来非常困难，有没有办法解决
