### ISSUE TITLE
指定功能前端代码未找到的问题

### ISSUE THREAD

**Issue by liangklfangl** [zhangdaiscott/jeecg-boot#731]
##### 版本号：
最新master

##### 问题描述：
为啥这些前端代码未在项目中找到

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25046350/69003912-22d50280-0945-11ea-9c42-f5073f995493.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liangklfangl** [comment]
@zhangdaiscott  希望能解答下

**Comment by zhangdaiscott** [comment]
有的非开源功能
