### ISSUE TITLE
online代码生成器能生成代码到其它的Maven模块中去吗?

### ISSUE THREAD

**Issue by MyOnlyCat** [zhangdaiscott/jeecg-boot#732]
##### 版本号：
2.1.1

##### 问题描述：
在online代码生成器的配置中只能配置代码生成到某个包下,能够配置为生成到某个maven模块中去吗?比如默认生成是在 **jggcg-boot-module-system**中,而我想让代码生成到我自己的模块**jggcg-boot-module-lqtest**

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以，代码生成项目地址路径即可
jeecg/jeecg_config.properties

![image](https://user-images.githubusercontent.com/3162115/69044251-92bfb780-0a2f-11ea-8a54-f17b86d4056c.png)
