### ISSUE TITLE
JeecgListMixin.js中初始化表格数据建议放到mounted钩子函数中

### ISSUE THREAD

**Issue by dssweb** [zhangdaiscott/jeecg-boot#735]
##### 版本号：
2.1.0

##### 问题描述：
路由跳转到另一个页面，传参，跳转到的页面参数无效，因为JeecgListMixin.js是在created的钩子函数中初始化的表格数据，建议将初始化表格和字典表的方法放到mounted钩子函数中

##### 截图&代码：
现在JeecgListMixin.js中的代码：
  created() {
    this.loadData();
    //初始化字典配置 在自己页面定义
    this.initDictConfig();
  },
建议修改为：
  mounted() {
    this.loadData();
    //初始化字典配置 在自己页面定义
    this.initDictConfig();
  },

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块恐怕得自己实现了，本地这块有缺陷，因为created不会被覆盖。
