### ISSUE TITLE
组件饼状图无效

### ISSUE THREAD

**Issue by shanggushenlong** [zhangdaiscott/jeecg-boot#736]
##### 版本号：
2.1.1

##### 问题描述：
引入jeecgboot项目中提供的饼状图组件，无效

##### 截图&代码：
代码引入如下：

<Pie :dataSource="dataSource"></Pie>

import Pie from '@/components/chart/Pie'

dataSource:[
             // 所有的 percent 相加等于 100
            { "item": "一月", "percent": 41 },
            { "item": "二月", "percent": 20 },
            { "item": "三月", "percent": 17 },
            { "item": "四月", "percent": 13 },
            { "item": "五月", "percent": 9 }
 ]

结果：
![image](https://user-images.githubusercontent.com/20007857/69216719-d4736e00-0ba7-11ea-80ac-b863fccaba2f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考jeecg的报表示例，看看有什么区别

**Comment by shanggushenlong** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:27
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 组件饼状图无效 (#736)




参考jeecg的报表示例，看看有什么区别

**Comment by shanggushenlong** [comment]
![image](https://user-images.githubusercontent.com/20007857/69218270-55803480-0bab-11ea-9b02-74d7d8429891.png)
![image](https://user-images.githubusercontent.com/20007857/69218293-60d36000-0bab-11ea-8a6a-b1e86907e7ac.png)
你好，确实无法正常显示

**Comment by shanggushenlong** [comment]
我使用的是文档提供的数据源
   { "item": "一月", "percent": 40 },
    { "item": "二月", "percent": 21 },
    { "item": "三月", "percent": 17 },
    { "item": "四月", "percent": 13 },
    { "item": "五月", "percent": 9 }

**Comment by shanggushenlong** [comment]
你好我刚刚试了，确实无法正常显示


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:27
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 组件饼状图无效 (#736)




Closed #736.

**Comment by shanggushenlong** [comment]
我已经在ieesue上截图说明了，麻烦你看看，谢谢
你好我刚刚试了，确实无法正常显示


------------------ 原始邮件 ------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午3:27
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"超群"<2538292294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 组件饼状图无效 (#736)




Closed #736.

**Comment by lokbun** [comment]
例子的值是percent，组件里是count。全部替换后可以正常显示
