### ISSUE TITLE
更改项目名称后，Online表单开发 提示找不到资源

### ISSUE THREAD

**Issue by aijuntao** [zhangdaiscott/jeecg-boot#737]
##### 版本号：
当前最新版本： 2.0.2（发布日期：20190708）

##### 问题描述：
更改项目名称后jeecg-boot修改为novat-boot，Online表单开发 提示找不到资源，打开 Online表单开发 功能后，报404错误，
除了这个功能外，其他功能都是正常的，不晓得是哪里没有修改完成导致的问题，忘大神帮助下，谢谢。

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/11253104/69316314-87f56480-0c73-11ea-9677-0f9da3e909de.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看常见问题贴

**Comment by aijuntao** [comment]
> 
> 
> 看常见问题贴

常见问题看了，没看到类似的，有两个关于在线表单开发的，虽然跟我的问题不一样，但也尝试处理了，没解决问题
