### ISSUE TITLE
为非管理员账号登录后访问自定义功能测试页面404

### ISSUE THREAD

**Issue by zhaolijin** [zhangdaiscott/jeecg-boot#738]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/12505757/69346086-28b44600-0cad-11ea-8a59-baeed1204d77.png)
admin下的按钮配置了隐藏没起作用

![image](https://user-images.githubusercontent.com/12505757/69345767-a6c41d00-0cac-11ea-83d5-eb5e4f453fd1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没授权，看常见问题贴

**Comment by zhaolijin** [comment]
大神我这里对应角色已经对菜单和按钮进行了授权，还有什么操作嚒

**Comment by zhaolijin** [comment]
![B3D22053-260A-44ac-89D1-301B464D5173](https://user-images.githubusercontent.com/12505757/69399535-78385780-0d29-11ea-9ac4-713560f1313a.png)

**Comment by zhaolijin** [comment]
配置的生成的页面就可以
