### ISSUE TITLE
想要【菜单栏搜索】新功能

### ISSUE THREAD

**Issue by iuok1001** [zhangdaiscott/jeecg-boot#740]
##### 问题描述：
想要【菜单栏搜索】新功能，如果菜单过多，需要有地方可以筛选
类似 http://www.zui.sexy/#control/button

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18457259/69496503-db82df00-0f0d-11ea-98a1-539133478cc0.png)

**Comment by zhangdaiscott** [comment]
你是说移动的时候？

**Comment by zhangdaiscott** [comment]
已经实现类似菜单搜索功能，下个版本会发布
