### ISSUE TITLE
Online表单功能搜索缺陷

### ISSUE THREAD

**Issue by eric-e-zhang** [zhangdaiscott/jeecg-boot#742]
##### 版本号：
v2.1.2 开源版

##### 问题描述：
自定义表单搜索项后，搜索字段不能按照关键字模糊查询。建议可以模糊查询。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg查询规则： 张*
在文字前后加*
