### ISSUE TITLE
能否 纯代码编写准备好了业务DDL sql的同时利用 `低代码开发` web功能 生成前后端代码?

### ISSUE THREAD

**Issue by johnwick67943532** [zhangdaiscott/jeecg-boot#7428]
我想生成30多张表,
但是使用后端web管理界面的手点表定义的 DDL效率较慢. 
我运行了建表的sql,但是web管理端没有显示有新的用sql生成的表:

![image](https://github.com/user-attachments/assets/40a304ff-7a2d-43cb-8a14-0d7a2dfb358d)

**Comment by zhangdaiscott** [comment]
导入数据库表
