### ISSUE TITLE
Online表单创建自定义表单权限的问题

### ISSUE THREAD

**Issue by eric-e-zhang** [zhangdaiscott/jeecg-boot#744]
##### 版本号：
v2.1.2 开源版

##### 问题描述：
现状描述：
通过Online表单创建在线表单后，将该表单配置到菜单项，然后创建新角色，授权该菜单项权限，将测试用户的角色设置为改角色。
.用户登录，可以看见菜单项，点击后到404页面.
.给管理员分配给权限，管理员通过菜单项点击可以正常查看。

预期结果：
普通用户分配菜单权限后，可以正常查看。

**Comment by zhangdaiscott** [comment]
online开发菜单目录下有几个auto开头的隐藏路由，需要给新的角色赋权

**Comment by eric-e-zhang** [comment]
好的，谢谢。

**Comment by eric-e-zhang** [comment]
你好，auto开头的隐藏路由给新的角色赋权后，还需要赋权父菜单权限，这样用户就会看到一个空的父菜单项，请问可以隐藏吗？谢谢。
