### ISSUE TITLE
前端部署后无法正常登录

### ISSUE THREAD

**Issue by demonskp** [zhangdaiscott/jeecg-boot#746]
##### 版本号：
2.1.1

##### 问题描述：
前端部署后admin账号无法登录，jeecg账号登录提示未设置部门并在控制台输出未找到dashboard路由。

产看路由配置发现确实dashboard命名路由在另一个对象(asyncRouterMap)中，我将另一个对象concat到constantRouterMap中，未找到dashboard路由报错消失了，但是依然未能正常登录。

网络中getUserPermissionByToken出错。

代码未修改过。

##### 截图&代码：

admin账号登陆
![image](https://user-images.githubusercontent.com/25999019/69768672-6a1c8800-11bc-11ea-8864-f60ea388fb66.png)

jeecg账号登陆
![image](https://user-images.githubusercontent.com/25999019/69768705-93d5af00-11bc-11ea-8214-5a3fdd054058.png)

网络出错：

```
http://localhost:3000/jeecg-boot/sys/permission/getUserPermissionByToken?_t=1574902388&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzQ5MDQyMTAsInVzZXJuYW1lIjoiamVlY2cifQ.ypq-cjE2UAqnyHXmCaKIjnxHhMzOIXos-RsGGBRAohk

{
  "success": false,
  "message": "查询失败:nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [org.apache.ibatis.reflection.ReflectionException: Error parsing property name 'lambda$8'.  Didn't start with 'is', 'get' or 'set'.]",
  "code": 500,
  "result": null,
  "timestamp": 1574902411278
}
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看常见问题贴

**Comment by youzhenqiang** [comment]
图表的啥时候开源啊发自我的华为手机-------- 原始邮件 --------主题：Re: [zhangdaiscott/jeecg-boot] 前端部署后无法正常登录 (#746)发件人：JEECG开源社区 收件人：zhangdaiscott/jeecg-boot 抄送：Subscribed 看常见问题贴
