### ISSUE TITLE
集成分库分表ShardingSphere 逻辑删除@TableLogic失效

### ISSUE THREAD

**Issue by hutianxi** [zhangdaiscott/jeecg-boot#7469]
##### 问题描述：
集成分库分表ShardingSphere 以后 逻辑删除失效
@TableLogic
 private Integer delFlag;

##### 错误截图：
![image](https://github.com/user-attachments/assets/111fa48b-1ccf-4dd2-b41b-78471a31b348)

![image](https://github.com/user-attachments/assets/47e6e20a-1695-47b6-9779-9b00c4f06def)
![image](https://github.com/user-attachments/assets/ef8907e4-6551-4747-a50d-9a62faba31a8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
框架问题，shardingsphere不通过Mybatis plus访问数据库，而是直接连的数据源访问数据库，故不生效是正常。
如果有该诉求，可以尝试在shardingsphere社区反馈。

**Comment by hutianxi** [comment]
> 框架问题，shardingsphere不通过Mybatis plus访问数据库，而是直接连的数据源访问数据库，故不生效是正常。 如果有该诉求，可以尝试在shardingsphere社区反馈。

ok  感谢
