### ISSUE TITLE
js增强使用‘that’关键字报错

### ISSUE THREAD

**Issue by F-T-Jen** [zhangdaiscott/jeecg-boot#750]
##### 版本号：
2.1.2

##### 问题描述：
online开发功能-js增强，在created方法中使用that正常，但是按钮js增强方法中使用that会报错

##### 截图&代码：
![图片1](https://user-images.githubusercontent.com/41729574/69780126-4f123e00-11e5-11ea-986a-0a4a2f8f2a19.png)
![图片2](https://user-images.githubusercontent.com/41729574/69780128-4f123e00-11e5-11ea-99f2-1ab9b14384cd.png)
![图片3](https://user-images.githubusercontent.com/41729574/69780132-4faad480-11e5-11ea-8e19-3021febbbe10.png)
![图片4](https://user-images.githubusercontent.com/41729574/69780134-4faad480-11e5-11ea-9459-27d82715a8ba.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by F-T-Jen** [comment]
已解决

**Comment by zhangdaiscott** [comment]
ok
应该是 
mounted(){
}

created(){
}
