### ISSUE TITLE
想用js增强实现条件查询，不成功

### ISSUE THREAD

**Issue by F-T-Jen** [zhangdaiscott/jeecg-boot#751]
##### 截图&代码：
![微信图片1](https://user-images.githubusercontent.com/41729574/69783848-56d6e000-11ef-11ea-8031-e598d15ad993.png)
![微信图片2](https://user-images.githubusercontent.com/41729574/69783849-56d6e000-11ef-11ea-88ad-ec8b0eabbf91.png)
![微信图片3](https://user-images.githubusercontent.com/41729574/69783850-576f7680-11ef-11ea-95eb-5fbb25b4ba7c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
console.log("--onlineList-查询条件-->",params)
console.log("--onlineList-列表数据",res)

看看这俩打印出来是什么

**Comment by F-T-Jen** [comment]
> console.log（“-onlineList-查询条件->”，params）
> console.log（“-onlineList-listdata”，res）
> 
> 看看这俩打印出来是什么

console打印出来的和network内打印出的参数是一样的
![微信图片_20191129084037](https://user-images.githubusercontent.com/41729574/69836442-c0083300-1283-11ea-804e-1640d0ab9b1e.png)

**Comment by zhangdaiscott** [comment]
打印出来的，这不delFlag=1吗

**Comment by F-T-Jen** [comment]
> 打印出来的，这不delFlag=1吗

是delFlag等于1，但是后台真正查询的时候没有这个where 条件（主题第三张图）

**Comment by zhangdaiscott** [comment]
那说明是后台问题，前端没问题

**Comment by F-T-Jen** [comment]
> 那说明是后台问题，前端没问题

后台依赖封装的代码是不是没把查询条件放进去
![6b385ca9176a9cdbf11c487ff40bbee6](https://user-images.githubusercontent.com/41729574/69839603-29437280-1293-11ea-87e9-ea9388ad568b.jpg)

**Comment by F-T-Jen** [comment]
问题已解决，queryParam.delFlag应该为queryParam.del_flag。online开发不会把驼峰命名的单词转为下划线

**Comment by zhangdaiscott** [comment]
你把del_flag配置成查询条件了吗

**Comment by F-T-Jen** [comment]
> 你把del_flag配置成查询条件了吗

是的

**Comment by F-T-Jen** [comment]
> 你把del_flag配置成查询条件了吗

实现的功能是去掉上面的查询条件，通过按钮来控制是否显示已经逻辑删除的数据。
![微信图片_20191129111715](https://user-images.githubusercontent.com/41729574/69841355-c903ff00-1299-11ea-8121-8399815260f4.png)
目前已经实现，但是按钮不是想要的类型，如果有switch类型按钮就好了，用户体验会更好。
