### ISSUE TITLE
war包部署方式，tomcat9  ，后台乱码

### ISSUE THREAD

**Issue by misureGitHub** [zhangdaiscott/jeecg-boot#752]
##### 版本号：
2.0

##### 问题描述：

war包部署方式，tomcat9  ，后台乱码
##### 截图&代码：

![image](https://user-images.githubusercontent.com/45928599/69784849-c0f08480-11f1-11ea-813d-c7025b80d590.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台项目编码是UTF-8吗

**Comment by misureGitHub** [comment]
是的，项目编码是utf-8，用jar包启动方式是ok 的

![image](https://user-images.githubusercontent.com/45928599/69839055-f8623e00-1290-11ea-8405-69813c869ebe.png)

**Comment by zhangdaiscott** [comment]
肯定是编码问题，确认下吧

**Comment by misureGitHub** [comment]
还要检查哪里的编码呢

**Comment by misureGitHub** [comment]
怎么排查呀，还没解决
