### ISSUE TITLE
resizable : true 时候 除了第一列可以 拖拽 ,其他列无法拖拽

### ISSUE THREAD

**Issue by clx20000410** [zhangdaiscott/jeecg-boot#7521]
##### 问题描述：
resizable : true 时候 除了第一列可以 拖拽 ,其他列无法拖拽

##### 错误截图：
![image](https://github.com/user-attachments/assets/0937e04b-0691-4613-91d7-dc9cfc92f6f4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新看看，老版无法处理

**Comment by wodewebqianduan** [comment]
> 升级到最新看看，老版无法处理

以错误治错误....直接app.vue里面初始化vex-table随便一个实例渲染v-show="false"隐藏，然后vex-table标签插槽columns随便写个比例v-for循环一个数组里面不存在的属性.replace('xp','')赋值给 :width ,会报错没有replace这个属性，然后这个时候basic-table组件全局渲染完成且完整，然后随便哪个之前写过的页面就都可以自由拖拽列宽了
