### ISSUE TITLE
Vue 一对多模板中存在错误<a-col>怎么会有gutter属性?用错了吧？

### ISSUE THREAD

**Issue by ren-liang** [zhangdaiscott/jeecg-boot#753]
##### 问题描述：
Vue 一对多模板中存在错误<a-col>怎么会有gutter属性?用错了吧？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8807004/69814840-09c72e00-1230-11ea-957a-3685af60632f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
的确写错，非常感谢

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
