### ISSUE TITLE
在线生成树形表单BUG

### ISSUE THREAD

**Issue by zhengzhi530** [zhangdaiscott/jeecg-boot#755]
##### 版本号：
 2.1.2(最新版)
##### 问题描述：
在线生成树形表单，测试的时候数据显示正常，生成的代码显示有问题。(刷新几次)树结构发生错乱。

##### 截图&代码：

![测试](https://user-images.githubusercontent.com/13163577/69839791-036a9d80-1294-11ea-8ece-d9994343e60d.jpg)
![正式代码生成](https://user-images.githubusercontent.com/13163577/69839797-082f5180-1294-11ea-824e-6500945f5b84.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ba370921** [comment]
我也遇到同样的问题了

**Comment by sjlei** [comment]
问题已修复，将在下个版本同步

**Comment by zhangdaiscott** [comment]
你是不是开启默认模糊查询了？
