### ISSUE TITLE
jeecg-boot-parent 2.1.1 下载不到

### ISSUE THREAD

**Issue by zn123** [zhangdaiscott/jeecg-boot#759]
##### 版本号：
2.1.1

##### 问题描述：
	<parent>
		<groupId>org.jeecgframework.boot</groupId>
		<artifactId>jeecg-boot-parent</artifactId>
		<version>2.1.1</version>
	</parent>
包下载不到

##### 截图&代码：

		<repository>
			<id>jeecg</id>
			<name>jeecg Repository</name>
			<url>http://maven.jeecg.org/nexus/content/repositories/jeecg</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不需要下，父目录的pom就是这个

![image](https://user-images.githubusercontent.com/3162115/69850896-586dda00-12bb-11ea-80c0-2ea4ad526788.png)

**Comment by zn123** [comment]
为啥 我用maven 命令行 package 的时候找不到；

**Comment by zhangdaiscott** [comment]
先执行install命令
