### ISSUE TITLE
路由地址带参数，首次进入页面获取不到参数，刷新页面404

### ISSUE THREAD

**Issue by xxrt** [zhangdaiscott/jeecg-boot#76]
路由地址带参数，例如：/user?type=teacher
1、从菜单点击进入页面时$route.query没有type
2、F5刷新页面，直接到404

**Comment by xxrt** [comment]
从菜单点击进入页面时$route.path为/user?type=teacher，应该是/user

**Comment by zhangdaiscott** [comment]
试试这个方案
https://github.com/zhangdaiscott/jeecg-boot/issues/39

**Comment by xxrt** [comment]
> 试试这个方案
> #39

昨晚试过了，无效

**Comment by zhangdaiscott** [comment]
不是一个问题？

**Comment by xxrt** [comment]
> 不是一个问题？

从菜单点击进入页面时$route.path为/user?type=teacher，应该是/user

**Comment by xxrt** [comment]
> 不是一个问题？

"从菜单点击进入页面时$route.path为/user?type=teacher，应该是/user"
从这个现象来看，应该是初始化路由的时候就有问题了

**Comment by zhangdaiscott** [comment]
菜单配置截图看下

或者参考
http://jeecg-boot.mydoc.io/
带参数路由配置

**Comment by xxrt** [comment]
> 菜单配置截图看下
> 
> 或者参考
> http://jeecg-boot.mydoc.io/
> 带参数路由配置

![image](https://user-images.githubusercontent.com/36843313/56935898-b9b3ac00-6b26-11e9-9ff8-11a92fae2290.png)

**Comment by xxrt** [comment]
> 菜单配置截图看下
> 
> 或者参考
> http://jeecg-boot.mydoc.io/
> 带参数路由配置

文档里那个配置没看懂，是要配置2个菜单的意思？

**Comment by zhangdaiscott** [comment]
已经发布最新版，可以更新看看

**Comment by dut3062796s** [comment]
麻烦问下,楼主你的问题处理了么.我也是同样是问题。

**Comment by huanlirui** [comment]
楼主，这种问题怎么复现？  我也是偶尔出现，刷新后404，我也怀疑是路由带参数的问题。怎么解决的？
