### ISSUE TITLE
在线代码生成不支持多列模板

### ISSUE THREAD

**Issue by dongzhanyun** [zhangdaiscott/jeecg-boot#760]
##### 版本号：
2.1.1

##### 问题描述：

在线代码生成选择多列，生成的代码，添加功能还是显示一列
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你理解的不对，模板是online在线用的，不是生成代码用的

**Comment by dongzhanyun** [comment]
明白，我再多试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2019年12月2日(星期一) 中午11:13
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "董占云"<872950541@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 在线代码生成不支持多列模板 (#760)




你理解的不对，模板是online在线用的，不是生成代码用的
