### ISSUE TITLE
关于jeecg-boot商用的问题

### ISSUE THREAD

**Issue by lanxianghua** [zhangdaiscott/jeecg-boot#761]
##### 版本号：
2.1.2
##### 问题描述：
您好，请问能否使用jeecg-boot开源项目作为底层，然后二次开发成一个论坛产品，然后出售给别人？请问这种允许吗？
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看开源项目协议
