### ISSUE TITLE
为什么添加用户后, sys_user表中的org_code是空的?

### ISSUE THREAD

**Issue by Rikhard-Dong** [zhangdaiscott/jeecg-boot#762]
##### 问题描述：
为什么添加用户后, sys_user表中的org_code是空的?

##### 截图&代码：

![微信图片_20191130105748](https://user-images.githubusercontent.com/22675968/69894833-44c87f00-1360-11ea-8128-e9c0bbdb43ef.png)
![微信图片_20191130105843](https://user-images.githubusercontent.com/22675968/69894847-6a558880-1360-11ea-95f2-cbf92c1190ab.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
选择部门登录了吗
