### ISSUE TITLE
token个别需求

### ISSUE THREAD

**Issue by tuyula** [zhangdaiscott/jeecg-boot#764]
##### 版本号：
latest

##### 问题描述：
我们公司想把系统用钉钉作为出口, 由于token时间较短, 半小时就会过期, 能否再官方文档备注添加token时长的方法, 谢谢

##### 截图&代码：

![dingdingBookError](https://user-images.githubusercontent.com/32473341/69912189-a7a13f80-1460-11ea-970a-67775c88b2f2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
org.jeecg.common.system.util.JwtUtil#EXPIRE_TIME
