### ISSUE TITLE
ORACLE版本如何在线代码生成

### ISSUE THREAD

**Issue by yfq900108** [zhangdaiscott/jeecg-boot#765]
##### 版本号：
2.1.2

##### 问题描述：
ORACLE版本如何在线代码生成

##### 截图&代码：

我部署了Oracle的版本，发现没有在西安代码生成菜单
#

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yfq900108** [comment]
![image](https://user-images.githubusercontent.com/11631643/69914054-aa109300-147a-11ea-8efb-11d36669f96a.png)

**Comment by zhangdaiscott** [comment]
用admin用户，其他用户没分配权限
