### ISSUE TITLE
希望能实现前端带token下载文件

### ISSUE THREAD

**Issue by badboyc** [zhangdaiscott/jeecg-boot#766]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你用的什么版本，最新版已经是带token方式

**Comment by badboyc** [comment]
我用的上一版本，不好意思我看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2019年12月2日(星期一) 上午10:01
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "1510405834"<1510405834@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 希望能实现前端带token下载文件 (#766)




你用的什么版本，最新版已经是带token方式

**Comment by badboyc** [comment]
我看了下最新版本的，后端shiroconfig还是把文件下载权限放开了不带token,前端我没找到在哪实现了带token下载文件（不是导出excel文件）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2019年12月2日(星期一) 上午10:01
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "1510405834"<1510405834@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 希望能实现前端带token下载文件 (#766)




你用的什么版本，最新版已经是带token方式
