### ISSUE TITLE
MyRealm 中依赖 提前初始化造成 获取对象为非代理对象，造成事物注解失效

### ISSUE THREAD

**Issue by zhang0001** [zhangdaiscott/jeecg-boot#77]
ShiroFilterFactoryBean 现了FactoryBean接口，所以它会提前被初始化。他依赖的都会提前，造成早于AnnotationAwareAspectJAutoProxyCreator 注册到 FactoryBean中，造成之前初始化的Bean 都是不是代理类。MyRealm 中的依赖 ISysPermissionService ISysUserService StringRedisTemplate RedisUtil，而ShiroFilterFactoryBean 依赖SecurityManager ，SecurityManager 依赖 MyRealm ，MyRealm 中的依赖会提前初始化，获取的是非代理对象，无法使用    @Transactional @Cacheable 等注解，可以添加@Lazy 延迟初始化。

**Comment by zhang0001** [comment]
StringRedisTemplate， RedisUtil 也是。ShiroFilterFactoryBean 现了FactoryBean接口，所以它会提前被初始化。他依赖的都会提前，造成早于AnnotationAwareAspectJAutoProxyCreator 注册到 FactoryBean中，造成之前初始化的Bean 都是不是代理类。

**Comment by zhangdaiscott** [comment]
3Q

**Comment by zhangdaiscott** [comment]
public class MyRealm extends AuthorizingRealm {

	@Autowired
	@Lazy
	private ISysUserService sysUserService;
	@Autowired
	@Lazy
	private RedisUtil redisUtil;

看看是否正确

**Comment by zhang0001** [comment]
是的

**Comment by zhangdaiscott** [comment]
ok 下个版本发布
