### ISSUE TITLE
主附表online生成代码后新增保存出错！

### ISSUE THREAD

**Issue by zhang91yun** [zhangdaiscott/jeecg-boot#770]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/49631698/69947115-f36aec00-1527-11ea-8200-d9350fcc4596.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看不出来，你自己跟下代码看看为什么

**Comment by zhangdaiscott** [comment]
没有新反馈的话，此问题明天关闭了
