### ISSUE TITLE
Online表单自定义表单的导入问题

### ISSUE THREAD

**Issue by eric-e-zhang** [zhangdaiscott/jeecg-boot#772]
##### 版本号：
v2.1.2

##### 问题描述：
Online表单自定义表单做数据导入时，是否可以指定导入按照条件更新，目前是无论是否重复，都会做追加操作。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，收录

**Comment by zhangdaiscott** [comment]
可以通过JAVA增强来自定义规则

**Comment by eric-e-zhang** [comment]
> 可以通过JAVA增强来自定义规则

JAVA增强目前只有新增、编辑、删除按钮，好像没有针对导入按钮的配置。

**Comment by zhangdaiscott** [comment]
我们扩展下

**Comment by zhangdaiscott** [comment]
已经实现了  导出和导入的增强拓展，下个版本发布
