### ISSUE TITLE
登录一直没跳转主页，getUserPermissionByToken接口报错

### ISSUE THREAD

**Issue by lifuchao** [zhangdaiscott/jeecg-boot#774]
##### 版本号：
2.1.1

##### 问题描述：
登录一直没跳转主页，个人分析应该是sys_permission表里的hidden字段是MySQL关键字。
我用的是腾讯的TDSQL，select version()查了的【5.7.17-11-V1.0R013D004-20190710-1030-log】
如果确实是这个问题，不知能否改一下？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15504114/70035671-4ad38f80-15ee-11ea-891e-f763290989b9.png)

![image](https://user-images.githubusercontent.com/15504114/70035888-ad2c9000-15ee-11ea-8206-c3f4eb6cf6ec.png)

图片看不了的话，这是我拷的后台sql在navicat里执行的报错：
[SQL]SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,
description,create_by,del_flag,rule_flag,hidden,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission

[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'hidden,create_time,update_by,update_time,status,always_show,internal_or_external' at line 2

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你什么数据库 版本

**Comment by lifuchao** [comment]
> 你什么数据库 版本

select version()查了的【5.7.17-11-V1.0R013D004-20190710-1030-log】,估计是基于MySQL5.7.17改的。如果不动数据库也行，我改了SysPermissionController里代码就OK了。或者有其他更好的办法，望告知。

/*
			LambdaQueryWrapper<SysPermission> query = new LambdaQueryWrapper<SysPermission>();
			query.eq(SysPermission::getDelFlag, CommonConstant.DEL_FLAG_0);
			query.eq(SysPermission::getMenuType, CommonConstant.MENU_TYPE_2);*/

			QueryWrapper<SysPermission> query = new QueryWrapper<SysPermission>();
			query.eq("del_flag", CommonConstant.DEL_FLAG_0);
			query.eq("menu_type", CommonConstant.MENU_TYPE_2);
			query.select("id","parent_id","name","perms","perms_type","icon","component","component_name","url","redirect","sort_no","menu_type","is_leaf AS leaf","is_route AS route","keep_alive","description","create_by","del_flag","rule_flag","`hidden`","create_time","update_by","update_time","status","always_show","internal_or_external");

**Comment by zhangdaiscott** [comment]
不应该啊，我们也是5.7为什么没提示这个问题
