### ISSUE TITLE
关于jeecg对接CAS, 服务端退出失效的问题

### ISSUE THREAD

**Issue by WANGJUEYA** [zhangdaiscott/jeecg-boot#776]
##### 版本号：

2.1.2

##### 问题描述：

jeecg 对接 CAS, 当服务器退出登录后, jeecg仍然能够正常访问

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
应该是的对接的有问题吧，cas这块我们测试过

**Comment by WANGJUEYA** [comment]
那请问下, 当cas服务端登出后, jeecgboot是在何处(前端还是后端)进行响应并移除token的呢? 谢谢

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273851

**Comment by lifuchao** [comment]
> ##### 版本号：
> 2.1.2
> 
> ##### 问题描述：
> jeecg 对接 CAS, 当服务器退出登录后, jeecg仍然能够正常访问
> 
> ##### 截图&代码：
> 友情提示： 未按格式要求发帖，会直接删掉。



你好，能问下你的cas是什么版本吗？你的单点登录已经集成好了吧。
我用的jeecg2.1.3+cas5.2.6，但是后端项目只要引入cas的依赖就会后端启动报错，麻烦问下遇到过吗？多谢了

<dependency>
			<groupId>org.apereo.cas</groupId>
			<artifactId>cas-server-support-rest</artifactId>
			<version>5.2.6</version>
		</dependency>

报错截图：
![image](https://user-images.githubusercontent.com/15504114/74718339-fcd53c00-526c-11ea-90cf-dd062902bad9.png)

**Comment by beAnger** [comment]
请问最后是怎么解决的？是要在cas那边配置logout_url吗
