### ISSUE TITLE
tomcat部署war报404 必看里说注掉spring内置tomcat的地方已经注掉了 还是404 怎么办

### ISSUE THREAD

**Issue by cruelchen** [zhangdaiscott/jeecg-boot#777]
04/Dec/2019:10:54:23 +0800] "GET /jeecg-boot/ HTTP/1.1" 404 694
##### 问题描述：
tomcat部署war报404 必看里说注掉spring内置tomcat的地方已经注掉了 还是404 怎么办

##### 截图&代码：

![b2a71d51942e7eaaf8db6a2760c3991f](https://user-images.githubusercontent.com/1943876/70108862-46a68100-1685-11ea-8f67-bbed07b4ea79.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273923
