### ISSUE TITLE
master版本缺少如下功能

### ISSUE THREAD

**Issue by CreateJava** [zhangdaiscott/jeecg-boot#778]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看readme的功能清单介绍

**Comment by CreateJava** [comment]
是这里么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午3:15
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"闫前刚"<1486488968@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] master版本缺少如下功能 (#778)




看readme的功能清单介绍
