### ISSUE TITLE
用户选择器，选择部门后，没有分页功能，切换页大小又会查询所有用户

### ISSUE THREAD

**Issue by aaronyin** [zhangdaiscott/jeecg-boot#779]
##### 问题描述：
用户选择器，选择部门后，没有分页功能，切换页大小又会查询所有用户

##### 截图&代码：
![123](https://user-images.githubusercontent.com/5564707/70121438-8a12e680-16a9-11ea-8bdd-35ea269acbd0.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yangzhiwei666** [comment]
![image](https://user-images.githubusercontent.com/32032126/70598452-da4bf480-1c25-11ea-885f-70f19d599454.png)
如图是JSelectUserByDepModal.vue中的部分代码，this.dataSource因为通过分页查询出来的，并没有获取全部用户，导致当用户量超过10个时，在用户选择器初始化的时候，名字无法显示。
![image](https://user-images.githubusercontent.com/32032126/70598693-5e05e100-1c26-11ea-8441-b859754ff06b.png)

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
