### ISSUE TITLE
以WAR方式部署生产环境到Window 10 tomcat+nginx,部分窗口(人员列表）中文出现乱码

### ISSUE THREAD

**Issue by gicp** [zhangdaiscott/jeecg-boot#78]
以WAR方式部署生产环境到Window 10 tomcat+nginx,部分窗口(人员列表）中文出现乱码

**Comment by zhangdaiscott** [comment]
发截图

**Comment by gicp** [comment]
![TIM图片20190428181526](https://user-images.githubusercontent.com/31814666/56862822-916e6500-69e1-11e9-8ac4-4c3c07aab85f.png)
![TIM图片20190428181535](https://user-images.githubusercontent.com/31814666/56862823-916e6500-69e1-11e9-92a1-d83a262e2aab.png)

**Comment by zhangdaiscott** [comment]
这是演示页面，没读数据库，看看你本地的环境
