### ISSUE TITLE
修改前端访问前缀和后台context-path，代码生成器模块的功能接口全部报404

### ISSUE THREAD

**Issue by souljessi** [zhangdaiscott/jeecg-boot#782]
##### 问题描述：统一修改了以下文件的访问前缀(前端的baseURL和后端的context-path):
src/main/resources/application-dev.yml   
ant-design-jeecg-vue/src/utils/request.js
ant-design-jeecg-vue/public/index.html
ant-design-jeecg-vue/vue.config.js
于是代码生成器模块功能接口全部报404，接口请求还是"jeecg-boot"打头的前缀，追查前端依赖的源码，貌似写死了BaseURL，除了不改动源码的基础上，有没有其他办法可以解决这个问题，官方有没有更好的方法修正这个问题呢？

##### 截图&代码：//@jeecg/antd-online/dist/OnlineForm.umd.min.js
   源码片段：var Ne=c.a.create({baseURL:"/jeecg-boot",timeout:9e3})

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44
