### ISSUE TITLE
报表功能：字段href设置之后，点击字段不能跳转

### ISSUE THREAD

**Issue by wangsheng1118** [zhangdaiscott/jeecg-boot#783]
##### 截图&代码：
![ceb8dfd48222b2c97d3354a14ce1490](https://user-images.githubusercontent.com/54489179/70135599-55148d00-16c5-11ea-80d6-3faec6770a16.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已在规划中

**Comment by zhangdaiscott** [comment]
已经开发完成，下个版本发布
