### ISSUE TITLE
Online表单部门选择的使用问题

### ISSUE THREAD

**Issue by eric-e-zhang** [zhangdaiscott/jeecg-boot#785]
##### 版本号：
V2.1.2

##### 问题描述：
使用Online表单功能创建表单，其中一个字段使用部门选择器，将该字段设置为可以查询，在表单列表页面查询部门时，不能出现部门选择器，只能手动输入部门全称才可以查询。
预期希望可以按照部门选择部门后进行查询，而不用手动输入部门名称。

**Comment by zhangdaiscott** [comment]
online在线功测试吗

**Comment by eric-e-zhang** [comment]
> online在线功测试吗

功能测试，或者将在线表单设置为菜单项后，都有同样问题。

**Comment by zhangdaiscott** [comment]
好的，收录

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
