### ISSUE TITLE
EL 表达式错误

### ISSUE THREAD

**Issue by zhang0001** [zhangdaiscott/jeecg-boot#79]
https://github.com/zhangdaiscott/jeecg-boot/blob/d8e70b7f900961a63eaadc909a493768a5bf357d/jeecg-boot/src/main/java/org/jeecg/modules/system/service/impl/SysPermissionServiceImpl.java#L119

@CacheEvict(value = "permission",allEntries=true,condition="#sysPermission.menuType=2")
应该是 condition="#sysPermission.menuType==2"  还有别的地方

**Comment by zhangdaiscott** [comment]
好的，3Q

**Comment by zhangdaiscott** [comment]
已改，下版本发布
