### ISSUE TITLE
我的部门功能 页面更换了默认项，报Error in v-on handler: "TypeError: Cannot read property 'onClearSelected' of undefined"

### ISSUE THREAD

**Issue by yfq900108** [zhangdaiscott/jeecg-boot#792]
##### 版本号：
V2.1.2

##### 问题描述：
``我的部门功能页面中，更换了默认展开的一对多的页面， 点击左侧树页面，只能加载第一个页面的内容，第二个页面内容默认无法加载，查看输出，js页面出现报错：Error in v-on handler: "TypeError: Cannot read property 'onClearSelected' of undefined"

##### 截图&代码：
代码如下：
![image](https://user-images.githubusercontent.com/11631643/70418262-10f70300-1a9e-11ea-9d73-e39befd34660.png)
功能操作如下：
![image](https://user-images.githubusercontent.com/11631643/70418503-7b0fa800-1a9e-11ea-9c6d-ab53310485ce.png)

报错信息：
![image](https://user-images.githubusercontent.com/11631643/70418517-85ca3d00-1a9e-11ea-848f-56f422a4df25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yfq900108** [comment]
有没有大神给分析下原因呢

**Comment by zhangdaiscott** [comment]
自己写的功能，就不要发了，自己多研究。
我们没有你的代码，没办法帮你判断
