### ISSUE TITLE
编辑主表信息显示不全，需要第二甚至第三次点开才会完全显示

### ISSUE THREAD

**Issue by Possition** [zhangdaiscott/jeecg-boot#793]
##### 截图&代码：
<img width="1296" alt="WX20191209-191356@2x" src="https://user-images.githubusercontent.com/20549981/70431676-81128280-1ab8-11ea-9a23-50995bb662b0.png">

出库方式，第一次点开可能不显示，需要多次点开才会显示

<img width="1306" alt="WX20191209-191434@2x" src="https://user-images.githubusercontent.com/20549981/70431712-97204300-1ab8-11ea-92c8-e440ae692502.png">

<img width="1589" alt="WX20191209-191620@2x" src="https://user-images.githubusercontent.com/20549981/70431726-9daeba80-1ab8-11ea-8687-fafd7d7fb284.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你自己写的功能？ 我这边怎么重现

**Comment by zhangdaiscott** [comment]
应该是因为字典加载的慢问题，可以换个写法
