### ISSUE TITLE
首页 与 其他页互相切换没有刷新页面，组件的keepAli..参数是false

### ISSUE THREAD

**Issue by happy-panda** [zhangdaiscott/jeecg-boot#794]
##### 版本号：
2.1.2

##### 问题描述：
首页 与 其他页互相切换没有刷新页面，组件的keepAli..参数是false；
其他页面之间相互 切换没问题，会重新刷新

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26876130/70491256-c2984180-1b3b-11ea-80a9-8456221a64c1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by happy-panda** [comment]
截图发不上去，我所说的就是 TabLayout.vue 中首页与其他页切换，页面数据没重新加载，没重新请求后台。但是其他页面之间相互切换没有问题。

**Comment by zhangdaiscott** [comment]
那是因为首页菜单配置设置了路由缓存，不需要的话，可以自己改造下
org.jeecg.modules.system.entity.SysPermission
![image](https://user-images.githubusercontent.com/3162115/70777843-c2a67480-1dbb-11ea-9ccb-1c340ef7c4c9.png)

**Comment by huanlirui** [comment]
这个问题怎么解决？

**Comment by happy-panda** [comment]
> 这个问题怎么解决？

我按照作者回复处理了，但是并没有效果， @zhangdaiscott

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/819

**Comment by huanlirui** [comment]
> > 这个问题怎么解决？
> 
> 我按照作者回复处理了，但是并没有效果， @zhangdaiscott

参考#814哈。作者解决了。
