### ISSUE TITLE
建议去除上传文件,有色情图片

### ISSUE THREAD

**Issue by liwang123** [zhangdaiscott/jeecg-boot#798]
##### 问题描述：
有色情问题图片

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26794395/70698278-194f7800-1d02-11ea-947f-d7f4efd7384e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
演示系统吗

**Comment by liwang123** [comment]
是的

**Comment by zhangdaiscott** [comment]
好的
