### ISSUE TITLE
点击菜单项跳转问题

### ISSUE THREAD

**Issue by MikuBlog** [zhangdaiscott/jeecg-boot#800]
##### 版本号：

线上版本

##### 问题描述：

不知道是不是有意而为之，点击在线文档等内嵌<iframe/>网页菜单项会另起标签页。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/43233731/70718138-a1497800-1d2a-11ea-82c9-553258166000.png)

**Comment by zhangdaiscott** [comment]
截图看

**Comment by MikuBlog** [comment]
github的图访问有点慢，我直接口述了吧：点击“在线文档”菜单项会另外打开新的标签页并加载在线文档，同时，系统里也会内嵌“在线文档”。我个人感觉是没有必要打开新的标签页的~

**Comment by zhangdaiscott** [comment]
请截图，说明是那个功能
演示系统没有在线文档功能，你指的是OA模块下的，文档管理吗

**Comment by MikuBlog** [comment]
菜单项：系统监控->在线文档、SQL监控。
![image](https://user-images.githubusercontent.com/43233731/70782937-2a13f280-1dc3-11ea-98c7-29b8f0c28cbd.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/70790901-f049e880-1dd0-11ea-8354-eb738c0af443.png)
