### ISSUE TITLE
切换菜单不刷新问题

### ISSUE THREAD

**Issue by shangxinxiaojian** [zhangdaiscott/jeecg-boot#803]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
描述太简单

**Comment by shangxinxiaojian** [comment]
我在菜单管理设置路由不缓存，但是点击切换菜单，不能实时刷新数据，切换菜单只调用一次后台数据接口

**Comment by zhangdaiscott** [comment]
目前菜单加载我们改成的效果是，只有点击菜单就会重新加载，除非你这边那个页面加了路由缓存

**Comment by shangxinxiaojian** [comment]
我在菜单管理里面看了的 路由缓存我关了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午2:35
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "伤"<1298321038@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 切换菜单不刷新问题 (#803)




目前菜单加载我们改成的效果是，只有点击菜单就会重新加载，除非你这边那个页面加了路由缓存

**Comment by zhangdaiscott** [comment]
你好好确认下吧
