### ISSUE TITLE
缩放bug

### ISSUE THREAD

**Issue by aleiliuwei** [zhangdaiscott/jeecg-boot#804]
##### 问题描述：
当打开多个tab页，如果页面进行缩放，tab页会自动关闭。当打开弹出model，比如新增，缩放会自动关闭

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23118292/70764335-43507b00-1d92-11ea-8238-deac00ca0a5d.png)
![image](https://user-images.githubusercontent.com/23118292/70764381-667b2a80-1d92-11ea-80ce-76ef6344abf2.png)
![image](https://user-images.githubusercontent.com/23118292/70764403-7bf05480-1d92-11ea-97af-199ae521b04d.png)

![image](https://user-images.githubusercontent.com/23118292/70764475-aa6e2f80-1d92-11ea-8f94-ca082b429cbc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是这样的，屏幕小的时候会自动切换到单tab模式，自适应移动模式

**Comment by aleiliuwei** [comment]
哦，我目前只用在pc端，能告诉下需要注释下哪部分代码吗，可以解决这个问题

**Comment by sjlei** [comment]
修改 `src/App.vue`，注释掉红框内的代码即可

![image](https://user-images.githubusercontent.com/34293221/70789781-a52ed600-1dce-11ea-972a-6ee5595b0099.png)

**Comment by codergcy** [comment]
改变浏览器窗口大小，页面重新加载 注释红色框内代码就行吗，会出现其他问题吗
