### ISSUE TITLE
jeecg-boot master导入错误

### ISSUE THREAD

**Issue by AmramXing** [zhangdaiscott/jeecg-boot#805]
##### 版本号：
jeecg-boot master

##### 问题描述：
用Maven导入项目的时候，报告如下图缺少autopoi-web-1.0.4.jar。手动从http://maven.jeecg.org/nexus/content/repositories/jeecg/org/jeecgframework/autopoi-web/1.0.4/下载jar到本地Maven仓库的时候，又报告另外的错误：
Failed to read artifact descriptor for org.jeecgframework:autopoi-web:jar:1.0.4
Missing artifact antlr:antlr:jar:2.7.7
Missing artifact ch.qos.logback:logback-classic:jar:1.2.3
Missing artifact ch.qos.logback:logback-core:jar:1.2.3
...

##### 截图&代码：
不能发送截图，拖拽文件也没用。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273965
