### ISSUE TITLE
Dockerfile运行问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#806]
##### 问题描述：
参照自带的Dockerfile，启动项目，总是报：Unable to access jarfile XX.jar

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你怎么打的包啊，你先手工在本地执行下这个JAR，看看是不是打的JAR有问题

**Comment by Nicky213Zhang** [comment]
> 你怎么打的包啊，你先手工在本地执行下这个JAR，看看是不是打的JAR有问题

已解决，谢谢大佬！docker还是小菜鸟一枚，目前已运行。
