### ISSUE TITLE
员工登记表样式出错

### ISSUE THREAD

**Issue by MikuBlog** [zhangdaiscott/jeecg-boot#808]
##### 版本号：

线上版本

##### 问题描述：

OA办公--->员工登记表，样式出错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/43233731/70786189-0baff600-1dc7-11ea-97d2-da912e287a70.png)

**Comment by zhangdaiscott** [comment]
自己写的功能？

**Comment by zhangdaiscott** [comment]
你是什么浏览器

**Comment by MikuBlog** [comment]
chrome

**Comment by MikuBlog** [comment]
@zhangdaiscott 不知道你那边是否有问题，如果chrome没问题的话，有可能是我插件样式的影响导致的~

**Comment by zhangdaiscott** [comment]
我这边是谷歌浏览器，没有问题
