### ISSUE TITLE
qurtz问题

### ISSUE THREAD

**Issue by Ray-Sir-Like** [zhangdaiscott/jeecg-boot#81]
1. 从前台新建一个定时任务

2. 设置为启动状态,
3. 这个时候如果重启后台, 重启后的后台 不会自动执行处于启动状态的任务

**Comment by zhangdaiscott** [comment]
已经发现这个问题，下个版本发布

**Comment by Ray-Sir-Like** [comment]
2.0.1里面,依然存在这个问题,
