### ISSUE TITLE
在线表单开发是否扩展支持point、line、ploygn等空间数据类型

### ISSUE THREAD

**Issue by 15152763704** [zhangdaiscott/jeecg-boot#810]
##### 版本号：
下载的最新版本

##### 问题描述：
在线表单开发是否扩展支持point、line、ploygn等空间数据类型

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58929241/70954704-3d67dc00-20a9-11ea-93b6-176c7a068d33.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
默认不支持，需要支持，得修改底层代码

**Comment by 15152763704** [comment]
这边有建议如何修改吗？或者我自己想要实现的话可以从修改哪里的代码作为入口

**Comment by zhangdaiscott** [comment]
这块的源码还未开放，你这边无法自己进行改造

**Comment by 15152763704** [comment]
根据我现在提的需求，你们内部会考虑做这方面的 升级吗？如果有升级可能更新时间是多久？
