### ISSUE TITLE
树形和一对多组合场景下自动生成的代码有问题（貌似只支持一对多功能，没有树功能）

### ISSUE THREAD

**Issue by heidongzai** [zhangdaiscott/jeecg-boot#812]
##### 版本号：

2.1.1
##### 问题描述：
树形和一对多组合场景下自动生成的代码有问题（貌似只支持一对多功能，没有树功能）

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前只单表支持树

**Comment by heidongzai** [comment]
预计在哪个版本一对多支持树

**Comment by chzhm159** [comment]
能否给一个手动编码实现 一对多的树形结构的例子
