### ISSUE TITLE
如何取消首页的缓存?

### ISSUE THREAD

**Issue by huanlirui** [zhangdaiscott/jeecg-boot#814]
##### 问题描述：
如何取消首页缓存？切换页签时能重新刷新首页。更新数据。

**Comment by huanlirui** [comment]
首页与其他页签切换时，无法刷新更新数据！！
其他页签之间切换没有这个问题。
如何解决？

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/71152243-d39a2e80-2270-11ea-80bb-7a93b652818e.png)
org.jeecg.modules.system.entity.SysPermission

**Comment by zhangdaiscott** [comment]
修改src/components/layouts/TabLayout.vue
![image](https://user-images.githubusercontent.com/3162115/71239598-e7fa2c00-2341-11ea-93a8-340ff0cdec8f.png)

改成
![image](https://user-images.githubusercontent.com/3162115/71239646-08c28180-2342-11ea-9879-da98cc0b2c78.png)

**Comment by Nicky213Zhang** [comment]
修改之后是可以刷新一级菜单了，包括首页。但是这一段原本加上是为了右击刷新当前tab的，这样改的话，刷新就失效了。主要是想知道，二级菜单为啥不改也是可以刷新的呢，按道理二级也是进了<keep-alive v-if="multipage">
          <router-view v-if="reloadFlag"/>
</keep-alive>

**Comment by huanlirui** [comment]
👍  给力哦。解决我的问题了。感谢大佬

**Comment by happy-panda** [comment]
> 修改之后是可以刷新一级菜单了，包括首页。但是这一段原本加上是为了右击刷新当前tab的，这样改的话，刷新就失效了。主要是想知道，二级菜单为啥不改也是可以刷新的呢，按道理二级也是进了

这样即可 @Nicky213Zhang 
![image](https://user-images.githubusercontent.com/26876130/71243988-7ffd1300-234c-11ea-980e-32e5d9d7ff60.png)
同时感谢通知，棒棒哒 @huanlirui
