### ISSUE TITLE
1.系统是否完美兼容ie9+，发现代码在chrome上正常，在ie9下运行无效果  2.

### ISSUE THREAD

**Issue by 15014147869** [zhangdaiscott/jeecg-boot#815]
##### 问题描述：
1.代码在chrome正常，在ie 11上双向绑定无效
2.代码console报错
Warning: `getFieldDecorator` will override `value`, so please don't set `value and v-model` directly and use `setFieldsValue` to set it.，
这个问题如何处理

##### 截图&代码：
// 如果没有可用的报案人表单，则自动添加一行
              this.model_.lgjzBarList.push({
                // barsf:"受害人",
                idcard:resultObj.resultContent.certNumber,
                barxm : resultObj.resultContent.partyName,
                address: resultObj.resultContent.certOrg
              });
            console.log(this.model_);
            this.$forceUpdate(); // 此处在1e11无效

**Comment by zhangdaiscott** [comment]
低版本不支持，目支持IE11+
