### ISSUE TITLE
修改后台启动项目名后从数据库导入表单功能失效

### ISSUE THREAD

**Issue by luokl2019** [zhangdaiscott/jeecg-boot#818]
##### 版本号：
JeecgBoot2.1.2

##### 问题描述：
当修改完后台启动项目名，并且在前端项目中修改了所有的请求url后，
使用从数据库导入表单功能时失效，无法从数据库中查询到表单数据。
错误为代码404，几经寻找，发现原因是因为JeecgBoot内置组件antd-online中把请求路径中的项目名写死了，导致无法访问到后台接口。

##### 截图&代码：
案例如下：
![image](https://user-images.githubusercontent.com/40263163/71150272-068df380-226c-11ea-9def-80b46ce02087.png)

错误代码如下：
![image](https://user-images.githubusercontent.com/40263163/71150314-27eedf80-226c-11ea-9403-44d196914342.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by luokl2019** [comment]
烦请修复一下吧！谢谢

**Comment by zhangdaiscott** [comment]
参考常见问题贴，手工修改项目名字
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
44

**Comment by luokl2019** [comment]
@zhangdaiscott 都改了，还是没效果，项目能跑，但是从数据库导入表单的功能失效！
