### ISSUE TITLE
一级路由菜单不刷新问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-boot#819]
##### 版本号：
2.1.2

##### 问题描述：
看了好几个issue都提到这个问题，正巧这边也遇到了，就整理一下，咨询下作者。
如果：设置的路由菜单为二级菜单，并且不缓存路由，那么相互切换是可以刷新页面数据的；反之：设置的路由菜单为一级菜单，且不缓存路由，切换菜单时一级菜单是不会刷新数据的。log打印也可以看出来keepalive为false。
不知问题出于哪里，可能是我对前端了解的还不够，还向作者请教。
##### 截图&代码：
![1](https://user-images.githubusercontent.com/25654842/71151819-aa2cd300-226f-11ea-8bf6-964809e836d5.png)
![2](https://user-images.githubusercontent.com/25654842/71151829-b022b400-226f-11ea-98c1-32628b9737de.png)
![3](https://user-images.githubusercontent.com/25654842/71151840-b4e76800-226f-11ea-9b39-1a288f1dfcb5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
跟配置的菜单缓使用的组件有关系
![image](https://user-images.githubusercontent.com/3162115/71152076-638ba880-2270-11ea-8802-d4f9ee3b9d86.png)
src/components/layouts/RouteView.vue


如何解决不了问题，可以全文搜索router-view、router-view
查看跟你页面有关系的组件

**Comment by Nicky213Zhang** [comment]
如将前端组件固定为：layouts/RouteView，只能是做展开下级菜单之用，访问不了具体页面。然后，router-view找了，看不出来问题具体怎么修改

**Comment by Nicky213Zhang** [comment]
> 跟配置的菜单缓使用的组件有关系
> ![image](https://user-images.githubusercontent.com/3162115/71152076-638ba880-2270-11ea-8802-d4f9ee3b9d86.png)
> src/components/layouts/RouteView.vue
> ![image](https://user-images.githubusercontent.com/3162115/71152655-fb3dc680-2271-11ea-9880-94d488590999.png)
> 
> 如何解决不了问题，可以全文搜索router-view、router-view
> 查看跟你页面有关系的组件

如将前端组件固定为：layouts/RouteView，只能是做展开下级菜单之用，访问不了具体页面。然后，router-view找了，看不出来问题具体怎么修改

**Comment by zhangdaiscott** [comment]
参考 https://github.com/zhangdaiscott/jeecg-boot/issues/814
看看是否类似的问题
