### ISSUE TITLE
密码解密算法无效，空指针

### ISSUE THREAD

**Issue by luokl2019** [zhangdaiscott/jeecg-boot#821]
##### 版本号：
2.1.2

##### 问题描述：
解密算法无效，最后空指针异常。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40263163/71165684-4533a600-228c-11ea-9569-3b9d06bdbd55.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
2.1.2 没有加密解密操作

**Comment by luokl2019** [comment]
@zhangdaiscott 那这个是什么
![image](https://user-images.githubusercontent.com/40263163/71222826-fc700180-230c-11ea-85b1-55a6559a0f8b.png)
