### ISSUE TITLE
没有找到和jeecg一样的接口管理模块

### ISSUE THREAD

**Issue by heidongzai** [zhangdaiscott/jeecg-boot#822]
##### 版本号：
2.1.1

##### 问题描述：

没有找到原来jeecg中的接口管理、接口用户管理、接口用户权限管理功能，接口用户和系统用户分开管理的模式。
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecgboot 是前后分离的模式，所有的请求都是接口，所以不需要老版的设计了
