### ISSUE TITLE
“首页”页签能否实现允许关闭

### ISSUE THREAD

**Issue by YvanYangi** [zhangdaiscott/jeecg-boot#823]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/42790947/71181773-c6e8fb00-22af-11ea-9e3c-34ec1ea5f569.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
首页禁止关闭是特意加的，需要关闭的话，可以自己改造

**Comment by huanlirui** [comment]
src/components/layouts/TabLayout.vue    
改造一下remove函数即可
