### ISSUE TITLE
online表单开发是否可以增加一个erp风格的选项，像一对多代码生成里的那样。

### ISSUE THREAD

**Issue by archorfight** [zhangdaiscott/jeecg-boot#824]
##### 版本号：

2.1.2
##### 问题描述：
online表单开发是否可以增加一个erp风格的选项，像一对多代码生成里的那样？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangdaiscott** [comment]
已实现，下个版本发布
