### ISSUE TITLE
Oracle数据库初始化问题

### ISSUE THREAD

**Issue by lakeland1990** [zhangdaiscott/jeecg-boot#825]
##### 版本号：
2.1.2

##### 问题描述：
2.1.2版本现在已经提供了
oracle11g_AMERICAN_AMERICA.ZHS16GBK.dmp
文件

对此我有两点建议
1. 建议能使用AL32UTF8而不是ZHS16GBK，ZHS16GBK字符集已经基本不适用于现代业务了。
2. 在1的基础上，希望能和mysql、sqlserver一样提供sql文件而不是dmp文件（注：两种字符集需求的字段大小是不同的）

##### 截图&代码：
不涉及

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
新版已经提供的sql脚步，可以试试
