### ISSUE TITLE
使用前端缓存keep-alive造成的bug。

### ISSUE THREAD

**Issue by xiuxiuyifan** [zhangdaiscott/jeecg-boot#827]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/27720360/71322577-0019a900-2504-11ea-9f9a-adeef061e127.png)

在插件里面看到router的path竟然是一样的，

![image](https://user-images.githubusercontent.com/27720360/71322641-edec3a80-2504-11ea-9d4d-8187cc20db8d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xiuxiuyifan** [comment]
我写了一个简单的例子，在github上面https://github.com/xiuxiuyifan/vue-router-test，因为上传到codesandbox运行报错了。

**Comment by zhangdaiscott** [comment]
这个问题下个版本修复
