### ISSUE TITLE
在线表单开发是否支持在线表单字段----模糊查询

### ISSUE THREAD

**Issue by 15152763704** [zhangdaiscott/jeecg-boot#830]
##### 版本号：
最新版本

##### 问题描述：
在线开发表单，是否支持字段模糊查询？？？

如果支持，该怎么修改？？？？

我看jeecg后台查询功能源码直接是mybatis-plus，如果要改造是不是自己重写拼写sql？？？？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58929241/71340120-b7f49800-2590-11ea-8cd2-7f56ff28994e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
支持模糊查询

   格式一： 张*    （后模糊匹配）
     格式二： *张    （前模糊匹配）
     格式三： *张*   （全模糊匹配）                                            
     格式四： *张*三* （更高级匹配）

http://doc.jeecg.com/1273939
