### ISSUE TITLE
配置聚合路由菜单显示为空

### ISSUE THREAD

**Issue by 273100050** [zhangdaiscott/jeecg-boot#831]
##### 问题描述：
配置聚合路由菜单显示为空

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8478281/71348049-a4542c00-25a6-11ea-8f36-695ff022f502.png)
![image](https://user-images.githubusercontent.com/8478281/71348090-bafa8300-25a6-11ea-83f1-5859c5853d97.png)
![image](https://user-images.githubusercontent.com/8478281/71348136-d06fad00-25a6-11ea-9eef-5cc07156c778.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by TankCoder** [comment]
这个最后是怎么修复的呢？？
