### ISSUE TITLE
Nginx代理相关问题，需要修改开发文档的示例

### ISSUE THREAD

**Issue by shenfazhire** [zhangdaiscott/jeecg-boot#833]
##### 问题描述：jeecg-boot开发文档关于上线发布JAR部署方案Nginx代理导致双//
由
#后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问		
		location ^~ /jeecg-boot {
			proxy_pass              http://127.0.0.1:8080/jeecg-boot/;
			proxy_set_header        Host 127.0.0.1;
			proxy_set_header        X-Real-IP $remote_addr;
			proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		}
改为
#后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问		
		location ^~ /jeecg-boot {
			proxy_pass              http://127.0.0.1:8080/jeecg-boot;
			proxy_set_header        Host 127.0.0.1;
			proxy_set_header        X-Real-IP $remote_addr;
			proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		}

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by quanquan-dane** [comment]
你好，你的nginx代理能成功么，我成功登录后一直是404

**Comment by liudonghua123** [comment]
根据 `proxy_pass` 的 官方使用文档
如果 `location` 中有 末尾 `/` 则 `proxy_pass` 中一般也需要，如果没有则 `proxy_pass`  中一般也不需要

参考
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
https://stackoverflow.com/questions/22759345/nginx-trailing-slash-in-proxy-pass-url

**Comment by zhangdaiscott** [comment]
这个没有影响啊，我们加了后缀斜杠，也不影响
