### ISSUE TITLE
部署到linux服务器之后，在已登录的情况下，直接访问登陆界面，显示404

### ISSUE THREAD

**Issue by quanquan-dane** [zhangdaiscott/jeecg-boot#834]
##### 版本号：
2.1.2

##### 问题描述：
部署到linux服务器之后，首次可以登录，在已登录的情况下，直接访问登陆界面，显示404，是按照文档配置的每个步骤都检查过，依然不行！！！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6870297/71367228-64f60180-25df-11ea-8735-3125a505d2ed.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273922

**Comment by quanquan-dane** [comment]
就是按照这个配置的，不行，不行，不行
