### ISSUE TITLE
j-tree-select如何获取text值？

### ISSUE THREAD

**Issue by chen110xi** [zhangdaiscott/jeecg-boot#838]
##### 版本号：
2.1.2

##### 问题描述：
j-tree-select如何获取text值？
已经参考http://jeecg-boot.mydoc.io/?t=345967，但是没有找到解决方案。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rubywu** [comment]
<j-tree-select
        style="width: 300px"
        v-model="treeValue"
        dict="sys_depart,depart_name,id"
        pid-field="parent_id">
      </j-tree-select>
      {{ treeValue }}
