### ISSUE TITLE
使用JeecgOneGUI 在MySQL8 代码生成，实体内的顺序不一致和表设置顺序不一致

### ISSUE THREAD

**Issue by emmetmayi** [zhangdaiscott/jeecg-boot#839]
##### 版本号：
```
<dependency>
    <groupId>org.jeecgframework.boot</groupId>
    <artifactId>codegenerate</artifactId>
    <version>1.0.8</version>
</dependency>
```

##### 问题描述：
查询 `information_schema.columns` 在Mysql8中，查询出来没有按照设置的排序顺序
```
select column_name,data_type,column_comment,numeric_precision,numeric_scale,character_maximum_length,is_nullable nullable from information_schema.columns where table_name = '' and table_schema = ''
```

## 解决方式： 在查询的后面增加 `order by ORDINAL_POSITION`
```
select column_name,data_type,column_comment,numeric_precision,numeric_scale,character_maximum_length,is_nullable nullable from information_schema.columns where table_name = '' and table_schema = '' order by ORDINAL_POSITION
```
##### 截图&代码：
![image](https://user-images.githubusercontent.com/4858936/71434387-38490380-271f-11ea-9339-398a40d582a6.png)

![image](https://user-images.githubusercontent.com/4858936/71434336-ec965a00-271e-11ea-8170-2a8a1392a451.png)

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangdaiscott** [comment]
已经修改升级jar即可
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.0.9</version>
</dependency>
