### ISSUE TITLE
多tab显示bug

### ISSUE THREAD

**Issue by qiuhaipeng1** [zhangdaiscott/jeecg-boot#840]
##### 版本号：
2.1.2

##### 问题描述：
打开多个tab页面后，最小化浏览器，再放大，其他tab标签会消失（包括首页）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23470739/71437276-e65aaa80-272b-11ea-8a8f-014cc8b56e4c.png)
![image](https://user-images.githubusercontent.com/23470739/71437198-819f5000-272b-11ea-8c4e-138572ac2621.png)
![image](https://user-images.githubusercontent.com/23470739/71437208-8fed6c00-272b-11ea-851e-515cbe8c9f5e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/804
