### ISSUE TITLE
路由缓存问题

### ISSUE THREAD

**Issue by aleiliuwei** [zhangdaiscott/jeecg-boot#842]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前还不支持这种模式，我们看看

**Comment by xiuxiuyifan** [comment]
你可以在代码里面对activated钩子里面做判断，这个钩子是当被缓存页面激活的时候会执行的。

**Comment by zhangdaiscott** [comment]
好

**Comment by sjlei** [comment]
问题已修复，将在下个版本同步。

-----

在下个版本发布之前可以先手动在`TabLayout.vue`文件中添加如下几行代码即可。

![image](https://user-images.githubusercontent.com/34293221/71711660-f1ed5600-2e3c-11ea-9a28-40c8ac5c320f.png)

``` js
          if (newRoute.meta.keepAlive) {
            this.routeReload()
          }
```

**Comment by zhangdaiscott** [comment]
已经重新改造，下个版本2.3.1 更新代码
