### ISSUE TITLE
2.1.3版本顶部顶部导航栏菜单搜索无法打开外链菜单

### ISSUE THREAD

**Issue by qixiaodong** [zhangdaiscott/jeecg-boot#843]
##### 版本号：
2.1.3

##### 问题描述：
通过顶部的顶部导航栏搜索菜单，打开外部链接的菜单，无法打开，报404错误；
如系统中的 常见案例->百度，大屏设计->生产销售监控、智慧物流监控 均无法通过搜索菜单打开。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/24423288/71452240-f6bb6580-27bd-11ea-82d2-db1565695372.png)
![image](https://user-images.githubusercontent.com/24423288/71452243-fcb14680-27bd-11ea-9a17-31aadee779a1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
了解

**Comment by sjlei** [comment]
已修改，下个版本发布
