### ISSUE TITLE
各种选择组件的功能需求

### ISSUE THREAD

**Issue by happy-panda** [zhangdaiscott/jeecg-boot#845]
##### 问题描述：
希望各种选择组件都设置自定义返回字段功能，这个在业务开发中灰常重要！！！！
不要别人提一个issue就改一个，做的时候就考虑一下。保证通用性很重要，毕竟做的就是脚手架项目。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
新版已经改了
