### ISSUE TITLE
2.1.3版本增加一级单位空指针错误

### ISSUE THREAD

**Issue by gudufun** [zhangdaiscott/jeecg-boot#847]
##### 版本号：
2.1.3

##### 问题描述：

这个实现类
src/main/java/org/jeecg/modules/system/service/impl/SysDepartServiceImpl.java
在新建一级部门的时候
String[] codeArray = (String[]) FillRuleUtil.executeRule("org_num_role",formData);
codeArray 会返回为null
导致后面的代码发生空指针错误

**Comment by zhangdaiscott** [comment]
你是下载的原始版本，还是自己升级后导致的？

**Comment by gudufun** [comment]
升级，我早上又查了下，发现是数据库fill_rule的规则没同步导致的。我之前只比对了代码。

**Comment by zhangdaiscott** [comment]
好
