### ISSUE TITLE
正常clone到本地idea，通过Maven下载好包，还是缺少引用

### ISSUE THREAD

**Issue by zazzlec** [zhangdaiscott/jeecg-boot#848]
#### 版本号：
2.1.3
##### 问题描述：
启动类的注解
@EnableAutoConfiguration
有红线
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52208462/71498917-4a4eb180-2899-11ea-98fc-4c30b6cbca6c.png)

**Comment by zhangdaiscott** [comment]
这个可以注释掉，没关系

http://doc.jeecg.com/1273965
