### ISSUE TITLE
用户管理权限

### ISSUE THREAD

**Issue by liushaowenliushaowen** [zhangdaiscott/jeecg-boot#849]
##### 截图&代码：

![1](https://user-images.githubusercontent.com/49803922/71496272-677d8300-288d-11ea-9ad9-bb8e34e7c6e6.jpeg)
![2](https://user-images.githubusercontent.com/49803922/71496294-88de6f00-288d-11ea-9692-f381c21b5c2d.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
默认的还是，自己改过什么？

**Comment by liushaowenliushaowen** [comment]
默认的，没有改过东西，我下了一个2.1.1版本，这个是正常的

**Comment by liushaowenliushaowen** [comment]
默认的，没有改过东西，我下了一个2.1.1版本，看了一下，这里的应该是正常

**Comment by zhangdaiscott** [comment]
参考这个改下代码
![image](https://user-images.githubusercontent.com/3162115/71505758-67937800-28b9-11ea-99e8-f4fd29b93efe.png)


或者给admin角色授权用户的编辑权限，默认是加上权限控制了，没有授权导致的
