### ISSUE TITLE
配置菜单按钮访问权限后 一直提示无权限

### ISSUE THREAD

**Issue by cwjtojava** [zhangdaiscott/jeecg-boot#850]
##### 问题描述：
在用户管理模板  编辑用户 后端代码修改接口配置user:edit 
在前端页面修改 一直提示无权限

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6203101/71498012-9d266a00-2895-11ea-9da0-023933e99258.png)
![image](https://user-images.githubusercontent.com/6203101/71498053-bf1fec80-2895-11ea-895b-7f43d028e79c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把权限的配置，详细截图看看

**Comment by cwjtojava** [comment]
![image](https://user-images.githubusercontent.com/6203101/71509191-72540a00-28c5-11ea-9643-dd7ef8253683.png)

**Comment by cwjtojava** [comment]
加了这边的开发群 群里管理也一直不回复相关的问题 一些小细节问题全部都得自己慢慢排查

**Comment by zhangdaiscott** [comment]
开源群是供大家自己交流学习，我们精力有限，群不做太多支持

**Comment by cwjtojava** [comment]
那么请问一下  我这个菜单配置有问题嘛 因为这块都是系统本身就有的功能嘛 我今天就试了哈 但是就发现了问题 群里不回答 就只好在这边上面问一下咯
