### ISSUE TITLE
统计报表/布局统计报表 档案统计显示不全

### ISSUE THREAD

**Issue by hxp0618** [zhangdaiscott/jeecg-boot#851]
##### 版本号：
2.1.3

##### 问题描述：
统计报表/布局统计报表 档案统计显示不全

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30236140/71505447-2b134c80-28b8-11ea-96fc-0e16fd35fa3d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收到

**Comment by sjlei** [comment]
已修改，下个版本发布
