### ISSUE TITLE
2.1.3版本中的JSelectBizComponentModal.vue报错：The data property "columns" is already declared as a prop. Use prop default value instead.

### ISSUE THREAD

**Issue by ixintian** [zhangdaiscott/jeecg-boot#852]
##### 版本号：
2.1.3

##### 问题描述：
JSelectMultiUser.vue中调用的JSelectBizComponentModal.vue
Console报错：
[Vue warn]: The data property "columns" is already declared as a prop. Use prop default value instead.

##### 截图&代码：

![image](https://user-images.githubusercontent.com/24642704/71509402-1b026980-28c6-11ea-8fdc-d3415a47ba8e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
看一下你JSelectBizComponentModal.vue这个文件的代码，截图 data() ，看看是不是和我的一样
![image](https://user-images.githubusercontent.com/34293221/71620589-a69d3280-2c05-11ea-9bad-36e4ee849c7e.png)

**Comment by ixintian** [comment]
是一样的
![image](https://user-images.githubusercontent.com/24642704/71622293-af930180-2c0f-11ea-9176-0aaa0b92aa42.png)

**Comment by sjlei** [comment]
那就奇怪了，我这里是没报错的，你是什么情况下报的错呢？在哪个页面上用的这个组件？

**Comment by ixintian** [comment]
刚开始怀疑ant-design-vue的版本，我从1.4.0升到了1.4.8，然后我降回去还是报错。后来就折腾升级Vue-CLI，现在不报错了。我再观察一下，麻烦你了。

**Comment by ixintian** [comment]
我查了一下原来是这样：
JSelectBizComponentModal中在新版本中的props中更改了columns的名字：
![image](https://user-images.githubusercontent.com/24642704/71654608-97d18f80-2d6d-11ea-8db4-2459a8fc450a.png)
然后JSelectBizComponentModal又mixins了JeecgListMixin，
在JeecgListMixin中的data中我增加了columns的定义，所以新版本报错了。麻烦作者了。
