### ISSUE TITLE
在线表单样式--设置两列

### ISSUE THREAD

**Issue by 15152763704** [zhangdaiscott/jeecg-boot#853]
##### 版本号：

最新版本
##### 问题描述：
生成的在线表单  页面内容 多行一列显示，但是我想设置成多行二列显示，不知道如何设置

##### 截图&代码：
代码片段：
<template>
  <a-modal :title="title":width="width":visible="visible" :confirmLoading="confirmLoading"
    @ok="handleOk" @cancel="handleCancel"  cancelText="关闭">
    <a-spin :spinning="confirmLoading">
      <a-form :form="form">
<a-form-item label="地区" :labelCol="labelCol" :wrapperCol="wrapperCol"></a-form-item>
<a-form-item label="创建时间" :labelCol="labelCol" :wrapperCol="wrapperCol" hidden>  </a-form-item>

![U(6_6%2~6IRV`RV FFBOC1C](https://user-images.githubusercontent.com/58929241/71511180-5bfd7c80-28cc-11ea-9685-8e13986042bb.png)
![KMRJJXH`KT$1M25~@` $6C](https://user-images.githubusercontent.com/58929241/71511183-5f910380-28cc-11ea-9e6a-4dc7cddc4482.png)
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
项目里面有双列的页面，参考下。另外可以看官方文档
https://vue.ant.design/docs/vue/introduce-cn/
