### ISSUE TITLE
配置菜单按钮访问权限后 一直提示无权限

### ISSUE THREAD

**Issue by cwjtojava** [zhangdaiscott/jeecg-boot#854]
##### 问题描述：
在用户管理模板 编辑用户 后端代码修改接口配置user:edit
在前端页面修改 一直提示无权限

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6203101/71511321-e47c1d00-28cc-11ea-8288-2a25a9874765.png)
![image](https://user-images.githubusercontent.com/6203101/71511323-e940d100-28cc-11ea-8970-34b7f29cf97a.png)
![image](https://user-images.githubusercontent.com/6203101/71511336-f067df00-28cc-11ea-9b26-cab2c73894d4.png)

感谢作者耐心查看此问题

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rubywu** [comment]
退出后重新登录试试

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecg-boot/issues/I179JN
