### ISSUE TITLE
下拉树有问题吧？？？？？

### ISSUE THREAD

**Issue by pog2g** [zhangdaiscott/jeecg-boot#859]
##### 版本号：
2.1.2

##### 问题描述：
* 添加子节点选择父节点时应该是选择父节点的id,但构建时返回确实parentId,让人摸不着头脑
* 为啥附加表构建下拉树parentId一定要传值的(如果是父节点parentId一般没有值。搞得太不灵活了)
* 友情提示:这代码不规范的太多了吧，，不得不让人吐槽(部分代码幼儿园写的，，部分大学生写的)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/48884933/71571769-f4873d00-2b16-11ea-9361-4bc51c28df3c.png)

![image](https://user-images.githubusercontent.com/48884933/71571810-27313580-2b17-11ea-9bf8-9b97fbc86385.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rubywu** [comment]
口气不小，搞的自己博士一样。
有默认值0，才更方便查询。用parentId还是用pid，或者随便其他是名字都可以。这才是灵活。

**Comment by zhangdaiscott** [comment]
二楼说的对，有默认值更好

**Comment by pog2g** [comment]
我只是中学生，，中学生都觉得不规范，，那博士可能就看不下去了。。。。。。

On Jan 5, 2020, at 6:26 PM, rubywu <notifications@github.com<mailto:notifications@github.com>> wrote:


口气不小，搞的自己博士一样。
有默认值0，才更方便查询。用parentId还是用pid，或者随便其他是名字都可以。这才是灵活。
