### ISSUE TITLE
新增的值不是按自增1-n+1而是一段数字

### ISSUE THREAD

**Issue by zhoudazhuang** [zhangdaiscott/jeecg-boot#860]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32217981/71572378-bb9c9780-2b19-11ea-9471-a25dc2598eff.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个前段生成id没有用

**Comment by zhoudazhuang** [comment]
请问这个可以改为数据库自增吗而不是自增一段数字
