### ISSUE TITLE
更换包名，页面表单自动生成代码不可用

### ISSUE THREAD

**Issue by xushuangshuang1234** [zhangdaiscott/jeecg-boot#861]
##### 截图&代码：请回答问题，老是删除干啥？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请先看常见问题贴，重复问题不要提。
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1

**Comment by xushuangshuang1234** [comment]
不是常见问题里面的问题，请帮忙查看
