### ISSUE TITLE
autopoi 双表头问题

### ISSUE THREAD

**Issue by Royyu1215** [zhangdaiscott/jeecg-boot#862]
##### 版本号：
2.1.0

##### 问题描述：

excel 导出的时候遇到双表头导出问题.原来easypoi 是有groupName 属性可以解决的.autopoi 则没有这个属性.因是单表数据,用excelentity 不合适且复杂
##### 截图&代码：

![image](https://user-images.githubusercontent.com/31911898/71574892-af1e3c00-2b25-11ea-815a-5e5f7580dd26.png)

如图所示

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
