### ISSUE TITLE
能否添加导航再分组

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#866]
##### 问题描述：
有个场景,页面的顶部是一些分类模块,比如系统管理,xxx应用,yyy应用,然后点击每一个模块后,刷新左侧的菜单树,不知道咱们这块对这个场景需求有计划考虑做进来吗?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jave-joe** [comment]
看到路由的readme里有这么一段说明:
 路由配置说明：
 建议：sider menu 请不要超过三级菜单，若超过三级菜单，则应该设计为顶部主菜单 配合左侧次级菜单
现在就想达到这种顶部主菜单配合左侧次级菜单的场景,请问如何配置还是需要怎么修改代码去做呢?

**Comment by jave-joe** [comment]
大概找到了顶部栏的地方,UserMenu.vue 这个组件,这里可以写顶部主菜单,想问下有没有提供左侧菜单树传值刷新的方法呢?点击顶部菜单的时候,需要调用这个方法去刷新左侧菜单.

**Comment by zhangdaiscott** [comment]
暂无此计划
