### ISSUE TITLE
发送系统通知时，向全体用户推送消息不成功，即发布后右上角消息提醒不显示。

### ISSUE THREAD

**Issue by Forevery1** [zhangdaiscott/jeecg-boot#867]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19872771/71655769-7c698300-2d73-11ea-9cf9-e315092be24c.png)
![image](https://user-images.githubusercontent.com/19872771/71655791-94410700-2d73-11ea-832c-cc66c7dcf289.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
测试没问题
需要点击发布
![Uploading image.png…]()
