### ISSUE TITLE
Online生成出代码后，无显示数据

### ISSUE THREAD

**Issue by lzdtech** [zhangdaiscott/jeecg-boot#869]
##### 截图&代码：
![1](https://user-images.githubusercontent.com/35595004/71657151-9b6b1380-2d79-11ea-8aee-aefb1461101a.png)
![2](https://user-images.githubusercontent.com/35595004/71657154-9e660400-2d79-11ea-884c-81a3b0249a5e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by hustweiwei** [comment]
这个功能我试过，可以的呢。但是我修改了项目名称后online就无法使用了

**Comment by lzdtech** [comment]
> 这个功能我试过，可以的呢。但是我修改了项目名称后online就无法使用了

我没有修改项目名称不行，重新git下来部署，测试一边也是同样

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/467
