### ISSUE TITLE
online表单开发，主附表模式修改表名后代码生成无法正常使用的bug

### ISSUE THREAD

**Issue by guojingbing** [zhangdaiscott/jeecg-boot#870]
##### 截图&代码：
生成代码页面报错
jeecg Cannot read property 'tableName' of nullError in render: "TypeError: Cannot read property 'tableName' ......

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
已经处理，online表单不允许修改表名，增加安全性
