### ISSUE TITLE
日期工具类线程不安全

### ISSUE THREAD

**Issue by alexanders9** [zhangdaiscott/jeecg-boot#871]
##### 问题描述：
日期工具类线程不安全（org.jeecg.common.util.DateUtils）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44674354/71706706-a6797e80-2e21-11ea-8c77-a2a192f6c84b.png)
##### 直接引用这些变量，导致线程不安全。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
