### ISSUE TITLE
online表单开发，富文本、下拉框有时会不显示内容

### ISSUE THREAD

**Issue by guojingbing** [zhangdaiscott/jeecg-boot#872]
##### 问题描述：
用online表达开发，实现了一个两个表单功能，都有富文本字段，配置到菜单中，进入第一个功能打开详情页数据正常显示；两个列表切换后再进入详情页，富文本和下拉框就不显示数据了，但是接口里是有相应数据的。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5864899/71709998-15140780-2e35-11ea-8c56-1cbdc5c76666.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请提供详细的重现步骤和截图
