### ISSUE TITLE
建议autoPoi升级，优化数据返回List Map格式下的复合表头导出excel的体验

### ISSUE THREAD

**Issue by fansir** [zhangdaiscott/jeecg-boot#873]
##### 版本号：
 autopoi 1.0.4

##### 问题描述：
导出excel时候，数据采用List<Map> 形式的，表头有复合表头，但每一条数据就是一个Map，没有一对多的关系。这种场景下，目前不能直接支持，需要对数据进行格式转换。可以改造下框架，对这种格式数据直接支持。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11716138/71710740-ba7caa80-2e38-11ea-94ac-ecc8a2c486ef.png)
想要使用的数据结构如下：
![image](https://user-images.githubusercontent.com/11716138/71710880-4a225900-2e39-11ea-892a-7915c38718e8.png)

##### 目前在项目中，临时处理办法
https://blog.csdn.net/xu_guo_jie/article/details/103757438

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3q

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
