### ISSUE TITLE
关于mybatis拦截器注入创建、修改时间问题

### ISSUE THREAD

**Issue by MQTimor** [zhangdaiscott/jeecg-boot#876]
##### 版本号：
2.1.3

##### 问题描述：
关于mybatis拦截器注入创建、修改时间问题

##### 截图&代码：

"createBy".equals(field.getName())

您好，个人觉得 创建人 创建时间 通过反射的时候使用硬编码匹配点不便于扩展、如果采用数组 可配置判断是否更加符合快速手脚架原则

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rubywu** [comment]
配置的形式，觉的默认值不便于获取。这种一般都固定的，不怎么重要。

**Comment by MQTimor** [comment]
好的，感谢解答，代码生成的时候字段名不为id的时候 无法被识别为主键的问题出现过吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "neo"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 下午4:35
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "Timor"<735121989@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 关于mybatis拦截器注入创建、修改时间问题 (#876)




配置的形式，觉的默认值不便于获取。这种一般都固定的，不怎么重要。
