### ISSUE TITLE
Maven配置已设置，但excel.def和view对应的依赖包是哪个？

### ISSUE THREAD

**Issue by ericql** [zhangdaiscott/jeecg-boot#880]
##### 版本号：
V2.1.3

##### 问题描述：
提示 
       Error:(25, 40) java: 程序包org.jeecgframework.poi.excel.def不存在
       Error:(28, 41) java: 程序包org.jeecgframework.poi.excel.view不存在

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28384866/71879243-97b80200-3168-11ea-9a8c-0cd18f912029.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by rubywu** [comment]
` 
		<dependency>
			<groupId>org.jeecgframework</groupId>
			<artifactId>autopoi-web</artifactId>
			<version>1.0.4</version>
			<exclusions>
				<exclusion>
					<groupId>commons-codec</groupId>
					<artifactId>commons-codec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>`

**Comment by ericql** [comment]
我找到问题的原因，发现是1.0.4不能用，降级成1.0.3就可以，不能引用

**Comment by ericql** [comment]
> ```
> 	<dependency>
> 		<groupId>org.jeecgframework</groupId>
> 		<artifactId>autopoi-web</artifactId>
> 		<version>1.0.4</version>
> 		<exclusions>
> 			<exclusion>
> 				<groupId>commons-codec</groupId>
> 				<artifactId>commons-codec</artifactId>
> 			</exclusion>
> 		</exclusions>
> 	</dependency>
> ```

我找到问题的原因，发现是1.0.4不能用，降级成1.0.3就可以，不能引用

**Comment by rubywu** [comment]
reimport maven

**Comment by ericql** [comment]
> reimport maven

跟reimport没关系，你拉最新的2.1.3代码试试

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/autopoi
