### ISSUE TITLE
前端Excel导出文件为TXT格式

### ISSUE THREAD

**Issue by alu4r** [zhangdaiscott/jeecg-boot#881]
##### 版本号：
V2.1.3

##### 问题描述：
谷歌浏览器导出Excel时，发现导出文件为TXT格式。（我的谷歌浏览器有安装下载管理器的插件）
定位代码到JeecgListMixin.js中handleExportXls方法。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/30022177/71894078-3dc73480-3188-11ea-8b31-4898edcdf1ee.png)
前端debug发现Blob对象的类型为text/xml：
![image](https://user-images.githubusercontent.com/30022177/71894407-29376c00-3189-11ea-8971-84dc214cfd5f.png)

后端已经指定了类型，不知道为什么前端类型是这个。可能是我安装了插件的原因吧。
建议前端也指定一下类型：
![image](https://user-images.githubusercontent.com/30022177/71894578-9c40e280-3189-11ea-85ae-4c4a298f38eb.png)
遇到这个问题的同学希望对你有帮助！

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
3Q

**Comment by zhangdaiscott** [comment]
已经修改，下个版本发布
