### ISSUE TITLE
动态报表查询中的数据权限

### ISSUE THREAD

**Issue by mysuplover** [zhangdaiscott/jeecg-boot#882]
##### 版本号：
V2.1.3

##### 问题描述：
jeecgboot在online模块进行了封装，动态报表查询，怎样实现数据权限。在jeecg中可以通过修改CgReportController，在查询时候进行数据拦截，来实现数据权限。但是boot版本查询请求直接到封装的jar包。感谢大佬指点

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本实现这功能
