### ISSUE TITLE
2.1.1版本一对一代码新增和编辑报错

### ISSUE THREAD

**Issue by heidongzai** [zhangdaiscott/jeecg-boot#883]
##### 版本号：
2.1.1

##### 问题描述：
在线生成的代码，前端进行新增和编辑报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19759686/72032024-30fe2a00-32c9-11ea-9cfc-892a461baaaf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
建议升到2.1.3 老版不好做支持

**Comment by heidongzai** [comment]
2.1.3版没这个问题了吗？
