### ISSUE TITLE
前端路由带参数打开多个相同页面问题

### ISSUE THREAD

**Issue by JacksonTanYi** [zhangdaiscott/jeecg-boot#884]
##### 问题描述：

情景：订单列表跳转订单详情页
结果：每打开一个详情页，带的参数id都不一样，导致判断fullpath不一致，打开新页面

期望的效果应该是只会打开一个详情页面
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by JacksonTanYi** [comment]
期望的效果应该是只会打开一个详情页面

**Comment by King10031** [comment]
解决了吗 老哥 这个问题
