### ISSUE TITLE
online表单配置菜单后除admin，其他角色访问404

### ISSUE THREAD

**Issue by shrto** [zhangdaiscott/jeecg-boot#885]
##### 版本号：
2.1.3

##### 问题描述：

online表单配置菜单后admin可以访问，其他角色访问404
在线开发的所有auto已经授权
全部auto在以下截图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59555469/72055914-9b818b00-3306-11ea-88e0-de5e2663c4f3.png)

**Comment by zhangdaiscott** [comment]
父一级不勾？

**Comment by shrto** [comment]
谢谢， 勾了可以访问， 但是其他角色就会显示 在线开发 这个菜单了，用户是不需要看到这个菜单的， 可以去掉这个菜单吗

**Comment by zhangdaiscott** [comment]
` //update--begin--autor:qinfeng-----date:20200109------for：JEECG-63 一级菜单的子菜单全部是隐藏路由，则一级菜单不显示------
            console.time()
            menuData.forEach((item, index) => {
              if (item["children"]) {
                let hasChildrenMenu = item["children"].filter((i) => {
                  return !i.hidden || i.hidden == false
                })
                if (hasChildrenMenu == null || hasChildrenMenu.length == 0) {
                  item["hidden"] = true
                }
              }
            })
            console.timeEnd();
            console.log(" menu show json ", menuData)
            //update--end--autor:qinfeng-----date:20200109------for：JEECG-63 一级菜单的子菜单全部是隐藏路由，则一级菜单不显示------
`

src/store/modules/user.js
123

**Comment by shrto** [comment]
谢谢，
![image](https://user-images.githubusercontent.com/59555469/72196768-7b141680-3455-11ea-94a8-06a7724b263c.png)
