### ISSUE TITLE
cas对接

### ISSUE THREAD

**Issue by fascination2016** [zhangdaiscott/jeecg-boot#886]
你好，我现在需要使用cas单点登陆功能，教学视频中那个jeecg-boot-cas-db项目代码能不能发出来？我大致了解这个项目是为了查询数据库的用户表验证密码，但还是希望能参考你写好的源码，谢谢了。

**Comment by 313988838** [comment]
你可以去官方下载cas做为服务端，然后再使用。

**Comment by zhangdaiscott** [comment]
这个暂时无法提供，自己写吧
