### ISSUE TITLE
系统使用的日志包有问题

### ISSUE THREAD

**Issue by 313988838** [zhangdaiscott/jeecg-boot#887]
##### 问题描述： @Slf4j  这个注解再高并发时会创建多个线程,造成系统宕机.
我们使用了jdk的线程监控工具查询出的

##### 截图&代码：
忘记截图了。修复建议：@Log4j2当前日志注解不会创建多个线程。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by galaxist** [comment]
是你们日志配置有问题，写入同一个文件了吧。
或者是专门测试高并发写入造成的，没有现实意义。
日志都能写的系统宕机的话，在那之前数据库早就宕机了。

**Comment by zhangdaiscott** [comment]
logback-spring.xml 配置有问题，导致日志未按照日期和大小，生成新文件
 下载附件覆盖
[logback-spring.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4546982/logback-spring.zip)
