### ISSUE TITLE
调用api，返回前台数据包含password，salt，容易推测密码

### ISSUE THREAD

**Issue by ares007** [zhangdaiscott/jeecg-boot#89]
jeecg-boot/src/main/java/org/jeecg/modules/system/service/impl/SysUserDepartServiceImpl.java

list，queryUserByDepId返回的数据中包含password，salt内容，数据泄露了

**Comment by zhangdaiscott** [comment]
3Q

**Comment by zhangdaiscott** [comment]
已经解决，下个版本发布
