### ISSUE TITLE
字体是否可商用

### ISSUE THREAD

**Issue by 743636214** [zhangdaiscott/jeecg-boot#891]
##### 截图&代码：
![企业微信截图_15789688872101](https://user-images.githubusercontent.com/51351795/72308979-9468cd00-36b8-11ea-871e-f5134b3771d5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://zhidao.baidu.com/question/1696117545603597068.html
