### ISSUE TITLE
online表单自定义树控件无法查询

### ISSUE THREAD

**Issue by dongshaofei666** [zhangdaiscott/jeecg-boot#892]
##### 版本号：
2.1.3

##### 问题描述：
online表单自定义树控件无法查询

##### 截图&代码：
![Snipaste_2020-01-14_11-11-19](https://user-images.githubusercontent.com/41518696/72311320-2ffd3c00-36bf-11ea-8bfd-88bda2eba7ee.png)
![Snipaste_2020-01-14_11-13-08](https://user-images.githubusercontent.com/41518696/72311321-312e6900-36bf-11ea-835a-ff72412fc06c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，目前查询区域树控件未支持

**Comment by zhangdaiscott** [comment]
功能已经实现，下个版本发布

**Comment by CrushXi** [comment]
已经更新，但树控件还是不支持查询呢
