### ISSUE TITLE
希望能支持LDAP登录

### ISSUE THREAD

**Issue by matraxa** [zhangdaiscott/jeecg-boot#893]
##### 版本号：
2.1.3

##### 问题描述：
从文档和登录界面中未能找到LDAP登录的支持，希望能支持LDAP登录方式，便于账号打通和一键登录。其中首次通过LDAP登录的用户可分配默认角色以达到权限控制。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11548462/72314740-17931e80-36cb-11ea-9399-8905721fbaa3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂时不考虑，可以自己二发

**Comment by panqingdian** [comment]
这个功能现在还没有吗，我觉得这个挺重要的一块
