### ISSUE TITLE
前端切换主题 header颜色显示问题

### ISSUE THREAD

**Issue by kingshan** [zhangdaiscott/jeecg-boot#894]
##### 版本号：

 2.1.3
##### 问题描述：

前端切换整体风格后，header不变色，之前版本会变白色，带颜色比较违和
##### 截图&代码：

 
![image](https://user-images.githubusercontent.com/12539881/72318060-31862e80-36d6-11ea-8af7-6c6b2b8c8342.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
