### ISSUE TITLE
手机端访问，点击搜索框变形后无背景颜色导致看不见

### ISSUE THREAD

**Issue by SuperAgo** [zhangdaiscott/jeecg-boot#895]
##### 版本号：

2.1.3大屏版本
##### 问题描述：
切换手机登录，点击搜索菜单会使导航栏下移，但是下移后没有设置背景颜色导致看不到导航栏

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29573348/72403392-dcf1ba80-378c-11ea-961b-26efed0a4a0d.png)
![image](https://user-images.githubusercontent.com/29573348/72403437-01e62d80-378d-11ea-9384-cbd86682014f.png)
![image](https://user-images.githubusercontent.com/29573348/72403515-440f6f00-378d-11ea-91a7-73ce57b8ef8d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收到，正在处理中
