### ISSUE TITLE
数据授权有时生效有时不生效

### ISSUE THREAD

**Issue by wrhwww** [zhangdaiscott/jeecg-boot#896]
##### 版本号：
v2.0.1

##### 问题描述：
数据授权配置后，同一授权字段，采用“模糊”授权规则，有的数据能够进行过滤，有的不可以
问题1.
如下图所示：采用第一个TJZ规则的可以授权生效，采用第二个规则的授权不生效，两条数据规则的“规则字段”都是相同的
问题2.
同一个“规则字段”，“规则值”不同，数据授权多选时，只能有一个生效，不能两个都生效。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53960031/72442821-2a4f4580-37e8-11ea-8d37-f5981525ee0c.png)
![image](https://user-images.githubusercontent.com/53960031/72442952-6b475a00-37e8-11ea-9842-af52dda6c51d.png)
![image](https://user-images.githubusercontent.com/53960031/72443106-b82b3080-37e8-11ea-9474-fc30afb97cc9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
同一个字段，只能配置一个规则，不支持多个
