### ISSUE TITLE
2.1.3.RELEASE 版本，打成jar包不可用导入功能不可用

### ISSUE THREAD

**Issue by baolongcheng** [zhangdaiscott/jeecg-boot#899]
##### 版本号：
2.1.3.RELEASE

##### 问题描述：
打成jar包后导入功能使用异常，报空指针异常。不打包本机运行正常。
依赖的auto-poi的版本为1.0.4

##### 截图&代码：

查看源码后， 发现问题是在PoiPublicUtil.class.getClassLoader().getResource("") 在打包后返回null。
![image](https://user-images.githubusercontent.com/40141347/72673296-2dc22580-3aa3-11ea-82f9-4818dae620b1.png)

在打包后运行结果

![image](https://user-images.githubusercontent.com/40141347/72673289-2438bd80-3aa3-11ea-8517-73ad54a3c0b6.png)

而在导入功能中有一处调用org.jeecgframework.poi.util.PoiPublicUtil#getWebRootPath
这个方法。
![image](https://user-images.githubusercontent.com/40141347/72673329-b50f9900-3aa3-11ea-8a7b-0fb572c55588.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你们部署的？这块特意改过，应该不会有问题了

**Comment by zhangdaiscott** [comment]
你把依赖升级到这个版本试试
<dependency>
  <groupId>org.jeecgframework</groupId>
  <artifactId>autopoi</artifactId>
  <version>1.0.5</version>
</dependency>

**Comment by zhangdaiscott** [comment]
经过测试 centos下 jar包部署不存在问题
