### ISSUE TITLE
Chrome 浏览器缓存问题

### ISSUE THREAD

**Issue by aijuntao** [zhangdaiscott/jeecg-boot#903]
##### 版本号：

2.1.1（发布日期：20191021）

##### 问题描述：

Centos 系统，前端 nginx，后端 tomcat，每次发布版本后，Chrome 浏览器需要先清理缓存后，才能看的新发布的功能，要怎么处理呢？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
我们发布，不需要清理缓存也可以看到更新内容，不清楚你的问题
