### ISSUE TITLE
列表页展示问题

### ISSUE THREAD

**Issue by yanming1** [zhangdaiscott/jeecg-boot#906]
版本号：
master

问题描述：
列表页子菜单头部展示问题

截图&代码：
![image](https://user-images.githubusercontent.com/15033680/72769998-89251c80-3c37-11ea-8cd7-0898e579f775.png)

**Comment by zhangdaiscott** [comment]
没明白

**Comment by zhangdaiscott** [comment]
此功能是演示页面，如果没有问题回复，本周关闭
