### ISSUE TITLE
后端查询字段是int类型，前端的控件用多选框，出错

### ISSUE THREAD

**Issue by 1987zfp** [zhangdaiscott/jeecg-boot#907]
##### 版本号：
2.1.3

##### 问题描述：
后端查询字段是int类型，前端控件用多选框
查询时，传到后端的是用逗号分隔的数字，string类型
后端接收的entity，对应字段为int类型，解析出错

##### 截图&代码：
前端已经用了j-checkbox

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
截图看下你的配置和错误信息

**Comment by zhangdaiscott** [comment]
无问题跟踪反馈，此问题先暂时关闭
