### ISSUE TITLE
点【从数据库导入表单】按钮报Unknown database 'jeecg-boot'错误，

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#911]
##### 版本号：
2.1.3 大屏版

##### 问题描述：
点从数据库导入表单报Unknown database 'jeecg-boot'错误，
我们数据库名不叫 'jeecg-boot'，请问如何修改？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。
![image](https://user-images.githubusercontent.com/3365218/73590221-e912a180-451a-11ea-8e98-501af60325e5.png)
![image](https://user-images.githubusercontent.com/3365218/73590225-f465cd00-451a-11ea-9f26-17d9f9dfbbd9.png)

**Comment by zhangdaiscott** [comment]
代码生成器的数据库配置单独的
http://doc.jeecg.com/1275846
