### ISSUE TITLE
如何让地址栏不显示参数

### ISSUE THREAD

**Issue by Huang-ChenGang** [zhangdaiscott/jeecg-boot#912]
##### 版本号：
vue-antd-jeecg 2.0.2

##### 问题描述：
this.$router.push({
path: '/process/BpmAutoDesformApplyMore',
query: {
procType: type
}
})
使用这种方式打开一个新的tab页之后，地址栏会展示传递的参数，如何让传递的参数不展示呢？

##### 截图&代码：
this.$router.push({path: '/market/orderDetail', query: {orderId: record.id}});

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
采用params方式
https://www.jianshu.com/p/d7b113ce981b

![image](https://user-images.githubusercontent.com/3162115/74139800-f3c1ea80-4c2e-11ea-94a8-6beede46d376.png)
