### ISSUE TITLE
online表单，如何实现多个文本框的onChange事件

### ISSUE THREAD

**Issue by ggi2003** [zhangdaiscott/jeecg-boot#913]
##### 版本号：
2.1.3

##### 问题描述：
online表单，如何实现多个文本框的onChange事件，按照下面的方式不行

##### 截图&代码：

 onlChange(){
   return {
    school_name(){
      let value = event.value
      let values = {'sys_org_code':value}
      that.triggleChangeValues(values)
    }
    sys_user_name(){
      let value = event.value
      let values = {'sys_user_id':value}
      that.triggleChangeValues(values)
    }
  }
 }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/74129869-996b5e80-4c1b-11ea-8a17-a58bab3ec9bc.png)

http://doc.jeecg.com/1276925

**Comment by ggi2003** [comment]
上面的例子中只有一个school的onlchange事件，我想说的是多个控件的onchange事件如何实现
