### ISSUE TITLE
如何让地址栏不显示参数-追问

### ISSUE THREAD

**Issue by Huang-ChenGang** [zhangdaiscott/jeecg-boot#915]
##### 版本号：
vue-antd-jeecg 2.0.2

##### 问题描述：
https://github.com/zhangdaiscott/jeecg-boot/issues/912
对这个问题的追问，这个回答的做法会让新页面覆盖整个页面，就是跳转后左侧和顶部菜单栏会没有，只显示中间内容区

##### 截图&代码：
https://github.com/zhangdaiscott/jeecg-boot/issues/912
![image](https://user-images.githubusercontent.com/35560581/74218414-01d24280-4ce5-11ea-9af2-3434d17c34d1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
基础问题不要在这里提问
