### ISSUE TITLE
GUI代码生成，配置表的主键无效

### ISSUE THREAD

**Issue by chishaohui333** [zhangdaiscott/jeecg-boot#918]
##### 截图&代码：
`#db Table id [User defined] 
db_table_id=user_id`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
主键自定义咱未实现支持

**Comment by chishaohui333** [comment]
哦，好的，所以现在数据库表的主键字段要为“id”吗

**Comment by zhangdaiscott** [comment]
是的

**Comment by saarLi2018** [comment]
自动生成表的主键名字必须为 id  不太合适啊
