### ISSUE TITLE
使用oracle序列，用@KeySequence配置序列，无效

### ISSUE THREAD

**Issue by chishaohui333** [zhangdaiscott/jeecg-boot#920]
##### 问题描述：
在实体类中用@KeySequence配置序列，无效，新增数据时报参数为空异常

##### 截图&代码：
代码：
@TableName("CITY_NAME")
@KeySequence(value = "SEQ_CITY_NAME_ID", clazz = Integer.class)
@TableId(
			value = "CITY_NAME_ID",type = IdType.INPUT
	)
	/**城市名ID */
	@Excel(name = "城市名ID ", width = 15)
	@ApiModelProperty(value = "城市名ID ,主键,自增")
	private Integer cityNameId;

异常：
nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='cityNameId', mode=IN, javaType=class java.lang.Integer, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}.Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://mp.baomidou.com/guide/sequence.html#spring-boot
