### ISSUE TITLE
online表单开发生成本地vue代码中，自定义树控件没有加载

### ISSUE THREAD

**Issue by blackbk** [zhangdaiscott/jeecg-boot#921]
##### 问题描述：

使用online表单开发生成代码到本地后列表页和编辑页内的的自定义树控件没有生效。但是使用online表单的功能测试页进行测试，树控件表现又是正常的。请问这是bug，还是开源免费版本的功能阉割？

##### 截图&代码：

生成的本地vue代码无法加载自定义树控件：
![image](https://user-images.githubusercontent.com/36270085/74446311-a8b80980-4eb2-11ea-9eba-b5df12e9a779.png)
![image](https://user-images.githubusercontent.com/36270085/74446315-ac4b9080-4eb2-11ea-9da4-a51ac95146ae.png)

在线online表单测试地址页可以正常加载自定义树控件：
![image](https://user-images.githubusercontent.com/36270085/74446321-aeadea80-4eb2-11ea-8e47-7405e2555bf4.png)
![image](https://user-images.githubusercontent.com/36270085/74446326-b1104480-4eb2-11ea-9b0d-caea6d16ddaa.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
还未支持树控件的生成
