### ISSUE TITLE
online表单中js增强中form中show()方法不识别that

### ISSUE THREAD

**Issue by ggi2003** [zhangdaiscott/jeecg-boot#922]
##### 版本号：
2.1.3

##### 问题描述：
online表单中js增强中form中show()方法不识别that

##### 截图&代码：
![image](https://user-images.githubusercontent.com/16665184/74587670-b5626c00-5030-11ea-8310-ed019fb57b26.png)
![image](https://user-images.githubusercontent.com/16665184/74587690-f0fd3600-5030-11ea-925d-edefa3370cd2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
确实存在问题，已安排

**Comment by zhangdaiscott** [comment]
已经解决，得下个版本发布
