### ISSUE TITLE
新建Module的单元测试问题

### ISSUE THREAD

**Issue by baogang** [zhangdaiscott/jeecg-boot#923]
##### 问题描述：
按照文档(https://my.oschina.net/u/3903209/blog/3083399?tdsourcetag=s_pctim_aiomsg)新建了一个自定义的Module。现需求在此项目中对开发的代码做单元测试(比如Service)，但是在增加了如下代码后，单元测试类不能启动。请问有什么方式对自开发的Module做单元测试，仅仅依赖的本Module的Spring上下文。

##### 截图&代码：

`
package org.jeecg;
@RunWith(SpringRunner.class)
@SpringBootTest()
public class MyTest {

    @Resource
    private HelloService helloService;

    @Test
    public void helloTest() {
        System.out.println("helloService: " + helloService);
    }
}
`

**Comment by zhangdaiscott** [comment]
你想单独启动，哪这个子模块就需要有springboot的相关配置文件。
你可以单独创建一个项目，把配置放进去，然后你这个子项目再反过来引用这个含配置的项目
