### ISSUE TITLE
新版文档图片挂掉了

### ISSUE THREAD

**Issue by zhourenfei17** [zhangdaiscott/jeecg-boot#924]
##### 版本号：
2.1.3

##### 问题描述：
新版本开发文档中的工作流模块很多图都挂掉了

##### 截图&代码：
文档地址：http://doc.jeecg.com/1437901

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此部分不开源，暂时图片不提供
