### ISSUE TITLE
菜单栏想要取消首页

### ISSUE THREAD

**Issue by fatemimipang** [zhangdaiscott/jeecg-boot#926]
##### 截图&代码：不知道如何取消菜单栏的首页,没找到.  在login.vue页面发现可指定登录完成之后跳转路由.

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
首页代码可以搜/dashboard/analysis

制定打开新页面可以改下面的图

![image](https://user-images.githubusercontent.com/3162115/74635195-794e1900-51a0-11ea-9928-0d95fc6cb1fc.png)
