### ISSUE TITLE
AUTO在线报表，配置参数后导出报错

### ISSUE THREAD

**Issue by liuyang94b** [zhangdaiscott/jeecg-boot#927]
##### 问题描述：
AUTO在线报表，如果online配置中有配置参数，导出的时候会报错
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51153073/74640530-aacbe200-51aa-11ea-916c-6ea96e8b40e1.png)
![image](https://user-images.githubusercontent.com/51153073/74640580-bcad8500-51aa-11ea-9bed-1bedceffdbdb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
功能测试是好的吗

**Comment by zhangdaiscott** [comment]
你配置了参数，得给传递参数啊，不然查询不出数据

**Comment by zhangdaiscott** [comment]
经过验证的确存在问题，我们尽快修复

**Comment by liuyang94b** [comment]
是考虑合着下个版本一起更新吗？还是修复了就先提交上来呢。届时麻烦回复我一下哈。感谢~

**Comment by zhangdaiscott** [comment]
已经解决，得下个版本发布
