### ISSUE TITLE
大屏设计模块，报表展示的行全部叠加在一起

### ISSUE THREAD

**Issue by Kecin-Chen** [zhangdaiscott/jeecg-boot#930]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/30857278/74717093-b8e13780-526a-11ea-8dc3-deab1d4bccff.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
没明白

**Comment by Kecin-Chen** [comment]
上面的这种


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JEECG开源社区"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 下午5:16
收件人:&nbsp;"zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;;
抄送:&nbsp;"凌☆风"<984187490@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-boot] 大屏设计模块，报表展示的行全部叠加在一起 (#930)




没明白
