### ISSUE TITLE
关于项目加强安全性的一些建议

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#931]
##### 版本号：
2.1.3

##### 问题描述：
感觉这个框架后端基本不考虑安全性的问题，一些基本的安全性，像登陆的时候密码、短信验证码都没有防暴力破解（图片验证码放前端生成基本就像个摆设），短信也没有防恶意发送，更主要的问题是后台一些敏感接口全都没有加权限控制，像我用一个普通账号的token就能改了任何人的密码，能调够用服务器和redis监控的接口。
之前在群里提过，大佬们给的回复大概是说权限这个东西你自己去配，但不是所有用这个框架的人都有这个安全意识，有这个意识也有可能因为对功能不熟悉造成一些遗漏，所以肯定会有些用jeecg的项目会有一些权限上的安全性问题。
像我这边每次用新的版本搭项目时，都要把安全性的东西改一遍，至少密码、验证码加上错几次锁定，然后把所有系统类的Controller不管3721全都加上admin的权限限制，用到哪个的时候再放开哪个。
纯属吐糟，这些也不算是bug，但是觉得如果这些完善一下的话会更给这个项目加分，至少可以在文档上单独给出一些上线生产时候的安全提醒吧。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44466941/74827050-a8eb5580-5347-11ea-97ca-0e03c99455dc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
1、敏感操作我们本地都加了 @RequiresRoles({"admin"}) ，开源版本去掉了，因为总有人不会问没有权限事情，所以放开了 方便大家自己灵活控制。
2、验证码是个问题，已经改了，下个版本发布
3、拼写错误也该了，下个版本发布
5、短信有5分钟有效控制

**Comment by zhanjunfeng** [comment]
> 1、敏感操作我们本地都加了 @RequiresRoles({"admin"}) ，开源版本去掉了，因为总有人不会用，问没有权限事情，所以放开了 方便大家自己灵活控制。
> 2、验证码是个问题，已经改了，下个版本发布
> 3、拼写错误也该了，下个版本发布
> 5、短信有5分钟有效控制

我说的短信是指没有防暴力破解，5分钟内有效，6位数字组合，甚至有的改成4位数字，没有加错误次数的验证，甚至程序里面还有一个单独的验证手机号和验证码的接口，要想破解太容易了，基本正规的网站这种都会加上错误一定次数就限制登陆一段时间

**Comment by zhanjunfeng** [comment]
也不是一定要在代码里加上权限校验，至少可以在文档里单独把这块点出来给大家提个醒吧，像那些说权限不会用的，你还指望他们用的时候能自觉加上权限校验吗，结果就是这些人的程序就是在裸奔

**Comment by galaxist** [comment]
> 也不是一定要在代码里加上权限校验，至少可以在文档里单独把这块点出来给大家提个醒吧，像那些说权限不会用的，你还指望他们用的时候能自觉加上权限校验吗，结果就是这些人的程序就是在裸奔

这个框架能够实现基于数据库的权限配置已经足够了，毕竟这是开源框架而已，把有限精力投入到这上面不如投入到更有用的地方，开发更多的功能不是更好吗？
想下零售价1千多的win系统还不是要自己装免费安全软件甚至是购买付费安全软件的。

**Comment by www546** [comment]
JeecgSuper 插件怎么用
