### ISSUE TITLE
日志配置文件logback-spring.xml不会生效

### ISSUE THREAD

**Issue by pythonlouvre** [zhangdaiscott/jeecg-boot#933]
##### 版本号：
所有版本

##### 问题描述：
日志配置文件logback-spring.xml不会生效，修改文件中的任何配置项都不会起作用

##### 截图&代码：
建议将logback-spring.xml文件名修改为logback.xml，在包org.jeecgframework.boot.codegenerate中发现了配置文件logback.xml，此配置文件的优先级比logback-spring.xml高，只有项目中使用同名的文件，才有可能覆盖此文件中的配置。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
codegenerate 更新到最新版本
