### ISSUE TITLE
online报表不支持按照登录用户过滤数据

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#934]
##### 版本号：
2.1.3

##### 问题描述：
1、通过online开发的数据报表，谁登陆，谁能看到自己的数据，现在online无法控制。

2、因为online开发的是popup弹出框选择数据，实际业务是，业务员自己创建的客户只允许自己查

看，现在是共享的数据，数据不严谨。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59654718/74934346-f8ea1b00-5420-11ea-87ae-2e28155b1935.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已解决。得下个版本发布

**Comment by yanyapeng123** [comment]
老大，我确实找了发版说明，还未找到，请支持下下
