### ISSUE TITLE
代码已经生成的单据想通过table的方式打开

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#935]
##### 版本号：
2.1.3

##### 问题描述：
1、在上面搜索查看了这个方式https://github.com/zhangdaiscott/jeecg-boot/issues/160 
还是不行。

2、代码生成后的单据，想在点击【新增】按钮后，让自动弹框的方式打开。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59654718/74935974-3a2ffa00-5424-11ea-99ad-91ee39d1f880.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考： 常用示例->单表模型示例 按钮【创建单据】
