### ISSUE TITLE
已生成的代码，子表最下下行添加合计行底部固定问题

### ISSUE THREAD

**Issue by yanyapeng123** [zhangdaiscott/jeecg-boot#936]
##### 版本号：
2.1.3

##### 问题描述：
1、根据系统提供的案例【常见案例】-【表格合计】根据后台的代码TableTotal.vue做目标单据发现，添加的合计行不显示，而且在测试后，发现table对align: 'center' 接口失效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59654718/74936588-58e2c080-5425-11ea-8550-0701ed1d4c1e.png)

![image](https://user-images.githubusercontent.com/59654718/74936502-351f7a80-5425-11ea-8a18-a9722f4d5542.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sjlei** [comment]
【常见案例】-【表格合计】代码里写的是 `<a-table/>`，但是你使用的是 `<j-editable-table/>`，这是两个不同的组件，使用方法也完全不同。`j-editable-table`没有`align`属性，不能设置居中；合计的实现方式也不一样，考虑下个版本将该功能内置到组件里。

**Comment by zhangdaiscott** [comment]
居中未实现；合计功能已经实现，下个版本发布
