### ISSUE TITLE
字典翻译注解@Dict的字典表用法对oracle不支持

### ISSUE THREAD

**Issue by chishaohui333** [zhangdaiscott/jeecg-boot#941]
##### 问题描述：
字典翻译注解@Dict中，使用字典表翻译用法，原本会根据外键去找主表的对应字段，但是找的过程中发送的 sql 语句支持mysql，不支持oracle。具体在于mysql自定义列名是 “ as 'xxx' ”，而oracle中不能有这个单引号，正确语法应该是 “ as xxx ”

##### 截图&代码：
实体类：
         /**所属学校*/
	@Dict(dicCode = "id",dictTable = "school",dicText = "school_name")
	private Long schoolId;

异常：
        2020-02-24 13:31:26.625 [http-nio-8081-exec-4] ERROR druid.sql.Statement:149 - {conn-10004, pstmt-20015} execute error. select school_name as 'text' from school where id= ?
java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你确定你是2.1.3？ 针对oracle兼容性2.1.3已经做了处理，都用的双引号
https://github.com/zhangdaiscott/jeecg-boot/blob/v2.1.3/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/mapper/xml/SysDictMapper.xml
