### ISSUE TITLE
表单高度一直在增加

### ISSUE THREAD

**Issue by mkq229** [zhangdaiscott/jeecg-boot#942]
##### 版本号：
2.1.4

##### 问题描述：
360浏览器  急速模式
OA办公->工单申请,点击测试傻瓜入职单，弹出表单高度一直在增加   

##### 截图&代码：
![158253012](https://user-images.githubusercontent.com/22499576/75135667-40242480-571d-11ea-9fa7-b6718d3574da.jpg)

height一直在增加

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
能截图吗

**Comment by lvdandan16** [comment]
测试后未发现此问题
