### ISSUE TITLE
访问速度很慢

### ISSUE THREAD

**Issue by misureGitHub** [zhangdaiscott/jeecg-boot#943]
##### 版本号：
jeecg-boot
##### 问题描述：

http://mhaiot.com

公众号“惠仁智能”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/45928599/75136439-af027d00-571f-11ea-8ae2-ce4109e74e14.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
五、nginx 开启压缩，提高首页访问效率
https://github.com/zhangdaiscott/jeecg-boot/issues/88
