### ISSUE TITLE
如何通过j-dict-select-tag组件实现二级联动？

### ISSUE THREAD

**Issue by guoqiujing** [zhangdaiscott/jeecg-boot#945]
##### 版本号：
2.1.0

##### 问题描述：
举个例子，表单有两个下拉框，一个下拉框是选择项目，一个是选择需求，需求下拉框的值取决于项目下拉框选中的值。

##### 截图&代码：
          <j-dict-select-tag
            @change="selectProject"
            v-decorator="['projectId', validatorRules.projectName ]"
            :triggerChange="true"
            placeholder="请选择项目"
            dictCode="tb_project_info,project_name,id,project_status=1 and create_by"
          />

          <j-dict-select-tag
            v-decorator="['functionParent', {} ]"
            :triggerChange="true"
            placeholder="请选择需求"
            :dictCode="functionParentDictCode"
          />

    methods: {
      selectProject(value) {
        if (value != undefined) {
          this.functionParentDictCode = this.functionParentDictCode + " ,project_id=" + value;
          console.log(this.functionParentDictCode)
          // this.$refs.
        }
      }
   }
我本来的想法是定义需求下拉框的dictCode为变量functionParentDictCode，通过项目下拉框@change事件触发更新functionParentDictCode。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用原生的动态更改下拉option
