### ISSUE TITLE
online form表单项能否支持配置有级联关系的内容

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#948]
##### 问题描述：在online表单配置的时候,有时候需要配置有父子级联关系的内容,例如省市区,
这个时候online的配置界面上没有办法配置这种的.所以希望能否在下个版本对这种需求进行支持
(我看到有其他的issues里有说过要做个省市级联的组件,我这个需求不止是省市级联,是需要online配置的时候可以配置有级联关系的父子下拉菜单)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
下个版本会支持
