### ISSUE TITLE
结合elementui  实现 table 动态列

### ISSUE THREAD

**Issue by archorfight** [zhangdaiscott/jeecg-boot#95]
是否有计划 整合  element-ui？ 实现一些类似 table 动态列的功能

**Comment by archorfight** [comment]
https://www.iviewui.com/   是否有计划 结合这个实现table的动态列呢？

**Comment by ileadall42** [comment]
@archorfight  动态列是啥意思的功能0 0小白请教。

**Comment by zhangdaiscott** [comment]
可以细化下，有例子吗

**Comment by archorfight** [comment]
![image](https://user-images.githubusercontent.com/16200346/57352761-ec9a1780-7198-11e9-9abd-969089f00e0a.png)
https://eight1302.github.io/CRM_xbb/view/index.html    类似这种的  可以选择  table  然后展示不同的列

**Comment by zhangdaiscott** [comment]
ok 明白

**Comment by zhangdaiscott** [comment]
已经实现，下个版本，增加示例

**Comment by fly1206** [comment]
参照wiki  http://jeecg-boot.mydoc.io/   
【UI前端开发技巧--列表自定义列实现】
