### ISSUE TITLE
online表单开发，”从数据库导入表单表“功能，点击后找不到记录。

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#952]
##### 版本号：
2.1.4

##### 问题描述：
online表单开发，”从数据库导入表单表“功能，点击后找不到记录。
安装的时候，数据库名字有过更改。

##### 截图&代码：
![iss1](https://user-images.githubusercontent.com/61414528/75373705-c307d380-5905-11ea-858f-bf8df32d82cf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1275846
