### ISSUE TITLE
mysql锁表

### ISSUE THREAD

**Issue by thingworx-iot** [zhangdaiscott/jeecg-boot#953]
##### 版本号：
jeecg-boot v2
mysql5.7
##### 问题描述：

执行定时任务，导致mysql锁表.

##### 截图&代码：

![image](https://user-images.githubusercontent.com/53252892/75407174-4993d380-594d-11ea-9407-4aafb88221e1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
怎么重现？
