### ISSUE TITLE
关于密码安全性问题

### ISSUE THREAD

**Issue by shiningwhh** [zhangdaiscott/jeecg-boot#954]
##### 版本号：
2.1.4及以下

##### 问题描述：
由于加密的算法使用了PBEWithMD5AndDES，这个目前普遍被认为是不安全的一种加密方式

我们目前自行替换成了Argon2，官方是否考虑更换一下加密方式，比如Argon2, PBKDF2, scrypt, bcrypt等

另外8位的盐，虽然迭代1000次，对于某些场景依然不太安全，通常推荐32位（我们直接上了64位）。

##### 截图&代码：
pom中
```
		<dependency>
			<groupId>de.mkammerer</groupId>
			<artifactId>argon2-jvm</artifactId>
			<version>2.4</version>
		</dependency>
```

加密
`PasswordEncoder passwordEncoder=new Argon2PasswordEncoder();`

解密
```
//String passwordEncode = PasswordUtil.encrypt(user.getUsername(), user.getPassword(), salt);
PasswordEncoder passwordEncoder=new Argon2PasswordEncoder();

```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
非常感谢
