### ISSUE TITLE
@Dict 怎么选择数据源

### ISSUE THREAD

**Issue by chishaohui333** [zhangdaiscott/jeecg-boot#955]
##### 问题描述：
@Dict 怎么选择数据源，因为查询表的数据在A数据库中，但是字典数据在B数据库中，在实体类中字段加上@Dict注解后，由于表的数据是在A数据库，导致字典数据找不到，前端页面的字段也没有显示对应的字典的文本信息

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持，自己写代码实现吧
