### ISSUE TITLE
在线表单 提示 ButtonExpHandler is not defined

### ISSUE THREAD

**Issue by Itdyf** [zhangdaiscott/jeecg-boot#957]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/31603738/75516836-44f81980-5a38-11ea-8476-9af2f9c02efe.png)
![image](https://user-images.githubusercontent.com/31603738/75516877-5b05da00-5a38-11ea-9759-88017bc59df1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不在支持ES6的语法，你是要实现什么功能？

**Comment by Itdyf** [comment]
link类型 自定义按钮 我把那段代码注释就行了，那babel转es5?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 下午4:57
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "梦"<674339035@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 在线表单 提示 ButtonExpHandler is not defined (#957)




不在支持ES6的语法，你是要实现什么功能？

**Comment by zhangdaiscott** [comment]
现在是纯js，兼容IE低浏览器

提供了 表达式可以控制连接是否显示
![image](https://user-images.githubusercontent.com/3162115/75539656-95ca3b00-5a55-11ea-9266-cfc7c7b55913.png)

**Comment by Itdyf** [comment]
主要那个是那份方法没找到，未定义



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JEECG开源社区"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 晚上6:10
收件人: "zhangdaiscott/jeecg-boot"<jeecg-boot@noreply.github.com&gt;; 
抄送: "梦"<674339035@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhangdaiscott/jeecg-boot] 在线表单 提示 ButtonExpHandler is not defined (#957)




现在是纯js，兼容IE低浏览器
 
提供了 表达式可以控制连接是否显示

**Comment by zhangdaiscott** [comment]
没明白，你要实现什么功能

**Comment by zhangdaiscott** [comment]
已经解决了，更新代码吧
