### ISSUE TITLE
参照文档整合CAS存在包冲突

### ISSUE THREAD

**Issue by zc12345683** [zhangdaiscott/jeecg-boot#959]
##### 版本号：
2.1.4
##### 问题描述：
参照文档整合cas存在包依赖冲突

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27858909/75599219-bfc74000-5add-11ea-9985-cdcdb0146c43.png)

![image](https://user-images.githubusercontent.com/27858909/75599196-8e4e7480-5add-11ea-961d-e0a002798dd0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
服务端是独立的项目，不是集成到 jeecg-boot里面

**Comment by zc12345683** [comment]
谢谢，已解决
