### ISSUE TITLE
表单配置中检验字段配置href，报表中该配置字段无法看到链接 

### ISSUE THREAD

**Issue by xagpx** [zhangdaiscott/jeecg-boot#961]
##### 版本号：
2.1。4

##### 问题描述：

表单配置中检验字段配置href，报表中无法启用 
##### 截图&代码：
![image](https://user-images.githubusercontent.com/13012069/75600390-ce1b5900-5ae9-11ea-9810-55a58405458b.png)

![image](https://user-images.githubusercontent.com/13012069/75600404-dffcfc00-5ae9-11ea-8a71-5ad57bb7c1f2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此有bug，已经修复了，尽快发布
