### ISSUE TITLE
SysUserMapper.xml查询脚本数据兼容问题

### ISSUE THREAD

**Issue by liaoyongxiong** [zhangdaiscott/jeecg-boot#962]
##### 截图&代码：
Line 73（右边值双引号修改为单引号）: sys_user.del_flag = "0" 修改为 sys_user.del_flag = '0'

<img width="720" alt="截屏2020-02-29 13 07 05" src="https://user-images.githubusercontent.com/9619081/75601426-f610b980-5af5-11ea-981e-a0fd89e6bfc6.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好的，感谢

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
