### ISSUE TITLE
j-checkbox 使用方法求助帖

### ISSUE THREAD

**Issue by RhineDream** [zhangdaiscott/jeecg-boot#963]
##### 版本号：
2.1.0
##### 截图&代码：
j-checkbox 怎么能和下拉框一样直接使用字典表的字典项？

现在我是通过这样的方式
`<a-form-item 
          :labelCol="labelCol"
          :wrapperCol="wrapperCol"
          label="公司福利">
          <j-checkbox
            v-model="comWelfareOptions.values"
            :options="comWelfareOptions.options"
            dictCode="sex"
            v-decorator="['comWelfare', {}]"
          />
        </a-form-item>`

![image](https://user-images.githubusercontent.com/42332606/75609624-2df31d80-5b45-11ea-838f-3cdf5ed0162f.png)

我希望的方式：
![image](https://user-images.githubusercontent.com/42332606/75609643-6266d980-5b45-11ea-87e7-a3257f5dd0a5.png)
`<a-col :md="6" :sm="8">
              <a-form-item label="性别">
                <j-dict-select-tag v-model="queryParam.sex" placeholder="请选择性别" dictCode="sex"/>
              </a-form-item>
            </a-col>
            <a-col :md="6" :sm="8">
              <a-form-item label="选择用户">
                <j-dict-select-tag v-model="queryParam.id" placeholder="请选择用户" dictCode="demo,name,id"/>
              </a-form-item>
            </a-col>`
希望能得到解答

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by RhineDream** [comment]
<a-col :md="6" :sm="8">
              <a-form-item label="性别">
                <j-dict-select-tag v-model="queryParam.sex" placeholder="请选择性别" dictCode="sex"/>
              </a-form-item>
            </a-col>
            <a-col :md="6" :sm="8">
              <a-form-item label="选择用户">
                <j-dict-select-tag v-model="queryParam.id" placeholder="请选择用户" dictCode="demo,name,id"/>
              </a-form-item>
            </a-col>


我希望可以简便的使用字典项 或者 指定的某张表的字段

**Comment by RhineDream** [comment]
<a-col :md="6" :sm="8">
              <a-form-item label="性别">
                <j-dict-select-tag v-model="queryParam.sex" placeholder="请选择性别" dictCode="sex"/>
              </a-form-item>
            </a-col>
            <a-col :md="6" :sm="8">
              <a-form-item label="选择用户">
                <j-dict-select-tag v-model="queryParam.id" placeholder="请选择用户" dictCode="demo,name,id"/>
              </a-form-item>
            </a-col>

**Comment by RhineDream** [comment]
图片为什么放不上呢。。

**Comment by zhangdaiscott** [comment]
目前不支持，可以自己改装下
