### ISSUE TITLE
代码生成器  文件路径配置问题

### ISSUE THREAD

**Issue by MarsCircle** [zhangdaiscott/jeecg-boot#964]
##### 截图&代码：
请问报这个错该怎么改。。我都试过了都是这样
![image](https://user-images.githubusercontent.com/45489550/75612591-fb0a5300-5b5f-11ea-9ad4-6ba6d1228d3c.png)
![image](https://user-images.githubusercontent.com/45489550/75612596-05c4e800-5b60-11ea-830e-01e108e61ab0.png)
![image](https://user-images.githubusercontent.com/45489550/75612603-11b0aa00-5b60-11ea-87a8-f04bc2a9b607.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
如果GUI代码生成器改这个配置即可，如果是online在生产界面选择
