### ISSUE TITLE
JDictSelectTag 字典标签安全漏洞，会泄露全部数据

### ISSUE THREAD

**Issue by zhanjunfeng** [zhangdaiscott/jeecg-boot#965]
##### 版本号：
2.1.3

##### 问题描述：
JDictSelectTag表字典条件用法，给任意表名和两个字段，都可以查出所有数据，而且这个方法还没法限制权限。建议尽快修改，把这种条件用法去掉吧，这种写法看着就吓人。
SysDictMapper.xml里大量这种随便传表名和字段的用法，没来得及全看完，但那个JSearchSelectTag看代码也应该是一样的问题，建议能把这个里面的方法全都排查一遍

##### 截图&代码：
![3](https://user-images.githubusercontent.com/44466941/75627293-e7b3c200-5c09-11ea-8031-21fa674c5c00.png)
![2](https://user-images.githubusercontent.com/44466941/75627299-f00bfd00-5c09-11ea-8eab-0a0240ddcf08.png)
![1](https://user-images.githubusercontent.com/44466941/75627302-f306ed80-5c09-11ea-9245-6e12a169affc.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhanjunfeng** [comment]
建议没有百分百的安全上的考虑，不要写这种把table也当传入参数的方法，尤其还是封装成了前端的组件

**Comment by zhangdaiscott** [comment]
想实现这高级功能，不开放此权限是没办法的，如果有安全考虑可以自行注释掉

**Comment by qq781548819** [comment]
有什么方案设置安全权限没
