### ISSUE TITLE
excel模板导出-能否实现咨询

### ISSUE THREAD

**Issue by 15152763704** [zhangdaiscott/jeecg-boot#966]
##### 版本号：
最新版本

##### 问题描述：
在线开发的表单，需要导出空白的excel模板，导出的模板能不能设置部分字段下拉选择固定的值（字典字段），例如性别字段（导出的模板中该字段只允许用户填入 男、女 ）。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持
