### ISSUE TITLE
使用Vue/cli的现代模式打包部署后，页面加载报错

### ISSUE THREAD

**Issue by ybbwk** [zhangdaiscott/jeecg-boot#968]
##### 版本号：
2.1.4

##### 问题描述：
使用Vue/cli的现代模式打包
vue-cli-service build --modern
打包后部署后，使用Chrome/Firefox/Chromium Edge浏览器访问会卡在加载页面，console报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/522288/75760981-3335af80-5d73-11ea-952f-088f03192695.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个没试过
你可以百度，看看方案
https://www.uis.cc/2018/06/29/What-is-Modern-mode-in-the-Vue-CLI-3-configuration/
