### ISSUE TITLE
关于打包后JS文件过大，导致加载缓慢的建议

### ISSUE THREAD

**Issue by ybbwk** [zhangdaiscott/jeecg-boot#969]
##### 版本号：
2.1.4

##### 问题描述：
打包后JS文件过大，通过分析得出是online开发模块的JS体积很大，在生产环境往往不需要开发相关功能，所以去除Online开发模块可大幅降低打包后JS文件体积。

##### 截图&代码：
可将main.js中的import改为require按需加载方式
原
import '@jeecg/antd-online-214'
import '@jeecg/antd-online-214/dist/OnlineForm.css'

改为
if (process.env.NODE_ENV !== 'production') {
  require('@jeecg/antd-online-214')
  require('@jeecg/antd-online-214/dist/OnlineForm.css')
}

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
ok

**Comment by rjliulei** [comment]
并没有减小包的大小啊。。util.js里面也用了。。
