### ISSUE TITLE
Excel注解的numFormat方法似乎未实现

### ISSUE THREAD

**Issue by qzmer1104** [zhangdaiscott/jeecg-boot#970]
##### 版本号：
autopoi-web 1.0.5

##### 问题描述：
http://doc.jeecg.com/1524939

Excel注解的属性中
文档中提到的numFormat

numFormat | String | "" | 数字格式化,参数是Pattern,使用的对象是DecimalFormat

对数字的格式化处理，使用时发现，还没有实现
我看了下1.0.3和1.0.4，也没有发现实现，是否开发遗漏？？目前暂时使用convert替代中

poi项目好像没人关注，所以提到这个项目里了

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
是的，咱未实现
