### ISSUE TITLE
下拉搜索框在编辑时下拉name无法带过来

### ISSUE THREAD

**Issue by jave-joe** [zhangdaiscott/jeecg-boot#971]
##### 问题描述：

在online配置的下拉搜索框,生成的对应代码model中的标签为:`<j-search-select-tag>`
在数据上点击编辑,这个时候下拉框回填的值是实际存储值,并不是显示的值.

另外还有一个小问题,下拉框使用数据字典的话,数据字典的项的值不能有0的,如果有0的话,在新增的时候选择这个保存后,再点击编辑,这个时候下拉框回显没有值内容为空

##### 截图&代码：

`<j-search-select-tag v-decorator="['neTypeId', validatorRules.neTypeId]" dict="sys_category,name,code" />`

table列表里展示的信息如下:
![avatar](http://chuantu.xyz/t6/722/1583312688x2073530529.jpg)
这里是获取的通过系统字典翻译过来的值,即 _dictText 的值,实际存储的值是个数字,这里显示正常

点击表格最后一栏操作的"编辑"按钮,弹出框的内容为如下:
![avatar](http://chuantu.xyz/t6/722/1583312869x2073530527.jpg)
这里就有些问题了,下拉框中应该显示"MRFP",而不是具体存的值"25",这是使用j-search-select-tag时出现的问题,如果使用j-dict-select-tag的话,就没有问题,但是我这里的下来内容比较多,必须要使用j-search-select-tag这种的带搜索的下拉框

点击下拉的时候,下来内容是正常的,如下:
![avatar](http://chuantu.xyz/t6/722/1583313219x2073530527.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jave-joe** [comment]
好像是因为我的值是不是string的原因.
Invalid prop: type check failed for prop "value". Expected String with value "44", got Number with value 44
我看到2.1.4版本的升级说明里有说"改造字典标签，支持数字类型值",但是看来解决的是j-dict-select-tag而j-search-select-tag还是有这个问题

**Comment by zhangdaiscott** [comment]
请配合截图说明

**Comment by jave-joe** [comment]
> 请配合截图说明

截图已补充

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
下载附件覆盖
[JSearchSelectTag.zip](https://github.com/zhangdaiscott/jeecg-boot/files/4357890/JSearchSelectTag.zip)
