### ISSUE TITLE
online表单中添加自定义按钮无法显示

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#973]
##### 版本号：
2.1.4

##### 问题描述：
online表单中添加自定义按钮，按钮类型为link+action/js，配置好后，发现在线测试的时候无法显示，F12显示如下图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58909486/75848404-1f468800-5e1d-11ea-8878-dec0f150b3bd.png)

![image](https://user-images.githubusercontent.com/58909486/75848373-fde59c00-5e1c-11ea-978d-29a184b51fe4.png)

我测试了一下，如果按钮类型设置为button，则在导航栏能正常显示

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
把你如何配置的，详细截图步骤一下

**Comment by COMAC919** [comment]
> 把你如何配置的，详细截图步骤一下

![image](https://user-images.githubusercontent.com/58909486/75849320-89602c80-5e1f-11ea-941e-820722c19f06.png)
![image](https://user-images.githubusercontent.com/58909486/75849344-9aa93900-5e1f-11ea-8e1b-6e787c080b08.png)
![image](https://user-images.githubusercontent.com/58909486/75849431-c5938d00-5e1f-11ea-9aa5-9cbff3cec4f7.png)
![image](https://user-images.githubusercontent.com/58909486/75849440-ca584100-5e1f-11ea-8ac1-04f03b3d1d71.png)

**Comment by COMAC919** [comment]
![image](https://user-images.githubusercontent.com/58909486/75850501-6a16ce80-5e22-11ea-9951-64105636c8c5.png)

**Comment by COMAC919** [comment]
> 把你如何配置的，详细截图步骤一下能帮忙看看把，我看群里面有两个人都有这个问题了

**Comment by zhangdaiscott** [comment]
确认是bug，我们尽快修复

**Comment by zhangdaiscott** [comment]
已经解决，请更新代码
