### ISSUE TITLE
点击新增或者编辑按钮弹框宽度的设置问题

### ISSUE THREAD

**Issue by COMAC919** [zhangdaiscott/jeecg-boot#974]
##### 版本号：

2.1.4
##### 问题描述：
能否可以在线设置弹框宽度或者默认设置宽屏？这样显示很难看，还必须手动点击右上角宽屏按钮。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/58909486/75848933-92043300-5e1e-11ea-939d-d0d3b0543071.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经规划

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
