### ISSUE TITLE
用HBuilder X打包 提示 network error 无法连接登陆

### ISSUE THREAD

**Issue by baixinan** [zhangdaiscott/jeecg-boot#976]
##### 截图&代码：
![微信图片_20200304153416](https://user-images.githubusercontent.com/38303001/75855760-e9f66600-5e2d-11ea-9a0a-1139f58db471.jpg)

**Comment by baixinan** [comment]
![image](https://user-images.githubusercontent.com/38303001/75856197-ce3f8f80-5e2e-11ea-9fa9-5d09f8e0e1e6.png)
补充配置截图

**Comment by baixinan** [comment]
index.html 配置修改信息：
    window._CONFIG['domianURL'] = 'http://boot.jeecg.org/jeecg-boot';
    window._CONFIG['casPrefixUrl'] = 'http://cas.example.org:8443/cas';
    window._CONFIG['onlinePreviewDomainURL'] = 'http://boot.jeecg.org/onlinePreview'

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/75893633-17630400-5e6e-11ea-923b-e7645b028210.png)
