### ISSUE TITLE
重大问题  望解决   不属于当前角色的权限  用postman  照样可以请求到

### ISSUE THREAD

**Issue by UPMuling** [zhangdaiscott/jeecg-boot#977]
##### 问题描述：

不属于当前角色的权限    用postman    照样可以请求到数据
大家可以试试   随便那拿个角色的token  就能随便请求接口
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
权限授权控制的是前端路由，如果需要控制可以，可以再后台control加上权限注解

**Comment by wufuwei** [comment]
@zhangdaiscott 
服务器端的地址也需要根据权限控制才好。

control加上权限注解也可以请求。如：@RequiresPermissions("user:add")，按钮权限不赋予其他用户对应的角色权限，但用其他用户的token请求此@RequiresPermissions("user:add")对应的url：/sys/user/add，照样可以访问。

所以，服务器端的地址也需要根据用户具有的权限进行控制才好，要不漏洞太大了，确实是随便用登录的token都可以请求后端的restful的数据。
