### ISSUE TITLE
AutoPOI导出Excel文件。超过6000条就没反应了。

### ISSUE THREAD

**Issue by gaoqingzhi** [zhangdaiscott/jeecg-boot#978]
##### 版本号：
2.1.3

##### 问题描述：
AutoPOI导出Excel文件。超过6000条就没反应了。

##### 截图&代码：
系统封装的代码，没动过
![image](https://user-images.githubusercontent.com/35336553/75939307-c16d7b00-5ec4-11ea-8cd2-6ef4e7bff842.png)

**Comment by zhangdaiscott** [comment]
直接访问导出数据接口，试试
看看卡在后台还是前台

**Comment by gaoqingzhi** [comment]
> 直接访问导出数据接口，试试
> 看看卡在后台还是前台

**Comment by gaoqingzhi** [comment]
> 直接访问导出数据接口，试试
> 看看卡在后台还是前台


好像是后台list(querywarper)查询慢。

**Comment by gaoqingzhi** [comment]
问题解决！跟字典表有关！
	@Excel(name = "用户姓名", width = 15,dictTable = "xiaoqu_user",dicCode = "id",dicText = "username")
我这存的人员id , 导出的时候查询 人员姓名导出。 人员表数据量也挺大，导致查询速度慢，网络超时。

**Comment by zhangdaiscott** [comment]
hao
