### ISSUE TITLE
表单无法提交

### ISSUE THREAD

**Issue by jiangjiacheng** [zhangdaiscott/jeecg-boot#979]
##### 版本号：
2.1.3

##### 问题描述：
进入用户列表-->编辑-->弹出对话框后，状态下拉框显示黄色感叹号，并且字典没有翻译-->表单提交没反应

##### 截图&代码：

![image](https://user-images.githubusercontent.com/22400199/75945051-28466080-5ed4-11ea-811c-f084ce035517.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个是模板，不是功能
