### ISSUE TITLE
online模块找不到资源

### ISSUE THREAD

**Issue by kingchengzdm** [zhangdaiscott/jeecg-boot#980]
##### 版本号：
2.1.4

##### 问题描述：
目前修改了包名，以及context-path，我查看了node_modules下@jeecg/antd-onine-214下的OnlineForm.umd.min.js已经没有jeecg-boot了，打开页面请求的地址也是我自定义的context-path，但还会出现404

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19925479/75964783-c94c1000-5f02-11ea-94ce-65f914998bf3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://bbs.jeecg.com/forum.php?mod=viewthread&tid=7816&page=1&extra=#pid21237
5
