### ISSUE TITLE
Excel导入问题

### ISSUE THREAD

**Issue by gelinagg** [zhangdaiscott/jeecg-boot#983]
##### 问题描述：
Excel导入如果是excel导入第一列为空的话，系统捕捉不到这个行记录。
代码生成器生成代码见下：
ExcelImportUtil.importExcel这个方法会过滤掉这行记录。。
org.jeecgframework.poi.excel;框架是1.03

##### 截图&代码：

List<BdUnit> listBdUnits = ExcelImportUtil.importExcel(file.getInputStream(), BdUnit.class, params);
ExcelOperateUtil.removeWrongCharAtStringLast(listBdUnits, new BdUnit());

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以按照你的格式要求，修改导入代码那块针对的行号
![image](https://user-images.githubusercontent.com/3162115/76048163-f995bc00-5f9f-11ea-972c-4adb47b829c7.png)

**Comment by gelinagg** [comment]
excel导入我们的需求：
1.必输字段为空，要求导不进去，提示excel哪行出了问题。
2.字段唯一性校验：excel中字段唯一性校验，excel与现有数据库中字段唯一性校验
3.参照校验：excel导入的字段是其他表的参照的，需要校验其他表中对应的字段是否有这个导入的内容。

**Comment by gelinagg** [comment]
我们用了这个注解
	@ExcelVerify(isMobile = true, notNull = true)
挺好，但是ExcelVerify这个类是封装的，字段太少，是否可以字段自定义，比如校验编码是否为空，就不好用
