### ISSUE TITLE
JEditableTable 用 slot的形式绑定一个JTreeSelect 如何实现双向绑定

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#984]
##### 版本号：

2.1.0
##### 问题描述：

希望在JEditableTable 的一个列里使用tree形式作为选择项，请教一下如何实现，目前使用slot的形式实现 但无法双向绑定 
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/76058623-e2fb5f00-5fb7-11ea-8724-568d2cc20d21.png)

![image](https://user-images.githubusercontent.com/52776371/76058578-c9f2ae00-5fb7-11ea-9b93-2ba13cb39ee9.png)

**Comment by he0128** [comment]
补充部分代码
<j-editable-table
            :ref="refKeys[0]"
            :loading="cameraTable.loading"
            :columns="cameraTable.columns"
            :dataSource="cameraTable.dataSource"
            :maxHeight="300"
            :rowNumber="true"
            :rowSelection="disableSubmit==false"
            :actionButton="disableSubmit==false"
            :disabled="disableSubmit"
          >
            <template v-slot:depositSite="props">
              <select-address v-bind="props.column"
              v-model="props.column"
               :trigger-change="true" />
            </template>
          </j-editable-table>
        </a-tab-pane>

**Comment by zhangdaiscott** [comment]
新行编辑即将出，可方便自定义组件

**Comment by CodeFly16** [comment]
请问解决了吗 我也遇到了这一个问题   https://github.com/zhangdaiscott/jeecg-boot/issues/1616

**Comment by guaicaiboshi** [comment]
> 请问解决了吗 我也遇到了这一个问题 #1616

我也遇到这个问题，请问解决了吗？
