### ISSUE TITLE
online表单，菜单配置“是否路由菜单”为否时，页面title显示不正确

### ISSUE THREAD

**Issue by rlecir** [zhangdaiscott/jeecg-boot#987]
##### 版本号：
2.1.4

##### 问题描述：
online表单title显示不正确，都显示成《AUTO在线表单》
试过将《是否路由菜单》改为是，title正常显示只是功能不起作用。

##### 截图&代码：

![Uploading image.png…]()

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
配置菜单，通过菜单访问，名字就是菜单名
