### ISSUE TITLE
【在线开发】【从数据库导入表单】时无法搜索数据库表

### ISSUE THREAD

**Issue by allmylove521** [zhangdaiscott/jeecg-boot#990]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/5745312/76144144-6d2aec80-60b8-11ea-8ca9-757ca8dae30e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
配置代码生成器的数据库
http://doc.jeecg.com/1275846

**Comment by Protector-001** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/33e2fe77-9830-4a6c-a93a-735fc61d5192)
![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/5fd81bf0-be27-4326-bf60-3d8e230e91dc)
jar包部署，config问价夹下已经配置代码生成器的数据库，但是列表也不显示
