### ISSUE TITLE
nginx部署后druid监控页面无法打开

### ISSUE THREAD

**Issue by ABoat365** [zhangdaiscott/jeecg-boot#996]
##### 版本号：
2.1.3

##### 问题描述：
nginx部署后druid监控页面无法打开。查看连接302跳转到127.0.0.1，并且未带端口。

##### 截图&代码：

![1583806881(1)](https://user-images.githubusercontent.com/34494887/76273637-51daff80-62b9-11ea-899d-e7507e563751.jpg)
![1583806981(1)](https://user-images.githubusercontent.com/34494887/76273646-54d5f000-62b9-11ea-8b05-37fe4b355260.jpg)
![1583807003(1)](https://user-images.githubusercontent.com/34494887/76273653-58697700-62b9-11ea-9cdf-09e24e866bf4.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
index.xml 页面后台访问地址没改把

**Comment by ABoat365** [comment]
> index.xml页面后台访问地址没改把

index.xml，这个文件在哪里？

**Comment by ABoat365** [comment]
> index.xml 页面后台访问地址没改把

前端项目中public\index.html中的 domianURL改了，不然系统其它功能也不能访问。现在只有druid监控页面无法打开。如果不用nginx代理，直接访问后端服务，druid监控页面是可以打开的。

**Comment by ABoat365** [comment]
@zhangdaiscott 前端项目中public\index.html中的 domianURL改了，不然系统其它功能也不能访问。现在只有druid监控页面无法打开。如果不用nginx代理，直接访问后端服务，druid监控页面是可以打开的。

**Comment by zhangdaiscott** [comment]
应该是你配置问题，我们演示环境也是Nginx分发的，没有问题

**Comment by ABoat365** [comment]
@zhangdaiscott 找到问题了，是[官方文档](http://doc.jeecg.com/1273922)中nginx配置有误。

**Comment by Nicky213Zhang** [comment]
> @zhangdaiscott 找到问题了，是[官方文档](http://doc.jeecg.com/1273922)中nginx配置有误。

偶然也发现这个问题了，虽然这个模块不长用到，但是还想请教下，nginx哪边配置需要调整

**Comment by ABoat365** [comment]
@Nicky213Zhang 
以下是官方文档中nginx的配置：
```
server {
		listen       80;
		server_name  你的域名;

		#后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问		
		location ^~ /jeecg-boot {
			proxy_pass              http://127.0.0.1:8080/jeecg-boot/;
			proxy_set_header        Host 127.0.0.1;
			proxy_set_header        X-Real-IP $remote_addr;
			proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		#解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
		location / {
			root   html;
			index  index.html index.htm;
			if (!-e $request_filename) {
				rewrite ^(.*)$ /index.html?s=$1 last;
				break;
			}
		}
	}
```

我把jeecg-boot部分修改成了以下：
```
location /jeecg-boot/ {
    proxy_pass    http://127.0.0.1:8080/jeecg-boot/;
    proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto    $scheme;
    proxy_set_header    X-Forwarded-Port    $server_port;
}
```
你可以试试。除此之外还加了websocket协议升级，不然websocke经过nginx无法连接，这里就不贴了，检索一下就知道了。
