### ISSUE TITLE
一个主表，多个付表。1对多。保存后，某些从表行项目内容保存成功，单重新打开数据表现丢失。

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#997]
##### 版本号：
2.1.4

##### 问题描述：
1、有些从表填写行项目内容的时候，保存成功。
2、重新打开编辑，第一个从表内容在页面还可以看到。
3、但后面有些从表，在页面发现数据丢失，但数据库表（直接查看数据库物理biao）有内容，但外键中的关联主表名、主表字段中的内容为：UUID4个字符；而不是真正的UUID36位字符串。
第一个从表的UUID内容是正常的。

##### 截图&代码：
主表名
主表字段
![image](https://user-images.githubusercontent.com/61414528/76351048-c3fa2580-6347-11ea-8e61-2341871babcf.png)
![image](https://user-images.githubusercontent.com/61414528/76351072-d07e7e00-6347-11ea-9aa9-717bfd69c89c.png)
下面这个是正常的：
![image](https://user-images.githubusercontent.com/61414528/76351174-fa37a500-6347-11ea-9c14-ae19cf653b02.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
有重新步骤吗或者录个视频

**Comment by bill74s** [comment]
您操作的是3个以内的从表，还是达到5个？

**Comment by bill74s** [comment]
感觉不是从表个数的问题。而是自动删除数据！
![image](https://user-images.githubusercontent.com/61414528/76388039-1d437280-63a3-11ea-8bae-cc5199113dde.png)
另外如果从表文件名长，多个加起来是否有关系？字段长度

**Comment by 553036892** [comment]
好像是JEditableTable的数据每行前台不是会自动生成id嘛，这个id回传到后台，导致后台的id不是空的，就没重新生成id，也遇到过

**Comment by zhangdaiscott** [comment]
怎么重现呢？

**Comment by bill74s** [comment]
这个bug应该比较大了。试想下如果很多业务数据，整个清掉，想想有点恐怖。为什么有删除语句呢？

**Comment by bill74s** [comment]
id弄上了，但只保留id(uuid)的值，但把其他字段进行清零了。所有记录
![image](https://user-images.githubusercontent.com/61414528/76404967-5fc87780-63c2-11ea-87d7-298b855a9486.png)

**Comment by bill74s** [comment]
原来是这样的：
1、2个从表。一个A从表2行，一个B从表1行记录。


![image](https://user-images.githubusercontent.com/61414528/76406078-23961680-63c4-11ea-9c4b-420f71682009.png)
2、现在编辑A从表，保存。
3、A和B的记录数进行交换。
![image](https://user-images.githubusercontent.com/61414528/76406134-30b30580-63c4-11ea-87c0-06708d9e02a6.png)

**Comment by bill74s** [comment]
1前面：
![image](https://user-images.githubusercontent.com/61414528/76406474-bafb6980-63c4-11ea-9249-8dbbcdc7a1a0.png)
2：修改一个表
![image](https://user-images.githubusercontent.com/61414528/76406556-e1210980-63c4-11ea-9100-dfdff08e9e06.png)
3：数据交换了（两个从表之间）
![image](https://user-images.githubusercontent.com/61414528/76406670-12013e80-63c5-11ea-9ca3-37b077f978eb.png)

**Comment by zhangdaiscott** [comment]
这是你自己写的代码还是用的online？还是生成的代码

**Comment by bill74s** [comment]
online

**Comment by zhangdaiscott** [comment]
已经重新 子表数据串位问题，下个版本修复
