### ISSUE TITLE
某些online页面导出xls文件异常

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#998]
##### 版本号：

2.1.4
##### 问题描述：
某些online页面导出xls文件异常。该表有上传的图片路径
![image](https://user-images.githubusercontent.com/61414528/76351678-d6289380-6348-11ea-90dc-1c8ddda5babc.png)

##### 截图&代码：
{"success":false,"message":"鎿嶄綔澶辫触锛孍xcel瀵煎嚭閿欒","code":500,"result":null,"timestamp":1583868506169}

![image](https://user-images.githubusercontent.com/61414528/76351369-4e428980-6348-11ea-8a75-795624f09fd5.png)
![image](https://user-images.githubusercontent.com/61414528/76351458-7631ed00-6348-11ea-9e87-bd216683514e.png)
![image](https://user-images.githubusercontent.com/61414528/76351575-a2e60480-6348-11ea-8178-493da845a233.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by bill74s** [comment]
已经验证，列表有时间字段的时候会出现该问题，隐藏时间字段正常

**Comment by zhangdaiscott** [comment]
单表还是一对多，我这边测试导出无问题
![image](https://user-images.githubusercontent.com/3162115/76375513-f8d69e80-6380-11ea-886b-03008a0049de.png)

**Comment by zhangdaiscott** [comment]
你看看后台报错没有，把错误发出来

**Comment by bill74s** [comment]
![image](https://user-images.githubusercontent.com/61414528/76380273-51139d80-638d-11ea-8020-334451b802fa.png)

**Comment by bill74s** [comment]
![image](https://user-images.githubusercontent.com/61414528/76380317-6dafd580-638d-11ea-8d2b-87e3951fac5d.png)

**Comment by bill74s** [comment]
![image](https://user-images.githubusercontent.com/61414528/76380524-f6c70c80-638d-11ea-9615-b23f780621df.png)
找到原因，如果为日期，但字段类型不为date 的时候出问题。
