### ISSUE TITLE
online增强SQL变量取数为null,#{sys.sys_date} 还有#{sys.sys_time} 

### ISSUE THREAD

**Issue by bill74s** [zhangdaiscott/jeecg-boot#999]
##### 版本号：
2.1.4

##### 问题描述：
![image](https://user-images.githubusercontent.com/61414528/76352490-176d7300-634a-11ea-9d09-a8281473c657.png)
上图 sql增强语句正常。
但x下图的 sql语句中，按照帮助写法取数为null，正确写法应该是？

#{sys.sys_date} | 系统日期"yyyy-MM-dd"
#{sys.sys_time} | 系统时间"yyyy-MM-dd HH:mm"

##### 截图&代码：

![image](https://user-images.githubusercontent.com/61414528/76352612-4daaf280-634a-11ea-9768-b60d707bd87f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
得新版发布才好使，现在还不支持
